ALTER TABLE corp_etl_complaints_incidents
DROP COLUMN followup_flag;

ALTER TABLE CORP_ETL_COMPL_INCIDENTS_OLTP
DROP COLUMN followup_flag;

ALTER TABLE CORP_ETL_COMPL_INCIDN_WIP_BPM
DROP COLUMN followup_flag;

ALTER TABLE d_complaint_current
DROP COLUMN followup_flag;

create or replace view D_COMPLAINT_CURRENT_SV as
select * from D_COMPLAINT_CURRENT
with read only;

drop index IX_COMPLAINTS_INS_STATUS2;
drop index IX_COMPLAINTS_FOLLOWUP2 ;
drop index IX_COMPLAINTS_FORWARDED_TO2;
drop index IX_COMPLAINTS_INCIDENT_ID2;
drop index IX_COMPLAINTS_FOLLOWUP3;
drop index IX_COMPLAINTS_FORWARDED_TO3;

create index IX_COMPLAINTS_INCIDENT_ID2 on CORP_ETL_COMPL_INCIDENTS_OLTP(INCIDENT_ID,MAX_INCI_STAT_HIST_ID)
tablespace MAXDAT_INDX;