CREATE OR REPLACE FORCE VIEW D_SUBPROGRAM_CON_XWALK_SV AS
SELECT PROGRAM_CON_XWALK_CODE
,DESCRIPTION
,REPORT_LABEL
,LMDEF_ID LETTER_DEFINITION_ID
,SUBPROGRAM_CODE
,CON_STATUS_CODE
,CON_UPDATE_CODE
,EFFECTIVE_DATE
,END_DATE
FROM D_SUBPROGRAM_CON_XWALK;
grant select on D_SUBPROGRAM_CON_XWALK_SV to MAXDAT_MITRAN_OLTP_SIU;
grant select on D_SUBPROGRAM_CON_XWALK_SV to MAXDAT_MITRAN_OLTP_SIUD;
grant select on D_SUBPROGRAM_CON_XWALK_SV to MAXDAT_MITRAN_READ_ONLY;


