--------------------------------------------------------
--  DDL for Index CASES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CASES_PK" ON "EMRS_D_CASE" ("CASE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_INDX" ;

  CREATE INDEX IDX1_CASENUM_PROGRAM ON EMRS_D_CASE(source_record_id, managed_care_program) TABLESPACE MAXDAT_INDX; 
  CREATE INDEX IDX2_CASENUM ON EMRS_D_CASE(CASE_NUMBER) TABLESPACE MAXDAT_INDX;
