--------------------------------------------------------
--  DDL for Index CHGREASON_PLAN_REASON_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHGREASON_PLAN_REASON_UK" ON "EMRS_D_CHANGE_REASON" ("CHANGE_REASON_CODE", "CHANGE_REASON_CODE_PLAN", "MANAGED_CARE_PROGRAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_INDX" ;
