
  CREATE TABLE "EMRS_S_CASE_STG" 
   (	"CASE_ID" NUMBER(*,0), 
	"MANAGED_CARE_PROGRAM" VARCHAR2(50), 
	"CASE_NUMBER" NUMBER(22,0), 
	"CSDA_CODE" VARCHAR2(32), 
	"FIRST_NAME" VARCHAR2(30), 
	"MIDDLE_INITIAL" VARCHAR2(1), 
	"LAST_NAME" VARCHAR2(30), 
	"FULL_NAME" VARCHAR2(80), 
	"PHONE" VARCHAR2(10), 
	"MAILING_ADDRESS1" VARCHAR2(55), 
	"MAILING_ADDRESS2" VARCHAR2(55), 
	"MAILING_CITY" VARCHAR2(30), 
	"MAILING_STATE" VARCHAR2(2), 
	"MAILING_ZIP" VARCHAR2(9), 
	"CASE_SEARCH_ELEMENT" VARCHAR2(9), 
	"GUARDIAN_FULL_NAME" VARCHAR2(80), 
	"RECORD_DATE" DATE, 
	"RECORD_TIME" VARCHAR2(5), 
	"RECORD_NAME" VARCHAR2(80), 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_TIME" VARCHAR2(5), 
	"MODIFIED_NAME" VARCHAR2(80), 
	"VERSION" NUMBER(*,0), 
	"SOURCE_RECORD_ID" NUMBER(18,0), 
	"CURRENT_CASE_ID" NUMBER(18,0), 
	"FAMILY_NUMBER" NUMBER(18,0), 
	"CASE_STATUS_DATE" DATE, 
	"CASE_EDUCATED_IND" VARCHAR2(1), 
	"CASE_EDUCATED_DATE" DATE, 
	"CASE_NEED_TRANSLATOR_IND" VARCHAR2(1), 
	"CASE_PHONE_REMINDER_USE" VARCHAR2(1), 
	"CASE_EDUCATED_BY" VARCHAR2(40), 
	"CASE_STAFF_ID" NUMBER(18,0), 
	"CASE_LANGUAGE_CD" VARCHAR2(32), 
	"CASE_HOW_EDUCATED_CD" VARCHAR2(32), 
	"CASE_STATUS" VARCHAR2(2), 
	"CASE_HEAD_SSN" VARCHAR2(30), 
	"CASE_TEAM" VARCHAR2(1), 
	"CASE_LOAD" NUMBER(6,0), 
	"CLNT_CLIENT_ID" NUMBER(18,0), 
	"FMNB_ID" NUMBER(18,0), 
	"LOAD_TYPE" VARCHAR2(32), 
	"CASE_SPOKEN_LANGUAGE_CD" VARCHAR2(32), 
	"NOTE_REF_ID" NUMBER(18,0), 
	"ANNIVERSARY_DT" DATE, 
	"STATE_STAFF_ID_EXT" VARCHAR2(32), 
	"CASE_GENERIC_FIELD1_DATE" DATE, 
	"CASE_GENERIC_FIELD2_DATE" DATE, 
	"CASE_GENERIC_FIELD3_NUM" NUMBER(18,0), 
	"CASE_GENERIC_FIELD4_NUM" NUMBER(18,0), 
	"CASE_GENERIC_FIELD5_TXT" VARCHAR2(256), 
	"CASE_GENERIC_FIELD6_TXT" VARCHAR2(256), 
	"CASE_GENERIC_FIELD7_TXT" VARCHAR2(256), 
	"CASE_GENERIC_FIELD8_TXT" VARCHAR2(256), 
	"CASE_GENERIC_FIELD9_TXT" VARCHAR2(256), 
	"CASE_GENERIC_FIELD10_TXT" VARCHAR2(256), 
	"CASE_GENERIC_REF11_ID" NUMBER(18,0), 
	"CASE_GENERIC_REF12_ID" NUMBER(18,0), 
	"LAST_STATE_UPDATE_TS" DATE, 
	"LAST_STATE_UPDATED_BY" NUMBER(18,0), 
	"CASE_CIN" VARCHAR2(30), 
	"RECORD_STATUS" VARCHAR2(30), 
	"UPD_CASE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_DATA" ;
  
--------------------------------------------------------
--  DDL for Index CASESTG
--------------------------------------------------------

  CREATE INDEX "IDX1_CASESTG" ON "EMRS_S_CASE_STG" ("CASE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_INDX" ;

  CREATE INDEX "IDX2_CASESTG" ON "EMRS_S_CASE_STG" ("RECORD_STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_INDX" ;
  
  CREATE OR REPLACE PUBLIC SYNONYM EMRS_S_CASE_STG FOR EMRS_S_CASE_STG;