--------------------------------------------------------
--  Constraints for Table EMRS_F_COMMUNICATION
--------------------------------------------------------

  ALTER TABLE "EMRS_F_COMMUNICATION" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_COMMUNICATION" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_COMMUNICATION" MODIFY ("TIME_PERIOD_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_COMMUNICATION" MODIFY ("STAFF_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_COMMUNICATION" MODIFY ("PROGRAM_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_COMMUNICATION" MODIFY ("LANGUAGE_CODE_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_COMMUNICATION" MODIFY ("DATE_PERIOD_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_COMMUNICATION" MODIFY ("COUNTY_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_COMMUNICATION" MODIFY ("CONTACT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_COMMUNICATION" MODIFY ("COMMUNICATION_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_COMMUNICATION" MODIFY ("COMMUNICATION_STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_COMMUNICATION" MODIFY ("COMMUNICATION_ACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_COMMUNICATION" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_COMMUNICATION" MODIFY ("CASE_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_COMMUNICATION" MODIFY ("BIZCHANL_CHANNEL_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_COMMUNICATION" MODIFY ("COMMUNICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_COMMUNICATION" ADD CONSTRAINT "COMMU_PK" PRIMARY KEY ("COMMUNICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MAXDAT_INDX"  ENABLE;
