--------------------------------------------------------
--  DDL for Table EMRS_D_ENROLLMENT_ACTION_STATU
--------------------------------------------------------

  CREATE TABLE "EMRS_D_ENROLLMENT_ACTION_STATU" 
   (	"ENROLLMENT_ACTION_STATUS_ID" NUMBER(*,0), 
	"MANAGED_CARE_PROGRAM" VARCHAR2(50), 
	"ENROLLMENT_ACTION_STATUS_CODE" VARCHAR2(80), 
	"ENROLLMENT_ACTION_STATUS_CODE_" VARCHAR2(500), 
	"SOURCE_RECORD_ID" NUMBER(22,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_DATA" ;

   COMMENT ON COLUMN "EMRS_D_ENROLLMENT_ACTION_STATU"."ENROLLMENT_ACTION_STATUS_ID" IS 'Enrollment Status ID (PK)';
   COMMENT ON COLUMN "EMRS_D_ENROLLMENT_ACTION_STATU"."MANAGED_CARE_PROGRAM" IS 'Managed Care Program that Uses This CSDA';
   COMMENT ON COLUMN "EMRS_D_ENROLLMENT_ACTION_STATU"."ENROLLMENT_ACTION_STATUS_CODE" IS 'Enrollment Status Code';
   COMMENT ON COLUMN "EMRS_D_ENROLLMENT_ACTION_STATU"."ENROLLMENT_ACTION_STATUS_CODE_" IS 'Enrollment Status Description';
