--------------------------------------------------------
--  Constraints for Table EMRS_D_OTHER_CHIP_CODE
--------------------------------------------------------

  ALTER TABLE "EMRS_D_OTHER_CHIP_CODE" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "EMRS_D_OTHER_CHIP_CODE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "EMRS_D_OTHER_CHIP_CODE" MODIFY ("MANAGED_CARE_PROGRAM" NOT NULL ENABLE);
  ALTER TABLE "EMRS_D_OTHER_CHIP_CODE" MODIFY ("OTHER_CHIP_CODE_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "EMRS_D_OTHER_CHIP_CODE" MODIFY ("OTHER_CHIP_CODE" NOT NULL ENABLE);
  ALTER TABLE "EMRS_D_OTHER_CHIP_CODE" MODIFY ("OTHER_CHIP_CODE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "EMRS_D_OTHER_CHIP_CODE" MODIFY ("OTHER_CHIP_CODE_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_D_OTHER_CHIP_CODE" ADD CONSTRAINT "OTHERCHIP_TYPE_UK" UNIQUE ("OTHER_CHIP_CODE_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MAXDAT_INDX"  ENABLE;
  ALTER TABLE "EMRS_D_OTHER_CHIP_CODE" ADD CONSTRAINT "OTHERCHIP_CODE_UK" UNIQUE ("OTHER_CHIP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MAXDAT_INDX"  ENABLE;
  ALTER TABLE "EMRS_D_OTHER_CHIP_CODE" ADD CONSTRAINT "OTHERCHIP_PK" PRIMARY KEY ("OTHER_CHIP_CODE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MAXDAT_INDX"  ENABLE;
