--------------------------------------------------------
--  Constraints for Table EMRS_F_ORCH_SELECTED_TARGET
--------------------------------------------------------

  ALTER TABLE "EMRS_F_ORCH_SELECTED_TARGET" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_ORCH_SELECTED_TARGET" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_ORCH_SELECTED_TARGET" MODIFY ("NUMBER_COUNT" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_ORCH_SELECTED_TARGET" MODIFY ("TARGET_GROUP_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_ORCH_SELECTED_TARGET" MODIFY ("TARGET_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_ORCH_SELECTED_TARGET" MODIFY ("TARGET_ACTIVITY_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_ORCH_SELECTED_TARGET" MODIFY ("SCHOOL_DISTRICT_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_ORCH_SELECTED_TARGET" MODIFY ("HEADSTART_GRANTEE_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_ORCH_SELECTED_TARGET" MODIFY ("CSDA_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_ORCH_SELECTED_TARGET" MODIFY ("COUNTY_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_ORCH_SELECTED_TARGET" MODIFY ("ACTION_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_ORCH_SELECTED_TARGET" MODIFY ("OUTREACH_SELECTED_TARGET_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_F_ORCH_SELECTED_TARGET" ADD CONSTRAINT "OUTSELTRG_ORCH_SEL_TGT_UK" UNIQUE ("TARGET_ACTIVITY_ID", "TARGET_GROUP_ID", "TARGET_GROUP_TYPE_ID", "SCHOOL_DISTRICT_ID", "COUNTY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MAXDAT_INDX"  ENABLE;
  ALTER TABLE "EMRS_F_ORCH_SELECTED_TARGET" ADD CONSTRAINT "OUTSELTRG_PK" PRIMARY KEY ("OUTREACH_SELECTED_TARGET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MAXDAT_INDX"  ENABLE;
