--------------------------------------------------------
--  DDL for Table EMRS_D_REJECTION_ERROR_REASON
--------------------------------------------------------

  CREATE TABLE "EMRS_D_REJECTION_ERROR_REASON" 
   (	"REJECTION_ERROR_REASON_ID" NUMBER(*,0), 
	"MANAGED_CARE_PROGRAM" VARCHAR2(30), 
	"REJECTION_CATEGORY" VARCHAR2(30), 
	"RELATED_FILES" VARCHAR2(32), 
	"REJECTION_CODE" VARCHAR2(32), 
	"REJECTION_ERROR_REASON" VARCHAR2(240), 
	"REJECTION_ERROR_DESCRIPTION" VARCHAR2(1000), 
	"SOURCE_RECORD_ID" NUMBER(22,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_DATA" ;

   COMMENT ON COLUMN "EMRS_D_REJECTION_ERROR_REASON"."REJECTION_ERROR_REASON_ID" IS 'Rejection Error Reason ID (PK)';
   COMMENT ON COLUMN "EMRS_D_REJECTION_ERROR_REASON"."MANAGED_CARE_PROGRAM" IS 'Managed Care Program';
   COMMENT ON COLUMN "EMRS_D_REJECTION_ERROR_REASON"."REJECTION_CATEGORY" IS 'Rejection Category (Department or System that Uses this Code)';
   COMMENT ON COLUMN "EMRS_D_REJECTION_ERROR_REASON"."RELATED_FILES" IS 'Rejection Error Reason applies to this related file(s)';
   COMMENT ON COLUMN "EMRS_D_REJECTION_ERROR_REASON"."REJECTION_CODE" IS 'Rejection Error Code';
   COMMENT ON COLUMN "EMRS_D_REJECTION_ERROR_REASON"."REJECTION_ERROR_REASON" IS 'Rejection Error Reason';
   COMMENT ON COLUMN "EMRS_D_REJECTION_ERROR_REASON"."REJECTION_ERROR_DESCRIPTION" IS 'Description or Definition for Rejection Error Reason';
