--------------------------------------------------------
--  DDL for Table EMRS_D_OUTREACH_ACTIVITY
--------------------------------------------------------

  CREATE TABLE "EMRS_D_OUTREACH_ACTIVITY" 
   (	"ACTIVITY_ID" NUMBER(*,0), 
	"MANAGED_CARE_PROGRAM" VARCHAR2(50), 
	"ACTIVITY_NAME" VARCHAR2(50), 
	"ACTIVITY_DATE" DATE, 
	"ACTIVITY_ADDRESS" VARCHAR2(55), 
	"ACTIVITY_CITY" VARCHAR2(30), 
	"ACTIVITY_STATE" VARCHAR2(2), 
	"ACTIVITY_ZIP" VARCHAR2(15), 
	"ACTIVITY_FEE_ASSESSED" NUMBER(7,2), 
	"ACTIVITY_DOOR_PRIZE_VALUE" NUMBER(7,2), 
	"CONTACT_FNAME" VARCHAR2(40), 
	"CONTACT_LNAME" VARCHAR2(40), 
	"CONTACT_EMAIL" VARCHAR2(50), 
	"CONTACT_ADDRESS" VARCHAR2(55), 
	"CONTACT_AREA_CODE" VARCHAR2(3), 
	"CONTACT_PHONE" VARCHAR2(11), 
	"CONTACT_EXTENSION" VARCHAR2(6), 
	"OBSERVATION" VARCHAR2(2000), 
	"OUTCOME_COMMENTS" VARCHAR2(1000), 
	"SOURCE_RECORD_ID" NUMBER(*,0), 
	"NBR_KITS_PROVIDED" NUMBER(*,0), 
	"NBR_RECIPIENT_ATTENDEES" NUMBER(*,0), 
	"NBR_STAFF_ATTENDEES" NUMBER(*,0), 
	"SR_COMM_TYPE_ID" NUMBER(*,0), 
	"SR_LANGUAGE_ID" NUMBER(*,0), 
	"SR_OBSERVATION_ID" NUMBER(*,0), 
	"SR_STAFF_ID" NUMBER(*,0), 
	"VERSION" NUMBER(2,0), 
	"DATE_OF_VALIDITY_START" DATE, 
	"DATE_OF_VALIDITY_END" DATE, 
	"CREATED_BY" VARCHAR2(18), 
	"DATE_CREATED" DATE, 
	"UPDATED_BY" VARCHAR2(18), 
	"DATE_UPDATED" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MAXDAT_DATA" ;

   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."ACTIVITY_ID" IS 'Outreach Activity ID (PK)';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."MANAGED_CARE_PROGRAM" IS 'Managed Care Program that Uses This Outreach Target Group Activity';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."ACTIVITY_NAME" IS 'Activity Name';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."ACTIVITY_DATE" IS 'Activity Date';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."ACTIVITY_ADDRESS" IS 'Activity Site Address';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."ACTIVITY_CITY" IS 'Activity City';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."ACTIVITY_STATE" IS 'Activity State';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."ACTIVITY_ZIP" IS 'Activity Zip Code';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."ACTIVITY_FEE_ASSESSED" IS 'Outreach Target Group Activity Fee Assessed (Y;N)';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."ACTIVITY_DOOR_PRIZE_VALUE" IS 'Outreach Target Group Activity Door Prize (Y;N)';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."CONTACT_FNAME" IS 'Contact First Name';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."CONTACT_LNAME" IS 'Contact Last Name';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."CONTACT_EMAIL" IS 'Contact Email Address';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."CONTACT_ADDRESS" IS 'Contact Address';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."CONTACT_AREA_CODE" IS 'Contact Area Code';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."CONTACT_PHONE" IS 'Contact Phone Number';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."CONTACT_EXTENSION" IS 'Contact Phone Extension';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."OBSERVATION" IS 'Observation';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."OUTCOME_COMMENTS" IS 'Outcome Comments';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."SOURCE_RECORD_ID" IS 'Source-System Primary-Key Record ID #';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."NBR_KITS_PROVIDED" IS 'Number of Kits Provided';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."NBR_RECIPIENT_ATTENDEES" IS 'Number of Recipient Attendees';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."NBR_STAFF_ATTENDEES" IS 'Number of Staff Attendees';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."SR_COMM_TYPE_ID" IS 'Source-System Communication TypeID';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."SR_LANGUAGE_ID" IS 'Source-System Language ID';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."SR_OBSERVATION_ID" IS 'Source-System Observation ID';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."SR_STAFF_ID" IS 'Source-System Staff ID';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."VERSION" IS 'Type-2 SCD Version Number';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."DATE_OF_VALIDITY_START" IS 'ETL Required Column to Designate the Start-Date for a Valid Slowly Changing Dimension (SCD) Record';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."DATE_OF_VALIDITY_END" IS 'ETL Required Column to Designate the End-Date for a Valid Slowly Changing Dimension (SCD) Record';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."CREATED_BY" IS 'Warehouse Load Created By';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."DATE_CREATED" IS 'Warehouse Load Creation Date';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."UPDATED_BY" IS 'Warehouse Load Updated By';
   COMMENT ON COLUMN "EMRS_D_OUTREACH_ACTIVITY"."DATE_UPDATED" IS 'Warehouse Load Date Updated';
