--------------------------------------------------------
--  DDL for Table EMRS_D_CARE_SERV_DELIV_AREA
--------------------------------------------------------

  CREATE TABLE "EMRS_D_CARE_SERV_DELIV_AREA" 
   (	"CSDA_ID" NUMBER(*,0), 
	"MANAGED_CARE_PROGRAM" VARCHAR2(50), 
	"CSDA_CODE" VARCHAR2(32), 
	"CSDA_NAME" VARCHAR2(240), 
	"REGION_NUMBER_CATEGORY" VARCHAR2(5), 
	"STATUS" VARCHAR2(1), 
	"IMPLEMENTATION_DATE" DATE, 
	"RECORD_DATE" DATE, 
	"RECORD_TIME" VARCHAR2(5), 
	"RECORD_NAME" VARCHAR2(80), 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_TIME" VARCHAR2(5), 
	"MODIFIED_NAME" VARCHAR2(80), 
	"STARPLUS" VARCHAR2(1), 
	"SOURCE_RECORD_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_DATA" ;

   COMMENT ON COLUMN "EMRS_D_CARE_SERV_DELIV_AREA"."CSDA_ID" IS 'CSDA ID (PK)';
   COMMENT ON COLUMN "EMRS_D_CARE_SERV_DELIV_AREA"."MANAGED_CARE_PROGRAM" IS 'Managed Care Program that Uses This CSDA';
   COMMENT ON COLUMN "EMRS_D_CARE_SERV_DELIV_AREA"."CSDA_CODE" IS 'Care Service Delivery Area ID';
   COMMENT ON COLUMN "EMRS_D_CARE_SERV_DELIV_AREA"."CSDA_NAME" IS 'CSDA Name';
   COMMENT ON COLUMN "EMRS_D_CARE_SERV_DELIV_AREA"."REGION_NUMBER_CATEGORY" IS 'Outreach Region Number';
   COMMENT ON COLUMN "EMRS_D_CARE_SERV_DELIV_AREA"."STATUS" IS 'CSDA Status';
   COMMENT ON COLUMN "EMRS_D_CARE_SERV_DELIV_AREA"."IMPLEMENTATION_DATE" IS 'CSDA Implementation Date';
   COMMENT ON COLUMN "EMRS_D_CARE_SERV_DELIV_AREA"."RECORD_DATE" IS 'Record Creation Date';
   COMMENT ON COLUMN "EMRS_D_CARE_SERV_DELIV_AREA"."RECORD_TIME" IS 'Record Creation Time';
   COMMENT ON COLUMN "EMRS_D_CARE_SERV_DELIV_AREA"."RECORD_NAME" IS 'Record Created By';
   COMMENT ON COLUMN "EMRS_D_CARE_SERV_DELIV_AREA"."MODIFIED_DATE" IS 'Record Modification Date';
   COMMENT ON COLUMN "EMRS_D_CARE_SERV_DELIV_AREA"."MODIFIED_TIME" IS 'Record Modification Time';
   COMMENT ON COLUMN "EMRS_D_CARE_SERV_DELIV_AREA"."MODIFIED_NAME" IS 'Record Modified By - Last Name';
   COMMENT ON COLUMN "EMRS_D_CARE_SERV_DELIV_AREA"."STARPLUS" IS 'STAR+PLUS CSDA (Y;N)';
   COMMENT ON COLUMN "EMRS_D_CARE_SERV_DELIV_AREA"."SOURCE_RECORD_ID" IS 'Source-System Primary-Key Record ID #';
