---BACKUPS
CREATE TABLE CC_F_ACTUALS_QUEUE_INTRVL_BAK2
  AS (SELECT * FROM CC_F_ACTUALS_QUEUE_INTERVAL);
  
create or replace public synonym CC_F_ACTUALS_QUEUE_INTRVL_BAK2
     for MAXDAT.CC_F_ACTUALS_QUEUE_INTRVL_BAK2;     
  
commit;

/  

   
