Insert into CC_A_LIST_LKUP (NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values ('ACTIVITY_NAME_FOR_LUNCH_CT','ACTIVITY_TYPE_NAME','ACTIVITY_TYPE_NAME','Lunch',null,1,to_date('19-SEP-16','DD-MON-RR'),to_date('07-JUL-77','DD-MON-RR'),'Activity type name for Lunch',to_date('21-SEP-16','DD-MON-RR'),to_date('21-SEP-16','DD-MON-RR'));
Insert into CC_A_LIST_LKUP (NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (
'ACTIVITY_NAME_FOR_LUNCH_TIME','ACTIVITY_TYPE_NAME','ACTIVITY_TYPE_NAME','Lunch Time',null,1,to_date('19-SEP-16','DD-MON-RR'),to_date('07-JUL-77','DD-MON-RR'),'Activity type name for Lunch',to_date('19-SEP-16','DD-MON-RR'),to_date('21-SEP-16','DD-MON-RR'));

commit;