use role SYSADMIN;
use warehouse PUREINSIGHTS_DEV_LOAD_DAILY_WH;
use database PUREINSIGHTS_DEV;
use schema PUBLIC;

create or replace view D_PI_SESSION_REQUESTED_ROUTING_SKILLS_VW(
	PROJECTID,
	PROJECTNAME,
	PROGRAMID,
	PROGRAMNAME,
	CONVERSATIONID,
	PARTICIPANTID,
	REQUESTEDROUTINGSKILLID,
	REQUESTEDROUTINGSKILLNAME,
	SESSIONID
) COPY GRANTS as
WITH
    skill AS (SELECT co.projectid AS projectid, co.raw:id AS ID, TRIM(CAST(co.raw:name AS VARCHAR(255))) AS skillName FROM raw.configuration_objects co  WHERE co.raw:type = 'skill')
select 
	pr.PROJECTID												AS	projectid,
	pr.PROJECTNAME												AS	projectname,
	srrs.PROGRAMID												AS	programid,
	srrs.PROGRAMNAME											AS	programname,
	TRIM(CAST(srrs.raw:conversationId AS VARCHAR(255)))			AS	conversationId,
	TRIM(CAST(srrs.raw:participantId AS VARCHAR(255)))			AS	participantId,
	TRIM(CAST(srrs.raw:skillId AS VARCHAR(255)))				AS	requestedRoutingSkillId,
	skill.skillName												AS	requestedRoutingSkillName,
	TRIM(CAST(srrs.raw:sessionId AS VARCHAR(255)))				AS	sessionId
from 
	RAW.SESSION_REQUESTED_ROUTING_SKILLS srrs
left join
	skill
ON
(
		srrs.projectid = skill.projectid
	AND	srrs.raw:skillId = skill.ID
)
inner join 
	PUBLIC.D_PI_PROJECTS pr
on 
(
	srrs.projectId = pr.projectId
);

GRANT SELECT ON D_PI_SESSION_REQUESTED_ROUTING_SKILLS_VW TO BI_PRODUCT_DEV;   
GRANT SELECT ON D_PI_SESSION_REQUESTED_ROUTING_SKILLS_VW TO DATA_SUPPORT_ROLE;
GRANT SELECT ON D_PI_SESSION_REQUESTED_ROUTING_SKILLS_VW TO DA_LAB_ADMIN;
GRANT SELECT ON D_PI_SESSION_REQUESTED_ROUTING_SKILLS_VW TO DA_LAB_READ;
GRANT SELECT ON D_PI_SESSION_REQUESTED_ROUTING_SKILLS_VW TO MAX_DEV;
GRANT SELECT ON D_PI_SESSION_REQUESTED_ROUTING_SKILLS_VW TO OPS_ANALYTICS_TEAM;
GRANT SELECT ON D_PI_SESSION_REQUESTED_ROUTING_SKILLS_VW TO PUBLIC;
GRANT SELECT ON D_PI_SESSION_REQUESTED_ROUTING_SKILLS_VW TO INFA_DATA_CATALOG_DEV_READ;
GRANT SELECT ON D_PI_SESSION_REQUESTED_ROUTING_SKILLS_VW TO PUREINSIGHTS_DEV_READ;
GRANT SELECT ON D_PI_SESSION_REQUESTED_ROUTING_SKILLS_VW TO PI_DATA_INGEST_DEV_ALERT_USER;
GRANT DELETE, INSERT, REBUILD, REFERENCES, SELECT, TRUNCATE, UPDATE ON D_PI_SESSION_REQUESTED_ROUTING_SKILLS_VW TO PUREINSIGHTS_DEV_POC;

