CREATE OR REPLACE VIEW INEO_D_QUEUE_SUMMARY_HISTORY_SV
AS
SELECT * FROM ineo.INEO_QUEUE_SUMMARY_HISTORY;

CREATE OR REPLACE VIEW INEO_D_QUEUE_DAILY_SUMMARY_HISTORY_SV
AS
SELECT * FROM ineo.INEO_QUEUE_DAILY_SUMMARY_HISTORY;