CREATE TABLE CC_L_PATCH_LOG 
    ( 
     PATCH_LOG_ID NUMBER (19)  NOT NULL , 
     PATCH_VERSION VARCHAR2 (30)  NOT NULL , 
     SCRIPT_SEQUENCE NUMBER (7)  NOT NULL , 
     SCRIPT_NAME VARCHAR2 (255)  NOT NULL , 
     SCRIPT_RUN_DATE DATE DEFAULT SYSDATE  NOT NULL 
    ) 
    LOGGING 
;



ALTER TABLE CC_L_PATCH_LOG 
    ADD CONSTRAINT CC_L_PATCH_LOG_PK PRIMARY KEY ( PATCH_LOG_ID ) ;


ALTER TABLE CC_L_PATCH_LOG 
    ADD CONSTRAINT CC_L_PATCH_LOG__UN UNIQUE ( PATCH_VERSION , SCRIPT_NAME ) ;


ALTER TABLE CC_L_PATCH_LOG 
    ADD CONSTRAINT CC_L_PATCH_LOG__UNv1 UNIQUE ( SCRIPT_SEQUENCE ) ;



CREATE SEQUENCE SEQ_CC_L_PATCH_LOG 
    START WITH 1 
    INCREMENT BY 1 
    MAXVALUE 9999999999999999999 
    MINVALUE 1 
    CACHE 20 
;

CREATE OR REPLACE TRIGGER BIU_CC_L_PATCH_LOG 
    BEFORE INSERT OR UPDATE ON CC_L_PATCH_LOG 
    FOR EACH ROW 
BEGIN
IF INSERTING AND :NEW.PATCH_LOG_ID IS NULL THEN 
  SELECT SEQ_CC_L_PATCH_LOG.NEXTVAL INTO :NEW.PATCH_LOG_ID FROM DUAL;
END IF;
END;
/

ALTER TRIGGER BIU_CC_L_PATCH_LOG ENABLE;

COMMIT;
