ALTER TABLE hco_activity_queue ADD step_sequence number DEFAULT 1 NOT NULL;
ALTER TABLE step_instance ADD step_sequence number DEFAULT 1 NOT NULL;
update step_instance set step_sequence = 1;

DROP INDEX MAXDAT.STEP_INSTANCE_UK1;
CREATE UNIQUE INDEX MAXDAT.STEP_INSTANCE_UK1 
ON MAXDAT.STEP_INSTANCE (REF_TYPE ASC, REF_ID ASC, STEP_DEFINITION_ID ASC, PROCESS_ID ASC, CREATE_TS ASC, STEP_SEQUENCE ASC);



