--ACCOUNT_RPT_VW
CREATE OR REPLACE FORCE VIEW "FLCPD0_STAGE"."ACCOUNT_RPT_VW" ("OPERATION$", "CSCN$", "COMMIT_TIMESTAMP$", "XIDUSN$", "XIDSLT$", "XIDSEQ$", "DDLDESC$", "DDLOPER$", "DDLPDOBJN$", "RSID$", "TARGET_COLMAP$", "TIMESTAMP$", "USERNAME$", "ACCOUNT_ID", "ACCOUNT_NUMBER", "ASSISTER_FULL_NAME", "ASSISTER_ORG_ID", "ASSISTER_ORG_NAME", "AUTOPAY_INELIG_REASON", "AUTOPAY_INELIG_REASON_DATE", "INSERT_DATE", "INSERT_JOB_NAME", "INSERT_USER", "INSERT_USER_ROLE", "JPA_VERSION", "LAST_UPDATE_JOB_NAME", "LAST_UPDATE_USER", "LEGACY_ACCOUNT_NUMBER", "PREGNANCY_DUE_DATE", "PROHIBIT_REFUND_FLAG", "UNPAID_MEDICAL_BILLS_IND", "UPDATE_DATE", "UPDATE_USER_ROLE", "WEB_APPLICATION_ID") AS 
Select decode(Shareplex_source_operation,'UPDATE BEFORE','UO','UPDATE AFTER','UN','INSERT','I','DELETE','D') "OPERATION$",
       Shareplex_source_SCN "CSCN$",
       Shareplex_source_TIME "COMMIT_TIMESTAMP$", 
       NULL "XIDUSN$",
       NULL "XIDSLT$", 
       NULL "XIDSEQ$",   
       NULL "DDLDESC$", 
       NULL "DDLOPER$", 
       NULL "DDLPDOBJN$", 
       NULL "RSID$", 
       NULL "TARGET_COLMAP$", 
       Shareplex_source_TIME "TIMESTAMP$", 
       NULL "USERNAME$", 
       ACC.*   
  FROM "FLCPD0_CDC"."ACCOUNT_CT" ACC
 WHERE ACC.shareplex_source_scn >= 523031955 and ACC.shareplex_source_scn <=539086134;