--ACCOUNT_RENEWAL_RPT_VW
CREATE OR REPLACE FORCE VIEW "FLCPD0_STAGE"."ACCOUNT_RENEWAL_RPT_VW" ("OPERATION$", "CSCN$", "COMMIT_TIMESTAMP$", "XIDUSN$", "XIDSLT$", "XIDSEQ$", "DDLDESC$", "DDLOPER$", "DDLPDOBJN$", "RSID$", "TARGET_COLMAP$", "TIMESTAMP$", "USERNAME$", "ACCOUNT_ID", "ADDTL_RENEWAL_REVIEW_DATE", "ADMIN_RENEWAL_CANDIDATE_FLAG", "ADMIN_RENEWAL_RESULT_IND", "AUTO_RENEW_CANDIDATE_FLAG", "CONTINUOUS_ELIG_END_DATE", "FAMILY_SUB_PREM_LOCK", "INSERT_DATE", "INSERT_JOB_NAME", "INSERT_USER", "INSERT_USER_ROLE", "JPA_VERSION", "LAST_RENEWAL_DATE", "LAST_UPDATE_JOB_NAME", "LAST_UPDATE_USER", "NEXT_FAMILY_SUB_PREM_LOCK", "NEXT_RENEWAL_DATE", "RENEWAL_DATE", "RENEWAL_SIGNED_FLAG", "RENEWAL_STATUS", "RENEWAL_STATUS_DATE", "UPDATE_DATE", "UPDATE_USER_ROLE") AS 
Select decode(Shareplex_source_operation,'UPDATE BEFORE','UO','UPDATE AFTER','UN','INSERT','I','DELETE','D') "OPERATION$",
       Shareplex_source_SCN "CSCN$",
       Shareplex_source_TIME "COMMIT_TIMESTAMP$", 
       NULL "XIDUSN$",
       NULL "XIDSLT$", 
       NULL "XIDSEQ$",   
       NULL "DDLDESC$", 
       NULL "DDLOPER$", 
       NULL "DDLPDOBJN$", 
       NULL "RSID$", 
       NULL "TARGET_COLMAP$", 
       Shareplex_source_TIME "TIMESTAMP$", 
       NULL "USERNAME$", 
       ARC.*   
  FROM "FLCPD0_CDC"."ACCOUNT_RENEWAL_CT" ARC
 WHERE ARC.shareplex_source_scn >= 523031955 and ARC.shareplex_source_scn <=539086134;