--ACCOUNT_CI_RPT_VW
CREATE OR REPLACE FORCE VIEW "FLCPD0_STAGE"."ACCOUNT_CI_RPT_VW" ("OPERATION$", "CSCN$", "COMMIT_TIMESTAMP$", "XIDUSN$", "XIDSLT$", "XIDSEQ$", "DDLDESC$", "DDLOPER$", "DDLPDOBJN$", "RSID$", "TARGET_COLMAP$", "TIMESTAMP$", "USERNAME$", "ACCOUNT_ID", "CELL_PHONE", "DO_NOT_CALL_FLAG", "EMAIL_ADDRESS", "EMAIL_BAD_ADDRESS_FLAG", "EMAIL_CONTACT_FLAG", "HOME_BAD_ADDRESS_FLAG", "HOME_CITY", "HOME_COUNTY", "HOME_MAILING_ADDRESS_SAME_FLAG", "HOME_PHONE", "HOME_POSTAL_CODE", "HOME_STATE", "HOME_STREET", "HOME_STREET2", "HOME_VALIDATION_STATUS", "INSERT_DATE", "INSERT_JOB_NAME", "INSERT_USER", "INSERT_USER_ROLE", "JPA_VERSION", "LANGUAGE_PREFERENCE", "LAST_UPDATE_JOB_NAME", "LAST_UPDATE_USER", "MAILING_BAD_ADDRESS_FLAG", "MAILING_CITY", "MAILING_COUNTY", "MAILING_POSTAL_CODE", "MAILING_STATE", "MAILING_STREET", "MAILING_STREET2", "MAILING_VALIDATION_STATUS", "PASSWORD", "PHONE_NONE_FLAG", "PREFERRED_CONTACT_METHOD", "SMS_CONTACT_FLAG", "UPDATE_DATE", "UPDATE_USER_ROLE") AS 
Select decode(Shareplex_source_operation,'UPDATE BEFORE','UO','UPDATE AFTER','UN','INSERT','I','DELETE','D') "OPERATION$",
       Shareplex_source_SCN "CSCN$",
       Shareplex_source_TIME "COMMIT_TIMESTAMP$", 
       NULL "XIDUSN$",
       NULL "XIDSLT$", 
       NULL "XIDSEQ$",   
       NULL "DDLDESC$", 
       NULL "DDLOPER$", 
       NULL "DDLPDOBJN$", 
       NULL "RSID$", 
       NULL "TARGET_COLMAP$", 
       Shareplex_source_TIME "TIMESTAMP$", 
       NULL "USERNAME$", 
       ACIC.*   
  FROM "FLCPD0_CDC"."ACCOUNT_CONTACT_INFO_CT" ACIC
 WHERE ACIC.shareplex_source_scn >= 523031955 and ACIC.shareplex_source_scn <=539086134;