  CREATE TABLE "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" 
   (	"SUBSCRIPTION_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"HANDLE" NUMBER NOT NULL ENABLE, 
	"SET_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CREATED" DATE NOT NULL ENABLE, 
	"STATUS" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"EARLIEST_SCN" NUMBER NOT NULL ENABLE, 
	"LATEST_SCN" NUMBER NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"LAST_PURGED" DATE, 
	"LAST_EXTENDED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLHK_TBS2" ;

  CREATE UNIQUE INDEX "FLCPD0_STAGE"."I_CDC_SUBSCRIPTIONS_STAGE" ON "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" ("SUBSCRIPTION_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLHK_TBS2" ;


  GRANT SELECT ON "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" TO "FLCPD0_CDC";
  GRANT SELECT ON "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" TO "FLCPD0_ATM";
  GRANT SELECT ON "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" TO "FLCPD0_SYS";
  GRANT SELECT ON "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" TO "FLCPD0_TASK";
  GRANT SELECT ON "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" TO "FLCPD0_LETTERS";
  GRANT SELECT ON "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" TO "FLCPD0_VIDA";
  
  REM INSERTING into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE"
SET DEFINE OFF;
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3718,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 ACCOUNT_RENEWAL',NULL,NULL,'ACCOUNT_RENEWAL_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3715,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 ACCOUNT',NULL,NULL,'ACCOUNT_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3717,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',1,12132956086054,'Subscription for FLCPD0 ACCOUNT_MISSING_INFO',null,to_date('12-JUN-22','DD-MON-RR'),'ACCOUNT_MI_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3719,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 ACCOUNT_RENEWAL_RESULT',NULL,NULL,'ACCOUNT_RR_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3720,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',1,12132956086054,'Subscription for FLCPD0 ACCT_MEMBER_ENROLLMENT_ATTRS',null,to_date('12-JUN-22','DD-MON-RR'),'ACCT_MEA_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3721,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 APPLICANT_INFO',NULL,NULL,'APPLICANT_INFO_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3722,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 APPLICATION',NULL,NULL,'APPLICATION_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3723,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',1,12132956086054,'Subscription for FLCPD0 APPLICATION_STATUS_REASON',null,to_date('12-JUN-22','DD-MON-RR'),'APP_STATUS_REASON_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3724,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 COVERAGE',NULL,NULL,'COVERAGE_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3725,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 DISPUTE',null,NULL,'DISPUTE_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3726,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 ELIGIBILITY_DETERMINATION',NULL,NULL,'ELIG_DETERM_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3727,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 ELIGIBILITY_RESULT',NULL,NULL,'ELIGIBILITY_RESULT_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3728,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',1,12132956086054,'Subscription for FLCPD0 ELIGIBILITY_STATUS_REASON',null,to_date('12-JUN-22','DD-MON-RR'),'ELIG_STATUS_REASON_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3729,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 FINANCIAL_TRANSACTION',NULL,NULL,'FIN_TRANS_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3730,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 INBOUND_DOCUMENT',NULL,NULL,'INBOUND_DOCUMENT_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3731,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 INCOME',NULL,NULL,'INCOME_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3732,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 INCOME_RESPONSE',NULL,NULL,'INCOME_RESP_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3733,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',1,12132956086054,'Subscription for FLCPD0 MEMBER_MISSING_INFO',null,to_date('12-JUN-22','DD-MON-RR'),'MEMBER_MISSING_INFO_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3734,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 PERSON',NULL,NULL,'PERSON_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3735,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 SUSPENSE_TRANSACTION',NULL,NULL,'SUS_TRANS_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3736,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 WORK_REQUESTS',NULL,NULL,'WORK_REQUESTS_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3737,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 COVERAGE_REQUEST',NULL,NULL,'COVERAGE_REQUEST_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3738,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 ACCOUNT_MEMBERSHIP',NULL,NULL,'ACCOUNT_MEMBERSHIP_RPT_FLCPD0');
Insert into "FLCPD0_STAGE"."CDC_SUBSCRIPTIONS_STAGE" (HANDLE,SET_NAME,USERNAME,CREATED,STATUS,EARLIEST_SCN,LATEST_SCN,DESCRIPTION,LAST_PURGED,LAST_EXTENDED,SUBSCRIPTION_NAME) values (3739,'CS_FLCPD0','FLCPD0_STAGE',to_date(SYSDATE,'DD-MON-RR'),'A',0,0,'Subscription for FLCPD0 ACCOUNT_CONTACT_INFO',NULL,NULL,'ACCOUNT_CI_RPT_FLCPD0');
commit;
