
ALTER TABLE METRIC ADD ( LABEL VARCHAR2(50) );

UPDATE METRIC SET LABEL = NAME;

ALTER TABLE METRIC MODIFY (LABEL VARCHAR2(50) NOT NULL);

UPDATE METRIC SET LABEL = 'AB Rate (%)' WHERE NAME = 'AB Rate';

ALTER TABLE METRIC_VALUE_DECIMAL MODIFY ( COMMENTS VARCHAR2(4000) );

CREATE OR REPLACE VIEW METRIC_SV AS
SELECT METRIC.* FROM METRIC ;

UPDATE METRIC_VALUE_DECIMAL
SET COMMENTS = 'The CRM System and Portal glitches allow the project to take phone applications with a small focus groups of agents ONLY.  NY HIX will open up phone application and expect a large impact on the AHT.'
WHERE METRIC_USAGE_ID IN (
  SELECT METRIC_USAGE_ID
  FROM METRIC_USAGE MU
  INNER JOIN PROJECT P ON MU.PROJECT_ID = P.PROJECT_ID
  INNER JOIN METRIC M ON MU.METRIC_ID = M.METRIC_ID
  WHERE PROJECT_NAME = 'NY HIX'
  AND M.NAME = 'AHT'
)
AND REPORTING_PERIOD_ID IN (
  SELECT REPORTING_PERIOD_ID
  FROM REPORTING_PERIOD
  WHERE END_DATE = TO_DATE('12-OCT-2013')
);


UPDATE METRIC_VALUE_DECIMAL
SET COMMENTS = 'Higher than forecasted calls volumes for VT HIX are attributed to: 1) general customer inquiries given portal issues. 2) calls from customers who have attempted to work with Navigators, where the Navigators do not have a functioning enrollment process due to system immaturity.  The project has not been given access to the portal or provided a solution to complete applications over the phone or support customers enrolling via the web at home. Hence the lower than expected AHT.'
WHERE METRIC_USAGE_ID IN (
  SELECT METRIC_USAGE_ID
  FROM METRIC_USAGE MU
  INNER JOIN PROJECT P ON MU.PROJECT_ID = P.PROJECT_ID
  INNER JOIN METRIC M ON MU.METRIC_ID = M.METRIC_ID
  WHERE PROJECT_NAME = 'VT HIX'
  AND M.NAME = 'AHT'
)
AND REPORTING_PERIOD_ID IN (
  SELECT REPORTING_PERIOD_ID
  FROM REPORTING_PERIOD
  WHERE END_DATE = TO_DATE('12-OCT-2013')
);


UPDATE METRIC_VALUE_DECIMAL
SET COMMENTS = 'CT: Actuals for WE 10/12 were not supplied by project.'
WHERE METRIC_USAGE_ID IN (
  SELECT METRIC_USAGE_ID
  FROM METRIC_USAGE MU
  INNER JOIN PROJECT P ON MU.PROJECT_ID = P.PROJECT_ID
  INNER JOIN METRIC M ON MU.METRIC_ID = M.METRIC_ID
  WHERE PROJECT_NAME = 'CT HIX'
  AND M.NAME = 'AHT'
)
AND REPORTING_PERIOD_ID IN (
  SELECT REPORTING_PERIOD_ID
  FROM REPORTING_PERIOD
  WHERE END_DATE = TO_DATE('12-OCT-2013')
);

UPDATE METRIC_VALUE_DECIMAL
SET COMMENTS = 'DC: It is unclear to the project the reason for the large % variance.'
WHERE METRIC_USAGE_ID IN (
  SELECT METRIC_USAGE_ID
  FROM METRIC_USAGE MU
  INNER JOIN PROJECT P ON MU.PROJECT_ID = P.PROJECT_ID
  INNER JOIN METRIC M ON MU.METRIC_ID = M.METRIC_ID
  WHERE PROJECT_NAME = 'DC HIX'
  AND M.NAME = 'AHT'
)
AND REPORTING_PERIOD_ID IN (
  SELECT REPORTING_PERIOD_ID
  FROM REPORTING_PERIOD
  WHERE END_DATE = TO_DATE('12-OCT-2013')
);

UPDATE METRIC_VALUE_DECIMAL
SET COMMENTS = 'GO LIVE for Boise is 10/16.'
WHERE METRIC_USAGE_ID IN (
  SELECT METRIC_USAGE_ID
  FROM METRIC_USAGE MU
  INNER JOIN PROJECT P ON MU.PROJECT_ID = P.PROJECT_ID
  INNER JOIN METRIC M ON MU.METRIC_ID = M.METRIC_ID
  WHERE PROJECT_NAME = 'CCO - Boise'
  AND M.NAME = 'AHT'
)
AND REPORTING_PERIOD_ID IN (
  SELECT REPORTING_PERIOD_ID
  FROM REPORTING_PERIOD
  WHERE END_DATE = TO_DATE('12-OCT-2013')
);

UPDATE METRIC_VALUE_DECIMAL
SET COMMENTS = 'At HI HIX,  performance improvements  (lower than expected AB Rate and ASA) are attributed to lower call volumes and AHT, and significantly improved scheduling - ensuring that sufficient staff are available during high call volume periods.'
WHERE METRIC_USAGE_ID IN (
  SELECT METRIC_USAGE_ID
  FROM METRIC_USAGE MU
  INNER JOIN PROJECT P ON MU.PROJECT_ID = P.PROJECT_ID
  INNER JOIN METRIC M ON MU.METRIC_ID = M.METRIC_ID
  WHERE PROJECT_NAME = 'HI HIX'
  AND M.NAME = 'AHT'
)
AND REPORTING_PERIOD_ID IN (
  SELECT REPORTING_PERIOD_ID
  FROM REPORTING_PERIOD
  WHERE END_DATE = TO_DATE('30-NOV-2013')
);


UPDATE METRIC_VALUE_DECIMAL
SET COMMENTS = 'VT HIX project has not submitted actuals for the WE 11/30.'
WHERE METRIC_USAGE_ID IN (
  SELECT METRIC_USAGE_ID
  FROM METRIC_USAGE MU
  INNER JOIN PROJECT P ON MU.PROJECT_ID = P.PROJECT_ID
  INNER JOIN METRIC M ON MU.METRIC_ID = M.METRIC_ID
  WHERE PROJECT_NAME = 'VT HIX'
  AND M.NAME = 'AHT'
)
AND REPORTING_PERIOD_ID IN (
  SELECT REPORTING_PERIOD_ID
  FROM REPORTING_PERIOD
  WHERE END_DATE = TO_DATE('30-NOV-2013')
);


UPDATE METRIC_VALUE_DECIMAL
SET COMMENTS = 'MD HIX experienced a lower than forecasted call volume due to HIX website maintenance on 11/24.  The project attributes its high actual ASA to a severely increased AHT in the enrollment queue which represents over 60% of all volume.'
WHERE METRIC_USAGE_ID IN (
  SELECT METRIC_USAGE_ID
  FROM METRIC_USAGE MU
  INNER JOIN PROJECT P ON MU.PROJECT_ID = P.PROJECT_ID
  INNER JOIN METRIC M ON MU.METRIC_ID = M.METRIC_ID
  WHERE PROJECT_NAME = 'MD HIX'
  AND M.NAME = 'AHT'
)
AND REPORTING_PERIOD_ID IN (
  SELECT REPORTING_PERIOD_ID
  FROM REPORTING_PERIOD
  WHERE END_DATE = TO_DATE('30-NOV-2013')
);

UPDATE METRIC_VALUE_DECIMAL
SET COMMENTS = 'MD HIX has received approval from client to now hire 40 additional phone agents. They will be attending an abbreviated one-week training module compared to the three-week normal class.'
WHERE METRIC_USAGE_ID IN (
  SELECT METRIC_USAGE_ID
  FROM METRIC_USAGE MU
  INNER JOIN PROJECT P ON MU.PROJECT_ID = P.PROJECT_ID
  INNER JOIN METRIC M ON MU.METRIC_ID = M.METRIC_ID
  WHERE PROJECT_NAME = 'MD HIX'
  AND M.NAME = 'FTE Count'
)
AND REPORTING_PERIOD_ID IN (
  SELECT REPORTING_PERIOD_ID
  FROM REPORTING_PERIOD
  WHERE END_DATE = TO_DATE('30-NOV-2013')
);

UPDATE METRIC_VALUE_DECIMAL
SET COMMENTS = 'While actual call volumes are tracking to their forecasts, DC HIX is experiencing an increased email volume, hence having to divert some of the FTEs to support the email queue.  In addition, several CSRs are doing call backs. Finally, the project has CSRs helping with manual applications, which was not part of the original scope.'
WHERE METRIC_USAGE_ID IN (
  SELECT METRIC_USAGE_ID
  FROM METRIC_USAGE MU
  INNER JOIN PROJECT P ON MU.PROJECT_ID = P.PROJECT_ID
  INNER JOIN METRIC M ON MU.METRIC_ID = M.METRIC_ID
  WHERE PROJECT_NAME = 'DC HIX'
  AND M.NAME = 'FTE Count'
)
AND REPORTING_PERIOD_ID IN (
  SELECT REPORTING_PERIOD_ID
  FROM REPORTING_PERIOD
  WHERE END_DATE = TO_DATE('30-NOV-2013')
);

