
ALTER TABLE AMP_USER MODIFY(
  LAST_NAME VARCHAR2 (50 CHAR) NULL,
  FIRST_NAME  VARCHAR2 (50 CHAR) NULL,
  PASSWORD VARCHAR2 (255 CHAR) NULL,
  EMAIL VARCHAR2 (255 CHAR) NULL
);

ALTER TABLE AMP_USER DROP CONSTRAINT AMP_USER__UN1;

INSERT INTO AMP_USER (
  ID
  , USERNAME
  , ACCOUNT_ENABLED
  , ACCOUNT_EXPIRED
  , ACCOUNT_LOCKED
  , CREDENTIALS_EXPIRED

) SELECT
  SEQ_AMP_USER.NEXTVAL
  , '56205'
  , 1
  , 0
  , 0
  , 0
FROM DUAL;

INSERT INTO AMP_USER_AMP_ROLE (
  USER_ID
  , ROLE_ID
) VALUES (
  1, 1
);

INSERT INTO AMP_USER_AMP_ROLE (
  USER_ID
  , ROLE_ID
) VALUES (
  1, 2
);

commit;