-- Truncates the MAXDat tables for UK HWS Assessments.
-- !! Use carefully.  Deletes all MAXDat Assessments data, except SLA_CONFIG table.

-- Drop foreign keys and truncate tables.

truncate table MAXDAT.D_APPOINTMENT_STATUS_HISTORY;

alter table MAXDAT.APPOINTMENT_STATUS_HISTORY drop constraint APPOINTMENT_STATUS_HISTORY_APPOINTMENTS_FK;
truncate table MAXDAT.APPOINTMENT_STATUS_HISTORY;

alter table MAXDAT.APPOINTMENT_DATE_HISTORY drop constraint APPOINTMENT_DATE_HISTORY_APPOINTMENTS_FK;
truncate table MAXDAT.APPOINTMENT_DATE_HISTORY;

alter table MAXDAT.APPOINTMENTS drop constraint APPOINTMENTS_ASSESSMENT_FK;
alter table MAXDAT.APPOINTMENTS drop constraint APPOINTMENTS_CASES_FK;
truncate table MAXDAT.APPOINTMENTS;

alter table MAXDAT.RECOM_SIGNPOSTING_ADJUST drop constraint RECOM_SIGNPOSTING_ADJUST_OBSTACLES_FK;
truncate table MAXDAT.RECOM_SIGNPOSTING_ADJUST;

alter table MAXDAT.OBSTACLES drop constraint ASSESSMENT_FK;
truncate table MAXDAT.OBSTACLES;

truncate table MAXDAT.D_ASSESSMENT_STATUS_HISTORY;

alter table MAXDAT.ASSESSMENT_STATUS_HISTORY drop constraint ASSESSMENT_STATUS_HISTORY_ASSESSMENTS_FK;
truncate table MAXDAT.ASSESSMENT_STATUS_HISTORY;

alter table MAXDAT.ASSESSMENT_OUTCOMES drop constraint ASSESSMENT_OUTCOMES_ASSESSMENTS_FK;
truncate table MAXDAT.ASSESSMENT_OUTCOMES;

alter table MAXDAT.DWP_INTERVENTIONS drop constraint DWP_INTERVENTIONS_ASSESSMENTS_FK;
truncate table MAXDAT.DWP_INTERVENTIONS;

alter table MAXDAT.DWP_SIGNPOSTING drop constraint DWP_SIGNPOSTING_ASSESSMENTS_FK;
truncate table MAXDAT.DWP_SIGNPOSTING;

alter table MAXDAT.ASSESSMENTS drop constraint ASSESSMENT_CASE_FK;
truncate table MAXDAT.ASSESSMENTS;

truncate table MAXDAT.D_CASE_STATUS_HISTORY;

alter table MAXDAT.CASE_STATUS_HISTORY drop constraint CASE_STATUS_HISTORY_CASES_FK;
truncate table MAXDAT.CASE_STATUS_HISTORY;

alter table MAXDAT.CASES drop constraint CASE_RESOURCE_FK;
truncate table MAXDAT.CASES;

alter table MAXDAT.APPOINTMENTS drop constraint APPOINTMENTS_RESOURCES_FK;
truncate table MAXDAT.RESOURCES;


-- Re-add foreign keys.
alter table MAXDAT.APPOINTMENT_STATUS_HISTORY add constraint APPOINTMENT_STATUS_HISTORY_APPOINTMENTS_FK 
  foreign key (APPOINTMENT_ID) references MAXDAT.APPOINTMENTS (APPOINTMENT_ID);

alter table MAXDAT.APPOINTMENTS add constraint APPOINTMENTS_CASES_FK 
  foreign key (CASE_ID) references MAXDAT.CASES (CASE_ID);

alter table MAXDAT.APPOINTMENT_DATE_HISTORY add constraint APPOINTMENT_DATE_HISTORY_APPOINTMENTS_FK 
  foreign key (APPOINTMENT_ID) references MAXDAT.APPOINTMENTS (APPOINTMENT_ID);

alter table MAXDAT.APPOINTMENTS add constraint APPOINTMENTS_RESOURCES_FK 
  foreign key (RESOURCE_ID) references MAXDAT.RESOURCES (RESOURCE_ID);

alter table MAXDAT.APPOINTMENTS add constraint APPOINTMENTS_ASSESSMENT_FK 
  foreign key (ASSESSMENT_ID) references MAXDAT.ASSESSMENTS (ASSESSMENT_ID);

alter table MAXDAT.ASSESSMENT_OUTCOMES add constraint ASSESSMENT_OUTCOMES_ASSESSMENTS_FK 
  foreign key (ASSESSMENT_ID) references MAXDAT.ASSESSMENTS (ASSESSMENT_ID);

alter table MAXDAT.ASSESSMENT_STATUS_HISTORY add constraint ASSESSMENT_STATUS_HISTORY_ASSESSMENTS_FK 
  foreign key (ASSESSMENT_ID) references MAXDAT.ASSESSMENTS (ASSESSMENT_ID);

alter table MAXDAT.ASSESSMENTS add constraint ASSESSMENT_CASE_FK 
  foreign key (CASE_ID) references MAXDAT.CASES(CASE_ID);

alter table MAXDAT.CASE_STATUS_HISTORY add constraint CASE_STATUS_HISTORY_CASES_FK 
  foreign key (CASE_ID) references MAXDAT.CASES (CASE_ID);

alter table MAXDAT.CASES add constraint CASE_RESOURCE_FK 
  foreign key (CASE_MANAGER_ID) references MAXDAT.RESOURCES (RESOURCE_ID);
 
alter table MAXDAT.DWP_INTERVENTIONS add constraint DWP_INTERVENTIONS_ASSESSMENTS_FK 
  foreign key (ASSESSMENT_ID) references MAXDAT.ASSESSMENTS (ASSESSMENT_ID);

alter table MAXDAT.DWP_SIGNPOSTING add constraint DWP_SIGNPOSTING_ASSESSMENTS_FK 
  foreign key (ASSESSMENT_ID) references MAXDAT.ASSESSMENTS (ASSESSMENT_ID);

alter table MAXDAT.OBSTACLES add constraint ASSESSMENT_FK 
  foreign key (ASSESSMENT_ID) references MAXDAT.ASSESSMENTS (ASSESSMENT_ID);

alter table MAXDAT.RECOM_SIGNPOSTING_ADJUST add constraint RECOM_SIGNPOSTING_ADJUST_OBSTACLES_FK 
  foreign key (OBSTACLE_ID) references MAXDAT.OBSTACLES (OBSTACLE_ID);
