USE [master]
GO

/****** Object:  Database [maxbae]    Script Date: 12/3/2019 9:04:40 AM ******/
CREATE DATABASE [maxbae]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'maxbae', FILENAME = N'D:\RDSDBDATA\DATA\maxbae.mdf' , SIZE = 37793408KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'maxbae_log', FILENAME = N'D:\RDSDBDATA\DATA\maxbae_log.ldf' , SIZE = 25037888KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [maxbae] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [maxbae].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [maxbae] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [maxbae] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [maxbae] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [maxbae] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [maxbae] SET ARITHABORT OFF 
GO

ALTER DATABASE [maxbae] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [maxbae] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [maxbae] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [maxbae] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [maxbae] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [maxbae] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [maxbae] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [maxbae] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [maxbae] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [maxbae] SET  ENABLE_BROKER 
GO

ALTER DATABASE [maxbae] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [maxbae] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [maxbae] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [maxbae] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [maxbae] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [maxbae] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [maxbae] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [maxbae] SET RECOVERY FULL 
GO

ALTER DATABASE [maxbae] SET  MULTI_USER 
GO

ALTER DATABASE [maxbae] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [maxbae] SET DB_CHAINING OFF 
GO

ALTER DATABASE [maxbae] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [maxbae] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [maxbae] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [maxbae] SET QUERY_STORE = OFF
GO

USE [maxbae]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [maxbae] SET  READ_WRITE 
GO


USE [maxbae]
GO

/****** Object:  Schema [maxbaeprd]    Script Date: 12/3/2019 9:11:35 AM ******/
CREATE SCHEMA [maxbaeprd]
GO
