CREATE OR REPLACE VIEW D_MW_TASK_STATUS_SV
AS
SELECT 'COMPLETED' AS TASK_STATUS_CD
      , 'Completed' AS TASK_STATUS
FROM DUAL
UNION ALL
SELECT 'UNCLAIMED' AS TASK_STATUS_CD
      , 'Unclaimed' AS TASK_STATUS
FROM DUAL
UNION ALL
SELECT 'CLAIMED' AS TASK_STATUS_CD
      , 'Claimed' AS TASK_STATUS
FROM DUAL
UNION ALL
SELECT 'TERMINATED' AS TASK_STATUS_CD
      , 'Terminated' AS TASK_STATUS
FROM DUAL
UNION ALL
SELECT 'TIMEOUT' AS TASK_STATUS_CD
      , 'Timeout' AS TASK_STATUS
FROM DUAL
UNION ALL
SELECT 'INPROCESS' AS TASK_STATUS_CD
      , 'In Process' AS TASK_STATUS
FROM DUAL
UNION ALL
SELECT 'UD' AS TASK_STATUS_CD
      , 'Undefined' AS TASK_STATUS
FROM DUAL;

GRANT SELECT ON D_MW_TASK_STATUS_SV TO MAXDAT_REPORTS;