UPDATE CC_C_CONTACT_QUEUE
SET QUEUE_TYPE = 'Transfer', UNIT_OF_WORK_NAME = 'TRANSFER'
WHERE QUEUE_NUMBER IN ( 5219, 5226);

UPDATE CC_S_CONTACT_QUEUE
SET QUEUE_TYPE = 'Transfer'
, UNIT_OF_WORK_ID = (SELECT UNIT_OF_WORK_ID FROM CC_C_UNIT_OF_WORK WHERE UNIT_OF_WORK_NAME = 'TRANSFER')
WHERE QUEUE_NUMBER IN ( 5219, 5226);

UPDATE CC_D_CONTACT_QUEUE
SET QUEUE_TYPE = 'Transfer'
, D_UNIT_OF_WORK_ID = (SELECT UOW_ID FROM CC_D_UNIT_OF_WORK WHERE UNIT_OF_WORK_NAME = 'TRANSFER')
WHERE QUEUE_NUMBER IN ( 5219, 5226);

commit;