ALTER TABLE CC_S_ACD_QUEUE_INTERVAL MODIFY ( CALLS_ON_HOLD DEFAULT NULL );

ALTER TABLE CC_F_ACD_QUEUE_INTERVAL MODIFY ( CALLS_ON_HOLD NULL );

update cc_s_acd_queue_interval set MIN_HANDLE_TIME = null
 ,MEDIAN_HANDLE_TIME = null
 ,STDDEV_HANDLE_TIME = null
 ,MIN_SPEED_TO_HANDLE = null
 ,MAX_SPEED_TO_HANDLE = null
 ,MEDIAN_SPEED_TO_HANDLE = null
 ,STDDEV_SPEED_TO_HANDLE = null
 ,MIN_SPEED_OF_ANSWER = null
 ,MEDIAN_SPEED_OF_ANSWER = null
 ,STDDEV_SPEED_OF_ANSWER = null
 ,LABOR_MINUTES_TOTAL = null
 ,CONTACT_INVENTORY = null
 ,CONTACT_INVENTORY_JEOPARDY = null
 ,CONTACT_INVENTORY_AGE_TOTAL = null
 ,MIN_CONTACT_INVENTORY_AGE = null
 ,MAX_CONTACT_INVENTORY_AGE = null
 ,MEAN_CONTACT_INVENTORY_AGE = null
 ,MEDIAN_CONTACT_INVENTORY_AGE = null
 ,STDDEV_CONTACT_INVENTORY_AGE = null
 ,CALLS_ON_HOLD = null
 ,IVR_TIME_TOTAL = null
 ,CONTACTS_BLOCKED = null
 ,ICR_DEFAULT_ROUTED = null
 ,NETWORK_DEFAULT_ROUTED = null
 ,RETURN_BUSY = null
 ,CALLS_RONA = null
 ,RETURN_RELEASE = null
 ,CALLS_ROUTED_NON_AGENT = null
 ,ERROR_COUNT = null
 ,AGENT_ERROR_COUNT = null
 ,RETURN_RING = null
 ,INCOMPLETE_CALLS = null
 ,MAX_CALLS_QUEUED = null;
 
commit;

update CC_F_ACD_QUEUE_INTERVAL set MIN_HANDLE_TIME = null
 ,MEDIAN_HANDLE_TIME = null
 ,STDDEV_HANDLE_TIME = null
 ,MIN_SPEED_TO_HANDLE = null
 ,MAX_SPEED_TO_HANDLE = null
 ,MEDIAN_SPEED_TO_HANDLE = null
 ,STDDEV_SPEED_TO_HANDLE = null
 ,MIN_SPEED_OF_ANSWER = null
 ,MEDIAN_SPEED_OF_ANSWER = null
 ,STDDEV_SPEED_OF_ANSWER = null
 ,LABOR_MINUTES_TOTAL = null
 ,CONTACT_INVENTORY = null
 ,CONTACT_INVENTORY_JEOPARDY = null
 ,MIN_CONTACT_INVENTORY_AGE = null
 ,MAX_CONTACT_INVENTORY_AGE = null
 ,MEAN_CONTACT_INVENTORY_AGE = null
 ,MEDIAN_CONTACT_INVENTORY_AGE = null
 ,STDDEV_CONTACT_INVENTORY_AGE = null
 ,CALLS_ON_HOLD = null
 ,CONTACTS_BLOCKED = null
 ,ICR_DEFAULT_ROUTED = null
 ,NETWORK_DEFAULT_ROUTED = null
 ,RETURN_BUSY = null
 ,CALLS_RONA = null
 ,RETURN_RELEASE = null
 ,CALLS_ROUTED_NON_AGENT = null
 ,ERROR_COUNT = null
 ,AGENT_ERROR_COUNT = null
 ,RETURN_RING = null
 ,INCOMPLETE_CALLS = null
 ,MAX_CALLS_QUEUED = null
, LABOR_MINUTES_AVAILABLE = null
, HEADCOUNT_TOTAL = null
, HEADCOUNT_UNAVAILABLE = null;

commit;