ALTER TABLE NYHX_ETL_COMPLAINTS_INCIDENTS
MODIFY (CREATED_BY_GROUP NULL,
        CREATED_BY_NAME NULL,
        CREATE_DT NULL);

ALTER TABLE NYHX_ETL_COMPL_INCIDENTS_OLTP
MODIFY (CREATED_BY_GROUP NULL,
        CREATED_BY_NAME NULL,
        CREATE_DT NULL);

ALTER TABLE NYHX_ETL_COMPL_INCIDN_WIP_BPM
MODIFY (CREATED_BY_GROUP NULL,
        CREATED_BY_NAME NULL,
        CREATE_DT NULL);

