UPDATE MAXDAT.PROCESS_BPM_QUEUE_JOB_CTRL_CFG
SET MAX_TOTAL_NUM_JOBS = 64
	, NUM_JOBS_TO_DEL_DURING_ADJUST = 1
	, NUM_JOBS_TO_ADD_DURING_ADJUST = 4
	, NUM_GROUP_CYCLES_BEFORE_ADD = 2
	, CONTROL_JOB_SLEEP_SECONDS = 30
	, LOCK_TIMEOUT_SECONDS = 300
	, PROCESS_SLEEP_SECONDS = 120
	, PROCESS_BATCH_SECONDS = 10
	, START_DELAY_SECONDS = 10
	, STOP_DELAY_SECONDS = 15
	, PROCESSING_ENABLED = 'Y';

UPDATE MAXDAT.PROCESS_BPM_QUEUE_JOB_CONFIG
SET PBQJC_ID = 1
	, BSL_ID = 0
	, BDM_ID = 0
	, MIN_NUM_JOBS = 1
	, INIT_NUM_JOBS = 2
	, MAX_NUM_JOBS = 24
	, BATCH_SIZE = 100
	, ENABLED = 'Y'
WHERE PBQJC_ID = 1;

COMMIT;