--------------------------------------------------------
--  DDL for Table EMRS_D_PROVIDER_SPECIALTY
--------------------------------------------------------

  CREATE TABLE "EMRS_D_PROVIDER_SPECIALTY" 
   (	"PROVIDER_NUMBER" NUMBER(22,0), 
	"PROVIDER_SPECIALTY_CODE_ID" NUMBER(22,0), 
	"CREATED_BY" VARCHAR2(18), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_DATA" ;
