--------------------------------------------------------
--  DDL for Table EMRS_D_HEADSTART_GRANTEE
--------------------------------------------------------

  CREATE TABLE "EMRS_D_HEADSTART_GRANTEE" 
   (	"HEADSTART_GRANTEE_ID" NUMBER(*,0), 
	"GRANTEE_NAME" VARCHAR2(50), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"SOURCE_RECORD_ID" NUMBER(*,0), 
	"SR_REGION_ID" NUMBER(*,0), 
	"VERSION" NUMBER(2,0), 
	"DATE_OF_VALIDITY_START" DATE, 
	"DATE_OF_VALIDITY_END" DATE, 
	"CREATED_BY" VARCHAR2(18), 
	"DATE_CREATED" DATE, 
	"UPDATED_BY" VARCHAR2(18), 
	"DATE_UPDATED" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MAXDAT_DATA" ;

   COMMENT ON COLUMN "EMRS_D_HEADSTART_GRANTEE"."HEADSTART_GRANTEE_ID" IS 'Head Start Grantee';
   COMMENT ON COLUMN "EMRS_D_HEADSTART_GRANTEE"."GRANTEE_NAME" IS 'Grantee Name';
   COMMENT ON COLUMN "EMRS_D_HEADSTART_GRANTEE"."START_DATE" IS 'Grantee Start Date';
   COMMENT ON COLUMN "EMRS_D_HEADSTART_GRANTEE"."END_DATE" IS 'Grantee End Date';
   COMMENT ON COLUMN "EMRS_D_HEADSTART_GRANTEE"."SOURCE_RECORD_ID" IS 'Source Record ID';
   COMMENT ON COLUMN "EMRS_D_HEADSTART_GRANTEE"."SR_REGION_ID" IS 'Source-System Region ID';
   COMMENT ON COLUMN "EMRS_D_HEADSTART_GRANTEE"."VERSION" IS 'Type-2 SCD Version Number';
   COMMENT ON COLUMN "EMRS_D_HEADSTART_GRANTEE"."DATE_OF_VALIDITY_START" IS 'ETL Required Column to Designate the Start-Date for a Valid Slowly Changing Dimension (SCD) Record';
   COMMENT ON COLUMN "EMRS_D_HEADSTART_GRANTEE"."DATE_OF_VALIDITY_END" IS 'ETL Required Column to Designate the End-Date for a Valid Slowly Changing Dimension (SCD) Record';
   COMMENT ON COLUMN "EMRS_D_HEADSTART_GRANTEE"."CREATED_BY" IS 'Warehouse Load Created By';
   COMMENT ON COLUMN "EMRS_D_HEADSTART_GRANTEE"."DATE_CREATED" IS 'Warehouse Load Creation Date';
   COMMENT ON COLUMN "EMRS_D_HEADSTART_GRANTEE"."UPDATED_BY" IS 'Warehouse Load Updated By';
   COMMENT ON COLUMN "EMRS_D_HEADSTART_GRANTEE"."DATE_UPDATED" IS 'Warehouse Load Date Updated';
