--------------------------------------------------------
--  Constraints for Table EMRS_D_AA_COUNTYCONTRACT
--------------------------------------------------------

  ALTER TABLE "EMRS_D_AA_COUNTYCONTRACT" ADD CONSTRAINT "AA_COUNTYCONTRACT_PK" PRIMARY KEY ("AA_COUNTYCONTRACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_INDX"  ENABLE;
