--------------------------------------------------------
--  Constraints for Table EMRS_D_ENROLLMENT_REJECTION
--------------------------------------------------------

  ALTER TABLE "EMRS_D_ENROLLMENT_REJECTION" ADD CONSTRAINT "ENRL_REJECTREASON_UK" UNIQUE ("ENROLLMENT_ID", "REJECTION_ERROR_REASON_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MAXDAT_INDX"  ENABLE;
