--------------------------------------------------------
--  DDL for Index SELECTIONTRANSHISTPK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SELECTIONTRANSHISTPK" ON "EMRS_D_SELECTION_TRANS_HISTORY" ("SELECTION_TRANS_HISTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MAXDAT_INDX" ;

 CREATE INDEX "IDX1_SLCTTXHIST_SOURCERECID" ON "EMRS_D_SELECTION_TRANS_HISTORY" ("SOURCE_RECORD_ID") TABLESPACE "MAXDAT_INDX" ;
