REM INSERTING into OFFICE
SET DEFINE OFF;
Insert into OFFICE (OFFICE_ID,LOCALE_ID,TIMEZONE_ID,NAME,DESCRIPTION,DELETE_DATE,OWNER_USER,MODIFY_USER,OWNER_DATE,MODIFY_DATE) values (1000,null,102,'ILN002',null,null,2,null,to_date('07-JAN-13','DD-MON-RR'),null);
Insert into OFFICE (OFFICE_ID,LOCALE_ID,TIMEZONE_ID,NAME,DESCRIPTION,DELETE_DATE,OWNER_USER,MODIFY_USER,OWNER_DATE,MODIFY_DATE) values (1001,null,102,'ILN007',null,null,2,null,to_date('07-JAN-13','DD-MON-RR'),null);
Insert into OFFICE (OFFICE_ID,LOCALE_ID,TIMEZONE_ID,NAME,DESCRIPTION,DELETE_DATE,OWNER_USER,MODIFY_USER,OWNER_DATE,MODIFY_DATE) values (1002,null,102,'MIC002',null,null,2,null,to_date('23-SEP-13','DD-MON-RR'),null);
COMMIT;