CREATE TABLE EMRS_D_CASE_CLIENT(
CASE_CLIENT_ID NUMBER(*,0),
SOURCE_RECORD_ID NUMBER(*,0),
CASE_NUMBER	NUMBER(*,0),
CLIENT_NUMBER	NUMBER(*,0),
CSCL_STATUS_BEGIN_DATE	DATE,
CSCL_CLOSE_REASON	VARCHAR2(240),
CSCL_RELATIONSHIP_CD	VARCHAR2(32),
CSCL_ELIG_DETERMINATION_DATE	DATE,
CSCL_MEDICAL_IND	VARCHAR2(1 ),
CSCL_STATUS_END_DATE	DATE,
CSCL_BYB_TEMP_ID	VARCHAR2(32),
CSCL_APPL_CLIENT_ID	NUMBER(18,0),
CSCL_ACTUAL_TERM_DATE	DATE,
CSCL_PACMIS_STATUS_CD	VARCHAR2(32),
CSCL_LEGACY	VARCHAR2(1),
RHSP	VARCHAR2(1),
RHGA	VARCHAR2(1),
CSCL_STATUS_CD	VARCHAR2(2),
CSCL_ADLK_ID	VARCHAR2(32),
CSCL_RES_ADDR_ID	NUMBER(18,0),
CSCL_ELIG_BEGIN_DT	DATE,
CSCL_ELIG_END_DT	DATE,
ANNIVERSARY_DT	DATE,
MANAGED_CARE_PROGRAM	VARCHAR2(32),
PROGRAM_STATUS_CD	VARCHAR2(32),
ELIG_BEGIN_ND	NUMBER(8,0),
ELIG_END_ND	NUMBER(8,0),
EPISODE_ID	NUMBER(18,0),
CSCL_GENERIC_FIELD1_DATE	DATE,
CSCL_GENERIC_FIELD2_DATE	DATE,
CSCL_GENERIC_FIELD3_NUM	NUMBER(18,0),
CSCL_GENERIC_FIELD4_NUM	NUMBER(18,0),
CSCL_GENERIC_FIELD5_TXT	VARCHAR2(256),
CSCL_GENERIC_FIELD6_TXT	VARCHAR2(256),
CSCL_GENERIC_FIELD7_TXT	VARCHAR2(256),
CSCL_GENERIC_FIELD8_TXT	VARCHAR2(256),
CSCL_GENERIC_FIELD9_TXT	VARCHAR2(256),
CSCL_GENERIC_FIELD10_TXT	VARCHAR2(256),
CSCL_GENERIC_REF11_ID	NUMBER(18,0),
CSCL_GENERIC_REF12_ID	NUMBER(18,0),
STATUS_BEGIN_NDT	NUMBER(18,0),
STATUS_END_NDT	NUMBER(18,0),
CHANGE_NOTES	VARCHAR2(1024),
RECORD_DATE DATE, 
RECORD_TIME VARCHAR2(10), 
RECORD_NAME VARCHAR2(80), 
MODIFIED_DATE DATE, 
MODIFIED_TIME VARCHAR2(10), 
MODIFIED_NAME VARCHAR2(80),
DATE_CREATED DATE, 
CREATED_BY VARCHAR2(18), 
UPDATED_BY VARCHAR2(18), 
DATE_UPDATED DATE) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_DATA" ;

  CREATE UNIQUE INDEX "CASE_CLIENT_PK" ON "EMRS_D_CASE_CLIENT" ("CASE_CLIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_INDX" ;

  ALTER TABLE "EMRS_D_CASE_CLIENT" MODIFY ("CASE_CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_D_CASE_CLIENT" ADD CONSTRAINT "CASE_CLIENT_PK" PRIMARY KEY ("CASE_CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_INDX"  ENABLE;

 -- ALTER TABLE "EMRS_D_CASE_CLIENT" ADD CONSTRAINT "CSCL_CLIENTNUM_FK" FOREIGN KEY ("CLIENT_NUMBER")
 -- REFERENCES "EMRS_D_CLIENT_REF" ("CLIENT_NUMBER") ENABLE;

  --ALTER TABLE "EMRS_D_CASE_CLIENT" ADD CONSTRAINT "CSCL_CASENUM_FK" FOREIGN KEY ("CASE_NUMBER")
  --REFERENCES "EMRS_D_CASE_REF" ("CASE_NUMBER") ENABLE;

  CREATE INDEX IDX1_CASECLIENT ON EMRS_D_CASE_CLIENT(source_record_id) TABLESPACE MAXDAT_INDX;  
  CREATE INDEX IDX2_CASECLIENT_PRG ON EMRS_D_CASE_CLIENT(MANAGED_CARE_PROGRAM) TABLESPACE MAXDAT_INDX; 
  CREATE INDEX IDX3_CASECLIENT_SDT ON EMRS_D_CASE_CLIENT(CSCL_STATUS_BEGIN_DATE) TABLESPACE MAXDAT_INDX;   
  CREATE INDEX IDX4_CASECLIENT_SDT ON EMRS_D_CASE_CLIENT(CSCL_ELIG_BEGIN_DT) TABLESPACE MAXDAT_INDX; 

