--------------------------------------------------------
--  Constraints for Table EMRS_D_SELECTION_MISSING_INFO
--------------------------------------------------------

  ALTER TABLE "EMRS_D_SELECTION_MISSING_INFO" ADD CONSTRAINT "SELECTIONMIPK" PRIMARY KEY ("SELECTION_MISSING_INFO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MAXDAT_INDX"  ENABLE;
  ALTER TABLE "EMRS_D_SELECTION_MISSING_INFO" MODIFY ("SELECTION_MISSING_INFO_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_D_SELECTION_MISSING_INFO" MODIFY ("SOURCE_RECORD_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_D_SELECTION_MISSING_INFO" MODIFY ("SELECTION_TRANSACTION_ID" NOT NULL ENABLE);
