--------------------------------------------------------
--  DDL for Index SELECTIONMIPK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SELECTIONMIPK" ON "EMRS_D_SELECTION_MISSING_INFO" ("SELECTION_MISSING_INFO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MAXDAT_INDX" ;

CREATE INDEX "SLCTMI_SLCTTRANS_FK_I" ON "EMRS_D_SELECTION_MISSING_INFO" ("SELECTION_TRANSACTION_ID") TABLESPACE "MAXDAT_INDX" ;

CREATE INDEX "SLCTMI_REJREASON_FK_I" ON "EMRS_D_SELECTION_MISSING_INFO" ("REJECTION_ERROR_REASON_ID") TABLESPACE "MAXDAT_INDX" ;

CREATE INDEX "SLCTMI_ENRERRORCODE_FK_I" ON "EMRS_D_SELECTION_MISSING_INFO" ("ENROLLMENT_ERROR_CODE_ID") TABLESPACE "MAXDAT_INDX" ;

CREATE INDEX "IDX1_SLCTMI_SOURCERECID" ON "EMRS_D_SELECTION_MISSING_INFO" ("SOURCE_RECORD_ID") TABLESPACE "MAXDAT_INDX" ;