CREATE SEQUENCE  SEQ_CECOM_ID;

CREATE OR REPLACE PUBLIC SYNONYM SEQ_CECOM_ID FOR SEQ_CECOM_ID;



CREATE SEQUENCE  SEQ_CMORCHLD_ID;

CREATE OR REPLACE PUBLIC SYNONYM SEQ_CMORCHLD_ID FOR SEQ_CMORCHLD_ID;  