alter table cc_s_call_detail
add Call_Disposition number;

alter table cc_f_call
add Call_disposition number;

CREATE OR REPLACE VIEW CC_F_CALL_SV (F_CALL_ID, D_DATE_ID, D_CONTACT_QUEUE_ID, QUEUE_NUMBER, D_AGENT_ID, AGENT_LOGIN_ID, D_PROJECT_ID, D_PROGRAM_ID, CALL_SEGMENT_ID, CALL_DATE, SOURCE_CALL_ID, DNIS, DISPOSITION, TRANSFER_TO, CALL_SEGMENT_END_DT, LANGUAGE, ANI_PHONE_NUMBER, QUEUE_TIME_SECONDS, RING_TIME_SECONDS, HOLD_TIME_SECONDS, AFTER_CALL_WORK_SECONDS, TALK_TIME_SECONDS, IVR_TIME_SECONDS, XFERRED_OUT_FLAG, VOICEMAIL_FLAG, CALL_ABANDONED_FLAG, CALL_REFERENCE_ID, CALL_DURATION, ACTIVITY_ID, ROUTER_SEQUENCE, CALL_OFFERED_FLAG, CALL_ANSWERED_FLAG, DATETIME, CREATE_DATE, LAST_UPDATE_DATE, LAST_UPDATE_BY, CALL_DISPOSITION) AS 
SELECT CC_F_CALL.F_CALL_ID,CC_F_CALL.D_DATE_ID,CC_F_CALL.D_CONTACT_QUEUE_ID,CC_F_CALL.QUEUE_NUMBER,
CC_F_CALL.D_AGENT_ID,CC_F_CALL.AGENT_LOGIN_ID,CC_D_CONTACT_QUEUE.D_PROJECT_ID,CC_D_CONTACT_QUEUE.D_PROGRAM_ID, CC_F_CALL.CALL_SEGMENT_ID,CC_F_CALL.CALL_DATE,
CC_F_CALL.SOURCE_CALL_ID,CC_F_CALL.DNIS,CC_F_CALL.DISPOSITION,CC_F_CALL.TRANSFER_TO,CC_F_CALL.CALL_SEGMENT_END_DT,CC_F_CALL.LANGUAGE,
CC_F_CALL.ANI_PHONE_NUMBER,CC_F_CALL.QUEUE_TIME_SECONDS, CC_F_CALL.RING_TIME_SECONDS, CC_F_CALL.HOLD_TIME_SECONDS,
CC_F_CALL.AFTER_CALL_WORK_SECONDS, CC_F_CALL.TALK_TIME_SECONDS, CC_F_CALL.IVR_TIME_SECONDS, CC_F_CALL.XFERRED_OUT_FLAG,
CC_F_CALL.VOICEMAIL_FLAG, 
case when CC_F_CALL.DISPOSITION = 'ABANDONED' then 1 else 0 end CALL_ABANDONED_FLAG, CC_F_CALL.CALL_REFERENCE_ID, CC_F_CALL.CALL_DURATION,
CC_F_CALL.ACTIVITY_ID, CC_F_CALL.ROUTER_SEQUENCE, CC_F_CALL.CALL_OFFERED_FLAG, CC_F_CALL.CALL_ANSWERED_FLAG,
CC_F_CALL.DATETIME, CC_F_CALL.CREATE_DATE,CC_F_CALL.LAST_UPDATE_DATE,CC_F_CALL.LAST_UPDATE_BY, CC_F_CALL.CALL_DISPOSITION
FROM CC_F_CALL
INNER JOIN CC_D_CONTACT_QUEUE ON CC_F_CALL.D_CONTACT_QUEUE_ID = CC_D_CONTACT_QUEUE.D_CONTACT_QUEUE_ID;