ALTER TABLE CC_S_TMP_CISCO_A_SG_INTERVAL ADD(AGENTROUTINGGROUPNUMBER NUMBER);

ALTER TABLE CC_S_TMP_CISCO_A_SG_INTERVAL ADD(AGENTROUTINGGROUPTYPE VARCHAR2(50));

alter table CC_S_TMP_TERMINATN_CALL_DETAIL
add (CallGUID VARCHAR2(50)
, ActivityID VARCHAR2(50)
, CallReferenceID VARCHAR2(40)
, DNIS VARCHAR2(10)
, Duration NUMBER
, CallDisposition NUMBER
, RouterCallKey NUMBER
, NetworkSkillGroupQTime NUMBER
, NetQTime NUMBER
, ANI VARCHAR2(50)
, RingTime NUMBER
, TimeToAband NUMBER	
);