CREATE OR REPLACE FORCE VIEW CC_F_PROGRAM_BY_INTERVAL_SV 
AS
with QUEUE_INTERVAL as 
(
SELECT 
      CC_F_ACTUALS_QUEUE_INTERVAL.D_DATE_ID as Q_D_DATE_ID,
      CC_F_ACTUALS_QUEUE_INTERVAL.D_INTERVAL_ID as Q_D_INTERVAL_ID,
      CC_D_CONTACT_QUEUE.D_PROJECT_ID as Q_D_PROJECT_ID,
      CC_D_CONTACT_QUEUE.D_PROGRAM_ID as Q_D_PROGRAM_ID,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_RECEIVED_FROM_IVR) as CONTACTS_RECEIVED_FROM_IVR,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ANSWERED) as CALLS_ANSWERED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.RAW_CONTACTS_OFFERED) as RAW_CONTACTS_OFFERED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_OFFERED) as CONTACTS_OFFERED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_HANDLED) as CONTACTS_HANDLED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_ABANDONED) as CONTACTS_ABANDONED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.LABOR_MINUTES_TOTAL) as LABOR_MINUTES_TOTAL,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.LABOR_MINUTES_AVAILABLE) as LABOR_MINUTES_AVAILABLE,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.LABOR_MINUTES_WAITING) as LABOR_MINUTES_WAITING,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HEADCOUNT_TOTAL) as HEADCOUNT_TOTAL,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HEADCOUNT_AVAILABLE) as HEADCOUNT_AVAILABLE,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HEADCOUNT_UNAVAILABLE) as HEADCOUNT_UNAVAILABLE,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACT_INVENTORY) as CONTACT_INVENTORY,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_TRANSFERRED) as CONTACTS_TRANSFERRED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.OUTFLOW_CONTACTS) as OUTFLOW_CONTACTS,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ANSWER_WAIT_TIME_TOTAL) as ANSWER_WAIT_TIME_TOTAL,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ABANDON_TIME_TOTAL) as ABANDON_TIME_TOTAL,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.TALK_TIME_TOTAL) as TALK_TIME_TOTAL,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.AFTER_CALL_WORK_TIME_TOTAL) as AFTER_CALL_WORK_TIME_TOTAL,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SERVICE_LEVEL_ANSWERED_COUNT) as SERVICE_LEVEL_ANSWERED_COUNT,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SERVICE_LEVEL_ABANDONED) as SERVICE_LEVEL_ABANDONED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ON_HOLD) as CALLS_ON_HOLD,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HOLD_TIME_TOTAL) as HOLD_TIME_TOTAL,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SHORT_ABANDONS) as SHORT_ABANDONS,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_BLOCKED) as CONTACTS_BLOCKED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ICR_DEFAULT_ROUTED) as ICR_DEFAULT_ROUTED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.NETWORK_DEFAULT_ROUTED) as NETWORK_DEFAULT_ROUTED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.RETURN_BUSY) as RETURN_BUSY,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_RONA) as CALLS_RONA,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.RETURN_RELEASE) as RETURN_RELEASE,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ROUTED_NON_AGENT) as CALLS_ROUTED_NON_AGENT,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ERROR_COUNT) as ERROR_COUNT,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.AGENT_ERROR_COUNT) as AGENT_ERROR_COUNT,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.RETURN_RING) as RETURN_RING,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.INCOMPLETE_CALLS) as INCOMPLETE_CALLS,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_GIVEN_FORCE_DISCONNECT) as CALLS_GIVEN_FORCE_DISCONNECT,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_GIVEN_ROUTE_TO) as CALLS_GIVEN_ROUTE_TO,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SHORT_CALLS) as SHORT_CALLS,
      MAX(CC_F_ACTUALS_QUEUE_INTERVAL.MAX_ABANDON_TIME) as MAX_ABANDON_TIME,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ABANDON_THRESHOLD) as ABANDON_THRESHOLD,
      MAX(CC_F_ACTUALS_QUEUE_INTERVAL.MAX_CALLS_QUEUED) as MAX_CALLS_QUEUED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HANDLE_TIME) as HANDLE_TIME,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CTVRU_TIME) as CTVRU_TIME,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SERVICE_LEVEL_CALLS) as SERVICE_LEVEL_CALLS,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ROUTER_QUEUE_WAIT_TIME) as ROUTER_QUEUE_WAIT_TIME,
      MAX(CC_F_ACTUALS_QUEUE_INTERVAL.MAX_SPEED_OF_ANSWER) as MAX_SPEED_OF_ANSWER,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACT_INVENTORY_JEOPARDY) as CONTACT_INVENTORY_JEOPARDY,
     ROUND( ( CASE WHEN SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_OFFERED)!=0 THEN (SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HANDLE_TIME)/SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_OFFERED))ELSE NULL END ),2) MEAN_HANDLE_TIME,
      ROUND(( CASE WHEN SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ANSWERED)!=0 THEN (SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SERVICE_LEVEL_CALLS)/SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ANSWERED))ELSE NULL END ),2) SERVICE_LEVEL_ANSWERED_PERCENT,
     ROUND(( CASE WHEN SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ANSWERED)!=0 THEN (SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ROUTER_QUEUE_WAIT_TIME)/SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ANSWERED))ELSE NULL END ),2) MEAN_SPEED_OF_ANSWER,
     ROUND(( CASE WHEN SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_OFFERED)!=0 THEN ((SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CTVRU_TIME) + SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ANSWER_WAIT_TIME_TOTAL) + SUM(CC_F_ACTUALS_QUEUE_INTERVAL.TALK_TIME_TOTAL) + SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HOLD_TIME_TOTAL))/SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_OFFERED))ELSE NULL END ),2) MEAN_SPEED_TO_HANDLE,
     ROUND( ( CASE WHEN SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_ABANDONED)!=0 THEN (SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ABANDON_TIME_TOTAL)/SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_ABANDONED))ELSE NULL END ),2) AVG_TIME_TO_ABANDON
    FROM CC_F_ACTUALS_QUEUE_INTERVAL
   INNER JOIN CC_D_CONTACT_QUEUE ON CC_F_ACTUALS_QUEUE_INTERVAL.D_CONTACT_QUEUE_ID = CC_D_CONTACT_QUEUE.D_CONTACT_QUEUE_ID
   --where d_interval_id in ( 96771, 96753)
    GROUP BY CC_F_ACTUALS_QUEUE_INTERVAL.D_DATE_ID,
    CC_F_ACTUALS_QUEUE_INTERVAL.D_INTERVAL_ID,
    CC_D_CONTACT_QUEUE.D_PROJECT_ID,
    CC_D_CONTACT_QUEUE.D_PROGRAM_ID),
AGENT_RTG_GRP_INTERVAL as
(
SELECT 
       CC_F_AGENT_RTG_GRP_INTERVAL.D_DATE_ID as ARG_D_DATE_ID,
       CC_F_AGENT_RTG_GRP_INTERVAL.D_INTERVAL_ID as ARG_D_INTERVAL_ID,
       CC_D_PROJECT.PROJECT_ID AS ARG_D_PROJECT_ID,
       CC_D_PROGRAM.PROGRAM_ID as ARG_D_PROGRAM_ID,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.HANDLE_CALLS_COUNT) as                 HANDLE_CALLS_COUNT,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.HANDLE_TIME_SECONDS) as 	              HANDLE_TIME_SECONDS,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.INTERNAL_CALLS_COUNT) as 	       INTERNAL_CALLS_COUNT,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.INTERNAL_SECONDS) as 		       INTERNAL_SECONDS,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.EXTERNAL_CALLS_COUNT) as 	       EXTERNAL_CALLS_COUNT,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.EXTERNAL_SECONDS) as 		       EXTERNAL_SECONDS,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.HOLD_SECONDS) as 		       HOLD_SECONDS,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.RING_SECONDS) as 		       RING_SECONDS,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.TALK_SECONDS) as 		       TALK_SECONDS,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.WRAP_SECONDS) as 		       WRAP_SECONDS,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.TALK_RESERVE_SECONDS) as 	       TALK_RESERVE_SECONDS,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.PREDICTIVE_TALK_SECONDS) as 	       PREDICTIVE_TALK_SECONDS,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.PREVIEW_TALK_SECONDS) as 	       PREVIEW_TALK_SECONDS,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.PREDICTIVE_CALLS_COUNT) as 	       PREDICTIVE_CALLS_COUNT,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.PREVIEW_CALLS_COUNT) as 	               PREVIEW_CALLS_COUNT,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.BREAK_TIME) as 			       BREAK_TIME,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.CONSULTATION_TIME) as 		       CONSULTATION_TIME,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.WALKAWAY_TIME) as 		       WALKAWAY_TIME,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.BUSYONDNTIME) as 		       BUSYONDNTIME,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.PAYROLL_COUNT) as 		       PAYROLL_COUNT,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.ATTRITED_COUNT) as 		       ATTRITED_COUNT,
       SUM(CC_F_AGENT_RTG_GRP_INTERVAL.CALLS_RETURNED_TO_QUEUE) as 	       CALLS_RETURNED_TO_QUEUE
       FROM CC_F_AGENT_RTG_GRP_INTERVAL
       INNER JOIN CC_C_AGENT_RTG_GRP ON (CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_ROUTING_GROUP_NUMBER = CC_C_AGENT_RTG_GRP.AGENT_ROUTING_GROUP_NUMBER AND
                                               CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_ROUTING_GROUP_TYPE = CC_C_AGENT_RTG_GRP.AGENT_ROUTING_GROUP_TYPE)
       INNER JOIN CC_D_PROJECT ON CC_C_AGENT_RTG_GRP.PROJECT_NAME = CC_D_PROJECT.PROJECT_NAME
       INNER JOIN CC_D_PROGRAM ON CC_C_AGENT_RTG_GRP.PROGRAM_NAME = CC_D_PROGRAM.PROGRAM_NAME
      -- where d_interval_id in ( 96771, 96753)
       GROUP BY 
       CC_F_AGENT_RTG_GRP_INTERVAL.D_DATE_ID,
       CC_F_AGENT_RTG_GRP_INTERVAL.D_INTERVAL_ID,
       CC_D_PROJECT.PROJECT_ID ,
       CC_D_PROGRAM.PROGRAM_ID),
COMBINATION as
(SELECT * FROM QUEUE_INTERVAL
FULL OUTER JOIN AGENT_RTG_GRP_INTERVAL ON  QUEUE_INTERVAL.Q_D_DATE_ID = AGENT_RTG_GRP_INTERVAL.ARG_D_DATE_ID
                           AND QUEUE_INTERVAL.Q_D_INTERVAL_ID = AGENT_RTG_GRP_INTERVAL.ARG_D_INTERVAL_ID
                           AND QUEUE_INTERVAL.Q_D_PROJECT_ID = AGENT_RTG_GRP_INTERVAL.ARG_D_PROJECT_ID
                           AND QUEUE_INTERVAL.Q_D_PROGRAM_ID = AGENT_RTG_GRP_INTERVAL.ARG_D_PROGRAM_ID)
SELECT
CASE WHEN Q_D_DATE_ID IS NULL THEN ARG_D_DATE_ID ELSE Q_D_DATE_ID END D_DATE_ID
,CASE WHEN Q_D_INTERVAL_ID IS NULL THEN ARG_D_INTERVAL_ID ELSE Q_D_INTERVAL_ID END D_INTERVAL_ID
,CASE WHEN Q_D_PROGRAM_ID IS NULL THEN ARG_D_PROGRAM_ID ELSE Q_D_PROGRAM_ID END D_PROGRAM_ID
,CASE WHEN Q_D_PROJECT_ID IS NULL THEN ARG_D_PROJECT_ID ELSE Q_D_PROJECT_ID END D_PROJECT_ID
,ABANDON_THRESHOLD
,ABANDON_TIME_TOTAL
,AFTER_CALL_WORK_TIME_TOTAL
,AGENT_ERROR_COUNT
,ANSWER_WAIT_TIME_TOTAL
,AVG_TIME_TO_ABANDON
,CALLS_ANSWERED
,CALLS_GIVEN_FORCE_DISCONNECT
,CALLS_GIVEN_ROUTE_TO
,CALLS_ON_HOLD
,CALLS_RONA
,CALLS_ROUTED_NON_AGENT
,CONTACTS_ABANDONED
,CONTACTS_BLOCKED
,CONTACTS_HANDLED
,CONTACTS_OFFERED
,RAW_CONTACTS_OFFERED
,CONTACTS_RECEIVED_FROM_IVR
,CONTACTS_TRANSFERRED
,CONTACT_INVENTORY
,CONTACT_INVENTORY_JEOPARDY
,CTVRU_TIME
,ERROR_COUNT
,HANDLE_TIME
,HEADCOUNT_AVAILABLE
,HEADCOUNT_TOTAL
,HEADCOUNT_UNAVAILABLE
,HOLD_TIME_TOTAL
,ICR_DEFAULT_ROUTED
,INCOMPLETE_CALLS
,LABOR_MINUTES_AVAILABLE
,LABOR_MINUTES_TOTAL
,LABOR_MINUTES_WAITING
,MAX_ABANDON_TIME
,MAX_CALLS_QUEUED
,MAX_SPEED_OF_ANSWER
,MEAN_HANDLE_TIME
,MEAN_SPEED_OF_ANSWER
,MEAN_SPEED_TO_HANDLE
,NETWORK_DEFAULT_ROUTED
,OUTFLOW_CONTACTS
,RETURN_BUSY
,RETURN_RELEASE
,RETURN_RING
,ROUTER_QUEUE_WAIT_TIME
,SERVICE_LEVEL_ABANDONED
,SERVICE_LEVEL_ANSWERED_COUNT
,SERVICE_LEVEL_ANSWERED_PERCENT
,SERVICE_LEVEL_CALLS
,SHORT_ABANDONS
,SHORT_CALLS
,TALK_TIME_TOTAL
,HANDLE_CALLS_COUNT
,HANDLE_TIME_SECONDS
,INTERNAL_CALLS_COUNT
,INTERNAL_SECONDS
,EXTERNAL_CALLS_COUNT
,EXTERNAL_SECONDS
,HOLD_SECONDS
,RING_SECONDS
,TALK_SECONDS
,WRAP_SECONDS
,TALK_RESERVE_SECONDS
,PREDICTIVE_TALK_SECONDS
,PREVIEW_TALK_SECONDS
,PREDICTIVE_CALLS_COUNT
,PREVIEW_CALLS_COUNT
,BREAK_TIME
,CONSULTATION_TIME
,WALKAWAY_TIME
,BUSYONDNTIME
,PAYROLL_COUNT
,ATTRITED_COUNT
,CALLS_RETURNED_TO_QUEUE
FROM COMBINATION;

grant select on CC_F_PROGRAM_BY_INTERVAL_SV to MAXDAT_READ_ONLY; 