ALTER TABLE CC_S_TMP_AVY_DAGENTPERFORMANCE ADD (
     BREAKTIME NUMBER (10,2) , 
     CONSULTATIONTIME NUMBER (10,2) , 
     WALKAWAYTIME NUMBER (10,2) 
);

ALTER TABLE CC_S_ACD_AGENT_ACTIVITY ADD (
     BREAK_TIME NUMBER (10,2) , 
     CONSULTATION_TIME NUMBER (10,2) , 
     WALKAWAY_TIME NUMBER (10,2) 
);


ALTER TABLE CC_F_AGENT_BY_DATE ADD (
     BREAK_TIME NUMBER (10,2) , 
     CONSULTATION_TIME NUMBER (10,2) , 
     WALKAWAY_TIME NUMBER (10,2) 
);


INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME)
VALUES ('0.3.1','110','110_ALTER_AGENT_TABLES_ADD_TIME_FIELDS');

COMMIT;