-- alter table ETL_JOB_CONFIG - increase the field length for JOB_SCHEDULE from 30 to 200
ALTER TABLE ETL_JOB_CONFIG MODIFY JOB_SCHEDULE VARCHAR2(200);

-- alter table ETL_JOB_CONFIG_AUDIT - increase the field length for JOB_SCHEDULE from 30 to 200
ALTER TABLE ETL_JOB_CONFIG_AUDIT MODIFY JOB_SCHEDULE VARCHAR2(200);

-- create sequences
CREATE SEQUENCE SEQ_ETL_JOB_HOLD_SKIP_ID START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999999 MINVALUE 1 CACHE 20;

-- create table ETL_JOB_HOLD_SKIP
CREATE TABLE ETL_JOB_HOLD_SKIP(
    SEQ_ID               NUMBER          NOT NULL, 
	JOB_ID_TO_HOLD       NUMBER          NOT NULL,
    JOB_ID_RUNNING       NUMBER          NOT NULL,
    SKIP_RUN             VARCHAR2(1)     NOT NULL,
    LAST_UPD_DT          DATE            NULL,
    LAST_UPD_USER        VARCHAR2(20)    NULL)
TABLESPACE MAXDAT_DATA;

-- add constraints to table ETL_JOB_CONFIG
ALTER TABLE ETL_JOB_HOLD_SKIP ADD CONSTRAINT ETL_JOB_HOLD_SKIP_PK PRIMARY KEY (SEQ_ID) USING INDEX TABLESPACE MAXDAT_INDX;
ALTER TABLE ETL_JOB_HOLD_SKIP MODIFY SEQ_ID DEFAULT SEQ_ETL_JOB_HOLD_SKIP_ID.NEXTVAL;
ALTER TABLE ETL_JOB_HOLD_SKIP ADD CONSTRAINT ETL_JOB_HOLD_SKIP_TO_HOLD_JOB_FK FOREIGN KEY (JOB_ID_TO_HOLD) REFERENCES ETL_JOB_CONFIG (JOB_ID);
ALTER TABLE ETL_JOB_HOLD_SKIP ADD CONSTRAINT ETL_JOB_HOLD_SKIP_RUNNING_JOB_FK FOREIGN KEY (JOB_ID_RUNNING) REFERENCES ETL_JOB_CONFIG (JOB_ID);
ALTER TABLE ETL_JOB_HOLD_SKIP ADD CONSTRAINT ETL_JOB_HOLD_SKIP_RUN_CHECK CHECK (SKIP_RUN IN ('Y','N'));

-- grant select on the table
GRANT SELECT ON ETL_JOB_HOLD_SKIP TO MAXDAT_READ_ONLY;

-- create view for ETL_JOB_HOLD_SKIP 
CREATE OR REPLACE VIEW ETL_JOB_HOLD_SKIP_SV AS 
SELECT
    SEQ_ID,
    JOB_ID_TO_HOLD,
    JOB_ID_RUNNING,
    SKIP_RUN,
    LAST_UPD_DT,
    LAST_UPD_USER
FROM ETL_JOB_HOLD_SKIP
WITH READ ONLY;

-- grant select on the view 
GRANT SELECT ON ETL_JOB_HOLD_SKIP_SV to MAXDAT_READ_ONLY;
/
