
ALTER TABLE S_METRIC_TEMPLATE ADD (
  REPORTING_PERIOD_TYPE VARCHAR(50)
  , IS_FORECAST_VARIANCE_PROCESSED VARCHAR2 (1)
  , IS_ACTUALS_TREND_PROCESSED VARCHAR2 (1)
  , IS_FORECAST VARCHAR2 (1)
  , IS_ACTUAL VARCHAR2 (1)
);

ALTER TABLE S_SLA_TEMPLATE ADD (
  REPORTING_PERIOD_TYPE VARCHAR(50)
);


INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME) 
VALUES ('2.3','005','005_ALTER_STAGING_TABLES');


COMMIT;
