ALTER TABLE CC_D_ACTIVITY_TYPE MODIFY (ACTIVITY_TYPE_NAME VARCHAR(50));

INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME) 
VALUES ('0.1.7','1','1_ALTER_ACTIVITY_TYPE_NAME');

COMMIT;
