
CREATE TABLE CC_S_TMP_AVY_ECSRSTAT
(
   CustID INTEGER,
   SequenceID NUMERIC(10,0),
   GUID VARCHAR(36),
   CCMID INTEGER,
   ProviderContactID VARCHAR(50),
   InterCallID INTEGER,
   ContactType INTEGER,
   ContactTypeName VARCHAR(30),
   ContactSubType VARCHAR(50),
   ContactProximity VARCHAR(50),
   Priority SMALLINT,
   Provider VARCHAR(50),
   SiteID INTEGER,
   SiteName VARCHAR(30),
   RemoteSiteID INTEGER,
   RemoteSiteName VARCHAR(30),
   Originator VARCHAR(256),
   Address VARCHAR(255),
   RoutePoint VARCHAR(30),
   ApplicationID INTEGER,
   ApplicationName VARCHAR(30),
   SourceApplicationName VARCHAR(30),
   ApplicationStartStamp timestamp,
   LastTreatmentID INTEGER,
   Treatment VARCHAR(50),
   LastTreatmentStamp timestamp,
   LastTreatmentTime INTEGER,
   SkillsetID INTEGER,
   SkillsetName VARCHAR(30),
   SkillsetQueuedStamp timestamp,
   LocalUserID INTEGER,
   AgentSurName VARCHAR(64),
   AgentGivenName VARCHAR(64),
   SupervisorSurName VARCHAR(64),
   SupervisorGivenName VARCHAR(64),
   AgentID VARCHAR(16),
   SupervisorID VARCHAR(16),
   OriginatedStamp timestamp,
   InitialDisposition VARCHAR(50),
   ServiceStamp timestamp,
   AppAbandonDelay INTEGER,
   AppAcceptedDelay INTEGER,
   SksAbandonDelay INTEGER,
   SksAcceptedDelay INTEGER,
   HandlingTime INTEGER,
   ConsultTime INTEGER,
   HoldTime INTEGER,
   NumberOfTimesOnHold INTEGER,
   NumberOfTimesRTQ INTEGER,
   FinalDisposition VARCHAR(50),
   FinalDispositionStamp timestamp,
   PresentingTime INTEGER,
   PCPTime INTEGER,
   PCPFirstCode VARCHAR(32),
   WaitTime INTEGER,
   NextAddress VARCHAR(255),
   NextSegmentID INTEGER,
   ContactOriginatedStamp timestamp,
   FinalDispositionInterval VARCHAR(255),
   ServiceInterval VARCHAR(255),
   OriginatedInterval VARCHAR(255),
   DisconnectSource VARCHAR(9),
   NumContactObserves INTEGER,
   NumContactBargeIns INTEGER,
   AnchoredMediaServer VARCHAR(50),
   PreferredMediaServer VARCHAR(50),
   PreferredMediaServerResult INTEGER,
   PreferredMediaServerResultDesc VARCHAR(80) 
)
;





INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME) 
	VALUES ('1.4.0','001','001_CREATE_CC_S_TMP_AVY_ECSRSTAT');

COMMIT;
