USE DATABASE PUREINSIGHTS_DEV;
USE SCHEMA PUBLIC;

CREATE OR REPLACE VIEW D_PI_ERROR_CODES_VW AS
SELECT ERRORID, ERRORCODE, MMS_ERROR_TYPE, GENESYS_ERROR_DESCRIPTION AS ERROR_DESCRIPTION,MMS_ERROR_DESCRIPTION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE
FROM RAW.C_SOURCE_ERROR_CODES
WHERE EFFECTIVE_END_DATE IS NULL
ORDER BY 1;    