
INSERT INTO CC_C_FILTER(FILTER_TYPE, VALUE) VALUES ('ACD_SKILL_GROUP_INC','18092');
INSERT INTO CC_C_FILTER(FILTER_TYPE, VALUE) VALUES ('ACD_SKILL_GROUP_INC','18093');
INSERT INTO CC_C_FILTER(FILTER_TYPE, VALUE) VALUES ('ACD_SKILL_GROUP_INC','18094');
INSERT INTO CC_C_FILTER(FILTER_TYPE, VALUE) VALUES ('ACD_SKILL_GROUP_INC','18095');
INSERT INTO CC_C_FILTER(FILTER_TYPE, VALUE) VALUES ('ACD_SKILL_GROUP_INC','18096');
INSERT INTO CC_C_FILTER(FILTER_TYPE, VALUE) VALUES ('ACD_SKILL_GROUP_INC','18097');
INSERT INTO CC_C_FILTER(FILTER_TYPE, VALUE) VALUES ('ACD_SKILL_GROUP_INC','18098');
INSERT INTO CC_C_FILTER(FILTER_TYPE, VALUE) VALUES ('ACD_SKILL_GROUP_INC','18143');
INSERT INTO CC_C_FILTER(FILTER_TYPE, VALUE) VALUES ('ACD_SKILL_GROUP_INC','18144');
INSERT INTO CC_C_FILTER(FILTER_TYPE, VALUE) VALUES ('ACD_SKILL_GROUP_INC','18145');
INSERT INTO CC_C_FILTER(FILTER_TYPE, VALUE) VALUES ('ACD_SKILL_GROUP_INC','18146');
INSERT INTO CC_C_FILTER(FILTER_TYPE, VALUE) VALUES ('ACD_SKILL_GROUP_INC','18147');
INSERT INTO CC_C_FILTER(FILTER_TYPE, VALUE) VALUES ('ACD_SKILL_GROUP_INC','18148');

  INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME) 
  VALUES ('0.1.6','101','101_CC_C_FILTER__INSERT_MISSING_SKILLS');
  
  COMMIT;