CREATE OR REPLACE VIEW MAXDAT_SUPPORT.D_ONBASE_DOC_CLIENT_APP_REL_SV
AS
SELECT d.document_id AS DOCUMENT_ID,
d.dcn AS DCN,
dl.client_id AS CLIENT_ID,
AL.APPLICATION_ID AS APPLICATION_ID,
D.CREATE_TS AS D_CREATE_TS,
D.DOC_TYPE_CD AS DOC_TYPE_CD,
D.DOC_FORM_TYPE AS DOC_FORM_TYPE
FROM DOCUMENT d
  LEFT JOIN DOC_LINK dl ON d.document_id = dl.document_id
  LEFT JOIN CLIENT cl ON dl.client_id = cl.clnt_client_id
  LEFT JOIN app_individual al ON cl.clnt_client_id = al.client_id
WHERE d.create_ts >= ADD_MONTHS(TRUNC(sysdate,'mm'),-13);

GRANT SELECT ON MAXDAT_SUPPORT.D_ONBASE_DOC_CLIENT_APP_REL_SV TO MAXDATSUPPORT_READ_ONLY; 
GRANT SELECT ON MAXDAT_SUPPORT.D_ONBASE_DOC_CLIENT_APP_REL_SV TO MAXDAT_REPORTS; 