ALTER TABLE CC_F_AGENT_BY_DATE
ADD ( PAYROLL_COUNT NUMBER (1) DEFAULT 0 NOT NULL,
	  ATTRITION_COUNT NUMBER (1) DEFAULT 0 NOT NULL);
	  
CREATE OR REPLACE VIEW CC_F_AGENT_BY_DATE_SV  AS
SELECT CC_F_AGENT_BY_DATE.* FROM CC_F_AGENT_BY_DATE ;

INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME) 
	VALUES ('2.12','001','001_ALTER_CC_F_AGENT_BY_DATE');

COMMIT;