insert into CC_C_FILTER (filter_type,value) values ('WFM_ORGANIZATION_INC','TEXAS');

INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME) 
VALUES ('0.2.3','101','101_OUTBOUND_WFM_ORG_TO_CC_C_FILTER');

commit;