CREATE OR REPLACE PROCEDURE MAXDAT_SUPPORT.UPDATE_CSC
AS
BEGIN
    execute immediate 'TRUNCATE TABLE MAXDAT_SUPPORT.CSC';    
    INSERT INTO MAXDAT_SUPPORT.CSC (CLIENT_ID,SEGMENT_TYPE_CD, SEGMENT_DETAIL_VALUE_2)
    SELECT client_id
    , segment_type_cd
    , SEGMENT_DETAIL_VALUE_2
    FROM eb.elig_segment_and_details 
    WHERE segment_type_cd='PL' 
    AND END_ND = 99991231 
    AND SEGMENT_DETAIL_VALUE_2 IN ('02','03', '55','56','57','58','73','74');
    COMMIT;
END;



