CREATE OR REPLACE VIEW EMRS_D_PROVIDER_SPECIALTY_SV
AS
  SELECT network_id AS PROVIDER_NUMBER ,
    COALESCE(specialty_type_cd, '0') AS PROVIDER_SPECIALTY_CODE,
    create_ts AS DATE_CREATED ,
    created_by AS CREATED_BY,
    update_ts AS DATE_UPDATED,
    updated_by AS UPDATED_BY
  FROM network_specialty;
  
  GRANT SELECT ON MAXDAT_SUPPORT.EMRS_D_PROVIDER_SPECIALTY_SV TO MAXDAT_REPORTS; 