--Disable Constraint for duration of cleanup script
ALTER TABLE CC_D_CONTACT_QUEUE
DISABLE CONSTRAINT CC_D_CONTACT_QUEUE__UN;


--Set duplicate records to an invalid effective date
MERGE INTO CC_D_CONTACT_QUEUE a
using ( SELECT * 
	FROM 
	(SELECT
		D_CONTACT_QUEUE_ID
	  , QUEUE_NUMBER
	  , VERSION
	  , RECORD_EFF_DT
	  , RECORD_END_DT
	  , LEAD (RECORD_EFF_DT , 1, NULL) OVER (PARTITION BY QUEUE_NUMBER ORDER BY QUEUE_NUMBER, VERSION, RECORD_EFF_DT, RECORD_END_DT) as NEXT_EFF_DT
	  FROM CC_D_CONTACT_QUEUE a
	  ORDER BY QUEUE_NUMBER, VERSION, RECORD_EFF_DT, RECORD_END_DT
	  )sub 
	WHERE RECORD_END_DT > NEXT_EFF_DT
	ORDER BY QUEUE_NUMBER, VERSION, RECORD_EFF_DT, RECORD_END_DT
) b
ON (a.D_CONTACT_QUEUE_ID = b.D_CONTACT_QUEUE_ID)
WHEN matched THEN UPDATE SET a.RECORD_EFF_DT = TO_DATE('2999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS');


--Update valid records to cover any gaps created by duplicate records
MERGE INTO CC_D_CONTACT_QUEUE a
using ( SELECT * 
	FROM 
	(SELECT
		D_CONTACT_QUEUE_ID
	  , QUEUE_NUMBER
	  , VERSION
	  , RECORD_EFF_DT
	  , RECORD_END_DT
	  , LEAD (RECORD_EFF_DT , 1, NULL) OVER (PARTITION BY QUEUE_NUMBER ORDER BY QUEUE_NUMBER, VERSION, RECORD_EFF_DT, RECORD_END_DT) as NEXT_EFF_DT
	  FROM CC_D_CONTACT_QUEUE a
	  ORDER BY QUEUE_NUMBER, VERSION, RECORD_EFF_DT, RECORD_END_DT
	  )sub 
	WHERE RECORD_END_DT < NEXT_EFF_DT
    AND NEXT_EFF_DT != TO_DATE('2999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
	ORDER BY QUEUE_NUMBER, VERSION, RECORD_EFF_DT, RECORD_END_DT
) b
ON (a.D_CONTACT_QUEUE_ID = b.D_CONTACT_QUEUE_ID)
WHEN matched THEN UPDATE SET a.RECORD_END_DT = b.NEXT_EFF_DT;


--Delete Duplicate Fact Tables assoc. to invalid D_CONTACT_QUEUE record

DELETE FROM CC_F_ACTUALS_QUEUE_INTERVAL
WHERE D_CONTACT_QUEUE_ID IN (
  SELECT sub.D_CONTACT_QUEUE_ID
  FROM CC_D_CONTACT_QUEUE sub
  WHERE sub.RECORD_EFF_DT = TO_DATE('2999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
);

--Delete duplicate CONTACT_QUEUE records
DELETE FROM CC_D_CONTACT_QUEUE a 
WHERE a.RECORD_EFF_DT = TO_DATE('2999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS');

--Re-Enable Unique Constraint
ALTER TABLE CC_D_CONTACT_QUEUE
ENABLE CONSTRAINT CC_D_CONTACT_QUEUE__UN;

INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME)
VALUES ('1.2.0','004','004_DEDUPE_CONTACT_QUEUES');

COMMIT;