CREATE OR REPLACE PUBLIC SYNONYM EMRS_D_PROVIDER FOR EMRS_D_PROVIDER;

CREATE OR REPLACE PUBLIC SYNONYM EMRS_D_PROVIDER_SPECIALTY FOR EMRS_D_PROVIDER_SPECIALTY;

CREATE OR REPLACE PUBLIC SYNONYM EMRS_D_PROVIDER_SPECIALTY_CODE FOR EMRS_D_PROVIDER_SPECIALTY_CODE;