CREATE SEQUENCE  "D_SEQ_AFFPARTY_TYPE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1061 CACHE 20 NOORDER  NOCYCLE ;

GRANT SELECT ON "D_SEQ_AFFPARTY_TYPE_ID" TO &role_name;

CREATE TABLE D_PI_AFFECTED_PARTY_TYPE
   (AFFECTED_PARTY_TYPE_ID NUMBER NOT NULL, 
    AFFECTED_PARTY_TYPE_CODE VARCHAR2(32),
    AFFECTED_PARTY_TYPE VARCHAR2(240)  
	  ) TABLESPACE &tablespace_name ;

 ALTER TABLE "D_PI_AFFECTED_PARTY_TYPE" ADD CONSTRAINT "DAFFPARTYTYPE_COMB_UK" UNIQUE ("AFFECTED_PARTY_TYPE_CODE") USING INDEX  TABLESPACE &tablespace_name  ENABLE;
 ALTER TABLE "D_PI_AFFECTED_PARTY_TYPE" ADD CONSTRAINT "DAFFPARTYTYPEPK" PRIMARY KEY ("AFFECTED_PARTY_TYPE_ID") USING INDEX TABLESPACE &tablespace_name  ENABLE;
  
GRANT SELECT ON "D_PI_AFFECTED_PARTY_TYPE" TO &role_name;

CREATE OR REPLACE TRIGGER "BIR_AFFECTED_PARTY_TYPE" 
 BEFORE INSERT
 ON d_pi_affected_party_type
 FOR EACH ROW
DECLARE
    v_seq_id     D_PI_AFFECTED_PARTY_TYPE.affected_party_type_id%TYPE;
BEGIN
  IF :NEW.affected_party_type_id IS NULL THEN
    SElECT D_SEQ_AFFPARTY_TYPE_ID.NEXTVAL
    INTO v_seq_id
    FROM dual;

    :NEW.affected_party_type_id       := v_seq_id;
  END IF;
END BIR_AFFECTED_PARTY_TYPE;
/
ALTER TRIGGER "BIR_AFFECTED_PARTY_TYPE" ENABLE;
/

CREATE OR REPLACE VIEW D_PI_AFFECTED_PARTY_TYPE_SV
AS
SELECT affected_party_type_code affected_party_type_cd
       ,affected_party_type
FROM d_pi_affected_party_type;

GRANT SELECT ON "D_PI_AFFECTED_PARTY_TYPE_SV" TO &role_name;
