INSERT INTO D_PI_AFFECTED_PARTY_TYPE (AFFECTED_PARTY_TYPE_ID,AFFECTED_PARTY_TYPE_CODE,AFFECTED_PARTY_TYPE )
SELECT 0
     ,'UD'
    , 'Undefined'  
FROM D_PI_AFFECTED_PARTY_TYPE
WHERE AFFECTED_PARTY_TYPE_CODE = 'UD'
HAVING count(*) = 0;

INSERT INTO D_PI_AFFECTED_PARTY_SUBTYPE (AFFECTED_PARTY_SUBTYPE_ID,AFFECTED_PARTY_SUBTYPE_CODE,AFFECTED_PARTY_SUBTYPE )
SELECT 0
     ,'UD'
    , 'Undefined'  
FROM D_PI_AFFECTED_PARTY_SUBTYPE
WHERE AFFECTED_PARTY_SUBTYPE_CODE = 'UD'
HAVING count(*) = 0;

commit;

INSERT INTO D_PI_INCIDENT_STATUS (INCIDENT_STATUS_ID,INCIDENT_STATUS_CODE,INCIDENT_STATUS )
SELECT 0
     ,'UD'
    , 'Undefined'  
FROM D_PI_INCIDENT_STATUS
WHERE INCIDENT_STATUS_CODE = 'UD'
HAVING count(*) = 0;

INSERT INTO D_PI_INCIDENT_ORIGIN (INCIDENT_ORIGIN_ID,INCIDENT_ORIGIN_CODE,INCIDENT_ORIGIN )
SELECT 0
     ,'UD'
    , 'Undefined'  
FROM D_PI_INCIDENT_ORIGIN
WHERE INCIDENT_ORIGIN_CODE = 'UD'
HAVING count(*) = 0;

commit;