

ALTER TABLE CC_C_UNIT_OF_WORK
ADD ( UNIT_OF_WORK_CATEGORY VARCHAR2(50) );

ALTER TABLE CC_D_UNIT_OF_WORK
ADD ( UNIT_OF_WORK_CATEGORY VARCHAR2(50) );

CREATE OR REPLACE VIEW CC_D_UNIT_OF_WORK_SV  AS
SELECT CC_D_UNIT_OF_WORK.* FROM CC_D_UNIT_OF_WORK ;

INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME) 
	VALUES ('1.5.0','001','001_ALTER_UNIT_OF_WORK_TABLES');

COMMIT;