CREATE TABLE CC_S_TMP_CISCO_CT_SG_INTERVAL 
    ( 
     DATETIME DATE , 
     DBDATETIME DATE , 
     SKILLGROUPSKILLTARGETID NUMBER,
     CALLSANSWERED NUMBER , 
     CALLSHANDLED NUMBER , 
     CALLSOFFERED NUMBER , 
     HANDLETIME NUMBER , 
     TALKTIME NUMBER , 
     HOLDTIME NUMBER ,
     ANSWERWAITTIME NUMBER , 
     ANSINTERVAL1 NUMBER , 
     ANSINTERVAL2 NUMBER , 
     ANSINTERVAL3 NUMBER , 
     ANSINTERVAL4 NUMBER , 
     ANSINTERVAL5 NUMBER , 
     ANSINTERVAL6 NUMBER , 
     ANSINTERVAL7 NUMBER , 
     ANSINTERVAL8 NUMBER , 
     ANSINTERVAL9 NUMBER , 
     ANSINTERVAL10 NUMBER , 
     ABANDINTERVAL1 NUMBER , 
     ABANDINTERVAL2 NUMBER , 
     ABANDINTERVAL3 NUMBER , 
     ABANDINTERVAL4 NUMBER , 
     ABANDINTERVAL5 NUMBER , 
     ABANDINTERVAL6 NUMBER , 
     ABANDINTERVAL7 NUMBER , 
     ABANDINTERVAL8 NUMBER , 
     ABANDINTERVAL9 NUMBER , 
     ABANDINTERVAL10 NUMBER , 
     ROUTERCALLSABANDQ NUMBER,
     ROUTERCALLSABANDTOAGENT NUMBER,
     DELAYAGENTABANDTIME NUMBER,
     DELAYQABANDTIME NUMBER,
     SERVICELEVELCALLSOFFERED NUMBER,
     SERVICELEVELABAND NUMBER , 
     SERVICELEVELCALLSDEQUEUE NUMBER,
     CALLSONHOLD NUMBER ,
     ROUTERQUEUEWAITTIME NUMBER ,
     SHORTCALLS NUMBER ,
     CALLSRONA NUMBER ,     
     CALLSROUTEDNONAGENT NUMBER , 
     ERRORCOUNT NUMBER , 
     AGENTERRORCOUNT NUMBER ,
     INCOMPLETECALLS NUMBER ,
     
     TIMEZONE NUMBER ,
     CALLTYPEID NUMBER , 
     TOTALCALLSABAND NUMBER ,
     ROUTERQUEUECALLTYPELIMIT NUMBER , 
     ROUTERQUEUEGLOBALLIMIT NUMBER , 
     MAXHOLDTIME NUMBER , 
     MAXCALLWAITTIME NUMBER , 
     SERVICELEVELCALLS NUMBER , 
     CALLDELAYABANDTIME NUMBER , 
     MAXCALLSQUEUED NUMBER , 
     REPORTING_INTERVAL NUMBER , 
     VRUSCRIPTEDXFERREDCALLS NUMBER , 
     VRUFORCEDXFERREDCALLS NUMBER , 
     OVERFLOWOUT NUMBER , 
     CTVRUTIME NUMBER , 
     ICRDEFAULTROUTED NUMBER , 
     NETWORKDEFAULTROUTED NUMBER , 
     RETURNBUSY NUMBER , 
     RETURNRELEASE NUMBER , 
     RETURNRING NUMBER 
    ) 
        TABLESPACE MAXDAT_DATA 
        LOGGING 
;

CREATE INDEX TMP_CISCO_CTYPE_INT_SGID_IDX ON CC_S_TMP_CISCO_CT_SG_INTERVAL 
    ( 
     SKILLGROUPSKILLTARGETID ASC 
    ) 
    TABLESPACE MAXDAT_INDX 
    COMPUTE STATISTICS 
;
CREATE INDEX TMP_CISCO_CTSGYPE_INT_DT_IDX ON CC_S_TMP_CISCO_CT_SG_INTERVAL 
    ( 
     DATETIME ASC 
    ) 
    TABLESPACE MAXDAT_INDX 
    COMPUTE STATISTICS 
;