update D_TASK_TYPES set OPERATIONS_GROUP = 'Application Processing', SLA_DAYS = 3, SLA_DAYS_TYPE = 'B', SLA_TARGET_DAYS =  '3', SLA_JEOPARDY_DAYS =  '2', UNIT_OF_WORK =  '' where TASK_TYPE_ID =  50417;
update D_TASK_TYPES set OPERATIONS_GROUP = 'System Administration', SLA_DAYS = 10, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  '10', SLA_JEOPARDY_DAYS =  '8', UNIT_OF_WORK =  '' where TASK_TYPE_ID =  15;
update D_TASK_TYPES set OPERATIONS_GROUP = 'Research', SLA_DAYS = 1, SLA_DAYS_TYPE = 'B', SLA_TARGET_DAYS =  '1', SLA_JEOPARDY_DAYS =  '1', UNIT_OF_WORK =  '' where TASK_TYPE_ID =  3015;
update D_TASK_TYPES set OPERATIONS_GROUP = 'Research', SLA_DAYS = 10, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  '10', SLA_JEOPARDY_DAYS =  '8', UNIT_OF_WORK =  '' where TASK_TYPE_ID =  3040;
commit;
