-- Update D_TASK_TYPES TNERPS-1216
update D_TASK_TYPES set OPERATIONS_GROUP = 'Call Center', SLA_DAYS = 35, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  30, SLA_JEOPARDY_DAYS =  30, UNIT_OF_WORK =  '' where TASK_TYPE_ID =  50417;
update D_TASK_TYPES set OPERATIONS_GROUP = 'Data Entry Unit', SLA_DAYS = 35, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  30, SLA_JEOPARDY_DAYS =  30, UNIT_OF_WORK =  '' where TASK_TYPE_ID =  3007;
update D_TASK_TYPES set OPERATIONS_GROUP = 'Data Entry Unit', SLA_DAYS = 35, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  30, SLA_JEOPARDY_DAYS =  30, UNIT_OF_WORK =  '' where TASK_TYPE_ID =  3011;
update D_TASK_TYPES set OPERATIONS_GROUP = 'Mail Room', SLA_DAYS = 2, SLA_DAYS_TYPE = 'B', SLA_TARGET_DAYS =  2, SLA_JEOPARDY_DAYS =  2, UNIT_OF_WORK =  '' where TASK_TYPE_ID =  3005;
update D_TASK_TYPES set OPERATIONS_GROUP = 'Research', SLA_DAYS = 35, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  30, SLA_JEOPARDY_DAYS =  30, UNIT_OF_WORK =  '' where TASK_TYPE_ID =  110;
update D_TASK_TYPES set OPERATIONS_GROUP = 'Research', SLA_DAYS = 35, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  30, SLA_JEOPARDY_DAYS =  30, UNIT_OF_WORK =  '' where TASK_TYPE_ID =  3003;
update D_TASK_TYPES set OPERATIONS_GROUP = 'Research', SLA_DAYS = 35, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  30, SLA_JEOPARDY_DAYS =  30, UNIT_OF_WORK =  '' where TASK_TYPE_ID =  3009;
update D_TASK_TYPES set OPERATIONS_GROUP = 'Research', SLA_DAYS = 35, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  30, SLA_JEOPARDY_DAYS =  30, UNIT_OF_WORK =  '' where TASK_TYPE_ID =  3015;
update D_TASK_TYPES set OPERATIONS_GROUP = 'Research', SLA_DAYS = 35, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  30, SLA_JEOPARDY_DAYS =  30, UNIT_OF_WORK =  '' where TASK_TYPE_ID =  50390;
update D_TASK_TYPES set OPERATIONS_GROUP = 'Research', SLA_DAYS = 35, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  30, SLA_JEOPARDY_DAYS =  30, UNIT_OF_WORK =  '' where TASK_TYPE_ID in (50437,50438);
update D_TASK_TYPES set OPERATIONS_GROUP = 'State Eligibility', SLA_DAYS = 60, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  60, SLA_JEOPARDY_DAYS =  60, UNIT_OF_WORK =  '' where TASK_TYPE_ID =  3013;
update D_TASK_TYPES set OPERATIONS_GROUP = 'State Eligibility', SLA_DAYS = 35, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  30, SLA_JEOPARDY_DAYS =  30, UNIT_OF_WORK =  '' where TASK_TYPE_ID =  50412;
update D_TASK_TYPES set OPERATIONS_GROUP = 'State Eligibility', SLA_DAYS = 60, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  60, SLA_JEOPARDY_DAYS =  60, UNIT_OF_WORK =  '' where TASK_TYPE_ID =  50413;
update D_TASK_TYPES set OPERATIONS_GROUP = 'State Eligibility', SLA_DAYS = 60, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  60, SLA_JEOPARDY_DAYS =  60, UNIT_OF_WORK =  '' where TASK_TYPE_ID =  50414;
update D_TASK_TYPES set OPERATIONS_GROUP = 'State Eligibility', SLA_DAYS = 60, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  60, SLA_JEOPARDY_DAYS =  60, UNIT_OF_WORK =  '' where TASK_TYPE_ID =  50415;
update D_TASK_TYPES set OPERATIONS_GROUP = 'State Eligibility', SLA_DAYS = 60, SLA_DAYS_TYPE = 'C', SLA_TARGET_DAYS =  60, SLA_JEOPARDY_DAYS =  60, UNIT_OF_WORK =  '' where TASK_TYPE_ID =  50416;
commit;