
UPDATE PP_D_UOW_SOURCE_REF SET SOURCE_REF_VALUE='DPR - SHOP Employer Task'   WHERE source_ref_detail_identifier='TASK ID' AND SOURCE_REF_VALUE='Employee Application';
INSERT INTO PP_D_UOW_SOURCE_REF SELECT 34, 4, 1, 'DPR - SHOP Employee Task', 'TASK ID', TO_DATE('20130701','YYYYMMDD'), TO_DATE('20770707','YYYYMMDD') FROM DUAL;
UPDATE PP_D_UOW_SOURCE_REF SET SOURCE_REF_VALUE='DPR - Account Correction'   WHERE source_ref_detail_identifier='TASK ID' AND SOURCE_REF_VALUE='Account Correction';
UPDATE PP_D_UOW_SOURCE_REF SET SOURCE_REF_VALUE='DPR - Complaint'   WHERE source_ref_detail_identifier='TASK ID' AND SOURCE_REF_VALUE='Complaint';
UPDATE PP_D_UOW_SOURCE_REF SET SOURCE_REF_VALUE='Data Entry Task'   WHERE source_ref_detail_identifier='TASK ID' AND SOURCE_REF_VALUE='Verification Document';
INSERT INTO PP_D_UOW_SOURCE_REF SELECT 35, 8, 1, 'Data Entry-Verification Document Task', 'TASK ID', TO_DATE('20130701','YYYYMMDD'), TO_DATE('20770707','YYYYMMDD') FROM DUAL;
INSERT INTO PP_D_UOW_SOURCE_REF SELECT 36, 8, 1, 'Data Entry-SHOP Employer Task', 'TASK ID', TO_DATE('20130701','YYYYMMDD'), TO_DATE('20770707','YYYYMMDD') FROM DUAL;
INSERT INTO PP_D_UOW_SOURCE_REF SELECT 37, 8, 1, 'Data Entry-SHOP Employee Task', 'TASK ID', TO_DATE('20130701','YYYYMMDD'), TO_DATE('20770707','YYYYMMDD') FROM DUAL;
UPDATE PP_D_UOW_SOURCE_REF SET SOURCE_REF_VALUE='HSDE-QC VHT'   WHERE source_ref_detail_identifier='TASK ID' AND SOURCE_REF_VALUE='HSDE-QC';
UPDATE PP_D_UOW_SOURCE_REF SET SOURCE_REF_VALUE='DPR - Free Form Follow-Up'   WHERE source_ref_detail_identifier='TASK ID' AND SOURCE_REF_VALUE='Free Form Text';
UPDATE PP_D_UOW_SOURCE_REF SET SOURCE_REF_VALUE='Returned Mail Data Entry Task'   WHERE source_ref_detail_identifier='TASK ID' AND SOURCE_REF_VALUE='Returned Mail';
UPDATE PP_D_UOW_SOURCE_REF SET SOURCE_REF_VALUE='DPR - Orphan Document'   WHERE source_ref_detail_identifier='TASK ID' AND SOURCE_REF_VALUE='Orphan Document';
UPDATE PP_D_UOW_SOURCE_REF SET SOURCE_REF_VALUE='DPR - Wrong Program'   WHERE source_ref_detail_identifier='TASK ID' AND SOURCE_REF_VALUE='Wrong Program';
UPDATE PP_D_UOW_SOURCE_REF SET SOURCE_REF_VALUE='NYHBE MAXIMUS QC Task'   WHERE source_ref_detail_identifier='TASK ID' AND SOURCE_REF_VALUE='Quality Control';
INSERT INTO PP_D_UOW_SOURCE_REF SELECT 38, 14, 1, 'Link Doc Set QC Task', 'TASK ID', TO_DATE('20130701','YYYYMMDD'), TO_DATE('20770707','YYYYMMDD') FROM DUAL;

delete from PP_D_ACTUAL_DETAILS;
delete from pp_f_actuals;

commit;

/
