/*
Created on 12/17/2014 for NYHIX-12475 by Raj A.
*/
insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1006, 0, 4, 'Hot Docs UPK', 'PIPKINS EVENTS', to_date('12/01/2014', 'mm/dd/yyyy'), to_date('7/7/2077', 'mm/dd/yyyy'), 1281);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1007, 19, 4, 'ID Proof - Task', 'PIPKINS EVENTS', to_date('12/01/2014', 'mm/dd/yyyy'), to_date('7/7/2077', 'mm/dd/yyyy'), 1282);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1008, 19, 4, 'ID Proof - Calls', 'PIPKINS EVENTS', to_date('12/01/2014', 'mm/dd/yyyy'), to_date('7/7/2077', 'mm/dd/yyyy'), 1283);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1009, 14, 4, 'Manual Notice QC', 'PIPKINS EVENTS', to_date('12/01/2014', 'mm/dd/yyyy'), to_date('7/7/2077', 'mm/dd/yyyy'), 1284);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1010, 14, 4, 'Evidence Packet QC', 'PIPKINS EVENTS', to_date('12/01/2014', 'mm/dd/yyyy'), to_date('7/7/2077', 'mm/dd/yyyy'), 1285);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1011, 9, 4, 'HSDE QC - App', 'PIPKINS EVENTS', to_date('12/01/2014', 'mm/dd/yyyy'), to_date('7/7/2077', 'mm/dd/yyyy'), 1286);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1012, 9, 4, 'HSDE QC - V Doc w/Engage', 'PIPKINS EVENTS', to_date('12/01/2014', 'mm/dd/yyyy'), to_date('7/7/2077', 'mm/dd/yyyy'), 1287);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1013, 19, 4, 'Data Entry Research - Other ', 'PIPKINS EVENTS', to_date('12/01/2014', 'mm/dd/yyyy'), to_date('7/7/2077', 'mm/dd/yyyy'), 1289);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1014, 19, 4, 'Application - Missing Data', 'PIPKINS EVENTS', to_date('12/01/2014', 'mm/dd/yyyy'), to_date('7/7/2077', 'mm/dd/yyyy'), 1290);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1015, 19, 4, 'Queue Empty ', 'PIPKINS EVENTS', to_date('12/01/2014', 'mm/dd/yyyy'), to_date('7/7/2077', 'mm/dd/yyyy'), 1291);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1016, 21, 1, 'Decision Overturned', 'TASK ID', sysdate, to_date('7/7/2077', 'mm/dd/yyyy'), 2015020);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1017, 21, 1, 'Dismissal - Failed to Attend Hearing', 'TASK ID', sysdate, to_date('7/7/2077', 'mm/dd/yyyy'), 2015015);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1018, 21, 1, 'Document-Account Review', 'TASK ID', sysdate, to_date('7/7/2077', 'mm/dd/yyyy'), 2016255);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1019, 21, 1, 'Evidence Packet Correction Task', 'TASK ID', sysdate, to_date('7/7/2077', 'mm/dd/yyyy'), 2016234);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1020, 21, 1, 'Hearing Set - Disposition Review Needed', 'TASK ID', sysdate, to_date('7/7/2077', 'mm/dd/yyyy'), 2015008);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1021, 21, 1, 'Refer to NY Appeals', 'TASK ID', sysdate, to_date('7/7/2077', 'mm/dd/yyyy'), 2015026);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1022, 21, 1, 'Request to Vacate Dismissal', 'TASK ID', sysdate, to_date('7/7/2077', 'mm/dd/yyyy'), 2015018);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1023, 21, 1, 'SHOP Desk Review', 'TASK ID', sysdate, to_date('7/7/2077', 'mm/dd/yyyy'), 2015023);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1024, 21, 1, 'DERT-Existing Appeal', 'TASK ID', sysdate, to_date('7/7/2077', 'mm/dd/yyyy'), 2013051);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1025, 29, 1, 'DERT-Authorized Representative', 'TASK ID', sysdate, to_date('7/7/2077', 'mm/dd/yyyy'), 2013054);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1026, 29, 1, 'DERT-Other', 'TASK ID', sysdate, to_date('7/7/2077', 'mm/dd/yyyy'), 2013052);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1027, 29, 1, 'DPR - Application-Missing Data', 'TASK ID', sysdate, to_date('7/7/2077', 'mm/dd/yyyy'), 2013058);

commit;