insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1029, 20, 4, 'Bonus Plan UPK', 'PIPKINS EVENTS', sysdate, to_date('7/7/2077', 'mm/dd/yyyy'), 1280);

insert into PP_D_UOW_SOURCE_REF (USR_ID, UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, SOURCE_REF_DETAIL_IDENTIFIER, EFFECTIVE_DATE, END_DATE, SOURCE_REF_ID)
values (1030, 30, 4, 'Bucket Cases', 'PIPKINS EVENTS', sysdate, to_date('7/7/2077', 'mm/dd/yyyy'), 1246);

commit;