/*
Created on 12/19/2014 by Raj A.
Description:  This script maps the events to the correct UOW.
*/
set define off;
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Flex Time' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'IDR incident' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Beginning of Attendance' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'End of Attendance' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Slack Time' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Break' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Lunch' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Vacation' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Sick' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Holiday' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Off' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = '(  )' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Unknown' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Clock In' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Clock Out' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Personal Day' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Late Start' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Invalid Agent State' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Unknown Work' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = '(none)' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Split Time' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = '(no actuals)' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = '(no schedule)' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Split Work Event' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Staff Meeting' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Training' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Outbound Calls' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'One-on-One' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'E-Chat' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Time Off' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'NY HBE Pilot - Individual' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'NY HBE Pilot - SHOP' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Non Existing Test group' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'SWCC-CSR' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Eligibility and Enrollment' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Mailroom' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Financial Management' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x 91011-Other' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x 5678-Orphan Document' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x 11223-Returned Mail - Application' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Mail Room Specialist' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x 1234-New Appeal' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x E&E Mailroom Team Lead' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Opening' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Prepping' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Sorting' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Scanning' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x HSDE' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x SHOP Appication Data Entry' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Eligibility Specialist A' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'HSDE' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Eligibility Specialist B' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'FM Specialists' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Proximal Search & Linking' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Eligibility' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x 22322-Verification Document' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Complaints' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Eligibility Specialist C' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Orphan' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x 100113-Wrong Program' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Returned Mail' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Quality Control' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Appeals' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x ORIGINAL Mail Room' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x ORIGINAL HSDE' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x ORIGINAL SHOP Application Data Entry' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x ORIGINAL HSDE QC' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x ORIGINAL Link Document Set' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x ORIGINAL Eligibility' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x ORIGINAL Quality Control' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'SWCC-CSR Bilingual' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'SWCC-CSR II' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'SWCC-CSR II Bilingual' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Consumer Services Specialist II - SHOP Bilingual' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Consumer Services Specialist I - SHOP Bilingual' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'CSS IV' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'CSS III Bilingual' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'CSS IV Bilingual' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Team Lead (SHOP)' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Team Lead (SHOP) - Bilingual' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Team Lead (Individual)' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Team Lead (Individual) - Bilingual' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x CSRI- Specialized' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x E&E Appeals' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'CSS I - SHOP' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x E&E Fin Main' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x CSR-II' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'CSS II - SHOP' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'CSS III' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Idle Time' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Inbound/Outbound Call' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Wrap Up' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Inbound Calls' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Complaints/NYSOH Support - Outbound Calls' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'ES C - Gen Info' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Awaiting Validity Check' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Evidence Packet Correction - Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Un-Scheduled Break' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'Appeal - Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'UPK Training' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Processing' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'WFM Chat' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Supervisor Help' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'System Problems' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Phone Problems' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x 233 KOFAX Imaging and QC' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Employer Application' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Employee Application' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x DPR - Account Correction' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Existing Appeal' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'Complaint' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Appeal deleted' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Incident Open' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Refer to ES-C' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Schedule Hearing' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 30 where 1=1 and Z.SOURCE_REF_VALUE = 'Verification Document' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 25 where 1=1 and Z.SOURCE_REF_VALUE = 'Free Form Text' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'Returned Mail Application' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Existing Appeal' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Complaint' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 25 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Other' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Document Problem Resolution' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'APPEAL' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Cancel Hearing' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Appeals' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Incident Open' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Refer to ES-C Supervisor' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Reschedule Hearing - Appellant Request' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Reschedule Hearing - DOH Request' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'NYHBE Complaints' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Nyhbe Incident VHT' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Supervisor Complaint Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Data Entry-SHOP Employee Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 30 where 1=1 and Z.SOURCE_REF_VALUE = 'Data Entry-Verification Document Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'NYHBE Verification Doc Research Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 22 where 1=1 and Z.SOURCE_REF_VALUE = 'HSDE-QC' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 25 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Account Correction' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 29 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Application in Process' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 29 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Multiple Applications' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 25 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Wrong Program' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 26 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Financial Management' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'Document Problem Resolution' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 25 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Doc/Form Type Mismatch Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 25 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Other' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 25 where 1=1 and Z.SOURCE_REF_VALUE = 'Other' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'BATCH TYPE';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Remand' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 10 where 1=1 and Z.SOURCE_REF_VALUE = 'Returned Mail Data Entry Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Manual Human Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Manual Task - General' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'MyManualTask' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'TPHI Manual Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 26 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Financial Management' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 10 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - FM Returned Mail' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Returned Mail Application' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Appeal Validity Check' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Awaiting Documentation' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Awaiting Validity Amendment' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Awaiting Validity Amendment - Individual' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Awaiting Validity Amendment - SHOP' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Awaiting Written Withdrawal' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - SHOP Employer Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 25 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Account Correction' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Appeal' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'IDR Incident Open' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Appeal Incident Open' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Refer to ES-C' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Schedule Hearing' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 29 where 1=1 and Z.SOURCE_REF_VALUE = 'Application In Process' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 22 where 1=1 and Z.SOURCE_REF_VALUE = 'HSDE-QC VHT' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 25 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Free Form Follow-Up' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'Returned Mail - Application' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 27 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Orphan Document' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 25 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Wrong Program' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 23 where 1=1 and Z.SOURCE_REF_VALUE = 'Link Document Set' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 26 where 1=1 and Z.SOURCE_REF_VALUE = 'Financial Management' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 10 where 1=1 and Z.SOURCE_REF_VALUE = 'FM Returned Mail' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - SHOP Employee Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 30 where 1=1 and Z.SOURCE_REF_VALUE = 'Data Entry-Verification Document Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 14 where 1=1 and Z.SOURCE_REF_VALUE = 'Link Doc Set QC Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x 222 Orphan Document' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 25 where 1=1 and Z.SOURCE_REF_VALUE = 'Wrong Program' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 10 where 1=1 and Z.SOURCE_REF_VALUE = 'FM Returned Mail' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'IDR Incident Open' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Team Meeting' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'TESTING' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'NYEC - Renewal Processing' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Problem Case' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'NYEC - Renewals' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'NYEC - Renewals Bilingual' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'NYEC - PAP' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'NYEC - FPBP' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'NYEC - Agency Conference' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Doctor Appointment' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Early Departure' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Weather Related Late Arrival' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'CSS III Spec Lang' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Unplanned Team Meeting' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Special Floor Meeting' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Unplanned Absence' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'CSS I - SHOP Bilingual' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'CSS II - SHOP Bilingual' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Missing Data' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'NYEC Renewal Processing' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Refresher Training' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Quality Training' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'CC Supervisor' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x TEST' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Research Specialist' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 29 where 1=1 and Z.SOURCE_REF_VALUE = 'Application Missing Information' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Identity Proofing' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 29 where 1=1 and Z.SOURCE_REF_VALUE = 'Incomplete Fax' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 26 where 1=1 and Z.SOURCE_REF_VALUE = 'Returned Mail' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'Appeals' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Seibel Updates Training' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Navigator' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Fire Drill/ Evacuation' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Complaint Training' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Data Entry - SHOP Employer' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Reschedule Hearing' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'VLP' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'TPHI' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Safety Training' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Cobrowse Training' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Eligibility Specialist C - Appeals' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Financial Management Specialist' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Eligibility Specialist A.' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Eligibility Specialist B.' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Eligibility Specialist C.' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Mailroom' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'Document Problem Resolution' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 25 where 1=1 and Z.SOURCE_REF_VALUE = 'Doc/Form Type Mismatch Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 26 where 1=1 and Z.SOURCE_REF_VALUE = 'Financial Management' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 25 where 1=1 and Z.SOURCE_REF_VALUE = 'Free Form Follow-Up' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'NYEC - Renewals Processing' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 22 where 1=1 and Z.SOURCE_REF_VALUE = 'HSDE-QC VHT' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 23 where 1=1 and Z.SOURCE_REF_VALUE = 'Link Document Set' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 30 where 1=1 and Z.SOURCE_REF_VALUE = 'Data Entry - Verification Document' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'NYHBE Verification Doc Research' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Data Entry-SHOP Employee Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 29 where 1=1 and Z.SOURCE_REF_VALUE = 'Data Entry Research Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Awaiting Documentation' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Awaiting Written Withdrawal' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'Appeals TBD' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 22 where 1=1 and Z.SOURCE_REF_VALUE = 'HSDE QC' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x DPR - Multiple Applications' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x DPR - Other' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'NYHBE Complaints' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'NYHBE Verification Doc Research Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Refer to ES-C Supervisor' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Supervisor Complaint Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Supervisor Referral Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Emergency Personal Call' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 29 where 1=1 and Z.SOURCE_REF_VALUE = 'Multiple Applications' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 27 where 1=1 and Z.SOURCE_REF_VALUE = 'Orphan Document' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Irate Client' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 25 where 1=1 and Z.SOURCE_REF_VALUE = 'Account Correction' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Orientation' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Agent Self Study Online' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Agent Classroom' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Compliance' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - SHOP Employee Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 29 where 1=1 and Z.SOURCE_REF_VALUE = 'Application In Process' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Document Problem Resolution' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 26 where 1=1 and Z.SOURCE_REF_VALUE = 'Financial Management' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 10 where 1=1 and Z.SOURCE_REF_VALUE = 'FM Returned Mail' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 28 where 1=1 and Z.SOURCE_REF_VALUE = 'Returned Mail - Application' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 29 where 1=1 and Z.SOURCE_REF_VALUE = 'Application in Process' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 29 where 1=1 and Z.SOURCE_REF_VALUE = 'Incarceration Proof' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Refer to ES-C' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Incident Open' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 21 where 1=1 and Z.SOURCE_REF_VALUE = 'Refer to ES-C Supervisor' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 26 where 1=1 and Z.SOURCE_REF_VALUE = 'DPR - Financial Management' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 24 where 1=1 and Z.SOURCE_REF_VALUE = 'Awaiting Documentation' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'TASK ID';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'x Storage' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
update pp_d_uow_source_ref Z set uow_id = 20 where 1=1 and Z.SOURCE_REF_VALUE = 'Account Review Unit / Non-Task' and Z.SOURCE_REF_DETAIL_IDENTIFIER = 'PIPKINS EVENTS';
commit;