Insert into PP_BO_EVENT_TARGET_LKUP (EVENT_ID, NAME, TARGET, SCORECARD_FLAG, START_DATE, END_DATE, CREATE_BY, CREATE_DATETIME, SCORECARD_GROUP, EE_ADHERENCE) values (1490,'QC - SWCC',8,'Y', to_date('14-Sep-16 00:00:00','dd-Mon-yy hh24:mi:ss'), null, 'script', to_date('9/15/2016  08:40:00','mm/dd/yyyy hh24:mi:ss'), 'CALL - SWCC', 'Y');
Insert into PP_BO_EVENT_TARGET_LKUP (EVENT_ID, NAME, TARGET, SCORECARD_FLAG, START_DATE, END_DATE, CREATE_BY, CREATE_DATETIME, SCORECARD_GROUP, EE_ADHERENCE) values (1491,'QC - SBM',8,'Y', to_date('15-Sep-16 00:00:00','dd-Mon-yy hh24:mi:ss'), null, 'script', to_date('9/15/2016  08:40:00','mm/dd/yyyy hh24:mi:ss'), 'CALL - SBM', 'Y');
Insert into PP_BO_EVENT_TARGET_LKUP (EVENT_ID, NAME, TARGET, SCORECARD_FLAG, START_DATE, END_DATE, CREATE_BY, CREATE_DATETIME, SCORECARD_GROUP, EE_ADHERENCE) values (1492,'QC - Individual Marketplace',3,'Y', to_date('16-Sep-16 00:00:00','dd-Mon-yy hh24:mi:ss'), null, 'script', to_date('9/15/2016  08:40:00','mm/dd/yyyy hh24:mi:ss'), 'CALL - Individual', 'Y');
Insert into PP_BO_EVENT_TARGET_LKUP (EVENT_ID, NAME, TARGET, SCORECARD_FLAG, START_DATE, END_DATE, CREATE_BY, CREATE_DATETIME, SCORECARD_GROUP, EE_ADHERENCE) values (1493,'QC - ARU Call',3,'Y', to_date('17-Sep-16 00:00:00','dd-Mon-yy hh24:mi:ss'), null, 'script', to_date('9/15/2016  08:40:00','mm/dd/yyyy hh24:mi:ss'), 'CALL - ARU', 'Y');
Insert into PP_BO_EVENT_TARGET_LKUP (EVENT_ID, NAME, TARGET, SCORECARD_FLAG, START_DATE, END_DATE, CREATE_BY, CREATE_DATETIME, SCORECARD_GROUP, EE_ADHERENCE) values (1494,'QC - ARU Backdating Call',2,'Y', to_date('18-Sep-16 00:00:00','dd-Mon-yy hh24:mi:ss'), null, 'script', to_date('9/15/2016  08:40:00','mm/dd/yyyy hh24:mi:ss'), 'CALL - ARU Backdating', 'Y');
Insert into PP_BO_EVENT_TARGET_LKUP (EVENT_ID, NAME, TARGET, SCORECARD_FLAG, START_DATE, END_DATE, CREATE_BY, CREATE_DATETIME, SCORECARD_GROUP, EE_ADHERENCE) values (1495,'QC - Research',5,'Y', to_date('19-Sep-16 00:00:00','dd-Mon-yy hh24:mi:ss'), null, 'script', to_date('9/15/2016  08:40:00','mm/dd/yyyy hh24:mi:ss'), 'TASK - Research', 'Y');
Insert into PP_BO_EVENT_TARGET_LKUP (EVENT_ID, NAME, TARGET, SCORECARD_FLAG, START_DATE, END_DATE, CREATE_BY, CREATE_DATETIME, SCORECARD_GROUP, EE_ADHERENCE) values (1496,'QC - VDoc',5,'Y', to_date('20-Sep-16 00:00:00','dd-Mon-yy hh24:mi:ss'), null, 'script', to_date('9/15/2016  08:40:00','mm/dd/yyyy hh24:mi:ss'), 'TASK - VDoc', 'Y');
Insert into PP_BO_EVENT_TARGET_LKUP (EVENT_ID, NAME, TARGET, SCORECARD_FLAG, START_DATE, END_DATE, CREATE_BY, CREATE_DATETIME, SCORECARD_GROUP, EE_ADHERENCE) values (1497,'QC - Mailroom',14,'Y', to_date('21-Sep-16 00:00:00','dd-Mon-yy hh24:mi:ss'), null, 'script', to_date('9/15/2016  08:40:00','mm/dd/yyyy hh24:mi:ss'), 'TASK - Mailroom', 'Y');
Insert into PP_BO_EVENT_TARGET_LKUP (EVENT_ID, NAME, TARGET, SCORECARD_FLAG, START_DATE, END_DATE, CREATE_BY, CREATE_DATETIME, SCORECARD_GROUP, EE_ADHERENCE) values (1498,'QC - Link Doc Set',5,'Y', to_date('22-Sep-16 00:00:00','dd-Mon-yy hh24:mi:ss'), null, 'script', to_date('9/15/2016  08:40:00','mm/dd/yyyy hh24:mi:ss'), 'TASK - Link Doc Set', 'Y');
Insert into PP_BO_EVENT_TARGET_LKUP (EVENT_ID, NAME, TARGET, SCORECARD_FLAG, START_DATE, END_DATE, CREATE_BY, CREATE_DATETIME, SCORECARD_GROUP, EE_ADHERENCE) values (1499,'QC - Link Doc Set QC',5,'Y', to_date('23-Sep-16 00:00:00','dd-Mon-yy hh24:mi:ss'), null, 'script', to_date('9/15/2016  08:40:00','mm/dd/yyyy hh24:mi:ss'), 'TASK - Link Doc Set QC', 'Y');
Insert into PP_BO_EVENT_TARGET_LKUP (EVENT_ID, NAME, TARGET, SCORECARD_FLAG, START_DATE, END_DATE, CREATE_BY, CREATE_DATETIME, SCORECARD_GROUP, EE_ADHERENCE) values (1500,'QC - HSDE',5,'Y', to_date('24-Sep-16 00:00:00','dd-Mon-yy hh24:mi:ss'), null, 'script', to_date('9/15/2016  08:40:00','mm/dd/yyyy hh24:mi:ss'), 'TASK - HSDE', 'Y');
Insert into PP_BO_EVENT_TARGET_LKUP (EVENT_ID, NAME, TARGET, SCORECARD_FLAG, START_DATE, END_DATE, CREATE_BY, CREATE_DATETIME, SCORECARD_GROUP, EE_ADHERENCE) values (1501,'QC - HSDE QC',5,'Y', to_date('25-Sep-16 00:00:00','dd-Mon-yy hh24:mi:ss'), null, 'script', to_date('9/15/2016  08:40:00','mm/dd/yyyy hh24:mi:ss'), 'TASK - HSDE QC', 'Y');
Insert into PP_BO_EVENT_TARGET_LKUP (EVENT_ID, NAME, TARGET, SCORECARD_FLAG, START_DATE, END_DATE, CREATE_BY, CREATE_DATETIME, SCORECARD_GROUP, EE_ADHERENCE) values (1502,'QC - ARU Task',5,'Y', to_date('26-Sep-16 00:00:00','dd-Mon-yy hh24:mi:ss'), null, 'script', to_date('9/15/2016  08:40:00','mm/dd/yyyy hh24:mi:ss'), 'TASK - ARU', 'Y');
Insert into PP_BO_EVENT_TARGET_LKUP (EVENT_ID, NAME, TARGET, SCORECARD_FLAG, START_DATE, END_DATE, CREATE_BY, CREATE_DATETIME, SCORECARD_GROUP, EE_ADHERENCE) values (1503,'QC - Tasks (Incidents, Defects, Activities)',5,'Y', to_date('27-Sep-16 00:00:00','dd-Mon-yy hh24:mi:ss'), null, 'script', to_date('9/15/2016  08:40:00','mm/dd/yyyy hh24:mi:ss'), 'TASK - Task Team', 'Y');

commit;
