/*
Created on 03/28/2017 by Raj A.
Description: NYHIX-26477
Adding BIU trigger after table rebuild.
*/
CREATE OR REPLACE TRIGGER BIU_PP_BO_TASK
    BEFORE INSERT OR UPDATE ON PP_BO_TASK
    FOR EACH ROW 
    ENABLE 
BEGIN
IF INSERTING THEN 
          :NEW.EXTRACT_DT := SYSDATE;
END IF;
:NEW.LAST_UPDATE_DT := SYSDATE;
:NEW.LAST_UPDATED_BY := USER;
END; 
/