CREATE OR REPLACE VIEW CC_S_AGENT_SV AS
SELECT CC_S_AGENT.* FROM CC_S_AGENT ;

GRANT SELECT ON CC_S_AGENT_SV TO MAXDAT_READ_ONLY;

INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME)
VALUES ('0.1.2','014','001_CREATE_CC_S_AGENT_SV');

COMMIT;

