update cc_d_activity_type
set IS_READY_FLAG=1
where ACTIVITY_TYPE_NAME='ES CHIP Outbound';

INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME) 
VALUES ('0.2.1','105','105_FIX_UPDATE_CC_C_CC_D_ACTIVITY_TYPE');

commit;