


INSERT INTO CC_D_INTERVAL (
  INTERVAL_START_DATE
  , INTERVAL_END_DATE
  , AM_PM
  , INTERVAL_START_HOUR
  , INTERVAL_START_MINUTE
  , INTERVAL_END_HOUR
  , INTERVAL_END_MINUTE
  , INTERVAL_SECONDS
  , INTERVAL_START_TIME_OF_DAY12
  , INTERVAL_START_TIME_OF_DAY24
  , INTERVAL_END_TIME_OF_DAY12
  , INTERVAL_END_TIME_OF_DAY24
  , RECORD_EFF_DT
  , RECORD_END_DT
  , VERSION
)
SELECT 
  INTERVAL_START_DATE
  , INTERVAL_END_DATE
  , CASE WHEN TO_NUMBER(TO_CHAR(INTERVAL_START_DATE, 'HH24')) < 12 THEN 'AM' ELSE 'PM' END AS "AM_PM"
  , TO_NUMBER(TO_CHAR(INTERVAL_START_DATE, 'HH24')) AS "INTERVAL_START_HOUR"
  , TO_NUMBER(TO_CHAR(INTERVAL_START_DATE, 'MI')) AS "INTERVAL_START_MINUTE"
  , TO_NUMBER(TO_CHAR(INTERVAL_END_DATE, 'HH24')) AS "INTERVAL_END_HOUR"
  , TO_NUMBER(TO_CHAR(INTERVAL_END_DATE, 'MI')) AS "INTERVAL_END_MINUTE"
  , INTERVAL_SECONDS
  , TO_CHAR(INTERVAL_START_DATE, 'HH:MI') AS "INTERVAL_START_TIME_OF_DAY12"
  , TO_CHAR(INTERVAL_START_DATE, 'HH24:MI') AS "INTERVAL_START_TIME_OF_DAY24"
  , TO_CHAR(INTERVAL_END_DATE, 'HH:MI') AS "INTERVAL_END_TIME_OF_DAY12"
  , TO_CHAR(INTERVAL_END_DATE, 'HH24:MI') AS "INTERVAL_END_TIME_OF_DAY24"
  , to_date('01-JAN-1900','DD-MON-YYYY') AS "RECORD_EFF_DT"
  , to_date('12-DEC-2999','DD-MON-YYYY') AS "RECORD_END_DT"
  , 1 AS "VERSION"
FROM CC_S_INTERVAL
WHERE INTERVAL_START_DATE NOT IN (
  SELECT INTERVAL_START_DATE FROM CC_D_INTERVAL
);



INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME) 
VALUES ('0.3.1','100','100_INSERT_CC_D_INTERVAL');


COMMIT;