REM INSERTING into CC_D_STATE
SET DEFINE OFF;
Insert into CC_D_STATE (STATE_NAME) values ('Kansas');
Insert into CC_D_STATE (STATE_NAME) values ('Maryland');
Insert into CC_D_STATE (STATE_NAME) values ('Michigan');
Insert into CC_D_STATE (STATE_NAME) values ('West Virginia');
Insert into CC_D_STATE (STATE_NAME) values ('Minnesota');
Insert into CC_D_STATE (STATE_NAME) values ('Nebraska');
Insert into CC_D_STATE (STATE_NAME) values ('Tennessee');
Insert into CC_D_STATE (STATE_NAME) values ('Virginia');
Insert into CC_D_STATE (STATE_NAME) values ('Missouri');
Insert into CC_D_STATE (STATE_NAME) values ('Georgia');
Insert into CC_D_STATE (STATE_NAME) values ('DC');
Insert into CC_D_STATE (STATE_NAME) values ('Idaho');
Insert into CC_D_STATE (STATE_NAME) values ('California');
Insert into CC_D_STATE (STATE_NAME) values ('Colorado');
Insert into CC_D_STATE (STATE_NAME) values ('Texas');
Insert into CC_D_STATE (STATE_NAME) values ('Wyoming');
Insert into CC_D_STATE (STATE_NAME) values ('District of Columbia');
Insert into CC_D_STATE (STATE_NAME) values ('Massachusetts');
Insert into CC_D_STATE (STATE_NAME) values ('South Carolina');
