alter session set plsql_code_type = native;

create or replace trigger TRG_BIU_CORP_ETL_APPEAL
before insert or update on CORP_ETL_APPEAL_WIP
for each row
declare
  v_instance_start_date date := null;
  v_instance_end_date date := null;
begin
  if inserting then
    if
	  :new.CEAP_ID is null then  :new.CEAP_ID := SEQ_CEAP_ID.nextval;
    end if;
    if
	   :new.STG_EXTRACT_DATE is null then :new.STG_EXTRACT_DATE  := sysdate;
    end if;
  end if;
  :new.STG_LAST_UPDATE_DATE := sysdate;
end;
/

create or replace trigger TRG_AI_CORP_ETL_APPEAL_Q
after insert on CORP_ETL_APPEAL
for each row
declare
  v_bsl_id number := 2004; -- 'FEDQIC_ETL'
  v_bil_id number := 3; -- 'Task ID'
  v_data_version number := 3; -- CDATA for varchar2 only and added STG_LAST_UPDATE_DATE
  v_identifier varchar2(100) := null;
  v_xml_string_new clob := null;
  v_sql_code number := null;
  v_log_message clob := null;
  v_event_date date := null;
begin
  v_event_date := :new.STG_LAST_UPDATE_DATE;
  v_identifier := :new.APPEAL_ID;
  v_xml_string_new :=
    '<?xml version="1.0"?>
    <ROWSET>
      <ROW>
        <CEAP_ID>' || :new.CEAP_ID || '</CEAP_ID>
         <APPEAL_ID><![CDATA[' || :new.APPEAL_ID || ']]></APPEAL_ID>
<CREATE_DATE>' || to_char(:new.CREATE_DATE,BPM_COMMON.GET_DATE_FMT) || '</CREATE_DATE>
<COMPLETE_DATE>' || to_char(:new.COMPLETE_DATE,BPM_COMMON.GET_DATE_FMT) || '</COMPLETE_DATE>
<CANCELLED_DATE>' || to_char(:new.CANCELLED_DATE,BPM_COMMON.GET_DATE_FMT) || '</CANCELLED_DATE>
<ADJUDICATOR><![CDATA[' || :new.ADJUDICATOR || ']]></ADJUDICATOR> 
<DEADLINE_DATE>' || to_char(:new.DEADLINE_DATE,BPM_COMMON.GET_DATE_FMT) || '</DEADLINE_DATE> 
<APPEAL_ISSUE><![CDATA[' || :new.APPEAL_ISSUE || ']]></APPEAL_ISSUE>
<APPEAL_ITEM><![CDATA[' || :new.APPEAL_ITEM || ']]></APPEAL_ITEM>  
<APPEAL_NUMBER><![CDATA[' || :new.APPEAL_NUMBER || ']]></APPEAL_NUMBER> 
<APPEAL_PRIORITY_ID><![CDATA[' || :new.APPEAL_PRIORITY_ID || ']]></APPEAL_PRIORITY_ID>
<REQUEST_RECEIVED>' || to_char(:new.REQUEST_RECEIVED,BPM_COMMON.GET_DATE_FMT) || '</REQUEST_RECEIVED> 
<APPEAL_STAGE><![CDATA[' || :new.APPEAL_STAGE || ']]></APPEAL_STAGE>  
<APPEAL_STATUS><![CDATA[' || :new.APPEAL_STATUS || ']]></APPEAL_STATUS> 
<APPEAL_TYPE><![CDATA[' || :new.APPEAL_TYPE || ']]></APPEAL_TYPE>
<APPEAL_DISMISSAL><![CDATA[' || :new.APPEAL_DISMISSAL || ']]></APPEAL_DISMISSAL>
<APPEAL_DISMISSAL_REASON><![CDATA[' || :new.APPEAL_DISMISSAL_REASON || ']]></APPEAL_DISMISSAL_REASON>
<AUTO_FORWARD><![CDATA[' || :new.AUTO_FORWARD || ']]></AUTO_FORWARD>
<CASE_FILE_REQUEST_DATE>' || to_char(:new.CASE_FILE_REQUEST_DATE,BPM_COMMON.GET_DATE_FMT) || '</CASE_FILE_REQUEST_DATE> 
<ACKNOWLEDGEMENT_LETTER_DATE>' || to_char(:new.ACKNOWLEDGEMENT_LETTER_DATE,BPM_COMMON.GET_DATE_FMT) || '</ACKNOWLEDGEMENT_LETTER_DATE>
<DECISION_MAILED_DATE>' || to_char(:new.DECISION_MAILED_DATE,BPM_COMMON.GET_DATE_FMT) || '</DECISION_MAILED_DATE>
<DECISION_SENT_PLAN_DATE>' || to_char(:new.DECISION_SENT_PLAN_DATE,BPM_COMMON.GET_DATE_FMT) || '</DECISION_SENT_PLAN_DATE>
<MEDICAL_REVIEW_CHECK><![CDATA[' || :new.MEDICAL_REVIEW_CHECK || ']]></MEDICAL_REVIEW_CHECK>
<APPEAL_PART_ID><![CDATA[' || :new.APPEAL_PART_ID || ']]></APPEAL_PART_ID>
<APPEAL_REASON><![CDATA[' || :new.APPEAL_REASON || ']]></APPEAL_REASON> 
<APPEAL_TOLLING_DATE>' || to_char(:new.APPEAL_TOLLING_DATE,BPM_COMMON.GET_DATE_FMT) || '</APPEAL_TOLLING_DATE>
<APPEAL_NOTICE_DATE>' || to_char(:new.APPEAL_NOTICE_DATE,BPM_COMMON.GET_DATE_FMT) || '</APPEAL_NOTICE_DATE>
<CASE_FILE_RECEIVED_DATE>' || to_char(:new.CASE_FILE_RECEIVED_DATE,BPM_COMMON.GET_DATE_FMT) || '</CASE_FILE_RECEIVED_DATE>  
<CLAIMED_DATE>' || to_char(:new.CLAIMED_DATE,BPM_COMMON.GET_DATE_FMT) || '</CLAIMED_DATE>
<DECISION><![CDATA[' || :new.DECISION || ']]></DECISION>
<DECISION_NOTIFICATION_METHOD><![CDATA[' || :new.DECISION_NOTIFICATION_METHOD || ']]></DECISION_NOTIFICATION_METHOD>
<HPMS><![CDATA[' || :new.HPMS || ']]></HPMS>
<HPMS_REQUESTED_DATE>' || to_char(:new.HPMS_REQUESTED_DATE,BPM_COMMON.GET_DATE_FMT) || '</HPMS_REQUESTED_DATE>
<IS_REQUEST_FOR_INFORMATION_P><![CDATA[' || :new.IS_REQUEST_FOR_INFORMATION_P || ']]></IS_REQUEST_FOR_INFORMATION_P>
<MAC><![CDATA[' || :new.MAC || ']]></MAC>
<MEDICARE_TYPE><![CDATA[' || :new.MEDICARE_TYPE || ']]></MEDICARE_TYPE>
<MSP><![CDATA[' || :new.MSP || ']]></MSP>
<NEW_DOCUMENTATION_REVIEWED><![CDATA[' || :new.NEW_DOCUMENTATION_REVIEWED || ']]></NEW_DOCUMENTATION_REVIEWED>
<PHYSICIAN_SPECIALTY><![CDATA[' || :new.PHYSICIAN_SPECIALTY || ']]></PHYSICIAN_SPECIALTY>
<PRECHECK_COMPLETED><![CDATA[' || :new.PRECHECK_COMPLETED || ']]></PRECHECK_COMPLETED>
<REASON_FOR_APPEAL><![CDATA[' || :new.REASON_FOR_APPEAL || ']]></REASON_FOR_APPEAL>
<WITHDRAWAL><![CDATA[' || :new.WITHDRAWAL || ']]></WITHDRAWAL>
<WITHDRAWAL_REQUEST_SUBMITTED><![CDATA[' || :new.WITHDRAWAL_REQUEST_SUBMITTED || ']]></WITHDRAWAL_REQUEST_SUBMITTED>
<NON_ENGLISH><![CDATA[' || :new.NON_ENGLISH || ']]></NON_ENGLISH>
<NON_ENGLISH_OTHER><![CDATA[' || :new.NON_ENGLISH_OTHER || ']]></NON_ENGLISH_OTHER>
<DISPOSITION><![CDATA[' || :new.DISPOSITION || ']]></DISPOSITION>
<DISPOSITION_EXPLANATION><![CDATA[' || :new.DISPOSITION_EXPLANATION || ']]></DISPOSITION_EXPLANATION>
<PROCEDURAL_DECISION_REASON><![CDATA[' || :new.PROCEDURAL_DECISION_REASON || ']]></PROCEDURAL_DECISION_REASON>
<SUBSTANTIVE_REASON><![CDATA[' || :new.SUBSTANTIVE_REASON || ']]></SUBSTANTIVE_REASON>
<FIRST_REVIEW_CASE_ATTESTATIO>' || to_char(:new.FIRST_REVIEW_CASE_ATTESTATIO,BPM_COMMON.GET_DATE_FMT) || '</FIRST_REVIEW_CASE_ATTESTATIO>
<FIRST_MEDICAL_REVIEW_DECISIO><![CDATA[' || :new.FIRST_MEDICAL_REVIEW_DECISIO || ']]></FIRST_MEDICAL_REVIEW_DECISIO>
<FIRST_REVIEWER><![CDATA[' || :new.FIRST_REVIEWER || ']]></FIRST_REVIEWER>
<THIRD_MEDICAL_REVIEW_DECISIO><![CDATA[' || :new.THIRD_MEDICAL_REVIEW_DECISIO || ']]></THIRD_MEDICAL_REVIEW_DECISIO>
<THIRD_REVIEW_CASE_ATTESTATIO>' || to_char(:new.THIRD_REVIEW_CASE_ATTESTATIO,BPM_COMMON.GET_DATE_FMT) || '</THIRD_REVIEW_CASE_ATTESTATIO>
<THIRD_REVIEWER><![CDATA[' || :new.THIRD_REVIEWER || ']]></THIRD_REVIEWER>
<EXPERT_REVIEW_CASE_ATTESTATI>' || to_char(:new.EXPERT_REVIEW_CASE_ATTESTATI,BPM_COMMON.GET_DATE_FMT) || '</EXPERT_REVIEW_CASE_ATTESTATI>
<EXPERT_REVIEW_CITATION><![CDATA[' || :new.EXPERT_REVIEW_CITATION  || ']]></EXPERT_REVIEW_CITATION>
<EXPERT_REVIEWER_MD_ID><![CDATA[' || :new.EXPERT_REVIEWER_MD_ID || ']]></EXPERT_REVIEWER_MD_ID>
<STG_EXTRACT_DATE>' || to_char(:new.STG_EXTRACT_DATE,BPM_COMMON.GET_DATE_FMT) || '</STG_EXTRACT_DATE>
<STG_LAST_UPDATE_DATE>' || to_char(:new.STG_LAST_UPDATE_DATE,BPM_COMMON.GET_DATE_FMT) || '</STG_LAST_UPDATE_DATE>
<CLOSED_DATE>' || to_char(:new.CLOSED_DATE,BPM_COMMON.GET_DATE_FMT) || '</CLOSED_DATE>
<WITHDRAWN_DATE>' || to_char(:new.WITHDRAWN_DATE,BPM_COMMON.GET_DATE_FMT) || '</WITHDRAWN_DATE>
    </ROW>
    </ROWSET>
    ';
  insert into BPM_UPDATE_EVENT_QUEUE
    (BUEQ_ID,BSL_ID,BIL_ID,IDENTIFIER,EVENT_DATE,QUEUE_DATE,DATA_VERSION,OLD_DATA,NEW_DATA)
  values (SEQ_BUEQ_ID.nextval,v_bsl_id,v_bil_id,v_identifier,v_event_date,sysdate,v_data_version,null,xmltype(v_xml_string_new));
exception
  when OTHERS then
    v_sql_code := SQLCODE;
    v_log_message := SQLERRM || '
      XML:
      ' || v_xml_string_new;
    BPM_COMMON.LOGGER(BPM_COMMON.LOG_LEVEL_SEVERE,null,$$PLSQL_UNIT,v_bsl_id,v_bil_id,v_identifier,null,v_log_message,v_sql_code);
    raise;
end;
/
create or replace trigger TRG_AU_CORP_ETL_APPEAL_Q
after update on CORP_ETL_APPEAL
for each row
declare
  v_bsl_id number := 2004; -- 'FEDQIC_ETL'
  v_bil_id number := 3; -- 'Task ID'
  v_data_version number := 3; -- CDATA for varchar2 only and added STG_LAST_UPDATE_DATE
  v_identifier varchar2(100) := null;
  v_xml_string_old clob := null;
  v_xml_string_new clob := null;
  v_sql_code number := null;
  v_log_message clob := null;
  v_event_date date := null;
begin
  v_event_date := :new.STG_LAST_UPDATE_DATE;
  v_identifier := :new.APPEAL_ID;
  /*
  Include:
    STG_LAST_UPDATE_DATE
  */
  v_xml_string_old :=
    '<?xml version="1.0"?>
    <ROWSET>
      <ROW>
 <APPEAL_ID><![CDATA[' || :old.APPEAL_ID || ']]></APPEAL_ID>
<CREATE_DATE>' || to_char(:old.CREATE_DATE,BPM_COMMON.GET_DATE_FMT) || '</CREATE_DATE>
<COMPLETE_DATE>' || to_char(:old.COMPLETE_DATE,BPM_COMMON.GET_DATE_FMT) || '</COMPLETE_DATE>
<CANCELLED_DATE>' || to_char(:old.CANCELLED_DATE,BPM_COMMON.GET_DATE_FMT) || '</CANCELLED_DATE>
<ADJUDICATOR><![CDATA[' || :old.ADJUDICATOR || ']]></ADJUDICATOR> 
<DEADLINE_DATE>' || to_char(:old.DEADLINE_DATE,BPM_COMMON.GET_DATE_FMT) || '</DEADLINE_DATE> 
<APPEAL_ISSUE><![CDATA[' || :old.APPEAL_ISSUE || ']]></APPEAL_ISSUE>
<APPEAL_ITEM><![CDATA[' || :old.APPEAL_ITEM || ']]></APPEAL_ITEM>  
<APPEAL_NUMBER><![CDATA[' || :old.APPEAL_NUMBER || ']]></APPEAL_NUMBER> 
<APPEAL_PRIORITY_ID><![CDATA[' || :old.APPEAL_PRIORITY_ID || ']]></APPEAL_PRIORITY_ID>
<REQUEST_RECEIVED>' || to_char(:old.REQUEST_RECEIVED,BPM_COMMON.GET_DATE_FMT) || '</REQUEST_RECEIVED> 
<APPEAL_STAGE><![CDATA[' || :old.APPEAL_STAGE || ']]></APPEAL_STAGE>  
<APPEAL_STATUS><![CDATA[' || :old.APPEAL_STATUS || ']]></APPEAL_STATUS> 
<APPEAL_TYPE><![CDATA[' || :old.APPEAL_TYPE || ']]></APPEAL_TYPE>
<APPEAL_DISMISSAL><![CDATA[' || :old.APPEAL_DISMISSAL || ']]></APPEAL_DISMISSAL>
<APPEAL_DISMISSAL_REASON><![CDATA[' || :old.APPEAL_DISMISSAL_REASON || ']]></APPEAL_DISMISSAL_REASON>
<AUTO_FORWARD><![CDATA[' || :old.AUTO_FORWARD || ']]></AUTO_FORWARD>
<CASE_FILE_REQUEST_DATE>' || to_char(:old.CASE_FILE_REQUEST_DATE,BPM_COMMON.GET_DATE_FMT) || '</CASE_FILE_REQUEST_DATE> 
<ACKNOWLEDGEMENT_LETTER_DATE>' || to_char(:old.ACKNOWLEDGEMENT_LETTER_DATE,BPM_COMMON.GET_DATE_FMT) || '</ACKNOWLEDGEMENT_LETTER_DATE>
<DECISION_MAILED_DATE>' || to_char(:old.DECISION_MAILED_DATE,BPM_COMMON.GET_DATE_FMT) || '</DECISION_MAILED_DATE>
<DECISION_SENT_PLAN_DATE>' || to_char(:old.DECISION_SENT_PLAN_DATE,BPM_COMMON.GET_DATE_FMT) || '</DECISION_SENT_PLAN_DATE>
<MEDICAL_REVIEW_CHECK><![CDATA[' || :old.MEDICAL_REVIEW_CHECK || ']]></MEDICAL_REVIEW_CHECK>
<APPEAL_PART_ID><![CDATA[' || :old.APPEAL_PART_ID || ']]></APPEAL_PART_ID>
<APPEAL_REASON><![CDATA[' || :old.APPEAL_REASON || ']]></APPEAL_REASON> 
<APPEAL_TOLLING_DATE>' || to_char(:old.APPEAL_TOLLING_DATE,BPM_COMMON.GET_DATE_FMT) || '</APPEAL_TOLLING_DATE>
<APPEAL_NOTICE_DATE>' || to_char(:old.APPEAL_NOTICE_DATE,BPM_COMMON.GET_DATE_FMT) || '</APPEAL_NOTICE_DATE>
<CASE_FILE_RECEIVED_DATE>' || to_char(:old.CASE_FILE_RECEIVED_DATE,BPM_COMMON.GET_DATE_FMT) || '</CASE_FILE_RECEIVED_DATE>  
<CLAIMED_DATE>' || to_char(:old.CLAIMED_DATE,BPM_COMMON.GET_DATE_FMT) || '</CLAIMED_DATE>
<DECISION><![CDATA[' || :old.DECISION || ']]></DECISION>
<DECISION_NOTIFICATION_METHOD><![CDATA[' || :old.DECISION_NOTIFICATION_METHOD || ']]></DECISION_NOTIFICATION_METHOD>
<HPMS><![CDATA[' || :old.HPMS || ']]></HPMS>
<HPMS_REQUESTED_DATE>' || to_char(:old.HPMS_REQUESTED_DATE,BPM_COMMON.GET_DATE_FMT) || '</HPMS_REQUESTED_DATE>
<IS_REQUEST_FOR_INFORMATION_P><![CDATA[' || :old.IS_REQUEST_FOR_INFORMATION_P || ']]></IS_REQUEST_FOR_INFORMATION_P>
<MAC><![CDATA[' || :old.MAC || ']]></MAC>
<MEDICARE_TYPE><![CDATA[' || :old.MEDICARE_TYPE || ']]></MEDICARE_TYPE>
<MSP><![CDATA[' || :old.MSP || ']]></MSP>
<NEW_DOCUMENTATION_REVIEWED><![CDATA[' || :old.NEW_DOCUMENTATION_REVIEWED || ']]></NEW_DOCUMENTATION_REVIEWED>
<PHYSICIAN_SPECIALTY><![CDATA[' || :old.PHYSICIAN_SPECIALTY || ']]></PHYSICIAN_SPECIALTY>
<PRECHECK_COMPLETED><![CDATA[' || :old.PRECHECK_COMPLETED || ']]></PRECHECK_COMPLETED>
<REASON_FOR_APPEAL><![CDATA[' || :old.REASON_FOR_APPEAL || ']]></REASON_FOR_APPEAL>
<WITHDRAWAL><![CDATA[' || :old.WITHDRAWAL || ']]></WITHDRAWAL>
<WITHDRAWAL_REQUEST_SUBMITTED><![CDATA[' || :old.WITHDRAWAL_REQUEST_SUBMITTED || ']]></WITHDRAWAL_REQUEST_SUBMITTED>
<NON_ENGLISH><![CDATA[' || :old.NON_ENGLISH || ']]></NON_ENGLISH>
<NON_ENGLISH_OTHER><![CDATA[' || :old.NON_ENGLISH_OTHER || ']]></NON_ENGLISH_OTHER>
<DISPOSITION><![CDATA[' || :old.DISPOSITION || ']]></DISPOSITION>
<DISPOSITION_EXPLANATION><![CDATA[' || :old.DISPOSITION_EXPLANATION || ']]></DISPOSITION_EXPLANATION>
<PROCEDURAL_DECISION_REASON><![CDATA[' || :old.PROCEDURAL_DECISION_REASON || ']]></PROCEDURAL_DECISION_REASON>
<SUBSTANTIVE_REASON><![CDATA[' || :old.SUBSTANTIVE_REASON || ']]></SUBSTANTIVE_REASON>
<FIRST_REVIEW_CASE_ATTESTATIO>' || to_char(:old.FIRST_REVIEW_CASE_ATTESTATIO,BPM_COMMON.GET_DATE_FMT) || '</FIRST_REVIEW_CASE_ATTESTATIO>
<FIRST_MEDICAL_REVIEW_DECISIO><![CDATA[' || :old.FIRST_MEDICAL_REVIEW_DECISIO || ']]></FIRST_MEDICAL_REVIEW_DECISIO>
<FIRST_REVIEWER><![CDATA[' || :old.FIRST_REVIEWER || ']]></FIRST_REVIEWER>
<THIRD_MEDICAL_REVIEW_DECISIO><![CDATA[' || :old.THIRD_MEDICAL_REVIEW_DECISIO || ']]></THIRD_MEDICAL_REVIEW_DECISIO>
<THIRD_REVIEW_CASE_ATTESTATIO>' || to_char(:old.THIRD_REVIEW_CASE_ATTESTATIO,BPM_COMMON.GET_DATE_FMT) || '</THIRD_REVIEW_CASE_ATTESTATIO>
<THIRD_REVIEWER><![CDATA[' || :old.THIRD_REVIEWER || ']]></THIRD_REVIEWER>
<EXPERT_REVIEW_CASE_ATTESTATI>' || to_char(:old.EXPERT_REVIEW_CASE_ATTESTATI,BPM_COMMON.GET_DATE_FMT) || '</EXPERT_REVIEW_CASE_ATTESTATI>
<EXPERT_REVIEW_CITATION><![CDATA[' || :old.EXPERT_REVIEW_CITATION || ']]></EXPERT_REVIEW_CITATION>
<EXPERT_REVIEWER_MD_ID><![CDATA[' || :old.EXPERT_REVIEWER_MD_ID || ']]></EXPERT_REVIEWER_MD_ID>	
<STG_EXTRACT_DATE>' || to_char(:old.STG_EXTRACT_DATE,BPM_COMMON.GET_DATE_FMT) || '</STG_EXTRACT_DATE>
<STG_LAST_UPDATE_DATE>' || to_char(:old.STG_LAST_UPDATE_DATE,BPM_COMMON.GET_DATE_FMT) || '</STG_LAST_UPDATE_DATE>
<CLOSED_DATE>' || to_char(:old.CLOSED_DATE,BPM_COMMON.GET_DATE_FMT) || '</CLOSED_DATE>
<WITHDRAWN_DATE>' || to_char(:old.WITHDRAWN_DATE,BPM_COMMON.GET_DATE_FMT) || '</WITHDRAWN_DATE>
    </ROW>
    </ROWSET>
    ';

  /*
  Include:
    STG_LAST_UPDATE_DATE
  */
  v_xml_string_new :=
    '<?xml version="1.0"?>
    <ROWSET>
      <ROW>
          <APPEAL_ID><![CDATA[' || :new.APPEAL_ID || ']]></APPEAL_ID>
<CREATE_DATE>' || to_char(:new.CREATE_DATE,BPM_COMMON.GET_DATE_FMT) || '</CREATE_DATE>
<COMPLETE_DATE>' || to_char(:new.COMPLETE_DATE,BPM_COMMON.GET_DATE_FMT) || '</COMPLETE_DATE>
<CANCELLED_DATE>' || to_char(:new.CANCELLED_DATE,BPM_COMMON.GET_DATE_FMT) || '</CANCELLED_DATE>
<ADJUDICATOR><![CDATA[' || :new.ADJUDICATOR || ']]></ADJUDICATOR> 
<DEADLINE_DATE>' || to_char(:new.DEADLINE_DATE,BPM_COMMON.GET_DATE_FMT) || '</DEADLINE_DATE> 
<APPEAL_ISSUE><![CDATA[' || :new.APPEAL_ISSUE || ']]></APPEAL_ISSUE>
<APPEAL_ITEM><![CDATA[' || :new.APPEAL_ITEM || ']]></APPEAL_ITEM>  
<APPEAL_NUMBER><![CDATA[' || :new.APPEAL_NUMBER || ']]></APPEAL_NUMBER> 
<APPEAL_PRIORITY_ID><![CDATA[' || :new.APPEAL_PRIORITY_ID || ']]></APPEAL_PRIORITY_ID>
<REQUEST_RECEIVED>' || to_char(:new.REQUEST_RECEIVED,BPM_COMMON.GET_DATE_FMT) || '</REQUEST_RECEIVED> 
<APPEAL_STAGE><![CDATA[' || :new.APPEAL_STAGE || ']]></APPEAL_STAGE>  
<APPEAL_STATUS><![CDATA[' || :new.APPEAL_STATUS || ']]></APPEAL_STATUS> 
<APPEAL_TYPE><![CDATA[' || :new.APPEAL_TYPE || ']]></APPEAL_TYPE>
<APPEAL_DISMISSAL><![CDATA[' || :new.APPEAL_DISMISSAL || ']]></APPEAL_DISMISSAL>
<APPEAL_DISMISSAL_REASON><![CDATA[' || :new.APPEAL_DISMISSAL_REASON || ']]></APPEAL_DISMISSAL_REASON>
<AUTO_FORWARD><![CDATA[' || :new.AUTO_FORWARD || ']]></AUTO_FORWARD>
<CASE_FILE_REQUEST_DATE>' || to_char(:new.CASE_FILE_REQUEST_DATE,BPM_COMMON.GET_DATE_FMT) || '</CASE_FILE_REQUEST_DATE> 
<ACKNOWLEDGEMENT_LETTER_DATE>' || to_char(:new.ACKNOWLEDGEMENT_LETTER_DATE,BPM_COMMON.GET_DATE_FMT) || '</ACKNOWLEDGEMENT_LETTER_DATE>
<DECISION_MAILED_DATE>' || to_char(:new.DECISION_MAILED_DATE,BPM_COMMON.GET_DATE_FMT) || '</DECISION_MAILED_DATE>
<DECISION_SENT_PLAN_DATE>' || to_char(:new.DECISION_SENT_PLAN_DATE,BPM_COMMON.GET_DATE_FMT) || '</DECISION_SENT_PLAN_DATE>
<MEDICAL_REVIEW_CHECK><![CDATA[' || :new.MEDICAL_REVIEW_CHECK || ']]></MEDICAL_REVIEW_CHECK>
<APPEAL_PART_ID><![CDATA[' || :new.APPEAL_PART_ID || ']]></APPEAL_PART_ID>
<APPEAL_REASON><![CDATA[' || :new.APPEAL_REASON || ']]></APPEAL_REASON> 
<APPEAL_TOLLING_DATE>' || to_char(:new.APPEAL_TOLLING_DATE,BPM_COMMON.GET_DATE_FMT) || '</APPEAL_TOLLING_DATE>
<APPEAL_NOTICE_DATE>' || to_char(:new.APPEAL_NOTICE_DATE,BPM_COMMON.GET_DATE_FMT) || '</APPEAL_NOTICE_DATE>
<CASE_FILE_RECEIVED_DATE>' || to_char(:new.CASE_FILE_RECEIVED_DATE,BPM_COMMON.GET_DATE_FMT) || '</CASE_FILE_RECEIVED_DATE>  
<CLAIMED_DATE>' || to_char(:new.CLAIMED_DATE,BPM_COMMON.GET_DATE_FMT) || '</CLAIMED_DATE>
<DECISION><![CDATA[' || :new.DECISION || ']]></DECISION>
<DECISION_NOTIFICATION_METHOD><![CDATA[' || :new.DECISION_NOTIFICATION_METHOD || ']]></DECISION_NOTIFICATION_METHOD>
<HPMS><![CDATA[' || :new.HPMS || ']]></HPMS>
<HPMS_REQUESTED_DATE>' || to_char(:new.HPMS_REQUESTED_DATE,BPM_COMMON.GET_DATE_FMT) || '</HPMS_REQUESTED_DATE>
<IS_REQUEST_FOR_INFORMATION_P><![CDATA[' || :new.IS_REQUEST_FOR_INFORMATION_P || ']]></IS_REQUEST_FOR_INFORMATION_P>
<MAC><![CDATA[' || :new.MAC || ']]></MAC>
<MEDICARE_TYPE><![CDATA[' || :new.MEDICARE_TYPE || ']]></MEDICARE_TYPE>
<MSP><![CDATA[' || :new.MSP || ']]></MSP>
<NEW_DOCUMENTATION_REVIEWED><![CDATA[' || :new.NEW_DOCUMENTATION_REVIEWED || ']]></NEW_DOCUMENTATION_REVIEWED>
<PHYSICIAN_SPECIALTY><![CDATA[' || :new.PHYSICIAN_SPECIALTY || ']]></PHYSICIAN_SPECIALTY>
<PRECHECK_COMPLETED><![CDATA[' || :new.PRECHECK_COMPLETED || ']]></PRECHECK_COMPLETED>
<REASON_FOR_APPEAL><![CDATA[' || :new.REASON_FOR_APPEAL || ']]></REASON_FOR_APPEAL>
<WITHDRAWAL><![CDATA[' || :new.WITHDRAWAL || ']]></WITHDRAWAL>
<WITHDRAWAL_REQUEST_SUBMITTED><![CDATA[' || :new.WITHDRAWAL_REQUEST_SUBMITTED || ']]></WITHDRAWAL_REQUEST_SUBMITTED>
<NON_ENGLISH><![CDATA[' || :new.NON_ENGLISH || ']]></NON_ENGLISH>
<NON_ENGLISH_OTHER><![CDATA[' || :new.NON_ENGLISH_OTHER || ']]></NON_ENGLISH_OTHER>
<DISPOSITION><![CDATA[' || :new.DISPOSITION || ']]></DISPOSITION>
<DISPOSITION_EXPLANATION><![CDATA[' || :new.DISPOSITION_EXPLANATION || ']]></DISPOSITION_EXPLANATION>
<PROCEDURAL_DECISION_REASON><![CDATA[' || :new.PROCEDURAL_DECISION_REASON || ']]></PROCEDURAL_DECISION_REASON>
<SUBSTANTIVE_REASON><![CDATA[' || :new.SUBSTANTIVE_REASON || ']]></SUBSTANTIVE_REASON>
<FIRST_REVIEW_CASE_ATTESTATIO>' || to_char(:new.FIRST_REVIEW_CASE_ATTESTATIO,BPM_COMMON.GET_DATE_FMT) || '</FIRST_REVIEW_CASE_ATTESTATIO>
<FIRST_MEDICAL_REVIEW_DECISIO><![CDATA[' || :new.FIRST_MEDICAL_REVIEW_DECISIO || ']]></FIRST_MEDICAL_REVIEW_DECISIO>
<FIRST_REVIEWER><![CDATA[' || :new.FIRST_REVIEWER || ']]></FIRST_REVIEWER>
<THIRD_MEDICAL_REVIEW_DECISIO><![CDATA[' || :new.THIRD_MEDICAL_REVIEW_DECISIO || ']]></THIRD_MEDICAL_REVIEW_DECISIO>
<THIRD_REVIEW_CASE_ATTESTATIO>' || to_char(:new.THIRD_REVIEW_CASE_ATTESTATIO,BPM_COMMON.GET_DATE_FMT) || '</THIRD_REVIEW_CASE_ATTESTATIO>
<THIRD_REVIEWER><![CDATA[' || :new.THIRD_REVIEWER || ']]></THIRD_REVIEWER>
<EXPERT_REVIEW_CASE_ATTESTATI>' || to_char(:new.EXPERT_REVIEW_CASE_ATTESTATI,BPM_COMMON.GET_DATE_FMT) || '</EXPERT_REVIEW_CASE_ATTESTATI>
<EXPERT_REVIEW_CITATION><![CDATA[' || :new.EXPERT_REVIEW_CITATION || ']]></EXPERT_REVIEW_CITATION>
<EXPERT_REVIEWER_MD_ID><![CDATA[' || :new.EXPERT_REVIEWER_MD_ID || ']]></EXPERT_REVIEWER_MD_ID>
<STG_EXTRACT_DATE>' || to_char(:new.STG_EXTRACT_DATE,BPM_COMMON.GET_DATE_FMT) || '</STG_EXTRACT_DATE>
<STG_LAST_UPDATE_DATE>' || to_char(:new.STG_LAST_UPDATE_DATE,BPM_COMMON.GET_DATE_FMT) || '</STG_LAST_UPDATE_DATE>
<CLOSED_DATE>' || to_char(:new.CLOSED_DATE,BPM_COMMON.GET_DATE_FMT) || '</CLOSED_DATE>
<WITHDRAWN_DATE>' || to_char(:new.WITHDRAWN_DATE,BPM_COMMON.GET_DATE_FMT) || '</WITHDRAWN_DATE>
     </ROW>
    </ROWSET>
    ';

  insert into BPM_UPDATE_EVENT_QUEUE
    (BUEQ_ID,BSL_ID,BIL_ID,IDENTIFIER,EVENT_DATE,QUEUE_DATE,DATA_VERSION,OLD_DATA,NEW_DATA)
    values (SEQ_BUEQ_ID.nextval,v_bsl_id,v_bil_id,v_identifier,v_event_date,sysdate,v_data_version,xmltype(v_xml_string_old),xmltype(v_xml_string_new));

exception

  when OTHERS then
    v_sql_code := SQLCODE;
    v_log_message := SQLERRM || '
      XML (old):
      ' || v_xml_string_old || '
      XML (new):
      ' || v_xml_string_new;
    BPM_COMMON.LOGGER(BPM_COMMON.LOG_LEVEL_SEVERE,null,$$PLSQL_UNIT,v_bsl_id,v_bil_id,v_identifier,null,v_log_message,v_sql_code);
    raise;

end;
/

alter session set plsql_code_type = interpreted;
