CREATE OR REPLACE VIEW D_PL_LETTER_STATUS_SV
AS
  SELECT report_label LETTER_STATUS    
  FROM enum_lm_status ;
  
GRANT SELECT ON MAXDAT_SUPPORT.D_PL_LETTER_STATUS_SV TO MAXDAT_REPORTS;
GRANT SELECT ON MAXDAT_SUPPORT.D_PL_LETTER_STATUS_SV TO MAXDAT_SUPPORT_READ_ONLY;