CREATE OR REPLACE VIEW MAXDAT_SUPPORT.F_PL_LET_REQ_STAT_HIST_SV
AS
SELECT "LRSHISTORY_ID",
	"LMREQ_ID",
	"STATUS_CD",
	"CREATED_BY",
	CREATE_TS AS STATUS_CREATE_TIMESTAMP,
    TRUNC(CREATE_TS) AS STATUS_CREATE_DATE,
    to_number(extract(month from CREATE_TS)) AS STATUS_CREATE_MONTH_NO,
    SUBSTR(to_char(CREATE_TS,'Month'),1,3) AS STATUS_CREATE_MONTH,
    to_number(extract(year from CREATE_TS)) AS STATUS_CREATE_YEAR	
	FROM letter_req_status_history
	WHERE  (CREATE_TS >= (SYSDATE - (365)));


GRANT SELECT ON MAXDAT_SUPPORT.F_PL_LET_REQ_STAT_HIST_SV TO MAXDAT_SUPPORT_READ_ONLY;
GRANT SELECT ON MAXDAT_SUPPORT.F_PL_LET_REQ_STAT_HIST_SV TO MAXDAT_REPORTS; 

