
ALTER TABLE CC_F_AGENT_BY_DATE MODIFY (FIRST_LOGIN NULL);
ALTER TABLE CC_F_AGENT_BY_DATE MODIFY (LAST_LOGOUT NULL);
ALTER TABLE CC_F_AGENT_BY_DATE MODIFY (SCHEDULED_SHIFT_MINUTES NULL);
ALTER TABLE CC_F_AGENT_BY_DATE MODIFY (ACTUAL_SHIFT_MINUTES NULL);
ALTER TABLE CC_F_AGENT_BY_DATE MODIFY (ACTUAL_OVERTIME_MINUTES NULL);
