ALTER TABLE CORP_ETL_CLNT_OUTREACH 
  ADD (EXEFF_OTHER_IND VARCHAR2(4000 BYTE));
  
ALTER TABLE CORP_ETL_CLNT_OUTREACH_OLTP  
  ADD (EXEFF_OTHER_IND VARCHAR2(4000 BYTE));  
  
ALTER TABLE CORP_ETL_CLNT_OUTREACH_WIP_BPM   
  ADD (EXEFF_OTHER_IND VARCHAR2(4000 BYTE));