Insert into CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MAX_UPDATE_TS_ENUM_FORM','D','2011/01/01 00:00:00','Max Update Date for ENUM_DOC_CODE_TO_TYPE Stage table',SYSDATE,SYSDATE);

Insert into CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MAX_UPDATE_TS_ENUM_ENV','D','2011/01/01 00:00:00','Max Update Date for ENUM_ENVELOPE_STATUS Stage table',SYSDATE,SYSDATE);

commit;