delete from MAXDAT.D_NYHIX_MFD_HISTORY_V2;
delete from MAXDAT.D_NYHIX_MFD_DOC_TYPE_V2;
delete from MAXDAT.D_NYHIX_MFD_DOC_STATUS_V2;
delete from MAXDAT.D_NYHIX_MFD_ENV_STATUS_V2;
delete from MAXDAT.D_NYHIX_MFD_FORM_TYPE_V2;
delete from MAXDAT.D_NYHIX_MFD_INS_STATUS_V2;
delete from MAXDAT.D_NYHIX_MFD_TIME_STATUS_V2;
delete from MAXDAT.D_NYHIX_MFD_CURRENT_V2;
commit;