update D_NYHIX_MFD_CURRENT_V2 V1
SET RECVD_TO_SCAN_AGE_IN_CAL_DAYS = (SELECT CASE WHEN RECEIVED_DT IS NOT NULL AND SCAN_DT IS NOT NULL AND ((TRUNC(SCAN_DT) - TRUNC(RECEIVED_DT)) >= 0)
                                            THEN (TRUNC(SCAN_DT) - TRUNC(RECEIVED_DT)) 
											ELSE CASE WHEN RECEIVED_DT IS NULL OR SCAN_DT IS NULL 
												THEN NULL 
												ELSE 0 END 
											END 
									FROM D_NYHIX_MFD_CURRENT_V2 V2 WHERE V2.NYHIX_MFD_BI_ID = V1.NYHIX_MFD_BI_ID)
,   RECVD_TO_SCAN_AGE_IN_BUS_DAYS = (SELECT CASE WHEN RECEIVED_DT IS NOT NULL AND SCAN_DT IS NOT NULL 
                                            THEN BUS_DAYS_BETWEEN(received_dt, scan_dt) 
											ELSE NULL 
											END 
									FROM D_NYHIX_MFD_CURRENT_V2 V2 WHERE V2.NYHIX_MFD_BI_ID = V1.NYHIX_MFD_BI_ID)											
WHERE instance_status ='Complete'
and (RECVD_TO_SCAN_AGE_IN_CAL_DAYS IS NULL
OR RECVD_TO_SCAN_AGE_IN_BUS_DAYS IS NULL)
AND trunc(CREATE_DT) BETWEEN trunc(to_date('10/01/2013','MM/DD/YYYY')) AND trunc(to_date('12/31/2013','MM/DD/YYYY'))
;

commit;

update D_NYHIX_MFD_CURRENT_V2 V1
SET RECVD_TO_SCAN_AGE_IN_CAL_DAYS = (SELECT CASE WHEN RECEIVED_DT IS NOT NULL AND SCAN_DT IS NOT NULL AND ((TRUNC(SCAN_DT) - TRUNC(RECEIVED_DT)) >= 0)
                                            THEN (TRUNC(SCAN_DT) - TRUNC(RECEIVED_DT)) 
											ELSE CASE WHEN RECEIVED_DT IS NULL OR SCAN_DT IS NULL 
												THEN NULL 
												ELSE 0 END 
											END 
									FROM D_NYHIX_MFD_CURRENT_V2 V2 WHERE V2.NYHIX_MFD_BI_ID = V1.NYHIX_MFD_BI_ID)
,   RECVD_TO_SCAN_AGE_IN_BUS_DAYS = (SELECT CASE WHEN RECEIVED_DT IS NOT NULL AND SCAN_DT IS NOT NULL 
                                            THEN BUS_DAYS_BETWEEN(received_dt, scan_dt) 
											ELSE NULL 
											END 
									FROM D_NYHIX_MFD_CURRENT_V2 V2 WHERE V2.NYHIX_MFD_BI_ID = V1.NYHIX_MFD_BI_ID)											
WHERE instance_status ='Complete'
and (RECVD_TO_SCAN_AGE_IN_CAL_DAYS IS NULL
OR RECVD_TO_SCAN_AGE_IN_BUS_DAYS IS NULL)
AND trunc(CREATE_DT) BETWEEN trunc(to_date('01/01/2014','MM/DD/YYYY')) AND trunc(to_date('06/30/2014','MM/DD/YYYY'))
;

commit;

update D_NYHIX_MFD_CURRENT_V2 V1
SET RECVD_TO_SCAN_AGE_IN_CAL_DAYS = (SELECT CASE WHEN RECEIVED_DT IS NOT NULL AND SCAN_DT IS NOT NULL AND ((TRUNC(SCAN_DT) - TRUNC(RECEIVED_DT)) >= 0)
                                            THEN (TRUNC(SCAN_DT) - TRUNC(RECEIVED_DT)) 
											ELSE CASE WHEN RECEIVED_DT IS NULL OR SCAN_DT IS NULL 
												THEN NULL 
												ELSE 0 END 
											END 
									FROM D_NYHIX_MFD_CURRENT_V2 V2 WHERE V2.NYHIX_MFD_BI_ID = V1.NYHIX_MFD_BI_ID)
,   RECVD_TO_SCAN_AGE_IN_BUS_DAYS = (SELECT CASE WHEN RECEIVED_DT IS NOT NULL AND SCAN_DT IS NOT NULL 
                                            THEN BUS_DAYS_BETWEEN(received_dt, scan_dt) 
											ELSE NULL 
											END 
									FROM D_NYHIX_MFD_CURRENT_V2 V2 WHERE V2.NYHIX_MFD_BI_ID = V1.NYHIX_MFD_BI_ID)											
WHERE instance_status ='Complete'
and (RECVD_TO_SCAN_AGE_IN_CAL_DAYS IS NULL
OR RECVD_TO_SCAN_AGE_IN_BUS_DAYS IS NULL)
AND trunc(CREATE_DT) BETWEEN trunc(to_date('07/01/2014','MM/DD/YYYY')) AND trunc(to_date('12/31/2014','MM/DD/YYYY'))
;

commit;

update D_NYHIX_MFD_CURRENT_V2 V1
SET RECVD_TO_SCAN_AGE_IN_CAL_DAYS = (SELECT CASE WHEN RECEIVED_DT IS NOT NULL AND SCAN_DT IS NOT NULL AND ((TRUNC(SCAN_DT) - TRUNC(RECEIVED_DT)) >= 0)
                                            THEN (TRUNC(SCAN_DT) - TRUNC(RECEIVED_DT)) 
											ELSE CASE WHEN RECEIVED_DT IS NULL OR SCAN_DT IS NULL 
												THEN NULL 
												ELSE 0 END 
											END 
									FROM D_NYHIX_MFD_CURRENT_V2 V2 WHERE V2.NYHIX_MFD_BI_ID = V1.NYHIX_MFD_BI_ID)
,   RECVD_TO_SCAN_AGE_IN_BUS_DAYS = (SELECT CASE WHEN RECEIVED_DT IS NOT NULL AND SCAN_DT IS NOT NULL 
                                            THEN BUS_DAYS_BETWEEN(received_dt, scan_dt) 
											ELSE NULL 
											END 
									FROM D_NYHIX_MFD_CURRENT_V2 V2 WHERE V2.NYHIX_MFD_BI_ID = V1.NYHIX_MFD_BI_ID)											
WHERE instance_status ='Complete'
and (RECVD_TO_SCAN_AGE_IN_CAL_DAYS IS NULL
OR RECVD_TO_SCAN_AGE_IN_BUS_DAYS IS NULL)
AND trunc(CREATE_DT) BETWEEN trunc(to_date('01/01/2015','MM/DD/YYYY')) AND trunc(to_date('06/30/2015','MM/DD/YYYY'))
;

commit;

update D_NYHIX_MFD_CURRENT_V2 V1
SET RECVD_TO_SCAN_AGE_IN_CAL_DAYS = (SELECT CASE WHEN RECEIVED_DT IS NOT NULL AND SCAN_DT IS NOT NULL AND ((TRUNC(SCAN_DT) - TRUNC(RECEIVED_DT)) >= 0)
                                            THEN (TRUNC(SCAN_DT) - TRUNC(RECEIVED_DT)) 
											ELSE CASE WHEN RECEIVED_DT IS NULL OR SCAN_DT IS NULL 
												THEN NULL 
												ELSE 0 END 
											END 
									FROM D_NYHIX_MFD_CURRENT_V2 V2 WHERE V2.NYHIX_MFD_BI_ID = V1.NYHIX_MFD_BI_ID)
,   RECVD_TO_SCAN_AGE_IN_BUS_DAYS = (SELECT CASE WHEN RECEIVED_DT IS NOT NULL AND SCAN_DT IS NOT NULL 
                                            THEN BUS_DAYS_BETWEEN(received_dt, scan_dt) 
											ELSE NULL 
											END 
									FROM D_NYHIX_MFD_CURRENT_V2 V2 WHERE V2.NYHIX_MFD_BI_ID = V1.NYHIX_MFD_BI_ID)											
WHERE instance_status ='Complete'
and (RECVD_TO_SCAN_AGE_IN_CAL_DAYS IS NULL
OR RECVD_TO_SCAN_AGE_IN_BUS_DAYS IS NULL)
AND trunc(CREATE_DT) BETWEEN trunc(to_date('07/01/2015','MM/DD/YYYY')) AND trunc(to_date('12/31/2015','MM/DD/YYYY'))
;

commit;

update D_NYHIX_MFD_CURRENT_V2 V1
SET RECVD_TO_SCAN_AGE_IN_CAL_DAYS = (SELECT CASE WHEN RECEIVED_DT IS NOT NULL AND SCAN_DT IS NOT NULL AND ((TRUNC(SCAN_DT) - TRUNC(RECEIVED_DT)) >= 0)
                                            THEN (TRUNC(SCAN_DT) - TRUNC(RECEIVED_DT)) 
											ELSE CASE WHEN RECEIVED_DT IS NULL OR SCAN_DT IS NULL 
												THEN NULL 
												ELSE 0 END 
											END 
									FROM D_NYHIX_MFD_CURRENT_V2 V2 WHERE V2.NYHIX_MFD_BI_ID = V1.NYHIX_MFD_BI_ID)
,   RECVD_TO_SCAN_AGE_IN_BUS_DAYS = (SELECT CASE WHEN RECEIVED_DT IS NOT NULL AND SCAN_DT IS NOT NULL 
                                            THEN BUS_DAYS_BETWEEN(received_dt, scan_dt) 
											ELSE NULL 
											END 
									FROM D_NYHIX_MFD_CURRENT_V2 V2 WHERE V2.NYHIX_MFD_BI_ID = V1.NYHIX_MFD_BI_ID)											
WHERE instance_status ='Complete'
and (RECVD_TO_SCAN_AGE_IN_CAL_DAYS IS NULL
OR RECVD_TO_SCAN_AGE_IN_BUS_DAYS IS NULL)
AND trunc(CREATE_DT) BETWEEN trunc(to_date('01/01/2016','MM/DD/YYYY')) AND trunc(to_date('06/30/2016','MM/DD/YYYY'))
;

commit;

update D_NYHIX_MFD_CURRENT_V2 V1
SET RECVD_TO_SCAN_AGE_IN_CAL_DAYS = (SELECT CASE WHEN RECEIVED_DT IS NOT NULL AND SCAN_DT IS NOT NULL AND ((TRUNC(SCAN_DT) - TRUNC(RECEIVED_DT)) >= 0)
                                            THEN (TRUNC(SCAN_DT) - TRUNC(RECEIVED_DT)) 
											ELSE CASE WHEN RECEIVED_DT IS NULL OR SCAN_DT IS NULL 
												THEN NULL 
												ELSE 0 END 
											END 
									FROM D_NYHIX_MFD_CURRENT_V2 V2 WHERE V2.NYHIX_MFD_BI_ID = V1.NYHIX_MFD_BI_ID)
,   RECVD_TO_SCAN_AGE_IN_BUS_DAYS = (SELECT CASE WHEN RECEIVED_DT IS NOT NULL AND SCAN_DT IS NOT NULL 
                                            THEN BUS_DAYS_BETWEEN(received_dt, scan_dt) 
											ELSE NULL 
											END 
									FROM D_NYHIX_MFD_CURRENT_V2 V2 WHERE V2.NYHIX_MFD_BI_ID = V1.NYHIX_MFD_BI_ID)											
WHERE instance_status ='Complete'
and (RECVD_TO_SCAN_AGE_IN_CAL_DAYS IS NULL
OR RECVD_TO_SCAN_AGE_IN_BUS_DAYS IS NULL)
AND trunc(CREATE_DT) BETWEEN trunc(to_date('07/01/2016','MM/DD/YYYY')) AND trunc(to_date('12/31/2016','MM/DD/YYYY'))
;

commit;

update D_NYHIX_MFD_CURRENT_V2 V1
SET RECVD_TO_SCAN_AGE_IN_CAL_DAYS = (SELECT CASE WHEN RECEIVED_DT IS NOT NULL AND SCAN_DT IS NOT NULL AND ((TRUNC(SCAN_DT) - TRUNC(RECEIVED_DT)) >= 0)
                                            THEN (TRUNC(SCAN_DT) - TRUNC(RECEIVED_DT)) 
											ELSE CASE WHEN RECEIVED_DT IS NULL OR SCAN_DT IS NULL 
												THEN NULL 
												ELSE 0 END 
											END 
									FROM D_NYHIX_MFD_CURRENT_V2 V2 WHERE V2.NYHIX_MFD_BI_ID = V1.NYHIX_MFD_BI_ID)
,   RECVD_TO_SCAN_AGE_IN_BUS_DAYS = (SELECT CASE WHEN RECEIVED_DT IS NOT NULL AND SCAN_DT IS NOT NULL 
                                            THEN BUS_DAYS_BETWEEN(received_dt, scan_dt) 
											ELSE NULL 
											END 
									FROM D_NYHIX_MFD_CURRENT_V2 V2 WHERE V2.NYHIX_MFD_BI_ID = V1.NYHIX_MFD_BI_ID)											
WHERE instance_status ='Complete'
and (RECVD_TO_SCAN_AGE_IN_CAL_DAYS IS NULL
OR RECVD_TO_SCAN_AGE_IN_BUS_DAYS IS NULL)
AND trunc(CREATE_DT) BETWEEN trunc(to_date('01/01/2017','MM/DD/YYYY')) AND trunc(to_date('08/31/2017','MM/DD/YYYY'))
;

commit;





