alter table maxdat.NYHIX_ETL_MAIL_FAX_DOC_APP_V2 add (HX_LINK_ID varchar2(30));

CREATE OR REPLACE VIEW MAXDAT.NYHIX_ETL_MFD_APP_V2_SV
AS
select "APP_DOC_DATA_ID"
,"APP_DOC_INDV_ID"
,"LINK_CREATE_DT"
,"HXID"
,"HX_ACCOUNT_ID"
,"LINK_UPDATE_DT"
,"FIRST_NAME"
,"LAST_NAME"
,"HOH_IND"
,"PRIMARY_PERSON_IND"
,"HX_ACCOUNT_ID_LINK"
,"HX_LINK_ID" 
from NYHIX_ETL_MAIL_FAX_DOC_APP_V2;

GRANT SELECT ON MAXDAT.NYHIX_ETL_MFD_APP_V2_SV TO MAXDAT_READ_ONLY;
GRANT SELECT ON MAXDAT.NYHIX_ETL_MFD_APP_V2_SV TO DP_SCORECARD;


