ALTER TABLE MAXDAT.NYHIX_ETL_MAIL_FAX_DOC_CSC_V2 ADD ACTION_STATUS VARCHAR2(50 BYTE);


CREATE TABLE  MAXDAT.NYHIX_ETL_MAIL_FAX_DOC_CSC_HIST 
   (	"CSC_DETAIL_ID" NUMBER(18,0) NOT NULL ENABLE, 
	"KOFAX_DCN" VARCHAR2(256 BYTE), 
	"CSC_PROC_STATUS_CD" VARCHAR2(256 BYTE), 
	"CSC_PROC_ERROR_CD" VARCHAR2(256 BYTE), 
	"CSC_PROC_DT" DATE, 
	"DCN" VARCHAR2(256 BYTE), 
	"ACTION_STATUS" VARCHAR2(50 BYTE), 
	 CONSTRAINT "CD_ID_PK_HIST" PRIMARY KEY ("CSC_DETAIL_ID")
   ) SEGMENT CREATION IMMEDIATE ;
   

create or replace view NYHIX_ETL_MFD_CSC_V2_SV as select * from NYHIX_ETL_MAIL_FAX_DOC_CSC_V2;
