ALTER TABLE app_doc_data_ext_stg
ADD (APP_DOC_REDACTION_DATA_ID NUMBER(18,0)  );

ALTER TABLE NYHIX_ETL_MAIL_FAX_DOC_OLTP_V2
ADD (APP_DOC_REDACTION_DATA_ID NUMBER(18,0)
     ,REDACTED_INFO_FLAG VARCHAR2(1));

ALTER TABLE NYHIX_ETL_MAIL_FAX_DOC_WIP_V2
ADD (APP_DOC_REDACTION_DATA_ID NUMBER(18,0)
    ,REDACTED_INFO_FLAG VARCHAR2(1));

ALTER TABLE NYHIX_ETL_MAIL_FAX_DOC_V2
ADD (APP_DOC_REDACTION_DATA_ID NUMBER(18,0)
    ,REDACTED_INFO_FLAG VARCHAR2(1));

ALTER TABLE D_NYHIX_MFD_CURRENT_V2
ADD (APP_DOC_REDACTION_DATA_ID NUMBER(18,0)
    ,REDACTED_INFO_FLAG VARCHAR2(1));

CREATE INDEX IDX4_APP_DOC_DATA_EXT_RID ON APP_DOC_DATA_EXT_STG(APP_DOC_REDACTION_DATA_ID) TABLESPACE MAXDAT_DATA;