

CREATE SEQUENCE  "FLCPD0_MAXDAT"."KFD_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1241 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE "FLCPD0_MAXDAT"."KFDOCDATA_TEMP" 
   ("KFD_ID" NUMBER NOT NULL ENABLE, 
	"KFD_CNTR" NUMBER NOT NULL ENABLE, 
	"SCANOP" VARCHAR2(50 BYTE), 
	"INDEXOP" VARCHAR2(50 BYTE), 
	"INDEXOP2" VARCHAR2(50 BYTE), 
	"DOCTYPE" VARCHAR2(50 BYTE), 
	"BATCHNAME" VARCHAR2(50 BYTE), 
	"BATCHCLASS" VARCHAR2(50 BYTE), 
	"ECN" VARCHAR2(50 BYTE), 
	"DCN" VARCHAR2(50 BYTE), 
	"PAGECOUNT" NUMBER, 
	"EXPORTDATE" VARCHAR2(20 BYTE), 
	"KFDOCID" VARCHAR2(50 BYTE), 
	 CONSTRAINT "KFDOCDATA_TEMP_PK" PRIMARY KEY ("KFD_ID"));

  CREATE OR REPLACE TRIGGER "FLCPD0_MAXDAT"."KFDOCDATA_TEMP_TRIG" 
   before insert on "FLCPD0_MAXDAT"."KFDOCDATA_TEMP" 
   for each row 
begin  
   if inserting then 
      if :NEW."KFD_ID" is null then 
         select KFD_ID_SEQ.nextval into :NEW."KFD_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "FLCPD0_MAXDAT"."KFDOCDATA_TEMP_TRIG" ENABLE;
