--------------------------------------------------------
--  File created - Thursday-September-12-2013   
--------------------------------------------------------
DROP TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM";
/
--------------------------------------------------------
--  DDL for Table FLHK_ETL_MANAGE_WORK_WIP_BPM
--------------------------------------------------------

  CREATE TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" 
  ("MW_ID" NUMBER,
 "TASK_ID" NUMBER,
 "PARENT_TASK_ID" NUMBER,
 "TASK_TYPE" VARCHAR2(100),
 "TASK_STATUS" VARCHAR2(100),
 "STATUS_DATE" DATE,
 "STATUS_REASON" VARCHAR2(100),
 "CREATE_DATE" DATE,
 "CREATED_BY_NAME" VARCHAR2(100),
 "PRIORITY" VARCHAR2(100),
 "DUE_DATE" DATE,
 "ASSIGNED_TO" VARCHAR2(100),
 "QUEUE" VARCHAR2(100),
 "CONTEXT" VARCHAR2(100),
 "DRIVER_TYPE" VARCHAR2(100),
 "DRIVER_KEY" VARCHAR2(50),
 "ACTION_CATEGORY" VARCHAR2(100),
 "RULE_EXECUTED" VARCHAR2(100),
 "ROLE_NAME" VARCHAR2(20),
 "CANCEL_WORK_DATE" DATE,
 "COMPLETE_DATE" DATE,
 "INSTANCE_STATUS" VARCHAR2(100) DEFAULT 'Active',
 "LAST_UPDATE_DATE" DATE,
 "LAST_UPDATE_BY_NAME" VARCHAR2(100),
 "ASF_CANCEL_WORK" VARCHAR2(1) DEFAULT 'N',
 "STAGE_DONE_DATE" DATE DEFAULT NULL,
 "STG_EXTRACT_DATE" DATE DEFAULT SYSDATE,
 "STG_LAST_UPDATE_DATE" DATE DEFAULT SYSDATE,
 "ASF_COMPLETE_WORK" VARCHAR2(1) DEFAULT 'N',
 "ASSD_COMPLETE_TASK" DATE,
 "ASED_COMPLETE_TASK" DATE,
 "MW_PROCESSED" VARCHAR2(1) DEFAULT 'N',
 "WRSTATUS_ID" NUMBER) ;
/
--------------------------------------------------------
--  DDL for Index ETL_MANAGED_WORK_WIP_BPM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETL_MANAGED_WORK_WIP_BPM_PK" ON "FLHK_ETL_MANAGE_WORK_WIP_BPM" ("MW_ID") ;
/
--------------------------------------------------------
--  Constraints for Table FLHK_ETL_MANAGE_WORK_WIP_BPM
--------------------------------------------------------

  ALTER TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" MODIFY ("MW_PROCESSED" NOT NULL ENABLE);
  ALTER TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" ADD CONSTRAINT "ETL_MANAGED_WORK_WIP_BPM_PK" PRIMARY KEY ("MW_ID") ENABLE;
  ALTER TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" MODIFY ("ASSD_COMPLETE_TASK" NOT NULL ENABLE);
  ALTER TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" MODIFY ("ASF_COMPLETE_WORK" NOT NULL ENABLE);
  ALTER TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" MODIFY ("STG_LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" MODIFY ("STG_EXTRACT_DATE" NOT NULL ENABLE);
  ALTER TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" MODIFY ("ASF_CANCEL_WORK" NOT NULL ENABLE);
  ALTER TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" MODIFY ("INSTANCE_STATUS" NOT NULL ENABLE);
  ALTER TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" MODIFY ("DRIVER_KEY" NOT NULL ENABLE);
  ALTER TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" MODIFY ("DRIVER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" MODIFY ("PRIORITY" NOT NULL ENABLE);
  ALTER TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" MODIFY ("STATUS_DATE" NOT NULL ENABLE);
  ALTER TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" MODIFY ("TASK_STATUS" NOT NULL ENABLE);
  ALTER TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" MODIFY ("TASK_TYPE" NOT NULL ENABLE);
  ALTER TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "FLHK_ETL_MANAGE_WORK_WIP_BPM" MODIFY ("MW_ID" NOT NULL ENABLE);
/
