Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 18000;
Update Nyec_etl_process_app set Heart_Case_status = 'Withdrawn from HEART' where App_id = 139254;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 145154;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 147141;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 150131;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 151113;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 152394;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 158813;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 165140;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 208781;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 229289;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 240322;
Update Nyec_etl_process_app set Heart_Case_status = 'First Contact' where App_id = 244533;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 245208;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 246276;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 246284;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 251746;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 252290;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 255195;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 257173;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 257368;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 257386;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 259329;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 259526;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 262681;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 263657;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 263728;
Update Nyec_etl_process_app set Heart_Case_status = 'Sign-off (Transactions Submitted)' where App_id = 263809;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 266003;
Update Nyec_etl_process_app set Heart_Case_status = 'Referred / withdrawn from HEART' where App_id = 267663;
Update Nyec_etl_process_app set Heart_Case_status = 'Error' where App_id = 268147;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 269718;
Update Nyec_etl_process_app set Heart_Case_status = 'Sign-off (Transactions Submitted)' where App_id = 272988;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 274081;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 274836;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 276129;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 276136;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 278127;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 278181;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 279128;
Update Nyec_etl_process_app set Heart_Case_status = 'Referred / withdrawn from HEART' where App_id = 280201;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 282214;
Update Nyec_etl_process_app set Heart_Case_status = 'Withdrawn from HEART' where App_id = 283511;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 284228;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 284768;
Update Nyec_etl_process_app set Heart_Case_status = 'In Progress' where App_id = 285640;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 286598;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 286815;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 288474;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 288926;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 290759;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 292716;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 293255;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 294584;
Update Nyec_etl_process_app set Heart_Case_status = 'First Contact' where App_id = 296452;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 296771;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 300657;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 300672;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 302594;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 308273;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 313112;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 315449;
Commit;