Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 99654;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 99705;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 111026;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 119608;
Update Nyec_etl_process_app set Heart_Case_status = 'Withdrawn from HEART' where App_id = 122268;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 129222;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 128321;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 141701;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 145545;
Update Nyec_etl_process_app set Heart_Case_status = 'In Progress' where App_id = 152772;
Update Nyec_etl_process_app set Heart_Case_status = 'In Progress' where App_id = 151239;
Update Nyec_etl_process_app set Heart_Case_status = 'Auto Close Transaction Submitted' where App_id = 166754;
Update Nyec_etl_process_app set Heart_Case_status = 'In Progress' where App_id = 186926;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 236317;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 237210;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 243556;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 246568;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 247745;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 247931;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 247836;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 248305;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 249333;
Update Nyec_etl_process_app set Heart_Case_status = 'In Progress' where App_id = 251515;
Update Nyec_etl_process_app set Heart_Case_status = 'Sign-off (Transactions Submitted)' where App_id = 253180;
Update Nyec_etl_process_app set Heart_Case_status = 'Withdrawn from HEART' where App_id = 253370;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 253704;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 254267;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 257686;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 259014;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 260060;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 260048;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 260897;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 261953;
Update Nyec_etl_process_app set Heart_Case_status = 'Withdrawn from HEART' where App_id = 262796;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 263790;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 269925;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 276152;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 279170;
Update Nyec_etl_process_app set Heart_Case_status = 'In Progress' where App_id = 280567;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 281046;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 284607;
Update Nyec_etl_process_app set Heart_Case_status = 'In Progress' where App_id = 285143;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 286393;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 286323;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 286427;
Update Nyec_etl_process_app set Heart_Case_status = 'In Progress' where App_id = 286591;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 287001;
Update Nyec_etl_process_app set Heart_Case_status = 'In Progress' where App_id = 288336;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 288692;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 290588;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 294121;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 295908;
Update Nyec_etl_process_app set Heart_Case_status = 'Error' where App_id = 303081;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 315967;
Update Nyec_etl_process_app set Heart_Case_status = 'Supervisor Review' where App_id = 315449;
Update Nyec_etl_process_app set Heart_Case_status = 'Auto Close Transaction Submitted' where App_id = 319039;
Update Nyec_etl_process_app set Heart_Case_status = 'Withdrawn from HEART' where App_id = 322974;
Update Nyec_etl_process_app set Heart_Case_status = 'Complete (no further action)' where App_id = 325419;
commit;
