DROP VIEW  awdb.Agent;
DROP VIEW  awdb.Agent_Attribute;
DROP VIEW  awdb.Agent_Desk_Settings;
DROP VIEW  awdb.Agent_Real_Time;
DROP VIEW  awdb.Agent_Team;
DROP VIEW  awdb.Agent_Team_Member;
DROP VIEW  awdb.Agent_Team_Supervisor;
DROP VIEW  awdb.Agent_Skill_Group_Real_Time;
DROP VIEW  awdb.Attribute;
DROP VIEW  awdb.Attribute_Set;
DROP VIEW  awdb.Attribute_Set_Member;
DROP VIEW  awdb.Bucket_Intervals;
DROP VIEW  awdb.Business_Entity;
DROP VIEW  awdb.Call_Type;
DROP VIEW  awdb.Call_Type_Map;
DROP VIEW  awdb.Call_Type_Real_Time;
DROP VIEW  awdb.Campaign;
DROP VIEW  awdb.Department;
DROP VIEW  awdb.Department_Member;
DROP VIEW  awdb.Enterprise_Skill_Group;
DROP VIEW  awdb.Enterprise_Skill_Group_Member;
DROP VIEW  awdb.Expanded_Call_Variable;
DROP VIEW  awdb.Master_Script;
DROP VIEW  awdb.Media_Class;
DROP VIEW  awdb.Media_Routing_Domain;
DROP VIEW  awdb.Network_Trunk_Group;
DROP VIEW  awdb.Network_Vru;
DROP VIEW  awdb.Peripheral;
DROP VIEW  awdb.Person;
DROP VIEW  awdb.Precision_Queue;
DROP VIEW  awdb.Precision_Q_Real_Time;
DROP VIEW  awdb.Reason_Code;
DROP VIEW  awdb.Route;
DROP VIEW  awdb.Routing_Client;
DROP VIEW  awdb.Route_Real_Time;
DROP VIEW  awdb.Service;
DROP VIEW  awdb.Service_Member;
DROP VIEW  awdb.Skill_Group;
DROP VIEW  awdb.Skill_Group_Member;
DROP VIEW  awdb.Skill_Group_Real_Time;
DROP VIEW  awdb.User_Variable;

 
CREATE VIEW [awdb].[Agent] as (select * from maxco_awdb.dbo.[Agent]) ;
CREATE VIEW [awdb].[Agent_Attribute] as (select * from maxco_awdb.dbo.[Agent_Attribute]) ;
CREATE VIEW [awdb].[Agent_Desk_Settings] as (select * from maxco_awdb.dbo.[Agent_Desk_Settings]) ;
CREATE VIEW [awdb].[Agent_Real_Time] as (select * from maxco_awdb.dbo.[Agent_Real_Time]) ;
CREATE VIEW [awdb].[Agent_Team] as (select * from maxco_awdb.dbo.[Agent_Team]) ;
CREATE VIEW [awdb].[Agent_Team_Member] as (select * from maxco_awdb.dbo.[Agent_Team_Member]) ;
CREATE VIEW [awdb].[Agent_Team_Supervisor] as (select * from maxco_awdb.dbo.[Agent_Team_Supervisor]) ;
CREATE VIEW [awdb].[Agent_Skill_Group_Real_Time] as (select * from maxco_awdb.dbo.[Agent_Skill_Group_Real_Time]) ;
CREATE VIEW [awdb].[Attribute] as (select * from maxco_awdb.dbo.[Attribute]) ;
CREATE VIEW [awdb].[Attribute_Set] as (select * from maxco_awdb.dbo.[Attribute_Set]) ;
CREATE VIEW [awdb].[Attribute_Set_Member] as (select * from maxco_awdb.dbo.[Attribute_Set_Member]) ;
CREATE VIEW [awdb].[Bucket_Intervals] as (select * from maxco_awdb.dbo.[Bucket_Intervals]) ;
CREATE VIEW [awdb].[Business_Entity] as (select * from maxco_awdb.dbo.[Business_Entity]) ;
CREATE VIEW [awdb].[Call_Type] as (select * from maxco_awdb.dbo.[Call_Type]) ;
CREATE VIEW [awdb].[Call_Type_Map] as (select * from maxco_awdb.dbo.[Call_Type_Map]) ;
CREATE VIEW [awdb].[Call_Type_Real_Time] as (select * from maxco_awdb.dbo.[Call_Type_Real_Time]) ;
CREATE VIEW [awdb].[Campaign] as (select * from maxco_awdb.dbo.[Campaign]) ;
CREATE VIEW [awdb].[Department] as (select * from maxco_awdb.dbo.[Department]) ;
CREATE VIEW [awdb].[Department_Member] as (select * from maxco_awdb.dbo.[Department_Member]) ;
CREATE VIEW [awdb].[Enterprise_Skill_Group] as (select * from maxco_awdb.dbo.[Enterprise_Skill_Group]) ;
CREATE VIEW [awdb].[Enterprise_Skill_Group_Member] as (select * from maxco_awdb.dbo.[Enterprise_Skill_Group_Member]) ;
CREATE VIEW [awdb].[Expanded_Call_Variable] as (select * from maxco_awdb.dbo.[Expanded_Call_Variable]) ;
CREATE VIEW [awdb].[Master_Script] as (select * from maxco_awdb.dbo.[Master_Script]) ;
CREATE VIEW [awdb].[Media_Class] as (select * from maxco_awdb.dbo.[Media_Class]) ;
CREATE VIEW [awdb].[Media_Routing_Domain] as (select * from maxco_awdb.dbo.[Media_Routing_Domain]) ;
CREATE VIEW [awdb].[Network_Trunk_Group] as (select * from maxco_awdb.dbo.[Network_Trunk_Group]) ;
CREATE VIEW [awdb].[Network_Vru] as (select * from maxco_awdb.dbo.[Network_Vru]) ;
CREATE VIEW [awdb].[Peripheral] as (select * from maxco_awdb.dbo.[Peripheral]) ;
CREATE VIEW [awdb].[Person] as (select * from maxco_awdb.dbo.[Person]) ;
CREATE VIEW [awdb].[Precision_Queue] as (select * from maxco_awdb.dbo.[Precision_Queue]) ;
CREATE VIEW [awdb].[Precision_Q_Real_Time] as (select * from maxco_awdb.dbo.[Precision_Q_Real_Time]) ;
CREATE VIEW [awdb].[Reason_Code] as (select * from maxco_awdb.dbo.[Reason_Code]) ;
CREATE VIEW [awdb].[Route] as (select * from maxco_awdb.dbo.[Route]) ;
CREATE VIEW [awdb].[Routing_Client] as (select * from maxco_awdb.dbo.[Routing_Client]) ;
CREATE VIEW [awdb].[Route_Real_Time] as (select * from maxco_awdb.dbo.[Route_Real_Time]) ;
CREATE VIEW [awdb].[Service] as (select * from maxco_awdb.dbo.[Service]) ;
CREATE VIEW [awdb].[Service_Member] as (select * from maxco_awdb.dbo.[Service_Member]) ;
CREATE VIEW [awdb].[Skill_Group] as (select * from maxco_awdb.dbo.[Skill_Group]) ;
CREATE VIEW [awdb].[Skill_Group_Member] as (select * from maxco_awdb.dbo.[Skill_Group_Member]) ;
CREATE VIEW [awdb].[Skill_Group_Real_Time] as (select * from maxco_awdb.dbo.[Skill_Group_Real_Time]) ;
CREATE VIEW [awdb].[User_Variable] as (select * from maxco_awdb.dbo.[User_Variable]) ;
