--Update CC_C_UNIT_OF_WORK Records
UPDATE CC_C_UNIT_OF_WORK SET UNIT_OF_WORK_CATEGORY = 'Unknown' WHERE UNIT_OF_WORK_NAME = 'Unknown';
UPDATE CC_C_UNIT_OF_WORK SET UNIT_OF_WORK_CATEGORY = 'IVR' WHERE UNIT_OF_WORK_NAME = 'IVR';
UPDATE CC_C_UNIT_OF_WORK SET UNIT_OF_WORK_CATEGORY = 'N/A' WHERE UNIT_OF_WORK_NAME = 'N/A';
UPDATE CC_C_UNIT_OF_WORK SET UNIT_OF_WORK_CATEGORY = 'INBOUND_CALL'
	WHERE UNIT_OF_WORK_NAME IN ('CHIP FREW ENG','CHIP FREW SPN','CHIP PROVIDER','CHIP SEU ENG','CHIP SEU SPN','CHIP SUPERVISOR','EB FREW ENG','EB FREW SPN','EB MBIC ENG'
		,'EB MBIC SPN','EB NONFREW ENG','EB NONFREW SPN','EB OUTREACH','EB PROVIDER','EB SUPERVISOR','ES EN','ES SEU  EN and ES SLAQ EN','ES SEU  SP and ES SLAQ SP'
		,'ES SEU EN','ES SEU SP','ES SP','STAR Plus NonFrew EN','STAR Plus NonFrew SP','THS FREW ENG','THS FREW SPN','THS OUTREACH','THS SSU ENG','THS SSU SPN');
UPDATE CC_C_UNIT_OF_WORK SET UNIT_OF_WORK_CATEGORY = 'OUTBOUND_CALL'
	WHERE UNIT_OF_WORK_NAME IN ('CHIP_OUTBOUND','CHIP_OUTBOUND_ENRL','CHIP_OUTBOUND_MI','CHIP_OUTBOUND_PMI','CHIP_OUTBOUND_XFR','EBS_OUTBOUND','ES Outbound','THS_OUTBOUND');
UPDATE CC_C_UNIT_OF_WORK SET UNIT_OF_WORK_CATEGORY = 'VOICEMAIL'
	WHERE UNIT_OF_WORK_NAME IN ('CHIP ENG VM','CHIP SPN VM','EB FREW ENG VM','EB FREW SPN VM','THS ENG VM','THS SPN VM');

--Update CC_D_UNIT_OF_WORK Records
UPDATE CC_D_UNIT_OF_WORK SET UNIT_OF_WORK_CATEGORY = 'Unknown' WHERE UNIT_OF_WORK_NAME = 'Unknown';
UPDATE CC_D_UNIT_OF_WORK SET UNIT_OF_WORK_CATEGORY = 'IVR' WHERE UNIT_OF_WORK_NAME = 'IVR';
UPDATE CC_D_UNIT_OF_WORK SET UNIT_OF_WORK_CATEGORY = 'N/A' WHERE UNIT_OF_WORK_NAME = 'N/A';
UPDATE CC_D_UNIT_OF_WORK SET UNIT_OF_WORK_CATEGORY = 'INBOUND_CALL'
	WHERE UNIT_OF_WORK_NAME IN ('CHIP FREW ENG','CHIP FREW SPN','CHIP PROVIDER','CHIP SEU ENG','CHIP SEU SPN','CHIP SUPERVISOR','EB FREW ENG','EB FREW SPN','EB MBIC ENG'
		,'EB MBIC SPN','EB NONFREW ENG','EB NONFREW SPN','EB OUTREACH','EB PROVIDER','EB SUPERVISOR','ES EN','ES SEU  EN and ES SLAQ EN','ES SEU  SP and ES SLAQ SP'
		,'ES SEU EN','ES SEU SP','ES SP','STAR Plus NonFrew EN','STAR Plus NonFrew SP','THS FREW ENG','THS FREW SPN','THS OUTREACH','THS SSU ENG','THS SSU SPN');
UPDATE CC_D_UNIT_OF_WORK SET UNIT_OF_WORK_CATEGORY = 'OUTBOUND_CALL'
	WHERE UNIT_OF_WORK_NAME IN ('CHIP_OUTBOUND','CHIP_OUTBOUND_ENRL','CHIP_OUTBOUND_MI','CHIP_OUTBOUND_PMI','CHIP_OUTBOUND_XFR','EBS_OUTBOUND','ES Outbound','THS_OUTBOUND');
UPDATE CC_D_UNIT_OF_WORK SET UNIT_OF_WORK_CATEGORY = 'VOICEMAIL'
	WHERE UNIT_OF_WORK_NAME IN ('CHIP ENG VM','CHIP SPN VM','EB FREW ENG VM','EB FREW SPN VM','THS ENG VM','THS SPN VM');


INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME) 
	VALUES ('1.5.0','100','100_UPDATE_TX_UNIT_OF_WORK_CATEGORY');

COMMIT;


