alter table CORP_ETL_MFB_BATCH_EVENTS disable constraint CORP_ETL_MFBB_BATCH_GUID;
alter table CORP_ETL_MFB_FORM disable constraint CORP_ETL_MFBF_BATCH_GUID;
alter table CORP_ETL_MFB_ENVELOPE disable constraint CORP_ETL_MFBEN_BATCH_GUID;
alter table CORP_ETL_MFB_DOCUMENT disable constraint CORP_ETL_MFBD_BATCH_GUID;

delete from bpm_instance_attribute where bi_id in(select mfb_bi_id from d_mfb_current where batch_guid in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1));
commit;
delete from bpm_update_event_queue where identifier in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1);
commit;
delete from bpm_update_event_queue_archive where identifier in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1);
commit;
delete from bpm_update_event where bi_id in (select mfb_bi_id from d_mfb_current where batch_guid in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1));
commit;
delete from bpm_logging where bi_id in (select mfb_bi_id from d_mfb_current where batch_guid in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1));
commit;
delete from bpm_instance where bi_id in (select mfb_bi_id from d_mfb_current where batch_guid in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1));
commit;
delete from F_MFB_BY_HOUR where mfb_bi_id in(select mfb_bi_id from d_mfb_current where batch_guid in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1));
commit;
delete from d_mfb_current where batch_guid in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1);
commit;
delete from corp_etl_mfb_batch_events where batch_guid in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1);
commit;
delete from corp_etl_mfb_batch_events_stg where batch_guid in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1);
commit;
delete from corp_etl_mfb_form where batch_guid in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1);
commit;
delete from corp_etl_mfb_form_stg where batch_guid in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1);
commit;
delete from corp_etl_mfb_envelope where batch_guid in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1);
commit;
delete from corp_etl_mfb_envelope_stg where batch_guid in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1);
commit;
delete from corp_etl_mfb_document where batch_guid in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1);
commit;
delete from corp_etl_mfb_document_stg where batch_guid in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1);
commit;
delete from corp_etl_mfb_batch_ars_stg where batch_guid in(select batch_guid from corp_etl_mfb_batch_stg where stg_insert_job_id=1);
commit;
delete from corp_etl_mfb_batch a where a.batch_guid in (select b.batch_guid from corp_etl_mfb_batch_stg b where a.batch_guid=b.batch_guid and b.stg_insert_job_id=1);
commit;
delete from corp_etl_mfb_batch_stg where stg_insert_job_id=1;
commit;

alter table CORP_ETL_MFB_BATCH_EVENTS enable constraint CORP_ETL_MFBB_BATCH_GUID;
alter table CORP_ETL_MFB_FORM enable constraint CORP_ETL_MFBF_BATCH_GUID;
alter table CORP_ETL_MFB_ENVELOPE enable constraint CORP_ETL_MFBEN_BATCH_GUID;
alter table CORP_ETL_MFB_DOCUMENT enable constraint CORP_ETL_MFBD_BATCH_GUID;
