
INSERT INTO D_PROGRAM (D_PROGRAM_ID, PROGRAM_NAME) VALUES (6, 'ES');



INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME) 
	VALUES ('2.5','004','004_INSERT_D_PROGRAM');

COMMIT;