
UPDATE D_METRIC_PROJECT
SET ACTUAL_VALUE_PROVIDED_BY = 'Template'
 , FORECAST_VALUE_PROVIDED_BY = 'Template'
WHERE D_METRIC_PROJECT_ID IN 
  (SELECT D_METRIC_PROJECT_ID
   FROM D_METRIC_PROJECT mp
   INNER JOIN D_PROJECT pj on mp.D_PROJECT_ID = pj.D_PROJECT_ID
   INNER JOIN D_PROGRAM pg on mp.D_PROGRAM_ID = pg.D_PROGRAM_ID
   WHERE pj.PROJECT_NAME NOT IN ('IL EB', 'IL EEV','TX Enrollment Broker','TX Eligibility Support'));

UPDATE D_METRIC_PROJECT
SET ACTUAL_VALUE_PROVIDED_BY = 'MAXDAT'
 , FORECAST_VALUE_PROVIDED_BY = 'MAXDAT'
WHERE D_METRIC_PROJECT_ID IN 
  (SELECT D_METRIC_PROJECT_ID
   FROM D_METRIC_PROJECT mp
   INNER JOIN D_PROJECT pj on mp.D_PROJECT_ID = pj.D_PROJECT_ID
   INNER JOIN D_PROGRAM pg on mp.D_PROGRAM_ID = pg.D_PROGRAM_ID
   WHERE pj.PROJECT_NAME IN ('IL EB', 'IL EEV','TX Enrollment Broker','TX Eligibility Support'));
   
UPDATE D_METRIC_PROJECT
SET ACTUAL_VALUE_PROVIDED_BY = 'MAXDAT'
 , FORECAST_VALUE_PROVIDED_BY = 'Template'
WHERE D_METRIC_PROJECT_ID IN 
  (SELECT D_METRIC_PROJECT_ID
   FROM D_METRIC_PROJECT mp
   INNER JOIN D_PROJECT pj on mp.D_PROJECT_ID = pj.D_PROJECT_ID
   INNER JOIN D_PROGRAM pg on mp.D_PROGRAM_ID = pg.D_PROGRAM_ID
   INNER JOIN D_METRIC_DEFINITION md on mp.D_METRIC_DEFINITION_ID = md.D_METRIC_DEFINITION_ID
   WHERE pj.PROJECT_NAME IN ('IL EB', 'IL EEV')
   AND md.NAME IN ('FTE Count'));
   
   UPDATE D_METRIC_PROJECT
SET ACTUAL_VALUE_PROVIDED_BY = 'Template'
 , FORECAST_VALUE_PROVIDED_BY = 'MAXDAT'
WHERE D_METRIC_PROJECT_ID IN 
  (SELECT D_METRIC_PROJECT_ID
   FROM D_METRIC_PROJECT mp
   INNER JOIN D_PROJECT pj on mp.D_PROJECT_ID = pj.D_PROJECT_ID
   INNER JOIN D_PROGRAM pg on mp.D_PROGRAM_ID = pg.D_PROGRAM_ID
   INNER JOIN D_METRIC_DEFINITION md on mp.D_METRIC_DEFINITION_ID = md.D_METRIC_DEFINITION_ID
   WHERE pj.PROJECT_NAME IN ('IL EB', 'IL EEV')
   AND md.NAME IN ('MAX_HANDLE_TIME'));
   
INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME) 
	VALUES ('2.5','005','005_UPDATE_D_METRIC_PROJECT');

COMMIT;