/* CC_S_ACD_INTERVAL */

-- Data correction to null

update cc_s_acd_interval set MIN_HANDLE_TIME = null
 ,MAX_HANDLE_TIME = null
 ,MEDIAN_HANDLE_TIME = null
 ,STDDEV_HANDLE_TIME = null
 ,MIN_SPEED_TO_HANDLE = null
 ,MAX_SPEED_TO_HANDLE = null
 ,MEDIAN_SPEED_TO_HANDLE = null
 ,STDDEV_SPEED_TO_HANDLE = null
 ,MIN_SPEED_OF_ANSWER = null
 ,MEDIAN_SPEED_OF_ANSWER = null
 ,STDDEV_SPEED_OF_ANSWER = null
 ,LABOR_MINUTES_TOTAL = null
 ,CONTACT_INVENTORY = null
 ,CONTACT_INVENTORY_JEOPARDY = null
 ,CONTACT_INVENTORY_AGE_TOTAL = null
 ,MIN_CONTACT_INVENTORY_AGE = null
 ,MAX_CONTACT_INVENTORY_AGE = null
 ,MEAN_CONTACT_INVENTORY_AGE = null
 ,MEDIAN_CONTACT_INVENTORY_AGE = null
 ,STDDEV_CONTACT_INVENTORY_AGE = null
 ,CALLS_ON_HOLD = null
 ,IVR_TIME_TOTAL = null
 ,CONTACTS_BLOCKED = null
 ,ICR_DEFAULT_ROUTED = null
 ,NETWORK_DEFAULT_ROUTED = null
 ,RETURN_BUSY = null
 ,CALLS_RONA = null
 ,RETURN_RELEASE = null
 ,CALLS_ROUTED_NON_AGENT = null
 ,ERROR_COUNT = null
 ,AGENT_ERROR_COUNT = null
 ,RETURN_RING = null
 ,INCOMPLETE_CALLS = null
 ,MAX_CALLS_QUEUED = null;


commit;



/* CC_S_ACD_QUEUE_INTERVAL */

-- Data correction to null

update cc_s_acd_queue_interval set MIN_HANDLE_TIME = null
 ,MAX_HANDLE_TIME = null
 ,MEDIAN_HANDLE_TIME = null
 ,STDDEV_HANDLE_TIME = null
 ,MIN_SPEED_TO_HANDLE = null
 ,MAX_SPEED_TO_HANDLE = null
 ,MEDIAN_SPEED_TO_HANDLE = null
 ,STDDEV_SPEED_TO_HANDLE = null
 ,MIN_SPEED_OF_ANSWER = null
 ,MEDIAN_SPEED_OF_ANSWER = null
 ,STDDEV_SPEED_OF_ANSWER = null
 ,LABOR_MINUTES_TOTAL = null
 ,CONTACT_INVENTORY = null
 ,CONTACT_INVENTORY_JEOPARDY = null
 ,CONTACT_INVENTORY_AGE_TOTAL = null
 ,MIN_CONTACT_INVENTORY_AGE = null
 ,MAX_CONTACT_INVENTORY_AGE = null
 ,MEAN_CONTACT_INVENTORY_AGE = null
 ,MEDIAN_CONTACT_INVENTORY_AGE = null
 ,STDDEV_CONTACT_INVENTORY_AGE = null
 ,CALLS_ON_HOLD = null
 ,IVR_TIME_TOTAL = null
 ,CONTACTS_BLOCKED = null
 ,ICR_DEFAULT_ROUTED = null
 ,NETWORK_DEFAULT_ROUTED = null
 ,RETURN_BUSY = null
 ,CALLS_RONA = null
 ,RETURN_RELEASE = null
 ,CALLS_ROUTED_NON_AGENT = null
 ,ERROR_COUNT = null
 ,AGENT_ERROR_COUNT = null
 ,RETURN_RING = null
 ,INCOMPLETE_CALLS = null
 ,MAX_CALLS_QUEUED = null;
 
commit;

/* CC_S_ACD_AGENT_ACTIVITY */

update CC_S_ACD_AGENT_ACTIVITY set 
PREDICTIVE_CALLS_COUNT = null
, PREDICTIVE_TALK_SECONDS = null
, PREVIEW_CALLS_COUNT = null
, PREVIEW_TALK_SECONDS = null;

commit;

/* CC_S_AGENT_WORK_DAY */

-- Data correction to null

update CC_S_AGENT_WORK_DAY set SCHEDULED_SHIFT_MINUTES = null, ACTUAL_OVERTIME_MINUTES = null;


commit;


--- FACTS ---

/* CC_F_ACTUALS_QUEUE_INTERVAL */

-- Data correction to null

update CC_F_ACTUALS_QUEUE_INTERVAL set MIN_HANDLE_TIME = null
 ,MAX_HANDLE_TIME = null
 ,MEDIAN_HANDLE_TIME = null
 ,STDDEV_HANDLE_TIME = null
 ,MIN_SPEED_TO_HANDLE = null
 ,MAX_SPEED_TO_HANDLE = null
 ,MEDIAN_SPEED_TO_HANDLE = null
 ,STDDEV_SPEED_TO_HANDLE = null
 ,MIN_SPEED_OF_ANSWER = null
 ,MEDIAN_SPEED_OF_ANSWER = null
 ,STDDEV_SPEED_OF_ANSWER = null
 ,LABOR_MINUTES_TOTAL = null
 ,CONTACT_INVENTORY = null
 ,CONTACT_INVENTORY_JEOPARDY = null
 ,MIN_CONTACT_INVENTORY_AGE = null
 ,MAX_CONTACT_INVENTORY_AGE = null
 ,MEAN_CONTACT_INVENTORY_AGE = null
 ,MEDIAN_CONTACT_INVENTORY_AGE = null
 ,STDDEV_CONTACT_INVENTORY_AGE = null
 ,CALLS_ON_HOLD = null
 ,CONTACTS_BLOCKED = null
 ,ICR_DEFAULT_ROUTED = null
 ,NETWORK_DEFAULT_ROUTED = null
 ,RETURN_BUSY = null
 ,CALLS_RONA = null
 ,RETURN_RELEASE = null
 ,CALLS_ROUTED_NON_AGENT = null
 ,ERROR_COUNT = null
 ,AGENT_ERROR_COUNT = null
 ,RETURN_RING = null
 ,INCOMPLETE_CALLS = null
 ,MAX_CALLS_QUEUED = null
, LABOR_MINUTES_AVAILABLE = null
, HEADCOUNT_TOTAL = null
, HEADCOUNT_UNAVAILABLE = null;

commit;

/* CC_F_ACD_QUEUE_INTERVAL */

-- Data correction to null

update CC_F_ACD_QUEUE_INTERVAL set MIN_HANDLE_TIME = null
 ,MAX_HANDLE_TIME = null
 ,MEDIAN_HANDLE_TIME = null
 ,STDDEV_HANDLE_TIME = null
 ,MIN_SPEED_TO_HANDLE = null
 ,MAX_SPEED_TO_HANDLE = null
 ,MEDIAN_SPEED_TO_HANDLE = null
 ,STDDEV_SPEED_TO_HANDLE = null
 ,MIN_SPEED_OF_ANSWER = null
 ,MEDIAN_SPEED_OF_ANSWER = null
 ,STDDEV_SPEED_OF_ANSWER = null
 ,LABOR_MINUTES_TOTAL = null
 ,CONTACT_INVENTORY = null
 ,CONTACT_INVENTORY_JEOPARDY = null
 ,MIN_CONTACT_INVENTORY_AGE = null
 ,MAX_CONTACT_INVENTORY_AGE = null
 ,MEAN_CONTACT_INVENTORY_AGE = null
 ,MEDIAN_CONTACT_INVENTORY_AGE = null
 ,STDDEV_CONTACT_INVENTORY_AGE = null
 ,CALLS_ON_HOLD = null
 ,CONTACTS_BLOCKED = null
 ,ICR_DEFAULT_ROUTED = null
 ,NETWORK_DEFAULT_ROUTED = null
 ,RETURN_BUSY = null
 ,CALLS_RONA = null
 ,RETURN_RELEASE = null
 ,CALLS_ROUTED_NON_AGENT = null
 ,ERROR_COUNT = null
 ,AGENT_ERROR_COUNT = null
 ,RETURN_RING = null
 ,INCOMPLETE_CALLS = null
 ,MAX_CALLS_QUEUED = null
, LABOR_MINUTES_AVAILABLE = null
, HEADCOUNT_TOTAL = null
, HEADCOUNT_UNAVAILABLE = null;

commit;


/* CC_F_AGENT_BY_DATE */

-- Data correction to null

update CC_F_AGENT_BY_DATE set 
SCHEDULED_SHIFT_MINUTES = null 
, ACTUAL_OVERTIME_MINUTES = null
, PREDICTIVE_CALLS_COUNT = null
, PREDICTIVE_TALK_SECONDS = null
, PREVIEW_CALLS_COUNT = null
, PREVIEW_TALK_SECONDS = null;


commit;