
INSERT INTO CC_S_ACD_INTERVAL_PERIOD ( 
	ACD_INTERVAL_PERIOD_ID, 
	PERIOD_TYPE, 
	PERIOD_1_UPPER_BOUND , 
	PERIOD_2_UPPER_BOUND , 
	PERIOD_3_UPPER_BOUND , 
	PERIOD_4_UPPER_BOUND , 
	PERIOD_5_UPPER_BOUND , 
	PERIOD_6_UPPER_BOUND , 
	PERIOD_7_UPPER_BOUND , 
	PERIOD_8_UPPER_BOUND , 
	PERIOD_9_UPPER_BOUND , 
	PERIOD_10_UPPER_BOUND , 
	EXTRACT_DT, 
	RECORD_EFF_DT, 
	RECORD_END_DT
) VALUES (
	2, 
	'CALLS_ABANDONED', 
	10, 
	20, 
	30, 
	40, 
	45, 
	50, 
	55, 
	60, 
	70, 
	0, 
	SYSDATE, 
	to_date('01-JAN-1900', 'DD-MON-YYYY'),
	to_date('31-DEC-2999', 'DD-MON-YYYY')
);


UPDATE cc_s_contact_queue
SET avg_speed_ansr_intrvl_priod_id = 1,
calls_abandond_intrvl_priod_id = 2
WHERE contact_queue_id != 0;


INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME)
VALUES ('0.1.1','013','013_INSERT_CALLS_ABANDONED_PERIOD');

COMMIT;