Insert into CORP_CMOR_TRGT_ATTND_SUB_LKUP (VALUE,DESCRIPTION) values ('FST','Foster Care');
Insert into CORP_CMOR_TRGT_ATTND_SUB_LKUP (VALUE,DESCRIPTION) values ('STAGT','State Agency');
Insert into CORP_CMOR_TRGT_ATTND_SUB_LKUP (VALUE,DESCRIPTION) values ('CBO','CBO');
Insert into CORP_CMOR_TRGT_ATTND_SUB_LKUP (VALUE,DESCRIPTION) values ('FBO','FBO');
Insert into CORP_CMOR_TRGT_ATTND_SUB_LKUP (VALUE,DESCRIPTION) values ('ISD','ISD/Schools');
Insert into CORP_CMOR_TRGT_ATTND_SUB_LKUP (VALUE,DESCRIPTION) values ('CBOS','CBO');
Insert into CORP_CMOR_TRGT_ATTND_SUB_LKUP (VALUE,DESCRIPTION) values ('HSGRNT','Head Start');
commit;