CREATE SEQUENCE SEQ_PP_DAD_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE PP_D_ACTUAL_DETAILS 
    ( 
     DAD_ID NUMBER  NOT NULL , 
     D_DATE DATE  NOT NULL , 
     D_HOUR NUMBER  NOT NULL , 
     USR_ID NUMBER  NOT NULL , 
     SOURCE_DETAIL_ID NUMBER NOT NULL,
     BUCKET_START_DATE DATE NOT NULL,
     BUCKET_END_DATE DATE NOT NULL,
     JEOPARDY_FLAG VARCHAR2(1) DEFAULT 'N', 
     ACTUAL_ARRIVAL NUMBER , 
     ACTUAL_COMPLETION NUMBER , 
     ACTUAL_INVENTORY NUMBER , 
     ACTUAL_INVENTORY_AGE NUMBER , 
     ACTUAL_HANDLE_TIME NUMBER , 
     ACTUAL_STAFF_HOURS NUMBER) 
tablespace MAXDAT_DATA;

ALTER TABLE PP_D_ACTUAL_DETAILS 
    ADD CONSTRAINT PP_D_ACTUAL_DETAILS_PK PRIMARY KEY ( DAD_ID ) using index tablespace MAXDAT_INDX;

grant select on PP_D_ACTUAL_DETAILS to MAXDAT_READ_ONLY;


CREATE TABLE PP_D_COUNTRY 
    ( 
     COUNTRY_ID NUMBER  NOT NULL , 
     COUNTRY_NAME VARCHAR2(50)) 
tablespace MAXDAT_DATA;

ALTER TABLE PP_D_COUNTRY 
    ADD CONSTRAINT PP_D_COUNTRY_PK PRIMARY KEY ( COUNTRY_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_COUNTRY 
    ADD CONSTRAINT PP_D_COUNTRY_NAME_UN UNIQUE ( COUNTRY_NAME ) using index tablespace MAXDAT_INDX;

grant select on PP_D_COUNTRY to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_COUNTRY_SV AS
SELECT COUNTRY_ID,
     COUNTRY_NAME 
	 FROM PP_D_COUNTRY
WITH READ ONLY; 

grant select on PP_D_COUNTRY_SV to MAXDAT_READ_ONLY;

CREATE TABLE PP_D_DATES 
    ( 
     D_DATE DATE  NOT NULL , 
     D_MONTH VARCHAR2(3)  NOT NULL , 
     D_MONTH_NAME VARCHAR2(9)  NOT NULL , 
     D_DAY VARCHAR2(3)  NOT NULL , 
     D_DAY_NAME VARCHAR2(9)  NOT NULL , 
     D_DAY_OF_WEEK VARCHAR2(1)  NOT NULL , 
     D_DAY_OF_MONTH VARCHAR2(2)  NOT NULL , 
     D_DAY_OF_YEAR VARCHAR2(3)  NOT NULL , 
     D_YEAR VARCHAR2(4)  NOT NULL , 
     D_MONTH_NUM VARCHAR2(2)  NOT NULL , 
     D_WEEK_OF_YEAR VARCHAR2(2)  NOT NULL , 
     D_WEEK_OF_MONTH VARCHAR2(1)  NOT NULL , 
     WEEKEND_FLAG VARCHAR2(1)  NOT NULL) 
tablespace MAXDAT_DATA;

CREATE INDEX PP_D_DATES_MONTH_NAME_IX ON PP_D_DATES 
    ( 
     D_MONTH_NAME ASC 
    ) tablespace MAXDAT_INDX;
CREATE INDEX PP_D_DATES_D_WEEK_OF_MONTH_IX ON PP_D_DATES 
    ( 
     D_WEEK_OF_MONTH ASC 
    ) tablespace MAXDAT_INDX;
CREATE UNIQUE INDEX PP_D_DATES_PK ON PP_D_DATES 
    ( 
     D_DATE ASC 
    ) tablespace MAXDAT_INDX;
ALTER TABLE PP_D_DATES 
    ADD CONSTRAINT PP_D_DATES_PK PRIMARY KEY ( D_DATE ) using index tablespace MAXDAT_INDX;

grant select on PP_D_DATES to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_DATES_SV
AS
  SELECT D_DATE,
    D_MONTH,
    D_MONTH_NAME,
    D_DAY,
    D_DAY_NAME,
    D_DAY_OF_WEEK,
    D_DAY_OF_MONTH,
    D_DAY_OF_YEAR,
    D_YEAR,
    D_MONTH_NUM,
    D_WEEK_OF_YEAR,
    D_WEEK_OF_MONTH,
    WEEKEND_FLAG,
    TRUNC(D_DATE) as TRUNC_D_DATE
  FROM PP_D_DATES
WITH read only;

grant select on PP_D_DATES_SV to MAXDAT_READ_ONLY;


create or replace view PP_D_ACTUAL_DETAILS_SV as
select
  DAD_ID,
  PPDD.D_DATE,
  D_HOUR,
  USR_ID,
  SOURCE_DETAIL_ID, 
  case 
    when DENSE_RANK() over (partition by SOURCE_DETAIL_ID order by SOURCE_DETAIL_ID asc, PPDD.D_DATE asc) = 1 then 1
    else 0
    end ACTUAL_ARRIVAL,
  ACTUAL_COMPLETION,
  ACTUAL_INVENTORY,
  ACTUAL_INVENTORY_AGE,
  ACTUAL_HANDLE_TIME,
  ACTUAL_STAFF_HOURS,
  JEOPARDY_FLAG
from 
  (SELECT D_DATE FROM PP_D_DATES WHERE D_DATE <= TRUNC(SYSDATE)) PPDD,
  PP_D_ACTUAL_DETAILS DAD
where
  PPDD.D_DATE >= DAD.BUCKET_START_DATE 
  and PPDD.D_DATE < DAD.BUCKET_END_DATE
union all
select
  DAD_ID,
  PPDD.D_DATE,
  D_HOUR,
  USR_ID,
  SOURCE_DETAIL_ID, 
  ACTUAL_ARRIVAL,
  ACTUAL_COMPLETION,
  ACTUAL_INVENTORY,
  ACTUAL_INVENTORY_AGE,
  ACTUAL_HANDLE_TIME,
  ACTUAL_STAFF_HOURS,
  JEOPARDY_FLAG
from 
  PP_D_DATES PPDD,
  PP_D_ACTUAL_DETAILS DAD
where
  PPDD.D_DATE = DAD.BUCKET_START_DATE 
  and PPDD.D_DATE = DAD.BUCKET_END_DATE
with read only;

grant select on PP_D_ACTUAL_DETAILS_SV to MAXDAT_READ_ONLY;


CREATE TABLE PP_D_DISTRICT 
    ( 
     DISTRICT_ID NUMBER  NOT NULL , 
     DISTRICT_NAME VARCHAR2(50))
tablespace MAXDAT_DATA;

ALTER TABLE PP_D_DISTRICT 
    ADD CONSTRAINT PP_D_DISTRICT_PK PRIMARY KEY ( DISTRICT_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_DISTRICT 
    ADD CONSTRAINT PP_D_DISTRICT_NAME_UN UNIQUE ( DISTRICT_NAME ) using index tablespace MAXDAT_INDX;

grant select on PP_D_DISTRICT to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_DISTRICT_SV AS
SELECT DISTRICT_ID, 
     DISTRICT_NAME 
	 FROM PP_D_DISTRICT
WITH READ ONLY; 

grant select on PP_D_DISTRICT_SV to MAXDAT_READ_ONLY;

CREATE TABLE PP_D_GEOGRAPHY_MASTER 
    ( 
     GEOGRAPHY_MASTER_ID NUMBER  NOT NULL , 
     GEOGRAPHY_NAME VARCHAR2(250)  NOT NULL , 
     COUNTRY_ID NUMBER  NOT NULL , 
     STATE_ID NUMBER  NOT NULL , 
     PROVINCE_ID NUMBER  NOT NULL , 
     DISTRICT_ID NUMBER  NOT NULL , 
     REGION_ID NUMBER  NOT NULL , 
     SITE_ID NUMBER  NOT NULL) 
tablespace MAXDAT_DATA;

ALTER TABLE PP_D_GEOGRAPHY_MASTER 
    ADD CONSTRAINT PP_D_GEOGRAPHY_MASTER_PK PRIMARY KEY ( GEOGRAPHY_MASTER_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_GEOGRAPHY_MASTER 
    ADD CONSTRAINT PP_D_GEOGRAPHY_LKUP_NAME_UN UNIQUE ( GEOGRAPHY_NAME ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_GEOGRAPHY_MASTER 
    ADD CONSTRAINT PP_D_GEOGRAPHY_MASTER__UN UNIQUE ( COUNTRY_ID , STATE_ID , PROVINCE_ID , DISTRICT_ID , REGION_ID , SITE_ID ) using index tablespace MAXDAT_INDX;

grant select on PP_D_GEOGRAPHY_MASTER to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_GEOGRAPHY_MASTER_SV AS
SELECT GEOGRAPHY_MASTER_ID, 
     GEOGRAPHY_NAME, 
     COUNTRY_ID, 
     STATE_ID, 
     PROVINCE_ID, 
     DISTRICT_ID, 
     REGION_ID, 
     SITE_ID 
	 FROM PP_D_GEOGRAPHY_MASTER
WITH READ ONLY; 

grant select on PP_D_GEOGRAPHY_MASTER_SV to MAXDAT_READ_ONLY;

CREATE TABLE PP_D_HOURS 
    ( 
     D_HOUR NUMBER  NOT NULL , 
     HOUR12 NUMBER  NOT NULL , 
     AM_PM VARCHAR2(2)  NOT NULL , 
     TIME_OF_DAY12 VARCHAR2(9)  NOT NULL , 
     TIME_OF_DAY24 VARCHAR2(9)  NOT NULL) 
tablespace MAXDAT_DATA;

ALTER TABLE PP_D_HOURS 
    ADD CONSTRAINT D_HOURS_PK PRIMARY KEY ( D_HOUR ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_HOURS 
    ADD CONSTRAINT PP_D_HOURS_UN UNIQUE ( HOUR12 , AM_PM ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_HOURS 
    ADD CONSTRAINT PP_D_HOURS_UN1 UNIQUE ( TIME_OF_DAY12 ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_HOURS 
    ADD CONSTRAINT PP_D_HOURS_UN2 UNIQUE ( TIME_OF_DAY24 ) using index tablespace MAXDAT_INDX;

grant select on PP_D_HOURS to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_HOURS_SV AS
SELECT D_HOUR, 
     HOUR12, 
     AM_PM, 
     TIME_OF_DAY12, 
     TIME_OF_DAY24 
	 FROM PP_D_HOURS
WITH READ ONLY; 

grant select on PP_D_HOURS_SV to MAXDAT_READ_ONLY;

CREATE SEQUENCE SEQ_PP_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE PP_D_PRODUCTION_PLAN 
    ( 
     PP_ID NUMBER  NOT NULL , 
     PRODUCTION_PLAN_NAME VARCHAR2(50)  NOT NULL , 
     PRODUCTION_PLAN_DESCRIPTION VARCHAR2(1000)  NOT NULL , 
     PROJECT_ID NUMBER  NOT NULL , 
     PROGRAM_ID NUMBER  NOT NULL , 
     GEOGRAPHY_MASTER_ID NUMBER  NOT NULL , 
     EFFECTIVE_DATE DATE  NOT NULL , 
     END_DATE DATE , 
     PP_CREATE_DATE DATE DEFAULT sysdate  NOT NULL , 
     PP_LAST_UPDATE_DATE DATE DEFAULT sysdate  NOT NULL 
    ) tablespace MAXDAT_DATA;

ALTER TABLE PP_D_PRODUCTION_PLAN 
    ADD CONSTRAINT D_PRODUCTION_PLAN_PK PRIMARY KEY ( PP_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_PRODUCTION_PLAN 
    ADD CONSTRAINT D_PRODUCTION_PLAN__UN UNIQUE ( PRODUCTION_PLAN_NAME , EFFECTIVE_DATE , PROJECT_ID , PROGRAM_ID , GEOGRAPHY_MASTER_ID )  using index tablespace MAXDAT_INDX;

grant select on PP_D_PRODUCTION_PLAN to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_PRODUCTION_PLAN_SV AS
SELECT PP_ID, 
     PRODUCTION_PLAN_NAME, 
     PRODUCTION_PLAN_DESCRIPTION, 
     PROJECT_ID, 
     PROGRAM_ID, 
     GEOGRAPHY_MASTER_ID, 
     EFFECTIVE_DATE, 
     END_DATE, 
     PP_CREATE_DATE, 
     PP_LAST_UPDATE_DATE 
	 FROM PP_D_PRODUCTION_PLAN
WITH READ ONLY; 

grant select on PP_D_PRODUCTION_PLAN_SV to MAXDAT_READ_ONLY;

CREATE SEQUENCE SEQ_PP_PPH_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE PP_D_PRODUCTION_PLAN_HORIZON 
    ( 
     PPH_ID NUMBER  NOT NULL , 
     PP_ID NUMBER  NOT NULL , 
     HORIZON_START_DATE DATE  NOT NULL , 
     HORIZON_START_HOUR NUMBER DEFAULT 0  NOT NULL , 
     HORIZON_END_DATE DATE  NOT NULL , 
     HORIZON_END_HOUR NUMBER DEFAULT 0  NOT NULL , 
     HORIZON_NAME VARCHAR2(50)  NOT NULL , 
     HORIZON_DESCRIPTION VARCHAR2(1000) , 
     FORECAST_LAST_MODIFIED_DATE DATE DEFAULT sysdate  NOT NULL , 
     CREATE_DATE DATE DEFAULT sysdate  NOT NULL , 
     LAST_UPDATE_DATE DATE DEFAULT sysdate  NOT NULL 
    ) tablespace MAXDAT_DATA;

ALTER TABLE PP_D_PRODUCTION_PLAN_HORIZON 
    ADD CONSTRAINT D_PRODUCTION_PLAN_HRZN_PK PRIMARY KEY ( PPH_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_PRODUCTION_PLAN_HORIZON 
    ADD CONSTRAINT D_PRODUCTION_PLAN_HRZN_UN UNIQUE ( PP_ID , HORIZON_START_DATE , HORIZON_START_HOUR ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_PRODUCTION_PLAN_HORIZON 
    ADD CONSTRAINT D_PRODUCTION_PLAN_HRZN_UN1 UNIQUE ( PP_ID , HORIZON_END_DATE , HORIZON_END_HOUR ) using index tablespace MAXDAT_INDX;

grant select on PP_D_PRODUCTION_PLAN_HORIZON to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_PROD_PLAN_HORIZON_SV AS
SELECT PPH_ID, 
     PP_ID, 
     HORIZON_START_DATE, 
     HORIZON_START_HOUR, 
     HORIZON_END_DATE, 
     HORIZON_END_HOUR, 
     HORIZON_NAME, 
     HORIZON_DESCRIPTION, 
     FORECAST_LAST_MODIFIED_DATE, 
     CREATE_DATE, 
     LAST_UPDATE_DATE 
	 FROM PP_D_PRODUCTION_PLAN_HORIZON
WITH READ ONLY; 

grant select on PP_D_PROD_PLAN_HORIZON_SV to MAXDAT_READ_ONLY;

CREATE TABLE PP_D_PROGRAM 
    ( 
     PROGRAM_ID NUMBER  NOT NULL , 
     PROGRAM_NAME VARCHAR2(35)  NOT NULL 
    ) tablespace MAXDAT_DATA;
	
ALTER TABLE PP_D_PROGRAM 
    ADD CONSTRAINT PP_D_PROGRAM_PK PRIMARY KEY ( PROGRAM_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_PROGRAM 
    ADD CONSTRAINT PP_D_PROGRAM_UNK UNIQUE ( PROGRAM_NAME ) using index tablespace MAXDAT_INDX;

grant select on PP_D_PROGRAM to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_PROGRAM_SV AS
SELECT PROGRAM_ID, 
     PROGRAM_NAME 
	 FROM PP_D_PROGRAM
WITH READ ONLY; 	

grant select on PP_D_PROGRAM_SV to MAXDAT_READ_ONLY;
	
CREATE TABLE PP_D_PROVINCE 
    ( 
     PROVINCE_ID NUMBER  NOT NULL , 
     PROVINCE_NAME VARCHAR2(50) 
    ) tablespace MAXDAT_DATA;

ALTER TABLE PP_D_PROVINCE 
    ADD CONSTRAINT PP_D_PROVINCE_PK PRIMARY KEY ( PROVINCE_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_PROVINCE 
    ADD CONSTRAINT PP_D_PROVINCE_NAME_UK UNIQUE ( PROVINCE_NAME ) using index tablespace MAXDAT_INDX;

grant select on PP_D_PROVINCE to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_PROVINCE_SV AS
SELECT PROVINCE_ID, 
     PROVINCE_NAME 
	 FROM PP_D_PROVINCE
WITH READ ONLY; 

grant select on PP_D_PROVINCE_SV to MAXDAT_READ_ONLY;

CREATE TABLE PP_D_REGION 
    ( 
     REGION_ID NUMBER  NOT NULL , 
     REGION_NAME VARCHAR2(50) 
    ) tablespace MAXDAT_DATA;
	
COMMENT ON TABLE PP_D_REGION IS 'List of Regions in MAXIMUS';
ALTER TABLE PP_D_REGION 
    ADD CONSTRAINT PP_D_REGION_PK PRIMARY KEY ( REGION_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_REGION 
    ADD CONSTRAINT PP_D_REGION_UNK UNIQUE ( REGION_NAME ) using index tablespace MAXDAT_INDX;

grant select on PP_D_REGION to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_REGION_SV AS
SELECT REGION_ID, 
     REGION_NAME 
	 FROM PP_D_REGION
WITH READ ONLY; 

grant select on PP_D_REGION_SV to MAXDAT_READ_ONLY;

CREATE TABLE PP_D_SEGMENT 
    ( 
     SEGMENT_ID NUMBER  NOT NULL , 
     SEGMENT_NAME VARCHAR2(35)  NOT NULL 
    ) tablespace MAXDAT_DATA;

ALTER TABLE PP_D_SEGMENT 
    ADD CONSTRAINT PK_D_SEGMENT_LKUP PRIMARY KEY ( SEGMENT_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_SEGMENT 
    ADD CONSTRAINT D_SEGMENT_UNK UNIQUE ( SEGMENT_NAME ) using index tablespace MAXDAT_INDX;

grant select on PP_D_SEGMENT to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_SEGMENT_SV AS
SELECT SEGMENT_ID, 
     SEGMENT_NAME 
	 FROM PP_D_SEGMENT
WITH READ ONLY; 

grant select on PP_D_SEGMENT_SV to MAXDAT_READ_ONLY;

CREATE TABLE PP_D_SITE 
    ( 
     SITE_ID NUMBER  NOT NULL , 
     SITE_NAME VARCHAR2(250) 
    ) tablespace MAXDAT_DATA;

ALTER TABLE PP_D_SITE 
    ADD CONSTRAINT PP_D_SITE_PK PRIMARY KEY ( SITE_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_SITE 
    ADD CONSTRAINT PP_D_SITE_SITE_NAME_UN UNIQUE ( SITE_NAME ) using index tablespace MAXDAT_INDX;

grant select on PP_D_SITE to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_SITE_SV AS
SELECT SITE_ID, 
     SITE_NAME 
	 FROM PP_D_SITE
WITH READ ONLY; 

grant select on PP_D_SITE_SV to MAXDAT_READ_ONLY;

CREATE SEQUENCE SEQ_PP_SOURCE_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE PP_D_SOURCE 
    ( 
     SOURCE_ID NUMBER  NOT NULL , 
     SOURCE_NAME VARCHAR2(35)  NOT NULL , 
     SOURCE_DESCRIPTION VARCHAR2(250)  NOT NULL 
    ) tablespace MAXDAT_DATA;

ALTER TABLE PP_D_SOURCE 
    ADD CONSTRAINT PP_D_SOURCE_PK PRIMARY KEY ( SOURCE_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_SOURCE 
    ADD CONSTRAINT PP_D_SOURCE__UN UNIQUE ( SOURCE_NAME ) using index tablespace MAXDAT_INDX;

grant select on PP_D_SOURCE to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_SOURCE_SV AS
SELECT SOURCE_ID, 
     SOURCE_NAME, 
     SOURCE_DESCRIPTION 
	 FROM PP_D_SOURCE
WITH READ ONLY; 

grant select on PP_D_SOURCE_SV to MAXDAT_READ_ONLY;

CREATE SEQUENCE SEQ_PP_SOURCE_REF_TYPE_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE PP_D_SOURCE_REF_TYPE 
    ( 
     SOURCE_REF_TYPE_ID NUMBER  NOT NULL , 
     SOURCE_REF_TYPE_NAME VARCHAR2(35)  NOT NULL , 
     SOURCE_ID NUMBER  NOT NULL 
    ) tablespace MAXDAT_DATA;

ALTER TABLE PP_D_SOURCE_REF_TYPE 
    ADD CONSTRAINT PP_D_SOURCE_REF_TYPE_PK PRIMARY KEY ( SOURCE_REF_TYPE_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_SOURCE_REF_TYPE 
    ADD CONSTRAINT PP_D_SOURCE_REF_TYPE_UN UNIQUE ( SOURCE_REF_TYPE_NAME , SOURCE_ID ) using index tablespace MAXDAT_INDX;

grant select on PP_D_SOURCE_REF_TYPE to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_SOURCE_REF_TYPE_SV AS
SELECT SOURCE_REF_TYPE_ID, 
     SOURCE_REF_TYPE_NAME, 
     SOURCE_ID 
	 FROM PP_D_SOURCE_REF_TYPE
WITH READ ONLY; 

grant select on PP_D_SOURCE_REF_TYPE_SV to MAXDAT_READ_ONLY;

CREATE TABLE PP_D_STATE 
    ( 
     STATE_ID NUMBER  NOT NULL , 
     STATE_NAME VARCHAR2(50) 
    ) tablespace MAXDAT_DATA;
	
ALTER TABLE PP_D_STATE 
    ADD CONSTRAINT PP_D_STATE_PK PRIMARY KEY ( STATE_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_STATE 
    ADD CONSTRAINT PP_D_STATE__UN UNIQUE ( STATE_NAME ) using index tablespace MAXDAT_INDX;

grant select on PP_D_STATE to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_STATE_SV AS
SELECT STATE_ID, 
     STATE_NAME 
	 FROM PP_D_STATE
WITH READ ONLY; 

grant select on PP_D_STATE_SV to MAXDAT_READ_ONLY;

CREATE SEQUENCE SEQ_PP_UOW_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE PP_D_UNIT_OF_WORK 
    ( 
     UOW_ID NUMBER  NOT NULL , 
     UNIT_OF_WORK_NAME VARCHAR2(50)  NOT NULL , 
     HANDLE_TIME_UNIT VARCHAR2(9) CHECK ( HANDLE_TIME_UNIT IN ('Days', 'Hours', 'Minutes', 'Seconds')) ,
     JEOPARDY_INV_AGE NUMBER NOT NULL ,
	 LABEL VARCHAR2(50) NOT NULL
    ) tablespace MAXDAT_DATA;

ALTER TABLE PP_D_UNIT_OF_WORK 
    ADD CONSTRAINT PP_D_UNIT_OF_WORK_PK PRIMARY KEY ( UOW_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_UNIT_OF_WORK 
    ADD CONSTRAINT PP_D_UNIT_OF_WORK_UK1 UNIQUE ( UNIT_OF_WORK_NAME ) using index tablespace MAXDAT_INDX;

grant select on PP_D_UNIT_OF_WORK to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_UNIT_OF_WORK_SV AS
SELECT UOW_ID, 
     UNIT_OF_WORK_NAME, 
     HANDLE_TIME_UNIT, 
     JEOPARDY_INV_AGE,
     LABEL	 
	 FROM PP_D_UNIT_OF_WORK
WITH READ ONLY; 

grant select on PP_D_UNIT_OF_WORK_SV to MAXDAT_READ_ONLY;


CREATE SEQUENCE SEQ_PP_USR_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE PP_D_UOW_SOURCE_REF 
    ( 
     USR_ID NUMBER  NOT NULL , 
     UOW_ID NUMBER  NOT NULL , 
     SOURCE_REF_TYPE_ID NUMBER  NOT NULL , 
     SOURCE_REF_VALUE VARCHAR2(250)  NOT NULL , 
     SOURCE_REF_DETAIL_IDENTIFIER VARCHAR2(50)  NOT NULL , 
     EFFECTIVE_DATE DATE  NOT NULL , 
     END_DATE DATE 
    ) tablespace MAXDAT_DATA;

ALTER TABLE PP_D_UOW_SOURCE_REF 
    ADD CONSTRAINT PP_D_UOW_SOURCE_REF_PK PRIMARY KEY ( USR_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_UOW_SOURCE_REF 
    ADD CONSTRAINT PP_D_UOW_SOURCE_REF_UN UNIQUE ( UOW_ID , SOURCE_REF_TYPE_ID , SOURCE_REF_VALUE , EFFECTIVE_DATE ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_UOW_SOURCE_REF 
    ADD CONSTRAINT PP_D_UOW_SOURCE_REF_UN1 UNIQUE ( UOW_ID , SOURCE_REF_TYPE_ID , SOURCE_REF_VALUE , END_DATE ) using index tablespace MAXDAT_INDX;

grant select on PP_D_UOW_SOURCE_REF to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_D_UOW_SOURCE_REF_SV AS
SELECT USR_ID, 
     UOW_ID, 
     SOURCE_REF_TYPE_ID, 
     SOURCE_REF_VALUE, 
     SOURCE_REF_DETAIL_IDENTIFIER, 
     EFFECTIVE_DATE, 
     END_DATE
	 FROM PP_D_UOW_SOURCE_REF
WITH READ ONLY;

grant select on PP_D_UOW_SOURCE_REF_SV to MAXDAT_READ_ONLY;

CREATE SEQUENCE SEQ_PP_PPN_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE PP_FORECAST_NOTES 
    ( 
     PPN_ID NUMBER  NOT NULL , 
     PP_ID NUMBER  NOT NULL , 
     PPH_ID NUMBER  NOT NULL , 
     NOTE_TYPE VARCHAR2(35)  NOT NULL , 
     NOTE_TEXT VARCHAR2(4000)  NOT NULL , 
     CREATE_DATE DATE  NOT NULL , 
     CREATE_BY VARCHAR2(100)  NOT NULL , 
     LAST_UPDATE_DATE DATE  NOT NULL , 
     LAST_UPDATE_BY VARCHAR2(100)  NOT NULL 
    ) tablespace MAXDAT_DATA;

ALTER TABLE PP_FORECAST_NOTES 
    ADD CONSTRAINT PP_FORECAST_NOTES_PK PRIMARY KEY ( PPN_ID ) using index tablespace MAXDAT_INDX;

grant select on PP_FORECAST_NOTES to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_FORECAST_NOTES_SV AS
SELECT PPN_ID, 
     PP_ID, 
     PPH_ID, 
     NOTE_TYPE, 
     NOTE_TEXT, 
     CREATE_DATE, 
     CREATE_BY, 
     LAST_UPDATE_DATE, 
     LAST_UPDATE_BY
	 FROM PP_FORECAST_NOTES
WITH READ ONLY;

grant select on PP_FORECAST_NOTES_SV to MAXDAT_READ_ONLY;
	
CREATE SEQUENCE SEQ_PP_F_ACTUALS_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;	
	
CREATE TABLE PP_F_ACTUALS 
    ( 
     ACTUALS_ID NUMBER  NOT NULL , 
     D_DATE DATE  NOT NULL , 
     D_HOUR NUMBER  NOT NULL , 
     UOW_ID NUMBER  NOT NULL , 
     PROJECT_ID NUMBER  NOT NULL , 
     PROGRAM_ID NUMBER  NOT NULL , 
     GEOGRAPHY_MASTER_ID NUMBER  NOT NULL , 
     ACTL_ARRIVAL NUMBER , 
     ACTL_COMPLETION NUMBER , 
     ACTL_INVENTORY NUMBER , 
     ACTL_INVENTORY_AGE_AVG NUMBER , 
     ACTL_INVENTORY_AGE_MIN NUMBER , 
     ACTL_INVENTORY_AGE_MAX NUMBER , 
     ACTL_INVENTORY_AGE_MEAN NUMBER , 
     ACTL_INVENTORY_AGE_MEDIAN NUMBER , 
     ACTL_INVENTORY_AGE_SD NUMBER , 
     ACTL_INVENTORY_JEOPARDY NUMBER , 
     ACTL_HANDLE_TIME_AVG NUMBER , 
     ACTL_HANDLE_TIME_MIN NUMBER , 
     ACTL_HANDLE_TIME_MAX NUMBER , 
     ACTL_HANDLE_TIME_MEAN NUMBER , 
     ACTL_HANDLE_TIME_MEDIAN NUMBER , 
     ACTL_HANDLE_TIME_SD NUMBER , 
     ACTL_STAFF_HOURS NUMBER 
    ) tablespace MAXDAT_DATA;

CREATE UNIQUE INDEX PP_F_ACTUALS_IDX ON PP_F_ACTUALS 
    ( 
     ACTUALS_ID ASC 
    );
ALTER TABLE PP_F_ACTUALS 
    ADD CONSTRAINT PP_F_ACTUALS_PK PRIMARY KEY ( ACTUALS_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_F_ACTUALS 
    ADD CONSTRAINT PP_F_ACTUALS_UN UNIQUE ( D_DATE , D_HOUR , UOW_ID ) using index tablespace MAXDAT_INDX;

grant select on PP_F_ACTUALS to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_F_ACTUALS_SV AS
SELECT ACTUALS_ID, 
     D_DATE, 
     D_HOUR, 
     UOW_ID, 
     PROJECT_ID, 
     PROGRAM_ID, 
     GEOGRAPHY_MASTER_ID, 
     ACTL_ARRIVAL, 
     ACTL_COMPLETION, 
     ACTL_INVENTORY, 
     ACTL_INVENTORY_AGE_AVG, 
     ACTL_INVENTORY_AGE_MIN, 
     ACTL_INVENTORY_AGE_MAX, 
     ACTL_INVENTORY_AGE_MEAN, 
     ACTL_INVENTORY_AGE_MEDIAN, 
     ACTL_INVENTORY_AGE_SD, 
     ACTL_INVENTORY_JEOPARDY, 
     ACTL_HANDLE_TIME_AVG, 
     ACTL_HANDLE_TIME_MIN, 
     ACTL_HANDLE_TIME_MAX, 
     ACTL_HANDLE_TIME_MEAN, 
     ACTL_HANDLE_TIME_MEDIAN, 
     ACTL_HANDLE_TIME_SD, 
     ACTL_STAFF_HOURS
	 FROM PP_F_ACTUALS
WITH READ ONLY;

grant select on PP_F_ACTUALS_SV to MAXDAT_READ_ONLY;
	

CREATE SEQUENCE SEQ_PP_F_FORECAST_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;		
	
CREATE TABLE PP_F_FORECAST 
    ( 
     FORECAST_ID NUMBER  NOT NULL , 
     D_DATE DATE  NOT NULL , 
     D_HOUR NUMBER  NOT NULL , 
     UOW_ID NUMBER  NOT NULL , 
     PPH_ID NUMBER  NOT NULL , 
     FORECAST_VERSION NUMBER  NOT NULL , 
     FCST_ARRIVAL NUMBER , 
     FCST_COMPLETION NUMBER , 
     FCST_INVENTORY NUMBER , 
     FCST_INVENTORY_AGE_AVG NUMBER , 
     FCST_INVENTORY_AGE_MIN NUMBER , 
     FCST_INVENTORY_AGE_MAX NUMBER , 
     FCST_INVENTORY_AGE_MEAN NUMBER , 
     FCST_INVENTORY_AGE_MEDIAN NUMBER , 
     FCST_INVENTORY_AGE_SD NUMBER , 
     FCST_INVENTORY_JEOPARDY NUMBER , 
     FCST_HANDLE_TIME_AVG NUMBER , 
     FCST_HANDLE_TIME_MIN NUMBER , 
     FCST_HANDLE_TIME_MAX NUMBER , 
     FCST_HANDLE_TIME_MEAN NUMBER , 
     FCST_HANDLE_TIME_MEDIAN NUMBER , 
     FCST_HANDLE_TIME_SD NUMBER , 
     FCST_STAFF_HOURS NUMBER , 
     FCST_EFFECTIVE_DATE DATE  NOT NULL , 
     FCST_EFFECTIVE_END_DATE DATE 
    ) tablespace MAXDAT_DATA;
	
CREATE UNIQUE INDEX FPP_PK ON PP_F_FORECAST 
    ( 
     FORECAST_ID ASC 
    );
ALTER TABLE PP_F_FORECAST 
    ADD CONSTRAINT FPP_PK PRIMARY KEY ( FORECAST_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_F_FORECAST 
    ADD CONSTRAINT PP_F_FORECAST_UN UNIQUE ( D_DATE , D_HOUR , UOW_ID , FORECAST_VERSION , PPH_ID ) using index tablespace MAXDAT_INDX;

grant select on PP_F_FORECAST to MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW PP_F_FORECAST_SV AS
SELECT FORECAST_ID, 
     D_DATE, 
     D_HOUR, 
     UOW_ID, 
     PPH_ID, 
     FORECAST_VERSION, 
     FCST_ARRIVAL, 
     FCST_COMPLETION, 
     FCST_INVENTORY, 
     FCST_INVENTORY_AGE_AVG, 
     FCST_INVENTORY_AGE_MIN, 
     FCST_INVENTORY_AGE_MAX, 
     FCST_INVENTORY_AGE_MEAN, 
     FCST_INVENTORY_AGE_MEDIAN, 
     FCST_INVENTORY_AGE_SD, 
     FCST_INVENTORY_JEOPARDY, 
     FCST_HANDLE_TIME_AVG, 
     FCST_HANDLE_TIME_MIN, 
     FCST_HANDLE_TIME_MAX, 
     FCST_HANDLE_TIME_MEAN, 
     FCST_HANDLE_TIME_MEDIAN, 
     FCST_HANDLE_TIME_SD, 
     FCST_STAFF_HOURS, 
     FCST_EFFECTIVE_DATE, 
     FCST_EFFECTIVE_END_DATE
	 FROM PP_F_FORECAST
WITH READ ONLY;		

grant select on PP_F_FORECAST_SV to MAXDAT_READ_ONLY;
	
CREATE SEQUENCE SEQ_PP_PROJECT_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;	

CREATE TABLE PP_D_PROJECT 
    ( 
     PROJECT_ID NUMBER  NOT NULL , 
     PROJECT_NAME VARCHAR2(35)  NOT NULL , 
     SEGMENT_ID NUMBER  NOT NULL 
    ) tablespace MAXDAT_DATA;

ALTER TABLE PP_D_PROJECT 
    ADD CONSTRAINT PK_PP_D_PROJECT PRIMARY KEY ( PROJECT_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_D_PROJECT 
    ADD CONSTRAINT PP_D_PROJECT_UNK UNIQUE ( PROJECT_NAME ) using index tablespace MAXDAT_INDX;

grant select on PP_D_PROJECT to MAXDAT_READ_ONLY;


CREATE OR REPLACE VIEW PP_D_PROJECT_SV AS
SELECT PROJECT_ID, 
     PROJECT_NAME, 
     SEGMENT_ID
	 FROM PP_D_PROJECT
WITH READ ONLY;		    

grant select on PP_D_PROJECT_SV to MAXDAT_READ_ONLY;

	
ALTER TABLE PP_D_ACTUAL_DETAILS 
    ADD CONSTRAINT PP_D_ACTUAL_DTLS_D_DATES_FK FOREIGN KEY 
    ( 
     D_DATE
    ) 
    REFERENCES PP_D_DATES 
    ( 
     D_DATE
    );


ALTER TABLE PP_D_ACTUAL_DETAILS 
    ADD CONSTRAINT PP_D_ACTUAL_DTLS_D_HOURS_FK FOREIGN KEY 
    ( 
     D_HOUR
    ) 
    REFERENCES PP_D_HOURS 
    ( 
     D_HOUR
    );

ALTER TABLE PP_D_ACTUAL_DETAILS 
    ADD CONSTRAINT PP_D_ACTUAL_DTLS_UOWSRCREF_FK FOREIGN KEY 
    ( 
     USR_ID
    ) 
    REFERENCES PP_D_UOW_SOURCE_REF 
    ( 
     USR_ID
    );


ALTER TABLE PP_D_GEOGRAPHY_MASTER 
    ADD CONSTRAINT PP_D_GM_PP_D_COUNTRY_FK FOREIGN KEY 
    ( 
     COUNTRY_ID
    ) 
    REFERENCES PP_D_COUNTRY 
    ( 
     COUNTRY_ID
    );


ALTER TABLE PP_D_GEOGRAPHY_MASTER 
    ADD CONSTRAINT PP_D_GM_PP_D_DISTRICT_FK FOREIGN KEY 
    ( 
     DISTRICT_ID
    ) 
    REFERENCES PP_D_DISTRICT 
    ( 
     DISTRICT_ID
    );


ALTER TABLE PP_D_GEOGRAPHY_MASTER 
    ADD CONSTRAINT PP_D_GM_PP_D_PROVINCE_FK FOREIGN KEY 
    ( 
     PROVINCE_ID
    ) 
    REFERENCES PP_D_PROVINCE 
    ( 
     PROVINCE_ID
    );


ALTER TABLE PP_D_GEOGRAPHY_MASTER 
    ADD CONSTRAINT PP_D_GM_PP_D_REGION_FK FOREIGN KEY 
    ( 
     REGION_ID
    ) 
    REFERENCES PP_D_REGION 
    ( 
     REGION_ID
    );


ALTER TABLE PP_D_GEOGRAPHY_MASTER 
    ADD CONSTRAINT PP_D_GM_PP_D_SITE_FK FOREIGN KEY 
    ( 
     SITE_ID
    ) 
    REFERENCES PP_D_SITE 
    ( 
     SITE_ID
    );


ALTER TABLE PP_D_GEOGRAPHY_MASTER 
    ADD CONSTRAINT PP_D_GM_PP_D_STATE_FK FOREIGN KEY 
    ( 
     STATE_ID
    ) 
    REFERENCES PP_D_STATE 
    ( 
     STATE_ID
    );

	
ALTER TABLE PP_D_PRODUCTION_PLAN 
    ADD CONSTRAINT PP_D_PP_D_PROJECT_FK FOREIGN KEY 
    ( 
     PROJECT_ID
    ) 
    REFERENCES PP_D_PROJECT 
    ( 
     PROJECT_ID
    );


ALTER TABLE PP_D_PRODUCTION_PLAN 
    ADD CONSTRAINT PP_D_PP_GM_FK FOREIGN KEY 
    ( 
     GEOGRAPHY_MASTER_ID
    ) 
    REFERENCES PP_D_GEOGRAPHY_MASTER 
    ( 
     GEOGRAPHY_MASTER_ID
    );


ALTER TABLE PP_D_PRODUCTION_PLAN 
    ADD CONSTRAINT PP_D_PP_PROGRAM_FK FOREIGN KEY 
    ( 
     PROGRAM_ID
    ) 
    REFERENCES PP_D_PROGRAM 
    ( 
     PROGRAM_ID
    );


ALTER TABLE PP_D_PRODUCTION_PLAN_HORIZON 
    ADD CONSTRAINT PP_D_PPH_PP_D_PP_FK FOREIGN KEY 
    ( 
     PP_ID
    ) 
    REFERENCES PP_D_PRODUCTION_PLAN 
    ( 
     PP_ID
    );

ALTER TABLE PP_D_SOURCE_REF_TYPE 
    ADD CONSTRAINT PP_D_SRC_REF_TYPE_PP_D_SRC_FK FOREIGN KEY 
    ( 
     SOURCE_ID
    ) 
    REFERENCES PP_D_SOURCE 
    ( 
     SOURCE_ID
    );

	
ALTER TABLE PP_D_UOW_SOURCE_REF 
    ADD CONSTRAINT PP_D_UOW_SRCREF_PP_DREFTYPE_FK FOREIGN KEY 
    ( 
     SOURCE_REF_TYPE_ID
    ) 
    REFERENCES PP_D_SOURCE_REF_TYPE 
    ( 
     SOURCE_REF_TYPE_ID
    );


ALTER TABLE PP_D_UOW_SOURCE_REF 
    ADD CONSTRAINT PP_D_UOW_SRC_REF_PP_D_UOW_FK FOREIGN KEY 
    ( 
     UOW_ID
    ) 
    REFERENCES PP_D_UNIT_OF_WORK 
    ( 
     UOW_ID
    );


ALTER TABLE PP_FORECAST_NOTES 
    ADD CONSTRAINT PP_FORECAST_NOTES_DPP_FK FOREIGN KEY 
    ( 
     PP_ID
    ) 
    REFERENCES PP_D_PRODUCTION_PLAN 
    ( 
     PP_ID
    );


ALTER TABLE PP_FORECAST_NOTES 
    ADD CONSTRAINT PP_FORECAST_NOTES_DPP_HRZN_FK FOREIGN KEY 
    ( 
     PPH_ID
    ) 
    REFERENCES PP_D_PRODUCTION_PLAN_HORIZON 
    ( 
     PPH_ID
    );


ALTER TABLE PP_F_ACTUALS 
    ADD CONSTRAINT PP_F_ACTUALS_PP_D_DATES_FK FOREIGN KEY 
    ( 
     D_DATE
    ) 
    REFERENCES PP_D_DATES 
    ( 
     D_DATE
    );


ALTER TABLE PP_F_ACTUALS 
    ADD CONSTRAINT PP_F_ACTUALS_PP_D_GEO_MSTR_FK FOREIGN KEY 
    ( 
     GEOGRAPHY_MASTER_ID
    ) 
    REFERENCES PP_D_GEOGRAPHY_MASTER 
    ( 
     GEOGRAPHY_MASTER_ID
    );


ALTER TABLE PP_F_ACTUALS 
    ADD CONSTRAINT PP_F_ACTUALS_PP_D_HOUR_FK FOREIGN KEY 
    ( 
     D_HOUR
    ) 
    REFERENCES PP_D_HOURS 
    ( 
     D_HOUR
    );


ALTER TABLE PP_F_ACTUALS 
    ADD CONSTRAINT PP_F_ACTUALS_PP_D_PROGRAM_FK FOREIGN KEY 
    ( 
     PROGRAM_ID
    ) 
    REFERENCES PP_D_PROGRAM 
    ( 
     PROGRAM_ID
    );


ALTER TABLE PP_F_ACTUALS 
    ADD CONSTRAINT PP_F_ACTUALS_PP_D_PROJECT_FK FOREIGN KEY 
    ( 
     PROJECT_ID
    ) 
    REFERENCES PP_D_PROJECT 
    ( 
     PROJECT_ID
    );


ALTER TABLE PP_F_ACTUALS 
    ADD CONSTRAINT PP_F_ACTUALS_PP_D_UOW_FK FOREIGN KEY 
    ( 
     UOW_ID
    ) 
    REFERENCES PP_D_UNIT_OF_WORK 
    ( 
     UOW_ID
    );


ALTER TABLE PP_F_FORECAST 
    ADD CONSTRAINT F_FORECAST_PP_D_HORIZON_FK FOREIGN KEY 
    ( 
     PPH_ID
    ) 
    REFERENCES PP_D_PRODUCTION_PLAN_HORIZON 
    ( 
     PPH_ID
    );


ALTER TABLE PP_F_FORECAST 
    ADD CONSTRAINT F_PP_D_UOW_FK FOREIGN KEY 
    ( 
     UOW_ID
    ) 
    REFERENCES PP_D_UNIT_OF_WORK 
    ( 
     UOW_ID
    );


ALTER TABLE PP_F_FORECAST 
    ADD CONSTRAINT PP_F_FORECAST_PP_D_DATES_FK FOREIGN KEY 
    ( 
     D_DATE
    ) 
    REFERENCES PP_D_DATES 
    ( 
     D_DATE
    );


ALTER TABLE PP_F_FORECAST 
    ADD CONSTRAINT PP_F_FORECAST_PP_D_HOURS_FK FOREIGN KEY 
    ( 
     D_HOUR
    ) 
    REFERENCES PP_D_HOURS 
    ( 
     D_HOUR
    );
    
ALTER TABLE PP_D_PROJECT 
    ADD CONSTRAINT PP_D_PROJ_PP_D_SEG_FK FOREIGN KEY 
    ( 
     SEGMENT_ID
    ) 
    REFERENCES PP_D_SEGMENT 
    ( 
     SEGMENT_ID
    );    


commit;



----------------------------------
--- PROD PLAN STAGING BELOW ------
----------------------------------
CREATE SEQUENCE SEQ_CFG_FRCST_FILE_CTRL_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;	

CREATE TABLE PP_CFG_FORECAST_FILE_CONTROL 
    ( 
     CFG_FORECAST_FILE_CONTROL_ID NUMBER  NOT NULL , 
     CFG_PRODUCTION_PLAN_ID NUMBER  NOT NULL , 
     FILE_LOCATION VARCHAR2(250) , 
     INVENTORY_FILENAME VARCHAR2(250) , 
     VOLUME_FILENAME VARCHAR2(250) , 
     ENABLED VARCHAR2(1)  NOT NULL , 
     CREATE_DATE DATE  NOT NULL , 
     LAST_UPDATE_DATE DATE 
    ) tablespace MAXDAT_DATA;


CREATE INDEX PP_CFG_FRCST_FILE_CONTROL_IDX ON PP_CFG_FORECAST_FILE_CONTROL 
    ( 
     CFG_PRODUCTION_PLAN_ID ASC 
    )
tablespace MAXDAT_INDX;

ALTER TABLE PP_CFG_FORECAST_FILE_CONTROL 
    ADD CONSTRAINT PP_CFG_FRCST_FILE_CONTROL_PK PRIMARY KEY ( CFG_FORECAST_FILE_CONTROL_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_CFG_FORECAST_FILE_CONTROL 
    ADD CONSTRAINT PP_CFG_FRCST_FILE_CONTROL_UN UNIQUE ( CFG_PRODUCTION_PLAN_ID ) using index tablespace MAXDAT_INDX;

	
CREATE SEQUENCE SEQ_CFG_GEOGRAPHY_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;		

CREATE TABLE PP_CFG_GEOGRAPHY_CONFIG 
    ( 
     CFG_GEOGRAPHY_CONFIG_ID NUMBER  NOT NULL , 
     SITE_NAME VARCHAR2(50) , 
     REGION_NAME VARCHAR2(50) , 
     STATE_NAME VARCHAR2(50) , 
     PROVINCE_NAME VARCHAR2(50) , 
     DISTRICT_NAME VARCHAR2(50) , 
     COUNTRY_NAME VARCHAR2(50) , 
     RECORD_EFF_DT DATE  NOT NULL , 
     RECORD_END_DT DATE  NOT NULL 
    ) tablespace MAXDAT_DATA;

ALTER TABLE PP_CFG_GEOGRAPHY_CONFIG 
    ADD CONSTRAINT PP_CFG_PROJECT_CONFIG_PK PRIMARY KEY ( CFG_GEOGRAPHY_CONFIG_ID ) using index tablespace MAXDAT_INDX;


CREATE SEQUENCE SEQ_CFG_HORIZON_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;	
	
CREATE TABLE PP_CFG_HORIZON 
    ( 
     CFG_HORIZON_ID NUMBER  NOT NULL , 
     CFG_PRODUCTION_PLAN_ID NUMBER  NOT NULL , 
     HORIZON_START_DATE DATE  NOT NULL , 
     HORIZON_START_HOUR NUMBER DEFAULT 0  NOT NULL , 
     HORIZON_END_DATE DATE  NOT NULL , 
     HORIZON_END_HOUR NUMBER DEFAULT 0  NOT NULL , 
     HORIZON_NAME VARCHAR2(50)  NOT NULL , 
     HORIZON_DESCRIPTION VARCHAR2(1000) , 
     CREATE_DATE DATE DEFAULT sysdate  NOT NULL , 
     LAST_UPDATE_DATE DATE DEFAULT sysdate  NOT NULL 
    ) tablespace MAXDAT_DATA;


ALTER TABLE PP_CFG_HORIZON 
    ADD CONSTRAINT PP_CFG_HORIZON_PK PRIMARY KEY ( CFG_HORIZON_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_CFG_HORIZON 
    ADD CONSTRAINT PP_CFG_HORIZON_UN UNIQUE ( CFG_PRODUCTION_PLAN_ID , HORIZON_START_DATE , HORIZON_START_HOUR ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_CFG_HORIZON 
    ADD CONSTRAINT PP_CFG_HORIZON_UN1 UNIQUE ( CFG_PRODUCTION_PLAN_ID , HORIZON_END_DATE , HORIZON_END_HOUR ) using index tablespace MAXDAT_INDX;


CREATE SEQUENCE SEQ_CFG_PRODUCTION_PLAN_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;		

CREATE TABLE PP_CFG_PRODUCTION_PLAN 
    ( 
     CFG_PRODUCTION_PLAN_ID NUMBER  NOT NULL , 
     CFG_GEOGRAPHY_CONFIG_ID NUMBER  NOT NULL , 
     CFG_PROJECT_CONFIG_ID NUMBER  NOT NULL , 
     PRODUCTION_PLAN_NAME VARCHAR2(50)  NOT NULL , 
     PRODUCTION_PLAN_DESCRIPTION VARCHAR2(1000)  NOT NULL , 
     EFFECTIVE_DATE DATE  NOT NULL , 
     END_DATE DATE , 
     CREATE_DATE DATE DEFAULT sysdate  NOT NULL , 
     LAST_UPDATE_DATE DATE DEFAULT sysdate  NOT NULL 
    ) tablespace MAXDAT_DATA;

ALTER TABLE PP_CFG_PRODUCTION_PLAN 
    ADD CONSTRAINT PP_CFG_PROD_PLAN_PK PRIMARY KEY ( CFG_PRODUCTION_PLAN_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_CFG_PRODUCTION_PLAN 
    ADD CONSTRAINT PP_CFG_PROD_PLAN_UN UNIQUE ( PRODUCTION_PLAN_NAME , CFG_GEOGRAPHY_CONFIG_ID , EFFECTIVE_DATE ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_CFG_PRODUCTION_PLAN 
    ADD CONSTRAINT PP_CFG_PROD_PLAN_UN1 UNIQUE ( CFG_GEOGRAPHY_CONFIG_ID , PRODUCTION_PLAN_NAME , END_DATE ) using index tablespace MAXDAT_INDX;


CREATE SEQUENCE SEQ_CFG_PROJECT_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE PP_CFG_PROJECT_CONFIG 
    ( 
     CFG_PROJECT_CONFIG_ID NUMBER  NOT NULL , 
     SEGMENT_NAME VARCHAR2(35)  NOT NULL , 
     PROJECT_NAME VARCHAR2(35)  NOT NULL , 
     PROGRAM_NAME VARCHAR2(35)  NOT NULL , 
     CREATE_DATE DATE DEFAULT sysdate  NOT NULL , 
     LAST_UPDATE_DATE DATE DEFAULT sysdate  NOT NULL 
    ) tablespace MAXDAT_DATA;

ALTER TABLE PP_CFG_PROJECT_CONFIG 
    ADD CONSTRAINT PP_CFG_PROJECT_PK PRIMARY KEY ( CFG_PROJECT_CONFIG_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_CFG_PROJECT_CONFIG 
    ADD CONSTRAINT PP_CFG_PROJECT_UN UNIQUE ( SEGMENT_NAME , PROJECT_NAME , PROGRAM_NAME ) using index tablespace MAXDAT_INDX;

CREATE TABLE PP_CFG_PROGRAM_CONFIG 
    ( 
     CFG_PROGRAM_CONFIG_ID NUMBER  NOT NULL , 
     PROGRAM_NAME VARCHAR2(35)  NOT NULL 
    ) tablespace MAXDAT_DATA;
ALTER TABLE PP_CFG_PROGRAM_CONFIG 
    ADD CONSTRAINT PP_CFG_PROGRAM_CONFIG_PK PRIMARY KEY ( CFG_PROGRAM_CONFIG_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_CFG_PROGRAM_CONFIG 
    ADD CONSTRAINT PP_CFG_PROGRAM_CONFIG_UNK UNIQUE ( PROGRAM_NAME ) using index tablespace MAXDAT_INDX;    

CREATE TABLE PP_CFG_SOURCE_CONFIG 
    ( 
     CFG_SOURCE_CONFIG_ID NUMBER  NOT NULL , 
     SOURCE_NAME VARCHAR2(35)  NOT NULL , 
     SOURCE_DESCRIPTION VARCHAR2(250)  NOT NULL 
    ) tablespace MAXDAT_DATA;
ALTER TABLE PP_CFG_SOURCE_CONFIG 
    ADD CONSTRAINT PP_CFG_SOURCE_CONFIG_PK PRIMARY KEY ( CFG_SOURCE_CONFIG_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_CFG_SOURCE_CONFIG 
    ADD CONSTRAINT PP_CFG_SOURCE_CONFIG_UNK UNIQUE ( SOURCE_NAME ) using index tablespace MAXDAT_INDX;    

CREATE SEQUENCE SEQ_CFG_UOW_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE PP_CFG_UNIT_OF_WORK 
    ( 
     CFG_UOW_ID NUMBER  NOT NULL , 
     UNIT_OF_WORK_NAME VARCHAR2(50)  NOT NULL , 
     HOURLY_FLAG VARCHAR2(1) DEFAULT 'N'  NOT NULL CHECK ( HOURLY_FLAG IN ('N', 'Y')) , 
     HANDLE_TIME_UNIT VARCHAR2(9) CHECK ( HANDLE_TIME_UNIT IN ('Days', 'Hours', 'Minutes', 'Seconds')) ,
     JEOPARDY_INV_AGE NUMBER NOT NULL ,
     AGE_DAYS_TYPE VARCHAR2(3) DEFAULT 'CAL'  NOT NULL CHECK ( AGE_DAYS_TYPE IN ('CAL', 'BUS')) ,
     INV_AVG_AGE NUMBER NOT NULL , 
     LABEL VARCHAR2(50) NOT NULL
    ) tablespace MAXDAT_DATA;
	
ALTER TABLE PP_CFG_UNIT_OF_WORK 
    ADD CONSTRAINT PP_CFG_UNIT_OF_WORK_PK PRIMARY KEY ( CFG_UOW_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_CFG_UNIT_OF_WORK 
    ADD CONSTRAINT PP_CFG_UNIT_OF_WORK_UK1 UNIQUE ( UNIT_OF_WORK_NAME ) using index tablespace MAXDAT_INDX;

CREATE TABLE PP_STG_FCST_BY_INV_AGE 
    ( 
     HORIZON_START_DATE DATE  NOT NULL , 
     HORIZON_END_DATE DATE  NOT NULL , 
     DAY_OF_PLAN NUMBER  NOT NULL , 
     FORECAST_HOUR NUMBER  NOT NULL , 
     UNIT_OF_WORK_NAME VARCHAR2(50)  NOT NULL , 
     INVENTORY_AGE NUMBER  NOT NULL , 
     INVENTORY_VOLUME NUMBER  NOT NULL , 
     CREATION_DATE DATE DEFAULT SYSDATE , 
     CFG_PRODUCTION_PLAN_ID NUMBER , 
     PROCESS_DATE DATE ,
     FORECAST_DATE DATE
    ) tablespace MAXDAT_DATA;



CREATE TABLE PP_STG_FCST_VOLUME 
    ( 
     HORIZON_START_DATE DATE  NOT NULL , 
     HORIZON_END_DATE DATE  NOT NULL , 
     DAY_OF_PLAN NUMBER  NOT NULL , 
     FORECAST_HOUR NUMBER  NOT NULL , 
     UNIT_OF_WORK_NAME VARCHAR2(50)  NOT NULL , 
     ARRIVAL_VOLUME NUMBER  NOT NULL , 
     COMPLETION_VOLUME NUMBER  NOT NULL , 
     STAFF_HOURS NUMBER  NOT NULL , 
     HANDLE_TIME_AVG NUMBER  NOT NULL , 
     HANDLE_TIME_MIN NUMBER  NOT NULL , 
     HANDLE_TIME_MAX NUMBER  NOT NULL ,
     CREATION_DATE DATE DEFAULT SYSDATE , 
     CFG_PRODUCTION_PLAN_ID NUMBER , 
     PROCESS_DATE DATE , 
     FORECAST_DATE DATE 
    ) tablespace MAXDAT_DATA;

CREATE SEQUENCE SEQ_SPPF_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;


CREATE TABLE PP_STG_FORECAST 
    ( 
     SPPF_ID NUMBER  NOT NULL , 
     CFG_HORIZON_ID NUMBER  NOT NULL , 
     FORECAST_DATE DATE  NOT NULL , 
     FORECAST_HOUR NUMBER DEFAULT 0  NOT NULL CHECK ( FORECAST_HOUR BETWEEN 0 AND 23) , 
     CFG_UOW_ID NUMBER  NOT NULL , 
     ARRIVAL NUMBER , 
     COMPLETION NUMBER , 
     INVENTORY NUMBER , 
     INVENTORY_AGE_AVG NUMBER , 
     INVENTORY_AGE_MIN NUMBER , 
     INVENTORY_AGE_MAX NUMBER , 
     INVENTORY_AGE_MEAN NUMBER , 
     INVENTORY_AGE_MEDIAN NUMBER , 
     INVENTORY_AGE_SD NUMBER , 
     INVENTORY_JEOPARDY NUMBER , 
     HANDLE_TIME_AVG NUMBER , 
     HANDLE_TIME_MIN NUMBER , 
     HANDLE_TIME_MAX NUMBER , 
     HANDLE_TIME_MEAN NUMBER , 
     HANDLE_TIME_MEDIAN NUMBER , 
     HANDLE_TIME_SD NUMBER , 
     STAFF_HOURS NUMBER , 
     FORECAST_VERSION NUMBER DEFAULT 1  NOT NULL , 
     EFFECTIVE_DATE DATE DEFAULT sysdate  NOT NULL , 
     END_DATE DATE DEFAULT sysdate  NOT NULL , 
     IDENTIFIER VARCHAR2(100) , 
     PROCESS_DATE DATE 
    ) tablespace MAXDAT_DATA;


CREATE UNIQUE INDEX PP_STG_FORECAST_PK ON PP_STG_FORECAST 
    ( 
     SPPF_ID ASC 
    );

ALTER TABLE PP_STG_FORECAST 
    ADD CONSTRAINT PP_STG_FORECAST_PK PRIMARY KEY ( SPPF_ID ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_STG_FORECAST 
    ADD CONSTRAINT PP_STG_FORECAST_UN UNIQUE ( CFG_HORIZON_ID , CFG_UOW_ID , FORECAST_DATE , FORECAST_HOUR , FORECAST_VERSION ) using index tablespace MAXDAT_INDX;
ALTER TABLE PP_STG_FORECAST 
    ADD CONSTRAINT PP_STG_FORECAST_UN1 UNIQUE ( CFG_HORIZON_ID , FORECAST_DATE , FORECAST_HOUR , CFG_UOW_ID , END_DATE ) using index tablespace MAXDAT_INDX;

CREATE SEQUENCE SEQ_PP_STG_ID
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;	

CREATE TABLE PP_STG_LOG 
    ( 
     PP_STG_ID NUMBER  NOT NULL , 
     LOG_TYPE VARCHAR2(3)  NOT NULL CHECK ( LOG_TYPE IN ('ERR', 'LOG', 'OTH')) , 
     PROCESS_DATE DATE  NOT NULL , 
     PROCESS VARCHAR2(50)  NOT NULL , 
     DESCRIPTION VARCHAR2(4000)  NOT NULL , 
     CREATE_DATE DATE  NOT NULL 
    ) tablespace MAXDAT_DATA;

ALTER TABLE PP_STG_LOG 
    ADD CONSTRAINT PP_STG_LOG_CK0 
    CHECK (LOG_TYPE IN ('ERR', 'LOG', 'OTH'));
ALTER TABLE PP_STG_LOG 
    ADD CONSTRAINT PP_STG_LOG_PK PRIMARY KEY ( PP_STG_ID ) using index tablespace MAXDAT_INDX;



ALTER TABLE PP_CFG_FORECAST_FILE_CONTROL 
    ADD CONSTRAINT CFG_FRCST_FILE_CTRL_PRDPLAN_FK FOREIGN KEY 
    ( 
     CFG_PRODUCTION_PLAN_ID
    ) 
    REFERENCES PP_CFG_PRODUCTION_PLAN 
    ( 
     CFG_PRODUCTION_PLAN_ID
    );


ALTER TABLE PP_CFG_HORIZON 
    ADD CONSTRAINT CFG_PRDPLAN_HRZN_CFG_PRDPLN_FK FOREIGN KEY 
    ( 
     CFG_PRODUCTION_PLAN_ID
    ) 
    REFERENCES PP_CFG_PRODUCTION_PLAN 
    ( 
     CFG_PRODUCTION_PLAN_ID
    );


ALTER TABLE PP_CFG_PRODUCTION_PLAN 
    ADD CONSTRAINT PP_CFG_PROD_PLAN_CFG_GEO_FK FOREIGN KEY 
    ( 
     CFG_GEOGRAPHY_CONFIG_ID
    ) 
    REFERENCES PP_CFG_GEOGRAPHY_CONFIG 
    ( 
     CFG_GEOGRAPHY_CONFIG_ID
    );


ALTER TABLE PP_CFG_PRODUCTION_PLAN 
    ADD CONSTRAINT PP_CFG_PROD_PLAN_CFG_PROJ_FK FOREIGN KEY 
    ( 
     CFG_PROJECT_CONFIG_ID
    ) 
    REFERENCES PP_CFG_PROJECT_CONFIG 
    ( 
     CFG_PROJECT_CONFIG_ID
    );


ALTER TABLE PP_STG_FORECAST 
    ADD CONSTRAINT PP_STG_FORECAST_PP_CFG_HRZN_FK FOREIGN KEY 
    ( 
     CFG_HORIZON_ID
    ) 
    REFERENCES PP_CFG_HORIZON 
    ( 
     CFG_HORIZON_ID
    );


ALTER TABLE PP_STG_FORECAST 
    ADD CONSTRAINT PP_STG_FORECAST_PP_CFG_UOW_FK FOREIGN KEY 
    ( 
     CFG_UOW_ID
    ) 
    REFERENCES PP_CFG_UNIT_OF_WORK 
    ( 
     CFG_UOW_ID
    );
    
--Add Actuals Import
---- ACTUALS CONTROL FILE  
CREATE TABLE PP_CFG_ACTUALS_FILE_CONTROL
(
  CFG_ACTUALS_FILE_CONTROL_ID  NUMBER NOT NULL,
  PROJECT_ID                   NUMBER NOT NULL,
  PROGRAM_ID                   NUMBER NOT NULL,
  GEOGRAPHY_MASTER_ID          NUMBER NOT NULL,
  FILE_LOCATION                VARCHAR2(250),
  ACTUALS_FILENAME             VARCHAR2(250),
  ENABLED                      VARCHAR2(1) NOT NULL,
  CREATE_DATE                  DATE NOT NULL,
  LAST_UPDATE_DATE             DATE
);

ALTER TABLE PP_CFG_ACTUALS_FILE_CONTROL
  ADD CONSTRAINT PP_CFG_ACTUALS_FILE_CTRL_PK PRIMARY KEY (CFG_ACTUALS_FILE_CONTROL_ID) using index tablespace MAXDAT_INDX;
  
ALTER TABLE PP_CFG_ACTUALS_FILE_CONTROL
  ADD CONSTRAINT PP_CFG_ACTUALS_FILE_CTRL_UN UNIQUE (PROJECT_ID,PROGRAM_ID,GEOGRAPHY_MASTER_ID) using index tablespace MAXDAT_INDX;
  
-- ACTUALS FROM FILE  
CREATE TABLE PP_STG_ACTUALS_IMPORT
(
  ACTUALS_DATE           DATE NOT NULL,
  ACTUALS_HOUR           NUMBER NOT NULL,
  UNIT_OF_WORK_NAME      VARCHAR2(50) NOT NULL,
  STAFF_HOURS            NUMBER,
  HANDLE_TIME_AVG        NUMBER,
  HANDLE_TIME_MIN        NUMBER,
  HANDLE_TIME_MAX        NUMBER,
  HANDLE_TIME_MEAN       NUMBER,
  HANDLE_TIME_MEDIAN     NUMBER,
  HANDLE_TIME_SD         NUMBER,
  CREATION_DATE          DATE DEFAULT SYSDATE,
  PROJECT_ID             NUMBER,
  PROGRAM_ID             NUMBER,
  GEOGRAPHY_MASTER_ID    NUMBER,
  PROCESS_DATE           DATE
) tablespace MAXDAT_DATA;

-- ACTUALS STAGING  
CREATE TABLE PP_STG_ACTUALS
(
  SA_ID                NUMBER NOT NULL,
  ACTUALS_DATE         DATE NOT NULL,
  ACTUALS_HOUR         NUMBER NOT NULL,
  CFG_UOW_ID           NUMBER NOT NULL,
  PROJECT_ID           NUMBER NOT NULL,
  PROGRAM_ID           NUMBER NOT NULL,
  GEOGRAPHY_MASTER_ID  NUMBER NOT NULL,
  HANDLE_TIME_AVG      NUMBER,
  HANDLE_TIME_MIN      NUMBER,
  HANDLE_TIME_MAX      NUMBER,
  HANDLE_TIME_MEAN     NUMBER,
  HANDLE_TIME_MEDIAN   NUMBER,
  HANDLE_TIME_SD       NUMBER,
  STAFF_HOURS          NUMBER,
  PROCESS_DATE         DATE
) tablespace MAXDAT_DATA;
ALTER TABLE PP_STG_ACTUALS
  ADD CONSTRAINT PP_STG_ACTUALS_PK PRIMARY KEY (SA_ID);
  
--ALTER TABLE PP_STG_ACTUALS ***NOT NEEDED
--  ADD CONSTRAINT PP_STG_ACTUALS_UN UNIQUE (ACTUALS_DATE, ACTUALS_HOUR, CFG_UOW_ID, PROJECT_ID, PROGRAM_ID, GEOGRAPHY_MASTER_ID, PROCESS_DATE); 
  
ALTER TABLE PP_STG_ACTUALS
  ADD CONSTRAINT PP_STG_ACTUALS_PP_CFG_UOW_FK FOREIGN KEY (CFG_UOW_ID)
  REFERENCES PP_CFG_UNIT_OF_WORK (CFG_UOW_ID);
  
ALTER TABLE PP_STG_ACTUALS
  ADD CHECK ( ACTUALS_HOUR BETWEEN 0 AND 23);
  
  
create sequence SEQ_PP_STG_ACTUALS_ID
minvalue 1
maxvalue 999999999999999999999999999
start with 1
increment by 1
cache 20;      
  
    
commit;  

CREATE OR REPLACE Procedure PP_AddUnitOfWork
(    in_uow_name IN varchar2,
     in_hourly_flag IN varchar2,
     in_handle_time_unit IN varchar2,
     in_jeopardy_inv_age IN number,
     in_age_days_type IN varchar2,
     in_inv_avg_age IN number,
     in_label IN varchar2
)

IS
   v_next_uow_id number;

   cursor c1 is
   SELECT max(cfg_uow_id) + 1 as next_uow_id FROM PP_CFG_UNIT_OF_WORK;

BEGIN

   open c1;
   fetch c1 into v_next_uow_id;

   if c1%notfound then
      v_next_uow_id := 1;
   end if;

   insert into pp_cfg_unit_of_work
     (cfg_uow_id, unit_of_work_name, hourly_flag, handle_time_unit, jeopardy_inv_age, age_days_type, inv_avg_age, label)
   values
     (v_next_uow_id, in_uow_name, in_hourly_flag, in_handle_time_unit, in_jeopardy_inv_age, in_age_days_type, in_inv_avg_age, in_label);

   insert into pp_d_unit_of_work
     (uow_id, unit_of_work_name, handle_time_unit, jeopardy_inv_age, label)
   values
     (v_next_uow_id, in_uow_name, in_handle_time_unit, in_jeopardy_inv_age, in_label);


   commit;

   close c1;

END;
/  


