
insert into PP_D_SOURCE (source_id,source_name,source_description) values (4,'EVENT','New York HIX PIPKINS Events Table');

insert into PP_D_SOURCE_REF_TYPE(SOURCE_REF_TYPE_ID,SOURCE_REF_TYPE_NAME,SOURCE_ID) values (4,'PIPKINS EVENTS',4);

insert into PP_D_UNIT_OF_WORK(UOW_ID,UNIT_OF_WORK_NAME,HANDLE_TIME_UNIT,JEOPARDY_INV_AGE,LABEL) values (0,'NA','Minutes',0,'NA');
insert into PP_D_UNIT_OF_WORK(UOW_ID,UNIT_OF_WORK_NAME,HANDLE_TIME_UNIT,JEOPARDY_INV_AGE,LABEL) values (18,'NYHIX_VERIF','Minutes',3,'VERIF');
insert into PP_D_UNIT_OF_WORK(UOW_ID,UNIT_OF_WORK_NAME,HANDLE_TIME_UNIT,JEOPARDY_INV_AGE,LABEL) values (19,'NYHIX_RESEARCH','Minutes',2,'RESEARCH');


commit;