alter session set current_schema = MAXDAT;

/*Staging tables*/
TRUNCATE TABLE CORP_ETL_MANAGE_ENROLL;
TRUNCATE TABLE CORP_ETL_MANAGE_ENROLL_OLTP;
TRUNCATE TABLE CORP_ETL_MANAGE_ENROLL_WIP;


/*Semantic tables*/
ALTER TABLE F_ME_BY_DATE DISABLE CONSTRAINT FMEBD_DMECUR_FK;
TRUNCATE TABLE F_ME_BY_DATE;
TRUNCATE TABLE D_ME_CURRENT;
ALTER TABLE F_ME_BY_DATE ENABLE CONSTRAINT FMEBD_DMECUR_FK;

DELETE FROM D_ME_ENRL_STATUS_CODE;


/*Update global controls*/
update corp_etl_control
set value = '90'
where name = 'MANAGEENROLL_CDC_DAYS_BACK';

update corp_etl_control
set value = '91066411'
where name = 'MANAGEENROLL_LAST_CLNT_ENRL_STAT_ID';

commit;
