ALTER TABLE TS_PORTAL_USAGE ADD (PORTAL_ENROLLMENT_STATUS VARCHAR2(100 BYTE));
    
CREATE OR REPLACE Procedure TS_PORTAL_USAGE_INSERT
    (
    IN_PORTAL_USAGE_LANGUAGE	      IN VARCHAR2,
    IN_PORTAL_USAGE_STATUS	      IN VARCHAR2,
    IN_PORTAL_USAGE_DATETIME	      IN DATE,
    IN_PORTAL_USAGE_TEST_CONTACT     IN NUMBER,
    IN_PORTAL_USAGE_FAX_ASSISTANCE   IN NUMBER,
    IN_PORTAL_USAGE_ENROLLMENT_ASSISTANCE    IN NUMBER,
    IN_PORTAL_USAGE_DISENROLLMENT_ASSISTANCE	      IN NUMBER,
    IN_PORTAL_USAGE_PACKET_REQUEST   IN NUMBER,
    IN_PORTAL_USAGE_OTHER    IN NUMBER,
    IN_STAFF_ID      IN VARCHAR2
   )
    
AS

BEGIN
 If  IN_PORTAL_USAGE_DATETIME is null  or IN_STAFF_ID is null or trunc(IN_PORTAL_USAGE_DATETIME) > trunc(sysdate) then
     /*do nothing*/
      null;
   else
      
      insert into TS_PORTAL_USAGE
(
   PORTAL_USAGE_ID,
   PORTAL_LANGUAGE,
   PORTAL_ENROLLMENT_STATUS,
   PORTAL_USAGE_DATETIME,
   PORTAL_USAGE_TEST_CONTACT,
   PORTAL_USAGE_FAX_ASSISTANCE,
   PORTAL_USAGE_ENROLLMENT_ASSISTANCE,
   PORTAL_USAGE_DISENROLLMENT_ASSISTANCE,
   PORTAL_USAGE_PACKET_REQUEST,
   PORTAL_USAGE_OTHER,
   CREATE_BY,
   CREATE_DATE,
   LAST_UPDATE_BY,
   LAST_UPDATE_DATE
)
      values
(
SEQ_PORTAL_USAGE_ID.Nextval,
   IN_PORTAL_USAGE_LANGUAGE,
   IN_PORTAL_USAGE_STATUS,
   IN_PORTAL_USAGE_DATETIME,
   IN_PORTAL_USAGE_TEST_CONTACT,
   IN_PORTAL_USAGE_FAX_ASSISTANCE,
   IN_PORTAL_USAGE_ENROLLMENT_ASSISTANCE,
   IN_PORTAL_USAGE_DISENROLLMENT_ASSISTANCE,
   IN_PORTAL_USAGE_PACKET_REQUEST,
   IN_PORTAL_USAGE_OTHER,
   IN_STAFF_ID,
   SYSDATE,
   IN_STAFF_ID,
   SYSDATE
);

       commit;

   end if;
   NULL;
END;
/       

CREATE OR REPLACE Procedure TS_PORTAL_USAGE_UPDATE
    (
   IN_PORTAL_USAGE_ID	      IN NUMBER,
   IN_PORTAL_USAGE_LANGUAGE	      IN VARCHAR2,
   IN_PORTAL_USAGE_STATUS	      IN VARCHAR2,
   IN_PORTAL_USAGE_DATETIME	      IN DATE,
   IN_PORTAL_USAGE_TEST_CONTACT     IN NUMBER,
   IN_PORTAL_USAGE_FAX_ASSISTANCE   IN NUMBER,
   IN_PORTAL_USAGE_ENROLLMENT_ASSISTANCE    IN NUMBER,
   IN_PORTAL_USAGE_DISENROLLMENT_ASSISTANCE	      IN NUMBER,
   IN_PORTAL_USAGE_PACKET_REQUEST   IN NUMBER,
   IN_PORTAL_USAGE_OTHER    IN NUMBER,
    IN_STAFF_ID      IN VARCHAR2
   )
     
AS
   
BEGIN

if  
length(IN_PORTAL_USAGE_TEST_CONTACT) is NULL AND length(IN_PORTAL_USAGE_FAX_ASSISTANCE) is NULL AND length(IN_PORTAL_USAGE_ENROLLMENT_ASSISTANCE) is NULL AND length(IN_PORTAL_USAGE_DISENROLLMENT_ASSISTANCE) is NULL AND length(IN_PORTAL_USAGE_PACKET_REQUEST) is NULL AND length(IN_PORTAL_USAGE_OTHER) is NULL then
     /*do nothing*/
      null;
   else
       
       update TS_PORTAL_USAGE
      set PORTAL_USAGE_TEST_CONTACT = case when (length(IN_PORTAL_USAGE_TEST_CONTACT)> 0) then IN_PORTAL_USAGE_TEST_CONTACT else  PORTAL_USAGE_TEST_CONTACT end,
      PORTAL_USAGE_FAX_ASSISTANCE = case when (length(IN_PORTAL_USAGE_FAX_ASSISTANCE)> 0) then IN_PORTAL_USAGE_FAX_ASSISTANCE else  PORTAL_USAGE_FAX_ASSISTANCE end,
      PORTAL_USAGE_ENROLLMENT_ASSISTANCE = case when (length(IN_PORTAL_USAGE_ENROLLMENT_ASSISTANCE)> 0) then IN_PORTAL_USAGE_ENROLLMENT_ASSISTANCE else  PORTAL_USAGE_ENROLLMENT_ASSISTANCE end,
      PORTAL_USAGE_DISENROLLMENT_ASSISTANCE = case when (length(IN_PORTAL_USAGE_DISENROLLMENT_ASSISTANCE)> 0) then IN_PORTAL_USAGE_DISENROLLMENT_ASSISTANCE else	PORTAL_USAGE_ENROLLMENT_ASSISTANCE end,
      PORTAL_USAGE_PACKET_REQUEST = case when (length(IN_PORTAL_USAGE_PACKET_REQUEST)> 0) then IN_PORTAL_USAGE_PACKET_REQUEST else  PORTAL_USAGE_PACKET_REQUEST end,
      PORTAL_USAGE_OTHER = case when (length(IN_PORTAL_USAGE_OTHER)> 0) then IN_PORTAL_USAGE_OTHER else  PORTAL_USAGE_OTHER end,
 	   LAST_UPDATE_BY = IN_STAFF_ID,
 	   LAST_UPDATE_DATE = sysdate
      where PORTAL_USAGE_ID = IN_PORTAL_USAGE_ID;

       commit;

   end if;
   NULL;

END;
/