CREATE TABLE TS_PORTAL_AVAILABILTY
    (
          PORTAL_AVAILABILTY_ID	 INTEGER,
    PORTAL_DOWNTIME		 VARCHAR2(100 BYTE),
    PORTAL_DATETIME		 DATE,
    PORTAL_AVAILABILTY_HOURS	 INTEGER,
    PORTAL_AVAILABILTY_MINUTES  INTEGER,
    PORTAL_AVAILABILTY_SECONDS  INTEGER,
    CREATE_BY			 VARCHAR2(50 BYTE),
    CREATE_DATE		 DATE,
    LAST_UPDATE_BY		 VARCHAR2(50 BYTE),
    LAST_UPDATE_DATE		 DATE,
    CONSTRAINT
   	   pk_portal_avail_id
   PRIMARY KEY (PORTAL_AVAILABILTY_ID)
   )TABLESPACE MAXDAT_DATA;

CREATE OR REPLACE VIEW TS_PORTAL_AVAILABILTY_SV AS
    select
    PORTAL_AVAILABILTY_ID,
    PORTAL_DOWNTIME,
    PORTAL_DATETIME,
    PORTAL_AVAILABILTY_HOURS,
    PORTAL_AVAILABILTY_MINUTES,
    PORTAL_AVAILABILTY_SECONDS,
    CREATE_BY,
    CREATE_DATE
    LAST_UPDATE_BY,
    LAST_UPDATE_DATE
    from TS_PORTAL_AVAILABILTY;

CREATE TABLE TS_PORTAL_USAGE
    (
          PORTAL_USAGE_ID				 INTEGER,
    PORTAL_LANGUAGE				 VARCHAR2(100 BYTE),
    PORTAL_USAGE_DATETIME			 DATE,
    PORTAL_USAGE_TEST_CONTACT			 INTEGER,
    PORTAL_USAGE_FAX_ASSISTANCE		 INTEGER,
    PORTAL_USAGE_ENROLLMENT_ASSISTANCE 	 INTEGER,
    PORTAL_USAGE_DISENROLLMENT_ASSISTANCE	 INTEGER,
    PORTAL_USAGE_PACKET_REQUEST		 INTEGER,
    PORTAL_USAGE_OTHER 			 INTEGER,
    CREATE_BY					 VARCHAR2(50 BYTE),
    CREATE_DATE				 DATE,
    LAST_UPDATE_BY				 VARCHAR2(50 BYTE),
    LAST_UPDATE_DATE				 DATE,
    CONSTRAINT
   	   pk_portal_usage_id
   PRIMARY KEY (PORTAL_USAGE_ID)
   )TABLESPACE MAXDAT_DATA;

CREATE OR REPLACE VIEW TS_PORTAL_USAGE_SV AS
    select
    PORTAL_USAGE_ID,
    PORTAL_LANGUAGE,
    PORTAL_USAGE_DATETIME,
    PORTAL_USAGE_TEST_CONTACT,
    PORTAL_USAGE_FAX_ASSISTANCE,
    PORTAL_USAGE_ENROLLMENT_ASSISTANCE,
    PORTAL_USAGE_DISENROLLMENT_ASSISTANCE,
    PORTAL_USAGE_PACKET_REQUEST,
    PORTAL_USAGE_OTHER,
    CREATE_BY,
    CREATE_DATE
    LAST_UPDATE_BY,
    LAST_UPDATE_DATE
    from TS_PORTAL_USAGE;

/*Grant privileges to Sequence*/
CREATE SEQUENCE  "SEQ_PORTAL_AVAILABILTY_ID"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 265 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
Grant SELECT ON  SEQ_PORTAL_AVAILABILTY_ID TO MAXDAT_MSTR_TRX_RPT;
CREATE SEQUENCE  "SEQ_PORTAL_USAGE_ID"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 265 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
Grant SELECT ON  SEQ_PORTAL_USAGE_ID TO MAXDAT_MSTR_TRX_RPT;

/*Grants - to allow MSTR Transactions to perform U,D,I*/
GRANT select on TS_PORTAL_AVAILABILTY_SV to MAXDAT_READ_ONLY; 
GRANT select on TS_PORTAL_USAGE_SV to MAXDAT_READ_ONLY;
GRANT insert, update ON TS_PORTAL_AVAILABILTY TO MAXDAT_MSTR_TRX_RPT;
GRANT insert, update ON TS_PORTAL_USAGE TO MAXDAT_MSTR_TRX_RPT;

/*Create individual indexes on columns of TS_PORTAL_AVAILABILTY below*/

CREATE INDEX MAXDAT.IN_PORTAL_DOWNTIME ON TS_PORTAL_AVAILABILTY(PORTAL_DOWNTIME) TABLESPACE MAXDAT_INDX;

CREATE INDEX IN_PORTAL_LANGUAGE ON TS_PORTAL_USAGE(PORTAL_LANGUAGE) TABLESPACE MAXDAT_INDX;
/