use UK_HWS
go

DROP VIEW MAXDAT.CC_D_ACTIVITY_TYPE_SV;
DROP VIEW MAXDAT.CC_D_AGENT_SV;
DROP VIEW MAXDAT.CC_D_CONTACT_QUEUE_SV;
DROP VIEW MAXDAT.CC_D_DATES_SV;
DROP VIEW MAXDAT.CC_D_FORECAST_NOTES_SV;
DROP VIEW MAXDAT.CC_D_GEOGRAPHY_MASTER_SV;
DROP VIEW MAXDAT.CC_D_GROUP_SV;
DROP VIEW MAXDAT.CC_D_INTERVAL_SV;
DROP VIEW MAXDAT.CC_D_IVR_SELF_SERVICE_PATH_SV;
DROP VIEW MAXDAT.CC_D_MANAGER_SV;
DROP VIEW MAXDAT.CC_D_PRODUCTION_PLAN_HORIZN_SV;
DROP VIEW MAXDAT.CC_D_PRODUCTION_PLAN_SV;
DROP VIEW MAXDAT.CC_D_PROGRAM_SV;
DROP VIEW MAXDAT.CC_D_PROJECT_SV;
DROP VIEW MAXDAT.CC_D_PROJECT_TARGETS_SV;
DROP VIEW MAXDAT.CC_D_SITE_SV;
DROP VIEW MAXDAT.CC_D_SUPERVISOR_SV;
DROP VIEW MAXDAT.CC_D_UNIT_OF_WORK_SV;
DROP VIEW MAXDAT.CC_F_ACTUALS_IVR_INTERVAL_SV;
DROP VIEW MAXDAT.CC_F_ACTUALS_QUEUE_INTERVAL_SV;
DROP VIEW MAXDAT.CC_F_AGENT_ACTIVITY_BY_DATE_SV;
DROP VIEW MAXDAT.CC_F_AGENT_BY_DATE_SV;
DROP VIEW MAXDAT.CC_F_FORECAST_INTERVAL_SV;
DROP VIEW MAXDAT.CC_F_IVR_SELF_SERVICE_USAGE_SV;


DROP TABLE MAXDAT.CC_F_ACTUALS_IVR_INTERVAL;
DROP TABLE MAXDAT.CC_F_ACTUALS_QUEUE_INTERVAL;
DROP TABLE MAXDAT.CC_F_AGENT_ACTIVITY_BY_DATE;
DROP TABLE MAXDAT.CC_F_AGENT_BY_DATE;
DROP TABLE MAXDAT.CC_F_FORECAST_INTERVAL;
DROP TABLE MAXDAT.CC_F_IVR_SELF_SERVICE_USAGE;
DROP TABLE MAXDAT.CC_D_ACTIVITY_TYPE;
DROP TABLE MAXDAT.CC_D_AGENT;
DROP TABLE MAXDAT.CC_D_CONTACT_QUEUE;
DROP TABLE MAXDAT.CC_D_DATES;
DROP TABLE MAXDAT.CC_D_FORECAST_NOTES;
DROP TABLE MAXDAT.CC_D_GROUP;
DROP TABLE MAXDAT.CC_D_INTERVAL;
DROP TABLE MAXDAT.CC_D_IVR_SELF_SERVICE_PATH;
DROP TABLE MAXDAT.CC_D_PRODUCTION_PLAN_HORIZON;
DROP TABLE MAXDAT.CC_D_PROD_PLANNING_TARGET;
DROP TABLE MAXDAT.CC_D_SITE;
DROP TABLE MAXDAT.CC_D_TARGET;
DROP TABLE MAXDAT.CC_D_UNIT_OF_WORK;
DROP TABLE MAXDAT.CC_D_PRODUCTION_PLAN;
DROP TABLE MAXDAT.CC_D_GEOGRAPHY_MASTER;
DROP TABLE MAXDAT.CC_D_PROJECT_TARGETS;
DROP TABLE MAXDAT.CC_D_PROGRAM;
DROP TABLE MAXDAT.CC_D_PROJECT;
DROP TABLE MAXDAT.CC_D_PROVINCE;
DROP TABLE MAXDAT.CC_D_REGION;
DROP TABLE MAXDAT.CC_D_STATE;
DROP TABLE MAXDAT.CC_D_COUNTRY;
DROP TABLE MAXDAT.CC_D_DISTRICT;
