--NYHIX60241
SET DEFINE OFF;
INSERT INTO DP_SCORECARD.Engage_Form_Type VALUES (826,'QC_NYSOH_CC_Individual Marketplace_v6.1','QC','CC','script',SYSDATE,TO_DATE('09/08/2020','MM/DD/YY HH:MI:SS AM'),'');
COMMIT;