--------------------------------------------------------
--  File created - Thursday-September-24-2020   
--------------------------------------------------------
REM INSERTING into DP_SCORECARD.ENGAGE_FORM_TYPE
SET DEFINE OFF;
Insert into DP_SCORECARD.ENGAGE_FORM_TYPE (FORM_TYPE_ID,EVALUATION_FORM,SCORECARD_SCORE_TYPE,SCORECARD_GROUP,CREATE_BY,CREATE_DATETIME,START_DATE,END_DATE) values (827,'QC_NYSOH_Team Lead_v1.0','QC','Team Leads','script',to_date('24-SEP-20 12.00.00','DD-MON-YY HH.MI.SS'),to_date('01-SEP-20 12.00.00','DD-MON-YY HH.MI.SS'),null);

Commit;


