declare  c int;
begin
   select count(*) into c from user_tables where table_name ='FORM_TYPE_CHANGE_HISTORY_STG';
   if c = 1 then
      execute immediate 'drop table FORM_TYPE_CHANGE_HISTORY_STG cascade constraints';
   end if;
end;
/ 

CREATE TABLE MAXDAT.FORM_TYPE_CHANGE_HISTORY_STG
    (
      FORM_TYPE_CHANGE_HISTORY_ID NUMBER (18)
    , ECN                         VARCHAR2 (256)
    , DCN                         VARCHAR2 (32)
    , APP_DOC_DATA_ID             NUMBER (18)
    , OLD_DOCUMENT_TYPE           VARCHAR2 (32)
    , NEW_DOCUMENT_TYPE           VARCHAR2 (32)
    , OLD_DOCUMENT_SUB_TYPE       VARCHAR2 (32)
    , NEW_DOCUMENT_SUB_TYPE       VARCHAR2 (32)
    , OLD_KOFAX_DCN               VARCHAR2 (50)
    , NEW_KOFAX_DCN               VARCHAR2 (50)
    , CREATED_TS                  DATE
    , CREATED_BY                  VARCHAR2 (80)
    )
    TABLESPACE MAXDAT_DATA
    STORAGE (BUFFER_POOL DEFAULT);

CREATE INDEX IDX_FORM_TYPE_CHANGE_HIST_ID
    ON MAXDAT.FORM_TYPE_CHANGE_HISTORY_STG (FORM_TYPE_CHANGE_HISTORY_ID)
    TABLESPACE MAXDAT_INDX;

GRANT SELECT ON MAXDAT.FORM_TYPE_CHANGE_HISTORY_STG TO MAXDAT_READ_ONLY;
GRANT SELECT ON MAXDAT.FORM_TYPE_CHANGE_HISTORY_STG TO DP_SCORECARD;

declare  c int;
begin
   select count(*) into c from user_tables where table_name ='NYHBE_RECONCILIATION_DATA_STG';
   if c = 1 then
      execute immediate 'drop table NYHBE_RECONCILIATION_DATA_STG cascade constraints';
   end if;
end;
/ 

CREATE TABLE MAXDAT.NYHBE_RECONCILIATION_DATA_STG
    (
      NYHBE_RECONCILIATION_DATA_ID NUMBER (18) NOT NULL
    , PERSON_ID                    NUMBER (4)
    , MEMBER_ID                    VARCHAR2 (30)
    , ACCOUNT_ID                   VARCHAR2 (30)
    , BATCH_RUN_DATE               DATE
    , KOFAX_DCN                    VARCHAR2 (50)
    , DOC_STATUS                   VARCHAR2 (32)
    , ECN                          VARCHAR2 (256)
    , DMS_DCN                      VARCHAR2 (32)
    , ZIP_FILE_NAME                VARCHAR2 (256)
    , DOCUMENT_TYPE                VARCHAR2 (32)
    , FORM_TYPE                    VARCHAR2 (32)
    , CREATED_BY                   VARCHAR2 (50)
    , CREATE_TS                    DATE
    , UPDATED_BY                   VARCHAR2 (50)
    , UPDATE_TS                    DATE,
    CONSTRAINT NYHBE_RECONCILIATION_DATA_PK PRIMARY KEY (NYHBE_RECONCILIATION_DATA_ID)
    )
    TABLESPACE MAXDAT_DATA
    STORAGE (BUFFER_POOL DEFAULT);

CREATE INDEX IDX_NYHBE_RECONC_DATA_ECNDCN
    ON MAXDAT.NYHBE_RECONCILIATION_DATA_STG (DMS_DCN, ECN)
    TABLESPACE MAXDAT_INDX;

CREATE INDEX IDX_NYHBE_RECONC_DATA_ECNKDCN
    ON MAXDAT.NYHBE_RECONCILIATION_DATA_STG (KOFAX_DCN, ECN)
    TABLESPACE MAXDAT_INDX;

GRANT SELECT ON MAXDAT.NYHBE_RECONCILIATION_DATA_STG TO MAXDAT_READ_ONLY;
GRANT SELECT ON MAXDAT.NYHBE_RECONCILIATION_DATA_STG TO DP_SCORECARD;
