ALTER SESSION SET CURRENT_SCHEMA = CISCO_ENTERPRISE_CC;

INSERT INTO CC_HCO_F_V2_CALL( F_V2_CALL_ID,
                ACTIVITY_ID,
                AGENT_LOGIN_ID,
                ANI_PHONE_NUMBER,
                CALLGUID,
                CALLTYPE_REPORTING_DATETIME,
                CALL_ABANDONED_FLAG,
                CALL_ANSWERED_FLAG,
                CALL_BUSY_FLAG,
                CALL_DIAL_METHOD,
                CALL_DISPOSITION,
                CALL_DISPOSITION_DESC,
                CALL_DISPOSITION_FLAG,
                CALL_DISPOSITION_FLG_DESC,
                CALL_DROPPED_FLAG,
                CALL_DURATION,
                CALL_HANDLE_METHOD,
                CALL_OFFERED_FLAG,
                CALL_REFERENCE_ID,
                CALL_SEGMENT_END_DT,
                CALL_SEGMENT_ID,
                CREATE_DATE,
                CUSTOMER_ACCOUNT_NUMBER,
                DATETIME,
                DELAY_TIME_SECONDS,
                DIGITS_DIALED,
                DNIS,
                D_AGENT_ID,
                D_CONTACT_QUEUE_ID,
                D_DATE_ID,
                D_PROGRAM_ID,
                D_PROJECT_ID,
                HOLD_TIME_SECONDS,
                IVR_TIME_SECONDS,
                LANGUAGE,
                LAST_UPDATED_BY,
                LAST_UPDATE_DATE,
                LOCAL_Q_TIME_SECONDS,
                NETWORK_TIME_SECONDS,
                PERIPHERAL_CALL_KEY,
                PERIPHERAL_CALL_TYPE,
                PERIPHERAL_ID,
                PRECISION_QUEUE_ID,
                QUEUE_NUMBER,
                QUEUE_TIME_SECONDS,
                RING_TIME_SECONDS,
                ROUTER_CALL_KEY,
                ROUTER_CALL_KEY_DAY,
                SKILL_GROUP_ID,
                SOURCE_AGENT_LOGIN_ID,
                SOURCE_CALL_ID,
                SOURCE_D_AGENT_ID,
                TALK_TIME_SECONDS,
                TIME_TO_ABAND_SECONDS,
                TRANSFER_TO,
                VOICEMAIL_FLAG,
                WORK_TIME_SECONDS,
                XFERRED_OUT_FLAG
            )
SELECT   A.F_V2_CALL_ID,
            A.ACTIVITY_ID,
            A.AGENT_LOGIN_ID,
            A.ANI_PHONE_NUMBER,
            A.CALLGUID,
            A.CALLTYPE_REPORTING_DATETIME,
            A.CALL_ABANDONED_FLAG,
            A.CALL_ANSWERED_FLAG,
            A.CALL_BUSY_FLAG,
            A.CALL_DIAL_METHOD,
            A.CALL_DISPOSITION,
            A.CALL_DISPOSITION_DESC,
            A.CALL_DISPOSITION_FLAG,
            A.CALL_DISPOSITION_FLG_DESC,
            A.CALL_DROPPED_FLAG,
            A.CALL_DURATION,
            A.CALL_HANDLE_METHOD,
            A.CALL_OFFERED_FLAG,
            A.CALL_REFERENCE_ID,
            A.CALL_SEGMENT_END_DT,
            A.CALL_SEGMENT_ID,
            A.CREATE_DATE,
            A.CUSTOMER_ACCOUNT_NUMBER,
            A.DATETIME,
            A.DELAY_TIME_SECONDS,
            A.DIGITS_DIALED,
            A.DNIS,
            A.D_AGENT_ID,
            A.D_CONTACT_QUEUE_ID,
            A.D_DATE_ID,
            A.D_PROGRAM_ID,
            A.D_PROJECT_ID,
            A.HOLD_TIME_SECONDS,
            A.IVR_TIME_SECONDS,
            A.LANGUAGE,
            A.LAST_UPDATED_BY,
            A.LAST_UPDATE_DATE,
            A.LOCAL_Q_TIME_SECONDS,
            A.NETWORK_TIME_SECONDS,
            A.PERIPHERAL_CALL_KEY,
            A.PERIPHERAL_CALL_TYPE,
            A.PERIPHERAL_ID,
            A.PRECISION_QUEUE_ID,
            A.QUEUE_NUMBER,
            A.QUEUE_TIME_SECONDS,
            A.RING_TIME_SECONDS,
            A.ROUTER_CALL_KEY,
            A.ROUTER_CALL_KEY_DAY,
            A.SKILL_GROUP_ID,
            A.SOURCE_AGENT_LOGIN_ID,
            A.SOURCE_CALL_ID,
            A.SOURCE_D_AGENT_ID,
            A.TALK_TIME_SECONDS,
            A.TIME_TO_ABAND_SECONDS,
            A.TRANSFER_TO,
            A.VOICEMAIL_FLAG,
            A.WORK_TIME_SECONDS,
            A.XFERRED_OUT_FLAG
            FROM CC_F_V2_CALL_SV A, CC_D_PROJECT B
WHERE A.D_PROJECT_ID = B.PROJECT_ID
AND B.PROJECT_NAME = 'CA HCO';

insert into cc_a_list_lkup (name, list_type, value, out_var, ref_id, start_date, end_date, comments)
values ('CAHCO_V2_CALL_UPDATE_DATE', 'CAHCO_V2_CALL_UPDATE_DATE', 'CA HCO', sysdate+1, 1, sysdate, to_date('12/31/2999', 'mm/dd/yyyy'), 'Date of last update for HCO_V2_F_CALL table');

COMMIT;

