create or replace view CORP_ETL_JOB_STATISTICS_SV as 
select 
 JOB_ID 
,PARENT_JOB_ID 
,JOB_NAME 
,JOB_STATUS_CD 	
,FILE_NAME  	
,RECORD_COUNT  	
,PROCESSED_COUNT  	
,ERROR_COUNT  	
,WARNING_COUNT  	
,RECORD_INSERTED_COUNT  	
,RECORD_UPDATED_COUNT  	
,JOB_START_DATE 	
,JOB_END_DATE 	
 from CORP_ETL_JOB_STATISTICS;

grant select on CORP_ETL_JOB_STATISTICS_SV to MAXDAT_READ_ONLY;

create or replace public synonym CORP_ETL_JOB_STATISTICS_SV for CORP_ETL_JOB_STATISTICS_SV;