-- Unable to render VIEW DDL for object MAXDAT.D_PL_CURRENT_SV with DBMS_METADATA attempting internal generator.
CREATE OR REPLACE VIEW D_TEAMS_SV
AS select T.TEAM_ID
,T.TEAM_NAME
,T.TEAM_DESCRIPTION
,T.TEAM_SUPERVISOR_STAFF_ID
,G.BUSINESS_UNIT_ID
,G.BUSINESS_UNIT
from D_TEAMS T
left join (SELECT G.GROUP_ID TEAM_ID, G1.GROUP_ID BUSINESS_UNIT_ID, G1.GROUP_NAME BUSINESS_UNIT
FROM GROUPS_STG G
LEFT JOIN GROUPS_STG G1
ON G.PARENT_GROUP_ID = G1.GROUP_ID
WHERE G.PARENT_GROUP_ID IS NOT NULL) G
on T.TEAM_ID = G.TEAM_ID 
WITH READ ONLY;


