/*
Created on 18-Jun-2013 by Raj A. 
Process: Manage Enrollment Activity.

Description:
Populate BPM_ATTRIBUTE table used to map attribute definitions to a process.

This script populates the BPM_ATTRIBUTE table for the Manage enrollment activity process.
*/
--Client Enroll Status ID
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1773,723,14,'CREATE',sysdate,BPM_COMMON.GET_MAX_DATE,'N');
--Client CIN
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1774,724,14,'CREATE',sysdate,BPM_COMMON.GET_MAX_DATE,'N');
--Service Area
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1775,725,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--ZIP Code
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1776,726,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Enrollment Status Code
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1777,727,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'Y'); 
--Enrollment Status Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1778,728,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'Y'); 
--Auto-Assign Due Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1779,729,14,'CREATE',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-----------------------
--Enrollment Packet Request ID
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1693,730,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Enrollment Packet Request Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1694,731,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Enrollment Fee Amount Due
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1695,732,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Enrollment Fee Amount Paid
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1696,733,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Enrollment Fee Received Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1697,734,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- CHIP Plan Change Notice ID
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1698,735,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- CHIP Plan Change Mailed Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1699,736,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- CHIP Enroll MI Notice ID
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1700,737,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- CHIP Enroll MI Sent Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1701,738,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Plan Type
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1702,739,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Program Type
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1703,740,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Selection Method
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1704,741,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Selection Created by Name
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1705,742,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Selection Create Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1706,743,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Selection Last Update by 
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1707,744,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Selection Last Update DatE
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1708,745,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Selection Auto Processed
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1709,746,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Generic Field 1
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1710,747,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Generic Field 2
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1711,748,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Generic Field 3
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1712,749,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Generic Field 4
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1713,750,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Generic Field 5
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1714,751,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--------------ASSD and ASED attributes.--------------
-- Valid Slcn Received Start Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1715,752,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Valid Slcn Received End Dt
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1716,753,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Send Enroll Packet Start Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1717,754,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Send Enroll Packet End Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1718,755,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- First Follow-up ID 
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1719,756,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- First Followup Type Code
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1720,757,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- First Follow-up Start Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1721,758,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- First Follow-up End Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1722,759,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Second Follow-up ID
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1723,760,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Second Followup Type Code
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1724,761,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Second Follow-up Start Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1725,762,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Second Follow-up End Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1726,763,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Third Follow-up ID
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1727,764,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Third Followup Type Code
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1728,765,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Third Follow-up Start Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1729,766,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Third Follow-up End Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1730,767,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Fourth Follow-up ID
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1731,768,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Fourth Followup Type Code
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1732,769,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Fourth Follow-up Start Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1733,770,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Fourth Follow-up End Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1734,771,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Auto Assign Start Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1735,772,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Auto Assign End Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1736,773,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Wait for Enroll Fee Start DatE
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1737,774,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Wait for Enroll Fee End Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1738,775,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Cancel Enroll Activity Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1739,776,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-- Cancelled By
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1740,777,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
------------------------------------------
-----Attributes that already exist. CREATE
--Client ID
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1741,593,14,'CREATE',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Create Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1742,7,14,'CREATE',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Case ID
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1743,479,14,'CREATE',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Newborn Flag
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1744,575,14,'CREATE',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
-----Attributes that already exist. BOTH
--Age_in_business_days
--insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1745,1,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Age_in_calendar_days
--insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1746,2,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--County Code
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1747,557,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Instance Status
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1748,66,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Complete Date
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1749,5,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N');  
--Cancel Reason
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1750,547,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Cancel Method
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1751,722,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
------ASF Attributes
--Send Enroll Packet Flag. ASF
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1752,778,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Selections Received Flag. ASF
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1753,779,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--First Follow-up Complete Flag. ASF
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1754,780,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Second Follow-up Complete Flag. ASF
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1755,781,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Third Follow-up Complete Flag. ASF
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1756,782,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Fourth Follow-up Complete Flag. ASF
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1757,783,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Auto Assign Flag. ASF
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1758,784,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Wait for Fee Flag. ASF
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1759,785,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
------GWF Attributes
--Enroll Packet Required Flag. GWF
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1760,786,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--First Follow-up Required Flag. GWF
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1761,787,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Second Follow-up Required Flag. GWF
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1762,788,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Third Follow-up Required Flag. GWF
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1763,789,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Fourth Follow-up Required Flag. GWF
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1764,790,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
--Required Fee Paid Flag. GWF
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1765,791,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N');


--Cancel Enroll Activity Flag. ASF
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (1766,792,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N'); 
Insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE,RETAIN_HISTORY_FLAG) values (2182,807,14,'BOTH',sysdate,BPM_COMMON.GET_MAX_DATE,'N');

commit;
