--MAXDAT-3473

ALTER SESSION SET CURRENT_SCHEMA = MAXDAT_KSCH_LEGACY;

ALTER TABLE CC_S_ACD_INTERVAL ADD (MAX_CALLS_QUEUED NUMBER (7));

ALTER TABLE CC_S_ACD_QUEUE_INTERVAL ADD (MAX_CALLS_QUEUED NUMBER (7));

ALTER TABLE CC_F_ACTUALS_QUEUE_INTERVAL ADD (MAX_CALLS_QUEUED NUMBER (7));

ALTER TABLE CC_F_ACD_QUEUE_INTERVAL ADD (MAX_CALLS_QUEUED NUMBER (7));

CREATE OR REPLACE VIEW CC_F_ACTUALS_QUEUE_INTERVAL_SV  AS
SELECT CC_F_ACTUALS_QUEUE_INTERVAL.* FROM CC_F_ACTUALS_QUEUE_INTERVAL ;

CREATE OR REPLACE VIEW CC_F_ACD_QUEUE_INTERVAL_SV  AS
SELECT CC_F_ACD_QUEUE_INTERVAL.* FROM CC_F_ACD_QUEUE_INTERVAL ;