CREATE TABLE MAXDAT.EMRS_D_PLAN
    (
      PLAN_ID               INTEGER NOT NULL
    , MANAGED_CARE_PROGRAM  VARCHAR2 (50) NOT NULL
    , CSDA                  VARCHAR2 (32)
    , PLAN_CODE             VARCHAR2 (32) NOT NULL
    , PLAN_NAME             VARCHAR2 (64) NOT NULL
    , PLAN_ABBREVIATION     VARCHAR2 (64)
    , PLAN_EFFECTIVE_DATE   DATE
    , ADDRESS1              VARCHAR2 (55)
    , ADDRESS2              VARCHAR2 (55)
    , CITY                  VARCHAR2 (20)
    , STATE                 VARCHAR2 (2)
    , ZIP                   VARCHAR2 (9)
    , ACTIVE                VARCHAR2 (1)
    , CONTACT_FIRST_NAME    VARCHAR2 (30)
    , CONTACT_INITIAL       VARCHAR2 (1)
    , CONTACT_LAST_NAME     VARCHAR2 (30)
    , CONTACT_FULL_NAME     VARCHAR2 (80)
    , CONTACT_PHONE         VARCHAR2 (12)
    , CONTACT_EXTENSION     VARCHAR2 (6)
    , MEMBER_CONTACT_PHONE  VARCHAR2 (12)
    , ENROLLOK              VARCHAR2 (1)
    , PLAN_ASSIGN           VARCHAR2 (1)
    , RECORD_DATE           DATE
    , RECORD_TIME           VARCHAR2 (5)
    , RECORD_NAME           VARCHAR2 (80)
    , SOURCE_RECORD_ID      NUMBER (22)
    , PLAN_TYPE_ID          NUMBER (22)
    , PLAN_WEBSITE          VARCHAR2 (2000)
    , CONTACT_EMAIL_ADDRESS VARCHAR2 (256)
    , PLAN_SERVICE_TYPE     VARCHAR2 (20)
    , PLAN_ID_EXT           VARCHAR2 (32),
    CONSTRAINT PLAN_PK PRIMARY KEY (PLAN_ID),
    CONSTRAINT PLAN_PLAN_COMB_UK UNIQUE (SOURCE_RECORD_ID, CSDA, MANAGED_CARE_PROGRAM),
    CONSTRAINT PLAN_TYPE_FK FOREIGN KEY (PLAN_TYPE_ID) REFERENCES MAXDAT.EMRS_D_PLAN_TYPE (PLAN_TYPE_ID)
    )
    TABLESPACE MAXDAT_DATA
    STORAGE (BUFFER_POOL DEFAULT);
/

COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.PLAN_ID IS 'Plan (PK)';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.MANAGED_CARE_PROGRAM IS 'Managed Care Program that Uses this Plan';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.CSDA IS 'Plan Service Delivery Area';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.PLAN_CODE IS 'Plan Code';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.PLAN_NAME IS 'Plan Name';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.PLAN_ABBREVIATION IS 'Plan Name Abbreviation';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.PLAN_EFFECTIVE_DATE IS 'Plan Effective Date';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.ADDRESS1 IS 'Plan Address1';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.ADDRESS2 IS 'Plan Address2';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.CITY IS 'Plan City';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.STATE IS 'Plan State';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.ZIP IS 'Plan Zip Code';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.ACTIVE IS 'Plan Activated';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.CONTACT_FIRST_NAME IS 'MAXIMUS Contact First Name';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.CONTACT_INITIAL IS 'MAXIMUS Contact Middle Initial';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.CONTACT_LAST_NAME IS 'MAXIMUS Contact Last Name';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.CONTACT_FULL_NAME IS 'MAXIMUS Contact First, Last Name';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.CONTACT_PHONE IS 'MAXIMUS Contact Phone Number';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.CONTACT_EXTENSION IS 'MAXIMUS Contact Phone Extension';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.MEMBER_CONTACT_PHONE IS 'Member Contact Phone Number';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.ENROLLOK IS 'OK To Enroll';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.PLAN_ASSIGN IS 'Use In Assignment (Y;N)';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.RECORD_DATE IS 'Record Creation Date';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.RECORD_TIME IS 'Record Creation Time';
COMMENT ON COLUMN MAXDAT.EMRS_D_PLAN.RECORD_NAME IS 'Record Created By';
CREATE INDEX IDX_EMRSPLAN1
    ON MAXDAT.EMRS_D_PLAN (PLAN_CODE)
    TABLESPACE MAXDAT_INDX;

CREATE INDEX IDX_EMRSPLAN2
    ON MAXDAT.EMRS_D_PLAN (CSDA)
    TABLESPACE MAXDAT_INDX;

CREATE INDEX IDX_EMRSPLAN3
    ON MAXDAT.EMRS_D_PLAN (MANAGED_CARE_PROGRAM)
    TABLESPACE MAXDAT_INDX;



GRANT SELECT ON MAXDAT.EMRS_D_PLAN TO MAXDAT_READ_ONLY;

