insert into BPM_EVENT_MASTER (BEM_ID,BRL_ID,BPRJ_ID,BPRG_ID,BPROL_ID,NAME,DESCRIPTION,EFFECTIVE_DATE,END_DATE) 
values (1,4,10,1,1,'Exeter WorkQWEST','Exeter-UK Manage Work',sysdate,BPM_COMMON.GET_MAX_DATE);

commit;