select
	(select count(*) from raw.audio_quality where projectid = 801) as audio_quality_cnt,
	(select count(*) from raw.billable_usage where projectid = 801) as billable_usage_cnt,
	(select count(*) from raw.configuration_objects where projectid = 801) as configuration_objects_cnt,
	(select count(*) from raw.contact_center_settings where projectid = 801) as contact_center_settings_cnt,
	(select count(*) from raw.conversations where projectid = 801) as conversations_cnt,
	(select count(*) from raw.conversations_detail where projectid = 801) as conversations_detail_cnt,
	(select count(*) from raw.conversations_summary where projectid = 801) as conversations_summary_cnt,
	(select count(*) from raw.conversation_attributes where projectid = 801) as conversations_attributes_cnt,
	(select count(*) from raw.dialer_detail where projectid = 801) as dialer_detail_cnt,
    (select count(*) from raw.dialer_preview_detail where projectid = 801) as dialer_preview_detail_cnt,
    (select count(*) from raw.divisions where projectid = 801) as divisions_cnt,
    (select count(*) from raw.evaluations where projectid = 801) as evaluations_cnt,
    (select count(*) from raw.evaluation_calibrations where projectid = 801) as evaluation_calibrations_cnt,
    (select count(*) from raw.evaluation_forms where projectid = 801) as evaluation_forms_cnt,-- what is the source of this data?
    (select count(*) from raw.flow_outcomes where projectid = 801) as flow_outcomes_cnt,
    (select count(*) from  where projectid = 801) as groups_membership_cnt,
    (select count(*) from raw.participants where projectid = 801) as participants_cnt,
    (select count(*) from raw.primary_presence where projectid = 801) as primary_presence_cnt,
    (select count(*) from raw.queues_membership where projectid = 801) as queues_membership_cnt,
    (select count(*) from raw.queue_configuration where projectid = 801) as queue_configuration_cnt,
    (select count(*) from raw.queue_interval_aggregates where projectid = 801) as queue_interval_aggregates_cnt,
    (select count(*) from raw.routing_status where projectid = 801) as routing_status_cnt,
    (select count(*) from raw.segments where projectid = 801) as segments_cnt,
    (select count(*) from raw.sessions where projectid = 801) as sessions_cnt,
    (select count(*) from raw.session_summary where projectid = 801) as session_summary_cnt,
    (select count(*) from raw.user_details where projectid = 801) as user_details_cnt,
    (select count(*) from raw.user_locations where projectid = 801) as user_locations_cnt,
    (select count(*) from raw.user_roles where projectid = 801) as user_roles_cnt,
    (select count(*) from raw.user_skills where projectid = 801) as user_skills_cnt,
    (select count(*) from raw.wfm_activity_codes where projectid = 801) as wfm_activity_codes_cnt,
    (select count(*) from raw.wfm_day_metrics where projectid = 801) as wfm_day_metrics_cnt                                                                
from
	dual;