use role SYSADMIN;
use warehouse PUREINSIGHTS_DEV_LOAD_DAILY_WH;
use database PUREINSIGHTS_DEV;
use schema PUBLIC;

SELECT 
	COUNT(*)
FROM
(
		SELECT 
			D.PROJECTID  					AS 	D_PROJECTID,
			P.PROJECTID  					AS 	P_PROJECTID,
			D.CONVERSATIONID 				AS	D_CONVERSATIONID,
			P.CONVERSATIONID				AS  P_CONVERSATIONID,
			D.SENTIMENTSCORE    			AS 	D_SENTIMENTSCORE,
			P.SENTIMENTSCORE				AS	P_SENTIMENTSCORE,
			D.SENTIMENTTREND 				AS	D_SENTIMENTTREND,
			P.SENTIMENTTREND				AS	P_SENTIMENTTREND,
			D.CONVERSATIONSTARTTIME 		AS	D_CONVERSATIONSTARTTIME,
			P.CONVERSATIONSTARTTIME			AS	P_CONVERSATIONSTARTTIME,
			D.CONVERSATIONSTARTDATE 		AS	D_CONVERSATIONSTARTDATE,
			P.CONVERSATIONSTARTDATE			AS	P_CONVERSATIONSTARTDATE,
			D.PROJECTCONVERSATIONSTARTTIME 	AS	D_PROJECTCONVERSATIONSTARTTIME,
			P.PROJECTCONVERSATIONSTARTTIME	AS	P_PROJECTCONVERSATIONSTARTTIME,
			D.PROJECTCONVERSATIONSTARTDATE 	AS	D_PROJECTCONVERSATIONSTARTDATE,
			P.PROJECTCONVERSATIONSTARTDATE	AS	P_PROJECTCONVERSATIONSTARTDATE,
			D.CONVERSATIONENDTIME			AS	D_CONVERSATIONENDTIME,
			P.CONVERSATIONENDTIME			AS	P_CONVERSATIONENDTIME,
			D.CONVERSATIONENDDATE 			AS	D_CONVERSATIONENDDATE,
			P.CONVERSATIONENDDATE			AS	P_CONVERSATIONENDDATE,
			D.PROJECTCONVERSATIONENDTIME	AS	D_PROJECTCONVERSATIONENDTIME,
			P.PROJECTCONVERSATIONENDTIME	AS	P_PROJECTCONVERSATIONENDTIME,
			D.PROJECTCONVERSATIONENDDATE 	AS	D_PROJECTCONVERSATIONENDDATE,
			P.PROJECTCONVERSATIONENDDATE	AS	P_PROJECTCONVERSATIONENDDATE,
			D.DURATION						AS	D_DURATION,
			P.DURATION						AS	P_DURATION,
			D.AGENTTALKDURATION				AS	D_AGENTTALKDURATION,
			P.AGENTTALKDURATION				AS	P_AGENTTALKDURATION,	
			D.CUSTOMERTALKDURATION			AS	D_CUSTOMERTALKDURATION,
			P.CUSTOMERTALKDURATION			AS	P_CUSTOMERTALKDURATION,
			D.SILENCEDURATION				AS	D_SILENCEDURATION,
			P.SILENCEDURATION				AS	P_SILENCEDURATION,
			D.IVRDURATION					AS	D_IVRDURATION,
			P.IVRDURATION					AS	P_IVRDURATION,
			D.ACDDURATION 					AS	D_ACDDURATION,
			P.ACDDURATION					AS	P_ACDDURATION,
			D.OVERTALKDURATION				AS	D_OVERTALKDURATION,
			P.OVERTALKDURATION				AS	P_OVERTALKDURATION,
			D.OVERTALKCOUNT					AS	D_OVERTALKCOUNT,
			P.OVERTALKCOUNT					AS	P_OVERTALKCOUNT,
			D.OTHERDURATION					AS	D_OTHERDURATION,
			P.OTHERDURATION					AS	P_OTHERDURATION,
			D.SENTIMENTTRENDCLASS			AS	D_SENTIMENTTRENDCLASS,
			P.SENTIMENTTRENDCLASS			AS	P_SENTIMENTTRENDCLASS
		FROM 
			PUREINSIGHTS_DEV.PUBLIC.F_PI_TRANSCRIPTION_CONVERSATION_SUMMARY_VW		D
		LEFT JOIN
			PUREINSIGHTS_PRD.PUBLIC.F_PI_TRANSCRIPTION_CONVERSATION_SUMMARY_VW		P 
		ON
		(
				D.projectid = p.projectid
			AND	D.conversationid = p.conversationid
		)
		WHERE 
		(
				D.PROJECTID != P.PROJECTID
			OR	D.CONVERSATIONID != P.conversationid
			OR	D.SENTIMENTSCORE != P.SENTIMENTSCORE
			OR  D.SENTIMENTTREND != P.SENTIMENTTREND
			OR  D.CONVERSATIONSTARTTIME != P.CONVERSATIONSTARTTIME
			OR  D.CONVERSATIONSTARTDATE != P.CONVERSATIONSTARTDATE
			OR  D.PROJECTCONVERSATIONSTARTTIME != P.PROJECTCONVERSATIONSTARTTIME
			OR	D.PROJECTCONVERSATIONSTARTDATE != P.PROJECTCONVERSATIONSTARTDATE
			OR  D.CONVERSATIONENDTIME != P.CONVERSATIONENDTIME
			OR  D.CONVERSATIONENDDATE != P.CONVERSATIONENDDATE
			OR 	D.PROJECTCONVERSATIONENDTIME != P.PROJECTCONVERSATIONENDTIME
			OR  D.PROJECTCONVERSATIONENDDATE != P.PROJECTCONVERSATIONENDDATE
			OR  D.DURATION != P.DURATION
			OR  D.AGENTTALKDURATION != P.AGENTTALKDURATION
			OR  D.CUSTOMERTALKDURATION != P.CUSTOMERTALKDURATION
			OR  D.SILENCEDURATION != P.SILENCEDURATION
			OR  D.IVRDURATION != P.IVRDURATION
			OR  D.ACDDURATION != P.ACDDURATION
			OR	D.OVERTALKDURATION != P.OVERTALKDURATION
			OR  D.OVERTALKCOUNT != P.OVERTALKCOUNT
			OR  D.OTHERDURATION != P.OTHERDURATION
			OR  D.SENTIMENTTRENDCLASS != P.SENTIMENTTRENDCLASS
		)
);	


SELECT 
	COUNT(*)
FROM
(
		SELECT 
			D.PROJECTID  					AS 	D_PROJECTID,
			P.PROJECTID  					AS 	P_PROJECTID,
			DP.PROJECTNAME					AS	D_PROJECTNAME,
			PP.PROJECTNAME					AS	P_PROJECTNAME,
			D.CONVERSATIONID 				AS	D_CONVERSATIONID,
			P.CONVERSATIONID				AS  P_CONVERSATIONID,
			D.SENTIMENTSCORE    			AS 	D_SENTIMENTSCORE,
			P.SENTIMENTSCORE				AS	P_SENTIMENTSCORE,
			D.SENTIMENTTREND 				AS	D_SENTIMENTTREND,
			P.SENTIMENTTREND				AS	P_SENTIMENTTREND,
			D.CONVERSATIONSTARTTIME 		AS	D_CONVERSATIONSTARTTIME,
			P.CONVERSATIONSTARTTIME			AS	P_CONVERSATIONSTARTTIME,
			D.CONVERSATIONSTARTDATE 		AS	D_CONVERSATIONSTARTDATE,
			P.CONVERSATIONSTARTDATE			AS	P_CONVERSATIONSTARTDATE,
			D.PROJECTCONVERSATIONSTARTTIME 	AS	D_PROJECTCONVERSATIONSTARTTIME,
			P.PROJECTCONVERSATIONSTARTTIME	AS	P_PROJECTCONVERSATIONSTARTTIME,
			D.PROJECTCONVERSATIONSTARTDATE 	AS	D_PROJECTCONVERSATIONSTARTDATE,
			P.PROJECTCONVERSATIONSTARTDATE	AS	P_PROJECTCONVERSATIONSTARTDATE,
			D.CONVERSATIONENDTIME			AS	D_CONVERSATIONENDTIME,
			P.CONVERSATIONENDTIME			AS	P_CONVERSATIONENDTIME,
			D.CONVERSATIONENDDATE 			AS	D_CONVERSATIONENDDATE,
			P.CONVERSATIONENDDATE			AS	P_CONVERSATIONENDDATE,
			D.PROJECTCONVERSATIONENDTIME	AS	D_PROJECTCONVERSATIONENDTIME,
			P.PROJECTCONVERSATIONENDTIME	AS	P_PROJECTCONVERSATIONENDTIME,
			D.PROJECTCONVERSATIONENDDATE 	AS	D_PROJECTCONVERSATIONENDDATE,
			P.PROJECTCONVERSATIONENDDATE	AS	P_PROJECTCONVERSATIONENDDATE,
			D.DURATION						AS	D_DURATION,
			P.DURATION						AS	P_DURATION,
			D.AGENTTALKDURATION				AS	D_AGENTTALKDURATION,
			P.AGENTTALKDURATION				AS	P_AGENTTALKDURATION,	
			D.CUSTOMERTALKDURATION			AS	D_CUSTOMERTALKDURATION,
			P.CUSTOMERTALKDURATION			AS	P_CUSTOMERTALKDURATION,
			D.SILENCEDURATION				AS	D_SILENCEDURATION,
			P.SILENCEDURATION				AS	P_SILENCEDURATION,
			D.IVRDURATION					AS	D_IVRDURATION,
			P.IVRDURATION					AS	P_IVRDURATION,
			D.ACDDURATION 					AS	D_ACDDURATION,
			P.ACDDURATION					AS	P_ACDDURATION,
			D.OVERTALKDURATION				AS	D_OVERTALKDURATION,
			P.OVERTALKDURATION				AS	P_OVERTALKDURATION,
			D.OVERTALKCOUNT					AS	D_OVERTALKCOUNT,
			P.OVERTALKCOUNT					AS	P_OVERTALKCOUNT,
			D.OTHERDURATION					AS	D_OTHERDURATION,
			P.OTHERDURATION					AS	P_OTHERDURATION,
			D.SENTIMENTTRENDCLASS			AS	D_SENTIMENTTRENDCLASS,
			P.SENTIMENTTRENDCLASS			AS	P_SENTIMENTTRENDCLASS
		FROM 
			PUREINSIGHTS_DEV.PUBLIC.F_PI_TRANSCRIPTION_CONVERSATION_SUMMARY_VW		D
		LEFT JOIN
			PUREINSIGHTS_PRD.PUBLIC.F_PI_TRANSCRIPTION_CONVERSATION_SUMMARY_VW		P 
		ON
		(
				D.projectid = p.projectid
			AND	D.conversationid = p.conversationid
		)
		LEFT JOIN 
			PUREINSIGHTS_DEV.PUBLIC.D_PI_PROJECTS		DP
		ON
		(
				D.PROJECTID = DP.PROJECTID
		)
		LEFT JOIN 
			PUREINSIGHTS_PRD.PUBLIC.D_PI_PROJECTS		PP
		ON
		(
				D.PROJECTID = PP.PROJECTID
		)		
		WHERE 
		(
				D.CONVERSATIONSTARTTIME != P.CONVERSATIONSTARTTIME
		)
);	

SELECT projectid, projectname, count(*) FROM PUREINSIGHTS_DEV.PUBLIC.F_PI_TRANSCRIPTION_CONVERSATION_SUMMARY_VW GROUP BY projectid, projectname;

		SELECT 
			CONVERSATIONID,
			SENTIMENTSCORE,
			SENTIMENTTREND,
			SENTIMENTTRENDCLASS,
			CONVERSATIONSTARTTIME,
			CONVERSATIONENDTIME,
			DURATION,
			AGENTTALKDURATION,
			CUSTOMERTALKDURATION,
			SILENCEDURATION,
			IVRDURATION,
			ACDDURATION,
			OVERTALKDURATION,
			OVERTALKCOUNT,
			OTHERDURATION		-
		FROM 
			PUREINSIGHTS_UAT.PUBLIC.F_PI_TRANSCRIPTION_CONVERSATION_SUMMARY_VW		D
		WHERE 
			D.PROJECTID = '6666'
		ORDER BY
			D.CONVERSATIONID;

select  Distinct ProjectId, ProjectName, CONVERSATIONID from PUREINSIGHTS_PRD.PUBLIC.f_pi_transcription_conversation_summary_vw where ConversationID not in (Select Distinct ConversationID from PUREINSIGHTS_UAT.PUBLIC.F_PI_TRANSCRIPTION_CONVERSATION_SUMMARY_VW);

select  Distinct Projectid, ProjectName from PUREINSIGHTS_PRD.PUBLIC.f_pi_transcription_conversation_summary_vw where ConversationID not in (Select Distinct ConversationID from PUREINSIGHTS_UAT.PUBLIC.F_PI_TRANSCRIPTION_CONVERSATION_SUMMARY_VW);

select  Distinct ProjectId, ProjectName, CONVERSATIONID from PUREINSIGHTS_PRD.PUBLIC.f_pi_transcription_conversation_summary_vw 
where ConversationID not in (Select Distinct ConversationID from PUREINSIGHTS_UAT.PUBLIC.F_PI_TRANSCRIPTION_CONVERSATION_SUMMARY_VW)
AND projectname = 'COVAC';

select  Distinct ProjectId, ProjectName, CONVERSATIONID from PUREINSIGHTS_PRD.PUBLIC.f_pi_transcription_conversation_summary_vw 
where ConversationID not in (Select Distinct ConversationID from PUREINSIGHTS_UAT.PUBLIC.F_PI_TRANSCRIPTION_CONVERSATION_SUMMARY_VW)
AND projectname = 'COVERVA';

select  Distinct ProjectId, ProjectName, CONVERSATIONID from PUREINSIGHTS_PRD.PUBLIC.f_pi_transcription_conversation_summary_vw 
where ConversationID not in (Select Distinct ConversationID from PUREINSIGHTS_UAT.PUBLIC.F_PI_TRANSCRIPTION_CONVERSATION_SUMMARY_VW)
AND projectname = 'NCEB';

select  Distinct ProjectId, ProjectName, CONVERSATIONID from PUREINSIGHTS_PRD.PUBLIC.f_pi_transcription_conversation_summary_vw 
where ConversationID not in (Select Distinct ConversationID from PUREINSIGHTS_UAT.PUBLIC.F_PI_TRANSCRIPTION_CONVERSATION_SUMMARY_VW)
AND projectname = 'PAIEB/CHC';

select  Distinct ProjectId, ProjectName, CONVERSATIONID from PUREINSIGHTS_PRD.PUBLIC.f_pi_transcription_conversation_summary_vw 
where ConversationID not in (Select Distinct ConversationID from PUREINSIGHTS_UAT.PUBLIC.F_PI_TRANSCRIPTION_CONVERSATION_SUMMARY_VW)
AND projectname = 'VT UI';

