-- Agent Routing Group semantic views by hour and date

  CREATE OR REPLACE FORCE VIEW CC_F_AGENT_RTG_GRP_BY_HOUR_SV (D_DATE_ID,INTERVAL_HOUR, D_AGENT_ID, AGENT_ROUTING_GROUP_ID, SUPERVISOR_D_AGENT_ID, MANAGER_D_AGENT_ID, D_PROJECT_ID, D_PROGRAM_ID, D_GEOGRAPHY_MASTER_ID, D_GROUP_ID, D_SITE_ID,AGENT_LOGIN_ID, SUPERVISOR_AGENT_LOGIN_ID, MANAGER_AGENT_LOGIN_ID,AGENT_ROUTING_GROUP_NUMBER, AGENT_ROUTING_GROUP_NAME, AGENT_ROUTING_GROUP_TYPE, HANDLE_CALLS_COUNT, HANDLE_TIME_SECONDS, INTERNAL_CALLS_COUNT, INTERNAL_SECONDS, EXTERNAL_CALLS_COUNT, EXTERNAL_SECONDS, HOLD_SECONDS, RING_SECONDS, TALK_SECONDS, WRAP_SECONDS,LOGIN_SECONDS, IDLE_SECONDS, NOT_READY_SECONDS, TALK_RESERVE_SECONDS, PREDICTIVE_TALK_SECONDS, PREVIEW_TALK_SECONDS, PREDICTIVE_CALLS_COUNT, PREVIEW_CALLS_COUNT, BREAK_TIME, CONSULTATION_TIME, WALKAWAY_TIME, BUSYONDNTIME, PAYROLL_COUNT, ATTRITED_COUNT,SHORT_CALLS,CALLS_RETURNED_TO_QUEUE)
AS
    SELECT 
      CC_F_AGENT_RTG_GRP_INTERVAL.D_DATE_ID,
      CC_D_INTERVAL.INTERVAL_START_HOUR,
      CC_F_AGENT_RTG_GRP_INTERVAL.D_AGENT_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_ROUTING_GROUP_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.SUPERVISOR_D_AGENT_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.MANAGER_D_AGENT_ID,
      CC_D_PROJECT.PROJECT_ID AS D_PROJECT_ID,
      CC_D_PROGRAM.PROGRAM_ID as D_PROGRAM_ID,
      CC_D_GEOGRAPHY_MASTER.GEOGRAPHY_MASTER_ID as D_GEOGRAPHY_MASTER_ID,
      CC_D_AGENT.D_GROUP_ID,
      CC_D_AGENT.D_SITE_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_LOGIN_ID as 		       AGENT_LOGIN_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.SUPERVISOR_AGENT_LOGIN_ID as 	       SUPERVISOR_AGENT_LOGIN_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.MANAGER_AGENT_LOGIN_ID as 	       MANAGER_AGENT_LOGIN_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_ROUTING_GROUP_NUMBER as         AGENT_ROUTING_GROUP_NUMBER,
      CC_C_AGENT_RTG_GRP.AGENT_ROUTING_GROUP_NAME as AGENT_ROUTING_GROUP_NAME,
      CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_ROUTING_GROUP_TYPE as 	       AGENT_ROUTING_GROUP_TYPE,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.HANDLE_CALLS_COUNT) as                 HANDLE_CALLS_COUNT,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.HANDLE_TIME_SECONDS) as 	       HANDLE_TIME_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.INTERNAL_CALLS_COUNT) as 	       INTERNAL_CALLS_COUNT,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.INTERNAL_SECONDS) as 		       INTERNAL_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.EXTERNAL_CALLS_COUNT) as 	       EXTERNAL_CALLS_COUNT,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.EXTERNAL_SECONDS) as 		       EXTERNAL_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.HOLD_SECONDS) as 		       HOLD_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.RING_SECONDS) as 		       RING_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.TALK_SECONDS) as 		       TALK_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.WRAP_SECONDS) as 		       WRAP_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.LOGIN_SECONDS) as 		       LOGIN_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.IDLE_SECONDS) as 		       IDLE_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.NOT_READY_SECONDS) as 		       NOT_READY_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.TALK_RESERVE_SECONDS) as 	       TALK_RESERVE_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.PREDICTIVE_TALK_SECONDS) as 	       PREDICTIVE_TALK_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.PREVIEW_TALK_SECONDS) as 	       PREVIEW_TALK_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.PREDICTIVE_CALLS_COUNT) as 	       PREDICTIVE_CALLS_COUNT,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.PREVIEW_CALLS_COUNT) as 	       PREVIEW_CALLS_COUNT,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.BREAK_TIME) as 			       BREAK_TIME,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.CONSULTATION_TIME) as 		       CONSULTATION_TIME,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.WALKAWAY_TIME) as 		       WALKAWAY_TIME,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.BUSYONDNTIME) as 		       BUSYONDNTIME,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.PAYROLL_COUNT) as 		       PAYROLL_COUNT,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.ATTRITED_COUNT) as 		       ATTRITED_COUNT,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.SHORT_CALLS) as 		       SHORT_CALLS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.CALLS_RETURNED_TO_QUEUE) as 	       CALLS_RETURNED_TO_QUEUE
      FROM CC_F_AGENT_RTG_GRP_INTERVAL
      INNER JOIN CC_C_AGENT_RTG_GRP ON CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_ROUTING_GROUP_ID = CC_C_AGENT_RTG_GRP.C_AGENT_ROUTING_GROUP_ID 
      INNER JOIN CC_D_PROJECT ON CC_C_AGENT_RTG_GRP.PROJECT_NAME = CC_D_PROJECT.PROJECT_NAME
      INNER JOIN CC_D_PROGRAM ON CC_C_AGENT_RTG_GRP.PROGRAM_NAME = CC_D_PROGRAM.PROGRAM_NAME
      INNER JOIN CC_D_GEOGRAPHY_MASTER ON CC_C_AGENT_RTG_GRP.STATE_NAME = CC_D_GEOGRAPHY_MASTER.GEOGRAPHY_NAME
      INNER JOIN CC_D_AGENT ON CC_F_AGENT_RTG_GRP_INTERVAL.D_AGENT_ID = CC_D_AGENT.D_AGENT_ID
      INNER JOIN CC_D_INTERVAL ON CC_F_AGENT_RTG_GRP_INTERVAL.D_INTERVAL_ID = CC_D_INTERVAL.D_INTERVAL_ID
      GROUP BY
      CC_F_AGENT_RTG_GRP_INTERVAL.D_DATE_ID,
      CC_D_INTERVAL.INTERVAL_START_HOUR,
      CC_F_AGENT_RTG_GRP_INTERVAL.D_AGENT_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_ROUTING_GROUP_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.SUPERVISOR_D_AGENT_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.MANAGER_D_AGENT_ID,
      CC_D_PROJECT.PROJECT_ID,
      CC_D_PROGRAM.PROGRAM_ID,
      CC_D_GEOGRAPHY_MASTER.GEOGRAPHY_MASTER_ID,
      CC_D_AGENT.D_GROUP_ID,
      CC_D_AGENT.D_SITE_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_LOGIN_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.SUPERVISOR_AGENT_LOGIN_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.MANAGER_AGENT_LOGIN_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_ROUTING_GROUP_NUMBER,
      CC_C_AGENT_RTG_GRP.AGENT_ROUTING_GROUP_NAME,
      CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_ROUTING_GROUP_TYPE;  
      
  CREATE OR REPLACE FORCE VIEW CC_F_AGENT_RTG_GRP_BY_DATE_SV (D_DATE_ID,D_AGENT_ID, AGENT_ROUTING_GROUP_ID, SUPERVISOR_D_AGENT_ID, MANAGER_D_AGENT_ID, D_PROJECT_ID, D_PROGRAM_ID, D_GEOGRAPHY_MASTER_ID, D_GROUP_ID, D_SITE_ID,AGENT_LOGIN_ID, SUPERVISOR_AGENT_LOGIN_ID, MANAGER_AGENT_LOGIN_ID,AGENT_ROUTING_GROUP_NUMBER,AGENT_ROUTING_GROUP_NAME, AGENT_ROUTING_GROUP_TYPE, HANDLE_CALLS_COUNT, HANDLE_TIME_SECONDS, INTERNAL_CALLS_COUNT, INTERNAL_SECONDS, EXTERNAL_CALLS_COUNT, EXTERNAL_SECONDS, HOLD_SECONDS, RING_SECONDS, TALK_SECONDS, WRAP_SECONDS,LOGIN_SECONDS, IDLE_SECONDS, NOT_READY_SECONDS, TALK_RESERVE_SECONDS, PREDICTIVE_TALK_SECONDS, PREVIEW_TALK_SECONDS, PREDICTIVE_CALLS_COUNT, PREVIEW_CALLS_COUNT, BREAK_TIME, CONSULTATION_TIME, WALKAWAY_TIME, BUSYONDNTIME, PAYROLL_COUNT, ATTRITED_COUNT,SHORT_CALLS,CALLS_RETURNED_TO_QUEUE)
AS
    SELECT 
      CC_F_AGENT_RTG_GRP_INTERVAL.D_DATE_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.D_AGENT_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_ROUTING_GROUP_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.SUPERVISOR_D_AGENT_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.MANAGER_D_AGENT_ID,
      CC_D_PROJECT.PROJECT_ID AS D_PROJECT_ID,
      CC_D_PROGRAM.PROGRAM_ID as D_PROGRAM_ID,
      CC_D_GEOGRAPHY_MASTER.GEOGRAPHY_MASTER_ID as D_GEOGRAPHY_MASTER_ID,
      CC_D_AGENT.D_GROUP_ID,
      CC_D_AGENT.D_SITE_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_LOGIN_ID as 		       AGENT_LOGIN_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.SUPERVISOR_AGENT_LOGIN_ID as 	       SUPERVISOR_AGENT_LOGIN_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.MANAGER_AGENT_LOGIN_ID as 	       MANAGER_AGENT_LOGIN_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_ROUTING_GROUP_NUMBER as         AGENT_ROUTING_GROUP_NUMBER,
      CC_C_AGENT_RTG_GRP.AGENT_ROUTING_GROUP_NAME as AGENT_ROUTING_GROUP_NAME,
      CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_ROUTING_GROUP_TYPE as 	       AGENT_ROUTING_GROUP_TYPE,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.HANDLE_CALLS_COUNT) as                 HANDLE_CALLS_COUNT,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.HANDLE_TIME_SECONDS) as 	       HANDLE_TIME_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.INTERNAL_CALLS_COUNT) as 	       INTERNAL_CALLS_COUNT,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.INTERNAL_SECONDS) as 		       INTERNAL_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.EXTERNAL_CALLS_COUNT) as 	       EXTERNAL_CALLS_COUNT,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.EXTERNAL_SECONDS) as 		       EXTERNAL_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.HOLD_SECONDS) as 		       HOLD_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.RING_SECONDS) as 		       RING_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.TALK_SECONDS) as 		       TALK_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.WRAP_SECONDS) as 		       WRAP_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.LOGIN_SECONDS) as 		       LOGIN_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.IDLE_SECONDS) as 		       IDLE_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.NOT_READY_SECONDS) as 		       NOT_READY_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.TALK_RESERVE_SECONDS) as 	       TALK_RESERVE_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.PREDICTIVE_TALK_SECONDS) as 	       PREDICTIVE_TALK_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.PREVIEW_TALK_SECONDS) as 	       PREVIEW_TALK_SECONDS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.PREDICTIVE_CALLS_COUNT) as 	       PREDICTIVE_CALLS_COUNT,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.PREVIEW_CALLS_COUNT) as 	       PREVIEW_CALLS_COUNT,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.BREAK_TIME) as 			       BREAK_TIME,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.CONSULTATION_TIME) as 		       CONSULTATION_TIME,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.WALKAWAY_TIME) as 		       WALKAWAY_TIME,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.BUSYONDNTIME) as 		       BUSYONDNTIME,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.PAYROLL_COUNT) as 		       PAYROLL_COUNT,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.ATTRITED_COUNT) as 		       ATTRITED_COUNT,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.SHORT_CALLS) as 		       SHORT_CALLS,
      SUM(CC_F_AGENT_RTG_GRP_INTERVAL.CALLS_RETURNED_TO_QUEUE) as 	       CALLS_RETURNED_TO_QUEUE
      FROM CC_F_AGENT_RTG_GRP_INTERVAL
      INNER JOIN CC_C_AGENT_RTG_GRP ON CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_ROUTING_GROUP_ID = CC_C_AGENT_RTG_GRP.C_AGENT_ROUTING_GROUP_ID 
      INNER JOIN CC_D_PROJECT ON CC_C_AGENT_RTG_GRP.PROJECT_NAME = CC_D_PROJECT.PROJECT_NAME
      INNER JOIN CC_D_PROGRAM ON CC_C_AGENT_RTG_GRP.PROGRAM_NAME = CC_D_PROGRAM.PROGRAM_NAME
      INNER JOIN CC_D_GEOGRAPHY_MASTER ON CC_C_AGENT_RTG_GRP.STATE_NAME = CC_D_GEOGRAPHY_MASTER.GEOGRAPHY_NAME
      INNER JOIN CC_D_AGENT ON CC_F_AGENT_RTG_GRP_INTERVAL.D_AGENT_ID = CC_D_AGENT.D_AGENT_ID
      GROUP BY
      CC_F_AGENT_RTG_GRP_INTERVAL.D_DATE_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.D_AGENT_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_ROUTING_GROUP_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.SUPERVISOR_D_AGENT_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.MANAGER_D_AGENT_ID,
      CC_D_PROJECT.PROJECT_ID,
      CC_D_PROGRAM.PROGRAM_ID,
      CC_D_GEOGRAPHY_MASTER.GEOGRAPHY_MASTER_ID,
      CC_D_AGENT.D_GROUP_ID,
      CC_D_AGENT.D_SITE_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_LOGIN_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.SUPERVISOR_AGENT_LOGIN_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.MANAGER_AGENT_LOGIN_ID,
      CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_ROUTING_GROUP_NUMBER,
      CC_C_AGENT_RTG_GRP.AGENT_ROUTING_GROUP_NAME,
      CC_F_AGENT_RTG_GRP_INTERVAL.AGENT_ROUTING_GROUP_TYPE;
      
-- IVR actuals semantic views by hour and date

-- by hour  

CREATE OR REPLACE FORCE VIEW CC_F_ACTUALS_IVR_BY_HOUR_SV (D_DATE_ID, INTERVAL_HOUR, D_PROJECT_ID, D_PROGRAM_ID, D_GEOGRAPHY_MASTER_ID, D_UNIT_OF_WORK_ID, CONTACTS_CREATED, CONTACTS_OFFERED_TO_ACD, CONTACTS_CONTAINED_IN_IVR, MIN_TIME_IN_THE_IVR, MAX_TIME_IN_THE_IVR, MEAN_TIME_IN_THE_IVR, MEDIAN_TIME_IN_THE_IVR, STDDEV_TIME_IN_THE_IVR)
AS
  (SELECT 
    CC_F_ACTUALS_IVR_INTERVAL.D_DATE_ID,
    CC_D_INTERVAL.INTERVAL_START_HOUR,
    CC_F_ACTUALS_IVR_INTERVAL.D_PROJECT_ID,
    CC_F_ACTUALS_IVR_INTERVAL.D_PROGRAM_ID,
    CC_F_ACTUALS_IVR_INTERVAL.D_GEOGRAPHY_MASTER_ID,
    CC_F_ACTUALS_IVR_INTERVAL.D_UNIT_OF_WORK_ID,
    SUM(CC_F_ACTUALS_IVR_INTERVAL.CONTACTS_CREATED) as CONTACTS_CREATED,
    SUM(CC_F_ACTUALS_IVR_INTERVAL.CONTACTS_OFFERED_TO_ACD) as CONTACTS_OFFERED_TO_ACD,
    SUM(CC_F_ACTUALS_IVR_INTERVAL.CONTACTS_CONTAINED_IN_IVR) as CONTACTS_CONTAINED_IN_IVR,
    MIN(CC_F_ACTUALS_IVR_INTERVAL.MIN_TIME_IN_THE_IVR) as MIN_TIME_IN_THE_IVR,
    MAX(CC_F_ACTUALS_IVR_INTERVAL.MAX_TIME_IN_THE_IVR) as MAX_TIME_IN_THE_IVR,
    null as MEAN_TIME_IN_THE_IVR,
    null as MEDIAN_TIME_IN_THE_IVR,
    null as STDDEV_TIME_IN_THE_IVR
  FROM CC_F_ACTUALS_IVR_INTERVAL 
  INNER JOIN CC_D_INTERVAL ON CC_F_ACTUALS_IVR_INTERVAL.D_INTERVAL_ID = CC_D_INTERVAL.D_INTERVAL_ID
  GROUP BY
  CC_F_ACTUALS_IVR_INTERVAL.D_DATE_ID,
  CC_D_INTERVAL.INTERVAL_START_HOUR,
  CC_F_ACTUALS_IVR_INTERVAL.D_PROJECT_ID,
  CC_F_ACTUALS_IVR_INTERVAL.D_PROGRAM_ID,
  CC_F_ACTUALS_IVR_INTERVAL.D_GEOGRAPHY_MASTER_ID,
  CC_F_ACTUALS_IVR_INTERVAL.D_UNIT_OF_WORK_ID);
 
 -- by date  
 
 CREATE OR REPLACE FORCE VIEW CC_F_ACTUALS_IVR_BY_DATE_SV (D_DATE_ID, D_PROJECT_ID, D_PROGRAM_ID, D_GEOGRAPHY_MASTER_ID, D_UNIT_OF_WORK_ID, CONTACTS_CREATED, CONTACTS_OFFERED_TO_ACD, CONTACTS_CONTAINED_IN_IVR, MIN_TIME_IN_THE_IVR, MAX_TIME_IN_THE_IVR, MEAN_TIME_IN_THE_IVR, MEDIAN_TIME_IN_THE_IVR, STDDEV_TIME_IN_THE_IVR)
 AS
   (SELECT 
     CC_F_ACTUALS_IVR_INTERVAL.D_DATE_ID,
     CC_F_ACTUALS_IVR_INTERVAL.D_PROJECT_ID,
     CC_F_ACTUALS_IVR_INTERVAL.D_PROGRAM_ID,
     CC_F_ACTUALS_IVR_INTERVAL.D_GEOGRAPHY_MASTER_ID,
     CC_F_ACTUALS_IVR_INTERVAL.D_UNIT_OF_WORK_ID,
     SUM(CC_F_ACTUALS_IVR_INTERVAL.CONTACTS_CREATED) as CONTACTS_CREATED,
     SUM(CC_F_ACTUALS_IVR_INTERVAL.CONTACTS_OFFERED_TO_ACD) as CONTACTS_OFFERED_TO_ACD,
     SUM(CC_F_ACTUALS_IVR_INTERVAL.CONTACTS_CONTAINED_IN_IVR) as CONTACTS_CONTAINED_IN_IVR,
     MIN(CC_F_ACTUALS_IVR_INTERVAL.MIN_TIME_IN_THE_IVR) as MIN_TIME_IN_THE_IVR,
     MAX(CC_F_ACTUALS_IVR_INTERVAL.MAX_TIME_IN_THE_IVR) as MAX_TIME_IN_THE_IVR,
     null as MEAN_TIME_IN_THE_IVR,
     null as MEDIAN_TIME_IN_THE_IVR,
     null as STDDEV_TIME_IN_THE_IVR
   FROM CC_F_ACTUALS_IVR_INTERVAL 
   GROUP BY
   CC_F_ACTUALS_IVR_INTERVAL.D_DATE_ID,
   CC_F_ACTUALS_IVR_INTERVAL.D_PROJECT_ID,
   CC_F_ACTUALS_IVR_INTERVAL.D_PROGRAM_ID,
   CC_F_ACTUALS_IVR_INTERVAL.D_GEOGRAPHY_MASTER_ID,
   CC_F_ACTUALS_IVR_INTERVAL.D_UNIT_OF_WORK_ID);
      
-- Queue semantic views by hour and date

CREATE OR REPLACE FORCE VIEW CC_F_ACTUALS_QUEUE_BY_HOUR_SV (D_DATE_ID, D_PROJECT_ID, D_PROGRAM_ID, D_GEOGRAPHY_MASTER_ID, D_UNIT_OF_WORK_ID, D_CONTACT_QUEUE_ID, INTERVAL_HOUR, D_AGENT_ID, QUEUE_NUMBER, AGENT_LOGIN_ID, CONTACTS_RECEIVED_FROM_IVR, CALLS_ANSWERED, RAW_CONTACTS_OFFERED, CONTACTS_OFFERED, CONTACTS_HANDLED, CONTACTS_ABANDONED,LABOR_MINUTES_TOTAL, LABOR_MINUTES_AVAILABLE, LABOR_MINUTES_WAITING, HEADCOUNT_TOTAL, HEADCOUNT_AVAILABLE, HEADCOUNT_UNAVAILABLE, CONTACT_INVENTORY,  CONTACTS_TRANSFERRED, OUTFLOW_CONTACTS, ANSWER_WAIT_TIME_TOTAL, ABANDON_TIME_TOTAL, TALK_TIME_TOTAL, AFTER_CALL_WORK_TIME_TOTAL, SERVICE_LEVEL_ANSWERED_COUNT, SERVICE_LEVEL_ABANDONED, CALLS_ON_HOLD, HOLD_TIME_TOTAL, SHORT_ABANDONS, CONTACTS_BLOCKED, ICR_DEFAULT_ROUTED, NETWORK_DEFAULT_ROUTED, RETURN_BUSY,
  CALLS_RONA, RETURN_RELEASE, CALLS_ROUTED_NON_AGENT, ERROR_COUNT, AGENT_ERROR_COUNT, RETURN_RING, INCOMPLETE_CALLS, CALLS_GIVEN_FORCE_DISCONNECT, CALLS_GIVEN_ROUTE_TO, SHORT_CALLS, MAX_ABANDON_TIME, ABANDON_THRESHOLD, MAX_CALLS_QUEUED, HANDLE_TIME, CTVRU_TIME, SERVICE_LEVEL_CALLS, ROUTER_QUEUE_WAIT_TIME, MAX_SPEED_OF_ANSWER, CONTACT_INVENTORY_JEOPARDY, MEAN_HANDLE_TIME, SERVICE_LEVEL_ANSWERED_PERCENT, MEAN_SPEED_OF_ANSWER, MEAN_SPEED_TO_HANDLE, AVG_TIME_TO_ABANDON )
AS
  SELECT 
    CC_F_ACTUALS_QUEUE_INTERVAL.D_DATE_ID,
    CC_D_CONTACT_QUEUE.D_PROJECT_ID,
    CC_D_CONTACT_QUEUE.D_PROGRAM_ID,
    CC_D_CONTACT_QUEUE.D_GEOGRAPHY_MASTER_ID,
    CC_D_CONTACT_QUEUE.D_UNIT_OF_WORK_ID,
    CC_F_ACTUALS_QUEUE_INTERVAL.D_CONTACT_QUEUE_ID,
    CC_D_INTERVAL.INTERVAL_START_HOUR,
    CC_F_ACTUALS_QUEUE_INTERVAL.D_AGENT_ID,
    CC_F_ACTUALS_QUEUE_INTERVAL.QUEUE_NUMBER,
    CC_F_ACTUALS_QUEUE_INTERVAL.AGENT_LOGIN_ID,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_RECEIVED_FROM_IVR) as CONTACTS_RECEIVED_FROM_IVR,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ANSWERED) as CALLS_ANSWERED,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.RAW_CONTACTS_OFFERED) as RAW_CONTACTS_OFFERED,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_OFFERED) as CONTACTS_OFFERED,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_HANDLED) as CONTACTS_HANDLED,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_ABANDONED) as CONTACTS_ABANDONED,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.LABOR_MINUTES_TOTAL) as LABOR_MINUTES_TOTAL,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.LABOR_MINUTES_AVAILABLE) as LABOR_MINUTES_AVAILABLE,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.LABOR_MINUTES_WAITING) as LABOR_MINUTES_WAITING,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HEADCOUNT_TOTAL) as HEADCOUNT_TOTAL,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HEADCOUNT_AVAILABLE) as HEADCOUNT_AVAILABLE,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HEADCOUNT_UNAVAILABLE) as HEADCOUNT_UNAVAILABLE,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACT_INVENTORY) as CONTACT_INVENTORY,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_TRANSFERRED) as CONTACTS_TRANSFERRED,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.OUTFLOW_CONTACTS) as OUTFLOW_CONTACTS,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ANSWER_WAIT_TIME_TOTAL) as ANSWER_WAIT_TIME_TOTAL,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ABANDON_TIME_TOTAL) as ABANDON_TIME_TOTAL,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.TALK_TIME_TOTAL) as TALK_TIME_TOTAL,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.AFTER_CALL_WORK_TIME_TOTAL) as AFTER_CALL_WORK_TIME_TOTAL,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SERVICE_LEVEL_ANSWERED_COUNT) as SERVICE_LEVEL_ANSWERED_COUNT,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SERVICE_LEVEL_ABANDONED) as SERVICE_LEVEL_ABANDONED,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ON_HOLD) as CALLS_ON_HOLD,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HOLD_TIME_TOTAL) as HOLD_TIME_TOTAL,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SHORT_ABANDONS) as SHORT_ABANDONS,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_BLOCKED) as CONTACTS_BLOCKED,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ICR_DEFAULT_ROUTED) as ICR_DEFAULT_ROUTED,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.NETWORK_DEFAULT_ROUTED) as NETWORK_DEFAULT_ROUTED,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.RETURN_BUSY) as RETURN_BUSY,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_RONA) as CALLS_RONA,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.RETURN_RELEASE) as RETURN_RELEASE,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ROUTED_NON_AGENT) as CALLS_ROUTED_NON_AGENT,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ERROR_COUNT) as ERROR_COUNT,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.AGENT_ERROR_COUNT) as AGENT_ERROR_COUNT,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.RETURN_RING) as RETURN_RING,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.INCOMPLETE_CALLS) as INCOMPLETE_CALLS,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_GIVEN_FORCE_DISCONNECT) as CALLS_GIVEN_FORCE_DISCONNECT,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_GIVEN_ROUTE_TO) as CALLS_GIVEN_ROUTE_TO,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SHORT_CALLS) as SHORT_CALLS,
    MAX(CC_F_ACTUALS_QUEUE_INTERVAL.MAX_ABANDON_TIME) as MAX_ABANDON_TIME,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ABANDON_THRESHOLD) as ABANDON_THRESHOLD,
    MAX(CC_F_ACTUALS_QUEUE_INTERVAL.MAX_CALLS_QUEUED) as MAX_CALLS_QUEUED,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HANDLE_TIME) as HANDLE_TIME,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CTVRU_TIME) as CTVRU_TIME,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SERVICE_LEVEL_CALLS) as SERVICE_LEVEL_CALLS,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ROUTER_QUEUE_WAIT_TIME) as ROUTER_QUEUE_WAIT_TIME,
    MAX(CC_F_ACTUALS_QUEUE_INTERVAL.MAX_SPEED_OF_ANSWER) as MAX_SPEED_OF_ANSWER,
    SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACT_INVENTORY_JEOPARDY) as CONTACT_INVENTORY_JEOPARDY,
   ROUND( ( CASE WHEN SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_OFFERED)!=0 THEN (SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HANDLE_TIME)/SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_OFFERED))ELSE NULL END ),2) MEAN_HANDLE_TIME,
    ROUND(( CASE WHEN SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ANSWERED)!=0 THEN (SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SERVICE_LEVEL_CALLS)/SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ANSWERED))ELSE NULL END ),2) SERVICE_LEVEL_ANSWERED_PERCENT,
   ROUND(( CASE WHEN SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ANSWERED)!=0 THEN (SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ROUTER_QUEUE_WAIT_TIME)/SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ANSWERED))ELSE NULL END ),2) MEAN_SPEED_OF_ANSWER,
   ROUND(( CASE WHEN SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_OFFERED)!=0 THEN ((SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CTVRU_TIME) + SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ANSWER_WAIT_TIME_TOTAL) + SUM(CC_F_ACTUALS_QUEUE_INTERVAL.TALK_TIME_TOTAL) + SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HOLD_TIME_TOTAL))/SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_OFFERED))ELSE NULL END ),2) MEAN_SPEED_TO_HANDLE,
   ROUND( ( CASE WHEN SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_ABANDONED)!=0 THEN (SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ABANDON_TIME_TOTAL)/SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_ABANDONED))ELSE NULL END ),2) AVG_TIME_TO_ABANDON
  FROM CC_F_ACTUALS_QUEUE_INTERVAL
  INNER JOIN CC_D_CONTACT_QUEUE ON CC_F_ACTUALS_QUEUE_INTERVAL.D_CONTACT_QUEUE_ID = CC_D_CONTACT_QUEUE.D_CONTACT_QUEUE_ID
  INNER JOIN CC_D_INTERVAL ON CC_F_ACTUALS_QUEUE_INTERVAL.D_INTERVAL_ID = CC_D_INTERVAL.D_INTERVAL_ID
  GROUP BY CC_F_ACTUALS_QUEUE_INTERVAL.D_DATE_ID,
    CC_D_CONTACT_QUEUE.D_PROJECT_ID,
    CC_D_CONTACT_QUEUE.D_PROGRAM_ID,
    CC_D_CONTACT_QUEUE.D_GEOGRAPHY_MASTER_ID,
    CC_D_CONTACT_QUEUE.D_UNIT_OF_WORK_ID,
    CC_F_ACTUALS_QUEUE_INTERVAL.D_CONTACT_QUEUE_ID,
    CC_D_INTERVAL.INTERVAL_START_HOUR,
    CC_F_ACTUALS_QUEUE_INTERVAL.D_AGENT_ID,
    CC_F_ACTUALS_QUEUE_INTERVAL.QUEUE_NUMBER,
    CC_F_ACTUALS_QUEUE_INTERVAL.AGENT_LOGIN_ID;
    
CREATE OR REPLACE FORCE VIEW CC_F_ACTUALS_QUEUE_BY_DATE_SV (D_DATE_ID, D_PROJECT_ID, D_PROGRAM_ID, D_GEOGRAPHY_MASTER_ID, D_UNIT_OF_WORK_ID, D_CONTACT_QUEUE_ID, D_AGENT_ID, QUEUE_NUMBER, AGENT_LOGIN_ID, CONTACTS_RECEIVED_FROM_IVR, CALLS_ANSWERED, RAW_CONTACTS_OFFERED, CONTACTS_OFFERED, CONTACTS_HANDLED, CONTACTS_ABANDONED,LABOR_MINUTES_TOTAL, LABOR_MINUTES_AVAILABLE, LABOR_MINUTES_WAITING, HEADCOUNT_TOTAL, HEADCOUNT_AVAILABLE, HEADCOUNT_UNAVAILABLE, CONTACT_INVENTORY,  CONTACTS_TRANSFERRED, OUTFLOW_CONTACTS, ANSWER_WAIT_TIME_TOTAL, ABANDON_TIME_TOTAL, TALK_TIME_TOTAL, AFTER_CALL_WORK_TIME_TOTAL, SERVICE_LEVEL_ANSWERED_COUNT, SERVICE_LEVEL_ABANDONED, CALLS_ON_HOLD, HOLD_TIME_TOTAL, SHORT_ABANDONS, CONTACTS_BLOCKED, ICR_DEFAULT_ROUTED, NETWORK_DEFAULT_ROUTED, RETURN_BUSY,
  CALLS_RONA, RETURN_RELEASE, CALLS_ROUTED_NON_AGENT, ERROR_COUNT, AGENT_ERROR_COUNT, RETURN_RING, INCOMPLETE_CALLS, CALLS_GIVEN_FORCE_DISCONNECT, CALLS_GIVEN_ROUTE_TO, SHORT_CALLS, MAX_ABANDON_TIME, ABANDON_THRESHOLD, MAX_CALLS_QUEUED, HANDLE_TIME, CTVRU_TIME, SERVICE_LEVEL_CALLS, ROUTER_QUEUE_WAIT_TIME, MAX_SPEED_OF_ANSWER,CONTACT_INVENTORY_JEOPARDY, MEAN_HANDLE_TIME, SERVICE_LEVEL_ANSWERED_PERCENT, MEAN_SPEED_OF_ANSWER, MEAN_SPEED_TO_HANDLE ,AVG_TIME_TO_ABANDON )
AS
    SELECT 
      CC_F_ACTUALS_QUEUE_INTERVAL.D_DATE_ID,
      CC_D_CONTACT_QUEUE.D_PROJECT_ID,
      CC_D_CONTACT_QUEUE.D_PROGRAM_ID,
      CC_D_CONTACT_QUEUE.D_GEOGRAPHY_MASTER_ID,
      CC_D_CONTACT_QUEUE.D_UNIT_OF_WORK_ID,
      CC_F_ACTUALS_QUEUE_INTERVAL.D_CONTACT_QUEUE_ID,
      CC_F_ACTUALS_QUEUE_INTERVAL.D_AGENT_ID,
      CC_F_ACTUALS_QUEUE_INTERVAL.QUEUE_NUMBER,
      CC_F_ACTUALS_QUEUE_INTERVAL.AGENT_LOGIN_ID,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_RECEIVED_FROM_IVR) as CONTACTS_RECEIVED_FROM_IVR,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ANSWERED) as CALLS_ANSWERED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.RAW_CONTACTS_OFFERED) as RAW_CONTACTS_OFFERED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_OFFERED) as CONTACTS_OFFERED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_HANDLED) as CONTACTS_HANDLED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_ABANDONED) as CONTACTS_ABANDONED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.LABOR_MINUTES_TOTAL) as LABOR_MINUTES_TOTAL,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.LABOR_MINUTES_AVAILABLE) as LABOR_MINUTES_AVAILABLE,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.LABOR_MINUTES_WAITING) as LABOR_MINUTES_WAITING,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HEADCOUNT_TOTAL) as HEADCOUNT_TOTAL,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HEADCOUNT_AVAILABLE) as HEADCOUNT_AVAILABLE,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HEADCOUNT_UNAVAILABLE) as HEADCOUNT_UNAVAILABLE,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACT_INVENTORY) as CONTACT_INVENTORY,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_TRANSFERRED) as CONTACTS_TRANSFERRED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.OUTFLOW_CONTACTS) as OUTFLOW_CONTACTS,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ANSWER_WAIT_TIME_TOTAL) as ANSWER_WAIT_TIME_TOTAL,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ABANDON_TIME_TOTAL) as ABANDON_TIME_TOTAL,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.TALK_TIME_TOTAL) as TALK_TIME_TOTAL,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.AFTER_CALL_WORK_TIME_TOTAL) as AFTER_CALL_WORK_TIME_TOTAL,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SERVICE_LEVEL_ANSWERED_COUNT) as SERVICE_LEVEL_ANSWERED_COUNT,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SERVICE_LEVEL_ABANDONED) as SERVICE_LEVEL_ABANDONED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ON_HOLD) as CALLS_ON_HOLD,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HOLD_TIME_TOTAL) as HOLD_TIME_TOTAL,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SHORT_ABANDONS) as SHORT_ABANDONS,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_BLOCKED) as CONTACTS_BLOCKED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ICR_DEFAULT_ROUTED) as ICR_DEFAULT_ROUTED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.NETWORK_DEFAULT_ROUTED) as NETWORK_DEFAULT_ROUTED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.RETURN_BUSY) as RETURN_BUSY,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_RONA) as CALLS_RONA,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.RETURN_RELEASE) as RETURN_RELEASE,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ROUTED_NON_AGENT) as CALLS_ROUTED_NON_AGENT,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ERROR_COUNT) as ERROR_COUNT,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.AGENT_ERROR_COUNT) as AGENT_ERROR_COUNT,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.RETURN_RING) as RETURN_RING,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.INCOMPLETE_CALLS) as INCOMPLETE_CALLS,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_GIVEN_FORCE_DISCONNECT) as CALLS_GIVEN_FORCE_DISCONNECT,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_GIVEN_ROUTE_TO) as CALLS_GIVEN_ROUTE_TO,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SHORT_CALLS) as SHORT_CALLS,
      MAX(CC_F_ACTUALS_QUEUE_INTERVAL.MAX_ABANDON_TIME) as MAX_ABANDON_TIME,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ABANDON_THRESHOLD) as ABANDON_THRESHOLD,
      MAX(CC_F_ACTUALS_QUEUE_INTERVAL.MAX_CALLS_QUEUED) as MAX_CALLS_QUEUED,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HANDLE_TIME) as HANDLE_TIME,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CTVRU_TIME) as CTVRU_TIME,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SERVICE_LEVEL_CALLS) as SERVICE_LEVEL_CALLS,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ROUTER_QUEUE_WAIT_TIME) as ROUTER_QUEUE_WAIT_TIME,
      MAX(CC_F_ACTUALS_QUEUE_INTERVAL.MAX_SPEED_OF_ANSWER) as MAX_SPEED_OF_ANSWER,
      SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACT_INVENTORY_JEOPARDY) as CONTACT_INVENTORY_JEOPARDY,
      ROUND(( CASE WHEN SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_OFFERED)!=0 THEN (SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HANDLE_TIME)/SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_OFFERED))ELSE NULL END ),2) MEAN_HANDLE_TIME,
      ROUND(( CASE WHEN SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ANSWERED)!=0 THEN (SUM(CC_F_ACTUALS_QUEUE_INTERVAL.SERVICE_LEVEL_CALLS)/SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ANSWERED))ELSE NULL END ),2) SERVICE_LEVEL_ANSWERED_PERCENT,
     ROUND(( CASE WHEN SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ANSWERED)!=0 THEN (SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ROUTER_QUEUE_WAIT_TIME)/SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CALLS_ANSWERED))ELSE NULL END ),2) MEAN_SPEED_OF_ANSWER,
   ROUND(( CASE WHEN SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_OFFERED)!=0 THEN ((SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CTVRU_TIME) + SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ANSWER_WAIT_TIME_TOTAL) + SUM(CC_F_ACTUALS_QUEUE_INTERVAL.TALK_TIME_TOTAL) + SUM(CC_F_ACTUALS_QUEUE_INTERVAL.HOLD_TIME_TOTAL))/SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_OFFERED))ELSE NULL END ),2)MEAN_SPEED_TO_HANDLE,
   ROUND( ( CASE WHEN SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_ABANDONED)!=0 THEN (SUM(CC_F_ACTUALS_QUEUE_INTERVAL.ABANDON_TIME_TOTAL)/SUM(CC_F_ACTUALS_QUEUE_INTERVAL.CONTACTS_ABANDONED))ELSE NULL END ),2) AVG_TIME_TO_ABANDON
  FROM CC_F_ACTUALS_QUEUE_INTERVAL
  INNER JOIN CC_D_CONTACT_QUEUE ON CC_F_ACTUALS_QUEUE_INTERVAL.D_CONTACT_QUEUE_ID = CC_D_CONTACT_QUEUE.D_CONTACT_QUEUE_ID
  GROUP BY CC_F_ACTUALS_QUEUE_INTERVAL.D_DATE_ID,
    CC_D_CONTACT_QUEUE.D_PROJECT_ID,
    CC_D_CONTACT_QUEUE.D_PROGRAM_ID,
    CC_D_CONTACT_QUEUE.D_GEOGRAPHY_MASTER_ID,
    CC_D_CONTACT_QUEUE.D_UNIT_OF_WORK_ID,
    CC_F_ACTUALS_QUEUE_INTERVAL.D_CONTACT_QUEUE_ID,
    CC_F_ACTUALS_QUEUE_INTERVAL.D_AGENT_ID,
    CC_F_ACTUALS_QUEUE_INTERVAL.QUEUE_NUMBER,
    CC_F_ACTUALS_QUEUE_INTERVAL.AGENT_LOGIN_ID;    
    
    
--------------------------------------------------------------------------------------------------------

CREATE OR REPLACE FORCE VIEW CC_F_ACD_QUEUE_BY_HOUR_SV (D_DATE_ID, D_PROJECT_ID, D_PROGRAM_ID, D_GEOGRAPHY_MASTER_ID, D_UNIT_OF_WORK_ID, D_CONTACT_QUEUE_ID, INTERVAL_HOUR, QUEUE_NUMBER, CONTACTS_RECEIVED_FROM_IVR, CALLS_ANSWERED, RAW_CONTACTS_OFFERED, CONTACTS_OFFERED, CONTACTS_HANDLED, CONTACTS_ABANDONED,LABOR_MINUTES_TOTAL, LABOR_MINUTES_AVAILABLE, LABOR_MINUTES_WAITING, HEADCOUNT_TOTAL, HEADCOUNT_AVAILABLE, HEADCOUNT_UNAVAILABLE, CONTACT_INVENTORY,  CONTACTS_TRANSFERRED, OUTFLOW_CONTACTS, ANSWER_WAIT_TIME_TOTAL, ABANDON_TIME_TOTAL, TALK_TIME_TOTAL, AFTER_CALL_WORK_TIME_TOTAL, SERVICE_LEVEL_ANSWERED_COUNT, SERVICE_LEVEL_ABANDONED, CALLS_ON_HOLD, HOLD_TIME_TOTAL, SHORT_ABANDONS, CONTACTS_BLOCKED, ICR_DEFAULT_ROUTED, NETWORK_DEFAULT_ROUTED, RETURN_BUSY,
  CALLS_RONA, RETURN_RELEASE, CALLS_ROUTED_NON_AGENT, ERROR_COUNT, AGENT_ERROR_COUNT, RETURN_RING, INCOMPLETE_CALLS, CALLS_GIVEN_FORCE_DISCONNECT, CALLS_GIVEN_ROUTE_TO, SHORT_CALLS, MAX_ABANDON_TIME, ABANDON_THRESHOLD, MAX_CALLS_QUEUED, HANDLE_TIME, CTVRU_TIME, SERVICE_LEVEL_CALLS, ROUTER_QUEUE_WAIT_TIME, MAX_SPEED_OF_ANSWER, CONTACT_INVENTORY_JEOPARDY, MEAN_HANDLE_TIME, SERVICE_LEVEL_ANSWERED_PERCENT, MEAN_SPEED_OF_ANSWER, MEAN_SPEED_TO_HANDLE, AVG_TIME_TO_ABANDON)
AS
      SELECT 
        CC_F_ACD_QUEUE_INTERVAL.D_DATE_ID,
        CC_D_CONTACT_QUEUE.D_PROJECT_ID,
        CC_D_CONTACT_QUEUE.D_PROGRAM_ID,
        CC_D_CONTACT_QUEUE.D_GEOGRAPHY_MASTER_ID,
        CC_D_CONTACT_QUEUE.D_UNIT_OF_WORK_ID,
        CC_F_ACD_QUEUE_INTERVAL.D_CONTACT_QUEUE_ID,
        CC_D_INTERVAL.INTERVAL_START_HOUR,
        CC_F_ACD_QUEUE_INTERVAL.QUEUE_NUMBER,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_RECEIVED_FROM_IVR) as CONTACTS_RECEIVED_FROM_IVR,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_ANSWERED) as CALLS_ANSWERED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.RAW_CONTACTS_OFFERED) as RAW_CONTACTS_OFFERED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_OFFERED) as CONTACTS_OFFERED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_HANDLED) as CONTACTS_HANDLED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_ABANDONED) as CONTACTS_ABANDONED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.LABOR_MINUTES_TOTAL) as LABOR_MINUTES_TOTAL,
        SUM(CC_F_ACD_QUEUE_INTERVAL.LABOR_MINUTES_AVAILABLE) as LABOR_MINUTES_AVAILABLE,
        SUM(CC_F_ACD_QUEUE_INTERVAL.LABOR_MINUTES_WAITING) as LABOR_MINUTES_WAITING,
        SUM(CC_F_ACD_QUEUE_INTERVAL.HEADCOUNT_TOTAL) as HEADCOUNT_TOTAL,
        SUM(CC_F_ACD_QUEUE_INTERVAL.HEADCOUNT_AVAILABLE) as HEADCOUNT_AVAILABLE,
        SUM(CC_F_ACD_QUEUE_INTERVAL.HEADCOUNT_UNAVAILABLE) as HEADCOUNT_UNAVAILABLE,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACT_INVENTORY) as CONTACT_INVENTORY,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_TRANSFERRED) as CONTACTS_TRANSFERRED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.OUTFLOW_CONTACTS) as OUTFLOW_CONTACTS,
        SUM(CC_F_ACD_QUEUE_INTERVAL.ANSWER_WAIT_TIME_TOTAL) as ANSWER_WAIT_TIME_TOTAL,
        SUM(CC_F_ACD_QUEUE_INTERVAL.ABANDON_TIME_TOTAL) as ABANDON_TIME_TOTAL,
        SUM(CC_F_ACD_QUEUE_INTERVAL.TALK_TIME_TOTAL) as TALK_TIME_TOTAL,
        SUM(CC_F_ACD_QUEUE_INTERVAL.AFTER_CALL_WORK_TIME_TOTAL) as AFTER_CALL_WORK_TIME_TOTAL,
        SUM(CC_F_ACD_QUEUE_INTERVAL.SERVICE_LEVEL_ANSWERED_COUNT) as SERVICE_LEVEL_ANSWERED_COUNT,
        SUM(CC_F_ACD_QUEUE_INTERVAL.SERVICE_LEVEL_ABANDONED) as SERVICE_LEVEL_ABANDONED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_ON_HOLD) as CALLS_ON_HOLD,
        SUM(CC_F_ACD_QUEUE_INTERVAL.HOLD_TIME_TOTAL) as HOLD_TIME_TOTAL,
        SUM(CC_F_ACD_QUEUE_INTERVAL.SHORT_ABANDONS) as SHORT_ABANDONS,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_BLOCKED) as CONTACTS_BLOCKED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.ICR_DEFAULT_ROUTED) as ICR_DEFAULT_ROUTED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.NETWORK_DEFAULT_ROUTED) as NETWORK_DEFAULT_ROUTED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.RETURN_BUSY) as RETURN_BUSY,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_RONA) as CALLS_RONA,
        SUM(CC_F_ACD_QUEUE_INTERVAL.RETURN_RELEASE) as RETURN_RELEASE,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_ROUTED_NON_AGENT) as CALLS_ROUTED_NON_AGENT,
        SUM(CC_F_ACD_QUEUE_INTERVAL.ERROR_COUNT) as ERROR_COUNT,
        SUM(CC_F_ACD_QUEUE_INTERVAL.AGENT_ERROR_COUNT) as AGENT_ERROR_COUNT,
        SUM(CC_F_ACD_QUEUE_INTERVAL.RETURN_RING) as RETURN_RING,
        SUM(CC_F_ACD_QUEUE_INTERVAL.INCOMPLETE_CALLS) as INCOMPLETE_CALLS,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_GIVEN_FORCE_DISCONNECT) as CALLS_GIVEN_FORCE_DISCONNECT,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_GIVEN_ROUTE_TO) as CALLS_GIVEN_ROUTE_TO,
        SUM(CC_F_ACD_QUEUE_INTERVAL.SHORT_CALLS) as SHORT_CALLS,
        MAX(CC_F_ACD_QUEUE_INTERVAL.MAX_ABANDON_TIME) as MAX_ABANDON_TIME,
        SUM(CC_F_ACD_QUEUE_INTERVAL.ABANDON_THRESHOLD) as ABANDON_THRESHOLD,
        MAX(CC_F_ACD_QUEUE_INTERVAL.MAX_CALLS_QUEUED) as MAX_CALLS_QUEUED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.HANDLE_TIME) as HANDLE_TIME,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CTVRU_TIME) as CTVRU_TIME,
        SUM(CC_F_ACD_QUEUE_INTERVAL.SERVICE_LEVEL_CALLS) as SERVICE_LEVEL_CALLS,
        SUM(CC_F_ACD_QUEUE_INTERVAL.ROUTER_QUEUE_WAIT_TIME) as ROUTER_QUEUE_WAIT_TIME,
        MAX(CC_F_ACD_QUEUE_INTERVAL.MAX_SPEED_OF_ANSWER) as MAX_SPEED_OF_ANSWER,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACT_INVENTORY_JEOPARDY) as CONTACT_INVENTORY_JEOPARDY,
        ROUND(( CASE WHEN SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_OFFERED)!=0 THEN (SUM(CC_F_ACD_QUEUE_INTERVAL.HANDLE_TIME)/SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_OFFERED))ELSE NULL END ),2) MEAN_HANDLE_TIME,
        ROUND(( CASE WHEN SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_ANSWERED)!=0 THEN (SUM(CC_F_ACD_QUEUE_INTERVAL.SERVICE_LEVEL_CALLS)/SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_ANSWERED))ELSE NULL END ),2) SERVICE_LEVEL_ANSWERED_PERCENT,
       ROUND(( CASE WHEN SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_ANSWERED)!=0 THEN (SUM(CC_F_ACD_QUEUE_INTERVAL.ROUTER_QUEUE_WAIT_TIME)/SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_ANSWERED))ELSE NULL END ),2) MEAN_SPEED_OF_ANSWER,
   ROUND(( CASE WHEN SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_OFFERED)!=0 THEN ((SUM(CC_F_ACD_QUEUE_INTERVAL.CTVRU_TIME) + SUM(CC_F_ACD_QUEUE_INTERVAL.ANSWER_WAIT_TIME_TOTAL) + SUM(CC_F_ACD_QUEUE_INTERVAL.TALK_TIME_TOTAL) + SUM(CC_F_ACD_QUEUE_INTERVAL.HOLD_TIME_TOTAL))/SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_OFFERED))ELSE NULL END ),2) MEAN_SPEED_TO_HANDLE,
   ROUND( ( CASE WHEN SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_ABANDONED)!=0 THEN (SUM(CC_F_ACD_QUEUE_INTERVAL.ABANDON_TIME_TOTAL)/SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_ABANDONED))ELSE NULL END ),2) AVG_TIME_TO_ABANDON
  FROM CC_F_ACD_QUEUE_INTERVAL
  INNER JOIN CC_D_CONTACT_QUEUE ON CC_F_ACD_QUEUE_INTERVAL.D_CONTACT_QUEUE_ID = CC_D_CONTACT_QUEUE.D_CONTACT_QUEUE_ID
  INNER JOIN CC_D_INTERVAL ON CC_F_ACD_QUEUE_INTERVAL.D_INTERVAL_ID = CC_D_INTERVAL.D_INTERVAL_ID
  GROUP BY CC_F_ACD_QUEUE_INTERVAL.D_DATE_ID,
    CC_D_CONTACT_QUEUE.D_PROJECT_ID,
    CC_D_CONTACT_QUEUE.D_PROGRAM_ID,
    CC_D_CONTACT_QUEUE.D_GEOGRAPHY_MASTER_ID,
    CC_D_CONTACT_QUEUE.D_UNIT_OF_WORK_ID,
    CC_F_ACD_QUEUE_INTERVAL.D_CONTACT_QUEUE_ID,
    CC_D_INTERVAL.INTERVAL_START_HOUR,
    CC_F_ACD_QUEUE_INTERVAL.QUEUE_NUMBER;
    
CREATE OR REPLACE FORCE VIEW CC_F_ACD_QUEUE_BY_DATE_SV (D_DATE_ID, D_PROJECT_ID, D_PROGRAM_ID, D_GEOGRAPHY_MASTER_ID, D_UNIT_OF_WORK_ID, D_CONTACT_QUEUE_ID, QUEUE_NUMBER, CONTACTS_RECEIVED_FROM_IVR, CALLS_ANSWERED, RAW_CONTACTS_OFFERED, CONTACTS_OFFERED, CONTACTS_HANDLED, CONTACTS_ABANDONED,LABOR_MINUTES_TOTAL, LABOR_MINUTES_AVAILABLE, LABOR_MINUTES_WAITING, HEADCOUNT_TOTAL, HEADCOUNT_AVAILABLE, HEADCOUNT_UNAVAILABLE, CONTACT_INVENTORY,  CONTACTS_TRANSFERRED, OUTFLOW_CONTACTS, ANSWER_WAIT_TIME_TOTAL, ABANDON_TIME_TOTAL, TALK_TIME_TOTAL, AFTER_CALL_WORK_TIME_TOTAL, SERVICE_LEVEL_ANSWERED_COUNT, SERVICE_LEVEL_ABANDONED, CALLS_ON_HOLD, HOLD_TIME_TOTAL, SHORT_ABANDONS, CONTACTS_BLOCKED, ICR_DEFAULT_ROUTED, NETWORK_DEFAULT_ROUTED, RETURN_BUSY,
  CALLS_RONA, RETURN_RELEASE, CALLS_ROUTED_NON_AGENT, ERROR_COUNT, AGENT_ERROR_COUNT, RETURN_RING, INCOMPLETE_CALLS, CALLS_GIVEN_FORCE_DISCONNECT, CALLS_GIVEN_ROUTE_TO, SHORT_CALLS, MAX_ABANDON_TIME, ABANDON_THRESHOLD, MAX_CALLS_QUEUED, HANDLE_TIME, CTVRU_TIME, SERVICE_LEVEL_CALLS, ROUTER_QUEUE_WAIT_TIME, MAX_SPEED_OF_ANSWER, CONTACT_INVENTORY_JEOPARDY, MEAN_HANDLE_TIME, SERVICE_LEVEL_ANSWERED_PERCENT, MEAN_SPEED_OF_ANSWER, MEAN_SPEED_TO_HANDLE, AVG_TIME_TO_ABANDON)
AS
      SELECT 
        CC_F_ACD_QUEUE_INTERVAL.D_DATE_ID,
        CC_D_CONTACT_QUEUE.D_PROJECT_ID,
        CC_D_CONTACT_QUEUE.D_PROGRAM_ID,
        CC_D_CONTACT_QUEUE.D_GEOGRAPHY_MASTER_ID,
        CC_D_CONTACT_QUEUE.D_UNIT_OF_WORK_ID,
        CC_F_ACD_QUEUE_INTERVAL.D_CONTACT_QUEUE_ID,
        CC_F_ACD_QUEUE_INTERVAL.QUEUE_NUMBER,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_RECEIVED_FROM_IVR) as CONTACTS_RECEIVED_FROM_IVR,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_ANSWERED) as CALLS_ANSWERED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.RAW_CONTACTS_OFFERED) as RAW_CONTACTS_OFFERED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_OFFERED) as CONTACTS_OFFERED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_HANDLED) as CONTACTS_HANDLED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_ABANDONED) as CONTACTS_ABANDONED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.LABOR_MINUTES_TOTAL) as LABOR_MINUTES_TOTAL,
        SUM(CC_F_ACD_QUEUE_INTERVAL.LABOR_MINUTES_AVAILABLE) as LABOR_MINUTES_AVAILABLE,
        SUM(CC_F_ACD_QUEUE_INTERVAL.LABOR_MINUTES_WAITING) as LABOR_MINUTES_WAITING,
        SUM(CC_F_ACD_QUEUE_INTERVAL.HEADCOUNT_TOTAL) as HEADCOUNT_TOTAL,
        SUM(CC_F_ACD_QUEUE_INTERVAL.HEADCOUNT_AVAILABLE) as HEADCOUNT_AVAILABLE,
        SUM(CC_F_ACD_QUEUE_INTERVAL.HEADCOUNT_UNAVAILABLE) as HEADCOUNT_UNAVAILABLE,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACT_INVENTORY) as CONTACT_INVENTORY,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_TRANSFERRED) as CONTACTS_TRANSFERRED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.OUTFLOW_CONTACTS) as OUTFLOW_CONTACTS,
        SUM(CC_F_ACD_QUEUE_INTERVAL.ANSWER_WAIT_TIME_TOTAL) as ANSWER_WAIT_TIME_TOTAL,
        SUM(CC_F_ACD_QUEUE_INTERVAL.ABANDON_TIME_TOTAL) as ABANDON_TIME_TOTAL,
        SUM(CC_F_ACD_QUEUE_INTERVAL.TALK_TIME_TOTAL) as TALK_TIME_TOTAL,
        SUM(CC_F_ACD_QUEUE_INTERVAL.AFTER_CALL_WORK_TIME_TOTAL) as AFTER_CALL_WORK_TIME_TOTAL,
        SUM(CC_F_ACD_QUEUE_INTERVAL.SERVICE_LEVEL_ANSWERED_COUNT) as SERVICE_LEVEL_ANSWERED_COUNT,
        SUM(CC_F_ACD_QUEUE_INTERVAL.SERVICE_LEVEL_ABANDONED) as SERVICE_LEVEL_ABANDONED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_ON_HOLD) as CALLS_ON_HOLD,
        SUM(CC_F_ACD_QUEUE_INTERVAL.HOLD_TIME_TOTAL) as HOLD_TIME_TOTAL,
        SUM(CC_F_ACD_QUEUE_INTERVAL.SHORT_ABANDONS) as SHORT_ABANDONS,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_BLOCKED) as CONTACTS_BLOCKED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.ICR_DEFAULT_ROUTED) as ICR_DEFAULT_ROUTED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.NETWORK_DEFAULT_ROUTED) as NETWORK_DEFAULT_ROUTED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.RETURN_BUSY) as RETURN_BUSY,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_RONA) as CALLS_RONA,
        SUM(CC_F_ACD_QUEUE_INTERVAL.RETURN_RELEASE) as RETURN_RELEASE,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_ROUTED_NON_AGENT) as CALLS_ROUTED_NON_AGENT,
        SUM(CC_F_ACD_QUEUE_INTERVAL.ERROR_COUNT) as ERROR_COUNT,
        SUM(CC_F_ACD_QUEUE_INTERVAL.AGENT_ERROR_COUNT) as AGENT_ERROR_COUNT,
        SUM(CC_F_ACD_QUEUE_INTERVAL.RETURN_RING) as RETURN_RING,
        SUM(CC_F_ACD_QUEUE_INTERVAL.INCOMPLETE_CALLS) as INCOMPLETE_CALLS,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_GIVEN_FORCE_DISCONNECT) as CALLS_GIVEN_FORCE_DISCONNECT,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_GIVEN_ROUTE_TO) as CALLS_GIVEN_ROUTE_TO,
        SUM(CC_F_ACD_QUEUE_INTERVAL.SHORT_CALLS) as SHORT_CALLS,
        MAX(CC_F_ACD_QUEUE_INTERVAL.MAX_ABANDON_TIME) as MAX_ABANDON_TIME,
        SUM(CC_F_ACD_QUEUE_INTERVAL.ABANDON_THRESHOLD) as ABANDON_THRESHOLD,
        MAX(CC_F_ACD_QUEUE_INTERVAL.MAX_CALLS_QUEUED) as MAX_CALLS_QUEUED,
        SUM(CC_F_ACD_QUEUE_INTERVAL.HANDLE_TIME) as HANDLE_TIME,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CTVRU_TIME) as CTVRU_TIME,
        SUM(CC_F_ACD_QUEUE_INTERVAL.SERVICE_LEVEL_CALLS) as SERVICE_LEVEL_CALLS,
        SUM(CC_F_ACD_QUEUE_INTERVAL.ROUTER_QUEUE_WAIT_TIME) as ROUTER_QUEUE_WAIT_TIME,
        MAX(CC_F_ACD_QUEUE_INTERVAL.MAX_SPEED_OF_ANSWER) as MAX_SPEED_OF_ANSWER,
        SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACT_INVENTORY_JEOPARDY) as CONTACT_INVENTORY_JEOPARDY,
        ROUND(( CASE WHEN SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_OFFERED)!=0 THEN (SUM(CC_F_ACD_QUEUE_INTERVAL.HANDLE_TIME)/SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_OFFERED))ELSE NULL END ),2)MEAN_HANDLE_TIME,
        ROUND(( CASE WHEN SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_ANSWERED)!=0 THEN (SUM(CC_F_ACD_QUEUE_INTERVAL.SERVICE_LEVEL_CALLS)/SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_ANSWERED))ELSE NULL END ),2) SERVICE_LEVEL_ANSWERED_PERCENT,
       ROUND(( CASE WHEN SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_ANSWERED)!=0 THEN (SUM(CC_F_ACD_QUEUE_INTERVAL.ROUTER_QUEUE_WAIT_TIME)/SUM(CC_F_ACD_QUEUE_INTERVAL.CALLS_ANSWERED))ELSE NULL END ),2) MEAN_SPEED_OF_ANSWER,
   ROUND(( CASE WHEN SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_OFFERED)!=0 THEN ((SUM(CC_F_ACD_QUEUE_INTERVAL.CTVRU_TIME) + SUM(CC_F_ACD_QUEUE_INTERVAL.ANSWER_WAIT_TIME_TOTAL) + SUM(CC_F_ACD_QUEUE_INTERVAL.TALK_TIME_TOTAL) + SUM(CC_F_ACD_QUEUE_INTERVAL.HOLD_TIME_TOTAL))/SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_OFFERED))ELSE NULL END ),2) MEAN_SPEED_TO_HANDLE,
   ROUND( ( CASE WHEN SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_ABANDONED)!=0 THEN (SUM(CC_F_ACD_QUEUE_INTERVAL.ABANDON_TIME_TOTAL)/SUM(CC_F_ACD_QUEUE_INTERVAL.CONTACTS_ABANDONED))ELSE NULL END ),2) AVG_TIME_TO_ABANDON
  FROM CC_F_ACD_QUEUE_INTERVAL
  INNER JOIN CC_D_CONTACT_QUEUE ON CC_F_ACD_QUEUE_INTERVAL.D_CONTACT_QUEUE_ID = CC_D_CONTACT_QUEUE.D_CONTACT_QUEUE_ID
  GROUP BY CC_F_ACD_QUEUE_INTERVAL.D_DATE_ID,
    CC_D_CONTACT_QUEUE.D_PROJECT_ID,
    CC_D_CONTACT_QUEUE.D_PROGRAM_ID,
    CC_D_CONTACT_QUEUE.D_GEOGRAPHY_MASTER_ID,
    CC_D_CONTACT_QUEUE.D_UNIT_OF_WORK_ID,
    CC_F_ACD_QUEUE_INTERVAL.D_CONTACT_QUEUE_ID,
    CC_F_ACD_QUEUE_INTERVAL.QUEUE_NUMBER;
     
-- Voicemail sematic views by hour, date and month

create or replace view cc_f_vm_call_hourly_sv (project_id, program_id, date_id, interval_hour, count_hourly)
as
select CC_D_CONTACT_QUEUE.D_PROJECT_ID, CC_D_CONTACT_QUEUE.D_PROGRAM_ID, CC_F_TERM_CALL_VM.d_date_id, CC_D_INTERVAL.interval_start_hour, count(*)
from cc_f_term_call_vm 
INNER JOIN CC_D_INTERVAL ON CC_F_TERM_CALL_VM.D_INTERVAL_ID = CC_D_INTERVAL.D_INTERVAL_ID
INNER JOIN CC_D_CONTACT_QUEUE ON CC_F_TERM_CALL_VM.D_CONTACT_QUEUE_ID = CC_D_CONTACT_QUEUE.D_CONTACT_QUEUE_ID
GROUP BY  CC_D_CONTACT_QUEUE.D_PROJECT_ID, CC_D_CONTACT_QUEUE.D_PROGRAM_ID, CC_F_TERM_CALL_VM.d_date_id, CC_D_INTERVAL.interval_start_hour;

create or replace view cc_f_vm_call_daily_sv (project_id, program_id, date_id, count_daily)
as
select CC_D_CONTACT_QUEUE.D_PROJECT_ID, CC_D_CONTACT_QUEUE.D_PROGRAM_ID, CC_F_TERM_CALL_VM.d_date_id, count(*)
from cc_f_term_call_vm 
INNER JOIN CC_D_CONTACT_QUEUE ON CC_F_TERM_CALL_VM.D_CONTACT_QUEUE_ID = CC_D_CONTACT_QUEUE.D_CONTACT_QUEUE_ID
group by CC_D_CONTACT_QUEUE.D_PROJECT_ID, CC_D_CONTACT_QUEUE.D_PROGRAM_ID, CC_F_TERM_CALL_VM.d_date_id;

create or replace view cc_f_vm_call_monthly_sv (project_id, program_id, month_name, month_number, year_name, count_monthly)
as
select CC_D_CONTACT_QUEUE.D_PROJECT_ID, CC_D_CONTACT_QUEUE.D_PROGRAM_ID, CC_D_DATES.d_month_name, CC_D_DATES.d_month_num, CC_D_DATES.d_year, count(*)
from cc_f_term_call_vm 
INNER JOIN CC_D_DATES ON CC_F_TERM_CALL_VM.D_DATE_ID = CC_D_DATES.D_DATE_ID
INNER JOIN CC_D_CONTACT_QUEUE ON CC_F_TERM_CALL_VM.D_CONTACT_QUEUE_ID = CC_D_CONTACT_QUEUE.D_CONTACT_QUEUE_ID
group by CC_D_CONTACT_QUEUE.D_PROJECT_ID, CC_D_CONTACT_QUEUE.D_PROGRAM_ID, CC_D_DATES.d_month_name, CC_D_DATES.d_month_num, CC_D_DATES.d_year;

     
grant select on CC_F_ACTUALS_QUEUE_BY_HOUR_SV to MAXDAT_READ_ONLY;     
grant select on CC_F_ACTUALS_QUEUE_BY_DATE_SV to MAXDAT_READ_ONLY; 
grant select on CC_F_ACD_QUEUE_BY_HOUR_SV to MAXDAT_READ_ONLY;     
grant select on CC_F_ACD_QUEUE_BY_DATE_SV to MAXDAT_READ_ONLY; 
grant select on CC_F_AGENT_RTG_GRP_BY_HOUR_SV to MAXDAT_READ_ONLY;
grant select on CC_F_AGENT_RTG_GRP_BY_DATE_SV to MAXDAT_READ_ONLY;  
grant select on CC_F_ACTUALS_IVR_BY_HOUR_SV to MAXDAT_READ_ONLY;
grant select on CC_F_ACTUALS_IVR_BY_DATE_SV to MAXDAT_READ_ONLY; 
grant select on CC_F_VM_CALL_HOURLY_SV TO MAXDAT_READ_ONLY;
grant select on CC_F_VM_CALL_DAILY_SV TO MAXDAT_READ_ONLY;
grant select on CC_F_VM_CALL_MONTHLY_SV TO MAXDAT_READ_ONLY;