delete from MAXDAT.CORP_ETL_MFB_FORM_STG;
delete from MAXDAT.CORP_ETL_MFB_BATCH_STG;
delete from MAXDAT.CORP_ETL_MFB_BATCH_EVENTS_STG;
delete from MAXDAT.CORP_ETL_MFB_BATCH_ARS_STG;

delete from MAXDAT.CORP_ETL_MFB_FORM_WIP;
delete from MAXDAT.CORP_ETL_MFB_ENVELOPE_WIP;
delete from MAXDAT.CORP_ETL_MFB_DOCUMENT_WIP;
delete from MAXDAT.CORP_ETL_MFB_BATCH_WIP;
delete from MAXDAT.CORP_ETL_MFB_BATCH_EVENTS_WIP;

delete from MAXDAT.CORP_ETL_MFB_ENVELOPE;
delete from MAXDAT.CORP_ETL_MFB_DOCUMENT;
delete from MAXDAT.CORP_ETL_MFB_ENVELOPE_STG;
delete from MAXDAT.CORP_ETL_MFB_DOCUMENT_STG;

delete from MAXDAT.CORP_ETL_MFB_FORM;
delete from MAXDAT.CORP_ETL_MFB_BATCH_EVENTS;
delete from MAXDAT.CORP_ETL_MFB_BATCH;

delete from MAXDAT.CORP_ETL_ERROR_LOG where process_name ='PROCESSMAILFAXBATCH';
delete from MAXDAT.CORP_ETL_JOB_STATISTICS where JOB_NAME like '%MFB%';

update MAXDAT.CORP_ETL_CONTROL set VALUE=to_date('01-Jan-2013') where name in('MFB_REMOTE_LAST_UPDATE_DATE','MFB_CENTRAL_LAST_UPDATE_DATE','MFB_ARS_LAST_UPDATE_DATE');

commit;

