ALTER SESSION SET CURRENT_SCHEMA=CISCO_ENTERPRISE_CC;

/* UNIT OF WORK */
INSERT INTO CC_C_UNIT_OF_WORK 
    (UNIT_OF_WORK_NAME, UNIT_OF_WORK_CATEGORY, RECORD_EFF_DT, RECORD_END_DT, ACD, IVR) VALUES
    ('BROKER','Inbound',to_date('1900/01/01', 'yyyy/mm/dd'),to_date('2999/12/31', 'yyyy/mm/dd'), 1, 0);

-- select * from cc_c_unit_of_work where unit_of_work_name='BROKER'
-- 1228

INSERT INTO CC_D_UNIT_OF_WORK 
(UNIT_OF_WORK_NAME, UNIT_OF_WORK_CATEGORY, PRODUCTION_PLAN_ID, HOURLY_FLAG, HANDLE_TIME_UNIT, ACD, IVR) VALUES
    ('BROKER','Inbound', 1, 'N', 'Seconds', 1, 0);

-- select * from cc_d_unit_of_work where unit_of_work_name='BROKER'
-- 2668

/* CC_C_CONTACT_QUEUE */
UPDATE CC_C_CONTACT_QUEUE SET UNIT_OF_WORK_NAME='MEDICAID' WHERE QUEUE_NUMBER='5219';
UPDATE CC_C_CONTACT_QUEUE SET UNIT_OF_WORK_NAME='MEDICAID - SPA' WHERE QUEUE_NUMBER='5226';
UPDATE CC_C_CONTACT_QUEUE SET UNIT_OF_WORK_NAME='BROKER' WHERE QUEUE_NUMBER='5265';
UPDATE CC_C_CONTACT_QUEUE SET UNIT_OF_WORK_NAME='CAC' WHERE QUEUE_NUMBER='5845';
UPDATE CC_C_CONTACT_QUEUE SET UNIT_OF_WORK_NAME='CAC' WHERE QUEUE_NUMBER='5851';

/* CC_S_CONTACT_QUEUE */
UPDATE CC_S_CONTACT_QUEUE SET UNIT_OF_WORK_ID = (SELECT UNIT_OF_WORK_ID FROM CC_C_UNIT_OF_WORK WHERE UNIT_OF_WORK_NAME='MEDICAID') WHERE QUEUE_NUMBER='5219';
UPDATE CC_S_CONTACT_QUEUE SET UNIT_OF_WORK_ID = (SELECT UNIT_OF_WORK_ID FROM CC_C_UNIT_OF_WORK WHERE UNIT_OF_WORK_NAME='MEDICAID - SPA') WHERE QUEUE_NUMBER='5226';
UPDATE CC_S_CONTACT_QUEUE SET UNIT_OF_WORK_ID = (SELECT UNIT_OF_WORK_ID FROM CC_C_UNIT_OF_WORK WHERE UNIT_OF_WORK_NAME='BROKER') WHERE QUEUE_NUMBER='5265';
UPDATE CC_S_CONTACT_QUEUE SET UNIT_OF_WORK_ID = (SELECT UNIT_OF_WORK_ID FROM CC_C_UNIT_OF_WORK WHERE UNIT_OF_WORK_NAME='CAC') WHERE QUEUE_NUMBER='5845';
UPDATE CC_S_CONTACT_QUEUE SET UNIT_OF_WORK_ID = (SELECT UNIT_OF_WORK_ID FROM CC_C_UNIT_OF_WORK WHERE UNIT_OF_WORK_NAME='CAC') WHERE QUEUE_NUMBER='5851';

/* CC_F_ACD_AGENT_INTERVAL */
SELECT COUNT(*) FROM CC_F_ACD_AGENT_INTERVAL WHERE QUEUE_NUMBER='5219';
UPDATE CC_F_ACD_AGENT_INTERVAL SET D_UNIT_OF_WORK_ID = (SELECT UOW_ID FROM CC_D_UNIT_OF_WORK WHERE UNIT_OF_WORK_NAME='MEDICAID') WHERE QUEUE_NUMBER='5219';

SELECT COUNT(*) FROM CC_F_ACD_AGENT_INTERVAL WHERE QUEUE_NUMBER='5226';
UPDATE CC_F_ACD_AGENT_INTERVAL SET D_UNIT_OF_WORK_ID = (SELECT UOW_ID FROM CC_D_UNIT_OF_WORK WHERE UNIT_OF_WORK_NAME='MEDICAID - SPA') WHERE QUEUE_NUMBER='5226';

SELECT COUNT(*) FROM CC_F_ACD_AGENT_INTERVAL WHERE QUEUE_NUMBER='5265';
UPDATE CC_F_ACD_AGENT_INTERVAL SET D_UNIT_OF_WORK_ID = (SELECT UOW_ID FROM CC_D_UNIT_OF_WORK WHERE UNIT_OF_WORK_NAME='BROKER') WHERE QUEUE_NUMBER='5265';

SELECT COUNT(*) FROM CC_F_ACD_AGENT_INTERVAL WHERE QUEUE_NUMBER='5845';
UPDATE CC_F_ACD_AGENT_INTERVAL SET D_UNIT_OF_WORK_ID = (SELECT UOW_ID FROM CC_D_UNIT_OF_WORK WHERE UNIT_OF_WORK_NAME='CAC' AND UNIT_OF_WORK_CATEGORY='INBOUND') WHERE QUEUE_NUMBER='5845';

SELECT COUNT(*) FROM CC_F_ACD_AGENT_INTERVAL WHERE QUEUE_NUMBER='5851';
UPDATE CC_F_ACD_AGENT_INTERVAL SET D_UNIT_OF_WORK_ID = (SELECT UOW_ID FROM CC_D_UNIT_OF_WORK WHERE UNIT_OF_WORK_NAME='CAC' AND UNIT_OF_WORK_CATEGORY='INBOUND') WHERE QUEUE_NUMBER='5851';

COMMIT;

