ALTER SESSION SET CURRENT_SCHEMA = MAXDAT;

UPDATE MAXDAT.CORP_ETL_CONTROL SET VALUE = '27-JUL-17' WHERE NAME IN ('MFB_REMOTE_LAST_UPDATE_DATE','MFB_CENTRAL_LAST_UPDATE_DATE','MFB_ARS_LAST_UPDATE_DATE');

/* UPDATE MAXDAT.CORP_ETL_CONTROL SET VALUE = '1' WHERE NAME IN ('MFB_REMOTE_LOOKBACK_DAYS','MFB_CENTRAL_LOOKBACK_DAYS','MFB_ARS_LOOKBACK_DAYS'); */

COMMIT;

