update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='',	letter_inv_name =''	where report_label = 'MCAPP';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='',	letter_inv_name =''	where report_label = 'APCC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group V',	letter_inv_name ='MIRx Application'	where report_label = 'MIRXAPP';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group Z',	letter_inv_name ='PHCR'	where report_label = 'PHCR';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group A',	letter_inv_name ='CN'	where report_label = 'CN';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group A',	letter_inv_name ='CNC'	where report_label = 'CNC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group D',	letter_inv_name ='CNCM'	where report_label = 'CNCM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group B',	letter_inv_name ='CND'	where report_label = 'CND';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group C',	letter_inv_name ='CNH'	where report_label = 'CNH';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group C',	letter_inv_name ='CNHC'	where report_label = 'CNHC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group D',	letter_inv_name ='CNM'	where report_label = 'CNM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group A',	letter_inv_name ='CNV'	where report_label = 'CNV';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group A',	letter_inv_name ='CNVC'	where report_label = 'CNVC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group B',	letter_inv_name ='CNVD'	where report_label = 'CNVD';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group C',	letter_inv_name ='CNVH'	where report_label = 'CNVH';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group D',	letter_inv_name ='CNVM'	where report_label = 'CNVM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group D',	letter_inv_name ='CVCM'	where report_label = 'CVCM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group C',	letter_inv_name ='CVHC'	where report_label = 'CVHC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AD',	letter_inv_name ='SDFC'	where report_label = 'SDFC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group A',	letter_inv_name ='DE'	where report_label = 'DE';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group A',	letter_inv_name ='DEC'	where report_label = 'DEC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group D',	letter_inv_name ='DECM'	where report_label = 'DECM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group C',	letter_inv_name ='DEH'	where report_label = 'DEH';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group C',	letter_inv_name ='DEHC'	where report_label = 'DEHC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group E',	letter_inv_name ='DEM'	where report_label = 'DEM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group E',	letter_inv_name ='DEMC'	where report_label = 'DEMC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group S',	letter_inv_name ='BCF'	where report_label = 'BCF';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group U',	letter_inv_name ='HRF'	where report_label = 'HRF';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group F',	letter_inv_name ='FI'	where report_label = 'FI';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group F',	letter_inv_name ='FIC'	where report_label = 'FIC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group F',	letter_inv_name ='FI'	where report_label = 'FICM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group F',	letter_inv_name ='FI'	where report_label = 'FID';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group M',	letter_inv_name ='FIM'	where report_label = 'FIM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='',	letter_inv_name =''	where report_label = 'Forms';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AO',	letter_inv_name ='FWCLA'	where report_label = 'FWCLA';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AO',	letter_inv_name ='FWCLA'	where report_label = 'FWCLB';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BI',	letter_inv_name ='FWDD'	where report_label = 'FWDD';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AM',	letter_inv_name ='FWIC with Coupons'	where report_label = 'FWIC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AO',	letter_inv_name ='FWLP'	where report_label = 'FWLP';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AO',	letter_inv_name ='FWPP  '	where report_label = 'FWPP';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AO',	letter_inv_name ='FWRA'	where report_label = 'FWRA';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BE',	letter_inv_name ='FWRL'	where report_label = 'FWRL';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BE',	letter_inv_name ='FWRT'	where report_label = 'FWRT';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AO',	letter_inv_name ='FWWLA'	where report_label = 'FWWLA';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AO',	letter_inv_name ='FWWLA'	where report_label = 'FWWLB';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AC',	letter_inv_name ='MCFL'	where report_label = 'MCFL';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AG',	letter_inv_name ='HLAR'	where report_label = 'HLAR';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AE',	letter_inv_name ='HLCN'	where report_label = 'HLCN';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AG',	letter_inv_name ='HLDD'	where report_label = 'HLDD';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AG',	letter_inv_name ='HLEC'	where report_label = 'HLEC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AF',	letter_inv_name ='HLED'	where report_label = 'HLED';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AG',	letter_inv_name ='HLEU'	where report_label = 'HLEU';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AH',	letter_inv_name ='HLOO'	where report_label = 'HLOO';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AG',	letter_inv_name ='HLRI'	where report_label = 'HLRI';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AK',	letter_inv_name ='HLSP'	where report_label = 'HLSP';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AL',	letter_inv_name ='HLTP'	where report_label = 'HLTP';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AI',	letter_inv_name ='HLVE'	where report_label = 'HLVE';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group G',	letter_inv_name ='HMPD'	where report_label = 'HMPD';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='',	letter_inv_name =''	where report_label = 'HUG';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AA',	letter_inv_name ='RRB'	where report_label = 'RRB';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group H',	letter_inv_name ='IA'	where report_label = 'IA';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group I',	letter_inv_name ='IAC'	where report_label = 'IAC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group J',	letter_inv_name ='IACM'	where report_label = 'IACM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group I',	letter_inv_name ='IAH'	where report_label = 'IAH';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group I',	letter_inv_name ='IAHC'	where report_label = 'IAHC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group J',	letter_inv_name ='IAM'	where report_label = 'IAM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group W',	letter_inv_name ='MFFS'	where report_label = 'MFFS';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group T',	letter_inv_name ='HMPH'	where report_label = 'HMPH';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AP',	letter_inv_name ='MCCL'	where report_label = 'MCCL';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BJ',	letter_inv_name ='MCDD'	where report_label = 'MCDD';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group D',	letter_inv_name ='MCDE'	where report_label = 'MCDE';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='',	letter_inv_name =''	where report_label = 'MCDM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AB',	letter_inv_name ='MCIB'	where report_label = 'MCIB';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AP',	letter_inv_name ='MCIC'	where report_label = 'MCIC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AP',	letter_inv_name ='MCLP'	where report_label = 'MCLP';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AP',	letter_inv_name ='MCMA'	where report_label = 'MCMA';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AP',	letter_inv_name ='MCPP'	where report_label = 'MCPP';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AP',	letter_inv_name ='MCRA'	where report_label = 'MCRA';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BD',	letter_inv_name ='MCRL'	where report_label = 'MCRL';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BD',	letter_inv_name ='MCRT'	where report_label = 'MCRT';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AP',	letter_inv_name ='MCWLA'	where report_label = 'MCWLA';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AP',	letter_inv_name ='MCWLB'	where report_label = 'MCWLB';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group A',	letter_inv_name ='MDE'	where report_label = 'MDE';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group A',	letter_inv_name ='MDEC'	where report_label = 'MDEC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AS',	letter_inv_name ='MHAL'	where report_label = 'MHAL';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AT',	letter_inv_name ='MHALR with Coupon'	where report_label = 'MHALR';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AR',	letter_inv_name ='MHCL'	where report_label = 'MHCL';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AR',	letter_inv_name ='MHCLR'	where report_label = 'MHCLR';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BH',	letter_inv_name ='MHDD'	where report_label = 'MHDD';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='',	letter_inv_name =''	where report_label = 'MHLP';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='',	letter_inv_name =''	where report_label = 'MHLPR';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AV',	letter_inv_name ='MHNF'	where report_label = 'MHNF';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AV',	letter_inv_name ='MHNF'	where report_label = 'MHNFR';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AV',	letter_inv_name ='MHOA'	where report_label = 'MHOA';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AV',	letter_inv_name ='MHOA'	where report_label = 'MHOAR';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AU',	letter_inv_name ='MHPO'	where report_label = 'MHPO';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='',	letter_inv_name =''	where report_label = 'MHPOR';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AW',	letter_inv_name ='MHPR'	where report_label = 'MHPR';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AW',	letter_inv_name ='MHPR'	where report_label = 'MHPRR';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BC',	letter_inv_name ='MHQS'	where report_label = 'MHQS';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BF',	letter_inv_name ='MHRL'	where report_label = 'MHRL';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BG',	letter_inv_name ='MHRLR'	where report_label = 'MHRLR';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BC',	letter_inv_name ='MHQS'	where report_label = 'MHRS';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BF',	letter_inv_name ='MHRT'	where report_label = 'MHRT';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BG',	letter_inv_name ='MHRTR'	where report_label = 'MHRTR';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BF',	letter_inv_name ='MHVL'	where report_label = 'MHVL';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BG',	letter_inv_name ='MHVLR'	where report_label = 'MHVLR';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BF',	letter_inv_name ='MHVT'	where report_label = 'MHVT';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BG',	letter_inv_name ='MHVTR'	where report_label = 'MHVTR';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AX',	letter_inv_name ='MHWB'	where report_label = 'MHWB';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AX',	letter_inv_name ='MHWB'	where report_label = 'MHWBR';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='',	letter_inv_name =''	where report_label = 'HC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group K',	letter_inv_name ='MPI'	where report_label = 'MPI';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AZ',	letter_inv_name ='Open Enrollment Under 21 OE'	where report_label = 'OE';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AY',	letter_inv_name ='OEC'	where report_label = 'OEC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BB',	letter_inv_name ='OECM Under 21'	where report_label = 'OECM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group B',	letter_inv_name ='OED'	where report_label = 'OED';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AY',	letter_inv_name ='OEHC'	where report_label = 'OEHC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group AZ',	letter_inv_name ='OEHM'	where report_label = 'OEHM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group BA',	letter_inv_name ='OEM'	where report_label = 'OEM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='',	letter_inv_name =''	where report_label = 'OTHER';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group F',	letter_inv_name ='RC'	where report_label = 'RC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group F',	letter_inv_name ='RCC'	where report_label = 'RCC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group M',	letter_inv_name ='RCCM'	where report_label = 'RCCM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group L',	letter_inv_name ='RCH'	where report_label = 'RCH';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group L',	letter_inv_name ='RCHC'	where report_label = 'RCHC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group M',	letter_inv_name ='RCM'	where report_label = 'RCM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group F',	letter_inv_name ='RE'	where report_label = 'RE';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group F',	letter_inv_name ='REC'	where report_label = 'REC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group M',	letter_inv_name ='RECM'	where report_label = 'RECM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group F',	letter_inv_name ='REH'	where report_label = 'REH';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group F',	letter_inv_name ='REH'	where report_label = 'REHC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group M',	letter_inv_name ='REM'	where report_label = 'REM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group F',	letter_inv_name ='RMC'	where report_label = 'RMC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group M',	letter_inv_name ='RMCM'	where report_label = 'RMCM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group F',	letter_inv_name ='RMH'	where report_label = 'RMH';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group F',	letter_inv_name ='RMHC'	where report_label = 'RMHC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group M',	letter_inv_name ='RMM'	where report_label = 'RMM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group B',	letter_inv_name ='RMR'	where report_label = 'RMR';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group N',	letter_inv_name ='VM'	where report_label = 'VM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group N',	letter_inv_name ='VMC'	where report_label = 'VMC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group P',	letter_inv_name ='VMCM'	where report_label = 'VMCM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group O',	letter_inv_name ='VMH'	where report_label = 'VMH';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group O',	letter_inv_name ='VMHC'	where report_label = 'VMHC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group P',	letter_inv_name ='VMM'	where report_label = 'VMM';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group Q',	letter_inv_name ='WCINC'	where report_label = 'WCINC';
update MAXDAT_MITRAN.D_LETTER_DEFINITION set group_name ='Group Q',	letter_inv_name ='WDNCH'	where report_label = 'WDNCH';
