CREATE OR REPLACE VIEW SC_LAG_TIME_SV
AS
select
lag_date
,agent_id
--,supervisor_id
,Tot_Sched_Productive_Time
from SC_LAG_TIME a
WHERE  create_date = (SELECT max(create_date) FROM SC_LAG_TIME b WHERE a.LAG_DATE = b.LAG_DATE AND a.AGENT_ID = b.AGENT_ID)
WITH READ ONLY;

GRANT SELECT ON DP_SCORECARD.SC_LAG_TIME_SV TO MAXDAT;
GRANT SELECT ON DP_SCORECARD.SC_LAG_TIME_SV TO MAXDAT_READ_ONLY;

