DROP TABLE DP_SCORECARD.SC_SUMMARY_CC_ROLLUP CASCADE CONSTRAINTS;

CREATE TABLE DP_SCORECARD.SC_SUMMARY_CC_ROLLUP
(
  SUPERVISOR_STAFF_ID           NUMBER(38),
  DATES_MONTH                   VARCHAR2(36 BYTE),
  DATES_MONTH_NUM               VARCHAR2(6 BYTE),
  DATES_YEAR                    VARCHAR2(41 BYTE),
  BUILDING                      VARCHAR2(100 BYTE),
  DEPARTMENT                    VARCHAR2(50 BYTE),
  EXCLUSION_FLAG                VARCHAR2(1 BYTE),
  TOT_CALLS_ANSWERED            NUMBER,
  TOT_SHORT_CALLS_ANSWERED      NUMBER,
  TOT_TOT_RETURN_TO_QUEUE       NUMBER,
  TOT_AVERAGE_HANDLE_TIME       NUMBER,
  TOT_SCHED_PRODUCTIVE_TIME     NUMBER,
  TOT_ACTUAL_PRODUCTIVE_TIME    NUMBER,
  TOT_TALK_TIME                 NUMBER,
  TOT_WRAP_UP_TIME              NUMBER,
  TOT_LOGGED_IN_TIME            NUMBER,
  TOT_NOT_READY_TIME            NUMBER,
  TOT_BREAK_TIME                NUMBER,
  TOT_LUNCH_TIME                NUMBER,
  QCS_PERFORMED                 NUMBER,
  AVG_QC_SCORE                  NUMBER,
  TOT_INCIDENTS_COMPLETED       NUMBER,
  DAYS_INCIDENTS_COMPLETED      NUMBER,
  TOT_DEFECTS_COMPLETED         NUMBER,
  DAYS_DEFECTS_COMPLETED        NUMBER,
  LAG_TIME_TOT_SCHED_PROD_TIME  NUMBER,
  TOT_CALL_RECORDS              NUMBER,
  TOT_CUSTOMER_COUNT            NUMBER,
  TOT_CALL_WRAP_UP_COUNT        NUMBER,
  TOT_WRAP_UP_ERROR             NUMBER,
  DAYS_SHORT_CALLS_GT_10        NUMBER,
  DAYS_CALLS_ANSWERED           NUMBER,
  ADHERENCE                     NUMBER,
  TOT_RETURN_TO_QUEUE_TIMEOUT   NUMBER,
  AVG_ATTENDANCE_BALANCE        NUMBER,
  AVG_ATTENDANCE_TOTAL_BALANCE  NUMBER,
  STAFF_COUNT                   NUMBER,
  SUM_QC_SCORE                  NUMBER,
  COUNT_QC_SCORE                NUMBER,
  QCS_REMAINING                 NUMBER,
  TOT_HANDLE_TIME               NUMBER,
  TOT_HANDLE_TIME_COUNT         NUMBER,
  STAFF_TRTQ_COUNT              NUMBER,
  SHORT_CALL_AGENT_COUNT        NUMBER
)
TABLESPACE MAXDAT_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX DP_SCORECARD.SC_SUMMARY_CC_RU_MON_NUM_NDX ON DP_SCORECARD.SC_SUMMARY_CC_ROLLUP
(DATES_MONTH_NUM)
LOGGING
TABLESPACE MAXDAT_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX DP_SCORECARD.SC_SUMMARY_CC_RU_SUP_ID_NDX ON DP_SCORECARD.SC_SUMMARY_CC_ROLLUP
(SUPERVISOR_STAFF_ID)
LOGGING
TABLESPACE MAXDAT_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON DP_SCORECARD.SC_SUMMARY_CC_ROLLUP TO MAXDAT;

GRANT SELECT ON DP_SCORECARD.SC_SUMMARY_CC_ROLLUP TO MAXDAT_READ_ONLY;

GRANT SELECT ON DP_SCORECARD.SC_SUMMARY_CC_ROLLUP TO DP_SCORECARD_READ_ONLY;
