
INSERT INTO DP_SCORECARD.ENGAGE_FORM_TYPE(FORM_TYPE_ID, EVALUATION_FORM, SCORECARD_SCORE_TYPE, SCORECARD_GROUP, CREATE_BY, CREATE_DATETIME, START_DATE, END_DATE) VALUES (517, 'QC_NYSOH_EE_Verification Docs_v3.2_LSC Added', 'QC', 'E&E', 'script', sysdate, sysdate, null);
INSERT INTO DP_SCORECARD.ENGAGE_FORM_TYPE(FORM_TYPE_ID, EVALUATION_FORM, SCORECARD_SCORE_TYPE, SCORECARD_GROUP, CREATE_BY, CREATE_DATETIME, START_DATE, END_DATE) VALUES (518, 'Supe Review_QC_NYSOH_EE_Verification Docs_v3.2_LSC Added', 'QCT', 'QCT', 'script', sysdate, sysdate, null);
commit;

