delete from dp_scorecard.scorecard_attendance_mthly where staff_staff_id = 13208 and dates_month_num = 201610;
delete from dp_scorecard.scorecard_attendance_mthly where staff_staff_id = 13208 and dates_month_num = 201611;
delete from dp_scorecard.scorecard_attendance_mthly where staff_staff_id = 13208 and dates_month_num = 201612;
delete from dp_scorecard.scorecard_attendance_mthly where staff_staff_id = 13208 and dates_month_num = 201701;
delete from dp_scorecard.scorecard_attendance_mthly where staff_staff_id = 13208 and dates_month_num = 201702;
delete from dp_scorecard.scorecard_attendance_mthly where staff_staff_id = 13208 and dates_month_num = 201703;
delete from dp_scorecard.scorecard_attendance_mthly where staff_staff_id = 13208 and dates_month_num = 201704;
delete from dp_scorecard.scorecard_attendance_mthly where staff_staff_id = 13208 and dates_month_num = 201705;
delete from dp_scorecard.scorecard_attendance_mthly where staff_staff_id = 13208 and dates_month_num = 201706;
delete from dp_scorecard.scorecard_attendance_mthly where staff_staff_id = 13208 and dates_month_num = 201707;
delete from dp_scorecard.scorecard_attendance_mthly where staff_staff_id = 13208 and dates_month_num = 201708;
delete from dp_scorecard.scorecard_attendance_mthly where staff_staff_id = 13208 and dates_month_num = 201709;

commit;