
INSERT INTO DP_SCORECARD.ENGAGE_FORM_TYPE(FORM_TYPE_ID, EVALUATION_FORM, SCORECARD_SCORE_TYPE, SCORECARD_GROUP, CREATE_BY, CREATE_DATETIME, START_DATE, END_DATE) VALUES (521, 'QC_FPBP_Doc Management_v1.0', 'QC', null, 'script', sysdate, sysdate, null);
INSERT INTO DP_SCORECARD.ENGAGE_FORM_TYPE(FORM_TYPE_ID, EVALUATION_FORM, SCORECARD_SCORE_TYPE, SCORECARD_GROUP, CREATE_BY, CREATE_DATETIME, START_DATE, END_DATE) VALUES (522, 'Supe Review_FPBP_Doc Management_v1.0', 'QCT', null, 'script', sysdate, sysdate, null);
commit;

