---- JIRA (NYHIX-29597) Engage Form Type Table Additions (2017-03-01)
INSERT INTO DP_SCORECARD.ENGAGE_FORM_TYPE(FORM_TYPE_ID, EVALUATION_FORM, SCORECARD_SCORE_TYPE, SCORECARD_GROUP, CREATE_BY, CREATE_DATETIME, START_DATE, END_DATE) VALUES (525, 'QC_NYSOH_EE_Account Review Unit_v1.4 ', 'QC', 'E&E', 'script', sysdate, sysdate, null);
INSERT INTO DP_SCORECARD.ENGAGE_FORM_TYPE(FORM_TYPE_ID, EVALUATION_FORM, SCORECARD_SCORE_TYPE, SCORECARD_GROUP, CREATE_BY, CREATE_DATETIME, START_DATE, END_DATE) VALUES (526, 'Supe Review_QC_NYSOH_EE_Account Review Unit_v1.4', 'QCT', 'QCT', 'script', sysdate, sysdate, null);
commit;

