---------------------------
-- CREATE BACKUPS
---------------------------


CREATE TABLE DP_SCORECARD.SC_AUDIT_PAYROLL_20181102_BAK
AS SELECT * FROM DP_SCORECARD.SC_AUDIT_PAYROLL;

GRANT SELECT ON DP_SCORECARD.SC_AUDIT_PAYROLL_20181102_BAK TO MAXDAT; 
                                      
GRANT SELECT ON DP_SCORECARD.SC_AUDIT_PAYROLL_20181102_BAK TO MAXDAT_REPORTS; 
                                      
GRANT SELECT ON DP_SCORECARD.SC_AUDIT_PAYROLL_20181102_BAK TO MAXDAT_READ_ONLY; 
                                      
GRANT SELECT ON DP_SCORECARD.SC_AUDIT_PAYROLL_20181102_BAK TO DP_SCORECARD_READ_ONLY; 


CREATE TABLE DP_SCORECARD.SC_AUDIT_PAYROLL_AUDIT_20181102_BAK
AS SELECT * FROM DP_SCORECARD.SC_AUDIT_PAYROLL_AUDIT;

GRANT SELECT ON DP_SCORECARD.SC_AUDIT_PAYROLL_AUDIT_20181102_BAK TO MAXDAT; 
                                      
GRANT SELECT ON DP_SCORECARD.SC_AUDIT_PAYROLL_AUDIT_20181102_BAK TO MAXDAT_REPORTS; 
                                      
GRANT SELECT ON DP_SCORECARD.SC_AUDIT_PAYROLL_AUDIT_20181102_BAK TO MAXDAT_READ_ONLY; 
                                      
GRANT SELECT ON DP_SCORECARD.SC_AUDIT_PAYROLL_AUDIT_20181102_BAK TO DP_SCORECARD_READ_ONLY; 


---------------------------
-- DROP THE TRIGGERS
---------------------------

DROP TRIGGER DP_SCORECARD.TRG_AIU_SC_AUDIT_PAYROLL;

DROP TRIGGER DP_SCORECARD.TRG_BIU_SC_AUDIT_PAYROLL;

---------------------------
-- ADD THE NEW COLUMN
---------------------------

ALTER TABLE DP_SCORECARD.SC_AUDIT_PAYROLL
ADD SUPERVISOR_STAFF_ID NUMBER(10);

ALTER TABLE  DP_SCORECARD.SC_AUDIT_PAYROLL_AUDIT
ADD SUPERVISOR_STAFF_ID NUMBER(10);


