insert into dp_scorecard.SC_DISCUSSION_LKUP values(52,'Compliance',to_date('7/7/2077','mm/dd/yyyy'),'CR 1834',trunc(sysdate));

insert into dp_scorecard.SC_DISCUSSION_LKUP values(53,'Kudos-QC',to_date('7/7/2077','mm/dd/yyyy'),'CR 1834',trunc(sysdate));

insert into dp_scorecard.SC_DISCUSSION_LKUP values(54,'Kudos-Other',to_date('7/7/2077','mm/dd/yyyy'),'CR 1834',trunc(sysdate));

insert into dp_scorecard.SC_DISCUSSION_LKUP values(55,'Mentor',to_date('7/7/2077','mm/dd/yyyy'),'CR 1834',trunc(sysdate));

insert into dp_scorecard.SC_DISCUSSION_LKUP values(56,'Performance',to_date('7/7/2077','mm/dd/yyyy'),'CR 1834',trunc(sysdate));

insert into dp_scorecard.SC_DISCUSSION_LKUP values(57,'Performance Development',to_date('7/7/2077','mm/dd/yyyy'),'CR 1834',trunc(sysdate));

insert into dp_scorecard.SC_DISCUSSION_LKUP values(58,'Quarterly Excellence',to_date('7/7/2077','mm/dd/yyyy'),'CR 1834',trunc(sysdate));

insert into dp_scorecard.SC_DISCUSSION_LKUP values(59,'Quarterly Performance Review',to_date('7/7/2077','mm/dd/yyyy'),'CR 1834',trunc(sysdate));

insert into dp_scorecard.SC_DISCUSSION_LKUP values(60,'QPP',to_date('7/7/2077','mm/dd/yyyy'),'CR 1834',trunc(sysdate));

insert into dp_scorecard.SC_DISCUSSION_LKUP values(61,'Shadower',to_date('7/7/2077','mm/dd/yyyy'),'CR 1834',trunc(sysdate));

insert into dp_scorecard.SC_DISCUSSION_LKUP values(62,'Technical Issues',to_date('7/7/2077','mm/dd/yyyy'),'CR 1834',trunc(sysdate));

insert into dp_scorecard.SC_DISCUSSION_LKUP values(63,'Team Meeting',to_date('7/7/2077','mm/dd/yyyy'),'CR 1834',trunc(sysdate));

insert into dp_scorecard.SC_DISCUSSION_LKUP values(64,'Time Keeping',to_date('7/7/2077','mm/dd/yyyy'),'CR 1834',trunc(sysdate));

Commit;