SET DEFINE OFF;
--SQL Statement which produced this data:
--
--  select * from SC_ATTENDANCE_initial_score;
--
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (4195, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (12960, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (5173, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (6972, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (5177, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (16156, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (14990, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (12992, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (5178, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (16157, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (10612, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (16152, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (4188, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (4196, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (14175, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (13526, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (4316, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (14180, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (4310, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (4903, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (13941, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (14992, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (5156, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (5182, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (16145, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (13906, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (16147, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (13937, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (16143, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
Insert into DP_SCORECARD.SC_ATTENDANCE_INITIAL_SCORE
   (STAFF_ID, ATTENDANCE_POINTS, START_DATE)
 Values
   (3578, 40, TO_DATE('12/31/2016', 'MM/DD/YYYY'));
COMMIT;
