-- NYHIX-46155
SELECT *  -- 1 record
FROM DP_SCORECARD.Sc_Lag_Time
WHERE (AGENT_ID = '246066' AND TRUNC(LAG_DATE) IN (TO_DATE('03-DEC-18','DD-MON-RR')));

delete from DP_SCORECARD.Sc_Lag_Time
WHERE (AGENT_ID = '246066' AND TRUNC(LAG_DATE) IN (TO_DATE('03-DEC-18','DD-MON-RR')));

commit;

SELECT *  -- 0 records
FROM DP_SCORECARD.Sc_Lag_Time
WHERE (AGENT_ID = '246066' AND TRUNC(LAG_DATE) IN (TO_DATE('03-DEC-18','DD-MON-RR')));

