-- NYHIX-44707
SELECT *  -- 2 records
FROM DP_SCORECARD.Sc_Lag_Time
WHERE (AGENT_ID = '148294' AND TRUNC(LAG_DATE) BETWEEN TO_DATE('14-SEP-18','DD-MON-RR') AND TO_DATE('28-SEP-18','DD-MON-RR'))
OR (AGENT_ID = '136277' AND TRUNC(LAG_DATE) IN (TO_DATE('07-SEP-18','DD-MON-RR')));


delete from DP_SCORECARD.Sc_Lag_Time
WHERE (AGENT_ID = '148294' AND TRUNC(LAG_DATE) BETWEEN TO_DATE('14-SEP-18','DD-MON-RR') AND TO_DATE('28-SEP-18','DD-MON-RR'))
OR (AGENT_ID = '136277' AND TRUNC(LAG_DATE) IN (TO_DATE('07-SEP-18','DD-MON-RR')));

commit;

SELECT *  -- 2 records
FROM DP_SCORECARD.Sc_Lag_Time
WHERE (AGENT_ID = '148294' AND TRUNC(LAG_DATE) BETWEEN TO_DATE('14-SEP-18','DD-MON-RR') AND TO_DATE('28-SEP-18','DD-MON-RR'))
OR (AGENT_ID = '136277' AND TRUNC(LAG_DATE) IN (TO_DATE('07-SEP-18','DD-MON-RR')));

