grant execute,debug on DP_SCORECARD.INSERT_SC_AUDIT_LWOP to maxdat_reports; 

grant execute,debug  on DP_SCORECARD.INSERT_SC_AUDIT_LWOP to maxdat;

grant execute,debug  on DP_SCORECARD.INSERT_SC_AUDIT_LWOP to MAXDAT_MSTR_TRX_RPT;

grant execute,debug  on DP_SCORECARD.INSERT_SC_AUDIT_LWOP to maxdat_read_only;

grant execute,debug  on DP_SCORECARD.UPDATE_SC_AUDIT_LWOP to maxdat_reports;

grant execute,debug  on DP_SCORECARD.UPDATE_SC_AUDIT_LWOP to maxdat;

grant execute,debug  on DP_SCORECARD.UPDATE_SC_AUDIT_LWOP to MAXDAT_MSTR_TRX_RPT;

grant execute,debug  on DP_SCORECARD.UPDATE_SC_AUDIT_LWOP to maxdat_read_only;


Commit;
/