CREATE OR REPLACE FORCE EDITIONABLE VIEW DP_SCORECARD.SCORECARD_SUMMARY_CC_ROLLUP_SV 
  (SUPERVISOR_STAFF_ID, D_DATE, DATES_MONTH, DATES_MONTH_NUM, DATES_YEAR, DATES_QTR_YEAR, BUILDING, DEPARTMENT, EXCLUSION_FLAG, 
  TOT_CALLS_ANSWERED, TOT_SHORT_CALLS_ANSWERED, TOT_TOT_RETURN_TO_QUEUE, TOT_AVERAGE_HANDLE_TIME, TOT_SCHED_PRODUCTIVE_TIME, 
  TOT_ACTUAL_PRODUCTIVE_TIME, TOT_TALK_TIME, TOT_WRAP_UP_TIME, TOT_LOGGED_IN_TIME, TOT_NOT_READY_TIME, TOT_BREAK_TIME, 
  TOT_LUNCH_TIME, QCS_PERFORMED, AVG_QC_SCORE, TOT_INCIDENTS_COMPLETED, DAYS_INCIDENTS_COMPLETED, TOT_DEFECTS_COMPLETED, 
  DAYS_DEFECTS_COMPLETED, LAG_TIME_TOT_SCHED_PROD_TIME, TOT_CALL_RECORDS, TOT_CUSTOMER_COUNT, TOT_CALL_WRAP_UP_COUNT, 
  TOT_WRAP_UP_ERROR, DAYS_SHORT_CALLS_GT_10, DAYS_CALLS_ANSWERED, ADHERENCE, TOT_RETURN_TO_QUEUE_TIMEOUT, AVG_ATTENDANCE_BALANCE, 
  AVG_ATTENDANCE_TOTAL_BALANCE, STAFF_COUNT, SUM_QC_SCORE, COUNT_QC_SCORE, QCS_REMAINING, TOT_HANDLE_TIME, TOT_HANDLE_TIME_COUNT, 
  STAFF_TRTQ_COUNT, SHORT_CALL_AGENT_COUNT, ADHERENCE_TOT_LOGGED_IN_TIME, ADHERENCE_TOT_NOT_READY_TIME, CALLS_OFFERED, WEBCHAT_ASSIGNED, 
  WEBCHAT_TRANSFERRED, WEBCHAT_CONFERENCED, WEBCHAT_TOTAL_NUMBER, 
  SHORT_CALLS_DISCONNECTED_BY_AGENT, SHORT_CALLS_DISCONNECTED_BY_CONSUMER, 
  CURRENT_MONTH_EVENTS_SCHEDULED, CURRENT_MONTH_EVENTS_MET, FIRST_PRIOR_MONTH_EVENTS_SCHEDULED, FIRST_PRIOR_MONTH_EVENTS_MET, 
  SECOND_PRIOR_MONTH_EVENTS_SCHEDULED, SECOND_PRIOR_MONTH_EVENTS_MET, FIRST_PRIOR_MONTH_ADHERENCE_TOT_LOGGED_IN_TIME, 
  FIRST_PRIOR_MONTH_ADHERENCE_TOT_NOT_READY_TIME, FIRST_PRIOR_MONTH_ADHERENCE_LAG_TIME_TOT_SCHED_PROD_TIME, 
  SECOND_PRIOR_MONTH_ADHERENCE_TOT_LOGGED_IN_TIME, SECOND_PRIOR_MONTH_ADHERENCE_TOT_NOT_READY_TIME, 
  SECOND_PRIOR_MONTH_ADHERENCE_LAG_TIME_TOT_SCHED_PROD_TIME, THREE_MONTH_CONFORMANCE_MISSED_COUNT, 
  THREE_MONTH_AVG_ADHERENCE, THREE_MONTH_ADHERENCE_FLAG, MONTHLY_CONFORMANCE_FLAG) AS 
  SELECT 
  SUPERVISOR_STAFF_ID, --DATES_MONTH, DATES_MONTH_NUM, DATES_YEAR, 
  		TO_DATE (dates_month_num, 'YYYYMM')
			AS d_date,
		dates_month,
		dates_month_num,
		dates_year,
			'Q'
		|| TO_CHAR (ADD_MONTHS (TO_DATE (dates_month_num, 'yyyymm'), +3),
					'Q')
		|| ' '
		|| TO_CHAR (ADD_MONTHS (TO_DATE (dates_month_num, 'yyyymm'), +3),
					'YYYY')
			AS dates_qtr_year,
  BUILDING, DEPARTMENT, EXCLUSION_FLAG, 
 TOT_CALLS_ANSWERED, TOT_SHORT_CALLS_ANSWERED, TOT_TOT_RETURN_TO_QUEUE, TOT_AVERAGE_HANDLE_TIME, 
 TOT_SCHED_PRODUCTIVE_TIME, TOT_ACTUAL_PRODUCTIVE_TIME, TOT_TALK_TIME, TOT_WRAP_UP_TIME, TOT_LOGGED_IN_TIME, TOT_NOT_READY_TIME, 
 TOT_BREAK_TIME, TOT_LUNCH_TIME, QCS_PERFORMED, AVG_QC_SCORE, 
 TOT_INCIDENTS_COMPLETED, DAYS_INCIDENTS_COMPLETED, TOT_DEFECTS_COMPLETED, DAYS_DEFECTS_COMPLETED, 
 LAG_TIME_TOT_SCHED_PROD_TIME, TOT_CALL_RECORDS, TOT_CUSTOMER_COUNT, 
 TOT_CALL_WRAP_UP_COUNT, TOT_WRAP_UP_ERROR, DAYS_SHORT_CALLS_GT_10, DAYS_CALLS_ANSWERED, 
 ADHERENCE, TOT_RETURN_TO_QUEUE_TIMEOUT, AVG_ATTENDANCE_BALANCE, AVG_ATTENDANCE_TOTAL_BALANCE, 
 STAFF_COUNT, SUM_QC_SCORE, COUNT_QC_SCORE, QCS_REMAINING, TOT_HANDLE_TIME, TOT_HANDLE_TIME_COUNT, 
 STAFF_TRTQ_COUNT, SHORT_CALL_AGENT_COUNT, ADHERENCE_TOT_LOGGED_IN_TIME, 
 ADHERENCE_TOT_NOT_READY_TIME, CALLS_OFFERED, WEBCHAT_ASSIGNED, WEBCHAT_TRANSFERRED, WEBCHAT_CONFERENCED, 
 WEBCHAT_TOTAL_NUMBER, 
 AGENT_DISCONNECTED_SHORT_CALLS		AS SHORT_CALLS_DISCONNECTED_BY_AGENT, 
 CONSUMER_DISCONNECTED_SHORT_CALLS	AS SHORT_CALLS_DISCONNECTED_BY_CONSUMER, 
 CURRENT_MONTH_EVENTS_SCHEDULED, CURRENT_MONTH_EVENTS_MET, 
 FIRST_PRIOR_MONTH_EVENTS_SCHEDULED, FIRST_PRIOR_MONTH_EVENTS_MET, 
 SECOND_PRIOR_MONTH_EVENTS_SCHEDULED, SECOND_PRIOR_MONTH_EVENTS_MET, 
 FIRST_PRIOR_MONTH_ADHERENCE_TOT_LOGGED_IN_TIME, FIRST_PRIOR_MONTH_ADHERENCE_TOT_NOT_READY_TIME, 
 FIRST_PRIOR_MONTH_ADHERENCE_LAG_TIME_TOT_SCHED_PROD_TIME, 
 SECOND_PRIOR_MONTH_ADHERENCE_TOT_LOGGED_IN_TIME, SECOND_PRIOR_MONTH_ADHERENCE_TOT_NOT_READY_TIME, 
 SECOND_PRIOR_MONTH_ADHERENCE_LAG_TIME_TOT_SCHED_PROD_TIME, 
 THREE_MONTH_CONFORMANCE_MISSED_COUNT, 
 THREE_MONTH_AVG_ADHERENCE, 
 THREE_MONTH_ADHERENCE_FLAG, 
 MONTHLY_CONFORMANCE_FLAG
 FROM DP_SCORECARD.SC_SUMMARY_CC_ROLLUP;
 
GRANT SELECT ON DP_SCORECARD.SCORECARD_SUMMARY_CC_ROLLUP_SV TO MAXDAT;
GRANT SELECT ON DP_SCORECARD.SCORECARD_SUMMARY_CC_ROLLUP_SV TO MAXDAT_REPORTS;
GRANT SELECT ON DP_SCORECARD.SCORECARD_SUMMARY_CC_ROLLUP_SV TO MAXDAT_READ_ONLY;
GRANT SELECT ON DP_SCORECARD.SCORECARD_SUMMARY_CC_ROLLUP_SV TO DP_SCORECARD_READ_ONLY;

