-- NYHIX-49316
set define off;

insert into dp_scorecard.ENGAGE_FORM_TYPE (FORM_TYPE_ID, EVALUATION_FORM, SCORECARD_SCORE_TYPE, SCORECARD_GROUP, CREATE_BY, CREATE_DATETIME, START_DATE, END_DATE)
 values (747,'QC_FPBP_Processing_v1.0','QC','FPBP',null,NULL, to_date('8-May-2019','DD-MON-YYYY'), null);
 
 insert into dp_scorecard.ENGAGE_FORM_TYPE (FORM_TYPE_ID, EVALUATION_FORM, SCORECARD_SCORE_TYPE, SCORECARD_GROUP, CREATE_BY, CREATE_DATETIME, START_DATE, END_DATE)
 values (748,'Supe Review QC_FPBP_Processing_v1.0','QCT','QCT',null,NULL, to_date('8-May-2019','DD-MON-YYYY'), null);
 
 insert into dp_scorecard.ENGAGE_FORM_TYPE (FORM_TYPE_ID, EVALUATION_FORM, SCORECARD_SCORE_TYPE, SCORECARD_GROUP, CREATE_BY, CREATE_DATETIME, START_DATE, END_DATE)
 values (749,'QC_NYSOH_EE_Verification Docs_v4.3','QC','E&E',null,NULL, to_date('8-May-2019','DD-MON-YYYY'), null);
 
 insert into dp_scorecard.ENGAGE_FORM_TYPE (FORM_TYPE_ID, EVALUATION_FORM, SCORECARD_SCORE_TYPE, SCORECARD_GROUP, CREATE_BY, CREATE_DATETIME, START_DATE, END_DATE)
 values (750,'Supe Review_QC_NYSOH_EE_Verification Docs_v4.3','QCT','QCT',null,NULL, to_date('8-May-2019','DD-MON-YYYY'), null);
 


commit;
