--------------------------------------------------------------------
-- sequence
--------------------------------------------------------------------

DROP SEQUENCE DP_SCORECARD.LWOP_SEQ;

DROP TABLE DP_SCORECARD.SC_AUDIT_LWOP CASCADE CONSTRAINTS;

DROP TABLE DP_SCORECARD.SC_AUDIT_LWOP_AUD CASCADE CONSTRAINTS;

DROP VIEW DP_SCORECARD.SC_AUDIT_LWOP_SV;

DROP Procedure DP_SCORECARD.INSERT_SC_AUDIT_LWOP;

DROP Procedure DP_SCORECARD.Update_SC_AUDIT_LWOP;
