ALTER TABLE DP_SCORECARD.SC_SUMMARY_CC
ADD (
  WEBCHAT_ASSIGNED          NUMBER,
  WEBCHAT_TRANSFERRED       NUMBER,
  WEBCHAT_CONFERENCED       NUMBER,
  WEBCHAT_TOTAL_NUMBER      NUMBER
);

ALTER TABLE DP_SCORECARD.SC_SUMMARY_CC_ROLLUP
ADD (
  WEBCHAT_ASSIGNED          NUMBER,
  WEBCHAT_TRANSFERRED       NUMBER,
  WEBCHAT_CONFERENCED       NUMBER,
  WEBCHAT_TOTAL_NUMBER      NUMBER
);