Insert into MAXDAT.PP_BO_EVENT_TARGET_LKUP (EVENT_ID,NAME,TARGET,SCORECARD_FLAG,START_DATE,END_DATE,CREATE_BY,CREATE_DATETIME,SCORECARD_GROUP,EE_ADHERENCE,OPS_GROUP,WORKSUBACTIVITY_FLAG,QC_FLAG,EE_ADHERENCE_V2) 
values (1671,'Kofax DE with Redaction/Splitting',0,'N',to_date('01-AUG-20','DD-MON-RR'),null,'CR 1771',to_date('24-JUL-20','DD-MON-RR'),'NON-PRODUCTIVE','N','Image Assembly Admin','N','N','Y');

COMMIT;