
grant execute on "DP_SCORECARD"."INSERT_SC_AUDIT_SCORECARD" to MAXDAT;
grant execute on "DP_SCORECARD"."INSERT_SC_AUDIT_SCORECARD" to MAXDAT_REPORTS;
grant execute on "DP_SCORECARD"."INSERT_SC_AUDIT_SCORECARD" to MAXDAT_READ_ONLY;
grant execute on "DP_SCORECARD"."INSERT_SC_AUDIT_SCORECARD" to DP_SCORECARD_READ_ONLY;
GRANT execute ON "DP_SCORECARD"."INSERT_SC_AUDIT_SCORECARD" to MAXDAT_MSTR_TRX_RPT;

Commit;
grant execute on "DP_SCORECARD"."UPDATE_SC_AUDIT_SCORECARD" to MAXDAT;
grant execute on "DP_SCORECARD"."UPDATE_SC_AUDIT_SCORECARD" to MAXDAT_REPORTS;
grant execute on "DP_SCORECARD"."UPDATE_SC_AUDIT_SCORECARD" to MAXDAT_READ_ONLY;
grant execute on "DP_SCORECARD"."UPDATE_SC_AUDIT_SCORECARD" to DP_SCORECARD_READ_ONLY;
GRANT execute ON "DP_SCORECARD"."UPDATE_SC_AUDIT_SCORECARD" to MAXDAT_MSTR_TRX_RPT;

Commit;