ALTER TABLE CORP_ETL_COMM_OUTREACH
  ADD (INSTANCE_START_DATE DATE,
       INSTANCE_END_DATE DATE);       
       
ALTER TABLE CORP_ETL_COMM_OUTREACH_OLTP
  ADD (INSTANCE_START_DATE DATE,
       INSTANCE_END_DATE DATE);

ALTER TABLE CORP_ETL_COMM_OUTREACH_WIP_BPM
  ADD (INSTANCE_START_DATE DATE,
       INSTANCE_END_DATE DATE);
       
ALTER TABLE D_CMOR_CURRENT
  ADD (INSTANCE_START_DATE DATE,
       INSTANCE_END_DATE DATE);