CREATE TABLE F_QUEUE_NUM_BY_DAY_STG
(FQNBDS_ID NUMBER NOT NULL, 
 D_DATE DATE, 
 TASK_TYPE VARCHAR2(100 BYTE), 
 INVENTORY_COUNT NUMBER, 
 INCR_TREND_IND VARCHAR2(1 BYTE) DEFAULT 'N', 
 DECR_TREND_IND VARCHAR2(1 BYTE) DEFAULT 'N',
 CREATE_DT   DATE NOT NULL, 
 CREATED_BY  VARCHAR2(100) NOT NULL,
 UPDATE_DT   DATE NOT NULL,
 UPDATED_BY  VARCHAR2(100) NOT NULL
 );
   
ALTER TABLE F_QUEUE_NUM_BY_DAY_STG ADD CONSTRAINT FQNBDS_ID_PK PRIMARY KEY
(
  FQNBDS_ID
)
;   

CREATE SEQUENCE SEQ_FQNBDS_ID START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999999 MINVALUE 1 CACHE 20 ;

CREATE OR REPLACE TRIGGER BIU_F_QUEUE_NUM_BY_DAY_STG
    BEFORE INSERT OR UPDATE ON F_QUEUE_NUM_BY_DAY_STG
    FOR EACH ROW 
    ENABLE 
BEGIN
IF INSERTING AND :NEW.FQNBDS_ID IS NULL THEN 
          SELECT SEQ_FQNBDS_ID.NEXTVAL INTO :NEW.FQNBDS_ID FROM DUAL;
END IF;
IF INSERTING THEN 
          :NEW.CREATE_DT := SYSDATE;
          :NEW.CREATED_BY:= USER;
END IF;
:NEW.UPDATE_DT := SYSDATE;
:NEW.UPDATED_BY := USER;
END;
/


CREATE OR REPLACE VIEW F_QUEUE_NUM_BY_DAY_STG_SV AS
SELECT 
*   
FROM F_QUEUE_NUM_BY_DAY_STG
WITH READ ONLY;


CREATE TABLE F_AVG_DAYS_IN_QUEUE_STG
(FADIQS_ID NUMBER NOT NULL, 
 D_DATE DATE, 
 TASK_TYPE VARCHAR2(100 BYTE), 
 AVG_DAYS_IN_QUEUE NUMBER(3,0), 
 INCR_TREND_IND VARCHAR2(1 BYTE) DEFAULT 'N', 
 DECR_TREND_IND VARCHAR2(1 BYTE) DEFAULT 'N',
 CREATE_DT   DATE NOT NULL, 
 CREATED_BY  VARCHAR2(100) NOT NULL,
 UPDATE_DT   DATE NOT NULL,
 UPDATED_BY  VARCHAR2(100) NOT NULL
 );
   
ALTER TABLE F_AVG_DAYS_IN_QUEUE_STG ADD CONSTRAINT FADIQS_ID_PK PRIMARY KEY
(
  FADIQS_ID
)
;   

CREATE SEQUENCE SEQ_FADIQS_ID START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999999 MINVALUE 1 CACHE 20 ;

CREATE OR REPLACE TRIGGER BIU_F_AVG_DAYS_IN_QUEUE_STG
    BEFORE INSERT OR UPDATE ON F_AVG_DAYS_IN_QUEUE_STG
    FOR EACH ROW 
    ENABLE 
BEGIN
IF INSERTING AND :NEW.FADIQS_ID IS NULL THEN 
          SELECT SEQ_FADIQS_ID.NEXTVAL INTO :NEW.FADIQS_ID FROM DUAL;
END IF;
IF INSERTING THEN 
          :NEW.CREATE_DT := SYSDATE;
          :NEW.CREATED_BY:= USER;
END IF;
:NEW.UPDATE_DT := SYSDATE;
:NEW.UPDATED_BY := USER;
END;
/


CREATE OR REPLACE VIEW F_AVG_DAYS_IN_QUEUE_STG_SV AS
SELECT 
*   
FROM F_AVG_DAYS_IN_QUEUE_STG
WITH READ ONLY;
