create index IMR_ID_INDX on S_CRS_IMR_ISSUES_IN_DISPUTE 
(
	IMR_ID
)
TABLESPACE MAXDAT_INDX LOGGING compute statistics;

create index ISSUE_IN_DISPUTE_ID_INDX on S_CRS_IMR_ISSUES_IN_DISPUTE 
(
	ISSUE_IN_DISPUTE_ID
)
TABLESPACE MAXDAT_INDX LOGGING compute statistics;