CREATE TABLE D_LETTER_DEFINITION 
( LMDEF_ID	NUMBER(18,0)
,NAME	VARCHAR2(40)
,DESCRIPTION	VARCHAR2(4000)
,DRIVER_TYPE	VARCHAR2(32)
,LETTER_OR_FORM	VARCHAR2(1)
,LOAD_IMAGE_IND	NUMBER(1,0)
,DRIVER_PRIMARY_KEY	VARCHAR2(38)
,DRIVER_TABLE_NAME	VARCHAR2(40)
,PRODUCED_BY	VARCHAR2(2)
,TRIGERRING_METHOD	VARCHAR2(2)
,EFFECTIVE_FROM_DATE	DATE
,EFFECTIVE_THRU_DATE	DATE
,CONTRACT_REFERENCE	VARCHAR2(40)
,POSTMARK_DELAY	NUMBER(2,0)
,RESPOND_BY_DELAY	NUMBER(2,0)
,RESPOND_BY_WORKDAY_IND	NUMBER(1,0)
,CREATED_BY	VARCHAR2(80)
,CREATE_TS	DATE
,UPDATED_BY	VARCHAR2(80)
,UPDATE_TS	DATE
,FORM_IND	NUMBER(1,0)
,ALERT_IND	NUMBER(1,0)
,ALERT_MESSAGE_KEY	VARCHAR2(255)
,SEND_EVENT	VARCHAR2(32)
,ALLOW_BAD_ADDR_IND	NUMBER(1,0)
,TRANSACTION_BEAN	VARCHAR2(128)
,PROCESS_BEAN	VARCHAR2(128)
,PROCESS_IND	NUMBER(1,0)
,OUT_PARAMS	VARCHAR2(1024)
,TRANSFORM_FILE	VARCHAR2(128)
,MAX_NUMBER_DAYS_4_RSND	NUMBER(19,0)
,SCOPE	VARCHAR2(128)
,MAX_LETTERS_PROCESSED	NUMBER(18,0) 
) TABLESPACE MAXDAT_DATA;


CREATE UNIQUE INDEX XPK_LETTER_DEFINITION ON D_LETTER_DEFINITION (LMDEF_ID) TABLESPACE MAXDAT_INDX;

GRANT SELECT ON D_LETTER_DEFINITION TO MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW D_LETTER_DEFINITION_SV
AS
SELECT *
FROM d_letter_definition
WHERE effective_thru_date IS NULL
  ;
  
GRANT SELECT ON D_LETTER_DEFINITION_SV to MAXDAT_READ_ONLY;