## Create Table ##
CREATE TABLE MAXDAT_MITRAN.D_EYR_LETTERS_COST
    (GROUP_NAME VARCHAR2(30),
     PRODUCTION_COST NUMBER(5,3),
     POSTAGE_COST NUMBER(5,3),
     EFF_START_DATE DATE,
     EFF_END_DATE DATE,
     CREATE_TS DATE,
     UPDATE_TS DATE,
     CREATED_BY VARCHAR2(50),
     UPDATED_BY VARCHAR2(50));

## Add PK ( Group name and effective start date ) 

ALTER TABLE MAXDAT_MITRAN.D_EYR_LETTERS_COST ADD PRIMARY KEY(GROUP_NAME,EFF_START_DATE);


## Create View ##
create or replace view MAXDAT_MITRAN.D_EYR_LETTERS_COST_SV AS
(select GROUP_NAME  as GROUP_NAME,
     PRODUCTION_COST  as PRODUCTION_COST,
     POSTAGE_COST  as POSTAGE_COST,
     EFF_START_DATE as EFFECTIVE_START_DATE, 
     EFF_END_DATE  as EFFECTIVE_END_DATE
     from MAXDAT_MITRAN.D_EYR_LETTERS_COST);
     

GRANT SELECT ON "MAXDAT_MITRAN"."D_EYR_LETTERS_COST_SV" TO "MAXDAT_MITRAN_READ_ONLY";
GRANT SELECT ON "MAXDAT_MITRAN"."D_EYR_LETTERS_COST_SV" TO "MAXDAT_MITRAN_OLTP_SIU";
GRANT SELECT ON "MAXDAT_MITRAN"."D_EYR_LETTERS_COST_SV" TO "MAXDAT_MITRAN_OLTP_SIUD";


## Alter d_tran_detail table to add INV_USER_ID column : 

alter table d_tran_detail add invoiced_user number;


Commit;


