CREATE TABLE GROUP_STEP_DEFINITION_STG
(
  GROUP_STEP_DEFINITION_ID NUMBER(18, 0) NOT NULL 
, EFFECTIVE_START_TS DATE 
, EFFECTIVE_END_TS DATE 
, FORWARDING_RULE_CD VARCHAR2(32 BYTE) 
, ESCALATION_RULE_CD VARCHAR2(32 BYTE) 
, GROUP_ID NUMBER(18, 0) 
, STEP_DEFINITION_ID NUMBER(18, 0) 
, CREATED_BY VARCHAR2(80 BYTE) 
, CREATE_TS DATE 
, UPDATED_BY VARCHAR2(80 BYTE) 
, UPDATE_TS DATE 
, CONSTRAINT XPKGROUP_STEP_DEFINITION PRIMARY KEY 
  (
    GROUP_STEP_DEFINITION_ID 
  )
  ENABLE 
) ;