alter trigger TRG_AI_CORP_ETL_MANAGE_WORK disable;
alter trigger TRG_AU_CORP_ETL_MANAGE_WORK disable;
alter trigger TRG_AI_CORP_ETL_MANAGE_WORK_Q enable;
alter trigger TRG_AU_CORP_ETL_MANAGE_WORK_Q enable;
alter trigger TRG_AI_NYEC_ETL_PROCESS_APP_Q disable;
alter trigger TRG_AU_NYEC_ETL_PROCESS_APP_Q disable;
alter trigger TRG_AI_NYEC_ETL_PA_MI_Q disable;
alter trigger TRG_AU_NYEC_ETL_PA_MI_Q disable;
