update d_mw_v2_current
   set AGE_IN_BUSINESS_DAYS = mw_v2.GET_AGE_IN_BUSINESS_DAYS(CURR_WORK_RECEIPT_DATE,INSTANCE_END_DATE),
       TIMELINESS_STATUS = mw_v2.GET_TIMELINESS_STATUS(
														 INSTANCE_END_DATE,
														 TASK_TYPE_ID,
														 CURR_WORK_RECEIPT_DATE
														 ) 
 where trunc(INSTANCE_END_DATE) >= to_date('13-MAR-2017','dd-MON-yyyy')
 and trunc(INSTANCE_END_DATE) <= to_date('16-MAR-2017','dd-MON-yyyy');
commit;

update  D_COMPLAINT_CURRENT
  set AGE_IN_BUSINESS_DAYS = PROCESS_COMPLAINTS_INCIDENTS.GET_AGE_IN_BUSINESS_DAYS(CREATE_DATE,COMPLETE_DT),
      TIMELINESS_STATUS = PROCESS_COMPLAINTS_INCIDENTS.GET_TIMELINESS_STATUS(CREATE_DATE,COMPLETE_DT,FORWARDED_FLAG,FORWARD_DT,INCIDENT_TYPE)
WHERE trunc(complete_dt) >=  to_date('13-MAR-2017','dd-MON-yyyy')
and trunc(complete_dt) <=  to_date('16-MAR-2017','dd-MON-yyyy'); 
commit;

