CREATE OR REPLACE SEQUENCE seq_regional_staff_roster_history_id;

CREATE OR REPLACE TABLE INEO_REGIONAL_STAFF_ROSTER_HISTORY 
(regional_staff_roster_history_id NUMBER NOT NULL DEFAULT seq_regional_staff_roster_history_id.nextval,
region VARCHAR,
department VARCHAR,
supervisor VARCHAR,
qisc VARCHAR,
manager VARCHAR,
psid VARCHAR,
filename VARCHAR,
regions_supporting VARCHAR,
time_zone VARCHAR,
employee_id VARCHAR,
employee_name VARCHAR,
maximus_email VARCHAR,
position_title VARCHAR,
work_group VARCHAR,
training_status VARCHAR,
employee_status VARCHAR,
transition_team_lead VARCHAR,
regional_team_leads VARCHAR,
regional_supervisors VARCHAR,
qi_supervisor VARCHAR,
sr_operations_manager VARCHAR,
hr_specialist VARCHAR,
agency_hire_date DATE,
conversion_date DATE,
maximus_hire_date DATE,
term_date DATE,
training_class_id VARCHAR,
nesting_start_date DATE,
nesting_end_date DATE,
previous_stateconduent_employee VARCHAR,
incumbent_transition VARCHAR,
employee_type VARCHAR,
staffing_agency VARCHAR,
fssa_id VARCHAR,
fssa_email VARCHAR,
genesys_i3_id VARCHAR,
attendance_status VARCHAR,
attendance_status_date DATE,
attendance_status_time VARCHAR,
attendance_points_accrued FLOAT,
shift_start_time VARCHAR,
break_1_time VARCHAR,
lunch_start_time VARCHAR,
lunch_end_time VARCHAR,
break_2_time VARCHAR,
shift_end_time VARCHAR,
shift_schedule_week_starting VARCHAR,
open_corrective_actions VARCHAR,
closed_corrective_actions VARCHAR,
 sf_create_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp(),
 sf_update_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp());
 
 alter table INEO_REGIONAL_STAFF_ROSTER_HISTORY add primary key (regional_staff_roster_history_id);
 
 CREATE OR REPLACE SEQUENCE seq_wmst_task_completion_timeliness_report_daily_history_id;
 
 CREATE OR REPLACE TABLE INEO_WMST_TASK_COMPLETION_TIMELINESS_REPORT_DAILY_HISTORY 
 (wmst_task_completion_timeliness_report_daily_history_id NUMBER NOT NULL DEFAULT seq_wmst_task_completion_timeliness_report_daily_history_id.nextval,
date DATE,
user_id VARCHAR,
first_name VARCHAR,
last_name VARCHAR,
user_group VARCHAR,
org_name VARCHAR,
filename VARCHAR,
reference_number VARCHAR,
reference_type VARCHAR,
task_sequence_number VARCHAR,
metric_description VARCHAR,
work_queue_name VARCHAR,
task_create_date DATE,
task_completed_date DATE,
calendar_days integer,
business_days integer,
metric_1_performance_completed_within_days integer,
metric_1_derivation_processed_timely VARCHAR,
metric_2_performance_completed_within_days integer,
metric_2_derivation_processed_timely VARCHAR,
primary_office_location_id VARCHAR,
primary_office_location_name VARCHAR,
 sf_create_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp(),
 sf_update_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp());
 
 ALTER TABLE INEO_WMST_TASK_COMPLETION_TIMELINESS_REPORT_DAILY_HISTORY ADD PRIMARY KEY(wmst_task_completion_timeliness_report_daily_history_id);
 
 