CREATE OR REPLACE SEQUENCE seq_qual_sdps_trash_id;
CREATE OR REPLACE SEQUENCE seq_qual_sdps_scorecards_id;

CREATE OR REPLACE TABLE INEO_QUALITY_SDPS_TRASH_HISTORY (
qual_sdps_trash_id NUMBER NOT NULL DEFAULT seq_qual_sdps_trash_id.nextval,
autonumber VARCHAR,
region VARCHAR,
supervisor VARCHAR,
manager VARCHAR,
status VARCHAR,
filename VARCHAR,
supervisor_name VARCHAR,
send_to_trash VARCHAR,
employee_id VARCHAR,
fssa_id VARCHAR,
art_id NUMBER,
employee_name VARCHAR,
submitted_employee_name VARCHAR,
training_status VARCHAR,
record_id VARCHAR,
scoring_date DATE,
task_sequence_number VARCHAR,
sf_create_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp(),
sf_update_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp());

ALTER TABLE INEO_QUALITY_SDPS_TRASH_HISTORY ADD PRIMARY KEY(qual_sdps_trash_id);

CREATE OR REPLACE TABLE INEO_QUALITY_SDPS_SCORECARDS_HISTORY (
qual_sdps_scorecards_id NUMBER NOT NULL DEFAULT seq_qual_sdps_scorecards_id.nextval,
autonumber VARCHAR,
region VARCHAR,
supervisor VARCHAR,
manager VARCHAR,
qisc VARCHAR,
status VARCHAR,
score FLOAT,
filename VARCHAR,
supervisor_name VARCHAR,
qisc_name VARCHAR,
qi_supervisor_name VARCHAR,
regional_supervisors VARCHAR,
generate_pdf VARCHAR,
send_to_trash VARCHAR,
employee_id VARCHAR,
fssa_id VARCHAR,
employee_name VARCHAR,
submitted_employee_name VARCHAR,
training_status VARCHAR,
fssa_email VARCHAR,
qi_supervisor VARCHAR,
record_id VARCHAR,
scoring_date DATE,
points_earned NUMBER,
points_possible NUMBER,
deduction_received FLOAT,
task_sequence_number VARCHAR,
cp_1a VARCHAR,
cp_1b VARCHAR,
cp_1c VARCHAR,
cp_1d VARCHAR,
cp_1e VARCHAR,
cp_1f VARCHAR,
cp_1g VARCHAR,
cp_1h VARCHAR,
cp_1i VARCHAR,
cp_1j VARCHAR,
cp_1applicable VARCHAR,
cp_1score NUMBER,
cp_1comments VARCHAR,
cp_2a VARCHAR,
cp_2b VARCHAR,
cp_2applicable VARCHAR,
cp_2score NUMBER,
cp_2comments VARCHAR,
cp_3a VARCHAR,
cp_3b VARCHAR,
cp_3c VARCHAR,
cp_3d VARCHAR,
cp_3e VARCHAR,
cp_3f VARCHAR,
cp_3applicable VARCHAR,
cp_3score NUMBER,
cp_3comments VARCHAR,
cp_4a VARCHAR,
cp_4b VARCHAR,
cp_4c VARCHAR,
cp_4d VARCHAR,
cp_4e VARCHAR,
cp_4f VARCHAR,
cp_4applicable VARCHAR,
cp_4score NUMBER,
cp_4comments VARCHAR,
cp_5a VARCHAR,
cp_5b VARCHAR,
cp_5c VARCHAR,
cp_5d VARCHAR,
cp_5e VARCHAR,
cp_5f VARCHAR,
cp_5g VARCHAR,
cp_5h VARCHAR,
cp_5i VARCHAR,
cp_5j VARCHAR,
cp_5k VARCHAR,
cp_5l VARCHAR,
cp_5applicable VARCHAR,
cp_5score NUMBER,
cp_5comments VARCHAR,
cp_6a VARCHAR,
cp_6b VARCHAR,
cp_6c VARCHAR,
cp_6d VARCHAR,
cp_6applicable VARCHAR,
cp_6score NUMBER,
cp_6comments VARCHAR,
cp_7a VARCHAR,
cp_7b VARCHAR,
cp_7c VARCHAR,
cp_7d VARCHAR,
cp_7e VARCHAR,
cp_7f VARCHAR,
cp_7g VARCHAR,
cp_7h VARCHAR,
cp_7applicable VARCHAR,
cp_7score NUMBER,
cp_7comments VARCHAR,
cp_8a VARCHAR,
cp_8b VARCHAR,
cp_8c VARCHAR,
cp_8applicable VARCHAR,
cp_8score NUMBER,
cp_8comments VARCHAR,
cp_9a VARCHAR,
cp_9b VARCHAR,
cp_9c VARCHAR,
cp_9d VARCHAR,
cp_9e VARCHAR,
cp_9f VARCHAR,
cp_9g VARCHAR,
cp_9h VARCHAR,
cp_9i VARCHAR,
cp_9j VARCHAR,
cp_9k VARCHAR,
cp_9applicable VARCHAR,
cp_9score NUMBER,
cp_9comments VARCHAR,
cp_10a VARCHAR,
cp_10b VARCHAR,
cp_10c VARCHAR,
cp_10d VARCHAR,
cp_10e VARCHAR,
cp_10f VARCHAR,
cp_10g VARCHAR,
cp_10h VARCHAR,
cp_10i VARCHAR,
cp_10applicable VARCHAR,
cp_10score NUMBER,
cp_10comments VARCHAR,
cp_11a VARCHAR,
cp_11b VARCHAR,
cp_11c VARCHAR,
cp_11d VARCHAR,
cp_11e VARCHAR,
cp_11f VARCHAR,
cp_11g VARCHAR,
cp_11h VARCHAR,
cp_11applicable VARCHAR,
cp_11score NUMBER,
cp_11comments VARCHAR,
cp_12a VARCHAR,
cp_12b VARCHAR,
cp_12c VARCHAR,
cp_12d VARCHAR,
cp_12e VARCHAR,
cp_12f VARCHAR,
cp_12g VARCHAR,
cp_12h VARCHAR,
cp_12i VARCHAR,
cp_12applicable VARCHAR,
cp_12score NUMBER,
cp_12comments VARCHAR,
cp_13a VARCHAR,
cp_13applicable VARCHAR,
cp_13score NUMBER,
cp_13comments VARCHAR,
cp_14a VARCHAR,
cp_14applicable VARCHAR,
cp_14score NUMBER,
cp_14comments VARCHAR,
cp_15a VARCHAR,
cp_15b VARCHAR,
cp_15c VARCHAR,
cp_15applicable VARCHAR,
cp_15score NUMBER,
cp_15comments VARCHAR,
cp_16a VARCHAR,
cp_16b VARCHAR,
cp_16applicable VARCHAR,
cp_16score NUMBER,
cp_16comments VARCHAR,
cp_17a VARCHAR,
cp_17b VARCHAR,
cp_17c VARCHAR,
cp_17d VARCHAR,
cp_17e VARCHAR,
cp_17f VARCHAR,
cp_17applicable VARCHAR,
cp_17score NUMBER,
cp_17comments VARCHAR,
cp_18a VARCHAR,
cp_18applicable VARCHAR,
cp_18score NUMBER,
cp_18comments VARCHAR,
cp_19a VARCHAR,
cp_19applicable VARCHAR,
cp_19score NUMBER,
cp_19comments VARCHAR,
cp_20a VARCHAR,
cp_20b VARCHAR,
cp_20applicable VARCHAR,
cp_20score NUMBER,
cp_20comments VARCHAR,
cp_21a VARCHAR,
cp_21b VARCHAR,
cp_21applicable VARCHAR,
cp_21score NUMBER,
cp_21comments VARCHAR,
cp_22a VARCHAR,
cp_22applicable VARCHAR,
cp_22score NUMBER,
cp_22comments VARCHAR,
cp_23a VARCHAR,
cp_23applicable VARCHAR,
cp_23score NUMBER,
cp_23comments VARCHAR,
cp_24a VARCHAR,
cp_24applicable VARCHAR,
cp_24score NUMBER,
cp_24comments VARCHAR,
cp_25a VARCHAR,
cp_25b VARCHAR,
cp_25applicable VARCHAR,
cp_25score NUMBER,
cp_25comments VARCHAR,
cp_26a VARCHAR,
cp_26b VARCHAR,
cp_26c VARCHAR,
cp_26applicable VARCHAR,
cp_26score NUMBER,
cp_26comments VARCHAR,
cp_27a VARCHAR,
cp_27applicable VARCHAR,
cp_27score NUMBER,
cp_27comments VARCHAR,
cp_28a VARCHAR,
cp_28b VARCHAR,
cp_28c VARCHAR,
cp_28d VARCHAR,
cp_28e VARCHAR,
cp_28f VARCHAR,
cp_28applicable VARCHAR,
cp_28score_percent_deduction FLOAT,
cp_28comments VARCHAR,
overall_comments VARCHAR,
sf_create_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp(),
sf_update_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp());
 
ALTER TABLE INEO_QUALITY_SDPS_SCORECARDS_HISTORY ADD PRIMARY KEY(qual_sdps_scorecards_id);

DELETE FROM file_load_lkup
WHERE filename_prefix IN('QUAL_SDPS_TRASH','QUAL_SDPS_SCORECARDS');

INSERT INTO file_load_lkup(filename_prefix,full_load_table_name,full_load_table_schema,insert_fields,select_fields,where_clause,load_file,derive_timestamp_stmt,file_day_received,current_table_name,current_table_primary_key,full_load_table_primary_key) 
 VALUES('QUAL_SDPS_TRASH','INEO_QUALITY_SDPS_TRASH_HISTORY','INEO',
'autonumber,region,supervisor,manager,status,filename,supervisor_name,send_to_trash,employee_id,fssa_id,art_id,employee_name,submitted_employee_name,training_status,record_id,scoring_date,task_sequence_number',
'autonumber,region,supervisor,manager,status,filename,supervisor_name,send_to_trash,employee_id,fssa_id,REGEXP_REPLACE(art_id,''[^0-9]'','''') art_id,employee_name,submitted_employee_name,training_status,record_id,scoring_date,task_sequence_',
'WHERE 1=1',
'Y',
'SELECT TO_CHAR(TO_TIMESTAMP(TRIM(SUBSTR(<filename>,LENGTH(<filename>)-13)),''yyyymmddhh24miss''),''mm/dd/yyyy hh24:mi:ss'') file_date,''Y'' with_timestamp FROM dual',
'PREVIOUS_BUSINESS_DAY', NULL,NULL,'QUAL_SDPS_TRASH_ID');


INSERT INTO file_load_lkup(filename_prefix,full_load_table_name,full_load_table_schema,insert_fields,select_fields,where_clause,load_file,derive_timestamp_stmt,file_day_received,current_table_name,current_table_primary_key,full_load_table_primary_key) 
 VALUES('QUAL_SDPS_SCORECARDS','INEO_QUALITY_SDPS_SCORECARDS_HISTORY','INEO',
'autonumber,region,supervisor,manager,qisc,status,score,filename,supervisor_name,qisc_name,qi_supervisor_name,regional_supervisors,generate_pdf,send_to_trash,employee_id,fssa_id,employee_name,submitted_employee_name,training_status,fssa_email,qi_supervisor,record_id,scoring_date,points_earned,points_possible,deduction_received,task_sequence_number,
cp_1a,cp_1b,cp_1c,cp_1d,cp_1e,cp_1f,cp_1g,cp_1h,cp_1i,cp_1j,cp_1applicable,cp_1score,cp_1comments,cp_2a,cp_2b,cp_2applicable,cp_2score,cp_2comments,
cp_3a,cp_3b,cp_3c,cp_3d,cp_3e,cp_3f,cp_3applicable,cp_3score,cp_3comments,cp_4a,cp_4b,cp_4c,cp_4d,cp_4e,cp_4f,cp_4applicable,cp_4score,cp_4comments,
cp_5a,cp_5b,cp_5c,cp_5d,cp_5e,cp_5f,cp_5g,cp_5h,cp_5i,cp_5j,cp_5k,cp_5l,cp_5applicable,cp_5score,cp_5comments,cp_6a,cp_6b,cp_6c,cp_6d,cp_6applicable,cp_6score,cp_6comments,
cp_7a,cp_7b,cp_7c,cp_7d,cp_7e,cp_7f,cp_7g,cp_7h,cp_7applicable,cp_7score,cp_7comments,cp_8a,cp_8b,cp_8c,cp_8applicable,cp_8score,cp_8comments,
cp_9a,cp_9b,cp_9c,cp_9d,cp_9e,cp_9f,cp_9g,cp_9h,cp_9i,cp_9j,cp_9k,cp_9applicable,cp_9score,cp_9comments,cp_10a,cp_10b,cp_10c,cp_10d,cp_10e,cp_10f,cp_10g,cp_10h,cp_10i,cp_10applicable,cp_10score,cp_10comments,
cp_11a,cp_11b,cp_11c,cp_11d,cp_11e,cp_11f,cp_11g,cp_11h,cp_11applicable,cp_11score,cp_11comments,cp_12a,cp_12b,cp_12c,cp_12d,cp_12e,cp_12f,cp_12g,cp_12h,cp_12i,cp_12applicable,cp_12score,cp_12comments,
cp_13a,cp_13applicable,cp_13score,cp_13comments,cp_14a,cp_14applicable,cp_14score,cp_14comments,
cp_15a,cp_15b,cp_15c,cp_15applicable,cp_15score,cp_15comments,cp_16a,cp_16b,cp_16applicable,cp_16score,cp_16comments,cp_17a,cp_17b,cp_17c,cp_17d,cp_17e,cp_17f,cp_17applicable,cp_17score,cp_17comments,
cp_18a,cp_18applicable,cp_18score,cp_18comments,cp_19a,cp_19applicable,cp_19score,cp_19comments,cp_20a,cp_20b,cp_20applicable,cp_20score,cp_20comments,cp_21a,cp_21b,cp_21applicable,cp_21score,cp_21comments,
cp_22a,cp_22applicable,cp_22score,cp_22comments,cp_23a,cp_23applicable,cp_23score,cp_23comments,cp_24a,cp_24applicable,cp_24score,cp_24comments,
cp_25a,cp_25b,cp_25applicable,cp_25score,cp_25comments,cp_26a,cp_26b,cp_26c,cp_26applicable,cp_26score,cp_26comments,cp_27a,cp_27applicable,cp_27score,cp_27comments,
cp_28a,cp_28b,cp_28c,cp_28d,cp_28e,cp_28f,cp_28applicable,cp_28score_percent_deduction,cp_28comments,overall_comments',
'autonumber,region,supervisor,manager,qisc,status,TRY_CAST(score AS FLOAT),filename,supervisor_name,qisc_name,qi_supervisor_name,regional_supervisors,generate_pdf,send_to_trash,employee_id,fssa_id,employee_name,submitted_employee_name,training_status,fssa_email,qi_supervisor,record_id,scoring_date,points_earned,points_possible,TRY_CAST(deduction_received AS FLOAT),task_sequence_,
cp_1a,cp_1b,cp_1c,cp_1d,cp_1e,cp_1f,cp_1g,cp_1h,cp_1i,cp_1j,cp_1applicable,TRY_CAST(cp_1score AS NUMBER),cp_1comments,cp_2a,cp_2b,cp_2applicable,TRY_CAST(cp_2score AS NUMBER),cp_2comments,
cp_3a,cp_3b,cp_3c,cp_3d,cp_3e,cp_3f,cp_3applicable,TRY_CAST(cp_3score AS NUMBER),cp_3comments,cp_4a,cp_4b,cp_4c,cp_4d,cp_4e,cp_4f,cp_4applicable,TRY_CAST(cp_4score AS NUMBER),cp_4comments,
cp_5a,cp_5b,cp_5c,cp_5d,cp_5e,cp_5f,cp_5g,cp_5h,cp_5i,cp_5j,cp_5k,cp_5l,cp_5applicable,TRY_CAST(cp_5score AS NUMBER),cp_5comments,cp_6a,cp_6b,cp_6c,cp_6d,cp_6applicable,TRY_CAST(cp_6score AS NUMBER),cp_6comments,
cp_7a,cp_7b,cp_7c,cp_7d,cp_7e,cp_7f,cp_7g,cp_7h,cp_7applicable,TRY_CAST(cp_7score AS NUMBER),cp_7comments,cp_8a,cp_8b,cp_8c,cp_8applicable,TRY_CAST(cp_8score AS NUMBER),cp_8comments,
cp_9a,cp_9b,cp_9c,cp_9d,cp_9e,cp_9f,cp_9g,cp_9h,cp_9i,cp_9j,cp_9k,cp_9applicable,TRY_CAST(cp_9score AS NUMBER),cp_9comments,cp_10a,cp_10b,cp_10c,cp_10d,cp_10e,cp_10f,cp_10g,cp_10h,cp_10i,cp_10applicable,TRY_CAST(cp_10score AS NUMBER),cp_10comments,
cp_11a,cp_11b,cp_11c,cp_11d,cp_11e,cp_11f,cp_11g,cp_11h,cp_11applicable,TRY_CAST(cp_11score AS NUMBER),cp_11comments,cp_12a,cp_12b,cp_12c,cp_12d,cp_12e,cp_12f,cp_12g,cp_12h,cp_12i,cp_12applicable,TRY_CAST(cp_12score AS NUMBER),cp_12comments,
cp_13a,cp_13applicable,TRY_CAST(cp_13score AS NUMBER),cp_13comments,cp_14a,cp_14applicable,TRY_CAST(cp_14score AS NUMBER),cp_14comments,
cp_15a,cp_15b,cp_15c,cp_15applicable,TRY_CAST(cp_15score AS NUMBER),cp_15comments,cp_16a,cp_16b,cp_16applicable,TRY_CAST(cp_16score AS NUMBER),cp_16comments,
cp_17a,cp_17b,cp_17c,cp_17d,cp_17e,cp_17f,cp_17applicable,TRY_CAST(cp_17score AS NUMBER),cp_17comments,cp_18a,cp_18applicable,TRY_CAST(cp_18score AS NUMBER),cp_18comments,
cp_19a,cp_19applicable,TRY_CAST(cp_19score AS NUMBER),cp_19comments,cp_20a,cp_20b,cp_20applicable,TRY_CAST(cp_20score AS NUMBER),cp_20comments,
cp_21a,cp_21b,cp_21applicable,TRY_CAST(cp_21score AS NUMBER),cp_21comments,cp_22a,cp_22applicable,TRY_CAST(cp_22score AS NUMBER),cp_22comments,
cp_23a,cp_23applicable,TRY_CAST(cp_23score AS NUMBER),cp_23comments,cp_24a,cp_24applicable,TRY_CAST(cp_24score AS NUMBER),cp_24comments,
cp_25a,cp_25b,cp_25applicable,TRY_CAST(cp_25score AS NUMBER),cp_25comments,cp_26a,cp_26b,cp_26c,cp_26applicable,TRY_CAST(cp_26score AS NUMBER),cp_26comments,
cp_27a,cp_27applicable,TRY_CAST(cp_27score AS NUMBER),cp_27comments,cp_28a,cp_28b,cp_28c,cp_28d,cp_28e,cp_28f,cp_28applicable,TRY_CAST(cp_28score AS FLOAT),cp_28comments,overall_comments',
'WHERE 1=1',
'Y',
'SELECT TO_CHAR(TO_TIMESTAMP(TRIM(SUBSTR(<filename>,LENGTH(<filename>)-13)),''yyyymmddhh24miss''),''mm/dd/yyyy hh24:mi:ss'') file_date,''Y'' with_timestamp FROM dual',
'PREVIOUS_BUSINESS_DAY', NULL,NULL,'QUAL_SDPS_SCORECARDS_ID');
