
CREATE OR REPLACE SEQUENCE seq_wmstmetricdetails_id;

CREATE OR REPLACE TABLE INEO_WMST_METRIC_DETAILS_HISTORY (wmstmetricdetails_id NUMBER NOT NULL DEFAULT seq_wmstmetricdetails_id.nextval,
region VARCHAR,
office VARCHAR,
caseworker VARCHAR,
filename VARCHAR,
record_id NUMBER,
user_id VARCHAR,
taskcall VARCHAR,
task_namecall_record VARCHAR,
task_completion_date DATE,
call_record_date DATE,
review_completion_date DATE,
total_possible_earned NUMBER,
maximum_possible_points NUMBER,
total_percentage_score FLOAT,
e2e_deduction FLOAT,
final_percentage_score FLOAT,
sf_create_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp(),
sf_update_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp());
 
ALTER TABLE INEO_WMST_METRIC_DETAILS_HISTORY ADD PRIMARY KEY(wmstmetricdetails_id); 

CREATE OR REPLACE SEQUENCE seq_wmst_user_cumulative_reviews_id;

CREATE OR REPLACE TABLE INEO_WMST_USER_CUMULATIVE_REVIEWS_HISTORY (wmst_user_cumulative_reviews_id NUMBER NOT NULL DEFAULT seq_wmst_user_cumulative_reviews_id.nextval,
caseworker VARCHAR,
region VARCHAR,
office VARCHAR,
filename VARCHAR,
user_id VARCHAR,
cumulative_number NUMBER,
number_of_reviews NUMBER,
sf_create_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp(),
sf_update_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp());
 
ALTER TABLE INEO_WMST_USER_CUMULATIVE_REVIEWS_HISTORY ADD PRIMARY KEY(wmst_user_cumulative_reviews_id);

CREATE OR REPLACE SEQUENCE seq_wmst_qa_by_region_id;
 
 CREATE OR REPLACE TABLE INEO_WMST_QA_BY_REGION_HISTORY (wmst_qa_by_region_id NUMBER NOT NULL DEFAULT seq_wmst_qa_by_region_id.nextval,
filename VARCHAR,
region_name VARCHAR,
january NUMBER,
february NUMBER,
march NUMBER,
april NUMBER,
may NUMBER,
june NUMBER,
july NUMBER,
august NUMBER,
september NUMBER,
october NUMBER,
november NUMBER,
december NUMBER,
cumulative_rate NUMBER,
year NUMBER,
 sf_create_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp(),
 sf_update_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp());

ALTER TABLE INEO_WMST_QA_BY_REGION_HISTORY ADD PRIMARY KEY(wmst_qa_by_region_id);

CREATE OR REPLACE SEQUENCE seq_wmst_monthly_metric_totals_id;

CREATE OR REPLACE TABLE INEO_WMST_MONTHLY_METRIC_TOTALS_HISTORY (wmst_monthly_metric_totals_id NUMBER NOT NULL DEFAULT seq_wmst_monthly_metric_totals_id.nextval,
metric VARCHAR,
filename VARCHAR,
number_of_reviews_completed NUMBER,
total_possible_points_earned NUMBER,
total_maximum_possible_points NUMBER,
total_final_percentage_score NUMBER,
 sf_create_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp(),
 sf_update_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp());

ALTER TABLE INEO_WMST_MONTHLY_METRIC_TOTALS_HISTORY ADD PRIMARY KEY(wmst_monthly_metric_totals_id);

CREATE OR REPLACE SEQUENCE seq_wmst_user_qa_scores_id;

CREATE OR REPLACE TABLE INEO_WMST_USER_QA_SCORES_HISTORY (wmst_user_qa_scores_id NUMBER NOT NULL DEFAULT seq_wmst_user_qa_scores_id.nextval,
metric VARCHAR,
filename VARCHAR,
record_id NUMBER,
task_name VARCHAR,
review_completion_date DATE,
total_possible_earned NUMBER,
maximum_possible_points NUMBER,
total_percentage_score FLOAT,
e2e_deduction FLOAT,
final_percentage_score FLOAT,
for_month_of DATE,
sf_create_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp(),
sf_update_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp());

ALTER TABLE INEO_WMST_USER_QA_SCORES_HISTORY ADD PRIMARY KEY(wmst_user_qa_scores_id);

CREATE OR REPLACE SEQUENCE seq_qual_metric_scorecards_id;

CREATE OR REPLACE TABLE INEO_QUALITY_METRIC_SCORECARDS_HISTORY (qual_metric_scorecards_id NUMBER NOT NULL DEFAULT seq_qual_metric_scorecards_id.nextval,
autonumber VARCHAR,
region VARCHAR,
supervisor VARCHAR,
manager VARCHAR,
qisc VARCHAR,
status VARCHAR,
score FLOAT,
filename VARCHAR,
supervisor_name VARCHAR,
qisc_name VARCHAR,
qi_supervisor_name VARCHAR,
regional_supervisors VARCHAR,
generate_pdf VARCHAR,
send_to_trash VARCHAR,
employee_id VARCHAR,
fssa_id VARCHAR,
art_id VARCHAR,
employee_name VARCHAR,
submitted_employee_name VARCHAR,
training_status VARCHAR,
fssa_email VARCHAR,
qi_supervisor VARCHAR,
record_id VARCHAR,
scoring_date DATE,
points_earned NUMBER,
points_possible NUMBER,
deduction_received FLOAT,
task_sequence_number VARCHAR,
cp_1a VARCHAR,
cp_1b VARCHAR,
cp_1c VARCHAR,
cp_1d VARCHAR,
cp_1e VARCHAR,
cp_1f VARCHAR,
cp_1g VARCHAR,
cp_1h VARCHAR,
cp_1i VARCHAR,
cp_1j VARCHAR,
cp_1applicable VARCHAR,
cp_1score NUMBER,
cp_1comments VARCHAR,
cp_2a VARCHAR,
cp_2b VARCHAR,
cp_2applicable VARCHAR,
cp_2score NUMBER,
cp_2comments VARCHAR,
cp_3a VARCHAR,
cp_3b VARCHAR,
cp_3c VARCHAR,
cp_3d VARCHAR,
cp_3e TEXT,
cp_3f VARCHAR,
cp_3applicable VARCHAR,
cp_3score NUMBER,
cp_3comments VARCHAR,
cp_4a VARCHAR,
cp_4b VARCHAR,
cp_4c VARCHAR,
cp_4d VARCHAR,
cp_4e VARCHAR,
cp_4f VARCHAR,
cp_4applicable VARCHAR,
cp_4score NUMBER,
cp_4comments VARCHAR,
cp_5a VARCHAR,
cp_5b VARCHAR,
cp_5c VARCHAR,
cp_5d VARCHAR,
cp_5e VARCHAR,
cp_5f VARCHAR,
cp_5g VARCHAR,
cp_5h VARCHAR,
cp_5i VARCHAR,
cp_5j VARCHAR,
cp_5k VARCHAR,
cp_5l VARCHAR,
cp_5applicable VARCHAR,
cp_5score NUMBER,
cp_5comments VARCHAR,
cp_6a VARCHAR,
cp_6b VARCHAR,
cp_6c VARCHAR,
cp_6d VARCHAR,
cp_6applicable VARCHAR,
cp_6score NUMBER,
cp_6comments VARCHAR,
cp_7a VARCHAR,
cp_7b VARCHAR,
cp_7c VARCHAR,
cp_7d VARCHAR,
cp_7e VARCHAR,
cp_7f VARCHAR,
cp_7g VARCHAR,
cp_7h VARCHAR,
cp_7applicable VARCHAR,
cp_7score NUMBER,
cp_7comments VARCHAR,
cp_8a VARCHAR,
cp_8b VARCHAR,
cp_8c VARCHAR,
cp_8applicable VARCHAR,
cp_8score NUMBER,
cp_8comments VARCHAR,
cp_9a VARCHAR,
cp_9b VARCHAR,
cp_9c VARCHAR,
cp_9d VARCHAR,
cp_9e VARCHAR,
cp_9f VARCHAR,
cp_9g VARCHAR,
cp_9h VARCHAR,
cp_9i VARCHAR,
cp_9j VARCHAR,
cp_9k VARCHAR,
cp_9applicable VARCHAR,
cp_9score NUMBER,
cp_9comments VARCHAR,
cp_10a VARCHAR,
cp_10b VARCHAR,
cp_10c VARCHAR,
cp_10d VARCHAR,
cp_10e VARCHAR,
cp_10f VARCHAR,
cp_10g VARCHAR,
cp_10h VARCHAR,
cp_10i VARCHAR,
cp_10applicable VARCHAR,
cp_10score NUMBER,
cp_10comments VARCHAR,
cp_11a VARCHAR,
cp_11b VARCHAR,
cp_11c VARCHAR,
cp_11d VARCHAR,
cp_11e VARCHAR,
cp_11f VARCHAR,
cp_11g VARCHAR,
cp_11h VARCHAR,
cp_11applicable VARCHAR,
cp_11score NUMBER,
cp_11comments VARCHAR,
cp_12a VARCHAR,
cp_12b VARCHAR,
cp_12c VARCHAR,
cp_12d VARCHAR,
cp_12e VARCHAR,
cp_12f VARCHAR,
cp_12g VARCHAR,
cp_12h VARCHAR,
cp_12i VARCHAR,
cp_12applicable VARCHAR,
cp_12score NUMBER,
cp_12comments VARCHAR,
cp_13a VARCHAR,
cp_13applicable VARCHAR,
cp_13score VARCHAR,
cp_13comments VARCHAR,
cp_14a VARCHAR,
cp_14applicable VARCHAR,
cp_14score VARCHAR,
cp_14comments VARCHAR,
cp_15a VARCHAR,
cp_15b VARCHAR,
cp_15c VARCHAR,
cp_15applicable VARCHAR,
cp_15score NUMBER,
cp_15comments VARCHAR,
cp_16a VARCHAR,
cp_16b VARCHAR,
cp_16applicable VARCHAR,
cp_16score NUMBER,
cp_16comments VARCHAR,
cp_17a VARCHAR,
cp_17b VARCHAR,
cp_17c VARCHAR,
cp_17d VARCHAR,
cp_17e VARCHAR,
cp_17f VARCHAR,
cp_17applicable VARCHAR,
cp_17score NUMBER,
cp_17comments VARCHAR,
cp_18a VARCHAR,
cp_18applicable VARCHAR,
cp_18score NUMBER,
cp_18comments VARCHAR,
cp_19a VARCHAR,
cp_19applicable VARCHAR,
cp_19score NUMBER,
cp_19comments VARCHAR,
cp_20a VARCHAR,
cp_20b VARCHAR,
cp_20applicable VARCHAR,
cp_20score NUMBER,
cp_20comments VARCHAR,
cp_21a VARCHAR,
cp_21b VARCHAR,
cp_21applicable VARCHAR,
cp_21score NUMBER,
cp_21comments VARCHAR,
cp_22a VARCHAR,
cp_22applicable VARCHAR,
cp_22score NUMBER,
cp_22comments VARCHAR,
cp_23a VARCHAR,
cp_23applicable VARCHAR,
cp_23score NUMBER,
cp_23comments VARCHAR,
cp_24a VARCHAR,
cp_24applicable VARCHAR,
cp_24score NUMBER,
cp_24comments VARCHAR,
cp_25a VARCHAR,
cp_25b VARCHAR,
cp_25applicable VARCHAR,
cp_25score NUMBER,
cp_25comments VARCHAR,
cp_26a VARCHAR,
cp_26b VARCHAR,
cp_26c VARCHAR,
cp_26applicable VARCHAR,
cp_26score NUMBER,
cp_26comments VARCHAR,
cp_27a VARCHAR,
cp_27applicable VARCHAR,
cp_27score NUMBER,
cp_27comments VARCHAR,
cp_28a VARCHAR,
cp_28b VARCHAR,
cp_28c VARCHAR,
cp_28d VARCHAR,
cp_28e VARCHAR,
cp_28f VARCHAR,
cp_28applicable VARCHAR,
cp_28score_percent_deduction FLOAT,
cp_28comments VARCHAR,
overall_comments VARCHAR,
 sf_create_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp(),
 sf_update_ts TIMESTAMP_NTZ(9) DEFAULT current_timestamp());
 
 ALTER TABLE INEO_QUALITY_METRIC_SCORECARDS_HISTORY ADD PRIMARY KEY(qual_metric_scorecards_id);