use role SYSADMIN;
use warehouse PUREINSIGHTS_UAT_LOAD_DAILY_WH;
use database PUREINSIGHTS_UAT;
use schema PUBLIC;

GRANT USAGE ON PROCEDURE DECISIONPOINT_UAT.STAGE.LOAD_PI_USER_HISTORY_PROC(VARCHAR, BOOLEAN, BOOLEAN) TO ROLE PI_DATA_INGEST_UAT_ALERT_USER WITH GRANT OPTION;

GRANT OWNERSHIP ON PROCEDURE STAGE.S_PI_QUEUE_MONITORING_PENDING_EVALUATIONS_LOAD(VARCHAR, BOOLEAN, BOOLEAN) TO ROLE PI_DATA_INGEST_UAT_ALERT_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON STAGE.S_PI_QUEUE_MONITORING_PENDING_EVALUATIONS TO ROLE PI_DATA_INGEST_UAT_ALERT_USER;
GRANT SELECT ON VIEW PUBLIC.D_PROJECT_DATES_SV TO ROLE PI_DATA_INGEST_UAT_ALERT_USER;
GRANT SELECT ON VIEW PUBLIC.D_PI_EVALUATIONS_VW TO ROLE PI_DATA_INGEST_UAT_ALERT_USER;

DELETE FROM 
	PUBLIC.D_PI_INGESTION_SPS 
WHERE 	
	sp_name = 'LOAD_PI_USER_HISTORY_PROC'
AND	schema_name = 'DECISIONPOINT_UAT.STAGE';

INSERT INTO
	PUBLIC.D_PI_INGESTION_SPS	
	(
		sp_name,
		schema_name,
		active,
		update_timestamp
	)
VALUES
	(	'LOAD_PI_USER_HISTORY_PROC',	
		'DECISIONPOINT_UAT.STAGE',
		TRUE,
		current_timestamp()
	);

DELETE FROM 
	PUBLIC.D_PI_INGESTION_SPS 
WHERE 	
	sp_name = 'S_PI_QUEUE_MONITORING_PENDING_EVALUATIONS_LOAD'
AND	schema_name = 'STAGE';

INSERT INTO
	PUBLIC.D_PI_INGESTION_SPS	
	(
		sp_name,
		schema_name,
		active,
		update_timestamp
	)
VALUES
	(	'S_PI_QUEUE_MONITORING_PENDING_EVALUATIONS_LOAD',	
		'STAGE',
		TRUE,
		current_timestamp()
	);
