--------------------------------------------------------
--  File created - Thursday-June-13-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FLHK_ETL_MONITOR_DISPUTES_OLTP
--------------------------------------------------------

  CREATE TABLE "FLCST0_MAXDAT"."FLHK_ETL_MONITOR_DISPUTES_OLTP" 
   (	"MD_ID" NUMBER, 
	"DISPUTE_ID" NUMBER, 
	"DISPUTE_ID_CREATE_DATE" DATE, 
	"ACCOUNT_ID" VARCHAR2(38 BYTE), 
	"CHANNEL" VARCHAR2(80 BYTE), 
	"WORK_REQUEST_ID" NUMBER, 
	"DISPUTE_CREATE_DATE" DATE, 
	"RECEIPT_DATE" DATE, 
	"STAFF_USERID" VARCHAR2(100 BYTE), 
	"STAFF_ROLE" VARCHAR2(100 BYTE), 
	"REPORTER_TYPE" VARCHAR2(100 BYTE), 
	"DISPUTE_STATUS" VARCHAR2(100 BYTE), 
	"DISPUTE_STATUS_DATE" DATE, 
	"COMPLETE_DATE" DATE, 
	"CANCEL_DATE" DATE, 
	"DISPUTE_LEVEL" VARCHAR2(100 BYTE), 
	"DISPUTE_LIABILITY" VARCHAR2(20 BYTE), 
	"LIABILITY_ASSIGNED_DATE" DATE, 
	"LIABILITY_AGE_BUSINESS_DAYS" NUMBER, 
	"SENT_TO_STATE_DATE" DATE, 
	"DISPUTE_RESOLUTION" VARCHAR2(100 BYTE), 
	"DISPUTE_ACKNOWLEDGE_REQ_ID" NUMBER, 
	"DISPUTE_DISPOSITION" VARCHAR2(100 BYTE), 
	"ASSD_PROCESS_DISPUTES" DATE, 
	"ASED_PROCESS_DISPUTES" DATE, 
	"ASF_PROCESS_DISPUTES" VARCHAR2(1 BYTE), 
	"STAGE_DONE_DATE" DATE, 
	"STG_EXTRACT_DATE" DATE, 
	"STG_LAST_UPDATE_DATE" DATE, 
	"INSTANCE_STATUS" VARCHAR2(100 BYTE), 
	"INSTANCE_COMPLETE_DATE" DATE, 
	"WORK_REQUESTS_COMPLETED" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHIP_DATA" ;
