--------------------------------------------------------
--  File created - Thursday-April-25-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FLHK_ETL_PROCESS_LETTERS_WIP
--------------------------------------------------------

  CREATE TABLE "FLCST0_MAXDAT"."FLHK_ETL_PROCESS_LETTERS_WIP" 
   (	"PK_ID" NUMBER, 
	"LETTER_REQ_ID" NUMBER, 
	"CREATE_DATE" DATE, 
	"CREATED_BY_NAME" VARCHAR2(100 BYTE), 
	"REQUESTED_ON_DATE" DATE, 
	"STATUS" VARCHAR2(100 BYTE), 
	"STATUS_DATE" DATE, 
	"TYPE" VARCHAR2(40 BYTE), 
	"CATEGORY" VARCHAR2(100 BYTE), 
	"USER_NAME" VARCHAR2(80 BYTE), 
	"SOURCE" VARCHAR2(80 BYTE), 
	"TRIGGERING_METHOD" VARCHAR2(3 BYTE), 
	"BATCH_ID" NUMBER, 
	"LANGUAGE" VARCHAR2(100 BYTE), 
	"DRIVER_TYPE" VARCHAR2(100 BYTE), 
	"DRIVER_KEY" NUMBER, 
	"ACCOUNT_ID" NUMBER, 
	"MEMBER_ID" NUMBER, 
	"APP_ID" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_BY_NAME" VARCHAR2(100 BYTE), 
	"VALIDATED_DATE" DATE, 
	"VALIDATED_OUTCOME" VARCHAR2(100 BYTE), 
	"TRANSMITTED_DATE" DATE, 
	"CONFIRMED_DATE" DATE, 
	"IMAGE_RECEIVED_DATE" DATE, 
	"REPLACEMENT_REQUEST_ID" VARCHAR2(38 BYTE), 
	"CANCEL_DATE" DATE, 
	"COMPLETE_DATE" DATE, 
	"ASSD_PROCESS_LETTER_REQUEST" DATE, 
	"ASED_PROCESS_LETTER_REQUEST" DATE, 
	"ASF_PROCESS_LETTER_REQUEST" VARCHAR2(1 BYTE), 
	"ASED_RECEIVED_CONFIRMATION" DATE, 
	"ASF_RECEIVED_CONFIRMATION" VARCHAR2(1 BYTE), 
	"ASSD_RECEIVED_CONFIRMATION" DATE, 
	"ASED_WAIT_UNTIL_NEW_RQST" DATE, 
	"ASF_WAIT_UNTIL_NEW_RQST" VARCHAR2(1 BYTE), 
	"ASSD_WAIT_UNTIL_NEW_RQST" VARCHAR2(100 BYTE), 
	"GWF_TRANSMIT" VARCHAR2(1 BYTE), 
	"GWF_NEW_LETTER_NEEDED" VARCHAR2(1 BYTE), 
	"STAGE_DONE_DATE" DATE, 
	"STG_EXTRACT_DATE" DATE, 
	"STG_LAST_UPDATE_DATE" DATE, 
	"INSTANCE_STATUS" VARCHAR2(100 BYTE), 
	"INSTANCE_COMPLETE_DATE" DATE, 
	"ERR_LEVEL" VARCHAR2(20 BYTE), 
	"PROCESS_NAME" VARCHAR2(120 BYTE), 
	"JOB_NAME" VARCHAR2(120 BYTE), 
	"DRIVER_TABLE_NAME" VARCHAR2(100 BYTE), 
	"ERR_DATE" DATE, 
	"UPDATED" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHIP_DATA" ;
