alter table CC_F_ACD_AGENT_INTERVAL modify (
 AFTER_CALL_WORK_TIME_TOTAL NULL
);

alter table CC_F_ACD_AGENT_INTERVAL modify (
 AFTER_CALL_WORK_TIME_TOTAL DEFAULT NULL
);

alter table CC_F_ACD_AGENT_INTERVAL modify (
 CONTACTS_ABANDONED NULL
);

alter table CC_F_ACD_AGENT_INTERVAL modify (
 CONTACTS_ABANDONED DEFAULT NULL
);

alter table CC_F_ACD_AGENT_INTERVAL modify (
 CONTACTS_HANDLED NULL
);

alter table CC_F_ACD_AGENT_INTERVAL modify (
 CONTACTS_HANDLED DEFAULT NULL
);

alter table CC_F_ACD_AGENT_INTERVAL modify (
 CONTACTS_OFFERED NULL
);

alter table CC_F_ACD_AGENT_INTERVAL modify (
 CONTACTS_OFFERED DEFAULT NULL
);

alter table CC_F_ACD_AGENT_INTERVAL modify (
 WAIT_TIME_TOTAL NULL
);

alter table CC_F_ACD_AGENT_INTERVAL modify (
 WAIT_TIME_TOTAL DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 ABANDON_TIME_TOTAL NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 ABANDON_TIME_TOTAL DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
  ANSWER_WAIT_TIME_TOTAL NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
  ANSWER_WAIT_TIME_TOTAL DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
  CALLS_ABANDONED_PERIOD_1 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
  CALLS_ABANDONED_PERIOD_1 DEFAULT NULL
);


alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_10 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_10 DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_2 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_2 DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_3 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_3  DEFAULT NULL
);


alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_4 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_4 DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_5 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_5 DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_6 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_6 DEFAULT NULL
);


alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_7 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_7 DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_8 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_8 DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_9 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_9 DEFAULT NULL
);


alter table CC_F_ACD_QUEUE_INTERVAL modify (
 HEADCOUNT_AVAILABLE NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 HEADCOUNT_AVAILABLE DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 HOLD_TIME_TOTAL NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 HOLD_TIME_TOTAL DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 OUTFLOW_CONTACTS NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 OUTFLOW_CONTACTS DEFAULT NULL
);

/*alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ABANDONED NULL
); */

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ABANDONED DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_COUNT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_COUNT DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_PERCENT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_PERCENT DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_1 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_1 DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_10 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_10 DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_2 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_2 DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_3 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_3 DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_4 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_4 DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_5 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_5 DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_6 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_6 DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_7 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_7 DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_8 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_8 DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_9 NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_9 DEFAULT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 TALK_TIME_TOTAL NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 TALK_TIME_TOTAL DEFAULT NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 CONTACTS_CONTAINED_IN_IVR NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 CONTACTS_CONTAINED_IN_IVR DEFAULT NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 CONTACTS_CREATED NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 CONTACTS_CREATED DEFAULT NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 CONTACTS_OFFERED_TO_ACD NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 CONTACTS_OFFERED_TO_ACD DEFAULT NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 MAX_TIME_IN_THE_IVR NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 MAX_TIME_IN_THE_IVR DEFAULT NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 MEAN_TIME_IN_THE_IVR NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 MEAN_TIME_IN_THE_IVR DEFAULT NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 MEDIAN_TIME_IN_THE_IVR NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 MEDIAN_TIME_IN_THE_IVR DEFAULT NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 MIN_TIME_IN_THE_IVR NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 MIN_TIME_IN_THE_IVR DEFAULT NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 STDDEV_TIME_IN_THE_IVR NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 STDDEV_TIME_IN_THE_IVR DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 ABANDON_TIME_TOTAL NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 ABANDON_TIME_TOTAL DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 AFTER_CALL_WORK_TIME_TOTAL NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 AFTER_CALL_WORK_TIME_TOTAL DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 ANSWER_WAIT_TIME_TOTAL NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 ANSWER_WAIT_TIME_TOTAL DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_1 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_1 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_10 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_10 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_2 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_2 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_3 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_3 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_4 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_4 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_5 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_5 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_6 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_6 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_7 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_7 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_8 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_8 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_9 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_9 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CONTACTS_ABANDONED NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CONTACTS_ABANDONED DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CONTACTS_HANDLED NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CONTACTS_HANDLED DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CONTACTS_OFFERED NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CONTACTS_OFFERED DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 HEADCOUNT_AVAILABLE NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 HEADCOUNT_AVAILABLE DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 HOLD_TIME_TOTAL NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 HOLD_TIME_TOTAL DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 OUTFLOW_CONTACTS NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 OUTFLOW_CONTACTS DEFAULT NULL
);

/*alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ABANDONED NULL
); */

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ABANDONED DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_COUNT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_COUNT DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_PERCENT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_PERCENT DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_1 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_1 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_10 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_10 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_2 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_2 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_3 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_3 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_4 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_4 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_5 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_5 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_6 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_6 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_7 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_7 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_8 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_8 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_9 NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_9 DEFAULT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 TALK_TIME_TOTAL NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 TALK_TIME_TOTAL DEFAULT NULL
);

alter table CC_F_AGENT_BY_DATE modify (
 IDLE_SECONDS NULL
);

alter table CC_F_AGENT_BY_DATE modify (
 IDLE_SECONDS DEFAULT NULL
);

alter table CC_F_AGENT_BY_DATE modify (
 LOGIN_SECONDS NULL
);

alter table CC_F_AGENT_BY_DATE modify (
 LOGIN_SECONDS DEFAULT NULL
);

alter table CC_F_AGENT_BY_DATE modify (
 NOT_READY_SECONDS NULL
);

alter table CC_F_AGENT_BY_DATE modify (
 NOT_READY_SECONDS DEFAULT NULL
);

alter table CC_F_AGENT_RTG_GRP_INTERVAL modify (
 IDLE_SECONDS NULL
);

alter table CC_F_AGENT_RTG_GRP_INTERVAL modify (
 IDLE_SECONDS DEFAULT NULL
);

alter table CC_F_AGENT_RTG_GRP_INTERVAL modify (
 LOGIN_SECONDS NULL
);

alter table CC_F_AGENT_RTG_GRP_INTERVAL modify (
 LOGIN_SECONDS DEFAULT NULL
);

alter table CC_F_AGENT_RTG_GRP_INTERVAL modify (
 NOT_READY_SECONDS NULL
);

alter table CC_F_AGENT_RTG_GRP_INTERVAL modify (
 NOT_READY_SECONDS DEFAULT NULL
);

alter table CC_F_IVR_SELF_SERVICE_USAGE modify (
 CONTACTS_ENTERING NULL
);

alter table CC_F_IVR_SELF_SERVICE_USAGE modify (
 CONTACTS_ENTERING DEFAULT NULL
);


/* Staging Tables */

alter table CC_S_ACD_AGENT_INTERVAL modify (
 AFTER_CALL_WORK_TIME_TOTAL NULL
);

alter table CC_S_ACD_AGENT_INTERVAL modify (
 AFTER_CALL_WORK_TIME_TOTAL DEFAULT NULL
);

alter table CC_S_ACD_AGENT_INTERVAL modify (
 CONTACTS_ABANDONED NULL
);

alter table CC_S_ACD_AGENT_INTERVAL modify (
 CONTACTS_ABANDONED DEFAULT NULL
);

alter table CC_S_ACD_AGENT_INTERVAL modify (
 CONTACTS_HANDLED NULL
);

alter table CC_S_ACD_AGENT_INTERVAL modify (
 CONTACTS_HANDLED DEFAULT NULL
);

alter table CC_S_ACD_AGENT_INTERVAL modify (
 CONTACTS_OFFERED NULL
);

alter table CC_S_ACD_AGENT_INTERVAL modify (
 CONTACTS_OFFERED DEFAULT NULL
);

alter table CC_S_ACD_AGENT_INTERVAL modify (
 WAIT_TIME_TOTAL NULL
);

alter table CC_S_ACD_AGENT_INTERVAL modify (
 WAIT_TIME_TOTAL DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 ABANDON_TIME_TOTAL NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 ABANDON_TIME_TOTAL DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
  ANSWER_WAIT_TIME_TOTAL NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
  ANSWER_WAIT_TIME_TOTAL DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
  CALLS_ABANDONED_PERIOD_1 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
  CALLS_ABANDONED_PERIOD_1 DEFAULT NULL
);


alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_10 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_10 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_2 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_2 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_3 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_3  DEFAULT NULL
);


alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_4 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_4 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_5 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_5 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_6 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_6 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_7 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_7 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_8 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_8 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_9 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_9 DEFAULT NULL
);


alter table CC_S_ACD_QUEUE_INTERVAL modify (
 HEADCOUNT_AVAILABLE NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 HEADCOUNT_AVAILABLE DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 HOLD_TIME_TOTAL NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 HOLD_TIME_TOTAL DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 OUTFLOW_CONTACTS NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 OUTFLOW_CONTACTS DEFAULT NULL
);

/*alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ABANDONED NULL
); */

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ABANDONED DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_COUNT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_COUNT DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_PERCENT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_PERCENT DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_1 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_1 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_10 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_10 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_2 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_2 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_3 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_3 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_4 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_4 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_5 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_5 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_6 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_6 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_7 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_7 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_8 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_8 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_9 NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_9 DEFAULT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 TALK_TIME_TOTAL NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 TALK_TIME_TOTAL DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 ABANDON_TIME_TOTAL NULL
);

alter table CC_S_ACD_INTERVAL modify (
 ABANDON_TIME_TOTAL DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 AFTER_CALL_WORK_TIME_TOTAL NULL
);

alter table CC_S_ACD_INTERVAL modify (
 AFTER_CALL_WORK_TIME_TOTAL DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 ANSWER_WAIT_TIME_TOTAL NULL
);

alter table CC_S_ACD_INTERVAL modify (
 ANSWER_WAIT_TIME_TOTAL DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_1 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_1 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_10 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_10 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_2 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_2 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_3 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_3 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_4 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_4 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_5 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_5 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_6 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_6 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_7 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_7 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_8 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_8 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_9 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_9 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CONTACTS_ABANDONED NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CONTACTS_ABANDONED DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CONTACTS_HANDLED NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CONTACTS_HANDLED DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CONTACTS_OFFERED NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CONTACTS_OFFERED DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 HEADCOUNT_AVAILABLE NULL
);

alter table CC_S_ACD_INTERVAL modify (
 HEADCOUNT_AVAILABLE DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 HOLD_TIME_TOTAL NULL
);

alter table CC_S_ACD_INTERVAL modify (
 HOLD_TIME_TOTAL DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 OUTFLOW_CONTACTS NULL
);

alter table CC_S_ACD_INTERVAL modify (
 OUTFLOW_CONTACTS DEFAULT NULL
);

/*alter table CC_S_ACD_INTERVAL modify (
 SERVICE_LEVEL_ABANDONED NULL
); */

alter table CC_S_ACD_INTERVAL modify (
 SERVICE_LEVEL_ABANDONED DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_COUNT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_COUNT DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_PERCENT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_PERCENT DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_1 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_1 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_10 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_10 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_2 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_2 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_3 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_3 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_4 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_4 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_5 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_5 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_6 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_6 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_7 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_7 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_8 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_8 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_9 NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_9 DEFAULT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 TALK_TIME_TOTAL NULL
);

alter table CC_S_ACD_INTERVAL modify (
 TALK_TIME_TOTAL DEFAULT NULL
);

alter table CC_S_ACD_AGENT_ACTIVITY modify (
 IDLE_SECONDS NULL
);

alter table CC_S_ACD_AGENT_ACTIVITY modify (
 IDLE_SECONDS DEFAULT NULL
);

alter table CC_S_ACD_AGENT_ACTIVITY modify (
 LOGIN_SECONDS NULL
);

alter table CC_S_ACD_AGENT_ACTIVITY modify (
 LOGIN_SECONDS DEFAULT NULL
);

alter table CC_S_ACD_AGENT_ACTIVITY modify (
 NOT_READY_SECONDS NULL
);

alter table CC_S_ACD_AGENT_ACTIVITY modify (
 NOT_READY_SECONDS DEFAULT NULL
);

alter table CC_S_AGENT_RTG_GRP_INTERVAL modify (
 IDLE_SECONDS NULL
);

alter table CC_S_AGENT_RTG_GRP_INTERVAL modify (
 IDLE_SECONDS DEFAULT NULL
);

alter table CC_S_AGENT_RTG_GRP_INTERVAL modify (
 LOGIN_SECONDS NULL
);

alter table CC_S_AGENT_RTG_GRP_INTERVAL modify (
 LOGIN_SECONDS DEFAULT NULL
);

alter table CC_S_AGENT_RTG_GRP_INTERVAL modify (
 NOT_READY_SECONDS NULL
);

alter table CC_S_AGENT_RTG_GRP_INTERVAL modify (
 NOT_READY_SECONDS DEFAULT NULL
);

alter table CC_S_IVR_SELF_SERVICE_USAGE modify (
 CONTACTS_ENTERING NULL
);

alter table CC_S_IVR_SELF_SERVICE_USAGE modify (
 CONTACTS_ENTERING DEFAULT NULL
);