UPDATE CC_F_ACD_AGENT_INTERVAL
SET AFTER_CALL_WORK_TIME_TOTAL = 0
WHERE AFTER_CALL_WORK_TIME_TOTAL IS NULL;

alter table CC_F_ACD_AGENT_INTERVAL modify (
 AFTER_CALL_WORK_TIME_TOTAL NOT NULL
);

alter table CC_F_ACD_AGENT_INTERVAL modify (
 AFTER_CALL_WORK_TIME_TOTAL DEFAULT 0
);

UPDATE CC_F_ACD_AGENT_INTERVAL 
SET CONTACTS_ABANDONED = 0
WHERE CONTACTS_ABANDONED IS NULL;

alter table CC_F_ACD_AGENT_INTERVAL modify (
 CONTACTS_ABANDONED NOT NULL
);

alter table CC_F_ACD_AGENT_INTERVAL modify (
 CONTACTS_ABANDONED DEFAULT 0
);

UPDATE CC_F_ACD_AGENT_INTERVAL 
SET CONTACTS_HANDLED = 0
WHERE CONTACTS_HANDLED IS NULL;

alter table CC_F_ACD_AGENT_INTERVAL modify (
 CONTACTS_HANDLED NOT NULL
);

alter table CC_F_ACD_AGENT_INTERVAL modify (
 CONTACTS_HANDLED DEFAULT 0
);

UPDATE CC_F_ACD_AGENT_INTERVAL 
SET CONTACTS_OFFERED = 0
WHERE CONTACTS_OFFERED IS NULL;

alter table CC_F_ACD_AGENT_INTERVAL modify (
 CONTACTS_OFFERED NOT NULL
);

alter table CC_F_ACD_AGENT_INTERVAL modify (
 CONTACTS_OFFERED DEFAULT 0
);

UPDATE CC_F_ACD_AGENT_INTERVAL
SET WAIT_TIME_TOTAL = 0
WHERE WAIT_TIME_TOTAL IS NULL;

alter table CC_F_ACD_AGENT_INTERVAL modify (
 WAIT_TIME_TOTAL NOT NULL
);

alter table CC_F_ACD_AGENT_INTERVAL modify (
 WAIT_TIME_TOTAL DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET ABANDON_TIME_TOTAL = 0
WHERE ABANDON_TIME_TOTAL IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 ABANDON_TIME_TOTAL NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 ABANDON_TIME_TOTAL DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET ANSWER_WAIT_TIME_TOTAL = 0
WHERE ANSWER_WAIT_TIME_TOTAL IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 ANSWER_WAIT_TIME_TOTAL NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 ANSWER_WAIT_TIME_TOTAL DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_1 = 0
WHERE CALLS_ABANDONED_PERIOD_1 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_1 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_1 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_10 = 0
WHERE CALLS_ABANDONED_PERIOD_10 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_10 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_10 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_2 = 0
WHERE CALLS_ABANDONED_PERIOD_2 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_2 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_2 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_3 = 0
WHERE CALLS_ABANDONED_PERIOD_3 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_3 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_3 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_4 = 0
WHERE CALLS_ABANDONED_PERIOD_4 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_4 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_4 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_5 = 0
WHERE CALLS_ABANDONED_PERIOD_5 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_5 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_5 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_6 = 0
WHERE CALLS_ABANDONED_PERIOD_6 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_6 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_6 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_7 = 0
WHERE CALLS_ABANDONED_PERIOD_7 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_7 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_7 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_8 = 0
WHERE CALLS_ABANDONED_PERIOD_8 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_8 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_8 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_9 = 0
WHERE CALLS_ABANDONED_PERIOD_9 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_9 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_9 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET HEADCOUNT_AVAILABLE  = 0
WHERE HEADCOUNT_AVAILABLE IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 HEADCOUNT_AVAILABLE NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 HEADCOUNT_AVAILABLE DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET HOLD_TIME_TOTAL = 0
WHERE HOLD_TIME_TOTAL IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 HOLD_TIME_TOTAL NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 HOLD_TIME_TOTAL DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET OUTFLOW_CONTACTS = 0
WHERE OUTFLOW_CONTACTS IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 OUTFLOW_CONTACTS NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 OUTFLOW_CONTACTS DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET SERVICE_LEVEL_ABANDONED = 0
WHERE SERVICE_LEVEL_ABANDONED IS NULL;

/* alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ABANDONED NOT NULL
); */

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ABANDONED DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET SERVICE_LEVEL_ANSWERED_COUNT = 0
WHERE SERVICE_LEVEL_ANSWERED_COUNT IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_COUNT NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_COUNT DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET SERVICE_LEVEL_ANSWERED_PERCENT = 0
WHERE SERVICE_LEVEL_ANSWERED_PERCENT IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_PERCENT NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_PERCENT DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_1 = 0
WHERE SPEED_OF_ANSWER_PERIOD_1 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_1 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_1 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL
SET SPEED_OF_ANSWER_PERIOD_10 = 0
WHERE SPEED_OF_ANSWER_PERIOD_10 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_10 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_10 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_2 = 0
WHERE SPEED_OF_ANSWER_PERIOD_2 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_2 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_2 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_3 = 0
WHERE SPEED_OF_ANSWER_PERIOD_3 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_3 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_3 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_4 = 0
WHERE SPEED_OF_ANSWER_PERIOD_4 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_4 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_4 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_5 = 0
WHERE SPEED_OF_ANSWER_PERIOD_5 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_5 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_5 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL
SET SPEED_OF_ANSWER_PERIOD_6 = 0
WHERE SPEED_OF_ANSWER_PERIOD_6 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_6 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_6 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_7 = 0
WHERE SPEED_OF_ANSWER_PERIOD_7 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_7 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_7 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_8 = 0
WHERE SPEED_OF_ANSWER_PERIOD_8 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_8 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_8 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL
SET SPEED_OF_ANSWER_PERIOD_9 = 0
WHERE SPEED_OF_ANSWER_PERIOD_9 IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_9 NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_9 DEFAULT 0
);

UPDATE CC_F_ACD_QUEUE_INTERVAL 
SET TALK_TIME_TOTAL = 0
WHERE TALK_TIME_TOTAL IS NULL;

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 TALK_TIME_TOTAL NOT NULL
);

alter table CC_F_ACD_QUEUE_INTERVAL modify (
 TALK_TIME_TOTAL DEFAULT 0
);

UPDATE CC_F_ACTUALS_IVR_INTERVAL 
SET CONTACTS_CONTAINED_IN_IVR = 0
WHERE CONTACTS_CONTAINED_IN_IVR IS NULL;

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 CONTACTS_CONTAINED_IN_IVR NOT NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 CONTACTS_CONTAINED_IN_IVR DEFAULT 0
);

UPDATE CC_F_ACTUALS_IVR_INTERVAL 
SET CONTACTS_CREATED = 0
WHERE CONTACTS_CREATED IS NULL;

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 CONTACTS_CREATED NOT NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 CONTACTS_CREATED DEFAULT 0
);

UPDATE CC_F_ACTUALS_IVR_INTERVAL 
SET CONTACTS_OFFERED_TO_ACD = 0
WHERE CONTACTS_OFFERED_TO_ACD IS NULL;

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 CONTACTS_OFFERED_TO_ACD NOT NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 CONTACTS_OFFERED_TO_ACD DEFAULT 0
);

UPDATE CC_F_ACTUALS_IVR_INTERVAL 
SET MAX_TIME_IN_THE_IVR = 0
WHERE MAX_TIME_IN_THE_IVR IS NULL;

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 MAX_TIME_IN_THE_IVR NOT NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 MAX_TIME_IN_THE_IVR DEFAULT 0
);

UPDATE CC_F_ACTUALS_IVR_INTERVAL 
SET MEAN_TIME_IN_THE_IVR = 0
WHERE MEAN_TIME_IN_THE_IVR IS NULL;

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 MEAN_TIME_IN_THE_IVR NOT NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 MEAN_TIME_IN_THE_IVR DEFAULT 0
);

UPDATE CC_F_ACTUALS_IVR_INTERVAL 
SET MEDIAN_TIME_IN_THE_IVR = 0
WHERE MEDIAN_TIME_IN_THE_IVR IS NULL;

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 MEDIAN_TIME_IN_THE_IVR NOT NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 MEDIAN_TIME_IN_THE_IVR DEFAULT 0
);

UPDATE CC_F_ACTUALS_IVR_INTERVAL
SET MIN_TIME_IN_THE_IVR = 0
WHERE MIN_TIME_IN_THE_IVR IS NULL;

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 MIN_TIME_IN_THE_IVR NOT NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 MIN_TIME_IN_THE_IVR DEFAULT 0
);

UPDATE CC_F_ACTUALS_IVR_INTERVAL 
SET STDDEV_TIME_IN_THE_IVR = 0
WHERE STDDEV_TIME_IN_THE_IVR IS NULL;

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 STDDEV_TIME_IN_THE_IVR NOT NULL
);

alter table CC_F_ACTUALS_IVR_INTERVAL modify (
 STDDEV_TIME_IN_THE_IVR DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL
SET ABANDON_TIME_TOTAL = 0
WHERE ABANDON_TIME_TOTAL IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 ABANDON_TIME_TOTAL NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 ABANDON_TIME_TOTAL DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET AFTER_CALL_WORK_TIME_TOTAL = 0
WHERE AFTER_CALL_WORK_TIME_TOTAL IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 AFTER_CALL_WORK_TIME_TOTAL NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 AFTER_CALL_WORK_TIME_TOTAL DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET ANSWER_WAIT_TIME_TOTAL = 0
WHERE ANSWER_WAIT_TIME_TOTAL IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 ANSWER_WAIT_TIME_TOTAL NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 ANSWER_WAIT_TIME_TOTAL DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL
SET CALLS_ABANDONED_PERIOD_1 = 0
WHERE CALLS_ABANDONED_PERIOD_1 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_1 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_1 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_10 = 0
WHERE CALLS_ABANDONED_PERIOD_10 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_10 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_10 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL
SET CALLS_ABANDONED_PERIOD_2 = 0
WHERE CALLS_ABANDONED_PERIOD_2 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_2 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_2 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL
SET CALLS_ABANDONED_PERIOD_3 = 0
WHERE CALLS_ABANDONED_PERIOD_3 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_3 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_3 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_4 = 0
WHERE CALLS_ABANDONED_PERIOD_4 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_4 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_4 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL  
SET CALLS_ABANDONED_PERIOD_5 = 0
WHERE CALLS_ABANDONED_PERIOD_5 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_5 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_5 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_6 = 0
WHERE CALLS_ABANDONED_PERIOD_6 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_6 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_6 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL
SET CALLS_ABANDONED_PERIOD_7 = 0
WHERE CALLS_ABANDONED_PERIOD_7 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_7 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_7 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_8 = 0
WHERE CALLS_ABANDONED_PERIOD_8 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_8 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_8 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_9 = 0
WHERE CALLS_ABANDONED_PERIOD_9 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_9 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_9 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL
SET CONTACTS_ABANDONED = 0
WHERE CONTACTS_ABANDONED IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CONTACTS_ABANDONED NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CONTACTS_ABANDONED DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET CONTACTS_HANDLED = 0
WHERE CONTACTS_HANDLED IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CONTACTS_HANDLED NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CONTACTS_HANDLED DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET CONTACTS_OFFERED = 0
WHERE CONTACTS_OFFERED IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CONTACTS_OFFERED NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 CONTACTS_OFFERED DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL
SET HEADCOUNT_AVAILABLE = 0
WHERE HEADCOUNT_AVAILABLE IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 HEADCOUNT_AVAILABLE NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 HEADCOUNT_AVAILABLE DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET HOLD_TIME_TOTAL = 0
WHERE HOLD_TIME_TOTAL IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 HOLD_TIME_TOTAL NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 HOLD_TIME_TOTAL DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET OUTFLOW_CONTACTS = 0
WHERE OUTFLOW_CONTACTS IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 OUTFLOW_CONTACTS NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 OUTFLOW_CONTACTS DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET SERVICE_LEVEL_ABANDONED = 0
WHERE SERVICE_LEVEL_ABANDONED IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ABANDONED NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ABANDONED DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET SERVICE_LEVEL_ANSWERED_COUNT = 0
WHERE SERVICE_LEVEL_ANSWERED_COUNT IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_COUNT NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_COUNT DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET SERVICE_LEVEL_ANSWERED_PERCENT = 0
WHERE SERVICE_LEVEL_ANSWERED_PERCENT IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_PERCENT NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_PERCENT DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_1 = 0
WHERE SPEED_OF_ANSWER_PERIOD_1 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_1 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_1 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_10 = 0
WHERE SPEED_OF_ANSWER_PERIOD_10 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_10 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_10 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_2 = 0
WHERE SPEED_OF_ANSWER_PERIOD_2 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_2 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_2 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL  
SET SPEED_OF_ANSWER_PERIOD_3 = 0
WHERE SPEED_OF_ANSWER_PERIOD_3 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_3 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_3 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_4 = 0
WHERE SPEED_OF_ANSWER_PERIOD_4 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_4 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_4 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_5 = 0
WHERE SPEED_OF_ANSWER_PERIOD_5 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_5 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_5 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_6 = 0
WHERE SPEED_OF_ANSWER_PERIOD_6 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_6 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_6 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_7 = 0
WHERE SPEED_OF_ANSWER_PERIOD_7 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_7 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_7 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_8 = 0
WHERE SPEED_OF_ANSWER_PERIOD_8 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_8 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_8 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_9 = 0
WHERE SPEED_OF_ANSWER_PERIOD_9 IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_9 NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_9 DEFAULT 0
);

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL
SET TALK_TIME_TOTAL = 0
WHERE TALK_TIME_TOTAL IS NULL;

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 TALK_TIME_TOTAL NOT NULL
);

alter table CC_F_ACTUALS_QUEUE_INTERVAL modify (
 TALK_TIME_TOTAL DEFAULT 0
);

UPDATE CC_F_AGENT_BY_DATE 
SET IDLE_SECONDS = 0
WHERE IDLE_SECONDS IS NULL;

alter table CC_F_AGENT_BY_DATE modify (
 IDLE_SECONDS NOT NULL
);

alter table CC_F_AGENT_BY_DATE modify (
 IDLE_SECONDS DEFAULT 0
);

UPDATE CC_F_AGENT_BY_DATE 
SET LOGIN_SECONDS = 0
WHERE LOGIN_SECONDS IS NULL;

alter table CC_F_AGENT_BY_DATE modify (
 LOGIN_SECONDS NOT NULL
);

alter table CC_F_AGENT_BY_DATE modify (
 LOGIN_SECONDS DEFAULT 0
);

UPDATE CC_F_AGENT_BY_DATE 
SET NOT_READY_SECONDS = 0
WHERE NOT_READY_SECONDS IS NULL;

alter table CC_F_AGENT_BY_DATE modify (
 NOT_READY_SECONDS NOT NULL
);

alter table CC_F_AGENT_BY_DATE modify (
 NOT_READY_SECONDS DEFAULT 0
);

UPDATE CC_F_AGENT_RTG_GRP_INTERVAL
SET IDLE_SECONDS = 0
WHERE IDLE_SECONDS IS NULL;

alter table CC_F_AGENT_RTG_GRP_INTERVAL modify (
 IDLE_SECONDS NOT NULL
);

alter table CC_F_AGENT_RTG_GRP_INTERVAL modify (
 IDLE_SECONDS DEFAULT 0
);

UPDATE CC_F_AGENT_RTG_GRP_INTERVAL 
SET LOGIN_SECONDS = 0
WHERE LOGIN_SECONDS IS NULL;

alter table CC_F_AGENT_RTG_GRP_INTERVAL modify (
 LOGIN_SECONDS NOT NULL
);

alter table CC_F_AGENT_RTG_GRP_INTERVAL modify (
 LOGIN_SECONDS DEFAULT 0
);

UPDATE CC_F_AGENT_RTG_GRP_INTERVAL 
SET NOT_READY_SECONDS = 0
WHERE NOT_READY_SECONDS IS NULL;

alter table CC_F_AGENT_RTG_GRP_INTERVAL modify (
 NOT_READY_SECONDS NOT NULL
);

alter table CC_F_AGENT_RTG_GRP_INTERVAL modify (
 NOT_READY_SECONDS DEFAULT 0
);

UPDATE CC_F_IVR_SELF_SERVICE_USAGE 
SET CONTACTS_ENTERING = 0
WHERE CONTACTS_ENTERING IS NULL;

alter table CC_F_IVR_SELF_SERVICE_USAGE modify (
 CONTACTS_ENTERING NOT NULL
);

alter table CC_F_IVR_SELF_SERVICE_USAGE modify (
 CONTACTS_ENTERING DEFAULT 0
);

/* staging tables */

UPDATE CC_S_ACD_AGENT_INTERVAL
SET AFTER_CALL_WORK_TIME_TOTAL = 0
WHERE AFTER_CALL_WORK_TIME_TOTAL IS NULL;

alter table CC_S_ACD_AGENT_INTERVAL modify (
 AFTER_CALL_WORK_TIME_TOTAL NOT NULL
);

alter table CC_S_ACD_AGENT_INTERVAL modify (
 AFTER_CALL_WORK_TIME_TOTAL DEFAULT 0
);

UPDATE CC_S_ACD_AGENT_INTERVAL 
SET CONTACTS_ABANDONED = 0
WHERE CONTACTS_ABANDONED IS NULL;

alter table CC_S_ACD_AGENT_INTERVAL modify (
 CONTACTS_ABANDONED NOT NULL
);

alter table CC_S_ACD_AGENT_INTERVAL modify (
 CONTACTS_ABANDONED DEFAULT 0
);

UPDATE CC_S_ACD_AGENT_INTERVAL 
SET CONTACTS_HANDLED = 0
WHERE CONTACTS_HANDLED IS NULL;

alter table CC_S_ACD_AGENT_INTERVAL modify (
 CONTACTS_HANDLED NOT NULL
);

alter table CC_S_ACD_AGENT_INTERVAL modify (
 CONTACTS_HANDLED DEFAULT 0
);

UPDATE CC_S_ACD_AGENT_INTERVAL 
SET CONTACTS_OFFERED = 0
WHERE CONTACTS_OFFERED IS NULL;

alter table CC_S_ACD_AGENT_INTERVAL modify (
 CONTACTS_OFFERED NOT NULL
);

alter table CC_S_ACD_AGENT_INTERVAL modify (
 CONTACTS_OFFERED DEFAULT 0
);

UPDATE CC_S_ACD_AGENT_INTERVAL
SET WAIT_TIME_TOTAL = 0
WHERE WAIT_TIME_TOTAL IS NULL;

alter table CC_S_ACD_AGENT_INTERVAL modify (
 WAIT_TIME_TOTAL NOT NULL
);

alter table CC_S_ACD_AGENT_INTERVAL modify (
 WAIT_TIME_TOTAL DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET ABANDON_TIME_TOTAL = 0
WHERE ABANDON_TIME_TOTAL IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 ABANDON_TIME_TOTAL NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 ABANDON_TIME_TOTAL DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET ANSWER_WAIT_TIME_TOTAL = 0
WHERE ANSWER_WAIT_TIME_TOTAL IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 ANSWER_WAIT_TIME_TOTAL NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 ANSWER_WAIT_TIME_TOTAL DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_1 = 0
WHERE CALLS_ABANDONED_PERIOD_1 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_1 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_1 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_10 = 0
WHERE CALLS_ABANDONED_PERIOD_10 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_10 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_10 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_2 = 0
WHERE CALLS_ABANDONED_PERIOD_2 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_2 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_2 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_3 = 0
WHERE CALLS_ABANDONED_PERIOD_3 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_3 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_3 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_4 = 0
WHERE CALLS_ABANDONED_PERIOD_4 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_4 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_4 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_5 = 0
WHERE CALLS_ABANDONED_PERIOD_5 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_5 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_5 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_6 = 0
WHERE CALLS_ABANDONED_PERIOD_6 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_6 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_6 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_7 = 0
WHERE CALLS_ABANDONED_PERIOD_7 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_7 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_7 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_8 = 0
WHERE CALLS_ABANDONED_PERIOD_8 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_8 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_8 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET CALLS_ABANDONED_PERIOD_9 = 0
WHERE CALLS_ABANDONED_PERIOD_9 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_9 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_9 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET HEADCOUNT_AVAILABLE = 0
WHERE HEADCOUNT_AVAILABLE IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 HEADCOUNT_AVAILABLE NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 HEADCOUNT_AVAILABLE DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET HOLD_TIME_TOTAL = 0
WHERE HOLD_TIME_TOTAL IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 HOLD_TIME_TOTAL NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 HOLD_TIME_TOTAL DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET OUTFLOW_CONTACTS = 0
WHERE OUTFLOW_CONTACTS IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 OUTFLOW_CONTACTS NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 OUTFLOW_CONTACTS DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET SERVICE_LEVEL_ABANDONED = 0
WHERE SERVICE_LEVEL_ABANDONED IS NULL;

/*alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ABANDONED NOT NULL
);*/

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ABANDONED DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET SERVICE_LEVEL_ANSWERED_COUNT = 0
WHERE SERVICE_LEVEL_ANSWERED_COUNT IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_COUNT NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_COUNT DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET SERVICE_LEVEL_ANSWERED_PERCENT = 0
WHERE SERVICE_LEVEL_ANSWERED_PERCENT IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_PERCENT NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_PERCENT DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_1 = 0
WHERE SPEED_OF_ANSWER_PERIOD_1 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_1 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_1 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL
SET SPEED_OF_ANSWER_PERIOD_10 = 0
WHERE SPEED_OF_ANSWER_PERIOD_10 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_10 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_10 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_2 = 0
WHERE SPEED_OF_ANSWER_PERIOD_2 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_2 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_2 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_3 = 0
WHERE SPEED_OF_ANSWER_PERIOD_3 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_3 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_3 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_4 = 0
WHERE SPEED_OF_ANSWER_PERIOD_4 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_4 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_4 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_5 = 0
WHERE SPEED_OF_ANSWER_PERIOD_5 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_5 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_5 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL
SET SPEED_OF_ANSWER_PERIOD_6 = 0
WHERE SPEED_OF_ANSWER_PERIOD_6 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_6 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_6 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_7 = 0
WHERE SPEED_OF_ANSWER_PERIOD_7 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_7 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_7 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_8 = 0
WHERE SPEED_OF_ANSWER_PERIOD_8 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_8 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_8 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL
SET SPEED_OF_ANSWER_PERIOD_9 = 0
WHERE SPEED_OF_ANSWER_PERIOD_9 IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_9 NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_9 DEFAULT 0
);

UPDATE CC_S_ACD_QUEUE_INTERVAL 
SET TALK_TIME_TOTAL = 0
WHERE TALK_TIME_TOTAL IS NULL;

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 TALK_TIME_TOTAL NOT NULL
);

alter table CC_S_ACD_QUEUE_INTERVAL modify (
 TALK_TIME_TOTAL DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL
SET ABANDON_TIME_TOTAL = 0
WHERE ABANDON_TIME_TOTAL IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 ABANDON_TIME_TOTAL NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 ABANDON_TIME_TOTAL DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET AFTER_CALL_WORK_TIME_TOTAL = 0
WHERE AFTER_CALL_WORK_TIME_TOTAL IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 AFTER_CALL_WORK_TIME_TOTAL NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 AFTER_CALL_WORK_TIME_TOTAL DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET ANSWER_WAIT_TIME_TOTAL = 0
WHERE ANSWER_WAIT_TIME_TOTAL IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 ANSWER_WAIT_TIME_TOTAL NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 ANSWER_WAIT_TIME_TOTAL DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL
SET CALLS_ABANDONED_PERIOD_1 = 0
WHERE CALLS_ABANDONED_PERIOD_1 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_1 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_1 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET CALLS_ABANDONED_PERIOD_10 = 0
WHERE CALLS_ABANDONED_PERIOD_10 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_10 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_10 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL
SET CALLS_ABANDONED_PERIOD_2 = 0
WHERE CALLS_ABANDONED_PERIOD_2 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_2 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_2 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL
SET CALLS_ABANDONED_PERIOD_3 = 0
WHERE CALLS_ABANDONED_PERIOD_3 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_3 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_3 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET CALLS_ABANDONED_PERIOD_4 = 0
WHERE CALLS_ABANDONED_PERIOD_4 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_4 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_4 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL  
SET CALLS_ABANDONED_PERIOD_5 = 0
WHERE CALLS_ABANDONED_PERIOD_5 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_5 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_5 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET CALLS_ABANDONED_PERIOD_6 = 0
WHERE CALLS_ABANDONED_PERIOD_6 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_6 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_6 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL
SET CALLS_ABANDONED_PERIOD_7 = 0
WHERE CALLS_ABANDONED_PERIOD_7 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_7 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_7 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET CALLS_ABANDONED_PERIOD_8 = 0
WHERE CALLS_ABANDONED_PERIOD_8 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_8 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_8 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET CALLS_ABANDONED_PERIOD_9 = 0
WHERE CALLS_ABANDONED_PERIOD_9 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_9 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CALLS_ABANDONED_PERIOD_9 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL
SET CONTACTS_ABANDONED = 0
WHERE CONTACTS_ABANDONED IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 CONTACTS_ABANDONED NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CONTACTS_ABANDONED DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET CONTACTS_HANDLED = 0
WHERE CONTACTS_HANDLED IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 CONTACTS_HANDLED NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CONTACTS_HANDLED DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET CONTACTS_OFFERED = 0
WHERE CONTACTS_OFFERED IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 CONTACTS_OFFERED NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 CONTACTS_OFFERED DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL
SET HEADCOUNT_AVAILABLE = 0
WHERE HEADCOUNT_AVAILABLE IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 HEADCOUNT_AVAILABLE NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 HEADCOUNT_AVAILABLE DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET HOLD_TIME_TOTAL = 0
WHERE HOLD_TIME_TOTAL IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 HOLD_TIME_TOTAL NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 HOLD_TIME_TOTAL DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET OUTFLOW_CONTACTS = 0
WHERE OUTFLOW_CONTACTS IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 OUTFLOW_CONTACTS NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 OUTFLOW_CONTACTS DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET SERVICE_LEVEL_ABANDONED = 0
WHERE SERVICE_LEVEL_ABANDONED IS NULL;

/*alter table CC_S_ACD_INTERVAL modify (
 SERVICE_LEVEL_ABANDONED NOT NULL
);*/

alter table CC_S_ACD_INTERVAL modify (
 SERVICE_LEVEL_ABANDONED DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET SERVICE_LEVEL_ANSWERED_COUNT = 0
WHERE SERVICE_LEVEL_ANSWERED_COUNT IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_COUNT NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_COUNT DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET SERVICE_LEVEL_ANSWERED_PERCENT = 0
WHERE SERVICE_LEVEL_ANSWERED_PERCENT IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_PERCENT NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SERVICE_LEVEL_ANSWERED_PERCENT DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_1 = 0
WHERE SPEED_OF_ANSWER_PERIOD_1 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_1 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_1 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_10 = 0
WHERE SPEED_OF_ANSWER_PERIOD_10 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_10 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_10 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_2 = 0
WHERE SPEED_OF_ANSWER_PERIOD_2 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_2 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_2 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL  
SET SPEED_OF_ANSWER_PERIOD_3 = 0
WHERE SPEED_OF_ANSWER_PERIOD_3 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_3 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_3 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_4 = 0
WHERE SPEED_OF_ANSWER_PERIOD_4 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_4 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_4 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_5 = 0
WHERE SPEED_OF_ANSWER_PERIOD_5 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_5 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_5 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_6 = 0
WHERE SPEED_OF_ANSWER_PERIOD_6 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_6 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_6 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_7 = 0
WHERE SPEED_OF_ANSWER_PERIOD_7 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_7 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_7 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_8 = 0
WHERE SPEED_OF_ANSWER_PERIOD_8 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_8 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_8 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL 
SET SPEED_OF_ANSWER_PERIOD_9 = 0
WHERE SPEED_OF_ANSWER_PERIOD_9 IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_9 NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 SPEED_OF_ANSWER_PERIOD_9 DEFAULT 0
);

UPDATE CC_S_ACD_INTERVAL
SET TALK_TIME_TOTAL = 0
WHERE TALK_TIME_TOTAL IS NULL;

alter table CC_S_ACD_INTERVAL modify (
 TALK_TIME_TOTAL NOT NULL
);

alter table CC_S_ACD_INTERVAL modify (
 TALK_TIME_TOTAL DEFAULT 0
);

UPDATE CC_S_ACD_AGENT_ACTIVITY 
SET IDLE_SECONDS = 0
WHERE IDLE_SECONDS IS NULL;

alter table CC_S_ACD_AGENT_ACTIVITY modify (
 IDLE_SECONDS NOT NULL
);

alter table CC_S_ACD_AGENT_ACTIVITY modify (
 IDLE_SECONDS DEFAULT 0
);

UPDATE CC_S_ACD_AGENT_ACTIVITY 
SET LOGIN_SECONDS = 0
WHERE LOGIN_SECONDS IS NULL;

alter table CC_S_ACD_AGENT_ACTIVITY modify (
 LOGIN_SECONDS NOT NULL
);

alter table CC_S_ACD_AGENT_ACTIVITY modify (
 LOGIN_SECONDS DEFAULT 0
);

UPDATE CC_S_ACD_AGENT_ACTIVITY 
SET NOT_READY_SECONDS = 0
WHERE NOT_READY_SECONDS IS NULL;

alter table CC_S_ACD_AGENT_ACTIVITY modify (
 NOT_READY_SECONDS NOT NULL
);

alter table CC_S_ACD_AGENT_ACTIVITY modify (
 NOT_READY_SECONDS DEFAULT 0
);

UPDATE CC_S_AGENT_RTG_GRP_INTERVAL
SET IDLE_SECONDS = 0
WHERE IDLE_SECONDS IS NULL;

alter table CC_S_AGENT_RTG_GRP_INTERVAL modify (
 IDLE_SECONDS NOT NULL
);

alter table CC_S_AGENT_RTG_GRP_INTERVAL modify (
 IDLE_SECONDS DEFAULT 0
);

UPDATE CC_S_AGENT_RTG_GRP_INTERVAL 
SET LOGIN_SECONDS = 0
WHERE LOGIN_SECONDS IS NULL;

alter table CC_S_AGENT_RTG_GRP_INTERVAL modify (
 LOGIN_SECONDS NOT NULL
);

alter table CC_S_AGENT_RTG_GRP_INTERVAL modify (
 LOGIN_SECONDS DEFAULT 0
);

UPDATE CC_S_AGENT_RTG_GRP_INTERVAL 
SET NOT_READY_SECONDS = 0
WHERE NOT_READY_SECONDS IS NULL;

alter table CC_S_AGENT_RTG_GRP_INTERVAL modify (
 NOT_READY_SECONDS NOT NULL
);

alter table CC_S_AGENT_RTG_GRP_INTERVAL modify (
 NOT_READY_SECONDS DEFAULT 0
);

UPDATE CC_S_IVR_SELF_SERVICE_USAGE 
SET CONTACTS_ENTERING = 0
WHERE CONTACTS_ENTERING IS NULL;

alter table CC_S_IVR_SELF_SERVICE_USAGE modify (
 CONTACTS_ENTERING NOT NULL
);

alter table CC_S_IVR_SELF_SERVICE_USAGE modify (
 CONTACTS_ENTERING DEFAULT 0
);

commit;

