
select  distinct
 MIN_HANDLE_TIME 
 ,MAX_HANDLE_TIME 
 ,MEDIAN_HANDLE_TIME 
 ,STDDEV_HANDLE_TIME 
 ,MIN_SPEED_TO_HANDLE 
 ,MAX_SPEED_TO_HANDLE 
 ,MEDIAN_SPEED_TO_HANDLE 
 ,STDDEV_SPEED_TO_HANDLE 
 ,MIN_SPEED_OF_ANSWER 
 ,MEDIAN_SPEED_OF_ANSWER 
 ,STDDEV_SPEED_OF_ANSWER 
 ,LABOR_MINUTES_TOTAL 
 ,LABOR_MINUTES_WAITING 
 ,CONTACT_INVENTORY 
 ,CONTACT_INVENTORY_JEOPARDY 
 ,CONTACT_INVENTORY_AGE_TOTAL 
 ,MIN_CONTACT_INVENTORY_AGE 
 ,MAX_CONTACT_INVENTORY_AGE 
 ,MEAN_CONTACT_INVENTORY_AGE 
 ,MEDIAN_CONTACT_INVENTORY_AGE 
 ,STDDEV_CONTACT_INVENTORY_AGE 
 ,CONTACTS_TRANSFERRED 
 ,IVR_TIME_TOTAL 
 ,SHORT_ABANDONS 
 ,CALLS_GIVEN_FORCE_DISCONNECT 
 ,CALLS_GIVEN_ROUTE_TO 
 ,MAX_ABANDON_TIME 
 from cc_S_acd_interval;
 
 
 select  distinct
  MIN_HANDLE_TIME 
  ,MAX_HANDLE_TIME 
  ,MEDIAN_HANDLE_TIME 
  ,STDDEV_HANDLE_TIME 
  ,MIN_SPEED_TO_HANDLE 
  ,MAX_SPEED_TO_HANDLE 
  ,MEDIAN_SPEED_TO_HANDLE 
  ,STDDEV_SPEED_TO_HANDLE 
  ,MIN_SPEED_OF_ANSWER 
  ,MEDIAN_SPEED_OF_ANSWER 
  ,STDDEV_SPEED_OF_ANSWER 
  ,LABOR_MINUTES_TOTAL 
  ,LABOR_MINUTES_WAITING 
  ,CONTACT_INVENTORY 
  ,CONTACT_INVENTORY_JEOPARDY 
  ,CONTACT_INVENTORY_AGE_TOTAL 
  ,MIN_CONTACT_INVENTORY_AGE 
  ,MAX_CONTACT_INVENTORY_AGE 
  ,MEAN_CONTACT_INVENTORY_AGE 
  ,MEDIAN_CONTACT_INVENTORY_AGE 
  ,STDDEV_CONTACT_INVENTORY_AGE 
  ,CONTACTS_TRANSFERRED 
  ,IVR_TIME_TOTAL 
  ,SHORT_ABANDONS 
  ,CALLS_GIVEN_FORCE_DISCONNECT 
  ,CALLS_GIVEN_ROUTE_TO 
  ,MAX_ABANDON_TIME 
  from cc_S_acd_queue_interval;
  
  
  select distinct CONTACTS_TRANSFERRED
from cc_s_acd_agent_interval;


select distinct scheduled_shift_minutes, actual_overtime_minutes from cc_s_agent_work_day;


select  distinct
 MIN_HANDLE_TIME 
 ,MAX_HANDLE_TIME 
 ,MEDIAN_HANDLE_TIME 
 ,STDDEV_HANDLE_TIME 
 ,MIN_SPEED_TO_HANDLE 
 ,MAX_SPEED_TO_HANDLE 
 ,MEDIAN_SPEED_TO_HANDLE 
 ,STDDEV_SPEED_TO_HANDLE 
 ,MIN_SPEED_OF_ANSWER 
 ,MEDIAN_SPEED_OF_ANSWER 
 ,STDDEV_SPEED_OF_ANSWER 
 ,LABOR_MINUTES_TOTAL 
 ,LABOR_MINUTES_WAITING 
 ,CONTACT_INVENTORY 
 ,CONTACT_INVENTORY_JEOPARDY 
 ,MIN_CONTACT_INVENTORY_AGE 
 ,MAX_CONTACT_INVENTORY_AGE 
 ,MEAN_CONTACT_INVENTORY_AGE 
 ,MEDIAN_CONTACT_INVENTORY_AGE 
 ,STDDEV_CONTACT_INVENTORY_AGE 
 ,CONTACTS_TRANSFERRED 
 ,SHORT_ABANDONS 
 ,CALLS_GIVEN_FORCE_DISCONNECT 
 ,CALLS_GIVEN_ROUTE_TO 
 ,MAX_ABANDON_TIME 
 , LABOR_MINUTES_AVAILABLE
 , HEADCOUNT_TOTAL
, HEADCOUNT_UNAVAILABLE
from cc_f_actuals_queue_interval;


select  distinct
 MIN_HANDLE_TIME 
 ,MAX_HANDLE_TIME 
 ,MEDIAN_HANDLE_TIME 
 ,STDDEV_HANDLE_TIME 
 ,MIN_SPEED_TO_HANDLE 
 ,MAX_SPEED_TO_HANDLE 
 ,MEDIAN_SPEED_TO_HANDLE 
 ,STDDEV_SPEED_TO_HANDLE 
 ,MIN_SPEED_OF_ANSWER 
 ,MEDIAN_SPEED_OF_ANSWER 
 ,STDDEV_SPEED_OF_ANSWER 
 ,LABOR_MINUTES_TOTAL 
 ,LABOR_MINUTES_WAITING 
 ,CONTACT_INVENTORY 
 ,CONTACT_INVENTORY_JEOPARDY 
 ,MIN_CONTACT_INVENTORY_AGE 
 ,MAX_CONTACT_INVENTORY_AGE 
 ,MEAN_CONTACT_INVENTORY_AGE 
 ,MEDIAN_CONTACT_INVENTORY_AGE 
 ,STDDEV_CONTACT_INVENTORY_AGE 
 ,CONTACTS_TRANSFERRED 
 ,SHORT_ABANDONS 
 ,CALLS_GIVEN_FORCE_DISCONNECT 
 ,CALLS_GIVEN_ROUTE_TO 
 ,MAX_ABANDON_TIME 
  , LABOR_MINUTES_AVAILABLE
  , HEADCOUNT_TOTAL
, HEADCOUNT_UNAVAILABLE
 from cc_f_acd_queue_interval;
 
   select distinct CONTACTS_TRANSFERRED
from cc_f_acd_agent_interval;

select distinct scheduled_shift_minutes	, actual_overtime_minutes, break_time, consultation_time, walkaway_time, busyondntime
from cc_f_agent_by_date;