rename CC_S_TMP_PIPKINS_EVENT_INFO to CC_S_TMP_PIPKINS_EVENT;

INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME) 
VALUES ('0.3.1','104','104_RENAME_EVENT_INFO_to_EVENT');
commit;