-- Lookup tables

CREATE TABLE CC_C_IVR_SURVEY
  (
    QUESTION_NUMBER       VARCHAR2(100) NOT NULL,
    QUESTION              VARCHAR2(1000) NOT NULL,
    QUESTION_QUEUE_NUMBER NUMBER (19) NOT NULL,
    ANSWER_KEY            VARCHAR2(50) NOT NULL,
    ANSWER_TEXT           VARCHAR2(100) NOT NULL,
    ANSWER_QUEUE_NUMBER   NUMBER (19) NOT NULL,
    CREATE_DATE                 DATE DEFAULT SYSDATE NOT NULL ,
    LAST_UPDATE_DATE            DATE DEFAULT SYSDATE NOT NULL ,
    LAST_UPDATED_BY 		VARCHAR2(30)NOT NULL
  ) ;
  
  ALTER TABLE CC_C_IVR_SURVEY ADD CONSTRAINT CC_C_IVR_SURVEY_PK PRIMARY KEY
    (
      ANSWER_QUEUE_NUMBER
    ) ;  
  
  ALTER TABLE CC_C_IVR_SURVEY ADD CONSTRAINT CC_C_IVR_SURVEY_UN UNIQUE
    (
      QUESTION, ANSWER_KEY
    )
    ;
    
  CREATE OR REPLACE TRIGGER BIU_CC_C_IVR_SURVEY
      BEFORE INSERT OR UPDATE ON CC_C_IVR_SURVEY
      FOR EACH ROW 
  BEGIN 
  IF INSERTING THEN 
            :NEW.CREATE_DATE := SYSDATE;
  END IF;
  :NEW.LAST_UPDATE_DATE := SYSDATE;
  :NEW.LAST_UPDATED_BY := USER;
  END; 
  /  
  
  
CREATE TABLE CC_C_IVR_SURVEY_LANGUAGE
  (
    QUEUE_NUMBER       NUMBER(19) NOT NULL,
    LANGUAGE          VARCHAR2(500) NOT NULL,
    CREATE_DATE                 DATE DEFAULT SYSDATE NOT NULL ,
    LAST_UPDATE_DATE            DATE DEFAULT SYSDATE NOT NULL ,
    LAST_UPDATED_BY 		VARCHAR2(30)NOT NULL
  ) ;
  
 ALTER TABLE CC_C_IVR_SURVEY_LANGUAGE ADD CONSTRAINT CC_C_IVR_SURVEY_LANGUAGE_PK PRIMARY KEY
    (
      QUEUE_NUMBER
    ) ; 
    
  CREATE OR REPLACE TRIGGER BIU_CC_C_IVR_SURVEY_LANGUAGE
      BEFORE INSERT OR UPDATE ON CC_C_IVR_SURVEY_LANGUAGE
      FOR EACH ROW 
  BEGIN 
  IF INSERTING THEN 
            :NEW.CREATE_DATE := SYSDATE;
  END IF;
  :NEW.LAST_UPDATE_DATE := SYSDATE;
  :NEW.LAST_UPDATED_BY := USER;
  END; 
  / 

CREATE INDEX CC_F_ACTUALS_Q_INTERVAL_IDX10 ON CC_F_ACTUALS_QUEUE_INTERVAL
      (
        QUEUE_NUMBER ASC
      ) ; 
  
 
-- semantic views 

CREATE OR REPLACE VIEW CC_C_IVR_SURVY_SV AS
SELECT * FROM CC_C_IVR_SURVEY;

  
GRANT SELECT ON CC_C_IVR_SURVY_SV TO MAXDAT_READ_ONLY; 

CREATE OR REPLACE VIEW CC_C_IVR_SURVY_LANGUAGE_SV AS
SELECT * FROM CC_C_IVR_SURVEY_LANGUAGE;

GRANT SELECT ON CC_C_IVR_SURVY_LANGUAGE_SV TO MAXDAT_READ_ONLY; 

CREATE OR REPLACE VIEW CC_F_IVR_SURVY_LANG_BY_DATE_SV AS
SELECT
D.D_DATE AS SURVEY_DATE
, F.QUEUE_NUMBER 
, L."LANGUAGE" as SURVEY_LANGUAGE
, sum (F.RAW_CONTACTS_OFFERED) as CALLS_COUNT
FROM 
CC_F_ACTUALS_QUEUE_INTERVAL F , CC_D_DATES D, CC_C_IVR_SURVEY_LANGUAGE L
WHERE F.D_DATE_ID = D.D_DATE_ID
AND F.QUEUE_NUMBER = L.QUEUE_NUMBER
GROUP BY D.D_DATE, F.QUEUE_NUMBER, L."LANGUAGE";

GRANT SELECT ON CC_F_IVR_SURVY_LANG_BY_DATE_SV TO MAXDAT_READ_ONLY; 

CREATE OR REPLACE VIEW CC_F_IVR_SURVY_BY_DATE_SV AS
SELECT
D.D_DATE AS SURVEY_DATE
, S.QUESTION_NUMBER
, S.QUESTION
, S.ANSWER_KEY
, S.ANSWER_TEXT
, sum (F.RAW_CONTACTS_OFFERED) as ANSWER_COUNT
FROM CC_F_ACTUALS_QUEUE_INTERVAL F, CC_D_DATES D, CC_C_IVR_SURVEY S
WHERE F.D_DATE_ID = D.D_DATE_ID
AND F.QUEUE_NUMBER = S.ANSWER_QUEUE_NUMBER
GROUP BY D_DATE, QUESTION_NUMBER, QUESTION, ANSWER_KEY, ANSWER_TEXT;

GRANT SELECT ON CC_F_IVR_SURVY_BY_DATE_SV TO MAXDAT_READ_ONLY; 