alter table d_letter_request add
(
PROGRAM_CON_XWALK_CODE VARCHAR2(30)
, CON_FILE_NAME  VARCHAR2(1000)
, CON_FILE_CREATION_DATE 	DATE
, CON_FILE_LOAD_DATE	DATE
, CON_CARD_REQUEST_FILE_NAME   VARCHAR2(200) 
, CON_RECIPIENT_FIRST_NAME VARCHAR2(80 ) 
, CON_RECIPIENT_LAST_NAME VARCHAR2(80 ) 
, CON_RECIPIENT_MI VARCHAR2(80 ) 
, CON_ATTENTION_LINE VARCHAR2(80 ) 
, CON_STREET_ADDRESS VARCHAR2(200 ) 
, CON_CITY VARCHAR2(80 ) 
, CON_STATE VARCHAR2(80 ) 
, CON_ZIP_CODE VARCHAR2(32 ) 
, CON_STATUS_CODE VARCHAR2(80 ) 
, CON_UPDATE_CODE VARCHAR2(80 ) 
, CON_CASE_ID VARCHAR2(32 ) 
, CON_MAILING_DATE DATE 
, CON_CONTROL_NUMBER VARCHAR2(80 ) 
, CON_RECIPIENT_ID VARCHAR2(80 ) 
, CON_MI_CARD_ID VARCHAR2(80 ) 
, CON_JOB_CTRL_ID NUMBER(38) 
, CON_SOURCE_JOB_ID	NUMBER(38)
, CON_SOURCE_ROW_NUM	NUMBER(38)
, CON_ERROR_COUNT NUMBER(18, 0) 
, CON_ERROR_TEXT VARCHAR2(512 ) 
, CON_ERROR_FIELDS VARCHAR2(512 ) 
, CON_LETTER_REQ_ID NUMBER(18, 0) 
);

alter table s_letter_request_stg add (
checksum number(10)
);

alter table d_letter_request add (
stg_checksum number(10)
);

