--Re-Enable Constraints
ALTER TABLE CC_D_AGENT
ENABLE CONSTRAINT CC_D_AGENT_REC_DATE_CK;

ALTER TABLE CC_D_AGENT
ENABLE CONSTRAINT CC_D_AGENT__UN;

INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME)
VALUES ('1.3.1','102','102_TXEB_DUPLICATED_AGENT_CLEANUP_3');

COMMIT;
