ALTER TABLE BPM_INSTANCE ADD CONSTRAINT BPM_INSTANCE_UNK2 UNIQUE ( BEM_ID, BSL_ID, SOURCE_ID ) USING INDEX COMPUTE STATISTICS TABLESPACE MAXDAT_INDX;
CREATE INDEX BPM_INSTANCE_ATTRIBUTE_IX4 ON BPM_INSTANCE_ATTRIBUTE (BA_ID, START_DATE, END_DATE, BI_ID, VALUE_NUMBER) COMPUTE STATISTICS TABLESPACE MAXDAT_INDX;
CREATE INDEX BPM_INSTANCE_ATTRIBUTE_IX5 ON BPM_INSTANCE_ATTRIBUTE (BA_ID, START_DATE, END_DATE, BI_ID, VALUE_CHAR) COMPUTE STATISTICS TABLESPACE MAXDAT_INDX;
CREATE INDEX BPM_INSTANCE_ATTRIBUTE_IX6 ON BPM_INSTANCE_ATTRIBUTE (BA_ID, START_DATE, END_DATE, BI_ID, VALUE_DATE) COMPUTE STATISTICS TABLESPACE MAXDAT_INDX;
create INDEX BPM_INSTANCE_IX1 ON BPM_INSTANCE (END_DATE ASC, START_DATE ASC) COMPUTE STATISTICS TABLESPACE MAXDAT_INDX;
create UNIQUE INDEX BPM_INSTANCE_UNK3 ON BPM_INSTANCE (START_DATE, END_DATE, BI_ID) COMPUTE STATISTICS TABLESPACE MAXDAT_INDX;
