update PROCESS_BPM_QUEUE_JOB 
set END_DATE = STATUS_DATE
where 
  END_DATE is null 
  and STATUS = 'STOPPED';
  
commit;


UPDATE BPM_UPDATE_EVENT_QUEUE
   SET WROTE_BPM_EVENT_DATE=SYSDATE
 WHERE BUEQ_ID IN 
		(
		SELECT q.BUEQ_ID 
		  FROM BPM_UPDATE_EVENT_QUEUE q
		 WHERE WROTE_BPM_EVENT_DATE IS NULL
		   AND q.OLD_DATA IS NULL
		   AND IDENTIFIER IN (SELECT IDENTIFIER FROM BPM_INSTANCE i WHERE i.BSL_ID=q.BSL_ID AND i.IDENTIFIER=q.IDENTIFIER)
		)
		
COMMIT;
