create or replace sequence coverva_dmas.seq_appmetric_v2_data_id;
CREATE OR REPLACE sequence coverva_dmas.seq_dmas_application_v2_inv_id;
CREATE OR REPLACE sequence coverva_dmas.seq_dmas_application_v2_current_id;
CREATE OR REPLACE sequence coverva_dmas.seq_dmas_application_v2_excluded_id;
CREATE OR REPLACE sequence coverva_dmas.seq_dmas_application_v2_event_id;

CREATE TABLE COVERVA_DMAS.APP_METRIC_V2_FULL_LOAD(
       appmetric_data_id NUMBER NOT NULL DEFAULT coverva_dmas.seq_appmetric_v2_data_id.nextval,
       Tracking_Number VARCHAR NOT NULL,
       Case_Number VARCHAR NULL,
       Application_Type VARCHAR,
       App_Received_Date TIMESTAMP_NTZ NULL,
       FFM_Transfer_Date TIMESTAMP_NTZ NULL,
       FFM_Application_Type VARCHAR NULL,
       Application_Status VARCHAR NULL,
       Application_Source VARCHAR NULL,
       Worker_ID VARCHAR NULL,
       Stage VARCHAR NULL,
       Range VARCHAR NULL,
       Pending_due_to_VCL VARCHAR NULL,
       VCL_Due_Date TIMESTAMP_NTZ NULL,
       Applicant_Last_Name VARCHAR NULL,
       Applicant_First_Name VARCHAR NULL,
       Application_ABD_Indicator VARCHAR NULL,
       Case_ABD_Indicator VARCHAR NULL,
       Application_LTC_Indicator VARCHAR NULL,
       Case_LTC_Indicator VARCHAR NULL,
       Application_Incarcerated_Indicator VARCHAR NULL,
       Case_Incarcerated_Indicator VARCHAR NULL,
       MA_PG_Indicator VARCHAR NULL,
       Processing_Unit VARCHAR NULL,       
       Filename VARCHAR NULL,
       VCL_Sent_Date TIMESTAMP_NTZ NULL);

alter table COVERVA_DMAS.APP_METRIC_V2_FULL_LOAD add primary key (appmetric_data_id);

CREATE TABLE coverva_dmas.DMAS_Application_V2_Inventory(
DMAS_Application_ID NUMBER NOT NULL DEFAULT coverva_dmas.seq_dmas_application_v2_inv_id.nextval,
Tracking_Number VARCHAR NOT NULL,
Source VARCHAR NULL,
App_Received_Date TIMESTAMP_NTZ NULL,
Processing_Unit VARCHAR NULL,
Application_Type VARCHAR NULL, 
Current_State VARCHAR NULL,
Initial_Review_Complete_Date TIMESTAMP_NTZ NULL,
Application_Processing_End_Date TIMESTAMP_NTZ NULL,
Last_Employee VARCHAR NULL,
Applicant_Name VARCHAR NULL,  
Case_Number VARCHAR NULL, 
Override_Value_Indicator VARCHAR NULL,
FP_Create_Dt TIMESTAMP_NTZ NULL, 
FP_Update_Dt TIMESTAMP_NTZ NULL,
File_ID VARCHAR NULL,
In_CP_Indicator VARCHAR NULL,
Migrated_App_Indicator VARCHAR NULL,
Initial_Review_DT_Null_Reason VARCHAR NULL,
Last_Employee_Null_Reason VARCHAR NULL,
End_Date_Null_Reason VARCHAR NULL,
VCL_Due_Date TIMESTAMP_NTZ NULL,
Intake_Date TIMESTAMP_NTZ NULL,
Complete_Date TIMESTAMP_NTZ NULL,
File_Inventory_Date TIMESTAMP_NTZ NULL,
maximus_source_date TIMESTAMP_NTZ,
state_app_received_date TIMESTAMP_NTZ NULL,
cp_application_type VARCHAR NULL,
cm044_verified VARCHAR(3),
non_maximus_initial_date TIMESTAMP_NTZ(9),
non_maximus_returned_date TIMESTAMP_NTZ(9),
vcl_sent_date DATE,
Case_Type VARCHAR,
SD_Stage VARCHAR);

--alter table COVERVA_DMAS.DMAS_Application add primary key (Application_ID,File_Inventory_Date);
alter table COVERVA_DMAS.DMAS_Application_V2_Inventory add primary key (DMAS_Application_ID);

CREATE OR REPLACE TABLE coverva_dmas.DMAS_Excluded_V2_Application(
DMAS_Excluded_Application_ID NUMBER NOT NULL DEFAULT coverva_dmas.seq_dmas_application_v2_excluded_id.nextval,
Tracking_Number VARCHAR NOT NULL,
Ignore_Application_Reason VARCHAR NULL,
File_ID VARCHAR NULL,
File_Inventory_Date TIMESTAMP_NTZ NULL,
FP_Create_Dt TIMESTAMP_NTZ NULL, 
FP_Update_Dt TIMESTAMP_NTZ NULL
);

--alter table COVERVA_DMAS.DMAS_Excluded_Application add primary key (Application_ID,File_Inventory_Date);
alter table COVERVA_DMAS.DMAS_Excluded_V2_Application add primary key (DMAS_Excluded_Application_ID);

CREATE TABLE coverva_dmas.DMAS_Application_V2_Current(
DMAS_Application_Current_ID NUMBER NOT NULL DEFAULT coverva_dmas.seq_dmas_application_v2_current_id.nextval,
Tracking_Number VARCHAR NOT NULL,
Source VARCHAR NULL,
App_Received_Date TIMESTAMP_NTZ NULL,
Processing_Unit VARCHAR NULL,
Application_Type VARCHAR NULL, 
Current_State VARCHAR NULL,
Initial_Review_Complete_Date TIMESTAMP_NTZ NULL,
Application_Processing_End_Date TIMESTAMP_NTZ NULL,
Last_Employee VARCHAR NULL,
Applicant_Name VARCHAR NULL,  
Case_Number VARCHAR NULL, 
Override_Value_Indicator VARCHAR NULL,
FP_Create_Dt TIMESTAMP_NTZ NULL, 
FP_Update_Dt TIMESTAMP_NTZ NULL,
File_ID VARCHAR NULL,
In_CP_Indicator VARCHAR NULL,
Migrated_App_Indicator VARCHAR NULL,
Initial_Review_DT_Null_Reason VARCHAR NULL,
Last_Employee_Null_Reason VARCHAR NULL,
End_Date_Null_Reason VARCHAR NULL,
VCL_Due_Date TIMESTAMP_NTZ NULL,
Intake_Date TIMESTAMP_NTZ NULL,
Complete_Date TIMESTAMP_NTZ NULL,
File_Inventory_Date TIMESTAMP_NTZ NULL,
maximus_source_date TIMESTAMP_NTZ,
state_app_received_date TIMESTAMP_NTZ NULL,
cp_application_type VARCHAR NULL,
cm044_verified VARCHAR(3),
non_maximus_initial_date TIMESTAMP_NTZ(9),
non_maximus_returned_date TIMESTAMP_NTZ(9),
vcl_sent_date DATE,
Case_Type VARCHAR,
SD_Stage VARCHAR);

alter table COVERVA_DMAS.DMAS_Application_V2_Current add primary key (DMAS_Application_Current_ID);

CREATE TABLE coverva_dmas.DMAS_Application_V2_Event(
Application_Event_ID  NUMBER DEFAULT coverva_dmas.seq_dmas_application_v2_event_id.nextval,
tracking_number VARCHAR NOT NULL,
event_date TIMESTAMP_NTZ NULL,
in_app_metric VARCHAR NULL,
in_app_metric_pw VARCHAR NULL,
in_ppit VARCHAR NULL,
in_cm043 VARCHAR NULL,
in_cm044 VARCHAR NULL,
in_cviu VARCHAR NULL,
in_cpu_incarcerated VARCHAR NULL,
in_cpu VARCHAR NULL,
cpu_status VARCHAR NULL,
cpu_app_received_date TIMESTAMP_NTZ NULL,
cm044_status VARCHAR NULL,
cm044_authorized_date TIMESTAMP_NTZ NULL,
override_status VARCHAR NULL,
cviu_processing_status VARCHAR NULL,
cpui_processing_status VARCHAR NULL,
pending_due_vcl_pw VARCHAR NULL,
pending_due_vcl_am VARCHAR NULL,
ppit_worker VARCHAR NULL,
cpui_worker VARCHAR NULL,
cviu_worker VARCHAR NULL,
cpu_worker VARCHAR NULL,
am_worker VARCHAR NULL,
pw_worker VARCHAR NULL,
vcl_due_date_am TIMESTAMP_NTZ NULL,
vcl_due_date_pw TIMESTAMP_NTZ NULL,
override_app_end_date TIMESTAMP_NTZ NULL,
override_last_employee VARCHAR,
in_app_override VARCHAR,
cm044_worker VARCHAR,
cm043_status VARCHAR NULL,
prev_current_state VARCHAR NULL,
prev_app_end_date TIMESTAMP_NTZ NULL,
running_cpu_status VARCHAR NULL,
running_cpu_app_received_date TIMESTAMP_NTZ NULL,
event_create_date TIMESTAMP_NTZ NULL,
event_update_date TIMESTAMP_NTZ NULL,
cp_iar_action_taken VARCHAR NULL,
cp_iar_ldss_created_on TIMESTAMP_NTZ NULL,
cp_iar_ldss_end_date TIMESTAMP_NTZ NULL, 
cp_inv_ad_disposition VARCHAR NULL,
cp_inv_ad_create_date TIMESTAMP_NTZ NULL,
cp_inv_ad_status_date TIMESTAMP_NTZ NULL,
cp_inv_ad_complete_date TIMESTAMP_NTZ NULL,
cp_inv_ad_worker VARCHAR NULL, 
cp_iar_ad_disposition VARCHAR NULL,
cp_iar_ad_created_on TIMESTAMP_NTZ NULL,
cp_iar_ad_status_date TIMESTAMP_NTZ NULL, 
cp_inv_pend_disposition VARCHAR NULL,
cp_inv_pend_create_date TIMESTAMP_NTZ NULL,
cp_inv_pend_status_date TIMESTAMP_NTZ NULL,
cp_inv_pend_complete_date TIMESTAMP_NTZ NULL,
cp_inv_pend_worker VARCHAR NULL, 
cp_iar_pend_disposition VARCHAR NULL,
cp_iar_pend_created_on TIMESTAMP_NTZ NULL,
cp_iar_pend_status_date TIMESTAMP_NTZ NULL, 
manual_cpu_status VARCHAR NULL,
mcpu_activity_date TIMESTAMP_NTZ NULL,
mcpu_last_employee VARCHAR NULL, 
manual_cviu_status VARCHAR NULL,
mcviu_activity_date TIMESTAMP_NTZ NULL, 
manual_prod_status VARCHAR NULL,
mpt_orig_status VARCHAR NULL,
mpt_complete_date TIMESTAMP_NTZ NULL,
mpt_last_employee VARCHAR NULL,
cp_inv_action_taken VARCHAR,
cp_inv_ldss_create_date TIMESTAMP_NTZ,
cp_inv_ldss_status_date TIMESTAMP_NTZ,
cp_inv_ldss_end_date TIMESTAMP_NTZ,
cp_inv_ldss_worker VARCHAR,
running_cpu_worker VARCHAR,
running_cpu_file_date TIMESTAMP_NTZ,
mpt_vcl_due_date TIMESTAMP_NTZ,
cp_vcl_due_date TIMESTAMP_NTZ,
iar_vcl_due_date TIMESTAMP_NTZ,
running_am_worker VARCHAR,
running_ppit_worker VARCHAR,
running_cviu_worker VARCHAR,
running_cviu_status VARCHAR,
running_cpui_worker VARCHAR,
running_cpui_status VARCHAR,
in_running_am VARCHAR,
in_running_ppit VARCHAR,
in_running_pw VARCHAR,
in_running_cm043 VARCHAR,
in_running_cviu VARCHAR,
in_running_cpui VARCHAR,
in_running_cpu VARCHAR,
mio_prod_status VARCHAR,
mio_orig_status VARCHAR,
mio_complete_date TIMESTAMP_NTZ,
mio_last_employee VARCHAR,
mio_vcl_due_date TIMESTAMP_NTZ,
Case_Type VARCHAR,
SD_Stage VARCHAR);

alter table COVERVA_DMAS.DMAS_Application_V2_Event add primary key (Application_Event_ID);

DELETE FROM coverva_dmas.dmas_file_load_lkup
WHERE filename_prefix = 'APPMETRIC_REPORT';
INSERT INTO coverva_dmas.dmas_file_load_lkup(filename_prefix,full_load_table_name,full_load_table_schema,insert_fields,select_fields,where_clause,load_file,use_in_inventory,with_timestamp,file_day_received,use_in_v2_inventory)
VALUES('APPMETRIC_REPORT','APP_METRIC_V2_FULL_LOAD','COVERVA_DMAS','Tracking_Number,Case_Number,Application_Type,App_Received_Date,FFM_Transfer_Date,FFM_Application_Type,Application_Status,Application_Source,Worker_ID,Stage,Range,Pending_due_to_VCL,VCL_Due_Date,Applicant_Last_Name,Applicant_First_Name,Application_ABD_Indicator,Case_ABD_Indicator,Application_LTC_Indicator,Case_LTC_Indicator,Application_Incarcerated_Indicator,Case_Incarcerated_Indicator,MA_PG_Indicator,Processing_Unit,Filename,VCL_Sent_Date'
       ,'REGEXP_REPLACE(Tracking_Number,''[^A-Za-z0-9]'',''''),Case_Number,Application_Type,CAST(regexp_replace(application_date,''[^A-Za-z0-9 -:/*]'','''') AS DATE) AS application_date,CAST(regexp_replace(ffm_transfer_date,''[^A-Za-z0-9 -:/*]'','''') AS DATE) AS ffm_transfer_date,FFM_Application_Type,Application_Status,Application_Source,Worker_ID,SD_Stage,Range,Pending_due_to_VCL,CAST(regexp_replace(vcl_due_date,''[^A-Za-z0-9 -:/*]'','''') AS DATE) AS vcl_due_date,Applicant_Last_Name,Applicant_First_Name,Application_Aged_Blind_Disabled_Indicator,Case_Aged_Blind_Disabled_Indicator,Application_Long_Term_Care_Indicator,Case_Long_Term_Care_Indicator,Application_Incarcerated_Indicator,Case_Incarcerated_Indicator,mapg_indicator,Processing_Unit,Filename,VCL_Sent_Date'
       ,'WHERE 1=1','Y','N','Y','PREVIOUS_BUSINESS_DAY','Y');