use maxdat
go

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_D_ACTIVITY_TYPE')
BEGIN
DROP SEQUENCE SEQ_CC_D_ACTIVITY_TYPE
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_D_AGENT')
BEGIN
DROP SEQUENCE SEQ_CC_D_AGENT
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_D_CONTACT_QUEUE')
BEGIN
DROP SEQUENCE SEQ_CC_D_CONTACT_QUEUE
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_D_DATE')
BEGIN
DROP SEQUENCE SEQ_CC_D_DATE
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_D_FORECAST_NOTES')
BEGIN
DROP SEQUENCE SEQ_CC_D_FORECAST_NOTES
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_D_GEOGRAPHY_MASTER')
BEGIN
DROP SEQUENCE SEQ_CC_D_GEOGRAPHY_MASTER
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_D_GROUP')
BEGIN
DROP SEQUENCE SEQ_CC_D_GROUP
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_D_INTERVAL')
BEGIN
DROP SEQUENCE SEQ_CC_D_INTERVAL
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_D_IVR_SELF_SERVICE_PATH')
BEGIN
DROP SEQUENCE SEQ_CC_D_IVR_SELF_SERVICE_PATH
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_D_PRODUCTION_PLAN')
BEGIN
DROP SEQUENCE SEQ_CC_D_PRODUCTION_PLAN
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_D_PROD_PLAN_HORIZON')
BEGIN
DROP SEQUENCE SEQ_CC_D_PROD_PLAN_HORIZON
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_D_PROGRAM')
BEGIN
DROP SEQUENCE SEQ_CC_D_PROGRAM
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_D_PROJECT')
BEGIN
DROP SEQUENCE SEQ_CC_D_PROJECT
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_D_PROJECT_TARGETS')
BEGIN
DROP SEQUENCE SEQ_CC_D_PROJECT_TARGETS
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_D_SITE')
BEGIN
DROP SEQUENCE SEQ_CC_D_SITE
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_D_UNIT_OF_WORK')
BEGIN
DROP SEQUENCE SEQ_CC_D_UNIT_OF_WORK
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_F_ACTUALS_IVR_INTERVAL')
BEGIN
DROP SEQUENCE SEQ_CC_F_ACTUALS_IVR_INTERVAL
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_F_ACTUALS_Q_INTERVAL')
BEGIN
DROP SEQUENCE SEQ_CC_F_ACTUALS_Q_INTERVAL
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_F_AGENT_ACTVTY_BY_DATE')
BEGIN
DROP SEQUENCE SEQ_CC_F_AGENT_ACTVTY_BY_DATE
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_F_AGENT_BY_DATE')
BEGIN
DROP SEQUENCE SEQ_CC_F_AGENT_BY_DATE
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_F_FORECAST_INTERVAL')
BEGIN
DROP SEQUENCE SEQ_CC_F_FORECAST_INTERVAL
END;

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME='SEQ_CC_F_IVR_SELF_SVC_USAGE')
BEGIN
DROP SEQUENCE SEQ_CC_F_IVR_SELF_SVC_USAGE
END;

CREATE SEQUENCE SEQ_CC_D_ACTIVITY_TYPE as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_D_AGENT as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_D_CONTACT_QUEUE as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_D_DATE as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_D_FORECAST_NOTES as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_D_GEOGRAPHY_MASTER as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_D_GROUP as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_D_INTERVAL as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_D_IVR_SELF_SERVICE_PATH as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_D_PRODUCTION_PLAN as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_D_PROD_PLAN_HORIZON as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_D_PROGRAM as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_D_PROJECT as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_D_PROJECT_TARGETS as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_D_SITE as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_D_UNIT_OF_WORK as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_F_ACTUALS_IVR_INTERVAL as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_F_ACTUALS_Q_INTERVAL as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_F_AGENT_ACTVTY_BY_DATE as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_F_AGENT_BY_DATE as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_F_FORECAST_INTERVAL as NUMERIC(19) increment by 1;
CREATE SEQUENCE SEQ_CC_F_IVR_SELF_SVC_USAGE as NUMERIC(19) increment by 1;

GRANT REFERENCES, UPDATE ON SEQ_CC_D_ACTIVITY_TYPE TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_D_AGENT TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_D_CONTACT_QUEUE TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_D_DATE TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_D_FORECAST_NOTES TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_D_GEOGRAPHY_MASTER TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_D_GROUP TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_D_INTERVAL TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_D_IVR_SELF_SERVICE_PATH TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_D_PRODUCTION_PLAN TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_D_PROD_PLAN_HORIZON TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_D_PROGRAM TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_D_PROJECT TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_D_PROJECT_TARGETS TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_D_SITE TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_D_UNIT_OF_WORK TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_F_ACTUALS_IVR_INTERVAL TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_F_ACTUALS_Q_INTERVAL TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_F_AGENT_ACTVTY_BY_DATE TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_F_AGENT_BY_DATE TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_F_FORECAST_INTERVAL TO MAXDAT_READ_ONLY;
GRANT REFERENCES, UPDATE ON SEQ_CC_F_IVR_SELF_SVC_USAGE TO MAXDAT_READ_ONLY;
