use MAXDAT
go


CREATE
  TABLE CC_A_ADHOC_JOB
  (
    ADHOC_JOB_ID         NUMERIC (19) not null primary key  constraint CC_A_ADHOC_JOB_PK default next value for SEQ_CC_A_ADHOC_JOB ,
    ADHOC_JOB_TYPE       VARCHAR (50) NOT NULL ,
    START_DATETIME_PARAM VARCHAR (50) NOT NULL ,
    END_DATETIME_PARAM   VARCHAR (50) NOT NULL ,
    CREATION_DATE        DATETIME NOT NULL ,
    IS_PENDING BIT NOT NULL ,
    IS_RUNNING BIT NOT NULL ,
    JOB_START_DATE DATETIME ,
    JOB_END_DATE   DATETIME ,
    SUCCESS BIT 
  )
  ON "default"
GO

CREATE
  TABLE CC_A_SCHEDULE
  (
    SCHEDULE_ID    NUMERIC (19) not null primary key  constraint CC_A_SCHEDULE_PK default next value for SEQ_CC_A_SCHEDULE,
    JOB_TYPE       VARCHAR (50) NOT NULL ,
    EXECUTION_TIME VARCHAR (50) NOT NULL
  )
  ON "default"
GO
/*
ALTER TABLE CC_A_SCHEDULE ADD CONSTRAINT REGEX_CHECK_EXECUTION_TIME CHECK ( REGEXP_LIKE(EXECUTION_TIME,'^([01][0-9]|2[0-3]):00:00$','i') ) 
GO
*/

CREATE
  TABLE CC_A_SCHEDULED_JOB
  (
    SCHEDULED_JOB_ID     NUMERIC (19) not null primary key  constraint CC_A_SCHEDULED_JOB_PK default next value for SEQ_CC_A_SCHEDULED_JOB ,
    SCHEDULED_JOB_TYPE   VARCHAR (50) NOT NULL ,
    START_DATETIME_PARAM VARCHAR (50) NOT NULL ,
    END_DATETIME_PARAM   VARCHAR (50) NOT NULL ,
    JOB_START_DATE       DATETIME NOT NULL ,
    JOB_END_DATE         DATETIME ,
    IS_RUNNING BIT NOT NULL ,
    SUCCESS BIT ,
    DATA_VALIDATION VARCHAR (50) ,
  CONSTRAINT CC_A_SCHEDULED_JOB__UN UNIQUE NONCLUSTERED (JOB_START_DATE) ON
  "default"
  )
  ON "default"
GO
ALTER TABLE CC_A_SCHEDULED_JOB
ADD
CHECK ( DATA_VALIDATION IN ('FAILURE', 'NOT_TESTED', 'SUCCESS') )
GO

CREATE
  TABLE CC_C_ACTIVITY_TYPE
  (
    ACTIVITY_TYPE_ID          NUMERIC (19) not null primary key  constraint CC_C_ACTIVITY_TYPE_PK default next value for SEQ_CC_C_ACTIVITY_TYPE ,
    ACTIVITY_TYPE_NAME        VARCHAR (100) NOT NULL ,
    ACTIVITY_TYPE_DESCRIPTION VARCHAR (1000) ,
    ACTIVITY_TYPE_CATEGORY    VARCHAR (50) ,
    IS_PAID_FLAG              CHAR (1) ,
    IS_AVAILABLE_FLAG         CHAR (1) ,
    IS_READY_FLAG             CHAR (1) ,
    IS_ABSENCE_FLAG           CHAR (1) ,
    EXTRACT_DT                DATE NOT NULL ,
    LAST_UPDATE_DT            DATE NOT NULL ,
    LAST_UPDATE_BY            VARCHAR (30) NOT NULL ,
    RECORD_EFF_DT             DATE NOT NULL ,
    RECORD_END_DT             DATE NOT NULL ,
  CONSTRAINT CC_C_ACTIVITY_TYPE__UN UNIQUE NONCLUSTERED (ACTIVITY_TYPE_NAME) ON
  "default"
  )
  ON "default"
GO

CREATE
  TABLE CC_C_CONTACT_QUEUE
  (
    C_CONTACT_QUEUE_ID NUMERIC (19) not null primary key  constraint CC_C_CONTACT_QUEUE_PK default next value for SEQ_CC_C_CONTACT_QUEUE ,
    QUEUE_NUMBER       NUMERIC (19) NOT NULL ,
    QUEUE_NAME         VARCHAR (100) ,
    QUEUE_TYPE         VARCHAR (50) ,
    SERVICE_PERCENT    NUMERIC (28) ,
    SERVICE_SECONDS    NUMERIC (28) ,
    INTERVAL_MINUTES   NUMERIC (28) ,
    UNIT_OF_WORK_NAME  VARCHAR (50) NOT NULL ,
    PROJECT_NAME       VARCHAR (50) NOT NULL ,
    PROGRAM_NAME       VARCHAR (50) NOT NULL ,
    REGION_NAME        VARCHAR (50) NOT NULL ,
    STATE_NAME         VARCHAR (50) NOT NULL ,
    PROVINCE_NAME      VARCHAR (50) NOT NULL ,
    DISTRICT_NAME      VARCHAR (50) NOT NULL ,
    COUNTRY_NAME       VARCHAR (50) NOT NULL ,
    RECORD_EFF_DT      DATE NOT NULL DEFAULT '01/01/1900' ,
    RECORD_END_DT DATE NOT NULL DEFAULT '12/31/2999'
	)
  ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_C_CONTACT_QUEUE__IDXv1 ON CC_C_CONTACT_QUEUE
(
  QUEUE_NUMBER ,
  RECORD_EFF_DT DESC
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_C_CONTACT_QUEUE__IDXv2 ON CC_C_CONTACT_QUEUE
(
  QUEUE_NUMBER
)
ON "default"
GO

CREATE
  TABLE CC_C_FILTER
  (
    FILTER_ID   NUMERIC (19) not null primary key  constraint CC_C_FILTER_PK default next value for SEQ_CC_C_FILTER ,
    FILTER_TYPE VARCHAR (40) NOT NULL ,
    VALUE       VARCHAR (50),
  CONSTRAINT CC_C_FILTER__UN UNIQUE NONCLUSTERED (FILTER_TYPE, VALUE) ON
  "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_C_FILTER__IDXv1 ON CC_C_FILTER
(
  FILTER_TYPE
)
ON "default"
GO

CREATE
  TABLE CC_C_LOOKUP
  (
    LOOKUP_ID    NUMERIC (19) not null primary key  constraint CC_C_LOOKUP_PK default next value for SEQ_CC_C_LOOKUP ,
    LOOKUP_TYPE  VARCHAR (40) NOT NULL ,
    LOOKUP_KEY   VARCHAR (50) NOT NULL ,
    LOOKUP_VALUE VARCHAR (50) ,
  CONSTRAINT CC_C_LOOKUP__UN UNIQUE NONCLUSTERED (LOOKUP_TYPE, LOOKUP_KEY) ON
  "default"
  )
  ON "default"
GO

CREATE
  TABLE CC_C_PROJECT_CONFIG
  (
    PROJECT_CONFIG_ID NUMERIC (19) not null primary key  constraint CC_C_PROJECT_CONFIG_PK default next value for SEQ_CC_C_PROJECT_CONFIG ,
    PROJECT_NAME      VARCHAR (50) NOT NULL ,
    PROGRAM_NAME      VARCHAR (50) NOT NULL ,
    REGION_NAME       VARCHAR (50) NOT NULL ,
    STATE_NAME        VARCHAR (50) NOT NULL ,
    PROVINCE_NAME     VARCHAR (50) NOT NULL ,
    DISTRICT_NAME     VARCHAR (50) NOT NULL ,
    COUNTRY_NAME      VARCHAR (50) NOT NULL ,
    RECORD_EFF_DT     DATE NOT NULL DEFAULT '01/01/1900'    ,
    RECORD_END_DT DATE NOT NULL DEFAULT '12/31/2999' ,
  CONSTRAINT CC_S_PROJECT_SITE_CONFIG__UN UNIQUE NONCLUSTERED (PROJECT_NAME,
  PROGRAM_NAME, RECORD_EFF_DT) ON "default"
  )
  ON "default"
GO

CREATE
  TABLE CC_C_UNIT_OF_WORK
  (
    UNIT_OF_WORK_ID       NUMERIC (19) not null primary key  constraint CC_C_UNIT_OF_WORK_PK default next value for SEQ_CC_C_UNIT_OF_WORK ,
    UNIT_OF_WORK_NAME     VARCHAR (50) NOT NULL ,
    UNIT_OF_WORK_CATEGORY VARCHAR (50) ,
    RECORD_EFF_DT         DATE NOT NULL DEFAULT '01/01/1900' ,
    RECORD_END_DT DATE NOT NULL DEFAULT '12/31/2999' ,
  CONSTRAINT CC_C_UNIT_OF_WORK__UN UNIQUE NONCLUSTERED (UNIT_OF_WORK_NAME,
  RECORD_EFF_DT) ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_C_UNIT_OF_WORK__IDX ON CC_C_UNIT_OF_WORK
(
  UNIT_OF_WORK_NAME ,
  RECORD_EFF_DT
)
ON "default"
GO

CREATE
  TABLE CC_L_ERROR
  (
    ID              NUMERIC (19) not null primary key  constraint CC_L_ERROR_PK default next value for SEQ_CC_L_ERROR ,
    MESSAGE         VARCHAR (4000) ,
    ERROR_FILE_PATH VARCHAR (255) ,
    ERROR_DATE      DATE ,
    JOB_NAME        VARCHAR (255) ,
    TRANSFORM_NAME  VARCHAR (255) 
	)
  ON "default"
GO

CREATE
  TABLE CC_L_PATCH_LOG
  (
    PATCH_LOG_ID    NUMERIC (19) not null primary key  constraint CC_L_PATCH_LOG_PK default next value for SEQ_CC_L_PATCH_LOG ,
    PATCH_VERSION   VARCHAR (30) NOT NULL ,
    SCRIPT_SEQUENCE NUMERIC (7) NOT NULL ,
    SCRIPT_NAME     VARCHAR (255) NOT NULL ,
    SCRIPT_RUN_DATE DATE NOT NULL DEFAULT GETDATE() ,
  CONSTRAINT CC_L_PATCH_LOG__UN UNIQUE NONCLUSTERED (PATCH_VERSION, SCRIPT_NAME
  ) ON "default" ,
  CONSTRAINT CC_L_PATCH_LOG__UNv1 UNIQUE NONCLUSTERED (PATCH_VERSION,
  SCRIPT_SEQUENCE) ON "default"
  )
  ON "default"
GO

CREATE
  TABLE CC_L_TRANSFORMATION
  (
    ID_BATCH       NUMERIC (19) NOT NULL ,
    CHANNEL_ID     VARCHAR (255) ,
    TRANSNAME      VARCHAR (255) ,
    STATUS         VARCHAR (15) ,
    LINES_READ     NUMERIC (19) ,
    LINES_WRITTEN  NUMERIC (19) ,
    LINES_UPDATED  NUMERIC (19) ,
    LINES_INPUT    NUMERIC (19) ,
    LINES_OUTPUT   NUMERIC (19) ,
    LINES_REJECTED NUMERIC (19) ,
    ERRORS         NUMERIC (19) ,
    STARTDATE      DATE ,
    ENDDATE        DATE ,
    LOGDATE        DATE ,
    DEPDATE        DATE ,
    REPLAYDATE     DATE ,
    LOG_FIELD      VARCHAR (MAX) ,
    CONSTRAINT CC_L_TRANSFORMATION_PK PRIMARY KEY CLUSTERED (ID_BATCH)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
CC_L_TRANSFORMATION_IDX1 ON CC_L_TRANSFORMATION
(
  ID_BATCH
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_L_TRANSFORMATION_IDX2 ON CC_L_TRANSFORMATION
(
  ERRORS ,
  STATUS ,
  TRANSNAME
)
ON "default"
GO

CREATE
  TABLE CC_S_ACD_AGENT_ACTIVITY
  (
    ACD_AGENT_ACTIVITY_ID   NUMERIC (19) not null primary key  constraint CC_S_ACD_AGENT_ACTIVITY_PK default next value for SEQ_CC_S_ACD_AGENT_ACTIVITY ,
    AGENT_CALLS_DT          DATE NOT NULL ,
    AGENT_ID                NUMERIC (19) NOT NULL ,
    LOGIN_SECONDS           NUMERIC (10,2) NOT NULL DEFAULT 0 ,
    EXTERNAL_SECONDS        NUMERIC (10,2) NOT NULL DEFAULT 0 ,
    INTERNAL_SECONDS        NUMERIC (10,2) NOT NULL DEFAULT 0 ,
    IDLE_SECONDS            NUMERIC (10,2) NOT NULL DEFAULT 0 ,
    NOT_READY_SECONDS       NUMERIC (10,2) NOT NULL DEFAULT 0 ,
    ACD_TALK_SECONDS        NUMERIC (10,2) NOT NULL ,
    HOLD_SECONDS            NUMERIC (10,2) NOT NULL ,
    AFTER_CALL_WORK_SECONDS NUMERIC (10,2) NOT NULL ,
    TALK_RESERVE_SECONDS    NUMERIC (10,2) ,
    RING_SECONDS            NUMERIC (10,2) NOT NULL ,
    PREDICTIVE_TALK_SECONDS NUMERIC (10,2) ,
    PREVIEW_TALK_SECONDS    NUMERIC (10,2) ,
    ACD_CALLS_COUNT         NUMERIC (10) NOT NULL DEFAULT 0 ,
    EXTERNAL_CALLS_COUNT    NUMERIC (10) NOT NULL DEFAULT 0 ,
    INTERNAL_CALLS_COUNT    NUMERIC (10) NOT NULL DEFAULT 0 ,
    PREDICTIVE_CALLS_COUNT  NUMERIC (10) ,
    PREVIEW_CALLS_COUNT     NUMERIC (10) ,
    BREAK_TIME              NUMERIC (10,2) ,
    CONSULTATION_TIME       NUMERIC (10,2) ,
    WALKAWAY_TIME           NUMERIC (10,2) ,
    BUSYONDNTIME            NUMERIC (10,2) ,
    EXTRACT_DT              DATE NOT NULL ,
    LAST_UPDATE_DT          DATE NOT NULL ,
    LAST_UPDATE_BY          VARCHAR (30) NOT NULL ,
  CONSTRAINT CC_S_ACD_AGENT_ACTIVITY_UN UNIQUE NONCLUSTERED (AGENT_CALLS_DT,
  AGENT_ID) ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
CC_S_ACD_AGENT_ACTIVITY_IDX ON CC_S_ACD_AGENT_ACTIVITY
(
  ACD_AGENT_ACTIVITY_ID
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
CC_S_ACD_AGENT_ACTIVITY_IDX2 ON CC_S_ACD_AGENT_ACTIVITY
(
  AGENT_ID ,
  AGENT_CALLS_DT DESC
)
ON "default"
GO

CREATE
  TABLE CC_S_ACD_INTERVAL
  (
    ACD_INTERVAL_ID                NUMERIC (19) not null primary key  constraint CC_S_ACD_INTERVAL_PK default next value for SEQ_CC_S_ACD_INTERVAL ,
    INTERVAL_DATE                  DATE NOT NULL DEFAULT GETDATE() ,
    CONTACT_QUEUE_ID               NUMERIC (19) NOT NULL ,
    INTERVAL_ID                    NUMERIC (19) NOT NULL ,
    AGENT_ID                       NUMERIC (19) NOT NULL ,
    CONTACTS_RECEIVED_FROM_IVR     NUMERIC (7) NOT NULL DEFAULT 0 ,
    CONTACTS_OFFERED               NUMERIC (7) NOT NULL DEFAULT 0 ,
    CONTACTS_HANDLED               NUMERIC (7) NOT NULL DEFAULT 0 ,
    CONTACTS_ABANDONED             NUMERIC (7) NOT NULL DEFAULT 0 ,
    MIN_HANDLE_TIME                NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    MAX_HANDLE_TIME                NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    MEAN_HANDLE_TIME               NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    MEDIAN_HANDLE_TIME             NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    STDDEV_HANDLE_TIME             NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    MIN_SPEED_TO_HANDLE            NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    MAX_SPEED_TO_HANDLE            NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    MEAN_SPEED_TO_HANDLE           NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    MEDIAN_SPEED_TO_HANDLE         NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    STDDEV_SPEED_TO_HANDLE         NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    MIN_SPEED_OF_ANSWER            NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    MAX_SPEED_OF_ANSWER            NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    MEAN_SPEED_OF_ANSWER           NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    MEDIAN_SPEED_OF_ANSWER         NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    STDDEV_SPEED_OF_ANSWER         NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    SPEED_OF_ANSWER_PERIOD_1       NUMERIC (7) NOT NULL DEFAULT 0 ,
    SPEED_OF_ANSWER_PERIOD_2       NUMERIC (7) NOT NULL DEFAULT 0 ,
    SPEED_OF_ANSWER_PERIOD_3       NUMERIC (7) NOT NULL DEFAULT 0 ,
    SPEED_OF_ANSWER_PERIOD_4       NUMERIC (7) NOT NULL DEFAULT 0 ,
    SPEED_OF_ANSWER_PERIOD_5       NUMERIC (7) NOT NULL DEFAULT 0 ,
    SPEED_OF_ANSWER_PERIOD_6       NUMERIC (7) NOT NULL DEFAULT 0 ,
    SPEED_OF_ANSWER_PERIOD_7       NUMERIC (7) NOT NULL DEFAULT 0 ,
    SPEED_OF_ANSWER_PERIOD_8       NUMERIC (7) NOT NULL DEFAULT 0 ,
    SPEED_OF_ANSWER_PERIOD_9       NUMERIC (7) NOT NULL DEFAULT 0 ,
    SPEED_OF_ANSWER_PERIOD_10      NUMERIC (7) NOT NULL DEFAULT 0 ,
    CALLS_ABANDONED_PERIOD_1       NUMERIC (7) NOT NULL DEFAULT 0 ,
    CALLS_ABANDONED_PERIOD_2       NUMERIC (7) NOT NULL DEFAULT 0 ,
    CALLS_ABANDONED_PERIOD_3       NUMERIC (7) NOT NULL DEFAULT 0 ,
    CALLS_ABANDONED_PERIOD_4       NUMERIC (7) NOT NULL DEFAULT 0 ,
    CALLS_ABANDONED_PERIOD_5       NUMERIC (7) NOT NULL DEFAULT 0 ,
    CALLS_ABANDONED_PERIOD_6       NUMERIC (7) NOT NULL DEFAULT 0 ,
    CALLS_ABANDONED_PERIOD_7       NUMERIC (7) NOT NULL DEFAULT 0 ,
    CALLS_ABANDONED_PERIOD_8       NUMERIC (7) NOT NULL DEFAULT 0 ,
    CALLS_ABANDONED_PERIOD_9       NUMERIC (7) NOT NULL DEFAULT 0 ,
    CALLS_ABANDONED_PERIOD_10      NUMERIC (7) NOT NULL DEFAULT 0 ,
    LABOR_MINUTES_TOTAL            NUMERIC (10,2) NOT NULL DEFAULT 0 ,
    LABOR_MINUTES_WAITING          NUMERIC (10,2) NOT NULL DEFAULT 0 ,
    HEADCOUNT_AVAILABLE            NUMERIC (7,2) NOT NULL DEFAULT 0 ,
    CONTACT_INVENTORY              NUMERIC (7) NOT NULL DEFAULT 0 ,
    CONTACT_INVENTORY_JEOPARDY     NUMERIC (7) NOT NULL DEFAULT 0 ,
    CONTACT_INVENTORY_AGE_TOTAL    NUMERIC (5,2) NOT NULL DEFAULT 0 ,
    MIN_CONTACT_INVENTORY_AGE      NUMERIC (5,2) NOT NULL DEFAULT 0 ,
    MAX_CONTACT_INVENTORY_AGE      NUMERIC (5,2) NOT NULL DEFAULT 0 ,
    MEAN_CONTACT_INVENTORY_AGE     NUMERIC (5,2) NOT NULL DEFAULT 0 ,
    MEDIAN_CONTACT_INVENTORY_AGE   NUMERIC (5,2) NOT NULL DEFAULT 0 ,
    STDDEV_CONTACT_INVENTORY_AGE   NUMERIC (5,2) NOT NULL DEFAULT 0 ,
    CONTACTS_TRANSFERRED           NUMERIC (7) NOT NULL DEFAULT 0 ,
    OUTFLOW_CONTACTS               NUMERIC (7) NOT NULL DEFAULT 0 ,
    ANSWER_WAIT_TIME_TOTAL         NUMERIC (12,2) NOT NULL DEFAULT 0 ,
    ABANDON_TIME_TOTAL             NUMERIC (12,2) NOT NULL DEFAULT 0 ,
    TALK_TIME_TOTAL                NUMERIC (12,2) NOT NULL DEFAULT 0 ,
    AFTER_CALL_WORK_TIME_TOTAL     NUMERIC (12,2) NOT NULL DEFAULT 0 ,
    SERVICE_LEVEL_ANSWERED_PERCENT NUMERIC (5,2) NOT NULL DEFAULT 0 ,
    SERVICE_LEVEL_ANSWERED_COUNT   NUMERIC (7) NOT NULL DEFAULT 0 ,
    SERVICE_LEVEL_ABANDONED        NUMERIC (5,2) DEFAULT 0 ,
    CALLS_ON_HOLD                  NUMERIC (7) NOT NULL DEFAULT 0 ,
    HOLD_TIME_TOTAL                NUMERIC (12,2) NOT NULL DEFAULT 0 ,
    IVR_TIME_TOTAL                 NUMERIC (12,2) DEFAULT 0 ,
    SHORT_ABANDONS                 NUMERIC (7) NOT NULL DEFAULT 0 ,
    CONTACTS_BLOCKED               NUMERIC (7) NOT NULL DEFAULT 0 ,
    ICR_DEFAULT_ROUTED             NUMERIC (7) NOT NULL DEFAULT 0 ,
    NETWORK_DEFAULT_ROUTED         NUMERIC (7) NOT NULL DEFAULT 0 ,
    RETURN_BUSY                    NUMERIC (7) NOT NULL DEFAULT 0 ,
    CALLS_RONA                     NUMERIC (7) NOT NULL DEFAULT 0 ,
    RETURN_RELEASE                 NUMERIC (7) NOT NULL DEFAULT 0 ,
    CALLS_ROUTED_NON_AGENT         NUMERIC (7) NOT NULL DEFAULT 0 ,
    ERROR_COUNT                    NUMERIC (7) NOT NULL DEFAULT 0 ,
    AGENT_ERROR_COUNT              NUMERIC (7) NOT NULL DEFAULT 0 ,
    RETURN_RING                    NUMERIC (7) NOT NULL DEFAULT 0 ,
    INCOMPLETE_CALLS               NUMERIC (7) NOT NULL DEFAULT 0 ,
    CALLS_GIVEN_FORCE_DISCONNECT   NUMERIC (7) NOT NULL DEFAULT 0 ,
    CALLS_GIVEN_ROUTE_TO           NUMERIC (7) NOT NULL DEFAULT 0 ,
    CALL_TYPE                      VARCHAR (200) ,
    EXTRACT_DT                     DATE NOT NULL DEFAULT GETDATE() ,
    LAST_UPDATE_DT                 DATE NOT NULL DEFAULT GETDATE() ,
    LAST_UPDATE_BY                 VARCHAR (30) NOT NULL ,
  CONSTRAINT CC_S_ACD_INTERVAL__UN UNIQUE NONCLUSTERED (INTERVAL_DATE,
  CONTACT_QUEUE_ID, INTERVAL_ID, AGENT_ID) ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_ACD_INT_CC_S_CNTCT_Q_FK ON CC_S_ACD_INTERVAL
(
  CONTACT_QUEUE_ID
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_ACD_INT_CC_S_INTERVAL_FK ON CC_S_ACD_INTERVAL
(
  ACD_INTERVAL_ID
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_ACD_INT_CC_S_AGENT_FK ON CC_S_ACD_INTERVAL
(
  AGENT_ID
)
ON "default"
GO

CREATE
  TABLE CC_S_ACD_INTERVAL_PERIOD
  (
    ACD_INTERVAL_PERIOD_ID NUMERIC (19) not null primary key  constraint CC_S_ACD_INTERVAL_PERIOD_PK default next value for SEQ_CC_S_ACD_INTERVAL_PERIOD ,
    PERIOD_TYPE            VARCHAR (50) NOT NULL ,
    PERIOD_1_UPPER_BOUND   NUMERIC (5) NOT NULL DEFAULT 0 ,
    PERIOD_2_UPPER_BOUND   NUMERIC (5) NOT NULL DEFAULT 0 ,
    PERIOD_3_UPPER_BOUND   NUMERIC (5) NOT NULL DEFAULT 0 ,
    PERIOD_4_UPPER_BOUND   NUMERIC (5) NOT NULL DEFAULT 0 ,
    PERIOD_5_UPPER_BOUND   NUMERIC (5) NOT NULL DEFAULT 0 ,
    PERIOD_6_UPPER_BOUND   NUMERIC (5) NOT NULL DEFAULT 0 ,
    PERIOD_7_UPPER_BOUND   NUMERIC (5) NOT NULL DEFAULT 0 ,
    PERIOD_8_UPPER_BOUND   NUMERIC (5) NOT NULL DEFAULT 0 ,
    PERIOD_9_UPPER_BOUND   NUMERIC (5) NOT NULL DEFAULT 0 ,
    PERIOD_10_UPPER_BOUND  NUMERIC (5) NOT NULL DEFAULT 0 ,
    EXTRACT_DT             DATE NOT NULL ,
    RECORD_EFF_DT          DATE NOT NULL DEFAULT '01/01/1900' ,
    RECORD_END_DT DATE NOT NULL DEFAULT '12/31/2999' ,
  CONSTRAINT CC_S_INTERVAL_PERIOD__UN UNIQUE NONCLUSTERED (PERIOD_TYPE,
  RECORD_EFF_DT, PERIOD_1_UPPER_BOUND, PERIOD_2_UPPER_BOUND,
  PERIOD_3_UPPER_BOUND, PERIOD_4_UPPER_BOUND, PERIOD_5_UPPER_BOUND,
  PERIOD_6_UPPER_BOUND, PERIOD_7_UPPER_BOUND, PERIOD_8_UPPER_BOUND,
  PERIOD_9_UPPER_BOUND, PERIOD_10_UPPER_BOUND) ON "default"
  )
  ON "default"
GO
ALTER TABLE CC_S_ACD_INTERVAL_PERIOD
ADD
CHECK ( PERIOD_TYPE IN ('CALLS_ABANDONED', 'SPEED_OF_ANSWER') )
GO

CREATE
  TABLE CC_S_AGENT
  (
    AGENT_ID NUMERIC (19) not null primary key  constraint ST_AGENT_PK default next value for SEQ_CC_S_AGENT ,
    LOGIN_ID NVARCHAR (100) NOT NULL ,
    PROJECT_CONFIG_ID NUMERIC (19) NOT NULL ,
    FIRST_NAME        VARCHAR (50) NOT NULL ,
    LAST_NAME         VARCHAR (50) NOT NULL ,
    MIDDLE_INITIAL    VARCHAR (20) ,
    JOB_TITLE         VARCHAR (50) NOT NULL ,
    LANGUAGE          VARCHAR (50) NOT NULL ,
    SITE_NAME         VARCHAR (50) NOT NULL ,
    SITE_DESCRIPTION  VARCHAR (200) NOT NULL ,
    HOURLY_RATE       DECIMAL (5,2) NOT NULL DEFAULT 0 ,
    RATE_CURRENCY     VARCHAR (3) NOT NULL ,
    AGENT_GROUP       VARCHAR (50) NOT NULL ,
    EXTRACT_DT        DATE NOT NULL ,
    HIRE_DATE         DATE ,
    TERMINATION_DATE  DATE ,
    LAST_UPDATE_DT    DATE NOT NULL ,
    LAST_UPDATE_BY    VARCHAR (30) NOT NULL ,
    RECORD_EFF_DT     DATE ,
    RECORD_END_DT     DATE ,
  CONSTRAINT CC_S_AGENT_UN UNIQUE NONCLUSTERED (LOGIN_ID, RECORD_EFF_DT) ON
  "default"
  )
  ON "default"
GO
ALTER TABLE CC_S_AGENT
ADD CONSTRAINT CC_S_AGENT_REC_DATE_CK
CHECK ( RECORD_EFF_DT <= RECORD_END_DT )
GO
CREATE UNIQUE NONCLUSTERED INDEX
CC_S_AGENT__IDX ON CC_S_AGENT
(
AGENT_ID
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
CC_S_AGENT__IDX2 ON CC_S_AGENT
(
LOGIN_ID ,
RECORD_EFF_DT DESC
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_AGENT__IDXv4 ON CC_S_AGENT
(
PROJECT_CONFIG_ID
)
ON "default"
GO

CREATE
  TABLE CC_S_AGENT_ABSENCE
  (
    AGENT_ABSENCE_ID   NUMERIC (19) not null primary key  constraint ST_AGENT_ABSENCES_PK default next value for SEQ_CC_S_AGENT_ABSENCE ,
    ABSENCE_DATE       DATE NOT NULL ,
    AGENT_ID           NUMERIC (19) NOT NULL ,
    ACTIVITY_TYPE_ID   NUMERIC (19) NOT NULL ,
    ABSENCE_MINUTES    NUMERIC (6,2) NOT NULL DEFAULT 0 ,
    ABSENCE_START_TIME DATE NOT NULL ,
    ABSENCE_END_TIME   DATE NOT NULL ,
    IS_PLANNED_FLAG BIT NOT NULL ,
    EXTRACT_DT     DATE NOT NULL ,
    LAST_UPDATE_DT DATE NOT NULL ,
    LAST_UPDATE_BY VARCHAR (30) NOT NULL ,
  CONSTRAINT CC_S_AGENT_ABSENCES__UN UNIQUE NONCLUSTERED (AGENT_ID,
  ABSENCE_END_TIME) ON "default"
  )
  ON "default"
GO
ALTER TABLE CC_S_AGENT_ABSENCE
ADD CONSTRAINT CC_S_AGENT_ABSENCE_CK
CHECK ( ABSENCE_START_TIME <= ABSENCE_END_TIME )
GO
CREATE UNIQUE NONCLUSTERED INDEX
CC_S_AGENT_ABSENCE__IDX ON CC_S_AGENT_ABSENCE
(
AGENT_ABSENCE_ID
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
CC_S_AGENT_ABSENCE__IDX2 ON CC_S_AGENT_ABSENCE
(
AGENT_ID ,
ABSENCE_END_TIME DESC
)
ON "default"
GO

CREATE
  TABLE CC_S_AGENT_SUPERVISOR
  (
    AGENT_SUPERVISOR_ID NUMERIC (19) not null primary key  constraint ST_AGENT_SUPERVISOR_PK default next value for SEQ_CC_S_AGENT_SUPERVISOR ,
    AGENT_ID            NUMERIC (19) NOT NULL ,
    SUPERVISOR_AGENT_ID NUMERIC (19) NOT NULL ,
    EXTRACT_DT          DATE NOT NULL ,
    RECORD_EFF_DT       DATE NOT NULL ,
    RECORD_END_DT       DATE NOT NULL ,
  CONSTRAINT CC_S_AGENT_SUPERVISOR_UN UNIQUE NONCLUSTERED (AGENT_ID,
  SUPERVISOR_AGENT_ID, RECORD_EFF_DT) ON "default"
  )
  ON "default"
GO
ALTER TABLE CC_S_AGENT_SUPERVISOR
ADD CONSTRAINT CC_S_AGENT_SPRVSR_REC_DT_CK
CHECK ( RECORD_EFF_DT <= RECORD_END_DT )
GO
CREATE UNIQUE NONCLUSTERED INDEX
CC_S_AGENT_SUPERVISOR__IDX ON CC_S_AGENT_SUPERVISOR
(
AGENT_SUPERVISOR_ID
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
CC_S_AGENT_SUPERVISOR__IDX2 ON CC_S_AGENT_SUPERVISOR
(
AGENT_ID ,
SUPERVISOR_AGENT_ID ,
RECORD_EFF_DT DESC
)
ON "default"
GO

CREATE
  TABLE CC_S_AGENT_WORK_DAY
  (
    AGENT_WORK_DAY_ID       NUMERIC (19) not null primary key  constraint CC_S_AGENT_WORK_DAY_PK default next value for SEQ_CC_S_AGENT_WORK_DAY ,
    AGENT_ID                NUMERIC (19) NOT NULL ,
    WORK_DATE               DATE NOT NULL ,
    FIRST_LOGIN             DATE NOT NULL ,
    LAST_LOGOUT             DATE NOT NULL ,
    SCHEDULED_SHIFT_MINUTES NUMERIC (6,2) DEFAULT 0 ,
    ACTUAL_SHIFT_MINUTES    NUMERIC (6,2) NOT NULL DEFAULT 0 ,
    ACTUAL_OVERTIME_MINUTES NUMERIC (6,2) NOT NULL DEFAULT 0 ,
    EXTRACT_DT              DATE NOT NULL ,
    LAST_UPDATE_DT          DATE NOT NULL ,
    LAST_UPDATE_BY          VARCHAR (30) NOT NULL ,
  CONSTRAINT CC_S_AGENT_WORK_DAY__UN UNIQUE NONCLUSTERED (AGENT_ID, WORK_DATE)
  ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_AGENT_WORK_DAY__IDXv2 ON CC_S_AGENT_WORK_DAY
(
  AGENT_ID
)
ON "default"
GO

CREATE
  TABLE CC_S_CALL_DETAIL
  (
    CALL_DETAIL_ID          NUMERIC (19) not null primary key  constraint ST_CALL_DETAIL_PK default next value for SEQ_CC_S_CALL_DETAIL ,
    CALL_SEGMENT_ID         VARCHAR (50) ,
    CALL_DATE               DATE NOT NULL ,
    CALL_TYPE               VARCHAR (200) ,
    SOURCE_CALL_ID          VARCHAR (40) ,
    AGENT_ID                NUMERIC (19) NOT NULL ,
    DNIS                    VARCHAR (30) ,
    DISPOSITION             VARCHAR (200) ,
    TRANSFER_TO             VARCHAR (200) ,
    CALL_SEGMENT_END_DT     DATE NOT NULL ,
    QUEUE_NAME              VARCHAR (50) NOT NULL ,
    LANGUAGE                VARCHAR (50) NOT NULL ,
    ANI_PHONE_NUMBER        VARCHAR (200) NOT NULL ,
    QUEUE_TIME_SECONDS      NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    RING_TIME_SECONDS       NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    HOLD_TIME_SECONDS       NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    AFTER_CALL_WORK_SECONDS NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    TALK_TIME_SECONDS       NUMERIC (11,2) NOT NULL DEFAULT 0 ,
    IVR_TIME_SECONDS        NUMERIC (11,2) ,
    XFERRED_OUT_FLAG BIT NOT NULL ,
    VOICEMAIL_FLAG      VARCHAR (1) ,
    CALL_ABANDONED_FLAG NUMERIC (1) ,
    EXTRACT_DT          DATE NOT NULL DEFAULT GETDATE() ,
    LAST_UPDATE_DT      DATE NOT NULL DEFAULT GETDATE() ,
    LAST_UPDATE_BY      VARCHAR (30) NOT NULL ,
  CONSTRAINT CC_S_CALL_DETAIL__UN UNIQUE NONCLUSTERED (SOURCE_CALL_ID,
  CALL_SEGMENT_ID) ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_CALL_DETAIL_AGENT_IDX ON CC_S_CALL_DETAIL
(
  AGENT_ID
)
ON "default"
GO

CREATE
  TABLE CC_S_CONTACT_QUEUE
  (
    CONTACT_QUEUE_ID               NUMERIC (19) not null primary key  constraint CC_S_CONTACT_QUEUE_PK default next value for SEQ_CC_S_CONTACT_QUEUE ,
    QUEUE_NUMBER                   NUMERIC (19) NOT NULL ,
    PROJECT_CONFIG_ID              NUMERIC (19) NOT NULL ,
    QUEUE_NAME                     VARCHAR (50) NOT NULL ,
    SOURCE_QUEUE                   NUMERIC (19) NOT NULL ,
    QUEUE_TYPE                     VARCHAR (50) NOT NULL ,
    SERVICE_PERCENT                NUMERIC (3) NOT NULL DEFAULT 0 ,
    SERVICE_SECONDS                NUMERIC (5) NOT NULL DEFAULT 0 ,
    QUEUE_GROUP                    NUMERIC (4) NOT NULL ,
    INTERVAL_MINUTES               NUMERIC (2) NOT NULL ,
    AVG_SPEED_ANSR_INTRVL_PRIOD_ID NUMERIC (19) NOT NULL ,
    CALLS_ABANDOND_INTRVL_PRIOD_ID NUMERIC (19) NOT NULL ,
    UNIT_OF_WORK_ID                NUMERIC (19) NOT NULL ,
    RECORD_EFF_DT                  DATE NOT NULL DEFAULT '01/01/1900' ,
    RECORD_END_DT DATE NOT NULL DEFAULT '12/31/2999' ,
  CONSTRAINT CC_S_CONTACT_QUEUE__UN UNIQUE NONCLUSTERED (QUEUE_NUMBER,
  RECORD_EFF_DT) ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_CONTACT_QUEUE__IDXv2 ON CC_S_CONTACT_QUEUE
(
  PROJECT_CONFIG_ID
)
ON "default"
GO

CREATE
  TABLE CC_S_FCST_INTERVAL
  (
    FCST_INTERVAL_ID              NUMERIC (19) not null primary key  constraint CC_S_FCST_INTERVAL_PK default next value for SEQ_CC_S_FCST_INTERVAL ,
    PRODUCTION_PLAN_HORIZON_ID    NUMERIC (19) NOT NULL ,
    UNIT_OF_WORK_ID               NUMERIC (19) NOT NULL ,
    INTERVAL_DATE                 DATE NOT NULL ,
    INTERVAL_ID                   NUMERIC (19) NOT NULL ,
    FORECAST_VERSION              NUMERIC (5) NOT NULL DEFAULT 0 ,
    CONTACTS_CREATED              NUMERIC (7) DEFAULT 0 ,
    CONTACTS_OFFERED              NUMERIC (7) DEFAULT 0 ,
    CONTACTS_HANDLED              NUMERIC (7) DEFAULT 0 ,
    MIN_SPEED_TO_HANDLE           NUMERIC (7,2) DEFAULT 0 ,
    MAX_SPEED_TO_HANDLE           NUMERIC (7,2) DEFAULT 0 ,
    MEAN_SPEED_TO_HANDLE          NUMERIC (7,2) DEFAULT 0 ,
    MEDIAN_SPEED_TO_HANDLE        NUMERIC (7,2) DEFAULT 0 ,
    STDDEV_SPEED_TO_HANDLE        NUMERIC (7,2) DEFAULT 0 ,
    MIN_SPEED_OF_ANSWER           NUMERIC (7,2) DEFAULT 0 ,
    MAX_SPEED_OF_ANSWER           NUMERIC (7,2) DEFAULT 0 ,
    MEAN_SPEED_OF_ANSWER          NUMERIC (7,2) DEFAULT 0 ,
    MEDIAN_SPEED_OF_ANSWER        NUMERIC (7,2) DEFAULT 0 ,
    STDDEV_SPEED_OF_ANSWER        NUMERIC (7,2) DEFAULT 0 ,
    CONTACTS_ABANDONED            NUMERIC (7) DEFAULT 0 ,
    CONTACT_INVENTORY             NUMERIC (7) DEFAULT 0 ,
    MIN_CONTACT_INVENTORY_AGE     NUMERIC (5,2) DEFAULT 0 ,
    MAX_CONTACT_INVENTORY_AGE     NUMERIC (5,2) DEFAULT 0 ,
    MEAN_CONTACT_INVENTORY_AGE    NUMERIC (5,2) DEFAULT 0 ,
    MEDIAN_CONTACT_INVENTORY_AGE  NUMERIC (5,2) DEFAULT 0 ,
    STDDEV_CONTACT_INVENTORY_AGE  NUMERIC (5,2) DEFAULT 0 ,
    MIN_HANDLE_TIME               NUMERIC (7,2) DEFAULT 0 ,
    MAX_HANDLE_TIME               NUMERIC (7,2) DEFAULT 0 ,
    MEAN_HANDLE_TIME              NUMERIC (7,2) DEFAULT 0 ,
    MEDIAN_HANDLE_TIME            NUMERIC (7,2) DEFAULT 0 ,
    CONTACT_INVENTORY_JEOPARDY    NUMERIC (7) DEFAULT 0 ,
    STDDEV_HANDLE_TIME            NUMERIC (7,2) DEFAULT 0 ,
    LABOR_MINUTES_TOTAL           NUMERIC (10,2) DEFAULT 0 ,
    LABOR_MINUTES_AVAILABLE       NUMERIC (9,2) DEFAULT 0 ,
    LABOR_MINUTES_WAITING         NUMERIC (10,2) DEFAULT 0 ,
    HEADCOUNT_TOTAL               NUMERIC (7,2) DEFAULT 0 ,
    HEADCOUNT_AVAILABLE           NUMERIC (7,2) DEFAULT 0 ,
    HEADCOUNT_UNAVAILABLE         NUMERIC (7,2) DEFAULT 0 ,
    SRVC_LEVEL_ANSWERED_PERCENT   NUMERIC (5,2) DEFAULT 0 ,
    SRVC_LEVEL_ANSWERED_PERCENT_2 NUMERIC (5,2) DEFAULT 0 ,
    EXTRACT_DT                    DATE NOT NULL DEFAULT GETDATE() ,
    LAST_UPDATE_DT                DATE NOT NULL DEFAULT GETDATE() ,
    LAST_UPDATE_BY                VARCHAR (30) NOT NULL ,
  CONSTRAINT CC_S_FCST_INTERVAL__UN UNIQUE NONCLUSTERED (
  PRODUCTION_PLAN_HORIZON_ID, INTERVAL_DATE, UNIT_OF_WORK_ID, INTERVAL_ID,
  FORECAST_VERSION) ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_FCST_INTERVAL__IDXv2 ON CC_S_FCST_INTERVAL
(
  UNIT_OF_WORK_ID
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_FCST_INTERVAL__IDXv3 ON CC_S_FCST_INTERVAL
(
  INTERVAL_ID
)
ON "default"
GO

CREATE
  TABLE CC_S_INTERVAL
  (
    INTERVAL_ID         NUMERIC (19) not null primary key  constraint CC_S_INTERVAL_PK default next value for SEQ_CC_S_INTERVAL ,
    INTERVAL_START_DATE DATE NOT NULL ,
    INTERVAL_END_DATE   DATE NOT NULL ,
    INTERVAL_SECONDS    NUMERIC (4) NOT NULL DEFAULT 1800 ,
    RECORD_EFF_DT       DATE NOT NULL DEFAULT '01/01/1900' ,
    RECORD_END_DT DATE NOT NULL DEFAULT '12/31/2999' ,
  CONSTRAINT CC_S_INTERVAL__UN UNIQUE NONCLUSTERED (INTERVAL_START_DATE,
  INTERVAL_END_DATE) ON "default"
  )
  ON "default"
GO
ALTER TABLE CC_S_INTERVAL
ADD
CHECK ( INTERVAL_SECONDS IN (900, 1800, 3600) )
GO
CREATE NONCLUSTERED INDEX
CC_S_INTERVAL__IDX1 ON CC_S_INTERVAL
(
INTERVAL_START_DATE
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_INTERVAL__IDX2 ON CC_S_INTERVAL
(
INTERVAL_END_DATE
)
ON "default"
GO

CREATE
  TABLE CC_S_IVR_INTERVAL
  (
    IVR_INTERVAL_ID           NUMERIC (19) not null primary key  constraint CC_S_IVR_INTERVAL_PK default next value for SEQ_CC_S_IVR_INTERVAL ,
    PROJECT_CONFIG_ID         NUMERIC (19) NOT NULL ,
    INTERVAL_DATE             DATE NOT NULL ,
    INTERVAL_ID               NUMERIC (19) NOT NULL ,
    CONTACTS_CREATED          NUMERIC (7) NOT NULL DEFAULT 0 ,
    CONTACTS_OFFERED_TO_ACD   NUMERIC (7) NOT NULL DEFAULT 0 ,
    CONTACTS_CONTAINED_IN_IVR NUMERIC (7) NOT NULL DEFAULT 0 ,
    MIN_TIME_IN_THE_IVR       NUMERIC (7,2) NOT NULL DEFAULT 0 ,
    MAX_TIME_IN_THE_IVR       NUMERIC (7,2) NOT NULL DEFAULT 0 ,
    MEAN_TIME_IN_THE_IVR      NUMERIC (7,2) NOT NULL DEFAULT 0 ,
    MEDIAN_TIME_IN_THE_IVR    NUMERIC (7,2) NOT NULL DEFAULT 0 ,
    STDDEV_TIME_IN_THE_IVR    NUMERIC (7,2) NOT NULL DEFAULT 0 ,
    EXTRACT_DT                DATE NOT NULL ,
    LAST_UPDATE_DT            DATE NOT NULL ,
    LAST_UPDATE_BY            VARCHAR (30) NOT NULL ,
  CONSTRAINT CC_S_IVR_INTERVAL__UN UNIQUE NONCLUSTERED (INTERVAL_DATE,
  INTERVAL_ID, PROJECT_CONFIG_ID) ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_IVR_INTERVAL__IDXv2 ON CC_S_IVR_INTERVAL
(
  INTERVAL_ID
)
ON "default"
GO

CREATE
  TABLE CC_S_IVR_SELF_SERVICE_PATH
  (
    IVR_SELF_SERVICE_PATH_ID NUMERIC (19) NOT NULL ,
    CODE                     VARCHAR (30) ,
    DESCRIPTION              VARCHAR (255) ,
    BEGIN_NODE               VARCHAR (30) NOT NULL ,
    END_NODE                 VARCHAR (30) NOT NULL ,
    RECORD_EFF_DT            DATE NOT NULL ,
    RECORD_END_DT            DATE NOT NULL ,
    CONSTRAINT CC_S_SELF_SERVICE_PATH_PK PRIMARY KEY CLUSTERED (
    IVR_SELF_SERVICE_PATH_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default" ,
  CONSTRAINT CC_S_SELF_SERVICE_PATH__UN UNIQUE NONCLUSTERED (BEGIN_NODE,
  END_NODE, RECORD_EFF_DT) ON "default"
  )
  ON "default"
GO

CREATE
  TABLE CC_S_IVR_SELF_SERVICE_USAGE
  (
    IVR_SELF_SERVICE_USAGE_ID  NUMERIC (19) NOT NULL ,
    PROJECT_CONFIG_ID          NUMERIC (19) NOT NULL ,
    INTERVAL_ID                NUMERIC (19) NOT NULL ,
    IVR_SELF_SERVICE_PATH_ID   NUMERIC (19) NOT NULL ,
    CONTACTS_ENTERING          NUMERIC (10) NOT NULL DEFAULT 0 ,
    CONTACTS_TRANSFERRED       NUMERIC (10) NOT NULL ,
    CONTACTS_COMPLETED         NUMERIC (10) NOT NULL ,
    MINUTES_IN_IVR_TRANSFERRED NUMERIC (12,2) NOT NULL ,
    MINUTES_IN_IVR_COMPLETED   NUMERIC (12,2) NOT NULL ,
    CONSTRAINT CC_S_IVR_SELF_SERVICE_USAGE_PK PRIMARY KEY CLUSTERED (
    IVR_SELF_SERVICE_USAGE_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default" ,
  CONSTRAINT CC_S_IVR_SELF_SVC_USAGE__UN UNIQUE NONCLUSTERED (INTERVAL_ID,
  IVR_SELF_SERVICE_PATH_ID, PROJECT_CONFIG_ID) ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_IVR_SELF_SVC_USAGE__IDXv1 ON CC_S_IVR_SELF_SERVICE_USAGE
(
  INTERVAL_ID
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_IVR_SELF_SVC_USAGE__IDXv2 ON CC_S_IVR_SELF_SERVICE_USAGE
(
  IVR_SELF_SERVICE_PATH_ID
)
ON "default"
GO

CREATE
  TABLE CC_S_PRODUCTION_PLAN
  (
    PRODUCTION_PLAN_ID          NUMERIC (19) not null primary key  constraint CC_C_PRODUCTION_PLAN_PK default next value for SEQ_CC_S_PRODUCTION_PLAN ,
    PRODUCTION_PLAN_NAME        VARCHAR (50) NOT NULL ,
    PRODUCTION_PLAN_DESCRIPTION VARCHAR (1000) ,
    PROGRAM_NAME                VARCHAR (50) NOT NULL ,
    PROJECT_NAME                VARCHAR (50) NOT NULL ,
    GEOGRAPHY_NAME              VARCHAR (50) NOT NULL ,
    EFFECTIVE_DATE              DATE NOT NULL DEFAULT GETDATE() ,
    LAST_UPDATE_DATE            DATE NOT NULL DEFAULT GETDATE() ,
    EXTRACT_DT                  DATE NOT NULL ,
    RECORD_EFF_DT               DATE NOT NULL ,
    RECORD_END_DT               DATE NOT NULL ,
  CONSTRAINT CC_S_PRODUCTION_PLAN__UN UNIQUE NONCLUSTERED (PRODUCTION_PLAN_NAME
  , RECORD_EFF_DT) ON "default"
  )
  ON "default"
GO

CREATE
  TABLE CC_S_PRODUCTION_PLAN_HORIZON
  (
    PRODUCTION_PLAN_HORIZON_ID NUMERIC (19) not null primary key  constraint CC_C_HORIZON_PK default next value for SEQ_CC_S_PP_HORIZON ,
    PRODUCTION_PLAN_ID         NUMERIC (19) NOT NULL ,
    HORIZON_START_DATE         DATE DEFAULT GETDATE() ,
    HORIZON_START_HOUR         NUMERIC (2) DEFAULT datepart(hh,getdate()) ,
    HORIZON_END_DATE           DATE DEFAULT GETDATE() ,
    HORIZON_END_HOUR           NUMERIC (2) DEFAULT datepart(hh,getdate()),
    HORIZON_NAME               VARCHAR (50) ,
    HORIZON_DESCRIPTION        VARCHAR (1000) ,
    INITIAL_VERSION            NUMERIC (4) NOT NULL ,
    FINAL_VERSION              NUMERIC (4) NOT NULL ,
    CREATE_DATE                DATE DEFAULT GETDATE() ,
    LAST_UPDATE_DATE           DATE DEFAULT GETDATE() ,
  CONSTRAINT CC_C_HORIZON__UN UNIQUE NONCLUSTERED (PRODUCTION_PLAN_ID,
  HORIZON_START_DATE, HORIZON_START_HOUR, HORIZON_END_DATE, HORIZON_END_HOUR)
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE CC_S_TIMEZONEAM
  (
    ID        NUMERIC (19) NOT NULL ,
    TIMEZONE  VARCHAR (50) ,
    STARTTIME DATE ,
    ENDTIME   DATE ,
    BIAS      NUMERIC (28) ,
    CONSTRAINT CC_S_TIMEZONEAM_PK PRIMARY KEY CLUSTERED (ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE CC_S_TMP_ACTUALEVENTTIMELINE
  (
    EMPLOYEEID           NUMERIC (28) NOT NULL ,
    STARTTIME            DATE NOT NULL ,
    ENDTIME              DATE NOT NULL ,
    LOGINID              NUMERIC (28) NOT NULL ,
    ACTIVITYID           NUMERIC (28) ,
    ACTIVITYCATEGORYNAME VARCHAR (50) ,
    ACTIVITYNAME         VARCHAR (50) ,
    TIMEENTRYEVENTID     NUMERIC (28) ,
    ISPAID               VARCHAR (20) ,
    ORGANIZATIONID       NUMERIC (28) ,
    ORGANIZATIONNAME     VARCHAR (250) ,
    TIMEZONE             VARCHAR (30) ,
    LOCAL_STARTTIME      DATE ,
    LOCAL_ENDTIME        DATE ,
    CONSTRAINT CC_S_TMP_ACTUALEVENTTIMELIN_PK PRIMARY KEY CLUSTERED (LOGINID,
    STARTTIME, ENDTIME)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_TMP_AET__IDX1 ON CC_S_TMP_ACTUALEVENTTIMELINE
(
  LOCAL_STARTTIME
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_TMP_AET__IDX2 ON CC_S_TMP_ACTUALEVENTTIMELINE
(
  LOCAL_ENDTIME
)
ON "default"
GO

CREATE
  TABLE CC_S_TMP_AGENT_SKILL_GROUP
  (
    SKILLTARGETID           NUMERIC (28) ,
    PERIPHERALNUMBER        NUMERIC (28) ,
    SKILLGROUPSKILLTARGETID NUMERIC (28) ,
    FIRSTNAME               VARCHAR (50) ,
    LASTNAME                VARCHAR (50)
  )
  ON "default"
GO

CREATE
  TABLE CC_S_TMP_AVY_AGENT
  (
    USER_ID       VARCHAR (32) NOT NULL ,
    TELSETLOGINID NUMERIC (16) ,
    SURNAME       VARCHAR (64) ,
    GIVENNAME     VARCHAR (64) ,
    DEPARTMENT    VARCHAR (64) ,
    TITLE         VARCHAR (64) ,
    SKILLSETID    NUMERIC (16) ,
    CONSTRAINT CC_S_TMP_AVY_AGENT_PK PRIMARY KEY CLUSTERED (USER_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE CC_S_TMP_AVY_AGENTBYAPP
  (
                  TIMESTAMP DATE ,
    AGENTLOGIN    VARCHAR (16) ,
    APPLICATIONID NUMERIC (10) ,
    HOLDTIME      NUMERIC (10)
  )
  ON "default"
GO

CREATE
  TABLE CC_S_TMP_AVY_APPLICATION
  (
    APPLICATIONID         NUMERIC (10) NOT NULL ,
    NAME                  VARCHAR (30) ,
    SERVICELEVELTHRESHOLD NUMERIC (10) ,
    TEMPLATEID            NUMERIC (10) ,
    CONSTRAINT CC_S_TMP_AVY_APPLICATION_PK PRIMARY KEY CLUSTERED (APPLICATIONID
    )
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE CC_S_TMP_AVY_DAGENTPERFORMANCE
  (
                           TIMESTAMP DATE ,
    USERID                 VARCHAR (32) ,
    AGENTLOGIN             VARCHAR (16) ,
    SUPERVISORLOGIN        VARCHAR (16) ,
    ACDCALLSANSWERED       NUMERIC (10) ,
    HOLDTIME               NUMERIC (10) ,
    LOGGEDINTIME           NUMERIC (10) ,
    NOTREADYTIME           NUMERIC (10) ,
    RESERVEDTIME           NUMERIC (10) ,
    RINGTIME               NUMERIC (10) ,
    TALKTIME               NUMERIC (10) ,
    WAITINGTIME            NUMERIC (10) ,
    POSTCALLPROCESSINGTIME NUMERIC (10) ,
    CONTACTTALKTIME        NUMERIC (10) ,
    CONTACTHOLDTIME        NUMERIC (10) ,
    CALLSANSWERED          NUMERIC (10) ,
    SITEID                 NUMERIC (10) ,
    SITE                   VARCHAR (30) ,
    DNINEXTCALLSTALKTIME   NUMERIC (10) ,
    DNOUTEXTCALLSTALKTIME  NUMERIC (10) ,
    DNININTCALLSTALKTIME   NUMERIC (10) ,
    DNOUTINTCALLSTALKTIME  NUMERIC (10) ,
    DNINEXTCALLS           NUMERIC (10) ,
    DNOUTEXTCALLS          NUMERIC (10) ,
    DNININTCALLS           NUMERIC (10) ,
    DNOUTINTCALLS          NUMERIC (10) ,
    BUSYONDNTIME           NUMERIC (10) ,
    BREAKTIME              NUMERIC (10) ,
    CONSULTATIONTIME       NUMERIC (10) ,
    WALKAWAYTIME           NUMERIC (10)
  )
  ON "default"
GO

CREATE
  TABLE CC_S_TMP_AVY_ECSRSTAT
  (
    CustID                         INTEGER ,
    SequenceID                     NUMERIC (10) ,
    GUID                           VARCHAR (36) ,
    CCMID                          INTEGER ,
    ProviderContactID              VARCHAR (50) ,
    InterCallID                    INTEGER ,
    ContactType                    INTEGER ,
    ContactTypeName                VARCHAR (30) ,
    ContactSubType                 VARCHAR (50) ,
    ContactProximity               VARCHAR (50) ,
    Priority                       SMALLINT ,
    Provider                       VARCHAR (50) ,
    SiteID                         INTEGER ,
    SiteName                       VARCHAR (30) ,
    RemoteSiteID                   INTEGER ,
    RemoteSiteName                 VARCHAR (30) ,
    Originator                     VARCHAR (256) ,
    Address                        VARCHAR (255) ,
    RoutePoint                     VARCHAR (30) ,
    ApplicationID                  INTEGER ,
    ApplicationName                VARCHAR (30) ,
    SourceApplicationName          VARCHAR (30) ,
    ApplicationStartStamp          DATETIME ,
    LastTreatmentID                INTEGER ,
    Treatment                      VARCHAR (50) ,
    LastTreatmentStamp             DATETIME ,
    LastTreatmentTime              INTEGER ,
    SkillsetID                     INTEGER ,
    SkillsetName                   VARCHAR (30) ,
    SkillsetQueuedStamp            DATETIME ,
    LocalUserID                    INTEGER ,
    AgentSurName                   VARCHAR (64) ,
    AgentGivenName                 VARCHAR (64) ,
    SupervisorSurName              VARCHAR (64) ,
    SupervisorGivenName            VARCHAR (64) ,
    AgentID                        VARCHAR (16) ,
    SupervisorID                   VARCHAR (16) ,
    OriginatedStamp                DATETIME ,
    InitialDisposition             VARCHAR (50) ,
    ServiceStamp                   DATETIME ,
    AppAbandonDelay                INTEGER ,
    AppAcceptedDelay               INTEGER ,
    SksAbandonDelay                INTEGER ,
    SksAcceptedDelay               INTEGER ,
    HandlingTime                   INTEGER ,
    ConsultTime                    INTEGER ,
    HoldTime                       INTEGER ,
    NumberOfTimesOnHold            INTEGER ,
    NumberOfTimesRTQ               INTEGER ,
    FinalDisposition               VARCHAR (50) ,
    FinalDispositionStamp          DATETIME ,
    PresentingTime                 INTEGER ,
    PCPTime                        INTEGER ,
    PCPFirstCode                   VARCHAR (32) ,
    WaitTime                       INTEGER ,
    NextAddress                    VARCHAR (255) ,
    NextSegmentID                  INTEGER ,
    ContactOriginatedStamp         DATETIME ,
    FinalDispositionInterval       VARCHAR (255) ,
    ServiceInterval                VARCHAR (255) ,
    OriginatedInterval             VARCHAR (255) ,
    DisconnectSource               VARCHAR (9) ,
    NumContactObserves             INTEGER ,
    NumContactBargeIns             INTEGER ,
    AnchoredMediaServer            VARCHAR (50) ,
    PreferredMediaServer           VARCHAR (50) ,
    PreferredMediaServerResult     INTEGER ,
    PreferredMediaServerResultDesc VARCHAR (80)
  )
  ON "default"
GO

CREATE
  TABLE CC_S_TMP_AVY_IAPPLICATION
  (
                               TIMESTAMP DATE ,
    APPLICATIONID              NUMERIC (10) ,
    APPLICATION                VARCHAR (30) ,
    CALLSABANDONED             NUMERIC (10) ,
    CALLSABANDONEDAFTTHRESHOLD NUMERIC (10) ,
    CALLSABANDONEDDELAY        NUMERIC (10) ,
    CALLSANSWERED              NUMERIC (10) ,
    CALLSANSWEREDAFTTHRESHOLD  NUMERIC (10) ,
    CALLSANSWEREDDELAY         NUMERIC (10) ,
    CALLSGIVENFORCEBUSY        NUMERIC (10) ,
    CALLSGIVENFORCEDISCONNECT  NUMERIC (10) ,
    CALLSGIVENFORCEOVERFLOW    NUMERIC (10) ,
    CALLSGIVENROUTETO          NUMERIC (10) ,
    CALLSOFFERED               NUMERIC (10) ,
    CALLSTRANSFERREDIN         NUMERIC (10) ,
    CALLSTRANSFERREDOUT        NUMERIC (10) ,
    IVRABANDONED               NUMERIC (10) ,
    IVRTERMINATED              NUMERIC (10) ,
    IVRTRANSFERRED             NUMERIC (10) ,
    POSTCALLPROCESSINGTIME     NUMERIC (10) ,
    TALKTIME                   NUMERIC (10) ,
    WAITTIME                   NUMERIC (10) ,
    ANSDELAY2                  NUMERIC (10) ,
    ANSDELAY4                  NUMERIC (10) ,
    ANSDELAY6                  NUMERIC (10) ,
    ANSDELAY8                  NUMERIC (10) ,
    ANSDELAY10                 NUMERIC (10) ,
    ANSDELAY12                 NUMERIC (10) ,
    ANSDELAY14                 NUMERIC (10) ,
    ANSDELAY16                 NUMERIC (10) ,
    ANSDELAY18                 NUMERIC (10) ,
    ANSDELAY20                 NUMERIC (10) ,
    ANSDELAY22                 NUMERIC (10) ,
    ANSDELAY24                 NUMERIC (10) ,
    ANSDELAY26                 NUMERIC (10) ,
    ANSDELAY28                 NUMERIC (10) ,
    ANSDELAY30                 NUMERIC (10) ,
    ANSDELAY32                 NUMERIC (10) ,
    ANSDELAY34                 NUMERIC (10) ,
    ANSDELAY36                 NUMERIC (10) ,
    ANSDELAY38                 NUMERIC (10) ,
    ANSDELAY40                 NUMERIC (10) ,
    ANSDELAY42                 NUMERIC (10) ,
    ANSDELAY44                 NUMERIC (10) ,
    ANSDELAY46                 NUMERIC (10) ,
    ANSDELAY48                 NUMERIC (10) ,
    ANSDELAY50                 NUMERIC (10) ,
    ANSDELAY52                 NUMERIC (10) ,
    ANSDELAY54                 NUMERIC (10) ,
    ANSDELAY56                 NUMERIC (10) ,
    ANSDELAY58                 NUMERIC (10) ,
    ANSDELAY60                 NUMERIC (10) ,
    ANSDELAY70                 NUMERIC (10) ,
    ANSDELAY80                 NUMERIC (10) ,
    ANSDELAY90                 NUMERIC (10) ,
    ANSDELAY100                NUMERIC (10) ,
    ANSDELAY110                NUMERIC (10) ,
    ANSDELAY120                NUMERIC (10) ,
    ANSDELAY130                NUMERIC (10) ,
    ANSDELAY140                NUMERIC (10) ,
    ANSDELAY150                NUMERIC (10) ,
    ANSDELAY160                NUMERIC (10) ,
    ANSDELAY170                NUMERIC (10) ,
    ANSDELAY180                NUMERIC (10) ,
    ANSDELAY190                NUMERIC (10) ,
    ANSDELAY200                NUMERIC (10) ,
    ANSDELAY210                NUMERIC (10) ,
    ANSDELAY220                NUMERIC (10) ,
    ANSDELAY230                NUMERIC (10) ,
    ANSDELAY240                NUMERIC (10) ,
    ANSDELAY250                NUMERIC (10) ,
    ANSDELAY260                NUMERIC (10) ,
    ANSDELAY270                NUMERIC (10) ,
    ANSDELAY280                NUMERIC (10) ,
    ANSDELAY290                NUMERIC (10) ,
    ANSDELAY300                NUMERIC (10) ,
    ANSDELAY360                NUMERIC (10) ,
    ANSDELAY420                NUMERIC (10) ,
    ANSDELAY480                NUMERIC (10) ,
    ANSDELAY540                NUMERIC (10) ,
    ANSDELAY600                NUMERIC (10) ,
    ANSDELAYBEYOND             NUMERIC (10) ,
    ABDDELAY2                  NUMERIC (10) ,
    ABDDELAY4                  NUMERIC (10) ,
    ABDDELAY6                  NUMERIC (10) ,
    ABDDELAY8                  NUMERIC (10) ,
    ABDDELAY10                 NUMERIC (10) ,
    ABDDELAY12                 NUMERIC (10) ,
    ABDDELAY14                 NUMERIC (10) ,
    ABDDELAY16                 NUMERIC (10) ,
    ABDDELAY18                 NUMERIC (10) ,
    ABDDELAY20                 NUMERIC (10) ,
    ABDDELAY22                 NUMERIC (10) ,
    ABDDELAY24                 NUMERIC (10) ,
    ABDDELAY26                 NUMERIC (10) ,
    ABDDELAY28                 NUMERIC (10) ,
    ABDDELAY30                 NUMERIC (10) ,
    ABDDELAY32                 NUMERIC (10) ,
    ABDDELAY34                 NUMERIC (10) ,
    ABDDELAY36                 NUMERIC (10) ,
    ABDDELAY38                 NUMERIC (10) ,
    ABDDELAY40                 NUMERIC (10) ,
    ABDDELAY42                 NUMERIC (10) ,
    ABDDELAY44                 NUMERIC (10) ,
    ABDDELAY46                 NUMERIC (10) ,
    ABDDELAY48                 NUMERIC (10) ,
    ABDDELAY50                 NUMERIC (10) ,
    ABDDELAY52                 NUMERIC (10) ,
    ABDDELAY54                 NUMERIC (10) ,
    ABDDELAY56                 NUMERIC (10) ,
    ABDDELAY58                 NUMERIC (10) ,
    ABDDELAY60                 NUMERIC (10) ,
    ABDDELAY70                 NUMERIC (10) ,
    ABDDELAY80                 NUMERIC (10) ,
    ABDDELAY90                 NUMERIC (10) ,
    ABDDELAY100                NUMERIC (10) ,
    ABDDELAY110                NUMERIC (10) ,
    ABDDELAY120                NUMERIC (10) ,
    ABDDELAY130                NUMERIC (10) ,
    ABDDELAY140                NUMERIC (10) ,
    ABDDELAY150                NUMERIC (10) ,
    ABDDELAY160                NUMERIC (10) ,
    ABDDELAY170                NUMERIC (10) ,
    ABDDELAY180                NUMERIC (10) ,
    ABDDELAY190                NUMERIC (10) ,
    ABDDELAY200                NUMERIC (10) ,
    ABDDELAY210                NUMERIC (10) ,
    ABDDELAY220                NUMERIC (10) ,
    ABDDELAY230                NUMERIC (10) ,
    ABDDELAY240                NUMERIC (10) ,
    ABDDELAY250                NUMERIC (10) ,
    ABDDELAY260                NUMERIC (10) ,
    ABDDELAY270                NUMERIC (10) ,
    ABDDELAY280                NUMERIC (10) ,
    ABDDELAY290                NUMERIC (10) ,
    ABDDELAY300                NUMERIC (10) ,
    ABDDELAY360                NUMERIC (10) ,
    ABDDELAY420                NUMERIC (10) ,
    ABDDELAY480                NUMERIC (10) ,
    ABDDELAY540                NUMERIC (10) ,
    ABDDELAY600                NUMERIC (10) ,
    ABDDELAYBEYOND             NUMERIC (10) ,
    TIME                       VARCHAR (5) ,
    CONTACTTYPE                VARCHAR (30) ,
    MAXCALLSANSDELAYATSKILLSET NUMERIC (10) ,
    MAXCALLSANSDELAY           NUMERIC (10)
  )
  ON "default"
GO

CREATE
  TABLE CC_S_TMP_CISCO_AGENT_INTERVAL
  (
                  DATETIME DATE ,
    SKILLTARGETID NUMERIC (28) ,
    TIMEZONE      NUMERIC (28) ,
    LOGGEDONTIME  NUMERIC (28) ,
    AVAILTIME     NUMERIC (28) ,
    NOTREADYTIME  NUMERIC (28) ,
    TALKOTHERTIME NUMERIC (28)
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
TMP_CISCO_AGT_INT_DTTIME_IDX ON CC_S_TMP_CISCO_AGENT_INTERVAL
(
  DATETIME
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
TMP_CISCO_AGT_INT_SKTGTID_IDX ON CC_S_TMP_CISCO_AGENT_INTERVAL
(
  SKILLTARGETID
)
ON "default"
GO

CREATE
  TABLE CC_S_TMP_CISCO_AGENT_LOGOUT
  (
    SKILLTARGETID  NUMERIC (28) ,
    LOGOUTDATETIME DATE ,
    TIMEZONE       NUMERIC (28) ,
    LOGINDURATION  NUMERIC (28) ,
    REASONCODE     NUMERIC (28)
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
TMP_CISCO_AGT_LOUT_LODTTME_IDX ON CC_S_TMP_CISCO_AGENT_LOGOUT
(
  LOGOUTDATETIME
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
TMP_CISCO_AGT_LOUT_SKTGTID_IDX ON CC_S_TMP_CISCO_AGENT_LOGOUT
(
  SKILLTARGETID
)
ON "default"
GO

CREATE
  TABLE CC_S_TMP_CISCO_A_SG_INTERVAL
  (
                            DATETIME DATE ,
    DBDATETIME              DATE ,
    SKILLTARGETID           NUMERIC (28) ,
    SKILLGROUPSKILLTARGETID NUMERIC (28) ,
    TIMEZONE                NUMERIC (28) ,
    AVAILTIME               NUMERIC (28) ,
    LOGGEDONTIME            NUMERIC (28) ,
    NOTREADYTIME            NUMERIC (28) ,
    TALKRESERVETIME         NUMERIC (28) ,
    RESERVEDSTATETIME       NUMERIC (28) ,
    TALKINTIME              NUMERIC (28) ,
    TALKOTHERTIME           NUMERIC (28) ,
    TALKOUTTIME             NUMERIC (28) ,
    TALKAUTOOUTTIME         NUMERIC (28) ,
    TALKPREVIEWTIME         NUMERIC (28) ,
    HOLDTIME                NUMERIC (28) ,
    WORKNOTREADYTIME        NUMERIC (28) ,
    WORKREADYTIME           NUMERIC (28) ,
    AGENTOUTCALLS           NUMERIC (28) ,
    CALLSHANDLED            NUMERIC (28) ,
    AUTOOUTCALLS            NUMERIC (28) ,
    PREVIEWCALLS            NUMERIC (28) ,
    INTERNALCALLS           NUMERIC (28)
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
TMP_CISCO_AGTSG_INT_DTTIME_IDX ON CC_S_TMP_CISCO_A_SG_INTERVAL
(
  DATETIME
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
TMP_CISCO_AGTSG_INT_STGID_IDX ON CC_S_TMP_CISCO_A_SG_INTERVAL
(
  SKILLTARGETID
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
TMP_CSCO_AGTSG_INT_SGTGTID_IDX ON CC_S_TMP_CISCO_A_SG_INTERVAL
(
  SKILLGROUPSKILLTARGETID
)
ON "default"
GO

CREATE
  TABLE CC_S_TMP_CISCO_C_T_INTERVAL
  (
    CALLTYPEID               NUMERIC (28) ,
    TIMEZONE                 NUMERIC (28) ,
                             DATETIME DATE ,
    DBDATETIME               DATE ,
    ANSWERWAITTIME           NUMERIC (28) ,
    CALLSHANDLED             NUMERIC (28) ,
    CALLSOFFERED             NUMERIC (28) ,
    HANDLETIME               NUMERIC (28) ,
    TALKTIME                 NUMERIC (28) ,
    HOLDTIME                 NUMERIC (28) ,
    CALLSANSWERED            NUMERIC (28) ,
    ANSINTERVAL1             NUMERIC (28) ,
    ANSINTERVAL2             NUMERIC (28) ,
    ANSINTERVAL3             NUMERIC (28) ,
    ANSINTERVAL4             NUMERIC (28) ,
    ANSINTERVAL5             NUMERIC (28) ,
    ANSINTERVAL6             NUMERIC (28) ,
    ANSINTERVAL7             NUMERIC (28) ,
    ANSINTERVAL8             NUMERIC (28) ,
    ANSINTERVAL9             NUMERIC (28) ,
    ANSINTERVAL10            NUMERIC (28) ,
    ABANDINTERVAL1           NUMERIC (28) ,
    ABANDINTERVAL2           NUMERIC (28) ,
    ABANDINTERVAL3           NUMERIC (28) ,
    ABANDINTERVAL4           NUMERIC (28) ,
    ABANDINTERVAL5           NUMERIC (28) ,
    ABANDINTERVAL6           NUMERIC (28) ,
    ABANDINTERVAL7           NUMERIC (28) ,
    ABANDINTERVAL8           NUMERIC (28) ,
    ABANDINTERVAL9           NUMERIC (28) ,
    ABANDINTERVAL10          NUMERIC (28) ,
    TOTALCALLSABAND          NUMERIC (28) ,
    ROUTERQUEUEWAITTIME      NUMERIC (28) ,
    ROUTERQUEUECALLTYPELIMIT NUMERIC (28) ,
    ROUTERQUEUEGLOBALLIMIT   NUMERIC (28) ,
    CALLSONHOLD              NUMERIC (28) ,
    MAXHOLDTIME              NUMERIC (28) ,
    MAXCALLWAITTIME          NUMERIC (28) ,
    SERVICELEVELCALLS        NUMERIC (28) ,
    SERVICELEVELABAND        NUMERIC (28) ,
    CALLDELAYABANDTIME       NUMERIC (28) ,
    MAXCALLSQUEUED           NUMERIC (28) ,
    SHORTCALLS               NUMERIC (28) ,
    REPORTING_INTERVAL       NUMERIC (28) ,
    VRUSCRIPTEDXFERREDCALLS  NUMERIC (28) ,
    VRUFORCEDXFERREDCALLS    NUMERIC (28) ,
    OVERFLOWOUT              NUMERIC (28) ,
    CTVRUTIME                NUMERIC (28) ,
    ICRDEFAULTROUTED         NUMERIC (28) ,
    NETWORKDEFAULTROUTED     NUMERIC (28) ,
    RETURNBUSY               NUMERIC (28) ,
    CALLSRONA                NUMERIC (28) ,
    RETURNRELEASE            NUMERIC (28) ,
    CALLSROUTEDNONAGENT      NUMERIC (28) ,
    ERRORCOUNT               NUMERIC (28) ,
    AGENTERRORCOUNT          NUMERIC (28) ,
    INCOMPLETECALLS          NUMERIC (28) ,
    RETURNRING               NUMERIC (28)
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
TMP_CISCO_CTYPE_INT_CLTPID_IDX ON CC_S_TMP_CISCO_C_T_INTERVAL
(
  CALLTYPEID
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
TMP_CISCO_CTYPE_INT_DTTIME_IDX ON CC_S_TMP_CISCO_C_T_INTERVAL
(
  DATETIME
)
ON "default"
GO

CREATE
  TABLE CC_S_TMP_INTERVAL
  (
    INTERVAL_ID         NUMERIC (19) NOT NULL ,
    INTERVAL_START_DATE DATE NOT NULL ,
    INTERVAL_END_DATE   DATE NOT NULL ,
    INTERVAL_SECONDS    NUMERIC (4) NOT NULL DEFAULT 1800 ,
    RECORD_EFF_DT       DATE NOT NULL DEFAULT '01/01/1900' ,
    RECORD_END_DT DATE NOT NULL DEFAULT '12/31/2999' ,
    CONSTRAINT CC_S_TMP_INTERVAL_PK PRIMARY KEY CLUSTERED (INTERVAL_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default" ,
  CONSTRAINT CC_S_TMP_INTERVAL_UN UNIQUE NONCLUSTERED (INTERVAL_START_DATE,
  INTERVAL_END_DATE) ON "default"
  )
  ON "default"
GO
ALTER TABLE CC_S_TMP_INTERVAL
ADD CONSTRAINT CK_CC_S_TMP_INTERVAL_SECONDS
CHECK ( INTERVAL_SECONDS IN (900, 1800, 3600) )
GO
CREATE NONCLUSTERED INDEX
CC_S_TMP_INTERVAL__IDX1 ON CC_S_TMP_INTERVAL
(
INTERVAL_START_DATE
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_TMP_INTERVAL__IDX2 ON CC_S_TMP_INTERVAL
(
INTERVAL_END_DATE
)
ON "default"
GO

CREATE
  TABLE CC_S_TMP_IVR_STEP
  (
    ID        NUMERIC (28) NOT NULL ,
    CLIENT    VARCHAR (200) ,
    STEPTIME  DATE ,
    CONNID    VARCHAR (200) ,
    SESSIONID VARCHAR (250) ,
    STEPNAME  VARCHAR (200) ,
    STEPVALUE VARCHAR (200) ,
    NODENAME  VARCHAR (200) ,
    CONSTRAINT CC_S_IVR_STEP_PK PRIMARY KEY CLUSTERED (ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
CC_S_IVR_STEP_IDX ON CC_S_TMP_IVR_STEP
(
  ID
)
ON "default"
GO

CREATE
  TABLE CC_S_TMP_PIPKINS_EVENT
  (
    EVENT_ID                NUMERIC (38) ,
    NAME                    VARCHAR (250) ,
    EVENT_TYPE_GROUP_ID     NUMERIC (38) ,
    EVENT_TYPE_ID           NUMERIC (38) ,
    TOLERANCE_FOR_TIMECLOCK DATE ,
    DELETE_DATE             DATE ,
    TOLERANCE_FOR_ADHERING  DATE ,
    DESCRIPTION             VARCHAR (250) ,
    OWNER_USER              NUMERIC (38) ,
    MODIFY_USER             NUMERIC (38) ,
    OWNER_DATE              DATE ,
    MODIFY_DATE             DATE ,
    WORK_CLASSIFICATION_ID  NUMERIC (38)
  )
  ON "default"
GO

CREATE
  TABLE CC_S_TMP_PIPKINS_OFFICE
  (
    OFFICE_ID   NUMERIC (10) ,
    LOCALE_ID   NUMERIC (10) ,
    TIMEZONE_ID NUMERIC (10) ,
    NAME        VARCHAR (20) ,
    DESCRIPTION VARCHAR (200) ,
    DELETE_DATE DATE ,
    OWNER_USER  NUMERIC (10) ,
    MODIFY_USER NUMERIC (10) ,
    OWNER_DATE  DATE ,
    MODIFY_DATE DATE
  )
  ON "default"
GO

CREATE
  TABLE CC_S_TMP_PIPKINS_STAFF
  (
    STAFF_ID                 NUMERIC (38) ,
    STAFF_GROUP_ID           NUMERIC (10) ,
    STAFF_GROUP_NAME         VARCHAR (50) ,
    FIRST_NAME               VARCHAR (50) ,
    MIDDLE_NAME              VARCHAR (50) ,
    LAST_NAME                VARCHAR (50) ,
    SUFFIX                   VARCHAR (50) ,
    NATIONAL_ID              VARCHAR (250) ,
    HIRE_DATE                DATE ,
    TERMINATION_DATE         DATE ,
    SCHEDULE_TYPE            NUMERIC (38) ,
    DELETE_DATE              DATE ,
    SENIORITY_EFFECTIVE_DATE DATE ,
    OWNER_USER               NUMERIC (38) ,
    OWNER_DATE               DATE ,
    MODIFY_USER              NUMERIC (38) ,
    MODIFY_DATE              DATE ,
    SECONDARY_ID             VARCHAR (250) ,
    EMAIL_ADDRESS            VARCHAR (250) ,
    HOME_PHONE               VARCHAR (28) ,
    WORK_PHONE               VARCHAR (28) ,
    CELL_PHONE               VARCHAR (28) ,
    ADDRESS                  VARCHAR (2000) ,
    PIP_ADDRESS              VARCHAR (250) ,
    TEXT_ADDRESS             VARCHAR (250) ,
    TERMINATION_POLICY_ID    NUMERIC (38) ,
    TERMINATION_REASON       VARCHAR (2000) ,
    COMMAND_SCRIPT           VARCHAR (4000) ,
    MESSAGE_BUFFER           VARCHAR (4000)
  )
  ON "default"
GO

CREATE
  TABLE CC_S_TMP_PIPKINS_STF_TO_OFFICE
  (
    EFFECTIVE_DATE DATE ,
    STAFF_ID       NUMERIC (10) ,
    OFFICE_ID      NUMERIC (10) ,
    END_DATE       DATE
  )
  ON "default"
GO

CREATE
  TABLE CC_S_TMP_PIPKINS_SUP_TO_STAFF
  (
    STAFF_ID       NUMERIC (38) ,
    SUPERVISOR     NUMERIC (38) ,
    PRIORITY       NUMERIC (38) ,
    EFFECTIVE_DATE DATE ,
    END_DATE       DATE ,
    SUPERVISOR_ID  NUMERIC (38)
  )
  ON "default"
GO

CREATE
  TABLE CC_S_TMP_PIPKINS_TASK
  (
    STAFF_ID                      NUMERIC (38) ,
    SCHEDULE_INSTANCE_ID          NUMERIC (38) ,
    TASK_START                    DATE ,
    LOCAL_TASK_START              DATE ,
    SCENARIO_GROUP_ID             NUMERIC (38) ,
    TASK_END                      DATE ,
    LOCAL_TASK_END                DATE ,
    TASK_CATEGORY_ID              NUMERIC (38) ,
    DURATION                      NUMERIC (38) ,
    EVENT_ID                      NUMERIC (38) ,
    SUPERVISOR                    NUMERIC (38) ,
    TASK_EDIT_ID                  NUMERIC (38) ,
    EDIT_STATE                    NUMERIC (38) ,
    TASK_MODIFICATION_REQUEST_REF NUMERIC (38) ,
    ALT_TASK_EDIT_ID              NUMERIC (38)
  )
  ON "default"
GO

CREATE
  TABLE CC_S_TMP_PIPKINS_TIMEZONE
  (
    TIMEZONE_ID  NUMERIC (10) ,
    STD_NAME     VARCHAR (50) ,
    NAME         VARCHAR (50) ,
    START_TIME   DATE ,
    DST_OBSERVED NUMERIC (10) ,
    STD_OFFSET FLOAT ,
    DST_OFFSET FLOAT ,
    START_MONTH                NUMERIC (10) ,
    START_WEEK                 NUMERIC (10) ,
    START_WEEK_DAY             NUMERIC (10) ,
    END_TIME                   DATE ,
    END_MONTH                  NUMERIC (10) ,
    END_WEEK                   NUMERIC (10) ,
    END_WEEK_DAY               NUMERIC (10) ,
    DST_NAME                   VARCHAR (50) ,
    SHIFT_YEAR1                NUMERIC (10) ,
    SHIFT_YEAR1_START_TIME     DATE ,
    SHIFT_YEAR1_START_MONTH    NUMERIC (10) ,
    SHIFT_YEAR1_START_WEEK     NUMERIC (10) ,
    SHIFT_YEAR1_START_WEEK_DAY NUMERIC (10) ,
    SHIFT_YEAR1_END_TIME       DATE ,
    SHIFT_YEAR1_END_MONTH      NUMERIC (10) ,
    SHIFT_YEAR1_END_WEEK       NUMERIC (10) ,
    SHIFT_YEAR1_END_WEEK_DAY   NUMERIC (10) ,
    DOTNET_NAME                VARCHAR (50) ,
    DISPLAY_FLAG               NUMERIC (10)
  )
  ON "default"
GO

CREATE
  TABLE CC_S_VM_IN_QUEUE
  (
    CCVMQ_ID       NUMERIC (19) not null primary key  constraint CC_S_VM_IN_QUEUE_PK default next value for SEQ_CC_S_VM_IN_QUEUE ,
    VM_QUEUE_ID    VARCHAR (25) NOT NULL ,
    MEDIA_TYPE     VARCHAR (15) NOT NULL ,
    VM_RECEIVED_DT DATE NOT NULL ,
    ANI            VARCHAR (25) NOT NULL ,
    EXTRACT_DT     DATE NOT NULL ,
    LAST_UPDATE_DT DATE NOT NULL ,
    LAST_UPDATE_BY VARCHAR (30) NOT NULL )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
CC_S_VM_IN_QUEUE_IDX ON CC_S_VM_IN_QUEUE
(
  VM_QUEUE_ID
)
ON "default"
GO

CREATE
  TABLE CC_S_WFM_AGENT_ACTIVITY
  (
    WFM_AGENT_ACTIVITY_ID     NUMERIC (19) not null primary key  constraint CC_S_WFM_AGENT_ACTIVITY_PK default next value for SEQ_CC_S_WFM_AGENT_ACTIVITY ,
    AGENT_ID                  NUMERIC (19) NOT NULL ,
    ACTIVITY_TYPE_ID          NUMERIC (19) NOT NULL ,
    ACTIVITY_START_TIME       DATE NOT NULL ,
    ACTIVITY_END_TIME         DATE NOT NULL ,
    ACTIVITY_DURATION_SECONDS NUMERIC (15,2) NOT NULL DEFAULT 0 ,
    ACTIVITY_DT               DATE NOT NULL ,
    EXTRACT_DT                DATE NOT NULL ,
    LAST_UPDATE_DT            DATE NOT NULL ,
    LAST_UPDATE_BY            VARCHAR (30) NOT NULL)
  ON "default"
GO
ALTER TABLE CC_S_WFM_AGENT_ACTIVITY
ADD CONSTRAINT CC_S_AGENT_ACTIVITY_CK
CHECK ( ACTIVITY_START_TIME <= ACTIVITY_END_TIME )
GO
CREATE UNIQUE NONCLUSTERED INDEX
CC_S_WFM_AGENT_ACTIVITY_IDX ON CC_S_WFM_AGENT_ACTIVITY
(
WFM_AGENT_ACTIVITY_ID
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_WFM_AGENT_ACTIVITY_IDX2 ON CC_S_WFM_AGENT_ACTIVITY
(
AGENT_ID ,
ACTIVITY_TYPE_ID ,
ACTIVITY_START_TIME
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_WFM_AGENT_ACTIVITY_IDX3 ON CC_S_WFM_AGENT_ACTIVITY
(
ACTIVITY_TYPE_ID
)
ON "default"
GO

CREATE
  TABLE CC_S_WFM_INTERVAL
  (
    WFM_INTERVAL_ID         NUMERIC (19) not null primary key  constraint CC_S_WFM_INTERVAL_PK default next value for SEQ_CC_S_WFM_INTERVAL ,
    INTERVAL_DATE           DATE NOT NULL ,
    CONTACT_QUEUE_ID        NUMERIC (19) NOT NULL ,
    INTERVAL_ID             NUMERIC (19) NOT NULL ,
    LABOR_MINUTES_TOTAL     NUMERIC (9,2) NOT NULL DEFAULT 0 ,
    LABOR_MINUTES_WAITING   NUMERIC (9,2) NOT NULL DEFAULT 0 ,
    LABOR_MINUTES_AVAILABLE NUMERIC (9,2) NOT NULL DEFAULT 0 ,
    HEADCOUNT_TOTAL         NUMERIC (7,2) NOT NULL DEFAULT 0 ,
    HEADCOUNT_AVAILABLE     NUMERIC (7,2) NOT NULL DEFAULT 0 ,
    HEADCOUNT_UNAVAILABLE   NUMERIC (7,2) NOT NULL DEFAULT 0 ,
    EXTRACT_DT              DATE NOT NULL ,
    LAST_UPDATE_DT          DATE NOT NULL ,
    LAST_UPDATE_BY          VARCHAR (30) NOT NULL ,
  CONSTRAINT CC_S_WFM_INTERVAL__UN UNIQUE NONCLUSTERED (INTERVAL_DATE,
  CONTACT_QUEUE_ID, INTERVAL_ID) ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_WFM_INTERVAL__IDXv2 ON CC_S_WFM_INTERVAL
(
  CONTACT_QUEUE_ID
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
CC_S_WFM_INTERVAL__IDXv3 ON CC_S_WFM_INTERVAL
(
  INTERVAL_ID
)
ON "default"
GO

ALTER TABLE CC_S_CONTACT_QUEUE
ADD CONSTRAINT CC_C_CNTCT_Q_CC_C_PRJCT_CFG_FK FOREIGN KEY
(
PROJECT_CONFIG_ID
)
REFERENCES CC_C_PROJECT_CONFIG
(
PROJECT_CONFIG_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_PRODUCTION_PLAN_HORIZON
ADD CONSTRAINT CC_C_HRZN_CC_C_PROD_PLN_FK FOREIGN KEY
(
PRODUCTION_PLAN_ID
)
REFERENCES CC_S_PRODUCTION_PLAN
(
PRODUCTION_PLAN_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_ACD_AGENT_ACTIVITY
ADD CONSTRAINT CC_S_ACD_AGT_ACT_CC_S_AGT_FK FOREIGN KEY
(
AGENT_ID
)
REFERENCES CC_S_AGENT
(
AGENT_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_ACD_INTERVAL
ADD CONSTRAINT CC_S_ACD_INTRVL_CC_S_AGENT_FK FOREIGN KEY
(
AGENT_ID
)
REFERENCES CC_S_AGENT
(
AGENT_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_ACD_INTERVAL
ADD CONSTRAINT CC_S_ACD_INTRVL_CC_S_CNTCTQ_FK FOREIGN KEY
(
CONTACT_QUEUE_ID
)
REFERENCES CC_S_CONTACT_QUEUE
(
CONTACT_QUEUE_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_ACD_INTERVAL
ADD CONSTRAINT CC_S_ACD_INTRVL_CC_S_INTRVL_FK FOREIGN KEY
(
INTERVAL_ID
)
REFERENCES CC_S_INTERVAL
(
INTERVAL_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_AGENT_ABSENCE
ADD CONSTRAINT CC_S_AGENT_ABS_CC_C_ACT_TYP_FK FOREIGN KEY
(
ACTIVITY_TYPE_ID
)
REFERENCES CC_C_ACTIVITY_TYPE
(
ACTIVITY_TYPE_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_AGENT_ABSENCE
ADD CONSTRAINT CC_S_AGENT_ABS_CC_S_AGENT_FK FOREIGN KEY
(
AGENT_ID
)
REFERENCES CC_S_AGENT
(
AGENT_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_AGENT
ADD CONSTRAINT CC_S_AGENT_CC_C_PRJ_CONFIG_FK FOREIGN KEY
(
PROJECT_CONFIG_ID
)
REFERENCES CC_C_PROJECT_CONFIG
(
PROJECT_CONFIG_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_WFM_AGENT_ACTIVITY
ADD CONSTRAINT CC_S_AGT_ACT_CC_C_ACT_TYPE_FK FOREIGN KEY
(
ACTIVITY_TYPE_ID
)
REFERENCES CC_C_ACTIVITY_TYPE
(
ACTIVITY_TYPE_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_WFM_AGENT_ACTIVITY
ADD CONSTRAINT CC_S_AGT_ACT_CC_S_AGT_FK FOREIGN KEY
(
AGENT_ID
)
REFERENCES CC_S_AGENT
(
AGENT_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_AGENT_SUPERVISOR
ADD CONSTRAINT CC_S_AGT_SUP_CC_S_AGT_FK FOREIGN KEY
(
SUPERVISOR_AGENT_ID
)
REFERENCES CC_S_AGENT
(
AGENT_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_AGENT_WORK_DAY
ADD CONSTRAINT CC_S_AGT_WORK_DAY_CC_S_AGT_FK FOREIGN KEY
(
AGENT_ID
)
REFERENCES CC_S_AGENT
(
AGENT_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_CALL_DETAIL
ADD CONSTRAINT CC_S_CALL_DETAIL_CC_S_AGENT_FK FOREIGN KEY
(
AGENT_ID
)
REFERENCES CC_S_AGENT
(
AGENT_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_CONTACT_QUEUE
ADD CONSTRAINT CC_S_CNTCT_Q_CC_C_UOW_FK FOREIGN KEY
(
UNIT_OF_WORK_ID
)
REFERENCES CC_C_UNIT_OF_WORK
(
UNIT_OF_WORK_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_CONTACT_QUEUE
ADD CONSTRAINT CC_S_CNTCT_Q_CC_S_ABN_PRIOD_FK FOREIGN KEY
(
CALLS_ABANDOND_INTRVL_PRIOD_ID
)
REFERENCES CC_S_ACD_INTERVAL_PERIOD
(
ACD_INTERVAL_PERIOD_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_CONTACT_QUEUE
ADD CONSTRAINT CC_S_CNTCT_Q_CC_S_ASA_PRIOD_FK FOREIGN KEY
(
AVG_SPEED_ANSR_INTRVL_PRIOD_ID
)
REFERENCES CC_S_ACD_INTERVAL_PERIOD
(
ACD_INTERVAL_PERIOD_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_FCST_INTERVAL
ADD CONSTRAINT CC_S_FCST_INTRVL_CC_C_HRZN_FK FOREIGN KEY
(
PRODUCTION_PLAN_HORIZON_ID
)
REFERENCES CC_S_PRODUCTION_PLAN_HORIZON
(
PRODUCTION_PLAN_HORIZON_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_FCST_INTERVAL
ADD CONSTRAINT CC_S_FCST_INTRVL_CC_C_UOW_FK FOREIGN KEY
(
UNIT_OF_WORK_ID
)
REFERENCES CC_C_UNIT_OF_WORK
(
UNIT_OF_WORK_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_FCST_INTERVAL
ADD CONSTRAINT CC_S_FCST_INTRVL_CC_S_INT_FK FOREIGN KEY
(
INTERVAL_ID
)
REFERENCES CC_S_INTERVAL
(
INTERVAL_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_IVR_INTERVAL
ADD CONSTRAINT CC_S_IVR_INTRVL_CC_S_INTRVL_FK FOREIGN KEY
(
INTERVAL_ID
)
REFERENCES CC_S_INTERVAL
(
INTERVAL_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_IVR_INTERVAL
ADD CONSTRAINT CC_S_IVR_INT_CC_C_PRJ_CC_C_FK FOREIGN KEY
(
PROJECT_CONFIG_ID
)
REFERENCES CC_C_PROJECT_CONFIG
(
PROJECT_CONFIG_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_IVR_SELF_SERVICE_USAGE
ADD CONSTRAINT CC_S_IVR_SVC_CC_S_SVC_PATH_FK FOREIGN KEY
(
IVR_SELF_SERVICE_PATH_ID
)
REFERENCES CC_S_IVR_SELF_SERVICE_PATH
(
IVR_SELF_SERVICE_PATH_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_IVR_SELF_SERVICE_USAGE
ADD CONSTRAINT CC_S_IVR_USAGE_C_PRJ_CNFG_FK FOREIGN KEY
(
PROJECT_CONFIG_ID
)
REFERENCES CC_C_PROJECT_CONFIG
(
PROJECT_CONFIG_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_IVR_SELF_SERVICE_USAGE
ADD CONSTRAINT CC_S_IVR_USAGE_S_INTERVAL_FK FOREIGN KEY
(
INTERVAL_ID
)
REFERENCES CC_S_INTERVAL
(
INTERVAL_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_WFM_INTERVAL
ADD CONSTRAINT CC_S_WFM_INT_CC_S_CNTCT_Q_FK FOREIGN KEY
(
CONTACT_QUEUE_ID
)
REFERENCES CC_S_CONTACT_QUEUE
(
CONTACT_QUEUE_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CC_S_WFM_INTERVAL
ADD CONSTRAINT CC_S_WFM_INT_CC_S_INTRVL_FK FOREIGN KEY
(
INTERVAL_ID
)
REFERENCES CC_S_INTERVAL
(
INTERVAL_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

CREATE VIEW CC_S_AGENT_SV  AS 
SELECT CC_S_AGENT.* FROM CC_S_AGENT 
GO




CREATE VIEW CC_S_CALL_DETAIL_SV  AS 
SELECT CC_S_CALL_DETAIL.* FROM CC_S_CALL_DETAIL 
GO




/*CREATE VIEW CC_S_TMP_IVR_STEP_SV  AS 
SELECT iStep.ID,
  iStep.CONNID,
  iStep.STEPTIME,
  iStep.STEPNAME,
  iStep.STEPVALUE,
  iStep.NODENAME,
  CASE
    WHEN iStep.STEPVALUE LIKE 'mdiivrapp%'
    THEN NULL
    ELSE LAG(iStep.NODENAME, 1, NULL) OVER (ORDER BY iStep.CONNID, iStep.STEPTIME)
  END            AS begin_node,
  iStep.NODENAME AS end_node,
  (
  CASE
    WHEN iStep.STEPNAME = 'RPT_IVRData'
    THEN iStep.STEPVALUE
    ELSE iStep.NODENAME
  END) AS ournodename
FROM CC_S_TMP_IVR_STEP iStep
WHERE (iStep.STEPNAME = 'RPT_IVR_GetMenu')
OR (iStep.STEPNAME    = 'RPT_IVR_GetData'
AND iStep.STEPVALUE LIKE 'mdiivrapp%')
OR (iStep.STEPNAME = 'RPT_IVRData'
AND iStep.STEPVALUE LIKE '%vcall')
ORDER BY iStep.CONNID,
  iStep.STEPTIME 
GO

*/

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            54
-- CREATE INDEX                            48
-- ALTER TABLE                             63
-- CREATE VIEW                              3
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
