DROP USER projectuser CASCADE;
DROP ROLE etluser;

DROP TABLESPACE PROJ_STG INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE PROJ_DIM INCLUDING CONTENTS AND DATAFILES;

DROP TABLESPACE MAXDAT_DATA INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE MAXDAT_INDX INCLUDING CONTENTS AND DATAFILES;

COMMIT;