CREATE TABLE "MAXDAT"."CORP_ETL_MFB_ECN_STG" 
   ("CEMFBECN_ID" NUMBER NOT NULL ENABLE, 
	"BATCH_GUID" VARCHAR2(38 BYTE) NOT NULL ENABLE, 
	"ECN" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"STG_EXTRACT_DATE" DATE, 
	"STG_PROCESSED_DATE" DATE, 
	 PRIMARY KEY ("CEMFBECN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MAXDAT_INDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  TABLESPACE "MAXDAT_DATA" ;

   COMMENT ON COLUMN "MAXDAT"."CORP_ETL_MFB_ECN_STG"."CEMFBECN_ID" IS 'sequence';
   COMMENT ON COLUMN "MAXDAT"."CORP_ETL_MFB_ECN_STG"."BATCH_GUID" IS 'Unique identifier for the batch.';
   COMMENT ON COLUMN "MAXDAT"."CORP_ETL_MFB_ECN_STG"."ECN" IS 'Unique number assigned to each envelope for tracking.';
   COMMENT ON COLUMN "MAXDAT"."CORP_ETL_MFB_ECN_STG"."STG_EXTRACT_DATE" IS 'Date of extract from Kofax';
   COMMENT ON COLUMN "MAXDAT"."CORP_ETL_MFB_ECN_STG"."STG_PROCESSED_DATE" IS 'Date that this row was successfully loaded to ETL.';

  CREATE INDEX "MAXDAT"."IDX_CEMFB_ECN_STG_IDX" ON "MAXDAT"."CORP_ETL_MFB_ECN_STG" ("BATCH_GUID", "ECN") 
  TABLESPACE "MAXDAT_INDX" ;
  
  
CREATE SEQUENCE  "MAXDAT"."SEQ_CEMFBECN_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 19701 CACHE 20 NOORDER  NOCYCLE;
  
CREATE OR REPLACE TRIGGER "MAXDAT"."TRG_R_CORP_ETL_MFB_ECN_STG" 
before insert or update on CORP_ETL_MFB_ECN_STG 
for each row
begin
if inserting then
   if :new.CEMFBECN_ID is null then
      :new.CEMFBECN_ID := SEQ_CEMFBECN_ID.nextval;
   end if;
   if :new.STG_EXTRACT_DATE is null then
      :new.STG_EXTRACT_DATE  := current_date;
   end if;
end if;
  :new.STG_PROCESSED_DATE := current_date;
end;
/
ALTER TRIGGER "MAXDAT"."TRG_R_CORP_ETL_MFB_ECN_STG" ENABLE;

Grant select on "MAXDAT"."CORP_ETL_MFB_ECN_STG"  to MAXDAT_READ_ONLY;

