ALTER TABLE CC_S_TMP_CISCO_A_SG_INTERVAL ADD (PRECISIONQUEUEID NUMBER);

ALTER TABLE CC_S_TMP_AGENT_SKILL_GROUP ADD (PRECISIONQUEUEID NUMBER);

ALTER TABLE CC_S_TMP_TERMINATN_CALL_DETAIL ADD (PRECISIONQUEUEID NUMBER);
