SET DEFINE OFF;
 
update cc_a_list_lkup
set out_var = '5000,5001'
where name = 'Default_Skill_Groups';

commit; 

delete from cc_c_filter
where filter_type = 'ACD_SKILL_GROUP_INC';

commit;

insert into cc_c_filter (filter_type, value) values ('ACD_DEFAULT_SKILL_GROUP_INC', 5000);
insert into cc_c_filter (filter_type, value) values ('ACD_DEFAULT_SKILL_GROUP_INC', 5001);

commit;

insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5001 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5004 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5005 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5006 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5007 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5008 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5009 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5010 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5011 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5012 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5013 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5014 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5015 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5016 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5017 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5018 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5019 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5020 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5021 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5022 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5023 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5024 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5027 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5028 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5029 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5030 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5031 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5032 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5033 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5034 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5035 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5036 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5037 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5038 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5047 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5048 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5049 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5050 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5051 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5052 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5053 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5054 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5055 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5056 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5057 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5058 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5059 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5060 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5061 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5062 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5063 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5064 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5065 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5066 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5067 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5068 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5073 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5074 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5075 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5076 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5077 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5078 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5079 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5080 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5081 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5082 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5083 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5084 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5085 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5086 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5087 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5088 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5089 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5090 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5091 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5092 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5093 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5094 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5095 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5096 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5097 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5098 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5099 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5100 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5101 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5102 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5103 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5104 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5105 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5106 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5107 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5108 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5109 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5110 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5111 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5112 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5113 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5114 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5115 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5116 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5117 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5118 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5119 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5120 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5121 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5122 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5123 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5124 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5125 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5126 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5127 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5128 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5129 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5130 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5131 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5132 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5133 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5134 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5135 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5136 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5137 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5138 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5139 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5140 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5141 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5142 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5143 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5144 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5145 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5146 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5147 );
insert into cc_c_filter (filter_type, value) values ('ACD_PQ_ID_INC',5148 );


insert into cc_c_filter (filter_type, value) values ('ACD_SKILL_GROUP_INC',5353);
insert into cc_c_filter (filter_type, value) values ('ACD_SKILL_GROUP_INC',5354);
insert into cc_c_filter (filter_type, value) values ('ACD_SKILL_GROUP_INC',8323);

commit;

delete from cc_c_lookup
where lookup_type in ('ACD_SKILLSET_PROJECT', 'ACD_SKILLSET_PROGRAM');

commit;

insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5116 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5010 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5018 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5056 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5057 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5012 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5019 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5008 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5020 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5011 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5021 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5009 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5022 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5132 ,'DC PDMS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5133 ,'DC PDMS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5134 ,'DC PDMS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5135 ,'DC PDMS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5136 ,'DC PDMS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5118 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5119 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5120 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5121 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5145 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5146 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5122 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5123 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5124 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5125 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5126 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5127 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5147 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5128 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5129 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5130 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5131 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5148 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5143 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5144 ,'GA IES' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5141 ,'IDHW E&T' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5142 ,'IDHW E&T' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5028 ,'KSLW' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5032 ,'KSLW' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5027 ,'KSLW' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5031 ,'KSLW' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5029 ,'KSLW' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5079 ,'KSLW' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5050 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5053 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5096 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5047 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5048 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5049 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5097 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5098 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5099 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5100 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5101 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5102 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5103 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5051 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5052 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5104 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5105 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5106 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5107 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5108 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5109 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5117 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5007 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5016 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5058 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5059 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5006 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5017 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5001 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5013 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5023 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5024 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5030 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5005 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5015 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5004 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5014 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5061 ,'MD EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5063 ,'MD EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5062 ,'MD EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5060 ,'MD EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5065 ,'MD EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5067 ,'MD EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5066 ,'MD EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5064 ,'MD EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5113 ,'MI APCC' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5114 ,'MI APCC' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5115 ,'MI APCC' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5035 ,'MIEB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5033 ,'MIEB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5037 ,'MIEB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5036 ,'MIEB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5038 ,'MIEB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5034 ,'MIEB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5073 ,'MI PACC' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5074 ,'MI PACC' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5076 ,'MI PACC' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5077 ,'MI PACC' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5075 ,'MI PACC' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5068 ,'WC HS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5054 ,'MAXIMUS IT' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5055 ,'MAXIMUS IT' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5110 ,'MO CS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5111 ,'MO CS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5112 ,'MO CS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5080 ,'NEPE' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5137 ,'TN 11' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5138 ,'TN 11' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5139 ,'TN 11' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5140 ,'TN 11' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5086 ,'CLCS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5085 ,'CLCS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5084 ,'CLCS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5078 ,'TNCS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5083 ,'TN NewHire' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5082 ,'TN NewHire' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5081 ,'TN NewHire' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5091 ,'VA EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5092 ,'VA EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5093 ,'VA EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5094 ,'VA EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5095 ,'VA EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5089 ,'WV EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5087 ,'WV EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5088 ,'WV EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROJECT',5090 ,'WV EB' );

insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_SKILLSET_PROJECT',5353 ,'KSLW' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_SKILLSET_PROJECT',5354 ,'KSLW' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_SKILLSET_PROJECT',8323 ,'WC HS' );

commit;

insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5116 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5010 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5018 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5056 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5057 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5012 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5019 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5008 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5020 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5011 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5021 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5009 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5022 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5132 ,'Provider Support' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5133 ,'Provider Support' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5134 ,'Provider Support' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5135 ,'Provider Support' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5136 ,'Provider Support' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5118 ,'GA Healthy Babies' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5119 ,'GA Healthy Babies' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5120 ,'GA Healthy Babies' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5121 ,'GA Healthy Babies' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5145 ,'GA Healthy Babies' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5146 ,'GA Healthy Babies' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5122 ,'GA Help Desk' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5123 ,'GA Help Desk' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5124 ,'GA Help Desk' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5125 ,'GA Help Desk' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5126 ,'GA Help Desk' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5127 ,'GA PeachCare CHIP' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5147 ,'GA PeachCare CHIP' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5128 ,'GA PeachCare CHIP' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5129 ,'GA PeachCare CHIP' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5130 ,'GA PeachCare CHIP' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5131 ,'GA PeachCare CHIP' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5148 ,'GA PeachCare CHIP' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5143 ,'GA PeachCare CHIP' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5144 ,'GA PeachCare CHIP' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5141 ,'Idaho Employment & Training Services' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5142 ,'Idaho Employment & Training Services' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5028 ,'KSLW' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5032 ,'KSLW' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5027 ,'KSLW' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5031 ,'KSLW' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5029 ,'KSLW' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5079 ,'KSLW' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5050 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5053 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5096 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5047 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5048 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5049 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5097 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5098 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5099 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5100 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5101 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5102 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5103 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5051 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5052 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5104 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5105 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5106 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5107 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5108 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5109 ,'KS CH' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5117 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5007 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5016 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5058 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5059 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5006 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5017 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5001 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5013 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5023 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5024 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5030 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5005 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5015 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5004 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5014 ,'MD HIX' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5061 ,'MD EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5063 ,'MD EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5062 ,'MD EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5060 ,'MD EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5065 ,'MD EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5067 ,'MD EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5066 ,'MD EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5064 ,'MD EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5113 ,'MI Provider Support' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5114 ,'MI Provider Support' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5115 ,'MI Provider Support' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5035 ,'MIEB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5033 ,'MIEB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5037 ,'MIEB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5036 ,'MIEB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5038 ,'MIEB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5034 ,'MIEB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5073 ,'MI PACC' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5074 ,'MI PACC' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5076 ,'MI PACC' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5077 ,'MI PACC' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5075 ,'MI PACC' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5068 ,'WC HS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5054 ,'Help Desk' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5055 ,'Help Desk' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5110 ,'MO Child Support' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5111 ,'MO Child Support' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5112 ,'MO Child Support' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5080 ,'NEPE' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5137 ,'Child Support' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5138 ,'Child Support' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5139 ,'Child Support' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5140 ,'Child Support' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5086 ,'CLCS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5085 ,'CLCS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5084 ,'CLCS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5078 ,'TNCS' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5083 ,'TN NewHire' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5082 ,'TN NewHire' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5081 ,'TN NewHire' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5091 ,'VA EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5092 ,'VA EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5093 ,'VA EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5094 ,'VA EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5095 ,'VA EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5089 ,'WV EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5087 ,'WV EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5088 ,'WV EB' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_PQ_PROGRAM',5090 ,'WV EB' );

insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_SKILLSET_PROGRAM',5353 ,'KSLW' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_SKILLSET_PROGRAM',5354 ,'KSLW' );
insert into cc_c_lookup (lookup_type, lookup_key, lookup_value) values ('ACD_SKILLSET_PROGRAM',8323 ,'WC HS' );

commit;
