
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='EEV English' WHERE QUEUE_NUMBER=10012;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='EEV Spanish' WHERE QUEUE_NUMBER=10013;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='EEV English' WHERE QUEUE_NUMBER=10014;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='EEV Spanish' WHERE QUEUE_NUMBER=10015;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='EEV Spanish' WHERE QUEUE_NUMBER=10020;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='EEV English' WHERE QUEUE_NUMBER=10021;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='CES English' WHERE QUEUE_NUMBER=10039;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='CES Spanish' WHERE QUEUE_NUMBER=10040;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='VMC English' WHERE QUEUE_NUMBER=10041;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='VMC Spanish' WHERE QUEUE_NUMBER=10042;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='ICP English' WHERE QUEUE_NUMBER=10043;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='ICP Spanish' WHERE QUEUE_NUMBER=10044;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='Health Connect English' WHERE QUEUE_NUMBER=10045;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='Health Connect Spanish' WHERE QUEUE_NUMBER=10046;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='General English' WHERE QUEUE_NUMBER=10047;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='General Spanish' WHERE QUEUE_NUMBER=10048;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Outbound', UNIT_OF_WORK_NAME='VMC English' WHERE QUEUE_NUMBER=10049;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Outbound', UNIT_OF_WORK_NAME='Health Connect Spanish' WHERE QUEUE_NUMBER=10050;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Outbound', UNIT_OF_WORK_NAME='ICP English' WHERE QUEUE_NUMBER=10051;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Outbound', UNIT_OF_WORK_NAME='ICP Spanish' WHERE QUEUE_NUMBER=10052;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Outbound', UNIT_OF_WORK_NAME='Health Connect English' WHERE QUEUE_NUMBER=10053;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Outbound', UNIT_OF_WORK_NAME='VMC Spanish' WHERE QUEUE_NUMBER=10054;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='MMAI English' WHERE QUEUE_NUMBER=10066;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Outbound', UNIT_OF_WORK_NAME='MMAI English' WHERE QUEUE_NUMBER=10067;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Outbound', UNIT_OF_WORK_NAME='MMAI Spanish' WHERE QUEUE_NUMBER=10068;
UPDATE CC_C_CONTACT_QUEUE SET QUEUE_TYPE='Inbound', UNIT_OF_WORK_NAME='MMAI Spanish' WHERE QUEUE_NUMBER=10069;

INSERT INTO CC_L_PATCH_LOG (PATCH_VERSION, SCRIPT_SEQUENCE, SCRIPT_NAME)
	VALUES ('0.3.1.3',102,'102_UPDATE_CC_C_CONTACT_QUEUE');

COMMIT;
