
ALTER TABLE CC_S_ACD_INTERVAL_PERIOD DROP CONSTRAINT SYS_C0011008;

INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME)
VALUES ('0.1','002','002_ALTER_CC_S_ACD_INTERVAL_PERIOD');

COMMIT;