--MAXDAT-3473

ALTER SESSION SET CURRENT_SCHEMA = FOLSOM_SHARED_CC;

ALTER TABLE CC_S_ACD_INTERVAL ADD (MAX_CALLS_QUEUED NUMBER (7));

ALTER TABLE CC_S_ACD_QUEUE_INTERVAL ADD (MAX_CALLS_QUEUED NUMBER (7));

ALTER TABLE CC_F_ACTUALS_QUEUE_INTERVAL ADD (MAX_CALLS_QUEUED NUMBER (7));

ALTER TABLE CC_F_ACD_QUEUE_INTERVAL ADD (MAX_CALLS_QUEUED NUMBER (7));

ALTER TABLE CC_S_ACD_INTERVAL MODIFY CALLS_ON_HOLD NULL;

ALTER TABLE CC_S_ACD_INTERVAL MODIFY(CALLS_ON_HOLD DEFAULT (null));

ALTER TABLE CC_S_ACD_QUEUE_INTERVAL MODIFY CALLS_ON_HOLD NULL;

ALTER TABLE CC_S_ACD_QUEUE_INTERVAL MODIFY(CALLS_ON_HOLD DEFAULT (null));

ALTER TABLE CC_F_ACTUALS_QUEUE_INTERVAL MODIFY CALLS_ON_HOLD NULL;

ALTER TABLE CC_F_ACTUALS_QUEUE_INTERVAL MODIFY(CALLS_ON_HOLD DEFAULT (null));

ALTER TABLE CC_F_ACD_QUEUE_INTERVAL MODIFY CALLS_ON_HOLD NULL;

ALTER TABLE CC_F_ACD_QUEUE_INTERVAL MODIFY(CALLS_ON_HOLD DEFAULT (null));

UPDATE CC_S_ACD_INTERVAL
SET CALLS_ON_HOLD = NULL
WHERE CALLS_ON_HOLD = 0;

UPDATE CC_S_ACD_QUEUE_INTERVAL
SET CALLS_ON_HOLD =  NULL
WHERE CALLS_ON_HOLD = 0;

UPDATE CC_F_ACTUALS_QUEUE_INTERVAL
SET CALLS_ON_HOLD =  NULL
WHERE CALLS_ON_HOLD = 0;

UPDATE CC_F_ACD_QUEUE_INTERVAL
SET CALLS_ON_HOLD =  NULL
WHERE CALLS_ON_HOLD = 0;

commit;