-- TODO: Set WHEN_POPULATED to correct values when defined in workbook.

insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (141,131,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (142,132,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (143,133,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (144,134,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (145,135,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (146,136,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (147,137,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (148,138,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (149,139,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (150,140,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (151,141,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (152,142,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (153,143,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (154,144,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (155,145,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (156,146,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (157,147,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (158,148,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (159,149,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (160,150,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (161,151,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (162,152,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (163,153,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (164,154,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (165,155,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (166,156,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (167,157,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (168,158,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (169,159,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (170,160,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (171,161,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (172,162,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (173,163,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (174,164,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (175,165,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (176,166,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (177,167,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (178,168,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (179,169,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (180,170,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (181,171,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (182,172,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (183,173,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (184,174,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (185,175,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (186,176,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (187,177,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (188,178,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (189,179,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (190,180,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (191,181,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (192,182,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (193,183,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (194,184,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (195,185,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (196,186,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (197,187,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (198,188,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (199,189,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (200,190,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (201,191,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (202,192,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (203,193,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (204,194,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (205,195,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (206,196,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (207,197,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (208,198,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (209,199,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (210,200,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));

insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (211,40,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (212,60,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));

insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (213,147,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (214,131,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (215,136,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (216,146,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));

insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (217,176,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (218,157,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (219,168,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
insert into BPM_ATTRIBUTE (BA_ID,BAL_ID,BEM_ID,WHEN_POPULATED,EFFECTIVE_DATE,END_DATE) 
values (220,146,3,'BOTH',sysdate,to_date('20770707','YYYYMMDD'));
