
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "MAXDAT"."D_NYHIX_MFD_DOC_RESCAN_SV" ("RESCAN_DATA_INFO_ID", "RESCAN_IND", "DOCUMENT_SET_ID", "CREATED_TS", "UPDATED_TS", "RESCAN_REQ_DATE", "DESCRIPTION", "ECN", "DCN") AS 
  select rdi.RESCAN_DATA_INFO_ID,
rdi.RESCAN_IND,
rdi.DOCUMENT_SET_ID,
trunc(rdi.CREATED_TS) CREATED_TS,
rdi.UPDATED_TS,
rdi.RESCAN_REQ_DATE,
err.description,
mfd.ECN,
mfd.DCN
from maxdat.RESCAN_DATA_INFO rdi
inner join RESCAN_DATA_REASON rdr on rdi.RESCAN_DATA_INFO_ID = rdr. RESCAN_DATA_INFO_ID
inner Join ENUM_RESCAN_REASONS err on rdr.RESCAN_REASON = err.value
INNER join D_NYHIX_MFD_CURRENT_SV mfd on rdi.document_set_id = mfd.document_set_id;


  GRANT SELECT ON "MAXDAT"."D_NYHIX_MFD_DOC_RESCAN_SV" TO "MAXDAT_READ_ONLY";
  GRANT DELETE ON "MAXDAT"."D_NYHIX_MFD_DOC_RESCAN_SV" TO "MAXDAT_OLTP_SIUD";
  GRANT INSERT ON "MAXDAT"."D_NYHIX_MFD_DOC_RESCAN_SV" TO "MAXDAT_OLTP_SIUD";
  GRANT SELECT ON "MAXDAT"."D_NYHIX_MFD_DOC_RESCAN_SV" TO "MAXDAT_OLTP_SIUD";
  GRANT UPDATE ON "MAXDAT"."D_NYHIX_MFD_DOC_RESCAN_SV" TO "MAXDAT_OLTP_SIUD";
  GRANT INSERT ON "MAXDAT"."D_NYHIX_MFD_DOC_RESCAN_SV" TO "MAXDAT_OLTP_SIU";
  GRANT SELECT ON "MAXDAT"."D_NYHIX_MFD_DOC_RESCAN_SV" TO "MAXDAT_OLTP_SIU";
  GRANT UPDATE ON "MAXDAT"."D_NYHIX_MFD_DOC_RESCAN_SV" TO "MAXDAT_OLTP_SIU";