CREATE OR REPLACE VIEW D_PI_REPORTED_BY_SV
AS
  SELECT r.value REPORTED_BY_CODE,
    r.report_label REPORTED_BY
  FROM ats.enum_reporter_type r
  UNION ALL
  SELECT '0' REPORTED_BY_CODE,
    NULL REPORTED_BY
  FROM DUAL;
  
  GRANT SELECT ON MAXDAT_SUPPORT.D_PI_REPORTED_BY_SV TO MAXDAT_REPORTS ; 