CREATE OR REPLACE VIEW D_PI_PLAN_SV
AS
  SELECT pl.plan_id source_record_id,
    pl.plan_id_ext,
    pl.created_by record_name,
    pl.plan_id,
    'MEDICAID' managed_care_program,
    '0' csda,
    pl.plan_code,
    pl.plan_name,
    NULL plan_abbreviation,
    NULL plan_effective_date,
    NULL address1,
    NULL address2,
    NULL city,
    NULL state,
    NULL zip,
    'N' active,
    NULL contact_first_name,
    NULL contact_initial,
    NULL contact_last_name,
    NULL contact_full_name,
    NULL contact_phone,
    NULL contact_extension,
    NULL member_contact_phone, --contact info
    'N' enrollok,
    'N' plan_assign,
    pl.create_ts record_date,
    TO_CHAR(pl.create_ts,'HH24MI') record_time,
    NULL plan_type_id,
    NULL plan_type,
    NULL plan_service_type
  FROM ATS.plans pl 
UNION
  SELECT 0 source_record_id,
    '0' AS plan_id_ext,
    NULL record_name,
    0 plan_id,
    'MEDICAID' managed_care_program,
    '0' csda,
    '0' plan_code,
    'Not Defined' plan_name,
    'Not Defined' plan_abbreviation,
    TO_DATE('01/01/1900','MM/DD/YYYY') plan_effective_date,
    NULL address1,
    NULL address2,
    NULL city,
    NULL state,
    NULL zip,
     'N'  active,
    NULL contact_first_name,
    NULL contact_initial,
    NULL contact_last_name,
    NULL contact_full_name,
    NULL contact_phone,
    NULL contact_extension,
    NULL member_contact_phone, --contact info
    'N' enrollok,
    'N' plan_assign,
    NULL record_date,
    NULL record_time,
    NULL plan_type_id,
    NULL plan_type,
    NULL plan_service_type
 FROM DUAL;
  
  GRANT SELECT ON MAXDAT_SUPPORT.D_PI_PLAN_SV TO MAXDAT_REPORTS; 