--------------------------------------------------------
--  DDL for Index CLIENTENRLPK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIENTENRLPK" ON "EMRS_D_CLIENT_PLAN_ENRL_STATUS" ("CLIENT_ENROLL_STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_INDX" ;

  CREATE INDEX IDX1_CLIENTENRL ON EMRS_D_CLIENT_PLAN_ENRL_STATUS(client_number) TABLESPACE MAXDAT_INDX;  

  CREATE INDEX IDX2_CLIENTENRL ON emrs_d_client_plan_enrl_status(client_number, plan_type_id) TABLESPACE MAXDAT_INDX;           

  CREATE INDEX IDX3_CLIENTENRL ON emrs_d_client_plan_enrl_status(date_created) TABLESPACE MAXDAT_INDX;           

  CREATE INDEX IDX4_CLIENTENRL ON emrs_d_client_plan_enrl_status(source_record_id) TABLESPACE MAXDAT_INDX;           