--------------------------------------------------------
--  DDL for Table EMRS_D_TERMINATION_REASON
--------------------------------------------------------

  CREATE TABLE "EMRS_D_TERMINATION_REASON" 
   (	"TERM_REASON_CODE_ID" NUMBER(*,0), 
	"MANAGED_CARE_PROGRAM" VARCHAR2(30), 
	"PLAN_NAME" VARCHAR2(25), 
	"REASON_CODE" VARCHAR2(50), 
	"REASON" VARCHAR2(240), 
	"SOURCE_RECORD_ID" NUMBER(22,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_DATA" ;

   COMMENT ON COLUMN "EMRS_D_TERMINATION_REASON"."TERM_REASON_CODE_ID" IS 'Term Reason Code ID (PK)';
   COMMENT ON COLUMN "EMRS_D_TERMINATION_REASON"."MANAGED_CARE_PROGRAM" IS 'Managed Care Program';
   COMMENT ON COLUMN "EMRS_D_TERMINATION_REASON"."PLAN_NAME" IS 'Plan Type Name (that Reason belongs to)';
   COMMENT ON COLUMN "EMRS_D_TERMINATION_REASON"."REASON_CODE" IS 'Reason Code';
   COMMENT ON COLUMN "EMRS_D_TERMINATION_REASON"."REASON" IS 'Term Reason';
