--------------------------------------------------------
--  Ref Constraints for Table EMRS_D_SELECTION_TRANS_HISTORY
--------------------------------------------------------

  ALTER TABLE "EMRS_D_SELECTION_TRANS_HISTORY" ADD CONSTRAINT "SLCTTRANSHIST_SLCTMI_FK" FOREIGN KEY ("SELECTION_STATUS_ID")
	  REFERENCES "EMRS_D_SELECTION_STATUS" ("SELECTION_STATUS_ID") ENABLE;
  ALTER TABLE "EMRS_D_SELECTION_TRANS_HISTORY" ADD CONSTRAINT "SLCTTRANSHIST_SLCTTRANS_FK" FOREIGN KEY ("SELECTION_TRANSACTION_ID")
	  REFERENCES "EMRS_D_SELECTION_TRANSACTION" ("SELECTION_TRANSACTION_ID") ENABLE;
