--------------------------------------------------------
--  Constraints for Table EMRS_D_SELECTION_SOURCE
--------------------------------------------------------

  ALTER TABLE "EMRS_D_SELECTION_SOURCE" ADD CONSTRAINT "SLCTSOURCE_COMB_UK" UNIQUE ("MANAGED_CARE_PROGRAM", "SELECTION_SOURCE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_INDX"  ENABLE;
  ALTER TABLE "EMRS_D_SELECTION_SOURCE" ADD CONSTRAINT "SLCTSOURCEPK" PRIMARY KEY ("SELECTION_SOURCE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_INDX"  ENABLE;
  ALTER TABLE "EMRS_D_SELECTION_SOURCE" MODIFY ("SELECTION_SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "EMRS_D_SELECTION_SOURCE" MODIFY ("SELECTION_SOURCE_CODE" NOT NULL ENABLE);
  ALTER TABLE "EMRS_D_SELECTION_SOURCE" MODIFY ("SELECTION_SOURCE" NOT NULL ENABLE);
  ALTER TABLE "EMRS_D_SELECTION_SOURCE" MODIFY ("MANAGED_CARE_PROGRAM" NOT NULL ENABLE);
