--------------------------------------------------------
--  DDL for Table EMRS_D_OTHER_CHIP_CODE
--------------------------------------------------------

  CREATE TABLE "EMRS_D_OTHER_CHIP_CODE" 
   (	"OTHER_CHIP_CODE_ID" NUMBER(30,0), 
	"OTHER_CHIP_CODE_TYPE" VARCHAR2(30), 
	"OTHER_CHIP_CODE" VARCHAR2(5), 
	"OTHER_CHIP_CODE_DESCRIPTION" VARCHAR2(100), 
	"MANAGED_CARE_PROGRAM" VARCHAR2(30), 
	"CREATED_BY" VARCHAR2(18), 
	"DATE_CREATED" DATE, 
	"UPDATED_BY" VARCHAR2(18), 
	"DATE_UPDATED" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MAXDAT_DATA" ;

   COMMENT ON COLUMN "EMRS_D_OTHER_CHIP_CODE"."OTHER_CHIP_CODE_ID" IS 'Other CHIP Codes ID (PK)';
   COMMENT ON COLUMN "EMRS_D_OTHER_CHIP_CODE"."OTHER_CHIP_CODE_TYPE" IS 'Category or Type of CHIP Code';
   COMMENT ON COLUMN "EMRS_D_OTHER_CHIP_CODE"."OTHER_CHIP_CODE" IS 'CHIP Code';
   COMMENT ON COLUMN "EMRS_D_OTHER_CHIP_CODE"."OTHER_CHIP_CODE_DESCRIPTION" IS 'CHIP Code Description';
   COMMENT ON COLUMN "EMRS_D_OTHER_CHIP_CODE"."MANAGED_CARE_PROGRAM" IS 'Managed Care Program';
   COMMENT ON COLUMN "EMRS_D_OTHER_CHIP_CODE"."CREATED_BY" IS 'Created By';
   COMMENT ON COLUMN "EMRS_D_OTHER_CHIP_CODE"."DATE_CREATED" IS 'Date Created';
   COMMENT ON COLUMN "EMRS_D_OTHER_CHIP_CODE"."UPDATED_BY" IS 'Updated By';
   COMMENT ON COLUMN "EMRS_D_OTHER_CHIP_CODE"."DATE_UPDATED" IS 'Date Updated';
