--------------------------------------------------------
--  DDL for Table EMRS_S_CLIENT_STG
--------------------------------------------------------

  CREATE TABLE "EMRS_S_CLIENT_STG" 
   (	"CLIENT_ID" NUMBER(*,0), 
	"CLIENT_NUMBER" NUMBER(11,0), 
	"MANAGED_CARE_PROGRAM" VARCHAR2(50), 
	"FULL_NAME" VARCHAR2(80), 
	"FIRST_NAME" VARCHAR2(30), 
	"MIDDLE_INITIAL" VARCHAR2(1), 
	"LAST_NAME" VARCHAR2(30), 
	"COVERAGE_TYPE" VARCHAR2(2), 
	"ENROLLMENT_STATUS" VARCHAR2(1), 
	"TRANSACTION_HOLD" VARCHAR2(1), 
	"MANAGED_CARE_CANDIDATE" VARCHAR2(1), 
	"BASE_PLAN" VARCHAR2(32), 
	"RACE" VARCHAR2(30), 
	"SEX" VARCHAR2(1), 
	"DATE_OF_BIRTH" DATE, 
	"PHONE" VARCHAR2(12), 
	"SOCIAL_SECURITY_NUMBER" VARCHAR2(11), 
	"ADD1" VARCHAR2(55), 
	"ADD2" VARCHAR2(55), 
	"CITY" VARCHAR2(30), 
	"ST" VARCHAR2(2), 
	"ZIP" VARCHAR2(9), 
	"COUNTY" VARCHAR2(3), 
	"SSN_RAILROAD_CLAIM_NUMBER" VARCHAR2(12), 
	"RECORD_DATE" DATE, 
	"RECORD_TIME" VARCHAR2(5), 
	"RECORD_NAME" VARCHAR2(80), 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_TIME" VARCHAR2(5), 
	"MODIFIED_NAME" VARCHAR2(80), 
	"VERSION" NUMBER(*,0), 
	"PREGNANT_MEMBER" VARCHAR2(1), 
	"NEWBORN" VARCHAR2(1), 
	"ADULT_OR_CHILD" VARCHAR2(1), 
	"THIRD_PARTY_RESOURCES_AVAIL" VARCHAR2(1), 
	"MIGRANT_WORKER_FLAG" VARCHAR2(1), 
	"MANAGED_VIA_GEN_REV_FLAG" VARCHAR2(1), 
	"MANAGED_VIA_STATE_FUND_FLAG" VARCHAR2(1), 
	"RECEIVING_TANF_FLAG" VARCHAR2(1), 
	"RECEIVING_SSI_FLAG" VARCHAR2(1), 
	"CLIENT_REPORTED_SHCN" VARCHAR2(1), 
	"PLAN_REPORTED_SHCN" VARCHAR2(1), 
	"DATE_OF_DEATH" DATE, 
	"DATE_OF_DEATH_SOURCE" VARCHAR2(30), 
	"SOURCE_RECORD_ID" NUMBER(22,0), 
	"CURRENT_CLIENT_ID" NUMBER(18,0), 
	"CLNT_CLNT_CLIENT_ID" NUMBER(18,0), 
	"CLNT_ETHNICITY" VARCHAR2(32), 
	"CLNT_TPL_PRESENT" VARCHAR2(1), 
	"CLNT_NATIONAL_ID" VARCHAR2(15), 
	"CLNT_FROM_PACMIS" VARCHAR2(1), 
	"CLNT_SHARE_PREMIUM" VARCHAR2(1), 
	"CLNT_NOT_BORN" VARCHAR2(1), 
	"CLNT_HIPAA_PRIVACY_IND" VARCHAR2(1), 
	"CLNT_FINET_VENDOR_NBR" VARCHAR2(10), 
	"CLNT_ENROLL_STATUS" VARCHAR2(32), 
	"CLNT_ENROLL_STATUS_DATE" DATE, 
	"SCHED_AUTO_ASSIGN_DATE" DATE, 
	"CLNT_CIN" VARCHAR2(30), 
	"CLNT_COMMENT" VARCHAR2(4000), 
	"CLNT_PSEUDO_ID" VARCHAR2(10), 
	"SSNVL_ID" NUMBER(38,0), 
	"NOTE_REF_ID" NUMBER(18,0), 
	"CLNT_MARITAL_CD" VARCHAR2(32), 
	"CLNT_STATUS_CD" VARCHAR2(32), 
	"CLNT_EXPECTED_DOB" DATE, 
	"CLNT_PREG_TERM_DATE" DATE, 
	"CLNT_PREG_TERM_REAS_CD" VARCHAR2(32), 
	"CLIENT_TYPE_CD" VARCHAR2(10), 
	"SUPPLEMENTAL_NBR" VARCHAR2(32), 
	"STATE_LANGUAGE" VARCHAR2(32), 
	"DO_NOT_CALL_IND" NUMBER(1,0), 
	"WRITTEN_LANGUAGE" VARCHAR2(32), 
	"SUFFIX" VARCHAR2(32), 
	"SALUTATION_CD" VARCHAR2(32), 
	"DOMESTIC_VIOLENCE_IND" NUMBER(1,0), 
	"ENGLISH_FLUENCY_CD" VARCHAR2(32), 
	"ENGLISH_LITERACY_CD" VARCHAR2(32), 
	"TRIBE_CD" VARCHAR2(32), 
	"CLNT_GENERIC_FIELD1_DATE" DATE, 
	"CLNT_GENERIC_FIELD2_DATE" DATE, 
	"CLNT_GENERIC_FIELD3_NUM" NUMBER(18,0), 
	"CLNT_GENERIC_FIELD4_NUM" NUMBER(18,0), 
	"CLNT_GENERIC_FIELD5_TXT" VARCHAR2(256), 
	"CLNT_GENERIC_FIELD6_TXT" VARCHAR2(256), 
	"CLNT_GENERIC_FIELD7_TXT" VARCHAR2(256), 
	"CLNT_GENERIC_FIELD8_TXT" VARCHAR2(256), 
	"CLNT_GENERIC_FIELD9_TXT" VARCHAR2(256), 
	"CLNT_GENERIC_FIELD10_TXT" VARCHAR2(256), 
	"CLNT_GENERIC_REF11_ID" NUMBER(18,0), 
	"CLNT_GENERIC_REF12_ID" NUMBER(18,0), 
	"DO_NOT_TEXT_IND" NUMBER(1,0), 
	"DO_NOT_EMAIL_IND" NUMBER(1,0), 
	"LAST_STATE_UPDATE_TS" DATE, 
	"LAST_STATE_UPDATED_BY" NUMBER(18,0), 
	"COMPARABLE_KEY" VARCHAR2(2000), 
	"UPD_CLIENT_ID" NUMBER(*,0), 
	"RECORD_STATUS" VARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_DATA" ;

--------------------------------------------------------
--  DDL for Index CLIENTSTG
--------------------------------------------------------

  CREATE INDEX "IDX1_CLIENTSTG" ON "EMRS_S_CLIENT_STG" ("CLIENT_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_INDX" ;

  CREATE INDEX "IDX2_CLIENTSTG" ON "EMRS_S_CLIENT_STG" ("RECORD_STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXDAT_INDX" ;
  
  CREATE OR REPLACE PUBLIC SYNONYM EMRS_S_CLIENT_STG FOR EMRS_S_CLIENT_STG;