--------------------------------------------------------
--  Constraints for Table EMRS_D_COMMUNICATION_TYPE
--------------------------------------------------------

  ALTER TABLE "EMRS_D_COMMUNICATION_TYPE" ADD CONSTRAINT "COMMTYP_CODEASSOC_UK" UNIQUE ("MANAGED_CARE_PROGRAM", "SOURCE_RECORD_ID", "COMMUNICATION_TYPE_CODE", "COMMUNICATION_TYPE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MAXDAT_INDX"  ENABLE;
  ALTER TABLE "EMRS_D_COMMUNICATION_TYPE" ADD CONSTRAINT "COMMTYP_PK" PRIMARY KEY ("COMMUNICATION_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MAXDAT_INDX"  ENABLE;
  ALTER TABLE "EMRS_D_COMMUNICATION_TYPE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "EMRS_D_COMMUNICATION_TYPE" MODIFY ("COMMUNICATION_TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "EMRS_D_COMMUNICATION_TYPE" MODIFY ("COMMUNICATION_TYPE_ID" NOT NULL ENABLE);
