--------------------------------------------------------
--  DDL for Table EMRS_F_ENROLLMENT
--------------------------------------------------------

  CREATE TABLE "EMRS_F_ENROLLMENT" 
   (	"ENROLLMENT_ID" NUMBER(*,0), 
	"CASE_ID" NUMBER(22,0), 
	"CHANGE_REASON_ID" NUMBER(22,0), 
	"CLIENT_ID" NUMBER(22,0), 
	"COMMUNICATION_TYPE_ID" NUMBER(22,0), 
	"COUNTY_ID" NUMBER(22,0), 
	"COVERAGE_CATEGORY_ID" NUMBER(22,0), 
	"CSDA_ID" NUMBER(22,0), 
	"DATE_PERIOD_ID" NUMBER(22,0), 
	"ENROLLMENT_ACTION_STATUS_ID" NUMBER(22,0), 
	"FPL_ID" NUMBER(22,0), 
	"LANGUAGE_CODE_ID" NUMBER(22,0), 
	"PLAN_ID" NUMBER(22,0), 
	"PROGRAM_ID" NUMBER(22,0), 
	"PROVIDER_ID" NUMBER(22,0), 
	"PROVIDER_TYPE_ID" NUMBER(22,0), 
	"RACE_ID" NUMBER(22,0), 
	"REJECTION_ERROR_REASON_ID" NUMBER(22,0), 
	"RISK_GROUP_ID" NUMBER(22,0), 
	"STAT_IN_GRP_ID" NUMBER(22,0), 
	"SUB_PROGRAM_ID" NUMBER(22,0), 
	"TERM_REASON_CODE_ID" NUMBER(22,0), 
	"TIME_PERIOD_ID" NUMBER(22,0), 
	"CERTIFICATION_DATE" DATE, 
	"CSDA_CHANGE_DATE" DATE, 
	"ENROLLMENT_STATUS_CHANGE_DATE" DATE, 
	"JYEAR_OF_LAST_ENROLLMENT_FORM" DATE, 
	"MANAGED_CARE_END_DATE" DATE, 
	"MANAGED_CARE_START_DATE" DATE, 
	"MEDICAID_BUY_IN_FEE" NUMBER(4,2), 
	"MEDICAID_BUY_IN_FEE_DATE" DATE, 
	"MEDICAID_RECERTIFICATION_DATE" DATE, 
	"NUMBER_COUNT" NUMBER, 
	"DATE_CREATED" DATE, 
	"CREATED_BY" VARCHAR2(18), 
	"UPDATED_BY" VARCHAR2(18), 
	"DATE_UPDATED" DATE, 
	"MET_COST_SHARE_CAP_DATE" DATE, 
	"COST_SHARE_START_DATE" DATE, 
	"COST_SHARE_END_DATE" DATE, 
	"ENROLLMENT_FEE_FREQUENCY" VARCHAR2(30), 
	"CHIP_ANNUAL_ENROLL_DATE" DATE, 
	"SELECTION_SOURCE_ID" NUMBER(22,0), 
	"SELECTION_REASON_ID" NUMBER(22,0), 
	"AID_CATEGORY_ID" NUMBER(22,0), 
	"CITIZENSHIP_ID" NUMBER(22,0), 
	"ENROLLMENT_GROUP_ID" NUMBER(22,0), 
	"SOURCE_RECORD_ID" NUMBER(22,0), 
	"PEOPLE_IN_FAMILY" NUMBER(22,2), 
	"ENROLLMENT_FEE_ASSESSED" NUMBER(22,4), 
	"ENROLLMENT_FEE_ASSESSED_DATE" DATE, 
	"ENROLLMENT_FEE_PAID" NUMBER(22,4), 
	"ENROLLMENT_FEE_PAID_DATE" DATE, 
	"CO_PAY_AMOUNT" NUMBER(22,3), 
	"SOURCE_TABLE_NAME" VARCHAR2(30), 
	"ELIGIBILITY_RECEIPT_DATE" DATE, 
	"CLIENT_NUMBER" NUMBER(22,0), 
	"CASE_NUMBER" NUMBER(22,0), 
	"PROVIDER_NUMBER" NUMBER(22,0),
  "PLAN_TYPE_ID" NUMBER(22,0),
  "FPL_PERCENTAGE" NUMBER(22,4)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MAXDAT_DATA" ;

   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."CASE_ID" IS 'Case ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."CHANGE_REASON_ID" IS 'Change Reason ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."CLIENT_ID" IS 'Client ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."COMMUNICATION_TYPE_ID" IS 'Communication Type ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."COUNTY_ID" IS 'County ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."COVERAGE_CATEGORY_ID" IS 'Coverage Category ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."CSDA_ID" IS 'CSDA ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."ENROLLMENT_ACTION_STATUS_ID" IS 'Enrollment Status ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."FPL_ID" IS ' Federal Poverty Level ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."LANGUAGE_CODE_ID" IS 'Language Code ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."PLAN_ID" IS 'Plan (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."PROGRAM_ID" IS 'Program Type ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."PROVIDER_ID" IS 'Provider Type ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."PROVIDER_TYPE_ID" IS 'Provider Type ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."RACE_ID" IS 'Race ID (SK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."REJECTION_ERROR_REASON_ID" IS 'Rejection Error Reason ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."RISK_GROUP_ID" IS 'Risk Group ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."STAT_IN_GRP_ID" IS 'Status in Group ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."SUB_PROGRAM_ID" IS 'Sub Program ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."TERM_REASON_CODE_ID" IS 'Term Reason Code ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."TIME_PERIOD_ID" IS 'Time Period ID (PK)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."CERTIFICATION_DATE" IS 'Certification Date';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."CSDA_CHANGE_DATE" IS 'Date CSDA Changed';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."ENROLLMENT_STATUS_CHANGE_DATE" IS 'Date Enrollment Status Changed';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."JYEAR_OF_LAST_ENROLLMENT_FORM" IS 'Year of Last Enrollment (Julian)';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."MANAGED_CARE_END_DATE" IS 'Managed Care End Date, Current';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."MANAGED_CARE_START_DATE" IS 'Managed Care Start Date, Current';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."MEDICAID_BUY_IN_FEE" IS 'Medicaid Buy-In Fee';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."MEDICAID_BUY_IN_FEE_DATE" IS 'Medicaid Buy-In Fee Date';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."MEDICAID_RECERTIFICATION_DATE" IS 'Medicaid Re-Certification Date';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."NUMBER_COUNT" IS 'Number Count';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."DATE_CREATED" IS 'Warehouse Load Creation Date';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."CREATED_BY" IS 'Warehouse Load Created By';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."UPDATED_BY" IS 'Warehouse Load Updated By';
   COMMENT ON COLUMN "EMRS_F_ENROLLMENT"."DATE_UPDATED" IS 'Warehouse Load Date Updated';
