--------------------------------------------------------
--  DDL for Table EMRS_D_ACTION_TYPE
--------------------------------------------------------

  CREATE TABLE "EMRS_D_ACTION_TYPE" 
   (	"ACTION_TYPE_ID" NUMBER(*,0), 
	"MANAGED_CARE_PROGRAM" VARCHAR2(50), 
	"ACTION_CATEGORY" VARCHAR2(10), 
	"ACTION_TYPE_NAME" VARCHAR2(50), 
	"ACTION_TYPE_DESCRIPTION" VARCHAR2(160), 
	"SOURCE_RECORD_ID" NUMBER(*,0), 
	"VERSION" NUMBER(2,0), 
	"DATE_OF_VALIDITY_START" DATE, 
	"DATE_OF_VALIDITY_END" DATE, 
	"CREATED_BY" VARCHAR2(18), 
	"DATE_CREATED" DATE, 
	"UPDATED_BY" VARCHAR2(18), 
	"DATE_UPDATED" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MAXDAT_DATA" ;

   COMMENT ON COLUMN "EMRS_D_ACTION_TYPE"."ACTION_TYPE_ID" IS 'Outreach Action Type ID (PK)';
   COMMENT ON COLUMN "EMRS_D_ACTION_TYPE"."MANAGED_CARE_PROGRAM" IS 'Managed Care Program that Uses This Action Type';
   COMMENT ON COLUMN "EMRS_D_ACTION_TYPE"."ACTION_CATEGORY" IS 'Outreach Action Type Category';
   COMMENT ON COLUMN "EMRS_D_ACTION_TYPE"."ACTION_TYPE_NAME" IS 'Outreach Action Type Name';
   COMMENT ON COLUMN "EMRS_D_ACTION_TYPE"."ACTION_TYPE_DESCRIPTION" IS 'Outreach Action Type Description';
   COMMENT ON COLUMN "EMRS_D_ACTION_TYPE"."SOURCE_RECORD_ID" IS 'Source-System Primary-Key Record ID #';
   COMMENT ON COLUMN "EMRS_D_ACTION_TYPE"."VERSION" IS 'Type-2 SCD Version Number';
   COMMENT ON COLUMN "EMRS_D_ACTION_TYPE"."DATE_OF_VALIDITY_START" IS 'ETL Required Column to Designate the Start-Date for a Valid Slowly Changing Dimension (SCD) Record';
   COMMENT ON COLUMN "EMRS_D_ACTION_TYPE"."DATE_OF_VALIDITY_END" IS 'ETL Required Column to Designate the End-Date for a Valid Slowly Changing Dimension (SCD) Record';
   COMMENT ON COLUMN "EMRS_D_ACTION_TYPE"."CREATED_BY" IS 'Warehouse Load Created By';
   COMMENT ON COLUMN "EMRS_D_ACTION_TYPE"."DATE_CREATED" IS 'Warehouse Load Creation Date';
   COMMENT ON COLUMN "EMRS_D_ACTION_TYPE"."UPDATED_BY" IS 'Warehouse Load Updated By';
   COMMENT ON COLUMN "EMRS_D_ACTION_TYPE"."DATE_UPDATED" IS 'Warehouse Load Date Updated';