--------------------------------------------------------
--  DDL for Table EMRS_D_DATE_PERIOD
--------------------------------------------------------

  CREATE TABLE "EMRS_D_DATE_PERIOD" 
   (	"DATE_PERIOD_ID" NUMBER, 
	"DATE_FULL" VARCHAR2(18), 
	"DATE_STANDARD_1" VARCHAR2(11), 
	"DATE_STANDARD_2" VARCHAR2(10), 
	"DATE_STANDARD_3" NUMBER(8,0), 
	"DATE_STANDARD_4" DATE, 
	"DAY_OF_WEEK" VARCHAR2(9), 
	"MONTH_NAME" VARCHAR2(9), 
	"SEASON" VARCHAR2(6), 
	"QUARTER" VARCHAR2(20), 
	"LAST_DAY_IN_MONTH_IND" VARCHAR2(1), 
	"LAST_DAY_IN_WEEK_IND" VARCHAR2(1), 
	"HOLIDAY_IND" VARCHAR2(35), 
	"WEEKDAY_IND" VARCHAR2(8), 
	"MAJOR_EVENT" VARCHAR2(80), 
	"WEEK_ENDING_DATE" DATE, 
	"DAY_NUMBER_IN_MONTH" VARCHAR2(4), 
	"DAY_NUMBER_IN_WEEK" VARCHAR2(1), 
	"DAY_NUMBER_IN_YEAR" VARCHAR2(5), 
	"FISCAL_HALF_YEAR" VARCHAR2(15), 
	"FISCAL_MONTH_NUM_IN_YEAR" NUMBER(2,0), 
	"FISCAL_QUARTER" VARCHAR2(18), 
	"FISCAL_WEEK" NUMBER(2,0), 
	"FISCAL_YEAR" VARCHAR2(4), 
	"FISCAL_YEAR_DAY_NUMBER" NUMBER(3,0), 
	"FISCAL_YEAR_MONTH" VARCHAR2(8), 
	"FISCAL_YEAR_QUARTER" VARCHAR2(13), 
	"MONTH_NUMBER_IN_YEAR" NUMBER(2,0), 
	"WEEK_NUMBER_IN_YEAR" NUMBER(2,0), 
	"YEAR_YYYY" VARCHAR2(4), 
	"YEAR_HALF" VARCHAR2(8), 
	"YEAR_MONTH" VARCHAR2(7), 
	"YEAR_QUARTER" VARCHAR2(13), 
	"VERSION" NUMBER(2,0), 
	"DATE_OF_VALIDITY_START" DATE, 
	"DATE_OF_VALIDITY_END" DATE, 
	"CREATED_BY" VARCHAR2(18), 
	"DATE_CREATED" DATE, 
	"UPDATED_BY" VARCHAR2(18), 
	"DATE_UPDATED" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MAXDAT_DATA" ;

   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."DATE_PERIOD_ID" IS 'Date Period ID (PK)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."DATE_FULL" IS 'Full Date Format (December 30, 2035)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."DATE_STANDARD_1" IS '1st Standard Date Format (31-Dec-2035)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."DATE_STANDARD_2" IS '2nd Standard Date Format (12;31;2035)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."DATE_STANDARD_3" IS '3nd Standard Date Format (20351231)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."DATE_STANDARD_4" IS '4nd Standard Date Format (31-DEC-2035)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."DAY_OF_WEEK" IS 'Day of Week (Monday)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."MONTH_NAME" IS 'Month Name (December)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."SEASON" IS 'Season of the Year (Winter)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."QUARTER" IS 'Calendar Year Quarter (Calendar 4th Quarter)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."LAST_DAY_IN_MONTH_IND" IS 'Last Day in Month Indicator (Y;N)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."LAST_DAY_IN_WEEK_IND" IS 'Last Day in Week Indicator (Y;N)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."HOLIDAY_IND" IS 'Updatable Field';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."WEEKDAY_IND" IS 'Weekday Indicator (Week-Day;Week-End)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."MAJOR_EVENT" IS 'Updatable Field';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."WEEK_ENDING_DATE" IS 'Week Ending Date (05-JAN-2036)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."DAY_NUMBER_IN_MONTH" IS 'Day Number in Month (31)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."DAY_NUMBER_IN_WEEK" IS 'Day Number in Week (2)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."DAY_NUMBER_IN_YEAR" IS 'Day Number in Year (365)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."FISCAL_HALF_YEAR" IS 'Fiscal Half-Year (Fiscal 1st-Half)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."FISCAL_MONTH_NUM_IN_YEAR" IS 'Fiscal Month Number in Year (4)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."FISCAL_QUARTER" IS 'Fiscal Quarter (Fiscal 2nd Quarter)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."FISCAL_WEEK" IS 'Fiscal Week (18)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."FISCAL_YEAR" IS 'Fiscal Year (2036)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."FISCAL_YEAR_DAY_NUMBER" IS 'Fiscal Year Day Number (122)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."FISCAL_YEAR_MONTH" IS 'Fiscal Year Month (F2036-4)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."FISCAL_YEAR_QUARTER" IS 'Fiscal Year Quarter (F2036-2nd Qtr)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."MONTH_NUMBER_IN_YEAR" IS 'Month Number in Year (12)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."WEEK_NUMBER_IN_YEAR" IS 'Week Number in Year (12)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."YEAR_YYYY" IS 'Year (2035)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."YEAR_HALF" IS 'Year Half (2nd Half)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."YEAR_MONTH" IS 'Year Month (2035-12)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."YEAR_QUARTER" IS 'Year Quarter (2035-4th Qtr)';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."VERSION" IS 'Type-2 SCD Version Number';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."DATE_OF_VALIDITY_START" IS 'ETL Required Column to Designate the Start-Date for a Valid Slowly Changing Dimension (SCD) Record';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."DATE_OF_VALIDITY_END" IS 'ETL Required Column to Designate the End-Date for a Valid Slowly Changing Dimension (SCD) Record';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."CREATED_BY" IS 'Created By';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."DATE_CREATED" IS 'Date Created';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."UPDATED_BY" IS 'Updated By';
   COMMENT ON COLUMN "EMRS_D_DATE_PERIOD"."DATE_UPDATED" IS 'Date Updated';
