UPDATE CC_D_INTERVAL 
SET 
  INTERVAL_START_DATE = TO_DATE('1900/01/01', 'YYYY/MM/DD')
  , INTERVAL_END_DATE = TO_DATE('2999/12/31', 'YYYY/MM/DD')
WHERE D_INTERVAL_ID =  0;


insert into cc_l_patch_log (PATCH_VERSION, SCRIPT_SEQUENCE, SCRIPT_NAME)
values ('2.4',010,'010_UPDATE_UNKNOWN_INTERVAL');

commit;

