CREATE INDEX CC_F_AGT_RTG_GRP_INTVL_IDX4 ON CC_F_AGENT_RTG_GRP_INTERVAL
   (
     AGENT_ROUTING_GROUP_NUMBER
   )
TABLESPACE MAXDAT_INDX LOGGING ;   
   
CREATE INDEX CC_F_AGT_RTG_GRP_INTVL_IDX5 ON CC_F_AGENT_RTG_GRP_INTERVAL
   (
     AGENT_ROUTING_GROUP_TYPE
   )
TABLESPACE MAXDAT_INDX LOGGING ; 