ALTER SESSION SET CURRENT_SCHEMA = MAXDAT_PRODUCT_CC;

-- WILL PROVIDE THE SCHEMA NAME IN THE MAXDAT TICKET, SO NOT GIVING ALTER SESSION STATEMENT HERE
-- SINCE INDEXES AND TRIGGERS ARE DROPPED AUTOMATICALLY WHEN A TABLE IS DROPPED, NO EXPLICIT STATEMENTS ARE GIVEN FOR DROPPING THEM
-- NO OTHER TYPE OF OBJECTS ARE DROPPED DUE TO ANALYSIS DOWN BELOW

-- DROP SEQUENCES

DROP SEQUENCE CC_CELL_HISTORY_SEQ;
DROP SEQUENCE HCO_SEQ_CAMPAIGNTRK_ID;
DROP SEQUENCE SEQ_CC_CELL_ID;
DROP SEQUENCE SEQ_CC_HCO_F_CALL_BACK;
DROP SEQUENCE SEQ_CC_HCO_S_CALL_BACK;
DROP SEQUENCE SEQ_CC_SRLKUP_ID;
DROP SEQUENCE SEQ_FLHK_EXT_CALL_DATA_ID;
DROP SEQUENCE SEQ_NF_CLNT_STG;
DROP SEQUENCE SEQ_TEST;

-- DROP VIEWS

DROP VIEW CC_HCO_F_CALL_BACK_SV;
DROP VIEW CC_HCO_F_VOICEMAIL_BY_HOUR_TYPE_BY_DAY;
DROP VIEW CC_NCEB_F_CALLS_BY_DAY_MULTIGRAIN_SV;
DROP VIEW CC_NCEB_F_V2_CALL_SV;
DROP VIEW HCO_C_CAMPAIGN_TRACKING_SV;
DROP VIEW HCO_F_VM_BY_HR_TYPE_BY_DAY_SV;
DROP VIEW HCO_F_VOICEMAIL_DETAILS_SV;

-- DROP TABLES

DROP TABLE CC_HCO_F_CALL_BACK;
DROP TABLE CC_HCO_F_V2_CALL;
DROP TABLE CC_HCO_S_CALL_BACK;
DROP TABLE CC_S_CALLER_SURVEY_DATA_SARA;
DROP TABLE CC_S_IVR_RESPONSE_TEST;
DROP TABLE CC_S_TMP_PIPKINS_EVENT;
DROP TABLE CC_S_TMP_PIPKINS_OFFICE;
DROP TABLE CC_S_TMP_PIPKINS_STAFF;
DROP TABLE CC_S_TMP_PIPKINS_STAFF_GROUP;
DROP TABLE CC_S_TMP_PIPKINS_STF_GRP_STF;
DROP TABLE CC_S_TMP_PIPKINS_STF_TO_OFFICE;
DROP TABLE CC_S_TMP_PIPKINS_SUP_TO_STAFF;
DROP TABLE CC_S_TMP_PIPKINS_TASK;
DROP TABLE CC_S_TMP_PIPKINS_TIMEZONE;
DROP TABLE CC_V2_CALL_TEST;
DROP TABLE CC_V3_CALL_TEST;
DROP TABLE CC_V4_CALL_TEST;
DROP TABLE CRM_CONTACT_CHANNEL_TYPE;
DROP TABLE CRM_CONTACT_RECORD;
DROP TABLE CRM_CONTACT_RECORD_TYPE;
DROP TABLE CRM_CONTACT_TYPE;
DROP TABLE EMP_TEST;
DROP TABLE ENUM_CONSUMER_TYPE;
DROP TABLE ENUM_CONTACT_ACTION_PROVIDE_INFO;
DROP TABLE ENUM_CONTACT_ACTION_PROVIDE_MATERIAL;
DROP TABLE ENUM_CONTACT_ACTION_UPDATE_INFO;
DROP TABLE ENUM_CONTACT_CHANNEL_TYPE;
DROP TABLE ENUM_CONTACT_COMPAIGN_TYPE;
DROP TABLE ENUM_CONTACT_RECORD_ACTION_REASON;
DROP TABLE ENUM_CONTACT_RECORD_ACTION_TYPE;
DROP TABLE ENUM_CONTACT_RECORD_DISPOSITION;
DROP TABLE ENUM_CONTACT_RECORD_EDIT_REASONS;
DROP TABLE ENUM_CONTACT_RECORD_LANGUAGE_TYPE;
DROP TABLE ENUM_CONTACT_RECORD_OUTCOME;
DROP TABLE ENUM_CONTACT_RECORD_TYPE;
DROP TABLE ENUM_CONTACT_TYPE;
DROP TABLE ENUM_INBOUND_CALL_QUEUE;
DROP TABLE ENUM_PROGRAM_TYPE;
DROP TABLE GLENDALE_TERMS;
DROP TABLE HARIS_CC_S_INTERVAL;
DROP TABLE HCO_BUSINESS_HOURS_TYPE_LKUP;
DROP TABLE HCO_C_CAMPAIGN_TRACKING;
DROP TABLE HCO_JOB_STATISTICS;
DROP TABLE JMS_MSG_STORE;
DROP TABLE MARS_ADDRESS;
DROP TABLE MARS_CASE;
DROP TABLE MARS_CASE_CONSUMER;
DROP TABLE MARS_CASE_MEMBER;
DROP TABLE MARS_COMMUNICATION_PREFERENCES;
DROP TABLE MARS_CONSUMER;
DROP TABLE MARS_CONSUMER_AUTHENTICATION;
DROP TABLE MARS_CONSUMER_CONSENT_REQUEST;
DROP TABLE MARS_CONSUMER_IDENTIFICATION_NUMBER;
DROP TABLE MARS_CONTACT_RECORD;
DROP TABLE MARS_CONTACT_RECORD_ACTIONS;
DROP TABLE MARS_CONTACT_RECORD_COMMENT;
DROP TABLE MARS_CONTACT_RECORD_REASON;
DROP TABLE MARS_CONTRACT_AID_CATEGORIES;
DROP TABLE MARS_EMAIL;
DROP TABLE MARS_EVENTS;
DROP TABLE MARS_LINK;
DROP TABLE MARS_MESSAGE;
DROP TABLE MARS_PHONE;
DROP TABLE MARS_PLAN;
DROP TABLE MARS_PLAN_CONTACT;
DROP TABLE MARS_PLAN_ENROLLMENT_LIMITS;
DROP TABLE MARS_PLAN_TYPE_ENTITY;
DROP TABLE MARS_PROCESS_CONTROL;
DROP TABLE MARS_PROJECT;
DROP TABLE MARS_PROJECT_CONTACT;
DROP TABLE MARS_PROJECT_ROLE;
DROP TABLE MARS_PROJECT_STATUS;
DROP TABLE MARS_PROVISIONING_STATUS;
DROP TABLE MARS_SERVICE_DELIVERY_AREAS;
DROP TABLE MARS_STAFF;
DROP TABLE MARS_TASK;
DROP TABLE MARS_USER;
DROP TABLE MLOG$_CC_F_DIALER_BY_DATE;
DROP TABLE MLOG$_CC_HCO_F_V2_CALL;
DROP TABLE MLOG$_TEST_MV;
DROP TABLE NF_CLNT_STG;
DROP TABLE RUPD$_CC_F_DIALER_BY_DATE;
DROP TABLE ST_CONTACT_CHANNEL_TYPE;
DROP TABLE ST_CONTACT_RECORD;
DROP TABLE ST_CONTACT_RECORD_TYPE;
DROP TABLE ST_CONTACT_TYPE;
DROP TABLE TEST;
DROP TABLE TEST1;
DROP TABLE TEST2;
DROP TABLE TEST_CC_F_CALL;
DROP TABLE TEST_CC_F_CALL_OLD;
DROP TABLE TEST_FILTER;
DROP TABLE TEST_FILTER_1;
DROP TABLE TEST_HCO_F_CALL_DETAILS_SV;
DROP TABLE TEST_MV;
DROP TABLE TF_CONTACT_CHANNEL_TYPE;
DROP TABLE TF_CONTACT_RECORD;
DROP TABLE TF_CONTACT_RECORD_TYPE;
DROP TABLE TF_CONTACT_TYPE;

-- NO DROP STATEMENTS FOR ANY OTHER OBJECTS DUE TO BELOW ANALYSIS:

-- Materialized Views       : 2 EXISTS : NONE TO DELETE
   -- 1) CC_F_AGENT_RTG_GRP_INTERVAL_MV
   -- 1) CC_F_AGENT_RTG_GRP_INTERVAL_MV_20171101
-- Public Synonyms          : SO MANY OF THEM EXISTS : NONE TO DELETE
-- Packages                 : 1 EXISTS : NONE TO DELETE
   -- 1) AMPEXP_HIST
-- Functions                : 1 EXISTS : NONE TO DELETE
   -- 1) CALLS OFFERED FUNC
-- Editions                 : 1 EXISTS : NONE TO DELETE
   -- 1) ORA$BASE
-- XML DB Repository        : 2 EXISTS : NONE TO DELETE
   -- 1) public
   -- 2) sys
-- OLAP Option              : 4 EXISTS : NONE TO DELETE
   -- 1) Analytic Workspaces
   -- 2) Build Jobs Scheduled
   -- 3) Build Jobs Running
   -- 4) Build Jobs History
-- Analytic Views           : 3 EXISTS : NONE TO DELETE
   -- 1) Attribute Dimensions
   -- 2) Hierarchies
   -- 3) Analytic Views
-- Scheduler                : 10 EXISTS : NONE TO DELETE
-- RDF Semantic Graph       : 6 EXISTS : NONE TO DELETE
-- Editioning Views         : NONE EXISTS : NONE TO DELETE
-- Procedures               : NONE EXISTS : NONE TO DELETE
-- Operators                : NONE EXISTS : NONE TO DELETE
-- Queues                   : NONE EXISTS : NONE TO DELETE
-- Queue Tables             : NONE EXISTS : NONE TO DELETE
-- Crossedition Triggers    : NONE EXISTS : NONE TO DELETE
-- Types                    : NONE EXISTS : NONE TO DELETE
-- Materialized View Logs   : NONE EXISTS : NONE TO DELETE
-- Synonyms                 : NONE EXISTS : NONE TO DELETE
-- Database Links           : NONE EXISTS : NONE TO DELETE
-- Public Database Links    : NONE EXISTS : NONE TO DELETE
-- Directories              : NONE EXISTS : NONE TO DELETE
-- Java                     : NONE EXISTS : NONE TO DELETE
-- XML Schemas              : NONE EXISTS : NONE TO DELETE
-- Recycle Bin              : NONE EXISTS : NONE TO DELETE
-- Other Users              : SO MANY OF THEM EXISTS : NONE TO DELETE
