CREATE OR REPLACE VIEW DP_SCORECARD.SC_CORRECTIVE_ACTION_AUDIT_SV AS
SELECT
    RECORD_TYPE
    , RECORD_ACTION
    , CA_ID
    , STAFF_ID
    , CA_ENTRY_DATE
    , CAL_ID
    , UNSATISFACTORY_BEHAVIOR
    , COMMENTS
    , CREATE_BY
    , CREATE_DATETIME
    , LAST_UPDATED_BY
    , LAST_UPDATED_DATETIME
    , TRANSACTION_DATE
FROM DP_SCORECARD.SC_CORRECTIVE_ACTION_AUDIT
WITH read only;
