CREATE OR REPLACE VIEW DP_SCORECARD.SC_AUDIT_TEAM_LEAD_QUALITY_SV AS
WITH STAFF_REC AS
( SELECT
    TEAM_LEAD_QUALITY_ID, TEAM_LEAD_AGENT_STAFF_ID, DATES_MONTH_NUM,
   TEAM_LEAD_QUALITY_CREATE_USER, TEAM_LEAD_QUALITY_CREATE_DATE, TEAM_LEAD_QUALITY_UPDATE_USER,
   TEAM_LEAD_QUALITY_UPDATE_DATE, REVIEW_SESSIONS_COMPLTD_RATING, REVIEW_SESSIONS_COMPLTD_POINTS,
   LIVE_OBSRV_COMPLTD_RATING, LIVE_OBSRV_COMPLTD_POINTS, QPP_CHECKLIST_COMPLTD_RATING,
   QPP_CHECKLIST_COMPLTD_POINTS, QPP_QUALITY_SCORE_1_RATING, QPP_QUALITY_SCORE_1_POINTS,
   QPP_QUALITY_SCORE_2_RATING, QPP_QUALITY_SCORE_2_POINTS,
   ---
   REVIEW_SESSIONS_COMPLTD_POINTS
   +LIVE_OBSRV_COMPLTD_POINTS
   +QPP_CHECKLIST_COMPLTD_POINTS
   +QPP_QUALITY_SCORE_1_POINTS
   +QPP_QUALITY_SCORE_2_POINTS AS TOTAL_POINTS
   ---
FROM DP_SCORECARD.SC_AUDIT_TEAM_LEAD_QUALITY
)
SELECT QTRS.DATES_MONTH_YEAR, QTRS.DATES_QTR_YEAR,
--
STAFF_REC.TEAM_LEAD_QUALITY_ID,
STAFF_REC.TEAM_LEAD_AGENT_STAFF_ID,
STAFF_REC.DATES_MONTH_NUM,
STAFF_REC.TEAM_LEAD_QUALITY_CREATE_USER,
STAFF_REC.TEAM_LEAD_QUALITY_CREATE_DATE,
STAFF_REC.TEAM_LEAD_QUALITY_UPDATE_USER,
STAFF_REC.TEAM_LEAD_QUALITY_UPDATE_DATE,
STAFF_REC.REVIEW_SESSIONS_COMPLTD_RATING,
STAFF_REC.REVIEW_SESSIONS_COMPLTD_POINTS,
STAFF_REC.LIVE_OBSRV_COMPLTD_RATING,
STAFF_REC.LIVE_OBSRV_COMPLTD_POINTS,
STAFF_REC.QPP_CHECKLIST_COMPLTD_RATING,
STAFF_REC.QPP_CHECKLIST_COMPLTD_POINTS,
STAFF_REC.QPP_QUALITY_SCORE_1_RATING,
STAFF_REC.QPP_QUALITY_SCORE_1_POINTS,
STAFF_REC.QPP_QUALITY_SCORE_2_RATING,
STAFF_REC.QPP_QUALITY_SCORE_2_POINTS,
STAFF_REC.TOTAL_POINTS,
---
OVERALL_RATING.EVALUATION_RATING
FROM STAFF_REC
JOIN DP_SCORECARD.SCORECARD_QUARTERS_SV QTRS
    ON QTRS.DATES_MONTH_NUM = STAFF_REC.DATES_MONTH_NUM
LEFT OUTER JOIN
	--QPP_EVALUATION_RATING AS
	(SELECT DROP_DOWN_VALUE, DROP_DOWN_TEXT AS EVALUATION_RATING,
	DROP_DOWN_RANGE_LOW, DROP_DOWN_RANGE_HIGH,
        EFFECTIVE_DATE, END_DATE
	FROM DP_SCORECARD.SCORECARD_DROP_DOWN_LKUP_SV
	WHERE TARGET_TABLE = 'SC_AUDIT_TEAM_LEAD_QUALITY'
	AND TARGET_COLUMN = 'QPP_EVALUATION_RATING'
	) OVERALL_RATING
ON  STAFF_REC.TOTAL_POINTS
	BETWEEN OVERALL_RATING.DROP_DOWN_RANGE_LOW
		AND OVERALL_RATING.DROP_DOWN_RANGE_HIGH
	AND TO_DATE(STAFF_REC.DATES_MONTH_NUM,'YYYYMM') BETWEEN OVERALL_RATING.EFFECTIVE_DATE
		AND TRUNC(NVL(OVERALL_RATING.END_DATE,SYSDATE))
ORDER BY TEAM_LEAD_AGENT_STAFF_ID, STAFF_REC.DATES_MONTH_NUM;
