Create table DP_SCORECARD.WEBCHAT_ACTUALS 
(
WEBCHAT_EID            number,
WEBCHAT_STAFF_ID       NUMBER,
WEBCHAT_DATE           date,
ASSIGNED               number,
TRANSFERRED            number,
CONFERENCED            number,
TOTAL_NUMBER           number,
AVG_TIME_WORK          number,
AVG_TIME_WRAP          number,
AVG_TIME_HANDLE        number,
CREATE_DATETIME        date,
LAST_UPDATE_DATE       date
)
TABLESPACE MAXDAT_DATA;
CREATE INDEX DP_SCORECARD.WEBCHAT_ACTUALS_NDX ON DP_SCORECARD.WEBCHAT_ACTUALS (WEBCHAT_EID,WEBCHAT_DATE ASC)  
TABLESPACE MAXDAT_INDX ;

CREATE or REPLACE
TRIGGER TRG_BIU_WEBCHAT_ACTUALS
BEFORE INSERT OR UPDATE ON DP_SCORECARD.WEBCHAT_ACTUALS
FOR EACH ROW

BEGIN
  IF INSERTING THEN
    :new.create_datetime := sysdate;
  else 
    :new.last_update_date := sysdate;
 END IF;

end;


CREATE OR REPLACE FORCE VIEW "DP_SCORECARD"."WEBCHAT_ACTUALS_SV" as
select 
WCA.WEBCHAT_EID "EID",
WCA.WEBCHAT_STAFF_ID "STAFF_ID",
WCA.WEBCHAT_DATE "WEBCHAT DATE",
WCA.ASSIGNED "ASSIGNED",
WCA.TRANSFERRED "TRANSFERRED",
WCA.CONFERENCED "CONFERENCED",
WCA.TOTAL_NUMBER "TOTAL NUMBER",
WCA.AVG_TIME_WORK "AVERAGE TIME WORK",
WCA.AVG_TIME_WRAP "AVERAGE TIME WRAP",
WCA.AVG_TIME_HANDLE "AVERAGE TIME HANDLE"
FROM WEBCHAT_ACTUALS WCA;

grant select on WEBCHAT_ACTUALS to MAXDAT_READ_ONLY;
grant select on WEBCHAT_ACTUALS_SV to MAXDAT_READ_ONLY;

