---- NYHIX-34334 
----

CREATE INDEX DP_SCORECARD.SC_PRODUCTION_BO_EVNT_NAME_NDX
ON DP_SCORECARD.SC_PRODUCTION_BO (EVENT_NAME, DATES ASC)  
TABLESPACE MAXDAT_INDX;


CREATE INDEX DP_SCORECARD.SC_PRODUCTION_BO_S_NAME_NDX
ON DP_SCORECARD.SC_PRODUCTION_BO (EVENT_SUBNAME, DATES, STAFF_ID ASC)  
TABLESPACE MAXDAT_INDX;

/