
create index CORP_ETL_PROC_OUTBND_CALL_IDX1 on CORP_ETL_PROC_OUTBND_CALL (COMPLETE_DT, 0) 
tablespace MAXDAT_INDX;

create index CORP_ETL_OUTBND_CALL_WIP_IDX2 on CORP_ETL_PROC_OUTBND_CALL_WIP (ASSD_PROCESS_OUTCOME, 0)
tablespace MAXDAT_INDX;