ALTER SESSION SET CURRENT_SCHEMA = MAXDAT_KSCH_LEGACY;

-- Update actual shift minutes ----

UPDATE CC_S_AGENT_WORK_DAY SET ACTUAL_SHIFT_MINUTES = null;

commit;

UPDATE CC_F_AGENT_BY_DATE set ACTUAL_SHIFT_MINUTES = LOGIN_SECONDS/60;

commit;
