update file_load_lkup
set load_file = 'N'
where filename_prefix IN('PIONEER_TEAM_COMS_LOG_ACTIVE',
'PIONEER_TEAM_COMS_LOG_ARCHIVE',
'PIONEER_TEAM_STAFF_ROSTER',
'QUALITY_APP_PROCESS_SCORECARD_ACTIVE',
'QUALITY_CHANGE_PROCESSING_SCORECARD_ACTIVE',
'QUALITY_REDETS_SCORECARD_ACTIVE',
'QUALITY_STAFF_ROSTER',
'QUALITY_TASK_NOTIFICATIONS_ACTIVE',
'QUALITY_TASK_NOTIFICATIONS_ARCHIVE',
'QUALITY_APP_PROCESSING_SCORECARD_ARCHIVE');


     