CREATE TABLE CC_S_TMP_ACTIVITY_TYPE
(
   REASONCODE NUMBER(19,0)
 , REASONTEXT VARCHAR2(250)
 , DESCRIPTION VARCHAR2(250)
)
      TABLESPACE MAXDAT_DATA 
        LOGGING 
;

CREATE TABLE CC_S_TMP_AGT_EVENT_DETAIL
(
  DBDATETIME DATE
 ,DATETIME DATE
 ,SKILLTARGETID NUMBER(19,0)
 ,LOGINDATETIME DATE
 ,DURATION NUMBER(19,0)
 ,REASONCODE NUMBER(19,0)
 ,REASONTEXT VARCHAR2(100)
 ,AGENTDESKSETTINGID NUMBER(19,0)
)
      TABLESPACE MAXDAT_DATA 
        LOGGING 
;

CREATE TABLE CC_S_TMP_AGENT_SUPERVISOR
(
  AGENTLOGINID NVARCHAR2(100)
 ,AGENTFIRSTNAME VARCHAR2(100)
 ,AGENTLASTNAME VARCHAR2(100)
 ,SUPLOGINID NVARCHAR2(100)
 ,SUPFIRSTNAME VARCHAR2(100)
 ,SUPLASTNAME VARCHAR2(100)
 ,DESKSETTING VARCHAR2(100)
 ,AGENTTEAMID NUMBER(19,0)
)
      TABLESPACE MAXDAT_DATA 
        LOGGING 
;


ALTER TABLE CC_S_TMP_AGENT ADD(AGENTDESKSETTINGSID NUMBER(19,0), FIRSTNAME VARCHAR2(100), LASTNAME VARCHAR2(100), AGENTGROUP VARCHAR2(100));

TRUNCATE TABLE CC_S_TMP_AGENT_SKILL_GROUP;

ALTER TABLE CC_S_TMP_AGENT_SKILL_GROUP MODIFY (PERIPHERALNUMBER NVARCHAR2(100));

grant select on CC_S_TMP_ACTIVITY_TYPE to MAXDAT_READ_ONLY; 

grant select on CC_S_TMP_AGT_EVENT_DETAIL to MAXDAT_READ_ONLY; 

grant select on CC_S_TMP_AGENT_SUPERVISOR to MAXDAT_READ_ONLY;