ALTER TABLE d_metric_project
ADD (UPPER_SPECIFICATION_LIMIT NUMBER(19,6)
     ,LOWER_SPECIFICATION_LIMIT NUMBER(19,6)
     ,CALCULATE_CONTROL_CHART_IND VARCHAR2(1)
     ,TREND_INDICATOR_CALCULATION VARCHAR2(20));
	 

INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME) 
	VALUES ('2.9','003','003_ALTER_D_METRIC_PROJECT');
	 
COMMIT;