execute MAXDAT_ADMIN.CONFIG_QUEUE_JOB(18,1,'ENABLED','N');
execute MAXDAT_ADMIN.CONFIG_QUEUE_JOB(18,2,'ENABLED','N');
exec DBMS_STATS.GATHER_TABLE_STATS(OWNNAME => 'MAXDAT',TABNAME => 'NYHIX_ETL_MAIL_FAX_DOC',CASCADE => TRUE,DEGREE  => 8,ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE,METHOD_OPT => 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(OWNNAME => 'MAXDAT',TABNAME => 'NYHIX_ETL_MAIL_FAX_DOC_WIP_BPM',CASCADE => TRUE,DEGREE  => 8,ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE,METHOD_OPT => 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(OWNNAME => 'MAXDAT',TABNAME => 'D_NYHIX_MFD_CURRENT',CASCADE => TRUE,DEGREE  => 8,ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE,METHOD_OPT => 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(OWNNAME => 'MAXDAT',TABNAME => 'F_NYHIX_MFD_BY_DATE',CASCADE => TRUE,DEGREE  => 8,ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE,METHOD_OPT => 'FOR ALL COLUMNS SIZE AUTO');
execute MAXDAT_ADMIN.CONFIG_QUEUE_JOB(18,1,'ENABLED','Y');
execute MAXDAT_ADMIN.CONFIG_QUEUE_JOB(18,2,'ENABLED','Y');