-- Semantic View

CREATE OR REPLACE VIEW CC_C_TEAM_SV AS
SELECT
ACD_TEAM_ID
,TEAM_NAME
,TEAM_DESC
,RECORD_EFF_DT
,RECORD_END_DT
,EXTRACT_DT
,LAST_UPDATE_DT
,LAST_UPDATE_BY
FROM
CC_C_ACD_TEAM;

GRANT SELECT ON CC_C_TEAM_SV TO MAXDAT_READ_ONLY; 