CREATE TABLE CC_S_TMP_ACD_AGENT_TEAM
(
AGENTTEAMID INT,
ENTERPRISENAME VARCHAR2(32),
SKILLTARGETID INT,
PERIPHERALNUMBER VARCHAR2(32)
);


CREATE TABLE CC_S_ACD_AGENT_TEAM
(
S_AGENT_TEAM_ID NUMBER(19) NOT NULL,
AGENT_ID NUMBER(19),
AGENT_LOGIN_ID NVARCHAR2(100),
ACD_TEAM_ID NUMBER(19),
EXTRACT_DT DATE,
LAST_UPDATE_DT DATE,
LAST_UPDATE_BY VARCHAR2(30 BYTE)
);


CREATE INDEX CC_S_ACD_AGENT_TEAM_IDX1 ON CC_S_ACD_AGENT_TEAM
  (
    S_AGENT_TEAM_ID
  );

CREATE INDEX CC_S_ACD_AGENT_TEAM_IDX2 ON CC_S_ACD_AGENT_TEAM
  (
   AGENT_ID
  );

CREATE INDEX CC_S_ACD_AGENT_TEAM_IDX4 ON CC_S_ACD_AGENT_TEAM
  (
   AGENT_LOGIN_ID
  );
  
CREATE INDEX CC_S_ACD_AGENT_TEAM_IDX3 ON CC_S_ACD_AGENT_TEAM
  (
    ACD_TEAM_ID
  );
  
ALTER TABLE CC_S_ACD_AGENT_TEAM ADD CONSTRAINTS CC_S_ACD_AGENT_TEAM_PK PRIMARY KEY
  (
    S_AGENT_TEAM_ID
  );
  
ALTER TABLE CC_S_ACD_AGENT_TEAM ADD CONSTRAINTS CC_S_ACD_AGENT_TEAM_UN UNIQUE
  (
     AGENT_ID
    ,ACD_TEAM_ID
  );
 
  
ALTER TABLE CC_S_ACD_AGENT_TEAM ADD CONSTRAINTS CC_S_ACD_AGENT_TEAM_AGT_FK FOREIGN KEY
  (
    AGENT_ID
  )REFERENCES CC_S_AGENT (AGENT_ID) NOT DEFERRABLE;
  
ALTER TABLE CC_S_ACD_AGENT_TEAM ADD CONSTRAINTS CC_S_ACD_AGENT_TEAM_TEAM_FK FOREIGN KEY
  (
    ACD_TEAM_ID
  )REFERENCES CC_C_ACD_TEAM (ACD_TEAM_ID) NOT DEFERRABLE;
  
  
CREATE SEQUENCE SEQ_CC_S_ACD_AGENT_TEAM START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999999 MINVALUE 1 CACHE 20;

CREATE OR REPLACE TRIGGER "BIU_CC_S_ACD_AGENT_TEAM" 
  BEFORE INSERT OR UPDATE ON CC_S_ACD_AGENT_TEAM 
  FOR EACH ROW 
BEGIN
IF INSERTING AND :NEW.S_AGENT_TEAM_ID IS NULL THEN 
  SELECT SEQ_CC_S_ACD_AGENT_TEAM.NEXTVAL INTO :NEW.S_AGENT_TEAM_ID FROM DUAL;
END IF;
IF INSERTING THEN
          :NEW.EXTRACT_DT := SYSDATE;
END IF;
:NEW.LAST_UPDATE_DT := SYSDATE;
:NEW.LAST_UPDATE_BY := USER;
END;
/ 


CREATE TABLE CC_D_ACD_AGENT_TEAM
(
D_AGENT_TEAM_ID NUMBER(19) NOT NULL,
D_AGENT_ID NUMBER(19),
AGENT_LOGIN_ID NVARCHAR2(100),
ACD_TEAM_ID NUMBER(19),
VERSION NUMBER(10),
EXTRACT_DT DATE,
LAST_UPDATE_DT DATE,
LAST_UPDATE_BY VARCHAR2(30 BYTE),
RECORD_EFF_DT  DATE,
RECORD_END_DT  DATE
);

CREATE INDEX CC_D_ACD_AGENT_TEAM_IDX1 ON CC_D_ACD_AGENT_TEAM
  (
    D_AGENT_TEAM_ID
  );

CREATE INDEX CC_D_ACD_AGENT_TEAM_IDX2 ON CC_D_ACD_AGENT_TEAM
  (
    D_AGENT_ID
  );
  
CREATE INDEX CC_D_ACD_AGENT_TEAM_IDX3 ON CC_D_ACD_AGENT_TEAM
  (
    AGENT_LOGIN_ID
  );
  
ALTER TABLE CC_D_ACD_AGENT_TEAM ADD CONSTRAINTS CC_D_ACD_AGENT_TEAM_PK PRIMARY KEY
  (
    D_AGENT_TEAM_ID
  );
  
ALTER TABLE CC_D_ACD_AGENT_TEAM ADD CONSTRAINTS CC_D_ACD_AGENT_TEAM_UN UNIQUE
  (
    D_AGENT_ID
    ,ACD_TEAM_ID
    ,RECORD_EFF_DT
    ,RECORD_END_DT
  );
  
ALTER TABLE CC_D_ACD_AGENT_TEAM ADD CONSTRAINTS CC_D_ACD_AGENT_TEAM_REC_CK CHECK
  (
    RECORD_EFF_DT <= RECORD_END_DT
  );
  
ALTER TABLE CC_D_ACD_AGENT_TEAM ADD CONSTRAINTS CC_D_ACD_AGENT_TEAM_AGT_FK FOREIGN KEY
  (
    D_AGENT_ID
  )REFERENCES CC_D_AGENT (D_AGENT_ID) NOT DEFERRABLE; 
  
ALTER TABLE CC_D_ACD_AGENT_TEAM ADD CONSTRAINTS CC_D_ACD_AGENT_TEAM_TEAM_FK FOREIGN KEY
  (
    ACD_TEAM_ID
  )REFERENCES CC_C_ACD_TEAM (ACD_TEAM_ID) NOT DEFERRABLE;
  
  
CREATE SEQUENCE SEQ_CC_D_ACD_AGENT_TEAM START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999999 MINVALUE 1 CACHE 20;

CREATE OR REPLACE TRIGGER "BIU_CC_D_ACD_AGENT_TEAM" 
  BEFORE INSERT OR UPDATE ON CC_D_ACD_AGENT_TEAM 
  FOR EACH ROW 
BEGIN
IF INSERTING AND :NEW.D_AGENT_TEAM_ID IS NULL THEN 
  SELECT SEQ_CC_D_ACD_AGENT_TEAM.NEXTVAL INTO :NEW.D_AGENT_TEAM_ID FROM DUAL;
END IF;
IF INSERTING THEN
          :NEW.EXTRACT_DT := SYSDATE;
END IF;
:NEW.LAST_UPDATE_DT := SYSDATE;
:NEW.LAST_UPDATE_BY := USER;
END;
/ 
