-- Semantic View

CREATE OR REPLACE VIEW CC_D_AGENT_TEAM_SV AS
SELECT
D_AGENT_TEAM_ID
,D_AGENT_ID
,AGENT_LOGIN_ID
,ACD_TEAM_ID
,VERSION
,RECORD_EFF_DT
,RECORD_END_DT
,EXTRACT_DT
,LAST_UPDATE_DT
,LAST_UPDATE_BY
FROM
CC_D_ACD_AGENT_TEAM;

GRANT SELECT ON CC_D_AGENT_TEAM_SV TO MAXDAT_READ_ONLY; 