truncate table BPM_D_OPS_GROUP_TASK;

insert into bpm_d_ops_group_task values ('Appeals/Complaints', 'Appeals Coordinator ReminderTask');
insert into bpm_d_ops_group_task values ('Appeals/Complaints', 'Appeals Coordinator Task');
insert into bpm_d_ops_group_task values ('Appeals/Complaints', 'CHP+ Appeal Task');
insert into bpm_d_ops_group_task values ('Appeals/Complaints', 'CHP+ Grievance Task');
insert into bpm_d_ops_group_task values ('Appeals/Complaints', 'Continuation of Benefits Task');
insert into bpm_d_ops_group_task values ('Appeals/Complaints', 'EC Complaints');
insert into bpm_d_ops_group_task values ('Appeals/Complaints', 'EC Supervisor Complaints');
insert into bpm_d_ops_group_task values ('Appeals/Complaints', 'ES 2 Complaints');
insert into bpm_d_ops_group_task values ('Appeals/Complaints', 'Incident Document Processing');
insert into bpm_d_ops_group_task values ('Appeals/Complaints', 'Medicaid - Dispute Task');
insert into bpm_d_ops_group_task values ('Appeals/Complaints', 'Medicaid - State Hearing Task');
insert into bpm_d_ops_group_task values ('New Application', 'AwDC New App Data Entry');
insert into bpm_d_ops_group_task values ('Renewal Application', 'AwDC Renewal App Data Entry');
insert into bpm_d_ops_group_task values ('New Application', 'Buy-In New App Data Entry');
insert into bpm_d_ops_group_task values ('CM-Adds/Changes', 'Add a Member Data Entry');
insert into bpm_d_ops_group_task values ('CM-Adds/Changes', 'Add a Member Task');
insert into bpm_d_ops_group_task values ('CM-Research', 'Application Problem Resolution');
insert into bpm_d_ops_group_task values ('CM-Letter Requests', 'Creditable Coverage Letter Task');
insert into bpm_d_ops_group_task values ('CM-Adds/Changes', 'Demographic Change Request Task');
insert into bpm_d_ops_group_task values ('CM-Disenrollment', 'Disenroll  CHP+ - 1 year old ');
insert into bpm_d_ops_group_task values ('CM-Disenrollment', 'Disenroll CHP+ - 19 year old');
insert into bpm_d_ops_group_task values ('CM-Disenrollment', 'Disenroll Medicaid - 1 year old ');
insert into bpm_d_ops_group_task values ('CM-Disenrollment', 'Disenroll Medicaid - 19 yr old');
insert into bpm_d_ops_group_task values ('CM-Disenrollment', 'Disenrollment - PARIS');
insert into bpm_d_ops_group_task values ('CM-Disenrollment', 'Disenrollment Request Task');
insert into bpm_d_ops_group_task values ('CM-Disenrollment', 'Disenrollment request from MCO');
insert into bpm_d_ops_group_task values ('CM-Manual Enrollment', 'Enrollment Request Task');
insert into bpm_d_ops_group_task values ('CM-Expedite', 'Expedite P1 Request Task');
insert into bpm_d_ops_group_task values ('CM-Expedite', 'Expedite P2 Request Task');
insert into bpm_d_ops_group_task values ('CM-Expedite', 'Expedite P3 Request Task');
insert into bpm_d_ops_group_task values ('CM-Research', 'Fee - Research');
insert into bpm_d_ops_group_task values ('CM-Research', 'Good Faith Effort');
insert into bpm_d_ops_group_task values ('CM-Research', 'IEVS Research');
insert into bpm_d_ops_group_task values ('CM-Initiate RRR', 'Initiate RRR - CHP+ 1 year old ');
insert into bpm_d_ops_group_task values ('CM-Initiate RRR', 'Initiate RRR-Medicaid Prenatal');
insert into bpm_d_ops_group_task values ('CM-Letter Requests', 'Insurance Card Creation Task');
insert into bpm_d_ops_group_task values ('CM-Research', 'MI Received - Non MAXIMUS Case ');
insert into bpm_d_ops_group_task values ('CM-Research', 'MI Received - Transition Task');
insert into bpm_d_ops_group_task values ('CM-Manual Enrollment', 'Manual Enrollment Expedite');
insert into bpm_d_ops_group_task values ('CM-Manual Enrollment', 'Manual Enrollment Request Task');
insert into bpm_d_ops_group_task values ('CM-Manual Enrollment', 'Manual Enrollment Request-Esc');
insert into bpm_d_ops_group_task values ('CM-Adds/Changes', 'PEAK Change Report');
insert into bpm_d_ops_group_task values ('CM-Letter Requests', 'Patient Registration Form Task');
insert into bpm_d_ops_group_task values ('CM-Fee', 'Process Enrollment Fee');
insert into bpm_d_ops_group_task values ('CM-Fee', 'Process Enrollment Fee - Lockbox');
insert into bpm_d_ops_group_task values ('CM-Enrollment Fee', 'Process Medicaid Buy-In Premium');
insert into bpm_d_ops_group_task values ('CM-Research', 'Research Task - General');
insert into bpm_d_ops_group_task values ('Image Assembly', 'Alternate Document Processing');
insert into bpm_d_ops_group_task values ('Image Assembly', 'Alternate Document VHT');
insert into bpm_d_ops_group_task values ('Image Assembly', 'AwDC Document Problem Resolution');
insert into bpm_d_ops_group_task values ('Image Assembly', 'AwDC HSDE-QC');
insert into bpm_d_ops_group_task values ('Image Assembly', 'AwDC Link Document Set');
insert into bpm_d_ops_group_task values ('Image Assembly', 'Buy-In HSDE-QC');
insert into bpm_d_ops_group_task values ('Image Assembly', 'Buy-In Link Document Set');
insert into bpm_d_ops_group_task values ('Image Assembly', 'Document Problem Resolution');
insert into bpm_d_ops_group_task values ('Image Assembly', 'HSDE-QC');
insert into bpm_d_ops_group_task values ('Image Assembly', 'Link Document Set');
insert into bpm_d_ops_group_task values ('Missing Information', 'AwDC Missing Info Data Entry');
insert into bpm_d_ops_group_task values ('Missing Information', 'Buy-In Missing Info Data Entry');
insert into bpm_d_ops_group_task values ('None', 'Backlog Application Data Entry');
insert into bpm_d_ops_group_task values ('None', 'CHP+ Authorization Task');
insert into bpm_d_ops_group_task values ('None', 'CSR General Reminder Task');
insert into bpm_d_ops_group_task values ('None', 'General Reminder Task');
insert into bpm_d_ops_group_task values ('None', 'MAXIMUS-QC');
insert into bpm_d_ops_group_task values ('None', 'MI Received Task');
insert into bpm_d_ops_group_task values ('None', 'MI Received via Phone task ');
insert into bpm_d_ops_group_task values ('None', 'MI without App Data Entry');
insert into bpm_d_ops_group_task values ('None', 'New App Data Entry');
insert into bpm_d_ops_group_task values ('None', 'Process Medicaid Buy-in NSF');
insert into bpm_d_ops_group_task values ('None', 'Process Medicaid Buy-in Refund');
insert into bpm_d_ops_group_task values ('None', 'Process NSF');
insert into bpm_d_ops_group_task values ('None', 'Process Refund');
insert into bpm_d_ops_group_task values ('None', 'Renewal - Change Task');
insert into bpm_d_ops_group_task values ('None', 'Renewal - No Change');
insert into bpm_d_ops_group_task values ('None', 'Renewal App Data Entry');
insert into bpm_d_ops_group_task values ('None', 'State Data Entry');
insert into bpm_d_ops_group_task values ('None', 'Verify SVES Results');
insert into bpm_d_ops_group_task values ('Unknown', 'AwDC App Problem Resolution');
insert into bpm_d_ops_group_task values ('Unknown', 'AwDC Pending Apps');
insert into bpm_d_ops_group_task values ('Unknown', 'AwDC Waitlist - Approved');
insert into bpm_d_ops_group_task values ('Unknown', 'Buy-In Doc Problem Resolution');
insert into bpm_d_ops_group_task values ('Unknown', 'BuyIn Demographic Change Request');
insert into bpm_d_ops_group_task values ('Unknown', 'Incident Hearing Processing');
insert into bpm_d_ops_group_task values ('Unknown', 'Liaison');
insert into bpm_d_ops_group_task values ('Unknown', 'Manual Human Task');
insert into bpm_d_ops_group_task values ('Unknown', 'Manual Linking');
insert into bpm_d_ops_group_task values ('Unknown', 'Mass Update Exception Task');
insert into bpm_d_ops_group_task values ('Unknown', 'Missing Info Data Entry');
insert into bpm_d_ops_group_task values ('Unknown', 'Outbound Call Request');
insert into bpm_d_ops_group_task values ('Unknown', 'Pending Apps');
insert into bpm_d_ops_group_task values ('Unknown', 'Pending Apps - Backlog');
insert into bpm_d_ops_group_task values ('Unknown', 'Pending Apps - Duplicates');
insert into bpm_d_ops_group_task values ('Unknown', 'Pending Apps - New Arrivals');
insert into bpm_d_ops_group_task values ('Unknown', 'Pending Apps - Renewals');
insert into bpm_d_ops_group_task values ('Unknown', 'Pending RRR - Due');
insert into bpm_d_ops_group_task values ('Unknown', 'Timely Process Data Entry');
insert into bpm_d_ops_group_task values ('Unknown', 'Unidentified Fees');

commit;
