Insert into CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION) values ('MAX_UPDATE_TS_DMS_BATCHES','D','1999/01/01 00:00:00','Max Update Date for DMS BATCHES Stage table');
Insert into CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION) values ('MAX_UPDATE_TS_DMS_DOCUMENTS','D','1999/01/01 00:00:00','Max Update Date for DMS DOCUMENTS Stage table');

COMMIT;

