declare  c int;
 begin
    select count(*) into c from user_tables where table_name ='APP_DOC_DATA_NYEC_STG';
    if c = 1 then
       execute immediate 'drop table APP_DOC_DATA_NYEC_STG cascade constraints';
    end if;
 end;
 /

CREATE TABLE MAXDAT.APP_DOC_DATA_NYEC_STG
    (
      APP_DOC_DATA_ID      NUMBER (18) NOT NULL
    , RECEIVED_DATE        DATE
    , ECN                  VARCHAR2 (256)
    , DCN                  VARCHAR2 (32)
    , DOCUMENT_TYPE_CD     VARCHAR2 (32)
    , CREATE_TS            DATE
    , UPDATE_TS            DATE
    , DOCUMENT_SET_ID      NUMBER (18)
    , DOCUMENT_ID          NUMBER (18)
    , STATUS_CD            VARCHAR2 (32)
    , STATUS_TS            DATE
    , MEDIA_CD             VARCHAR2 (32)
    , DOCUMENT_SUB_TYPE    VARCHAR2 (32)
    , CREATED_BY           VARCHAR2 (50)
    , UPDATED_BY           VARCHAR2 (50)
    , PRIORITY             NUMBER (18)
    , MINOR_APPLICANT_FLAG VARCHAR2 (1)
    , BIRTH_DATE           DATE,
    CONSTRAINT ADDID_NYEC_PK PRIMARY KEY (APP_DOC_DATA_ID)
    )
    TABLESPACE MAXDAT_DATA
    STORAGE (BUFFER_POOL DEFAULT);

CREATE INDEX IDX3_APP_DOC_DATA_NYEC_CD
    ON MAXDAT.APP_DOC_DATA_NYEC_STG (CREATE_TS)
    TABLESPACE MAXDAT_INDX;

CREATE INDEX IDX3_APP_DOC_DATA_NYEC_DI
    ON MAXDAT.APP_DOC_DATA_NYEC_STG (DOCUMENT_ID)
    TABLESPACE MAXDAT_INDX;

CREATE INDEX IDX3_APP_DOC_DATA_NYEC_DS
    ON MAXDAT.APP_DOC_DATA_NYEC_STG (DOCUMENT_SET_ID)
    TABLESPACE MAXDAT_INDX;

CREATE INDEX IDX3_APP_DOC_DATA_NYEC_RD
    ON MAXDAT.APP_DOC_DATA_NYEC_STG (RECEIVED_DATE)
    TABLESPACE MAXDAT_INDX;

CREATE INDEX IDX3_APP_DOC_DATA_NYEC_SD
    ON MAXDAT.APP_DOC_DATA_NYEC_STG (STATUS_TS)
    TABLESPACE MAXDAT_INDX;

CREATE INDEX IDX3_APP_DOC_DATA_NYEC_UD
    ON MAXDAT.APP_DOC_DATA_NYEC_STG (UPDATE_TS)
    TABLESPACE MAXDAT_INDX;



GRANT SELECT ON MAXDAT.APP_DOC_DATA_NYEC_STG TO MAXDAT_READ_ONLY;

