alter session set current_schema = MAXDAT;
---- DEV_OPS 6589
CREATE TABLE "MAXDAT"."BPM_UPDATE_EVENT_QUEUE_ARCHIVE_TMP"
   (    "BUEQ_ID" NUMBER NOT NULL ENABLE,
        "BSL_ID" NUMBER NOT NULL ENABLE,
        "BIL_ID" NUMBER NOT NULL ENABLE,
        "IDENTIFIER" VARCHAR2(100) NOT NULL ENABLE,
        "EVENT_DATE" DATE NOT NULL ENABLE,
        "QUEUE_DATE" DATE NOT NULL ENABLE,
        "PROCESS_BUEQ_ID" NUMBER,
        "WROTE_BPM_SEMANTIC_DATE" DATE,
        "DATA_VERSION" NUMBER NOT NULL ENABLE,
        "OLD_DATA" "SYS"."XMLTYPE" ,
        "NEW_DATA" "SYS"."XMLTYPE"  NOT NULL ENABLE,
        "CEJS_JOB_ID" NUMBER
   );

INSERT INTO  MAXDAT.BPM_UPDATE_EVENT_QUEUE_ARCHIVE_TMP 
Select * from MAXDAT.BPM_UPDATE_EVENT_QUEUE_ARCHIVE where EVENT_DATE > TRUNC(SYSDATE-30);
COMMIT;

DROP TABLE MAXDAT.BPM_UPDATE_EVENT_QUEUE_ARCHIVE;
DROP TABLE MAXDAT.BPM_UPDATE_EVENT_RETIRE;
DROP TABLE MAXDAT.BPM_UPDATE_EVENT_QUEUE_BAK;
DROP TABLE MAXDAT.BPM_UPDATE_EVENT_QUEUE;
DROP TABLE MAXDAT.BPM_UPDATE_EVENT_BACKUP;

COMMIT;
RENAME MAXDAT.BPM_UPDATE_EVENT_QUEUE_ARCHIVE_TMP to MAXDAT.BPM_UPDATE_EVENT_QUEUE_ARCHIVE;
COMMIT;