CREATE SEQUENCE  "EMRS_SEQ_RACE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 582 CACHE 5 NOORDER  NOCYCLE ;

GRANT SELECT ON "EMRS_SEQ_RACE_ID" TO "MAXDAT_READ_ONLY";

CREATE TABLE EMRS_D_RACE
  (RACE_ID NUMBER NOT NULL, 	 
	 RACE_CODE VARCHAR2(32), 	
   RACE_DESCRIPTION VARCHAR2(240)
   ) TABLESPACE MAXDAT_DATA ;

ALTER TABLE "EMRS_D_RACE" ADD CONSTRAINT "RACE_RACECODE_UK" UNIQUE ("RACE_CODE") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE; 
ALTER TABLE "EMRS_D_RACE" ADD CONSTRAINT "RACE_PK" PRIMARY KEY ("RACE_ID") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE;
  
GRANT SELECT ON "EMRS_D_RACE" TO "MAXDAT_READ_ONLY";

CREATE OR REPLACE TRIGGER "BIR_RACES" 
 BEFORE INSERT
 ON emrs_d_race
 FOR EACH ROW
DECLARE
    v_seq_id     EMRS_D_RACE.race_id%TYPE;
BEGIN
  IF :NEW.race_id IS NULL THEN
    SElECT EMRS_SEQ_RACE_ID.NEXTVAL
    INTO v_seq_id
    FROM dual;

    :NEW.race_id       := v_seq_id;
  END IF;
END BIR_RACES;
/
ALTER TRIGGER "BIR_RACES" ENABLE;
/

CREATE OR REPLACE VIEW EMRS_D_RACE_SV
AS
SELECT race_id
       ,race_code
       ,race_description       
FROM emrs_d_race;

GRANT SELECT ON "EMRS_D_RACE_SV" TO "MAXDAT_READ_ONLY";

