-- CREATE SEQUENCE  "EMRS_SEQ_DEMAP_MCARE_MCAL_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE ;

-- GRANT SELECT ON "EMRS_SEQ_DEMAP_MCARE_MCAL_ID" TO "MAXDAT_READ_ONLY";

CREATE TABLE EMRS_D_DEMAP_MCARETOMCAL(
    DE_MCARE_MCAL_ID NUMBER(9) NOT NULL,
	COUNTY_CODE VARCHAR2(2),
	MCARE_PLAN_ID VARCHAR2(3),
	MCARE_PLAN_NAME VARCHAR2(50),
	MCAL_PLAN_ID VARCHAR2(3),
	AFFILIATE_ID VARCHAR2(3),
	MCARE_CONTRACTNUM VARCHAR2(5)
) TABLESPACE MAXDAT_DATA ;

--ALTER TABLE "EMRS_D_DEMAP_MCARETOMCAL" ADD CONSTRAINT "DE_CNTY_MCARE_MCAL_PLAN_UK" UNIQUE ("COUNTY_CODE", "MCARE_PLAN_ID","MCAL_PLAN_ID") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE; 
--ALTER TABLE "EMRS_D_DEMAP_MCARETOMCAL" ADD CONSTRAINT "DE_MCARE_MCAL_ID_PK" PRIMARY KEY ("DE_MCARE_MCAL_ID") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE;
  
GRANT SELECT ON EMRS_D_DEMAP_MCARETOMCAL TO "MAXDAT_READ_ONLY";
GRANT SELECT, INSERT, UPDATE ON EMRS_D_DEMAP_MCARETOMCAL TO MAXDAT_OLTP_SIU;
GRANT SELECT, INSERT, UPDATE, DELETE ON EMRS_D_DEMAP_MCARETOMCAL TO MAXDAT_OLTP_SIUD;


/*
CREATE OR REPLACE TRIGGER "BIR_DE_MCARETOMCAL" 
 BEFORE INSERT
 ON EMRS_D_DEMAP_MCARETOMCAL
 FOR EACH ROW
DECLARE
    v_seq_id     EMRS_D_DEMAP_MCARETOMCAL.DE_MCARE_MCAL_ID%TYPE;
BEGIN
  IF :NEW.DE_MCARE_MCAL_ID IS NULL THEN
    SElECT EMRS_SEQ_DEMAP_MCARE_MCAL_ID.NEXTVAL
    INTO v_seq_id
    FROM dual;

    :NEW.DE_MCARE_MCAL_ID       := v_seq_id;
  END IF;
END BIR_DE_MCARETOMCAL;

ALTER TRIGGER "BIR_DE_MCARETOMCAL" ENABLE;
*/

CREATE OR REPLACE VIEW EMRS_D_DEMAP_MCARETOMCAL_SV
AS
SELECT  DE_MCARE_MCAL_ID
       ,COUNTY_CODE
	   ,MCARE_PLAN_ID
	   ,MCARE_PLAN_NAME
	   ,MCAL_PLAN_ID
	   ,AFFILIATE_ID
	   ,MCARE_CONTRACTNUM
FROM EMRS_D_DEMAP_MCARETOMCAL;

GRANT SELECT ON "EMRS_D_DEMAP_MCARETOMCAL_SV" TO "MAXDAT_READ_ONLY";