CREATE SEQUENCE  "EMRS_SEQ_LANGUAGE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 582 CACHE 5 NOORDER  NOCYCLE ;

GRANT SELECT ON "EMRS_SEQ_LANGUAGE_ID" TO "MAXDAT_READ_ONLY";

CREATE TABLE EMRS_D_LANGUAGE
  (LANGUAGE_ID NUMBER NOT NULL, 	 
	 LANGUAGE_CODE VARCHAR2(32), 	
   LANGUAGE VARCHAR2(240)
   ) TABLESPACE MAXDAT_DATA ;

ALTER TABLE "EMRS_D_LANGUAGE" ADD CONSTRAINT "LANG_LANGCODE_UK" UNIQUE ("LANGUAGE_CODE") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE; 
ALTER TABLE "EMRS_D_LANGUAGE" ADD CONSTRAINT "LANG_LANGUAGEID_PK" PRIMARY KEY ("LANGUAGE_ID") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE;
  
GRANT SELECT ON "EMRS_D_LANGUAGE" TO "MAXDAT_READ_ONLY";

  CREATE OR REPLACE TRIGGER "BIR_LANGUAGE" 
 BEFORE INSERT
 ON emrs_d_language
 FOR EACH ROW
DECLARE
    v_seq_id     EMRS_D_LANGUAGE.language_id%TYPE;
BEGIN
  IF :NEW.language_id IS NULL THEN
    SElECT EMRS_SEQ_LANGUAGE_ID.NEXTVAL
    INTO v_seq_id
    FROM dual;

    :NEW.language_id       := v_seq_id;
  END IF;
END BIR_LANGUAGE;
/
ALTER TRIGGER "BIR_LANGUAGE" ENABLE;
/


CREATE OR REPLACE VIEW EMRS_D_LANGUAGE_SV
AS
SELECT language_id
       ,language_code
       ,language
       ,CASE WHEN language_code IN ('0','3','6','A','F','G','I','J','K','L','M','P','Q','S','T') THEN 'English'
     WHEN language_code in ('2','B','C') THEN 'Chinese' ELSE COALESCE( language, 'English') END language_derived_desc
FROM emrs_d_language;

GRANT SELECT ON "EMRS_D_LANGUAGE_SV" TO "MAXDAT_READ_ONLY";

