CREATE SEQUENCE  "EMRS_SEQ_PLAN_HIST_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 92481 CACHE 5 NOORDER  NOCYCLE ;

GRANT SELECT ON "EMRS_SEQ_PLAN_HIST_ID" TO "MAXDAT_READ_ONLY";


CREATE TABLE EMRS_D_PLAN_HISTORY
(PLAN_HISTORY_ID NUMBER
,DATE_OF_VALIDITY_START DATE
,DATE_OF_VALIDITY_END DATE
,CURRENT_PLAN_ID VARCHAR2(32)
,CAPITATED_ENROLL NUMBER
,CAPITATED_ENROLL_DATE DATE
,CREATED_BY VARCHAR2(30)
,DATE_CREATED DATE
,UPDATED_BY VARCHAR2(30)
,DATE_UPDATED DATE) TABLESPACE MAXDAT_DATA;

 ALTER TABLE "EMRS_D_PLAN_HISTORY" ADD CONSTRAINT "DPPLANHISTID_PK" PRIMARY KEY ("PLAN_HISTORY_ID") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE;
 
 CREATE INDEX EMRSDPLANHIST_IDX01 ON EMRS_D_PLAN_HISTORY (DATE_OF_VALIDITY_START,DATE_OF_VALIDITY_END) TABLESPACE MAXDAT_INDX;   
 CREATE INDEX EMRSDPLANHIST_IDX02 ON EMRS_D_PLAN_HISTORY (CURRENT_PLAN_ID) TABLESPACE MAXDAT_INDX;   
 
 GRANT SELECT ON "EMRS_D_PLAN_HISTORY" TO "MAXDAT_READ_ONLY";

CREATE OR REPLACE TRIGGER "BUIR_PLAN_HIST" 
 BEFORE INSERT OR UPDATE
 ON emrs_d_plan_history
 FOR EACH ROW
DECLARE
    v_seq_id     EMRS_D_PLAN_HISTORY.plan_history_id%TYPE;
BEGIN
  IF inserting THEN
    IF :NEW.plan_history_id IS NULL THEN
      SElECT EMRS_SEQ_PLAN_HIST_ID.NEXTVAL
      INTO v_seq_id
      FROM dual;

      :NEW.plan_history_id       := v_seq_id;
    END IF;
    :new.created_by := user;
    :new.date_created := sysdate;
  END IF;
    :new.updated_by := user;
    :new.date_updated := sysdate;
END BUIR_PLAN_HIST;
/
ALTER TRIGGER "BUIR_PLAN_HIST" ENABLE;
/

CREATE OR REPLACE VIEW EMRS_D_PLAN_HISTORY_SV
AS
SELECT plan_history_id
       ,date_of_validity_start
       ,date_of_validity_end
       ,current_plan_id
       ,capitated_enroll
       ,capitated_enroll_date
FROM emrs_d_plan_history;

GRANT SELECT ON "EMRS_D_PLAN_HISTORY_SV" TO "MAXDAT_READ_ONLY";

