CREATE SEQUENCE  "EMRS_SEQ_ENROLMT_TRANS_TYPE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 550 CACHE 20 NOORDER  NOCYCLE ;

GRANT SELECT ON "EMRS_SEQ_ENROLMT_TRANS_TYPE_ID" TO "MAXDAT_READ_ONLY";

CREATE TABLE EMRS_D_ENROLL_TRANS_TYPE
   (ENROLLMENT_TRANS_TYPE_ID NUMBER NOT NULL, 	
	  ENROLLMENT_TRANS_TYPE_CODE VARCHAR2(80), 
	  ENROLLMENT_TRANS_TYPE VARCHAR2(500)	
   ) TABLESPACE MAXDAT_DATA ;

ALTER TABLE EMRS_D_ENROLL_TRANS_TYPE ADD CONSTRAINT ENRLTRANSTYPE_PK PRIMARY KEY (ENROLLMENT_TRANS_TYPE_ID) USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE;
ALTER TABLE EMRS_D_ENROLL_TRANS_TYPE ADD CONSTRAINT "ENRLTRANSTYPE_UK" UNIQUE (ENROLLMENT_TRANS_TYPE_CODE) USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE;   
  
GRANT SELECT ON "EMRS_D_ENROLL_TRANS_TYPE" TO "MAXDAT_READ_ONLY";

CREATE OR REPLACE TRIGGER "BIR_ENRL_TRANS_TYPE" 
 BEFORE INSERT
 ON EMRS_D_ENROLL_TRANS_TYPE
 FOR EACH ROW
DECLARE
    v_seq_id     EMRS_D_ENROLL_TRANS_TYPE.enrollment_trans_type_id%TYPE;
BEGIN
    IF :NEW.enrollment_trans_type_id IS NULL THEN
      SElECT EMRS_SEQ_ENROLMT_TRANS_TYPE_ID.NEXTVAL
      INTO v_seq_id
      FROM dual;

      :NEW.enrollment_trans_type_id       := v_seq_id;
    END IF;
END BIR_ENRL_TRANS_TYPE;
/
ALTER TRIGGER "BIR_ENRL_TRANS_TYPE" ENABLE;
/

CREATE OR REPLACE VIEW EMRS_D_ENROLL_TRANS_TYPE_SV
AS
SELECT enrollment_trans_type_code
       ,enrollment_trans_type
FROM emrs_d_enroll_trans_type;

GRANT SELECT ON "EMRS_D_ENROLL_TRANS_TYPE_SV" TO "MAXDAT_READ_ONLY";