CREATE SEQUENCE  "EMRS_SEQ_DENR_STATUS_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 341 CACHE 20 NOORDER  NOCYCLE ;

GRANT SELECT ON "EMRS_SEQ_DENR_STATUS_ID" TO "MAXDAT_READ_ONLY";

CREATE TABLE EMRS_D_EMRGCY_DENR_STATUS
  (EMRGCY_DENR_STATUS_ID NUMBER NOT NULL, 
	 EMRGCY_DENR_STATUS_CODE VARCHAR2(32), 
	 EMRGCY_DENR_STATUS VARCHAR2(240),
   FINAL_STATUS VARCHAR2(10),
   APPROVAL VARCHAR2(10),
   DENIAL VARCHAR2(10),
   PENDING VARCHAR2(10)
   ) TABLESPACE MAXDAT_DATA ;

ALTER TABLE "EMRS_D_EMRGCY_DENR_STATUS" ADD CONSTRAINT "EMRGCYDENRSTATUS_UK" UNIQUE ("EMRGCY_DENR_STATUS_CODE") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE; 
ALTER TABLE "EMRS_D_EMRGCY_DENR_STATUS" ADD CONSTRAINT "EMRGCYDENRSTATUSPK" PRIMARY KEY ("EMRGCY_DENR_STATUS_ID") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE;
  
GRANT SELECT ON "EMRS_D_EMRGCY_DENR_STATUS" TO "MAXDAT_READ_ONLY";

CREATE OR REPLACE TRIGGER "BIR_EMRGCY_DENR_STATUS" 
 BEFORE INSERT
 ON emrs_d_emrgcy_denr_status
 FOR EACH ROW
DECLARE
    v_seq_id     EMRS_D_EMRGCY_DENR_STATUS.emrgcy_denr_status_id%TYPE;
BEGIN
  IF :NEW.emrgcy_denr_status_id IS NULL THEN
    SElECT EMRS_SEQ_DENR_STATUS_ID.NEXTVAL
    INTO v_seq_id
    FROM dual;

    :NEW.emrgcy_denr_status_id       := v_seq_id;
  END IF;
END BIR_EMRGCY_DENR_STATUS;
/
ALTER TRIGGER "BIR_EMRGCY_DENR_STATUS" ENABLE;
/

CREATE OR REPLACE VIEW EMRS_D_EMRGCY_DENR_STATUS_SV
AS
SELECT emrgcy_denr_status_id
       ,emrgcy_denr_status_code
       ,emrgcy_denr_status
       ,final_status
       ,approval
       ,denial
       ,pending
FROM emrs_d_emrgcy_denr_status;

GRANT SELECT ON "EMRS_D_EMRGCY_DENR_STATUS_SV" TO "MAXDAT_READ_ONLY";

