CREATE SEQUENCE  "EMRS_SEQ_PLANTYPE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 582 CACHE 5 NOORDER  NOCYCLE ;

GRANT SELECT ON "EMRS_SEQ_PLANTYPE_ID" TO "MAXDAT_READ_ONLY";

CREATE TABLE EMRS_D_PLAN_TYPE
  (PLAN_TYPE_ID NUMBER NOT NULL, 	 
	 PLAN_TYPE VARCHAR2(32), 	
   PLAN_TYPE_DESC VARCHAR2(64)
   ) TABLESPACE MAXDAT_DATA ;

ALTER TABLE "EMRS_D_PLAN_TYPE" ADD CONSTRAINT "PLANTYPE_PLANTYPECODE_UK" UNIQUE ("PLAN_TYPE") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE; 
ALTER TABLE "EMRS_D_PLAN_TYPE" ADD CONSTRAINT "PLANTYPE_PK" PRIMARY KEY ("PLAN_TYPE_ID") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE;
  
GRANT SELECT ON "EMRS_D_PLAN_TYPE" TO "MAXDAT_READ_ONLY";

CREATE OR REPLACE TRIGGER "BIR_PLAN_TYPE" 
 BEFORE INSERT
 ON emrs_d_plan_type
 FOR EACH ROW
DECLARE
    v_seq_id     EMRS_D_PLAN_TYPE.plan_type_id%TYPE;
BEGIN
  IF :NEW.plan_type_id IS NULL THEN
    SElECT EMRS_SEQ_PLANTYPE_ID.NEXTVAL
    INTO v_seq_id
    FROM dual;

    :NEW.plan_type_id       := v_seq_id;
  END IF;
END BIR_PLAN_TYPE;
/
ALTER TRIGGER "BIR_PLAN_TYPE" ENABLE;
/

CREATE OR REPLACE VIEW EMRS_D_PLAN_TYPE_SV
AS
SELECT plan_type,
plan_type_desc
FROM emrs_d_plan_type;

GRANT SELECT ON "EMRS_D_PLAN_TYPE_SV" TO "MAXDAT_READ_ONLY";

