CREATE SEQUENCE  "EMRS_SEQ_TERM_REASON_CODE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 92481 CACHE 5 NOORDER  NOCYCLE ;

GRANT SELECT ON "EMRS_SEQ_TERM_REASON_CODE_ID" TO "MAXDAT_READ_ONLY";

CREATE TABLE EMRS_D_TERMINATION_REASON
   (TERM_REASON_CODE_ID NUMBER NOT NULL, 	
    REASON_CODE VARCHAR2(80), 	  
    REASON VARCHAR2(500),
    PLAN_NAME VARCHAR2(240),
    TERM_REASON_TYPE VARCHAR2(10)
   ) TABLESPACE MAXDAT_DATA ;

 ALTER TABLE "EMRS_D_TERMINATION_REASON" ADD CONSTRAINT "TERMREAS_PLANCODE_UK" UNIQUE ("REASON_CODE", "PLAN_NAME") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE;
 ALTER TABLE "EMRS_D_TERMINATION_REASON" ADD CONSTRAINT "TERMREAS_PK" PRIMARY KEY ("TERM_REASON_CODE_ID") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE;
  
GRANT SELECT ON "EMRS_D_TERMINATION_REASON" TO "MAXDAT_READ_ONLY";

  CREATE OR REPLACE TRIGGER "BIR_TERMINATION_REASONS" 
 BEFORE INSERT
 ON emrs_d_termination_reason
 FOR EACH ROW
DECLARE
    v_seq_id     EMRS_D_TERMINATION_REASON.term_reason_code_id%TYPE;
BEGIN
  IF :NEW.term_reason_code_id IS NULL THEN
    SElECT EMRS_SEQ_TERM_REASON_CODE_ID.NEXTVAL
    INTO v_seq_id
    FROM dual;

    :NEW.term_reason_code_id       := v_seq_id;
  END IF;
END BIR_TERMINATION_REASONS;
/
ALTER TRIGGER "BIR_TERMINATION_REASONS" ENABLE;
/



CREATE OR REPLACE VIEW EMRS_D_TERMINATION_REASON_SV
AS
SELECT reason_code
       ,reason
       ,plan_name
       ,term_reason_type
FROM emrs_d_termination_reason;

GRANT SELECT ON "EMRS_D_TERMINATION_REASON_SV" TO "MAXDAT_READ_ONLY";
