CREATE SEQUENCE  "EMRS_SEQ_SELECTION_SOURCE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 341 CACHE 20 NOORDER  NOCYCLE ;

GRANT SELECT ON "EMRS_SEQ_SELECTION_SOURCE_ID" TO "MAXDAT_READ_ONLY";

CREATE TABLE EMRS_D_SELECTION_SOURCE
  (SELECTION_SOURCE_ID NUMBER(10), 
	 SELECTION_SOURCE_CODE VARCHAR2(32), 
	 SELECTION_SOURCE VARCHAR2(240), 	
	 IS_CHOICE_IND VARCHAR2(1),
   DP_SELECTION_SOURCE_ID NUMBER(10) NOT NULL
   ) TABLESPACE MAXDAT_DATA ;

ALTER TABLE "EMRS_D_SELECTION_SOURCE" ADD CONSTRAINT "SLCTSOURCE_COMB_UK" UNIQUE ("SELECTION_SOURCE_ID") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE; 
ALTER TABLE "EMRS_D_SELECTION_SOURCE" ADD CONSTRAINT "SLCTSOURCEPK" PRIMARY KEY ("DP_SELECTION_SOURCE_ID") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE;

CREATE INDEX EMRSDSELSOURCE_IDX01 ON EMRS_D_SELECTION_SOURCE(SELECTION_SOURCE_CODE) TABLESPACE MAXDAT_INDX;
  
GRANT SELECT ON "EMRS_D_SELECTION_SOURCE" TO "MAXDAT_READ_ONLY";

CREATE OR REPLACE TRIGGER "BIR_SELECTION_SOURCES" 
 BEFORE INSERT
 ON emrs_d_selection_source
 FOR EACH ROW
DECLARE
    v_seq_id     EMRS_D_SELECTION_SOURCE.dp_selection_source_id%TYPE;
BEGIN
  IF :NEW.dp_selection_source_id IS NULL THEN
    SElECT EMRS_SEQ_SELECTION_SOURCE_ID.NEXTVAL
    INTO v_seq_id
    FROM dual;

    :NEW.dp_selection_source_id       := v_seq_id;
  END IF;
END BIR_SELECTION_SOURCES;
/
ALTER TRIGGER "BIR_SELECTION_SOURCES" ENABLE;
/


CREATE OR REPLACE VIEW EMRS_D_SELECTION_SOURCE_SV
AS
SELECT selection_source_id
       ,selection_source_code
       ,selection_source
       ,is_choice_ind       
FROM emrs_d_selection_source;

GRANT SELECT ON "EMRS_D_SELECTION_SOURCE_SV" TO "MAXDAT_READ_ONLY";
