CREATE SEQUENCE  "EMRS_SEQ_COUNTIES_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10216 CACHE 5 NOORDER  NOCYCLE ;

GRANT SELECT ON "EMRS_SEQ_COUNTIES_ID" TO "MAXDAT_READ_ONLY";

CREATE TABLE EMRS_D_COUNTY
  (COUNTY_ID NUMBER NOT NULL, 
   COUNTY_CODE VARCHAR2(32), 
   COUNTY_FIPS_CODE VARCHAR2(32), 
   COUNTY_NAME VARCHAR2(240), 
   PLAN_SERVICE_TYPE VARCHAR2(20), 
   STATE VARCHAR2(17), 
   AUTO_ASSIGNMENT VARCHAR2(1),
   MVX_STATUS VARCHAR2(1), 
   COVERED_BY_PROGRAM VARCHAR2(32),
   PHASE VARCHAR2(32),
   EXPANSION_IND VARCHAR2(1),
   PLAN_TYPE VARCHAR2(2)) TABLESPACE MAXDAT_DATA ;

ALTER TABLE "EMRS_D_COUNTY" ADD CONSTRAINT "CNTY_CNTY_COMB_UK" UNIQUE ("STATE", "COUNTY_CODE", "PLAN_SERVICE_TYPE") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE; 
ALTER TABLE "EMRS_D_COUNTY" ADD CONSTRAINT "CNTY_PK" PRIMARY KEY ("COUNTY_ID") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE;
  
GRANT SELECT ON "EMRS_D_COUNTY" TO "MAXDAT_READ_ONLY";

  CREATE OR REPLACE TRIGGER "BIR_COUNTIES" 
 BEFORE INSERT
 ON emrs_d_county
 FOR EACH ROW
DECLARE
    v_seq_id     EMRS_D_COUNTY.county_id%TYPE;
BEGIN
  IF :NEW.county_id IS NULL THEN
    SElECT EMRS_SEQ_COUNTIES_ID.NEXTVAL
    INTO v_seq_id
    FROM dual;

    :NEW.county_id       := v_seq_id;
  END IF;
END BIR_COUNTIES;
/
ALTER TRIGGER "BIR_COUNTIES" ENABLE;
/

CREATE OR REPLACE VIEW EMRS_D_COUNTY_SV
AS
SELECT county_id
       ,county_code
       ,county_fips_code
       ,county_name
       ,plan_service_type
       ,state
       ,auto_assignment
       ,mvx_status
       ,covered_by_program
       ,phase
       ,expansion_ind
       ,plan_type
FROM emrs_d_county;

GRANT SELECT ON "EMRS_D_COUNTY_SV" TO "MAXDAT_READ_ONLY";


