 declare  c int;
 begin
    select count(*) into c from user_tables where table_name ='EMRS_D_CLIENT_AGEGROUP';
    if c = 1 then
       execute immediate 'drop table EMRS_D_CLIENT_AGEGROUP cascade constraints';
    end if;
 end;
 /

 declare  c int;
 begin
    select count(*) into c from user_views where view_name ='EMRS_D_CLIENT_AGEGROUP_SV';
    if c = 1 then
       execute immediate 'drop view EMRS_D_CLIENT_AGEGROUP_SV ';
    end if;
 end;
 /


CREATE TABLE maxdat.EMRS_D_CLIENT_AGEGROUP
(
AGEGROUP_ID NUMBER(18),
AGEGROUP_YEAR NUMBER(4),
AGEGROUP      NUMBER(4),
AGEGROUP0     NUMBER(4),
AGEGROUP5 	  NUMBER(4),
AGEGROUP_DESC VARCHAR2(15),
AGEGROUP0_DESC VARCHAR2(20),
AGEGROUP5_DESC VARCHAR2(15)
)
    TABLESPACE MAXDAT_DATA
    STORAGE (BUFFER_POOL DEFAULT);

ALTER TABLE EMRS_D_CLIENT_AGEGROUP ADD CONSTRAINT PK_EMRS_D_CLIENT_AGEGROUP_ID PRIMARY KEY (agegroup_id);
CREATE INDEX IDX_EMRS_D_CLIENT_AGEGROUP_YEAR ON EMRS_D_CLIENT_AGEGROUP(agegroup_year);

GRANT SELECT ON EMRS_D_CLIENT_AGEGROUP TO MAXDAT_READ_ONLY;


CREATE OR REPLACE VIEW MAXDAT.EMRS_D_CLIENT_AGEGROUP_SV
AS
SELECT AGEGROUP_ID ,
AGEGROUP_YEAR ,
AGEGROUP,
AGEGROUP0,
AGEGROUP5,
AGEGROUP_DESC ,
AGEGROUP0_DESC ,
AGEGROUP5_DESC
FROM EMRS_D_CLIENT_AGEGROUP
WITH read only;
/

GRANT SELECT ON MAXDAT.EMRS_D_CLIENT_AGEGROUP_SV TO MAXDAT_READ_ONLY;
