CREATE SEQUENCE  "HCO_SEQ_FORMINCRSN_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 582 CACHE 5 NOORDER  NOCYCLE ;

GRANT SELECT ON "HCO_SEQ_FORMINCRSN_ID" TO "MAXDAT_READ_ONLY";

CREATE TABLE HCO_D_FORM_INCOMPLETE_REASON
  (INCOMPLETE_REASON_CODE VARCHAR2(32), 	
   INCOMPLETE_REASON VARCHAR2(400),  
   MEDICAL_OR_DENTAL VARCHAR2(1),
   CHOICE_FORM_REASON_CODE VARCHAR2(3),
   LETTER_TYPE VARCHAR2(5),
   IS_SYSTEM_CODE VARCHAR2(1),
   DP_FORM_INC_RSN_ID NUMBER NOT NULL
   ) TABLESPACE MAXDAT_DATA ;

ALTER TABLE "HCO_D_FORM_INCOMPLETE_REASON" ADD CONSTRAINT "FORM_FORMINCRSN_UK" UNIQUE ("INCOMPLETE_REASON_CODE","MEDICAL_OR_DENTAL") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE; 
ALTER TABLE "HCO_D_FORM_INCOMPLETE_REASON" ADD CONSTRAINT "FORMINCRSN_ID_PK" PRIMARY KEY ("DP_FORM_INC_RSN_ID") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE;
  
GRANT SELECT ON "HCO_D_FORM_INCOMPLETE_REASON" TO "MAXDAT_READ_ONLY";

CREATE OR REPLACE TRIGGER "BIR_FORM_INCRSN" 
 BEFORE INSERT
 ON hco_d_form_incomplete_reason
 FOR EACH ROW
DECLARE
    v_seq_id     HCO_D_FORM_INCOMPLETE_REASON.dp_form_inc_rsn_id%TYPE;
BEGIN
  IF :NEW.dp_form_inc_rsn_id IS NULL THEN
    SElECT HCO_SEQ_FORMINCRSN_ID.NEXTVAL
    INTO v_seq_id
    FROM dual;

    :NEW.dp_form_inc_rsn_id       := v_seq_id;
  END IF;
END BIR_FORM_INCRSN;
/
ALTER TRIGGER "BIR_FORM_INCRSN" ENABLE;
/

CREATE OR REPLACE VIEW HCO_D_FORM_INCOMPLETE_RSN_SV
AS
SELECT incomplete_reason_code
       ,incomplete_reason
       ,medical_or_dental
       ,choice_form_reason_code
       ,letter_type
       ,is_system_code
FROM hco_d_form_incomplete_reason;

GRANT SELECT ON "HCO_D_FORM_INCOMPLETE_RSN_SV" TO "MAXDAT_READ_ONLY";
