/*
drop Tables
------------
drop table NYHIX_ETL_MAIL_FAX_DOC_V2;
drop table NYHIX_ETL_MAIL_FAX_DOC_OLTP_V2;
drop table NYHIX_ETL_MAIL_FAX_DOC_WIP_V2;
drop table NYHIX_ETL_MAIL_FAX_DOC_CSC_V2;
drop table NYHIX_ETL_MAIL_FAX_DOC_APP_V2;
*/

--Create Tables
create table NYHIX_ETL_MAIL_FAX_DOC_V2
(
EEMFDB_ID NUMBER(18,0) NOT NULL, 
INSTANCE_STATUS VARCHAR2(32 BYTE) NOT NULL,
INSTANCE_START_DATE DATE, 
INSTANCE_END_DATE DATE, 
COMPLETE_DT DATE, 
CANCEL_DT DATE, 
CANCEL_BY VARCHAR2(32 BYTE), 
CANCEL_REASON VARCHAR2(32 BYTE), 
CANCEL_METHOD VARCHAR2(32 BYTE), 
DCN VARCHAR2(256 BYTE) NOT NULL, 
CREATE_DT DATE NOT NULL, 
RECEIVED_DT DATE, 
DOC_TYPE_CD VARCHAR2(32 BYTE) NOT NULL, 
PAGE_COUNT NUMBER(18,0), 
ECN VARCHAR2(256 BYTE) NOT NULL,
CHANNEL VARCHAR2(32 BYTE) NOT NULL,
KOFAX_DCN VARCHAR2(256 BYTE) NOT NULL, 
BATCH_ID NUMBER(38,0) NOT NULL, 
BATCH_NAME VARCHAR2(256 BYTE) NOT NULL, 
DOC_STATUS_CD VARCHAR2(32 BYTE) NOT NULL, 
DOC_STATUS_DT DATE NOT NULL, 
DOC_UPDATE_DT DATE, 
DOC_UPDATED_BY_STAFF_ID VARCHAR2(50 BYTE), 
DOC_UPDATED_BY VARCHAR2(32 BYTE) ,
APP_DOC_DATA_ID NUMBER(18,0) , 
PRIORITY NUMBER(2,0) ,
FORM_TYPE_CD VARCHAR2(256 BYTE) ,
FREE_FORM_TXT_IND VARCHAR2(1 BYTE) , 
PREVIOUS_KOFAX_DCN VARCHAR2(50 BYTE) ,
SCAN_DT DATE, 
RELEASE_DT DATE, 
APP_DOC_TRACKER_ID NUMBER(18,0) ,
ENV_STATUS_CD VARCHAR2(32 BYTE) ,
ENV_STATUS VARCHAR2(256 BYTE) default 'Received',
ENV_STATUS_DT DATE, 
SLA_COMPLETE_DT DATE, 
ENV_UPDATE_DT DATE, 
ENV_UPDATED_BY_STAFF_ID VARCHAR2(50 BYTE) ,
ENV_UPDATED_BY VARCHAR2(32 BYTE) ,
SLA_COMPLETE VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
MAXE_ORIGINATION_DT DATE, 
RESCANNED_IND VARCHAR2(1 BYTE) ,
RETURNED_MAIL_IND VARCHAR2(1 BYTE), 
RETURNED_MAIL_REASON VARCHAR2(32 BYTE) ,
RESCAN_COUNT NUMBER(18,0) , 
NOTE_ID VARCHAR2(32 BYTE) ,
ASF_PROCESS_DOC VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
ASF_CANCEL_DOC VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
TRASHED_DT DATE, 
TRASHED_BY VARCHAR2(32 BYTE) ,
TRASHED_IND VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
ORIG_DOC_TYPE_CD VARCHAR2(32 BYTE) ,
ORIG_DOC_FORM_TYPE VARCHAR2(32 BYTE) ,
ORIG_DOC_FORM_TYPE_CD VARCHAR2(32 BYTE) ,
RESEARCH_REQ_IND VARCHAR2(1 BYTE) ,
EXPEDIATED_IND VARCHAR2(1 BYTE) ,
STG_EXTRACT_DATE DATE, 
STG_LAST_UPDATE_DATE DATE, 
FORM_TYPE VARCHAR2(64 BYTE) ,
STG_DONE_DATE DATE, 
LAST_EVENT_DATE DATE, 
UPDATED VARCHAR2(1 BYTE) ,
INSERTED VARCHAR2(1 BYTE)
)tablespace MAXDAT_DATA;

create table NYHIX_ETL_MAIL_FAX_DOC_OLTP_V2
(
EEMFDB_ID NUMBER(18,0) NOT NULL,
INSTANCE_STATUS VARCHAR2(32 BYTE) NOT NULL,
INSTANCE_START_DATE DATE,
INSTANCE_END_DATE DATE,
COMPLETE_DT DATE,
CANCEL_DT DATE,
CANCEL_BY VARCHAR2(32 BYTE),
CANCEL_REASON VARCHAR2(32 BYTE),
CANCEL_METHOD VARCHAR2(32 BYTE),
DCN VARCHAR2(256 BYTE) NOT NULL,
CREATE_DT DATE NOT NULL,
RECEIVED_DT DATE,
DOC_TYPE_CD VARCHAR2(32 BYTE) NOT NULL,
PAGE_COUNT NUMBER(18,0),
ECN VARCHAR2(256 BYTE) NOT NULL,
CHANNEL VARCHAR2(32 BYTE) NOT NULL,
KOFAX_DCN VARCHAR2(256 BYTE) NOT NULL,
BATCH_ID NUMBER(38,0) NOT NULL,
BATCH_NAME VARCHAR2(256 BYTE) NOT NULL,
DOC_STATUS_CD VARCHAR2(32 BYTE) NOT NULL,
DOC_STATUS VARCHAR2(32 BYTE) ,
DOC_STATUS_DT DATE NOT NULL,
DOC_UPDATE_DT DATE ,
DOC_UPDATED_BY_STAFF_ID VARCHAR2(50 BYTE) ,
DOC_UPDATED_BY VARCHAR2(32 BYTE) ,
APP_DOC_DATA_ID NUMBER(18,0) ,
PRIORITY NUMBER(2,0) ,
FORM_TYPE_CD VARCHAR2(256 BYTE),
FREE_FORM_TXT_IND VARCHAR2(1 BYTE),
PREVIOUS_KOFAX_DCN VARCHAR2(50 BYTE),
SCAN_DT DATE ,
RELEASE_DT DATE ,
APP_DOC_TRACKER_ID NUMBER(18,0) ,
ENV_STATUS_CD VARCHAR2(32 BYTE) ,
ENV_STATUS VARCHAR2(256 BYTE)  default 'Received',
ENV_STATUS_DT DATE ,
SLA_COMPLETE_DT DATE,
ENV_UPDATE_DT DATE ,
ENV_UPDATED_BY_STAFF_ID VARCHAR2(50 BYTE) ,
ENV_UPDATED_BY VARCHAR2(32 BYTE) ,
SLA_COMPLETE VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
MAXE_ORIGINATION_DT DATE ,
RESCANNED_IND VARCHAR2(1 BYTE) ,
RETURNED_MAIL_IND VARCHAR2(1 BYTE) ,
RETURNED_MAIL_REASON VARCHAR2(32 BYTE),
RESCAN_COUNT NUMBER(18,0) ,
NOTE_ID VARCHAR2(32 BYTE) ,
ASF_PROCESS_DOC VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
ASF_CANCEL_DOC VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
UPDATED VARCHAR2(1 BYTE) ,
TRASHED_DT DATE ,
TRASHED_BY VARCHAR2(32 BYTE) ,
TRASHED_IND VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
ORIG_DOC_TYPE_CD VARCHAR2(32 BYTE) ,
ORIG_DOC_FORM_TYPE VARCHAR2(32 BYTE) ,
ORIG_DOC_FORM_TYPE_CD VARCHAR2(32 BYTE) ,
RESEARCH_REQ_IND VARCHAR2(1 BYTE) ,
EXPEDIATED_IND VARCHAR2(1 BYTE) ,
STG_EXTRACT_DATE DATE ,
STG_LAST_UPDATE_DATE DATE ,
FORM_TYPE VARCHAR2(64 BYTE) ,
DOCUMENT_SET_ID NUMBER(18,0) ,
STG_DONE_DATE DATE ,
INSERTED VARCHAR2(1 BYTE) ,
LAST_EVENT_DATE DATE 
)tablespace MAXDAT_DATA;

create table NYHIX_ETL_MAIL_FAX_DOC_WIP_V2
(
EEMFDB_ID NUMBER(18,0) NOT NULL,
INSTANCE_STATUS VARCHAR2(32 BYTE) NOT NULL,
INSTANCE_START_DATE DATE ,
INSTANCE_END_DATE DATE ,
COMPLETE_DT DATE ,
CANCEL_DT DATE ,
CANCEL_BY VARCHAR2(32 BYTE) ,
CANCEL_REASON VARCHAR2(32 BYTE) ,
CANCEL_METHOD VARCHAR2(32 BYTE) ,
DCN VARCHAR2(256 BYTE) NOT NULL,
CREATE_DT DATE NOT NULL,
RECEIVED_DT DATE ,
DOC_TYPE_CD VARCHAR2(32 BYTE) NOT NULL,
PAGE_COUNT NUMBER(18,0) ,
ECN VARCHAR2(256 BYTE) NOT NULL,
CHANNEL VARCHAR2(32 BYTE) NOT NULL,
KOFAX_DCN VARCHAR2(256 BYTE) NOT NULL,
BATCH_ID NUMBER(38,0) NOT NULL,
BATCH_NAME VARCHAR2(256 BYTE) NOT NULL,
DOC_STATUS_CD VARCHAR2(32 BYTE) NOT NULL,
DOC_STATUS VARCHAR2(32 BYTE) ,
DOC_STATUS_DT DATE NOT NULL,
DOC_UPDATE_DT DATE ,
DOC_UPDATED_BY_STAFF_ID VARCHAR2(50 BYTE) ,
DOC_UPDATED_BY VARCHAR2(32 BYTE) ,
APP_DOC_DATA_ID NUMBER(18,0) ,
PRIORITY NUMBER(2,0) ,
FORM_TYPE_CD VARCHAR2(256 BYTE) ,
FREE_FORM_TXT_IND VARCHAR2(1 BYTE) ,
PREVIOUS_KOFAX_DCN VARCHAR2(50 BYTE) ,
SCAN_DT DATE ,
RELEASE_DT DATE ,
APP_DOC_TRACKER_ID NUMBER(18,0) ,
ENV_STATUS_CD VARCHAR2(32 BYTE) ,
ENV_STATUS VARCHAR2(256 BYTE)  default 'Received',
ENV_STATUS_DT DATE ,
SLA_COMPLETE_DT DATE ,
ENV_UPDATE_DT DATE ,
ENV_UPDATED_BY_STAFF_ID VARCHAR2(50 BYTE) ,
ENV_UPDATED_BY VARCHAR2(32 BYTE) ,
SLA_COMPLETE VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
MAXE_ORIGINATION_DT DATE ,
RESCANNED_IND VARCHAR2(1 BYTE) ,
RETURNED_MAIL_IND VARCHAR2(1 BYTE) ,
RETURNED_MAIL_REASON VARCHAR2(32 BYTE) ,
RESCAN_COUNT NUMBER(18,0) ,
NOTE_ID VARCHAR2(32 BYTE) ,
ASF_PROCESS_DOC VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
ASF_CANCEL_DOC VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
UPDATED VARCHAR2(1 BYTE) ,
TRASHED_DT DATE ,
TRASHED_BY VARCHAR2(32 BYTE) ,
TRASHED_IND VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
ORIG_DOC_TYPE_CD VARCHAR2(32 BYTE) ,
ORIG_DOC_FORM_TYPE VARCHAR2(32 BYTE) ,
ORIG_DOC_FORM_TYPE_CD VARCHAR2(32 BYTE) ,
RESEARCH_REQ_IND VARCHAR2(1 BYTE) ,
EXPEDIATED_IND VARCHAR2(1 BYTE) ,
STG_EXTRACT_DATE DATE ,
STG_LAST_UPDATE_DATE DATE ,
FORM_TYPE VARCHAR2(64 BYTE) ,
STG_DONE_DATE DATE ,
INSERTED VARCHAR2(1 BYTE) ,
LAST_EVENT_DATE DATE 
)tablespace MAXDAT_DATA;

create table NYHIX_ETL_MAIL_FAX_DOC_CSC_V2
(
 CSC_DETAIL_ID number(18,0) not null,
 KOFAX_DCN varchar(256) not null, 
 CSC_PROC_STATUS_CD varchar2(256),
 CSC_PROC_ERROR_CD varchar2(256),
 CSC_PROC_DT date
)tablespace MAXDAT_DATA;

create or replace view NYHIX_ETL_MFD_CSC_V2_SV
as select * from NYHIX_ETL_MAIL_FAX_DOC_CSC_V2;

create or replace public synonym NYHIX_ETL_MFD_CSC_V2_SV for NYHIX_ETL_MFD_CSC_V2_SV;
grant select on NYHIX_ETL_MFD_CSC_V2_SV to MAXDAT_READ_ONLY;

create table NYHIX_ETL_MAIL_FAX_DOC_APP_V2
(
 APP_DOC_DATA_ID number(18,0) not null,
 APP_DOC_INDV_ID number(18,0) not null,
 LINK_CREATE_DT date not null, 
 HXID varchar2(64),
 HX_ACCOUNT_ID varchar2(64),
 LINK_UPDATE_DT date
)tablespace MAXDAT_DATA;

create or replace view NYHIX_ETL_MFD_APP_V2_SV
as select * from NYHIX_ETL_MAIL_FAX_DOC_APP_V2;

create or replace public synonym NYHIX_ETL_MFD_APP_V2_SV for NYHIX_ETL_MFD_APP_V2_SV;
grant select on NYHIX_ETL_MFD_APP_V2_SV to MAXDAT_READ_ONLY;

--Create Primary Keys

alter table NYHIX_ETL_MAIL_FAX_DOC_V2 add constraint DCN_PK primary key (DCN);
alter table NYHIX_ETL_MAIL_FAX_DOC_OLTP_V2 add constraint DCN_PK1 primary key (DCN);
alter table NYHIX_ETL_MAIL_FAX_DOC_WIP_V2 add constraint DCN_PK2 primary key (DCN);
alter table NYHIX_ETL_MAIL_FAX_DOC_CSC_V2 add constraint CD_ID_PK primary key (CSC_DETAIL_ID);
alter table NYHIX_ETL_MAIL_FAX_DOC_APP_V2 add constraint ADD_ID_PK primary key (APP_DOC_INDV_ID);

--Create Indexes

create index IDX_MAILFAXDOCOLTP_ADD_ID on NYHIX_ETL_MAIL_FAX_DOC_OLTP_V2 (APP_DOC_DATA_ID) TABLESPACE  MAXDAT_INDX ;
create index IDX_MAILFAXDOCOLTP_DOC_ID on NYHIX_ETL_MAIL_FAX_DOC_OLTP_V2 (DOCUMENT_SET_ID) TABLESPACE  MAXDAT_INDX ;
create index IDX_MAILFAXDOCOLTP_KDCN on NYHIX_ETL_MAIL_FAX_DOC_OLTP_V2 (KOFAX_DCN) TABLESPACE  MAXDAT_INDX ;

create index IDX_MAILFAXDOCCSC_KDCN on NYHIX_ETL_MAIL_FAX_DOC_CSC_V2 (KOFAX_DCN) TABLESPACE  MAXDAT_INDX ;

--GRANTS & PUBLIC SYNONYMNS

create or replace public synonym NYHIX_ETL_MAIL_FAX_DOC_V2 for NYHIX_ETL_MAIL_FAX_DOC_V2;
create or replace public synonym NYHIX_ETL_MAIL_FAX_DOC_OLTP_V2 for NYHIX_ETL_MAIL_FAX_DOC_OLTP_V2;
create or replace public synonym NYHIX_ETL_MAIL_FAX_DOC_WIP_V2 for NYHIX_ETL_MAIL_FAX_DOC_WIP_V2;
create or replace public synonym NYHIX_ETL_MAIL_FAX_DOC_CSC_V2 for NYHIX_ETL_MAIL_FAX_DOC_CSC_V2;
create or replace public synonym NYHIX_ETL_MAIL_FAX_DOC_APP_V2 for NYHIX_ETL_MAIL_FAX_DOC_APP_V2;

grant select on NYHIX_ETL_MAIL_FAX_DOC_V2 to MAXDAT_READ_ONLY;
grant select on NYHIX_ETL_MAIL_FAX_DOC_OLTP_V2 to MAXDAT_READ_ONLY;
grant select on NYHIX_ETL_MAIL_FAX_DOC_WIP_V2 to MAXDAT_READ_ONLY;
grant select on NYHIX_ETL_MAIL_FAX_DOC_CSC_V2 to MAXDAT_READ_ONLY;
grant select on NYHIX_ETL_MAIL_FAX_DOC_APP_V2 to MAXDAT_READ_ONLY;
