CREATE OR REPLACE VIEW DOC_LINK_HIST_SV as
SELECT D.DOC_LINK_HIST_ID,
D.DOCUMENT_ID,
D.LINK_TYPE_CD,
D.AUTO_LINKED_IND,
D.CREATED_BY,
D.CREATE_TS,
D.CASE_ID,
CA.CASE_CIN ACCOUNT_ID,
D.CLIENT_ID,
C.CLNT_CIN HX_ID,
D.LINK_REF_ID
FROM MAXDAT.DOC_LINK_HIST_STG D
LEFT JOIN MAXDAT.CLIENT_STG C ON C.CLNT_CLIENT_ID = D.CLIENT_ID
LEFT JOIN MAXDAT.CASES_STG CA ON CA.CASE_ID = D.CASE_ID
WITH read only;

GRANT SELECT ON DOC_LINK_HIST_SV TO MAXDAT_READ_ONLY;
GRANT SELECT ON DOC_LINK_HIST_SV TO DP_SCORECARD;

