create table control.CFG_PAIEB_SESSION_PARAMS (
PARAM_NAME VARCHAR
, PARAM_VALUE VARCHAR
, PARAM_SQL VARCHAR
, CREATE_NTZ TIMESTAMP_NTZ
);

alter table control.CFG_PAIEB_SESSION_PARAMS add (param_order number(10));

//DELETE FROM CONTROL.CFG_PAIEB_sESSION_PARAMS;

MERGE INTO CONTROL.CFG_PAIEB_SESSION_PARAMS TGT
USING (SELECT 1 PORDER, 'ROLE' PNAME, 'MAXEB_DP4BI_PAIEB_UAT_ADMIN' PVALUE, 'USE ~PN~ ~PV~;' PSQL, CURRENT_TIMESTAMP() PTIME FROM DUAL) SRC
ON SRC.PNAME = TGT.PARAM_NAME
WHEN MATCHED THEN UPDATE SET PARAM_ORDER = PORDER, PARAM_VALUE = PVALUE, PARAM_SQL = PSQL, CREATE_NTZ = PTIME
WHEN NOT MATCHED THEN INSERT (PARAM_ORDER,PARAM_NAME, PARAM_VALUE, PARAM_SQL, CREATE_NTZ)
VALUES (PORDER, PNAME, PVALUE, PSQL, PTIME)
;
MERGE INTO CONTROL.CFG_PAIEB_SESSION_PARAMS TGT
USING (SELECT 3 PORDER, 'DATABASE' PNAME, 'MAXEB_DP4BI_PAIEB_UAT' PVALUE, 'USE ~PN~ ~PV~;' PSQL, CURRENT_TIMESTAMP() PTIME FROM DUAL) SRC
ON SRC.PNAME = TGT.PARAM_NAME
WHEN MATCHED THEN UPDATE SET PARAM_ORDER = PORDER, PARAM_VALUE = PVALUE, PARAM_SQL = PSQL, CREATE_NTZ = PTIME
WHEN NOT MATCHED THEN INSERT (PARAM_ORDER,PARAM_NAME, PARAM_VALUE, PARAM_SQL, CREATE_NTZ)
VALUES (PORDER, PNAME, PVALUE, PSQL, PTIME)
;
MERGE INTO CONTROL.CFG_PAIEB_SESSION_PARAMS TGT
USING (SELECT 2 PORDER, 'WAREHOUSE' PNAME, 'MAXEB_DP4BI_PAIEB_UAT_LOAD_WH' PVALUE, 'USE ~PN~ ~PV~;' PSQL, CURRENT_TIMESTAMP() PTIME FROM DUAL) SRC
ON SRC.PNAME = TGT.PARAM_NAME
WHEN MATCHED THEN UPDATE SET PARAM_ORDER = PORDER, PARAM_VALUE = PVALUE, PARAM_SQL = PSQL, CREATE_NTZ = PTIME
WHEN NOT MATCHED THEN INSERT (PARAM_ORDER,PARAM_NAME, PARAM_VALUE, PARAM_SQL, CREATE_NTZ)
VALUES (PORDER, PNAME, PVALUE, PSQL, PTIME)
;
MERGE INTO CONTROL.CFG_PAIEB_SESSION_PARAMS TGT
USING (SELECT 4 PORDER, 'SCHEMA' PNAME, 'PAIEB_UAT' PVALUE, 'USE ~PN~ ~PV~;' PSQL, CURRENT_TIMESTAMP() PTIME FROM DUAL) SRC
ON SRC.PNAME = TGT.PARAM_NAME
WHEN MATCHED THEN UPDATE SET PARAM_ORDER = PORDER, PARAM_VALUE = PVALUE, PARAM_SQL = PSQL, CREATE_NTZ = PTIME
WHEN NOT MATCHED THEN INSERT (PARAM_ORDER,PARAM_NAME, PARAM_VALUE, PARAM_SQL, CREATE_NTZ)
VALUES (PORDER, PNAME, PVALUE, PSQL, PTIME)
;
MERGE INTO CONTROL.CFG_PAIEB_SESSION_PARAMS TGT
USING (SELECT 5 PORDER, 'DATE_INPUT_FORMAT' PNAME, 'YYYY-MM-DD' PVALUE, 'ALTER SESSION SET ~PN~ = ''~PV~'';' PSQL, CURRENT_TIMESTAMP() PTIME FROM DUAL) SRC
ON SRC.PNAME = TGT.PARAM_NAME
WHEN MATCHED THEN UPDATE SET PARAM_ORDER = PORDER, PARAM_VALUE = PVALUE, PARAM_SQL = PSQL, CREATE_NTZ = PTIME
WHEN NOT MATCHED THEN INSERT (PARAM_ORDER,PARAM_NAME, PARAM_VALUE, PARAM_SQL, CREATE_NTZ)
VALUES (PORDER, PNAME, PVALUE, PSQL, PTIME)
;
MERGE INTO CONTROL.CFG_PAIEB_SESSION_PARAMS TGT
USING (SELECT 6 PORDER, 'TIMESTAMP_INPUT_FORMAT' PNAME, 'YYYY-MM-DD\"T\"HH24:MI:SS.FFTZH:TZM' PVALUE, 'ALTER SESSION SET ~PN~ = ''~PV~'';' PSQL, CURRENT_TIMESTAMP() PTIME FROM DUAL) SRC
ON SRC.PNAME = TGT.PARAM_NAME
WHEN MATCHED THEN UPDATE SET PARAM_ORDER = PORDER, PARAM_VALUE = PVALUE, PARAM_SQL = PSQL, CREATE_NTZ = PTIME
WHEN NOT MATCHED THEN INSERT (PARAM_ORDER,PARAM_NAME, PARAM_VALUE, PARAM_SQL, CREATE_NTZ)
VALUES (PORDER, PNAME, PVALUE, PSQL, PTIME)
;
