CREATE TABLE	NYEC_ETL_PROCESS_APP			(	
CEPA_ID	NUMBER			NOT NULL	,
STAGE_DONE_DATE	DATE				,
STG_EXTRACT_DATE	DATE	DEFAULT	SYSDATE	NOT NULL	,
STG_LAST_UPDATE_DATE	DATE	DEFAULT	SYSDATE	NOT NULL	,
GWF_QC_RQRD	VARCHAR(1)				,
GWF_MISSING_INFO	VARCHAR(1)				,
GWF_PEND_NOTIFY_RQRD	VARCHAR(1)	DEFAULT	'Y'		,
GWF_OUTCM_NOTIFY_RQRD	VARCHAR(1)	DEFAULT	'N'		,
GWF_RESEARCH	VARCHAR(1)				,
GWF_QC_OUTCOME	VARCHAR(1)				,
GWF_NEW_MI	VARCHAR(1)				,
asf_cancel_app	VARCHAR(1)	DEFAULT	'N'	NOT NULL	,
asf_close_app	VARCHAR(1)	DEFAULT	'N'	NOT NULL	,
asf_receive_app	VARCHAR(1)	DEFAULT	'N'	NOT NULL	,
asf_review_enter_data	VARCHAR(1)	DEFAULT	'N'	NOT NULL	,
asf_process_app_info	VARCHAR(1)	DEFAULT	'N'	NOT NULL	,
asf_perform_qc	VARCHAR(1)	DEFAULT	'N'	NOT NULL	,
asf_notify_client_pended_app	VARCHAR(1)	DEFAULT	'N'	NOT NULL	,
asf_receive_process_mi	VARCHAR(1)	DEFAULT	'N'	NOT NULL	,
asf_complete_app	VARCHAR(1)	DEFAULT	'N'	NOT NULL	,
asf_send_outcome_notification	VARCHAR(1)	DEFAULT	'N'	NOT NULL	,
asf_perform_research	VARCHAR(1)	DEFAULT	'N'	NOT NULL	,
asf_wait_state_approval	VARCHAR(1)	DEFAULT	'N'	NOT NULL	,
APP_ID	NUMBER			NOT NULL	,
CHANNEL	VARCHAR2(20)				,
CREATE_DT	DATE			NOT NULL	,
RECEIPT_DT	DATE				,
COMPLETE_DT	DATE				,
AGE_IN_BUSINESS_DAYS	NUMBER			NOT NULL	,
AGE_IN_CALENDAR_DAYS	NUMBER			NOT NULL	,
APP_STATUS	VARCHAR2(50)			NOT NULL	,
APP_STATUS_GROUP	VARCHAR2(30)			NOT NULL	,
APP_CYCLE_START_DT	DATE				,
APP_CYCLE_END_DT	DATE				,
APP_CYCLE_BUS_DAYS	NUMBER				,
APP_CYCLE_CAL_DAYS	NUMBER				,
SLA_DAYS	NUMBER				,
SLA_DAYS_TYPE	VARCHAR(1)				,
SLA_JEOPARDY_DAYS	NUMBER				,
SLA_TARGET_DAYS	NUMBER				,
JEOPARDY_FLAG	VARCHAR(1)	DEFAULT	'N'	NOT NULL	,
TIMELINESS_STATUS	VARCHAR2(20)	DEFAULT	'Not Complete'	NOT NULL	,
RVW_ENTER_DATA_DT	DATE				,
PROCESS_APP_INFO_DT	DATE				,
PERFORM_QC_DT	DATE				,
NOTIFY_CLIENT_PENDED_APP_DT	DATE				,
SEND_OUTCM_NOTIFICATION_DT	DATE				,
CANCEL_FLAG	VARCHAR(1)	DEFAULT	'N'	NOT NULL	,
CANCEL_DATE	DATE				,
APP_TYPE	VARCHAR2(30)				,
QC_TASK_ID	NUMBER				,
COUNTY	VARCHAR2(60)				,
APP_COMPLETE_RESULT	VARCHAR2(50)				,
AUTO_REPROCESS_FLAG	VARCHAR2(1)				,
INSTANCE_COMPLETE_DT	DATE				,
INSTANCE_STATUS	VARCHAR2(10)	DEFAULT	 'Active'	NOT NULL	,
LAST_MAIL_DT	DATE				,
MI_RECEIVED_TASK_COUNT	NUMBER			NOT NULL	,
REFER_LDSS_FLAG	VARCHAR2(1)	DEFAULT	 'N'	NOT NULL	,
SLA_JEOPARDY_DT	DATE				,
STATE_REVIEW_TASK_COUNT	NUMBER			NOT NULL	,
CLOCKDOWN_INDICATOR	VARCHAR2(1)				,
DE_TASK_ID	NUMBER				,
HEART_APP_STATUS	VARCHAR2(50)				,
PERFORM_RESEARCH_DT	DATE				,
RESEARCH_REASON	VARCHAR2(50)				,
RESEARCH_TASK_ID	NUMBER				,
STATE_REVIEW_TASK_ID	NUMBER				,
WAIT_STATE_APPROVAL_DT	DATE				,
ELIGIBILITY_ACTION	VARCHAR2(20)				,
CURRENT_TASK_ID	NUMBER				,
ASSD_CANCEL_APP	DATE				,
ASSD_CLOSE_APP	DATE				,
ASSD_RECEIVE_APP	DATE				,
ASSD_RVW_ENTER_DATA	DATE				,
ASSD_PROCESS_APP_INFO	DATE				,
ASSD_PERFORM_QC	DATE				,
ASSD_PERFORM_RESEARCH	DATE				,
ASSD_NOTIFY_CLIENT_PENDED_APP	DATE				,
ASSD_RECEIVE_PROCESS_MI	DATE				,
ASSD_WAIT_STATE_APPROVAL	DATE				,
ASSD_COMPLETE_APP	DATE				,
ASSD_SEND_OUTCOME_NOTIFICATION	DATE				,
ASED_CANCEL_APP	DATE				,
ASED_CLOSE_APP	DATE				,
ASED_RECEIVE_APP	DATE				,
ASED_RVW_ENTER_DATA	DATE				,
ASED_PROCESS_APP_INFO	DATE				,
ASED_PERFORM_QC	DATE				,
ASED_PERFORM_RESEARCH	DATE				,
ASED_NOTIFY_CLIENT_PENDED_APP	DATE				,
ASED_RECEIVE_PROCESS_MI	DATE				,
ASED_WAIT_STATE_APPROVAL	DATE				,
ASED_COMPLETE_APP	DATE				,
ASED_SEND_OUTCOME_NOTIFICATION	DATE				,
ASPB_CANCEL_APP	VARCHAR2(100)				,
ASPB_CLOSE_APP	VARCHAR2(100)				,
ASPB_COMPLETE_APP	VARCHAR2(100)				,
ASPB_NOTIFY_CLIENT_PENDED_APP	VARCHAR2(100)				,
ASPB_PERFORM_QC	VARCHAR2(100)				,
ASPB_PERFORM_RESEARCH	VARCHAR2(100)				,
ASPB_PROCESS_APP_INFO	VARCHAR2(100)				,
ASPB_RECEIVE_PROCESS_MI	VARCHAR2(100)				,
ASPB_RECEIVE_APP	VARCHAR2(100)				,
ASPB_RVW_ENTER_DATA	VARCHAR2(100)				,
ASPB_SEND_OUTCOME_NOTIFICATION	VARCHAR2(100)				,
ASPB_WAIT_STATE_APPROVAL	VARCHAR2(100)				,
HEART_SYNCH_FLAG  VARCHAR2(1) DEFAULT	 'N' not null);

ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_GWF_QC_RQRD	CHECK (	GWF_QC_RQRD	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_GWF_MISSING_INFO	CHECK (	GWF_MISSING_INFO	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_GWF_PEND_NOTIFY_RQRD	CHECK (	GWF_PEND_NOTIFY_RQRD	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_GWF_OUTCM_NOTIFY_RQRD	CHECK (	GWF_OUTCM_NOTIFY_RQRD	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_GWF_RESEARCH	CHECK (	GWF_RESEARCH	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_GWF_QC_OUTCOME	CHECK (	GWF_QC_OUTCOME	IN(	 'R','L','C'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_GWF_NEW_MI	CHECK (	GWF_NEW_MI	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_asf_cancel_app	CHECK (	asf_cancel_app	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_asf_close_app	CHECK (	asf_close_app	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_asf_receive_app	CHECK (	asf_receive_app	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_asf_review_enter_data	CHECK (	asf_review_enter_data	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_asf_process_app_info	CHECK (	asf_process_app_info	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_asf_perform_qc	CHECK (	asf_perform_qc	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_asf_notify_clnt_pnd_app	CHECK (	asf_notify_client_pended_app	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_asf_receive_process_mi	CHECK (	asf_receive_process_mi	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_asf_complete_app	CHECK (	asf_complete_app	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_asf_send_out_notif	CHECK (	asf_send_outcome_notification	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_asf_perform_research	CHECK (	asf_perform_research	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_asf_wait_state_approval	CHECK (	asf_wait_state_approval	IN(	 'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_APP_STATUS_GROUP	CHECK (	APP_STATUS_GROUP	IN(	'Renewal Initiated',
'Received',
'In Process',
'Awaiting Missing Information',
'Done',
'Cancelled'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_APP_COMPLETE_RESULT	CHECK (	APP_COMPLETE_RESULT	IN(	'Eligible',
'Ineligible',
'Referred to District',
'Withdrawn from HEART',
'Disregarded',
'Deleted',
'Not Received Prior to Authorization'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_INSTANCE_STATUS	CHECK (	INSTANCE_STATUS	IN(	 'Active','Complete'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_REFER_LDSS_FLAG	CHECK (	REFER_LDSS_FLAG	IN(	'Y','N'	));
ALTER TABLE 	NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_ELIGIBILITY_ACTION	CHECK (	ELIGIBILITY_ACTION	IN(	 'Renewed','Not Renewed'	));
ALTER TABLE   NYEC_ETL_PROCESS_APP	 add CONSTRAINT CHECK_HEART_SYNCH_FLAG	CHECK (	HEART_SYNCH_FLAG	IN(	 'Y','N'	));

COMMENT ON COLUMN 	NYEC_ETL_PROCESS_APP.STAGE_DONE_DATE	IS 'Indicates the date ETL processing stopped for this record.';
COMMENT ON COLUMN 	NYEC_ETL_PROCESS_APP.STG_EXTRACT_DATE	IS 'On INSERT only, sets the current system date that the record was created.';
COMMENT ON COLUMN 	NYEC_ETL_PROCESS_APP.STG_LAST_UPDATE_DATE	IS 'On INSERT or UPDATE, sets the current system date that the record was created or updated.';
COMMENT ON COLUMN   NYEC_ETL_PROCESS_APP.NOTIFY_CLIENT_PENDED_APP_DT IS 'Date the notification of MI was sent.';
COMMENT ON COLUMN   NYEC_ETL_PROCESS_APP.HEART_SYNCH_FLAG IS 'Indicates if MAXe is in-synch with the HEART system. If this value is "N", then it indicates that there is an issue with MAXe and HEART data synchronization which may prevent certain work from being completed by Maximus until the issue is resolved.';

