   ALTER SESSION SET CURRENT_SCHEMA = FOLSOM_SHARED_CC;
   
   CREATE TABLE "CC_S_TMP_ACD_INTERVAL" 
     (	"ACD_INTERVAL_ID" NUMBER(19,0) NOT NULL ENABLE, 
  	"INTERVAL_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
  	"CONTACT_QUEUE_ID" NUMBER(19,0) NOT NULL ENABLE, 
  	"INTERVAL_ID" NUMBER(19,0) NOT NULL ENABLE, 
  	"AGENT_ID" NUMBER(19,0) NOT NULL ENABLE, 
  	"CONTACTS_RECEIVED_FROM_IVR" NUMBER(7,0) DEFAULT NULL, 
  	"CONTACTS_OFFERED" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"CONTACTS_HANDLED" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"CONTACTS_ABANDONED" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"MIN_HANDLE_TIME" NUMBER(11,2) DEFAULT NULL, 
  	"MAX_HANDLE_TIME" NUMBER(11,2) DEFAULT NULL, 
  	"MEAN_HANDLE_TIME" NUMBER(11,2) DEFAULT NULL, 
  	"MEDIAN_HANDLE_TIME" NUMBER(11,2) DEFAULT NULL, 
  	"STDDEV_HANDLE_TIME" NUMBER(11,2) DEFAULT NULL, 
  	"MIN_SPEED_TO_HANDLE" NUMBER(11,2) DEFAULT NULL, 
  	"MAX_SPEED_TO_HANDLE" NUMBER(12,2) DEFAULT NULL, 
  	"MEAN_SPEED_TO_HANDLE" NUMBER(12,2) DEFAULT NULL, 
  	"MEDIAN_SPEED_TO_HANDLE" NUMBER(12,2) DEFAULT NULL, 
  	"STDDEV_SPEED_TO_HANDLE" NUMBER(11,2) DEFAULT NULL, 
  	"MIN_SPEED_OF_ANSWER" NUMBER(11,2) DEFAULT NULL, 
  	"MAX_SPEED_OF_ANSWER" NUMBER(12,2) DEFAULT NULL, 
  	"MEAN_SPEED_OF_ANSWER" NUMBER(12,2) DEFAULT NULL, 
  	"MEDIAN_SPEED_OF_ANSWER" NUMBER(12,2) DEFAULT NULL, 
  	"STDDEV_SPEED_OF_ANSWER" NUMBER(11,2) DEFAULT NULL, 
  	"SPEED_OF_ANSWER_PERIOD_1" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"SPEED_OF_ANSWER_PERIOD_2" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"SPEED_OF_ANSWER_PERIOD_3" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"SPEED_OF_ANSWER_PERIOD_4" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"SPEED_OF_ANSWER_PERIOD_5" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"SPEED_OF_ANSWER_PERIOD_6" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"SPEED_OF_ANSWER_PERIOD_7" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"SPEED_OF_ANSWER_PERIOD_8" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"SPEED_OF_ANSWER_PERIOD_9" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"SPEED_OF_ANSWER_PERIOD_10" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"CALLS_ABANDONED_PERIOD_1" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"CALLS_ABANDONED_PERIOD_2" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"CALLS_ABANDONED_PERIOD_3" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"CALLS_ABANDONED_PERIOD_4" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"CALLS_ABANDONED_PERIOD_5" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"CALLS_ABANDONED_PERIOD_6" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"CALLS_ABANDONED_PERIOD_7" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"CALLS_ABANDONED_PERIOD_8" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"CALLS_ABANDONED_PERIOD_9" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"CALLS_ABANDONED_PERIOD_10" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"LABOR_MINUTES_TOTAL" NUMBER(10,2) DEFAULT NULL, 
  	"LABOR_MINUTES_WAITING" NUMBER(10,2) DEFAULT NULL, 
  	"HEADCOUNT_AVAILABLE" NUMBER(7,2) DEFAULT 0 NOT NULL ENABLE, 
  	"CONTACT_INVENTORY" NUMBER(7,0) DEFAULT NULL, 
  	"CONTACT_INVENTORY_JEOPARDY" NUMBER(7,0) DEFAULT NULL, 
  	"CONTACT_INVENTORY_AGE_TOTAL" NUMBER(5,2) DEFAULT NULL, 
  	"MIN_CONTACT_INVENTORY_AGE" NUMBER(5,2) DEFAULT NULL, 
  	"MAX_CONTACT_INVENTORY_AGE" NUMBER(5,2) DEFAULT NULL, 
  	"MEAN_CONTACT_INVENTORY_AGE" NUMBER(5,2) DEFAULT NULL, 
  	"MEDIAN_CONTACT_INVENTORY_AGE" NUMBER(5,2) DEFAULT NULL, 
  	"STDDEV_CONTACT_INVENTORY_AGE" NUMBER(5,2) DEFAULT NULL, 
  	"CONTACTS_TRANSFERRED" NUMBER(7,0) DEFAULT NULL, 
  	"OUTFLOW_CONTACTS" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"ANSWER_WAIT_TIME_TOTAL" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE, 
  	"ABANDON_TIME_TOTAL" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE, 
  	"TALK_TIME_TOTAL" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE, 
  	"AFTER_CALL_WORK_TIME_TOTAL" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE, 
  	"SERVICE_LEVEL_ANSWERED_PERCENT" NUMBER(5,2) DEFAULT 0 NOT NULL ENABLE, 
  	"SERVICE_LEVEL_ANSWERED_COUNT" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
  	"SERVICE_LEVEL_ABANDONED" NUMBER(5,2) DEFAULT 0, 
  	"CALLS_ON_HOLD" NUMBER(7,0) DEFAULT NULL, 
  	"HOLD_TIME_TOTAL" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE, 
  	"IVR_TIME_TOTAL" NUMBER(12,2) DEFAULT NULL, 
  	"SHORT_ABANDONS" NUMBER(7,0) DEFAULT NULL, 
  	"CONTACTS_BLOCKED" NUMBER(7,0) DEFAULT NULL, 
  	"ICR_DEFAULT_ROUTED" NUMBER(7,0) DEFAULT NULL, 
  	"NETWORK_DEFAULT_ROUTED" NUMBER(7,0) DEFAULT NULL, 
  	"RETURN_BUSY" NUMBER(7,0) DEFAULT NULL, 
  	"CALLS_RONA" NUMBER(7,0) DEFAULT NULL, 
  	"RETURN_RELEASE" NUMBER(7,0) DEFAULT NULL, 
  	"CALLS_ROUTED_NON_AGENT" NUMBER(7,0) DEFAULT NULL, 
  	"ERROR_COUNT" NUMBER(7,0) DEFAULT NULL, 
  	"AGENT_ERROR_COUNT" NUMBER(7,0) DEFAULT NULL, 
  	"RETURN_RING" NUMBER(7,0) DEFAULT NULL, 
  	"INCOMPLETE_CALLS" NUMBER(7,0) DEFAULT NULL, 
  	"CALLS_GIVEN_FORCE_DISCONNECT" NUMBER(7,0) DEFAULT NULL, 
  	"CALLS_GIVEN_ROUTE_TO" NUMBER(7,0) DEFAULT NULL, 
  	"CALL_TYPE" VARCHAR2(200 BYTE), 
  	"EXTRACT_DT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
  	"LAST_UPDATE_DT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
  	"LAST_UPDATE_BY" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
  	"MAX_ABANDON_TIME" NUMBER DEFAULT NULL, 
  	"ABANDON_THRESHOLD" NUMBER(7,0) DEFAULT NULL, 
  	"SHORT_CALLS" NUMBER(7,0) DEFAULT NULL, 
  	"MAX_CALLS_QUEUED" NUMBER(7,0) DEFAULT NULL);
   
   
   CREATE SEQUENCE SEQ_CC_S_TMP_ACD_INTERVAL;
   
  CREATE TABLE "CC_S_TMP_ACD_QUEUE_INTERVAL" 
   (	"ACD_QUEUE_INTERVAL_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"INTERVAL_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CONTACT_QUEUE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"INTERVAL_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CONTACTS_RECEIVED_FROM_IVR" NUMBER(7,0) DEFAULT NULL, 
	"CONTACTS_OFFERED" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"CONTACTS_HANDLED" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"CONTACTS_ABANDONED" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"MIN_HANDLE_TIME" NUMBER(11,2) DEFAULT NULL, 
	"MAX_HANDLE_TIME" NUMBER(11,2) DEFAULT NULL, 
	"MEAN_HANDLE_TIME" NUMBER(11,2) DEFAULT NULL, 
	"MEDIAN_HANDLE_TIME" NUMBER(11,2) DEFAULT NULL, 
	"STDDEV_HANDLE_TIME" NUMBER(11,2) DEFAULT NULL, 
	"MIN_SPEED_TO_HANDLE" NUMBER(11,2) DEFAULT NULL, 
	"MAX_SPEED_TO_HANDLE" NUMBER(11,2) DEFAULT NULL, 
	"MEAN_SPEED_TO_HANDLE" NUMBER(11,2) DEFAULT NULL, 
	"MEDIAN_SPEED_TO_HANDLE" NUMBER(11,2) DEFAULT NULL, 
	"STDDEV_SPEED_TO_HANDLE" NUMBER(11,2) DEFAULT NULL, 
	"MIN_SPEED_OF_ANSWER" NUMBER(11,2) DEFAULT NULL, 
	"MAX_SPEED_OF_ANSWER" NUMBER(11,2) DEFAULT NULL, 
	"MEAN_SPEED_OF_ANSWER" NUMBER(11,2) DEFAULT NULL, 
	"MEDIAN_SPEED_OF_ANSWER" NUMBER(11,2) DEFAULT NULL, 
	"STDDEV_SPEED_OF_ANSWER" NUMBER(11,2) DEFAULT NULL, 
	"SPEED_OF_ANSWER_PERIOD_1" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"SPEED_OF_ANSWER_PERIOD_2" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"SPEED_OF_ANSWER_PERIOD_3" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"SPEED_OF_ANSWER_PERIOD_4" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"SPEED_OF_ANSWER_PERIOD_5" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"SPEED_OF_ANSWER_PERIOD_6" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"SPEED_OF_ANSWER_PERIOD_7" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"SPEED_OF_ANSWER_PERIOD_8" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"SPEED_OF_ANSWER_PERIOD_9" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"SPEED_OF_ANSWER_PERIOD_10" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"CALLS_ABANDONED_PERIOD_1" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"CALLS_ABANDONED_PERIOD_2" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"CALLS_ABANDONED_PERIOD_3" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"CALLS_ABANDONED_PERIOD_4" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"CALLS_ABANDONED_PERIOD_5" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"CALLS_ABANDONED_PERIOD_6" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"CALLS_ABANDONED_PERIOD_7" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"CALLS_ABANDONED_PERIOD_8" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"CALLS_ABANDONED_PERIOD_9" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"CALLS_ABANDONED_PERIOD_10" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"LABOR_MINUTES_TOTAL" NUMBER(10,2) DEFAULT NULL, 
	"LABOR_MINUTES_WAITING" NUMBER(10,2) DEFAULT NULL, 
	"HEADCOUNT_AVAILABLE" NUMBER(7,2) DEFAULT 0 NOT NULL ENABLE, 
	"CONTACT_INVENTORY" NUMBER(7,0) DEFAULT NULL, 
	"CONTACT_INVENTORY_JEOPARDY" NUMBER(7,0) DEFAULT NULL, 
	"CONTACT_INVENTORY_AGE_TOTAL" NUMBER(5,2) DEFAULT NULL, 
	"MIN_CONTACT_INVENTORY_AGE" NUMBER(5,2) DEFAULT NULL, 
	"MAX_CONTACT_INVENTORY_AGE" NUMBER(5,2) DEFAULT NULL, 
	"MEAN_CONTACT_INVENTORY_AGE" NUMBER(5,2) DEFAULT NULL, 
	"MEDIAN_CONTACT_INVENTORY_AGE" NUMBER(5,2) DEFAULT NULL, 
	"STDDEV_CONTACT_INVENTORY_AGE" NUMBER(5,2) DEFAULT NULL, 
	"CONTACTS_TRANSFERRED" NUMBER(7,0) DEFAULT NULL, 
	"OUTFLOW_CONTACTS" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"ANSWER_WAIT_TIME_TOTAL" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE, 
	"ABANDON_TIME_TOTAL" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE, 
	"TALK_TIME_TOTAL" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE, 
	"AFTER_CALL_WORK_TIME_TOTAL" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE, 
	"SERVICE_LEVEL_ANSWERED_PERCENT" NUMBER(5,2) DEFAULT 0 NOT NULL ENABLE, 
	"SERVICE_LEVEL_ANSWERED_COUNT" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"SERVICE_LEVEL_ABANDONED" NUMBER(5,2) DEFAULT 0, 
	"CALLS_ON_HOLD" NUMBER(7,0) DEFAULT NULL, 
	"HOLD_TIME_TOTAL" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE, 
	"IVR_TIME_TOTAL" NUMBER(12,2) DEFAULT NULL, 
	"SHORT_ABANDONS" NUMBER(7,0) DEFAULT NULL, 
	"CONTACTS_BLOCKED" NUMBER(7,0) DEFAULT NULL, 
	"ICR_DEFAULT_ROUTED" NUMBER(7,0) DEFAULT NULL, 
	"NETWORK_DEFAULT_ROUTED" NUMBER(7,0) DEFAULT NULL, 
	"RETURN_BUSY" NUMBER(7,0) DEFAULT NULL, 
	"CALLS_RONA" NUMBER(7,0) DEFAULT NULL, 
	"RETURN_RELEASE" NUMBER(7,0) DEFAULT NULL, 
	"CALLS_ROUTED_NON_AGENT" NUMBER(7,0) DEFAULT NULL, 
	"ERROR_COUNT" NUMBER(7,0) DEFAULT NULL, 
	"AGENT_ERROR_COUNT" NUMBER(7,0) DEFAULT NULL, 
	"RETURN_RING" NUMBER(7,0) DEFAULT NULL, 
	"INCOMPLETE_CALLS" NUMBER(7,0) DEFAULT NULL, 
	"CALLS_GIVEN_FORCE_DISCONNECT" NUMBER(7,0) DEFAULT NULL, 
	"CALLS_GIVEN_ROUTE_TO" NUMBER(7,0) DEFAULT NULL, 
	"CALL_TYPE" VARCHAR2(200 BYTE), 
	"EXTRACT_DT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"LAST_UPDATE_DT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"LAST_UPDATE_BY" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"MAX_ABANDON_TIME" NUMBER DEFAULT NULL, 
	"ABANDON_THRESHOLD" NUMBER(7,0) DEFAULT NULL, 
	"SHORT_CALLS" NUMBER(7,0) DEFAULT NULL, 
	"MAX_CALLS_QUEUED" NUMBER(7,0) DEFAULT NULL
	) ;

   
   CREATE SEQUENCE SEQ_CC_S_TMP_ACD_QUEUE_INT;

 CREATE TABLE "CC_S_TMP_ACD_AGENT_ACTIVITY" 
   (	"ACD_AGENT_ACTIVITY_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"AGENT_CALLS_DT" DATE NOT NULL ENABLE, 
	"AGENT_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"LOGIN_SECONDS" NUMBER(10,2) DEFAULT 0 NOT NULL ENABLE, 
	"EXTERNAL_SECONDS" NUMBER(10,2) DEFAULT 0 NOT NULL ENABLE, 
	"INTERNAL_SECONDS" NUMBER(10,2) DEFAULT 0 NOT NULL ENABLE, 
	"IDLE_SECONDS" NUMBER(10,2) DEFAULT 0 NOT NULL ENABLE, 
	"NOT_READY_SECONDS" NUMBER(10,2) DEFAULT 0 NOT NULL ENABLE, 
	"ACD_TALK_SECONDS" NUMBER(10,2) NOT NULL ENABLE, 
	"HOLD_SECONDS" NUMBER(10,2) NOT NULL ENABLE, 
	"AFTER_CALL_WORK_SECONDS" NUMBER(10,2) NOT NULL ENABLE, 
	"TALK_RESERVE_SECONDS" NUMBER(10,2), 
	"RING_SECONDS" NUMBER(10,2) NOT NULL ENABLE, 
	"PREDICTIVE_TALK_SECONDS" NUMBER(10,2), 
	"PREVIEW_TALK_SECONDS" NUMBER(10,2), 
	"ACD_CALLS_COUNT" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"EXTERNAL_CALLS_COUNT" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"INTERNAL_CALLS_COUNT" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"PREDICTIVE_CALLS_COUNT" NUMBER(10,0), 
	"PREVIEW_CALLS_COUNT" NUMBER(10,0), 
	"BREAK_TIME" NUMBER(10,2), 
	"CONSULTATION_TIME" NUMBER(10,2), 
	"WALKAWAY_TIME" NUMBER(10,2), 
	"BUSYONDNTIME" NUMBER(10,2), 
	"EXTRACT_DT" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_DT" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_BY" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"SHORT_CALLS" NUMBER(10,0), 
	"CALLS_RETURNED_TO_QUEUE" NUMBER(10,0));


   CREATE SEQUENCE SEQ_CC_S_TMP_ACD_AGENT_ACT;
   
   
CREATE TABLE "CC_S_TMP_ACD_AGENT_INTERVAL" 
   (	"ACD_AGENT_INTERVAL_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"INTERVAL_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CONTACT_QUEUE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"AGENT_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"INTERVAL_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CONTACTS_OFFERED" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"CONTACTS_HANDLED" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"CONTACTS_ABANDONED" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
	"CONTACTS_TRANSFERRED" NUMBER(7,0) DEFAULT NULL, 
	"MIN_HANDLE_TIME" NUMBER(11,2) DEFAULT NULL, 
	"MAX_HANDLE_TIME" NUMBER(11,2) DEFAULT NULL, 
	"MEAN_HANDLE_TIME" NUMBER(11,2) DEFAULT NULL, 
	"MEDIAN_HANDLE_TIME" NUMBER(11,2) DEFAULT NULL, 
	"STDDEV_HANDLE_TIME" NUMBER(11,2) DEFAULT NULL, 
	"WAIT_TIME_TOTAL" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE, 
	"TALK_TIME_TOTAL" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE, 
	"AFTER_CALL_WORK_TIME_TOTAL" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE, 
	"HOLD_TIME_TOTAL" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE, 
	"EXTRACT_DT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"LAST_UPDATE_DT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"LAST_UPDATE_BY" VARCHAR2(30 BYTE) NOT NULL ENABLE);
 

   CREATE SEQUENCE SEQ_CC_S_TMP_ACD_AGENT_INT;
   
   
 CREATE TABLE "CC_S_TMP_AGENT_WORK_DAY" 
   (	"AGENT_WORK_DAY_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"AGENT_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"WORK_DATE" DATE NOT NULL ENABLE, 
	"FIRST_LOGIN" DATE, 
	"LAST_LOGOUT" DATE, 
	"SCHEDULED_SHIFT_MINUTES" NUMBER(10,2) DEFAULT NULL, 
	"ACTUAL_SHIFT_MINUTES" NUMBER(10,2) DEFAULT NULL, 
	"ACTUAL_OVERTIME_MINUTES" NUMBER(10,2) DEFAULT NULL, 
	"EXTRACT_DT" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_DT" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_BY" VARCHAR2(30 BYTE) NOT NULL ENABLE);

   
   CREATE SEQUENCE SEQ_CC_S_TMP_AGENT_WORK_DAY;
   
      CREATE OR REPLACE TRIGGER BIU_CC_S_TMP_AGENT_WORK_DAY
          BEFORE INSERT OR UPDATE ON CC_S_TMP_AGENT_WORK_DAY
          FOR EACH ROW
      BEGIN
      IF INSERTING AND :NEW.AGENT_WORK_DAY_ID IS NULL THEN
                SELECT SEQ_CC_S_TMP_AGENT_WORK_DAY.NEXTVAL INTO :NEW.AGENT_WORK_DAY_ID FROM DUAL;
      END IF;
      IF INSERTING THEN
                :NEW.EXTRACT_DT := SYSDATE;
      END IF;
      IF :NEW.LAST_UPDATE_BY IS NULL THEN
                :NEW.LAST_UPDATE_BY := USER;
      END IF;
      :NEW.LAST_UPDATE_DT := SYSDATE;
END;

  CREATE TABLE "CC_S_TMP_WFM_AGENT_ACTIVITY" 
   (	"WFM_AGENT_ACTIVITY_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"AGENT_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ACTIVITY_TYPE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ACTIVITY_START_TIME" DATE, 
	"ACTIVITY_END_TIME" DATE, 
	"ACTIVITY_DURATION_SECONDS" NUMBER(15,2) DEFAULT 0 NOT NULL ENABLE, 
	"ACTIVITY_DT" DATE NOT NULL ENABLE, 
	"EXTRACT_DT" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_DT" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_BY" VARCHAR2(30 BYTE) NOT NULL ENABLE);
	
CREATE SEQUENCE SEQ_CC_S_TMP_WFM_AGENT_ACT;

  CREATE TABLE "CC_S_TMP_AGENTS" 
   (	"AGENT_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"LOGIN_ID" NVARCHAR2(100) NOT NULL ENABLE, 
	"PROJECT_CONFIG_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"MIDDLE_INITIAL" VARCHAR2(20 BYTE), 
	"JOB_TITLE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"LANGUAGE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SITE_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"HOURLY_RATE" NUMBER(5,2) DEFAULT 0 NOT NULL ENABLE, 
	"RATE_CURRENCY" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"AGENT_GROUP" VARCHAR2(50 BYTE), 
	"EXTRACT_DT" DATE NOT NULL ENABLE, 
	"HIRE_DATE" DATE, 
	"TERMINATION_DATE" DATE, 
	"LAST_UPDATE_DT" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_BY" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"RECORD_EFF_DT" DATE, 
	"RECORD_END_DT" DATE, 
	"SITE_DESCRIPTION" VARCHAR2(200 BYTE) NOT NULL ENABLE);

CREATE SEQUENCE SEQ_CC_S_TMP_AGENTS;

  CREATE TABLE CC_S_TMP_AGENT_SUPERVISOR 
   (	AGENT_SUPERVISOR_ID NUMBER(19,0) NOT NULL , 
	AGENT_ID NUMBER(19,0) NOT NULL , 
	SUPERVISOR_AGENT_ID NUMBER(19,0) NOT NULL , 
	EXTRACT_DT DATE NOT NULL , 
	RECORD_EFF_DT DATE NOT NULL , 
	RECORD_END_DT DATE NOT NULL 
   ) ;

CREATE SEQUENCE SEQ_CC_S_TMP_AGENT_SUP;

      CREATE OR REPLACE TRIGGER BIU_CC_S_TMP_ACD_INTERVAL
       BEFORE INSERT OR UPDATE ON CC_S_TMP_ACD_INTERVAL
       FOR EACH ROW
   BEGIN
   IF INSERTING AND :NEW.ACD_INTERVAL_ID IS NULL THEN
             SELECT SEQ_CC_S_TMP_ACD_INTERVAL.NEXTVAL INTO :NEW.ACD_INTERVAL_ID FROM DUAL;
   END IF;
   IF INSERTING THEN
             :NEW.EXTRACT_DT := SYSDATE;
   END IF;
   IF :NEW.LAST_UPDATE_BY IS NULL THEN
             :NEW.LAST_UPDATE_BY := USER;
   END IF;
   :NEW.LAST_UPDATE_DT := SYSDATE;
END;
/

   CREATE OR REPLACE TRIGGER BIU_CC_S_TMP_ACD_QUEUE_INT
   BEFORE INSERT OR UPDATE ON CC_S_TMP_ACD_QUEUE_INTERVAL
       FOR EACH ROW
   BEGIN
   IF INSERTING AND :NEW.ACD_QUEUE_INTERVAL_ID IS NULL THEN
             SELECT SEQ_CC_S_TMP_ACD_QUEUE_INT.NEXTVAL INTO :NEW.ACD_QUEUE_INTERVAL_ID FROM DUAL;
   END IF;
   IF INSERTING THEN
             :NEW.EXTRACT_DT := SYSDATE;
   END IF;
   IF :NEW.LAST_UPDATE_BY IS NULL THEN
             :NEW.LAST_UPDATE_BY := USER;
   END IF;
   :NEW.LAST_UPDATE_DT := SYSDATE;
END;
/

   CREATE OR REPLACE TRIGGER BIU_CC_S_TMP_ACD_AGENT_ACT
       BEFORE INSERT OR UPDATE ON CC_S_TMP_ACD_AGENT_ACTIVITY
       FOR EACH ROW
   BEGIN
   IF INSERTING AND :NEW.ACD_AGENT_ACTIVITY_ID IS NULL THEN
             SELECT SEQ_CC_S_TMP_ACD_AGENT_ACT.NEXTVAL INTO :NEW.ACD_AGENT_ACTIVITY_ID FROM DUAL;
   END IF;
   IF INSERTING THEN
             :NEW.EXTRACT_DT := SYSDATE;
   END IF;
   IF :NEW.LAST_UPDATE_BY IS NULL THEN
             :NEW.LAST_UPDATE_BY := USER;
   END IF;
   :NEW.LAST_UPDATE_DT := SYSDATE;
END;
/

   CREATE OR REPLACE TRIGGER BIU_CC_S_TMP_ACD_AGENT_INT
       BEFORE INSERT OR UPDATE ON CC_S_TMP_ACD_AGENT_INTERVAL
       FOR EACH ROW
   BEGIN
   IF INSERTING AND :NEW.ACD_AGENT_INTERVAL_ID IS NULL THEN
             SELECT SEQ_CC_S_TMP_ACD_AGENT_INT.NEXTVAL INTO :NEW.ACD_AGENT_INTERVAL_ID FROM DUAL;
   END IF;
   IF INSERTING THEN
             :NEW.EXTRACT_DT := SYSDATE;
   END IF;
   IF :NEW.LAST_UPDATE_BY IS NULL THEN
             :NEW.LAST_UPDATE_BY := USER;
   END IF;
   :NEW.LAST_UPDATE_DT := SYSDATE;
END;
/

      CREATE OR REPLACE TRIGGER BIU_CC_S_TMP_WFM_AGENT_ACT
          BEFORE INSERT OR UPDATE ON CC_S_TMP_WFM_AGENT_ACTIVITY
          FOR EACH ROW
      BEGIN
      IF INSERTING AND :NEW.WFM_AGENT_ACTIVITY_ID IS NULL THEN
                SELECT SEQ_CC_S_TMP_WFM_AGENT_ACT.NEXTVAL INTO :NEW.WFM_AGENT_ACTIVITY_ID FROM DUAL;
      END IF;
      IF INSERTING THEN
                :NEW.EXTRACT_DT := SYSDATE;
      END IF;
      IF :NEW.LAST_UPDATE_BY IS NULL THEN
                :NEW.LAST_UPDATE_BY := USER;
      END IF;
      :NEW.LAST_UPDATE_DT := SYSDATE;
END;
/

    CREATE OR REPLACE TRIGGER BIU_CC_S_TMP_AGENTS
          BEFORE INSERT OR UPDATE ON CC_S_TMP_AGENTS
          FOR EACH ROW
      BEGIN
      IF INSERTING AND :NEW.AGENT_ID IS NULL THEN
                SELECT SEQ_CC_S_TMP_AGENTS.NEXTVAL INTO :NEW.AGENT_ID FROM DUAL;
      END IF;
      IF INSERTING THEN
                :NEW.EXTRACT_DT := SYSDATE;
      END IF;
      IF :NEW.LAST_UPDATE_BY IS NULL THEN
                :NEW.LAST_UPDATE_BY := USER;
      END IF;
      :NEW.LAST_UPDATE_DT := SYSDATE;
END;
/

      CREATE OR REPLACE TRIGGER BIU_CC_S_TMP_AGENT_SUP
          BEFORE INSERT OR UPDATE ON CC_S_TMP_AGENT_SUPERVISOR
          FOR EACH ROW
      BEGIN
      IF INSERTING AND :NEW.AGENT_SUPERVISOR_ID IS NULL THEN
                SELECT SEQ_CC_S_TMP_AGENT_SUP.NEXTVAL INTO :NEW.AGENT_SUPERVISOR_ID FROM DUAL;
      END IF;
END;
/