Truncate table MAXDAT.D_CES_LOGIN;



  CREATE OR REPLACE FORCE EDITIONABLE VIEW "MAXDAT"."D_CES_LOGIN_SV" ("FIRST_NAME", "LAST_NAME", "EXT_STAFF_NUM", "STAFF_TYPE_CODE", "ACTION", "ATTEMPTS_WHILE_LOCKED", "CREATED_BY", "INVALID_LOGINS", "SEC_USER_ID", "CREATE_TS", "STAFF_NUMBER", "AGENT_WFM_ID", "EMPLOYEE_ID", "MANAGEMENT_UNIT_DATE", "SCHEDULE_START_MU_DATETIME","SCHEDULE_END_MU_DATETIME","RECORD_STATUS") AS 
  (
	SELECT FIRST_NAME, 
	LAST_NAME , 
	EXT_STAFF_NUM , 
	STAFF_TYPE_CODE , 
	ACTION , 
	ATTEMPTS_WHILE_LOCKED, 
	CREATED_BY , 
	INVALID_LOGINS, 
	SEC_USER_ID, 
	CREATE_TS, 
	STAFF_NUMBER, 
	AGENT_WFM_ID , 
	EMPLOYEE_ID, 
	MANAGEMENT_UNIT_DATE, 
	SCHEDULE_START_MU_DATETIME,
	SCHEDULE_END_MU_DATETIME, 
	CASE WHEN Employee_id IS NULL THEN 'Not a Current Employee'
	     WHEN management_unit_date IS NULL THEN 'No Valid Schedule'
	     WHEN create_TS NOT BETWEEN SCHEDULE_START_MU_DATETIME AND SCHEDULE_END_MU_DATETIME THEN 'Login/Logout Violation'
	     ELSE 'Valid Logon/Logout'
	END Record_Status 
FROM MAXDAT.D_CES_LOGIN
);

GRANT SELECT ON MAXDAT.D_CES_LOGIN_SV TO MAXDAT_READ_ONLY;
  