CREATE TABLE CALL_RECORD_STG(
CALL_RECORD_ID	NUMBER(18,0) NOT NULL,	
CALLER_TYPE	VARCHAR2(64),
CALL_TYPE	VARCHAR2(64),	
CALL_TRACKING_NUMBER	VARCHAR2(32),
WORKER_ID	VARCHAR2(32),	
WORKER_USERNAME	VARCHAR2(32),
LANGUAGE	VARCHAR2(64),	
CALL_ACTION	VARCHAR2(64),	
CALL_START_TS	DATE,	
CALL_END_TS	DATE,	
CREATED_BY	VARCHAR2(32),	
CREATE_TS	DATE,	
UPDATED_BY	VARCHAR2(32),
UPDATE_TS	DATE,	
NOTE_REF_ID	NUMBER(18,0),	
CALL_RECORD_FIELD1	VARCHAR2(80),
EVENT_ID 	NUMBER(18,0),
PARENT_CALL_RECORD_ID	NUMBER(18,0),
caller_last_name VARCHAR2(50),
caller_first_name VARCHAR2(50),
caller_phone VARCHAR2(20),
call_type_cd VARCHAR2(64) ) TABLESPACE MAXDAT_DATA;

CREATE UNIQUE INDEX XPKCALL_RECORD ON CALL_RECORD_STG (CALL_RECORD_ID, EVENT_ID) TABLESPACE MAXDAT_INDX;

CREATE INDEX IDX1_CALL_RECORD_STG ON CALL_RECORD_STG(CREATE_TS) TABLESPACE MAXDAT_INDX;
CREATE INDEX IDX2_CALL_RECORD_STG ON CALL_RECORD_STG(CALL_ACTION) TABLESPACE MAXDAT_INDX;
CREATE INDEX IDX3_CALL_RECORD_STG ON CALL_RECORD_STG(call_record_id) TABLESPACE MAXDAT_INDX;
CREATE INDEX IDX4_CALL_RECORD_STG ON CALL_RECORD_STG(call_type_cd) TABLESPACE MAXDAT_INDX;

GRANT SELECT ON CALL_RECORD_STG TO MAXDAT_READ_ONLY;

CREATE OR REPLACE VIEW D_MANUAL_CALL_ACTION_SV
AS
select call_record_id,	
caller_type,
call_type,	
call_tracking_number,
worker_id,	
worker_username,
language,	
call_action,	
call_start_ts,	
call_end_ts,	
created_by,	
create_ts,	
updated_by,
update_ts,	
note_ref_id,	
call_record_field1,
event_id,
parent_call_record_id
FROM call_record_stg;

GRANT SELECT ON D_MANUAL_CALL_ACTION_SV TO MAXDAT_READ_ONLY;