ALTER TABLE PP_D_ACTUAL_DETAILS DROP CONSTRAINT PP_D_ACTUAL_DETAILS__UN;
 COMMIT;
 
create or replace view maxdat.PP_D_ACTUAL_DETAILS_SV as
select
  DAD_ID,
  PPDD.D_DATE,
  D_HOUR,
  USR_ID,
  SOURCE_DETAIL_ID, 
  case 
    when DENSE_RANK() over (partition by SOURCE_DETAIL_ID order by SOURCE_DETAIL_ID asc, PPDD.D_DATE asc) = 1 then 1
    else 0
    end ACTUAL_ARRIVAL,
  ACTUAL_COMPLETION,
  ACTUAL_INVENTORY,
  ACTUAL_INVENTORY_AGE,
  ACTUAL_HANDLE_TIME,
  ACTUAL_STAFF_HOURS,
  JEOPARDY_FLAG
from 
  (SELECT D_DATE FROM PP_D_DATES WHERE D_DATE <= TRUNC(SYSDATE)) PPDD,
  PP_D_ACTUAL_DETAILS DAD
where
  PPDD.D_DATE >= DAD.BUCKET_START_DATE 
  and PPDD.D_DATE < DAD.BUCKET_END_DATE
union all
select
  DAD_ID,
  PPDD.D_DATE,
  D_HOUR,
  USR_ID,
  SOURCE_DETAIL_ID, 
  ACTUAL_ARRIVAL,
  ACTUAL_COMPLETION,
  ACTUAL_INVENTORY,
  ACTUAL_INVENTORY_AGE,
  ACTUAL_HANDLE_TIME,
  ACTUAL_STAFF_HOURS,
  JEOPARDY_FLAG
from 
  PP_D_DATES PPDD,
  PP_D_ACTUAL_DETAILS DAD
where
  PPDD.D_DATE = DAD.BUCKET_START_DATE 
  and PPDD.D_DATE = DAD.BUCKET_END_DATE
with read only;
commit; 
 
 /