CREATE OR REPLACE VIEW PP_D_UOW_SOURCE_REF_SV AS
SELECT USR_ID, 
     UOW_ID, 
     SOURCE_REF_TYPE_ID, 
     SOURCE_REF_VALUE, 
     SOURCE_REF_DETAIL_IDENTIFIER, 
     EFFECTIVE_DATE, 
     END_DATE
	 FROM PP_D_UOW_SOURCE_REF
WITH READ ONLY;

grant select on PP_D_UOW_SOURCE_REF_SV to MAXDAT_READ_ONLY;