ALTER TABLE PP_BO_ACTUALS DROP CONSTRAINT EVENT_ID_FK;
ALTER TABLE PP_BO_TASK DROP CONSTRAINT TSK_EVENT_ID_FK;
ALTER TABLE PP_BO_SCHEDULE_MONITOR DROP CONSTRAINT SCHED_MON_EVENT_ID_FK;

ALTER TABLE PP_D_UOW_SOURCE_REF DROP CONSTRAINT PP_D_UOW_SOURCE_REF_UK;
DROP INDEX  PP_D_UOW_SOURCE_REF_UK;

ALTER TABLE MAXDAT.PP_D_UOW_SOURCE_REF 
DROP CONSTRAINT PP_D_UOW_SOURCE_REF_UN;

ALTER TABLE MAXDAT.PP_D_UOW_SOURCE_REF 
DROP CONSTRAINT PP_D_UOW_SOURCE_REF_UN1;

DROP INDEX PP_D_UOW_SOURCE_REF_UN;
DROP INDEX PP_D_UOW_SOURCE_REF_UN1;

commit;
 alter table MAXDAT.PP_D_UOW_SOURCE_REF
   add constraint PP_D_UOW_SOURCE_REF_UN unique (UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, source_ref_id, EFFECTIVE_DATE);
 alter table MAXDAT.PP_D_UOW_SOURCE_REF
   add constraint PP_D_UOW_SOURCE_REF_UN1 unique (UOW_ID, SOURCE_REF_TYPE_ID, SOURCE_REF_VALUE, source_ref_id, END_DATE);
   
commit;

/   
