CREATE TABLE CC_S_VM_IN_QUEUE
  (
    CCVMQ_ID          NUMBER(19,0) NOT NULL ENABLE,
    VM_QUEUE_ID       VARCHAR2(25) NOT NULL ENABLE,
    MEDIA_TYPE        VARCHAR2(15) NOT NULL ENABLE,
    VM_RECEIVED_DT    DATE NOT NULL ENABLE,
    ANI               VARCHAR2(25) NOT NULL ENABLE,
    EXTRACT_DT        DATE NOT NULL ENABLE,
    LAST_UPDATE_DT    DATE NOT NULL ENABLE,
    LAST_UPDATE_BY    VARCHAR2(30 BYTE) NOT NULL ENABLE)
    LOGGING 
;

CREATE UNIQUE INDEX CC_S_VM_IN_QUEUE_IDX ON CC_S_VM_IN_QUEUE 
    ( 
     VM_QUEUE_ID ASC 
    ) 
    LOGGING 
;

ALTER TABLE CC_S_VM_IN_QUEUE 
    ADD CONSTRAINT CC_S_VM_IN_QUEUE_PK PRIMARY KEY ( CCVMQ_ID ) ;
    
    
CREATE SEQUENCE SEQ_CC_S_VM_IN_QUEUE 
    START WITH 1 
    INCREMENT BY 1 
    MAXVALUE 9999999999999999999 
    MINVALUE 1 
    CACHE 20 
;    
    
    
CREATE OR REPLACE TRIGGER BIU_CC_S_VM_IN_QUEUE 
    BEFORE INSERT OR UPDATE ON CC_S_VM_IN_QUEUE
    FOR EACH ROW 
BEGIN 
IF INSERTING AND :NEW.CCVMQ_ID IS NULL THEN 
          SELECT SEQ_CC_S_VM_IN_QUEUE.NEXTVAL INTO :NEW.CCVMQ_ID FROM DUAL;
END IF;
IF INSERTING THEN 
          :NEW.EXTRACT_DT := SYSDATE;
END IF;
:NEW.LAST_UPDATE_DT := SYSDATE;
:NEW.LAST_UPDATE_BY := USER;
END; 
/

ALTER TRIGGER BIU_CC_S_VM_IN_QUEUE ENABLE;


INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME) 
VALUES ('0.2','103','103_create_CC_S_VM_IN_QUEUE');

COMMIT;