CREATE OR REPLACE VIEW PUBLIC.D_PLAN_INSTANCE_SV AS
SELECT PROJECT_ID,
PLAN_ID,
PLAN_NAME,
PLAN_CODE,
PLAN_PROVIDER_CD,
MCO_ID,
START_DATE AS PLAN_START_DATE,
END_DATE AS PLAN_END_DATE,
ENROLLMENT_START_DATE,
ENROLLMENT_END_DATE
FROM MARSDB.MARSDB_MCO_CONTRACTS_VW 