--index on document_notification_stg
create index IDX3_DOCUMENT_NOTIFICATION_DCN on DOCUMENT_NOTIFICATION_STG(DCN) online tablespace MAXDAT_INDX parallel compute statistics;

--Index on NYHIX MFD tables
create index IDX_MAILFAXDOC_KOFAX_DCN on NYHIX_ETL_MAIL_FAX_DOC (KOFAX_DCN) TABLESPACE MAXDAT_INDX;
create index IDX1_MAILFAXDOC_KOFAX_DCN on NYHIX_ETL_MAIL_FAX_DOC_OLTP (KOFAX_DCN) TABLESPACE MAXDAT_INDX;
create index IDX2_MAILFAXDOC_KOFAX_DCN on NYHIX_ETL_MAIL_FAX_DOC_WIP_BPM (KOFAX_DCN) TABLESPACE  MAXDAT_INDX;