INSERT INTO D_SEGMENT(d_segment_id, segment_name, create_date, last_modified_date)
VALUES (0, 'Unknown', to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'), to_date('31-DEC-2999 00:00:00','DD-MON-RRRR HH24:MI:SS'));

INSERT INTO D_DIVISION(d_division_id, division_name, d_segment_id, create_date, last_modified_date)
VALUES (0, 'Unknown', 0, to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'), to_date('31-DEC-2999 00:00:00','DD-MON-RRRR HH24:MI:SS'));

INSERT INTO D_PROJECT(d_project_id, project_name, d_division_id, create_date, last_modified_date)
VALUES (0, 'Unknown',0, to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'), to_date('31-DEC-2999 00:00:00','DD-MON-RRRR HH24:MI:SS'));

INSERT INTO CC_D_PROJECT_TARGETS(d_project_targets_id, project_id, average_handle_time_target,cost_per_call_target,labor_cost_per_call_target,occupancy_target,utilization_target,record_eff_dt,record_end_dt,version) 
VALUES (0, 0, 0, 0, 0, 0, 0, to_date('01-JAN-1900','DD-MON-YYYY'), to_date('31-DEC-2999','DD-MON-YYYY'), 1);

INSERT INTO D_PROGRAM(d_program_id, program_name, create_date, last_modified_date)
VALUES (0, 'Unknown', to_date('01-JAN-1900','DD-MON-YYYY'), to_date('31-DEC-2999 00:00:00','DD-MON-RRRR HH24:MI:SS'));

INSERT INTO CC_D_COUNTRY(COUNTRY_ID, COUNTRY_NAME) VALUES(0,'Unknown');

INSERT INTO CC_D_REGION(REGION_ID, REGION_NAME) VALUES(0, 'Unknown');

INSERT INTO CC_D_STATE(STATE_ID, STATE_NAME) VALUES(0, 'Unknown');

INSERT INTO CC_D_TARGET(D_TARGET_ID, TARGET_NAME, TARGET_DESCRIPTION)
VALUES (0, 'Unknown', 'Unknown');

INSERT INTO CC_D_PROVINCE(PROVINCE_ID, PROVINCE_NAME) VALUES(0,'Unknown');

INSERT INTO CC_D_DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES(0,'Unknown');

INSERT INTO CC_D_CONTACT_QUEUE (D_CONTACT_QUEUE_ID,D_PROJECT_ID,QUEUE_NUMBER,QUEUE_NAME,SOURCE_QUEUE,QUEUE_TYPE,SERVICE_PERCENT,SERVICE_SECONDS,QUEUE_GROUP,INTERVAL_MINUTES,SPEED_ANSWER_PERIOD_1_BOUND,SPEED_ANSWER_PERIOD_2_BOUND,SPEED_ANSWER_PERIOD_3_BOUND,SPEED_ANSWER_PERIOD_4_BOUND,SPEED_ANSWER_PERIOD_5_BOUND,SPEED_ANSWER_PERIOD_6_BOUND,SPEED_ANSWER_PERIOD_7_BOUND,SPEED_ANSWER_PERIOD_8_BOUND,SPEED_ANSWER_PERIOD_9_BOUND,SPEED_ANSWER_PERIOD_10_BOUND,CALLS_ABNDONED_PERIOD_1_BOUND,CALLS_ABNDONED_PERIOD_2_BOUND,CALLS_ABNDONED_PERIOD_3_BOUND,CALLS_ABNDONED_PERIOD_4_BOUND,CALLS_ABNDONED_PERIOD_5_BOUND,CALLS_ABNDONED_PERIOD_6_BOUND,CALLS_ABNDONED_PERIOD_7_BOUND,CALLS_ABNDONED_PERIOD_8_BOUND,CALLS_ABNDONED_PERIOD_9_BOUND,CALLS_ABNDONED_PERIOD_10_BOUND,VERSION,RECORD_EFF_DT,RECORD_END_DT) 
VALUES (0,0,0,'Unknown',0,'Unknown',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'),to_date('31-DEC-2999 00:00:00','DD-MON-RRRR HH24:MI:SS'));

INSERT INTO D_GEOGRAPHY_MASTER(d_geography_master_id, geography_name, create_date, last_modified_date, country_id, state_id, province_id, district_id, region_id)
VALUES(0, 'Unknown', to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'), to_date('31-DEC-2999 00:00:00','DD-MON-RRRR HH24:MI:SS'), 0, 0, 0, 0, 0);

INSERT INTO CC_D_ACTIVITY_TYPE (D_ACTIVITY_TYPE_ID, D_PROJECT_ID, ACTIVITY_TYPE_NAME, ACTIVITY_TYPE_DESC, ACTIVITY_TYPE_CATEGORY, IS_PAID_FLAG, IS_AVAILABLE_FLAG, IS_READY_FLAG, IS_ABSENCE_FLAG, VERSION, RECORD_EFF_DT, RECORD_END_DT)
VALUES(0, 0, 'Unknown', 'Unknown', 'Unknown', 'N', 'N', 'N', 'N', 1, to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'),to_date('31-DEC-2999 00:00:00','DD-MON-RRRR HH24:MI:SS'));

INSERT INTO CC_D_AGENT (D_AGENT_ID, D_PROJECT_ID, LOGIN_ID, FIRST_NAME, MIDDLE_INITIAL, LAST_NAME, JOB_TITLE, LANGUAGE, SITE_NAME, HOURLY_RATE, RATE_CURRENCY, VERSION, RECORD_EFF_DT, RECORD_END_DT)
VALUES(0, 0, 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 0.0, 'USD', 1, to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'),to_date('31-DEC-2999 00:00:00','DD-MON-RRRR HH24:MI:SS'));

INSERT INTO CC_D_PRODUCTION_PLAN (PRODUCTION_PLAN_ID, PLAN_TYPE, PRODUCTION_PLAN_NAME, PRODUCTION_PLAN_DESCRIPTION, PROJECT_ID, PROGRAM_ID, GEOGRAPHY_MASTER_ID, EFFECTIVE_DATE, END_DATE, CREATE_DATE, LAST_UPDATE_DATE)
VALUES(0, 'Unknown', 'Unknown', 'Unknown', 0, 0, 0, to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'),to_date('31-DEC-2999 00:00:00','DD-MON-RRRR HH24:MI:SS'), to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'),to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'));

INSERT INTO CC_D_PRODUCTION_PLAN_HORIZON (PRODUCTION_PLAN_HRZN_ID, PRODUCTION_PLAN_ID, HORIZON_START_DATE, HORIZON_START_HOUR, HORIZON_END_DATE, HORIZON_END_HOUR, INITIAL_VERSION, FINAL_VERSION, FORECAST_LAST_MODIFIED_DATE, CREATE_DATE, LAST_UPDATE_DATE)
VALUES(0, 0, to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'), 00, to_date('31-DEC-2999 00:00:00','DD-MON-RRRR HH24:MI:SS'), 00, 1, 1, to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'), to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'), to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'));

INSERT INTO CC_D_FORECAST_NOTES (D_FORECAST_NOTES_ID, PRODUCTION_PLAN_HORIZON_ID, NOTE_TYPE, NOTE_TEXT, CREATE_DATE, CREATE_BY, LAST_UPDATE_DATE, LAST_UPDATE_BY)
VALUES(0, 0, 'Unknown', 'Unknown', to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'), 'Unknown', to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'), 'Unknown');

INSERT INTO CC_D_GROUP (D_GROUP_ID, D_PROJECT_ID, GROUP_NAME, GROUP_DESCRIPTION, VERSION, RECORD_EFF_DT, RECORD_END_DT)
VALUES(0, 0, 'Unknown', 'Unknown', 1, to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'),to_date('31-DEC-2999 00:00:00','DD-MON-RRRR HH24:MI:SS'));

INSERT INTO CC_D_SITE (D_SITE_ID, SITE_NAME, SITE_DESCRIPTION, VERSION, RECORD_EFF_DT, RECORD_END_DT)
VALUES (0, 'Unknown', 'Unknown', 1, to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'),to_date('31-DEC-2999 00:00:00','DD-MON-RRRR HH24:MI:SS'));

INSERT INTO CC_D_INTERVAL (D_INTERVAL_ID, INTERVAL_START_DATE, INTERVAL_END_DATE, AM_PM, INTERVAL_START_HOUR, INTERVAL_START_MINUTE, INTERVAL_END_HOUR, INTERVAL_END_MINUTE, INTERVAL_SECONDS, INTERVAL_START_TIME_OF_DAY12, INTERVAL_START_TIME_OF_DAY24, INTERVAL_END_TIME_OF_DAY12, INTERVAL_END_TIME_OF_DAY24, RECORD_EFF_DT, RECORD_END_DT, VERSION)
VALUES(0, to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'), to_date('01-JAN-1900 00:30:00','DD-MON-RRRR HH24:MI:SS'), 'AM', 00, 00, 00, 30, 1800, '12:00', '00:00', '12:30', '00:30', to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'),to_date('31-DEC-2999 00:00:00','DD-MON-RRRR HH24:MI:SS'), 1);

INSERT INTO CC_D_IVR_SELF_SERVICE_PATH (D_IVR_SELF_SERVICE_PATH_ID, D_PROJECT_ID, CODE, DESCRIPTION, BEGIN_NODE, END_NODE, VERSION, RECORD_EFF_DT, RECORD_END_DT)
VALUES(0, 0, 'Unknown', 'Unknown', 'Unknown', 'Unknown', 1, to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'),to_date('31-DEC-2999 00:00:00','DD-MON-RRRR HH24:MI:SS'));

INSERT INTO CC_D_PROD_PLANNING_TARGET (D_PROD_PLANNING_TARGET_ID, D_PROJECT_ID, D_TARGET_ID, TARGET_VALUE, RECORD_EFF_DT, RECORD_END_DT, VERSION)
VALUES(0, 0, 0, 0.0, to_date('01-JAN-1900 00:00:00','DD-MON-RRRR HH24:MI:SS'),to_date('31-DEC-2999 00:00:00','DD-MON-RRRR HH24:MI:SS'), 1);

INSERT INTO CC_D_UNIT_OF_WORK (UOW_ID, D_PROJECT_ID, UNIT_OF_WORK_NAME, PRODUCTION_PLAN_ID, HOURLY_FLAG, HANDLE_TIME_UNIT)
VALUES(0, 0, 'Unknown', 0, 'N', 'Seconds');