alter session set plsql_code_type = native;

create or replace
trigger TRG_AI_NYEC_ETL_PROCESS_APP_Q
after insert on NYEC_ETL_PROCESS_APP
for each row

declare

  v_bsl_id number := 2; -- 'NYEC_ETL_PROCESS_APP'  
  v_bil_id number := 2; -- 'Application ID' 
  -- v_data_version number := 2; -- Added r4 - HEART_CASE_STATUS and STATE_CASE_IDEN.
  -- v_data_version number := 3; -- Removed calculation columns.
  v_data_version number := 4; -- Added reactivation columns.
  
  v_event_date date := null;
  v_identifier varchar2(100) := null;
  
  v_xml_string_new clob := null;
  
  v_sql_code number := null;
  v_log_message clob := null;
  
begin

  v_event_date := :new.STG_LAST_UPDATE_DATE;
  v_identifier := :new.APP_ID || '_' || to_char(:new.REACTIVATION_NBR);

  /* 
  Include: 
    CEPA_ID
    STG_LAST_UPDATE_DATE
  Exclude:
    AGE_IN_BUSINESS_DAYS
    AGE_IN_CALENDAR_DAYS
    APP_CYCLE_BUS_DAYS
    APP_CYCLE_CAL_DAYS
    DAYS_UNTIL_TIMEOUT
    JEOPARDY_FLAG
    TIMELINESS_STATUS
  */
  v_xml_string_new := 
    '<?xml version="1.0"?>
    <ROWSET>  
      <ROW>
        <APPLICANT_ID>' || :new.APPLICANT_ID || '</APPLICANT_ID>
        <APP_COMPLETE_RESULT><![CDATA[' || :new.APP_COMPLETE_RESULT || ']]></APP_COMPLETE_RESULT>
        <APP_CYCLE_END_DT>' || to_char(:new.APP_CYCLE_END_DT,BPM_COMMON.GET_DATE_FMT) || '</APP_CYCLE_END_DT>
        <APP_CYCLE_START_DT>' || to_char(:new.APP_CYCLE_START_DT,BPM_COMMON.GET_DATE_FMT) || '</APP_CYCLE_START_DT>
        <APP_ID>' || :new.APP_ID || '</APP_ID>
        <APP_STATUS><![CDATA[' || :new.APP_STATUS || ']]></APP_STATUS>
        <APP_STATUS_GROUP><![CDATA[' || :new.APP_STATUS_GROUP || ']]></APP_STATUS_GROUP>
        <APP_TYPE><![CDATA[' || :new.APP_TYPE || ']]></APP_TYPE>
        <ASF_CANCEL_APP><![CDATA[' || :new.ASF_CANCEL_APP || ']]></ASF_CANCEL_APP>
        <ASF_CLOSE_APP><![CDATA[' || :new.ASF_CLOSE_APP || ']]></ASF_CLOSE_APP>
        <ASF_COMPLETE_APP><![CDATA[' || :new.ASF_COMPLETE_APP || ']]></ASF_COMPLETE_APP>
        <ASF_NOTIFY_CLIENT_PENDED_APP><![CDATA[' || :new.ASF_NOTIFY_CLIENT_PENDED_APP || ']]></ASF_NOTIFY_CLIENT_PENDED_APP>
        <ASF_PERFORM_QC><![CDATA[' || :new.ASF_PERFORM_QC || ']]></ASF_PERFORM_QC>
        <ASF_PERFORM_RESEARCH><![CDATA[' || :new.ASF_PERFORM_RESEARCH || ']]></ASF_PERFORM_RESEARCH>
        <ASF_PROCESS_APP_INFO><![CDATA[' || :new.ASF_PROCESS_APP_INFO || ']]></ASF_PROCESS_APP_INFO>
        <ASF_RECEIVE_APP><![CDATA[' || :new.ASF_RECEIVE_APP || ']]></ASF_RECEIVE_APP>
        <ASF_RECEIVE_PROCESS_MI><![CDATA[' || :new.ASF_RECEIVE_PROCESS_MI || ']]></ASF_RECEIVE_PROCESS_MI>
        <ASF_REVIEW_ENTER_DATA><![CDATA[' || :new.ASF_REVIEW_ENTER_DATA || ']]></ASF_REVIEW_ENTER_DATA>
        <ASF_WAIT_STATE_APPROVAL><![CDATA[' || :new.ASF_WAIT_STATE_APPROVAL || ']]></ASF_WAIT_STATE_APPROVAL>
        <ASPB_CANCEL_APP><![CDATA[' || :new.ASPB_CANCEL_APP || ']]></ASPB_CANCEL_APP>
        <ASPB_CLOSE_APP><![CDATA[' || :new.ASPB_CLOSE_APP || ']]></ASPB_CLOSE_APP>
        <ASPB_COMPLETE_APP><![CDATA[' || :new.ASPB_COMPLETE_APP || ']]></ASPB_COMPLETE_APP>
        <ASPB_NOTIFY_CLIENT_PENDED_APP><![CDATA[' || :new.ASPB_NOTIFY_CLIENT_PENDED_APP || ']]></ASPB_NOTIFY_CLIENT_PENDED_APP>
        <ASPB_PERFORM_QC><![CDATA[' || :new.ASPB_PERFORM_QC || ']]></ASPB_PERFORM_QC>
        <ASPB_PERFORM_QC_REG><![CDATA[' || :new.ASPB_PERFORM_QC_REG || ']]></ASPB_PERFORM_QC_REG>
        <ASPB_PERFORM_RESEARCH><![CDATA[' || :new.ASPB_PERFORM_RESEARCH || ']]></ASPB_PERFORM_RESEARCH>
        <ASPB_PROCESS_APP_INFO><![CDATA[' || :new.ASPB_PROCESS_APP_INFO || ']]></ASPB_PROCESS_APP_INFO>
        <ASPB_REG_ENTER_DATA><![CDATA[' || :new.ASPB_REG_ENTER_DATA || ']]></ASPB_REG_ENTER_DATA>
        <ASPB_RVW_ENTER_DATA><![CDATA[' || :new.ASPB_RVW_ENTER_DATA || ']]></ASPB_RVW_ENTER_DATA>
        <ASPB_WAIT_STATE_APPROVAL><![CDATA[' || :new.ASPB_WAIT_STATE_APPROVAL || ']]></ASPB_WAIT_STATE_APPROVAL>
        <ASSD_NOTIFY_CLIENT_PENDED_APP>' || to_char(:new.ASSD_NOTIFY_CLIENT_PENDED_APP,BPM_COMMON.GET_DATE_FMT) || '</ASSD_NOTIFY_CLIENT_PENDED_APP>
        <ASSD_PERFORM_QC>' || to_char(:new.ASSD_PERFORM_QC,BPM_COMMON.GET_DATE_FMT) || '</ASSD_PERFORM_QC>
        <ASSD_PERFORM_QC_REG>' || to_char(:new.ASSD_PERFORM_QC_REG,BPM_COMMON.GET_DATE_FMT) || '</ASSD_PERFORM_QC_REG>
        <ASSD_PERFORM_RESEARCH>' || to_char(:new.ASSD_PERFORM_RESEARCH,BPM_COMMON.GET_DATE_FMT) || '</ASSD_PERFORM_RESEARCH>
        <ASSD_PROCESS_APP_INFO>' || to_char(:new.ASSD_PROCESS_APP_INFO,BPM_COMMON.GET_DATE_FMT) || '</ASSD_PROCESS_APP_INFO>
        <ASSD_REG_ENTER_DATA>' || to_char(:new.ASSD_REG_ENTER_DATA,BPM_COMMON.GET_DATE_FMT) || '</ASSD_REG_ENTER_DATA>
        <ASSD_RVW_ENTER_DATA>' || to_char(:new.ASSD_RVW_ENTER_DATA,BPM_COMMON.GET_DATE_FMT) || '</ASSD_RVW_ENTER_DATA>
        <ASSD_WAIT_STATE_APPROVAL>' || to_char(:new.ASSD_WAIT_STATE_APPROVAL,BPM_COMMON.GET_DATE_FMT) || '</ASSD_WAIT_STATE_APPROVAL>
        <AUTO_REPROCESS_FLAG><![CDATA[' || :new.AUTO_REPROCESS_FLAG || ']]></AUTO_REPROCESS_FLAG>
        <CANCEL_DATE>' || to_char(:new.CANCEL_DATE,BPM_COMMON.GET_DATE_FMT) || '</CANCEL_DATE>
        <CEPA_ID>' || :new.CEPA_ID || '</CEPA_ID>
        <CHANNEL><![CDATA[' || :new.CHANNEL || ']]></CHANNEL>
        <CIN><![CDATA[' || :new.CIN || ']]></CIN>
        <CIN_DT>' || to_char(:new.CIN_DT,BPM_COMMON.GET_DATE_FMT) || '</CIN_DT>
        <CLOCKDOWN_INDICATOR><![CDATA[' || :new.CLOCKDOWN_INDICATOR || ']]></CLOCKDOWN_INDICATOR>
        <COMPLETE_DT>' || to_char(:new.COMPLETE_DT,BPM_COMMON.GET_DATE_FMT) || '</COMPLETE_DT>
        <COUNTY><![CDATA[' || :new.COUNTY || ']]></COUNTY>
        <CREATE_DT>' || to_char(:new.CREATE_DT,BPM_COMMON.GET_DATE_FMT) || '</CREATE_DT>
        <CURRENT_TASK_ID>' || :new.CURRENT_TASK_ID || '</CURRENT_TASK_ID>
        <CURR_MODE_CD><![CDATA[' || :new.CURR_MODE_CD || ']]></CURR_MODE_CD>
        <CURR_MODE_LABEL><![CDATA[' || :new.CURR_MODE_LABEL || ']]></CURR_MODE_LABEL>
        <DE_TASK_ID>' || :new.DE_TASK_ID || '</DE_TASK_ID>
        <ELIGIBILITY_ACTION><![CDATA[' || :new.ELIGIBILITY_ACTION || ']]></ELIGIBILITY_ACTION>
        <FPBP_TYPE><![CDATA[' || :new.FPBP_TYPE || ']]></FPBP_TYPE>
        <GWF_MISSING_INFO><![CDATA[' || :new.GWF_MISSING_INFO || ']]></GWF_MISSING_INFO>
        <GWF_NEW_MI><![CDATA[' || :new.GWF_NEW_MI || ']]></GWF_NEW_MI>
        <GWF_OUTCM_NOTIFY_RQRD><![CDATA[' || :new.GWF_OUTCM_NOTIFY_RQRD || ']]></GWF_OUTCM_NOTIFY_RQRD>
        <GWF_PEND_NOTIFY_RQRD><![CDATA[' || :new.GWF_PEND_NOTIFY_RQRD || ']]></GWF_PEND_NOTIFY_RQRD>
        <GWF_QC_OUTCOME><![CDATA[' || :new.GWF_QC_OUTCOME || ']]></GWF_QC_OUTCOME>
        <GWF_QC_RQRD><![CDATA[' || :new.GWF_QC_RQRD || ']]></GWF_QC_RQRD>
        <GWF_RESEARCH><![CDATA[' || :new.GWF_RESEARCH || ']]></GWF_RESEARCH>
        <HEART_APP_STATUS><![CDATA[' || :new.HEART_APP_STATUS || ']]></HEART_APP_STATUS>
        <HEART_CASE_STATUS><![CDATA[' || :new.HEART_CASE_STATUS || ']]></HEART_CASE_STATUS>
        <HEART_INCMPLT_APP_IND><![CDATA[' || :new.HEART_INCMPLT_APP_IND || ']]></HEART_INCMPLT_APP_IND>
        <HEART_REPROCESS_STATUS><![CDATA[' || :new.HEART_REPROCESS_STATUS || ']]></HEART_REPROCESS_STATUS>
        <HEART_REPROCESS_STATUS_DT>' || to_char(:new.HEART_REPROCESS_STATUS_DT,BPM_COMMON.GET_DATE_FMT) || '</HEART_REPROCESS_STATUS_DT>
        <HEART_SYNCH_FLAG><![CDATA[' || :new.HEART_SYNCH_FLAG || ']]></HEART_SYNCH_FLAG>
        <INVOICE_READY_DT>' || to_char(:new.INVOICE_READY_DT,BPM_COMMON.GET_DATE_FMT) || '</INVOICE_READY_DT>
        <LAST_MAIL_DT>' || to_char(:new.LAST_MAIL_DT,BPM_COMMON.GET_DATE_FMT) || '</LAST_MAIL_DT>
        <MA_REASON><![CDATA[' || :new.MA_REASON || ']]></MA_REASON>
        <MI_RECEIVED_TASK_COUNT>' || :new.MI_RECEIVED_TASK_COUNT || '</MI_RECEIVED_TASK_COUNT>
        <NOTIFY_CLIENT_PENDED_APP_DT>' || to_char(:new.NOTIFY_CLIENT_PENDED_APP_DT,BPM_COMMON.GET_DATE_FMT) || '</NOTIFY_CLIENT_PENDED_APP_DT>
        <NUMBER_OF_APPLICANTS>' || :new.NUMBER_OF_APPLICANTS || '</NUMBER_OF_APPLICANTS>
        <OFFICE_ID>' || :new.OFFICE_ID || '</OFFICE_ID>
        <OUTCOME_LTR_CREATE_DT>' || to_char(:new.OUTCOME_LTR_CREATE_DT,BPM_COMMON.GET_DATE_FMT) || '</OUTCOME_LTR_CREATE_DT>
        <OUTCOME_LTR_ID>' || :new.OUTCOME_LTR_ID || '</OUTCOME_LTR_ID>
        <OUTCOME_LTR_SENT_DT>' || to_char(:new.OUTCOME_LTR_SENT_DT,BPM_COMMON.GET_DATE_FMT) || '</OUTCOME_LTR_SENT_DT>
        <OUTCOME_LTR_STATUS><![CDATA[' || :new.OUTCOME_LTR_STATUS || ']]></OUTCOME_LTR_STATUS>
        <OUTCOME_LTR_TYPE><![CDATA[' || :new.OUTCOME_LTR_TYPE || ']]></OUTCOME_LTR_TYPE>
        <OUTCOME_NOTIFY_RQRD_FLAG><![CDATA[' || :new.OUTCOME_NOTIFY_RQRD_FLAG || ']]></OUTCOME_NOTIFY_RQRD_FLAG>
        <PERFORM_QC_DT>' || to_char(:new.PERFORM_QC_DT,BPM_COMMON.GET_DATE_FMT) || '</PERFORM_QC_DT>
        <PERFORM_QC_REG_DT>' || to_char(:new.PERFORM_QC_REG_DT,BPM_COMMON.GET_DATE_FMT) || '</PERFORM_QC_REG_DT>
        <PERFORM_RESEARCH_DT>' || to_char(:new.PERFORM_RESEARCH_DT,BPM_COMMON.GET_DATE_FMT) || '</PERFORM_RESEARCH_DT>
        <PROCESS_APP_INFO_DT>' || to_char(:new.PROCESS_APP_INFO_DT,BPM_COMMON.GET_DATE_FMT) || '</PROCESS_APP_INFO_DT>
        <PROVIDER_NAME><![CDATA[' || :new.PROVIDER_NAME || ']]></PROVIDER_NAME>
        <QC_IND><![CDATA[' || :new.QC_IND || ']]></QC_IND>
        <QC_REG_TASK_ID>' || :new.QC_REG_TASK_ID || '</QC_REG_TASK_ID>
        <QC_TASK_ID>' || :new.QC_TASK_ID || '</QC_TASK_ID>
        <REACTIVATED_BY><![CDATA[' || :new.REACTIVATED_BY || ']]></REACTIVATED_BY>
        <REACTIVATION_DT>' || to_char(:new.REACTIVATION_DT,BPM_COMMON.GET_DATE_FMT) || '</REACTIVATION_DT>
        <REACTIVATION_IND>' || :new.REACTIVATION_IND || '</REACTIVATION_IND>
        <REACTIVATION_NBR>' || :new.REACTIVATION_NBR || '</REACTIVATION_NBR>
        <REACTIVATION_REASON><![CDATA[' || :new.REACTIVATION_REASON || ']]></REACTIVATION_REASON>
        <RECEIPT_DT>' || to_char(:new.RECEIPT_DT,BPM_COMMON.GET_DATE_FMT) || '</RECEIPT_DT>
        <REFER_LDSS_FLAG><![CDATA[' || :new.REFER_LDSS_FLAG || ']]></REFER_LDSS_FLAG>
        <REG_ENTER_DATA_DT>' || to_char(:new.REG_ENTER_DATA_DT,BPM_COMMON.GET_DATE_FMT) || '</REG_ENTER_DATA_DT>
        <REG_TASK_ID>' || :new.REG_TASK_ID || '</REG_TASK_ID>
        <RESEARCH_REASON><![CDATA[' || :new.RESEARCH_REASON || ']]></RESEARCH_REASON>
        <RESEARCH_TASK_ID>' || :new.RESEARCH_TASK_ID || '</RESEARCH_TASK_ID>
        <REV_CLEAR_IND><![CDATA[' || :new.REV_CLEAR_IND || ']]></REV_CLEAR_IND>
        <REV_CLEAR_IND_DT>' || to_char(:new.REV_CLEAR_IND_DT,BPM_COMMON.GET_DATE_FMT) || '</REV_CLEAR_IND_DT>
        <REV_CLEAR_OUTCOME><![CDATA[' || :new.REV_CLEAR_OUTCOME || ']]></REV_CLEAR_OUTCOME>
        <REV_CLEAR_REASON><![CDATA[' || :new.REV_CLEAR_REASON || ']]></REV_CLEAR_REASON>
        <RVW_ENTER_DATA_DT>' || to_char(:new.RVW_ENTER_DATA_DT,BPM_COMMON.GET_DATE_FMT) || '</RVW_ENTER_DATA_DT>
        <SLA_DAYS>' || :new.SLA_DAYS || '</SLA_DAYS>
        <SLA_DAYS_TYPE><![CDATA[' || :new.SLA_DAYS_TYPE || ']]></SLA_DAYS_TYPE>
        <SLA_JEOPARDY_DAYS>' || :new.SLA_JEOPARDY_DAYS || '</SLA_JEOPARDY_DAYS>
        <SLA_JEOPARDY_DT>' || to_char(:new.SLA_JEOPARDY_DT,BPM_COMMON.GET_DATE_FMT) || '</SLA_JEOPARDY_DT>
        <SLA_TARGET_DAYS>' || :new.SLA_TARGET_DAYS || '</SLA_TARGET_DAYS>
        <STATE_CASE_IDEN><![CDATA[' || :new.STATE_CASE_IDEN || ']]></STATE_CASE_IDEN>
        <STATE_REVIEW_TASK_COUNT>' || :new.STATE_REVIEW_TASK_COUNT || '</STATE_REVIEW_TASK_COUNT>
        <STATE_REVIEW_TASK_ID>' || :new.STATE_REVIEW_TASK_ID || '</STATE_REVIEW_TASK_ID>
        <STG_LAST_UPDATE_DATE>' || to_char(:new.STG_LAST_UPDATE_DATE,BPM_COMMON.GET_DATE_FMT) || '</STG_LAST_UPDATE_DATE>
        <STOP_APP_REASON><![CDATA[' || :new.STOP_APP_REASON || ']]></STOP_APP_REASON>
        <UPSTATE_INDICATOR><![CDATA[' || :new.UPSTATE_INDICATOR || ']]></UPSTATE_INDICATOR>
        <WAIT_STATE_APPROVAL_DT>' || to_char(:new.WAIT_STATE_APPROVAL_DT,BPM_COMMON.GET_DATE_FMT) || '</WAIT_STATE_APPROVAL_DT>
        <WMS_REASON><![CDATA[' || :new.WMS_REASON || ']]></WMS_REASON>
        <WORKFLOW_REACT_IND><![CDATA[' || :new.WORKFLOW_REACT_IND || ']]></WORKFLOW_REACT_IND>
      </ROW>
    </ROWSET>
    ';

  insert into BPM_UPDATE_EVENT_QUEUE (BUEQ_ID,BSL_ID,BIL_ID,IDENTIFIER,EVENT_DATE,QUEUE_DATE,DATA_VERSION,OLD_DATA,NEW_DATA)
  values (SEQ_BUEQ_ID.nextval,v_bsl_id,v_bil_id,v_identifier,v_event_date,sysdate,v_data_version,null,xmltype(v_xml_string_new));
    
exception
     
  when OTHERS then
    v_sql_code := SQLCODE;
    v_log_message := SQLERRM || '
      XML: 
      ' || v_xml_string_new;
    BPM_COMMON.LOGGER(BPM_COMMON.LOG_LEVEL_SEVERE,null,$$PLSQL_UNIT,v_bsl_id,v_bil_id,v_identifier,null,v_log_message,v_sql_code); 
    raise;
  
end;
/


/*
-- This is the standard type of after update to use.
create or replace
trigger TRG_AU_NYEC_ETL_PROCESS_APP_Q
after update on NYEC_ETL_PROCESS_APP
for each row
*/

-- Non-standard after update trigger header.  Only for NYEC Process App.
create or replace trigger TRG_AU_NYEC_ETL_PROCESS_APP_Q
after update of
  APP_COMPLETE_RESULT,
  APP_CYCLE_END_DT,
  APP_CYCLE_START_DT,
  APP_ID,
  APP_STATUS,
  APP_STATUS_GROUP,
  APP_TYPE,
  ASF_CANCEL_APP,
  ASF_CLOSE_APP,
  ASF_COMPLETE_APP,
  ASF_NOTIFY_CLIENT_PENDED_APP,
  ASF_PERFORM_QC,
  ASF_PERFORM_RESEARCH,
  ASF_PROCESS_APP_INFO,
  ASF_RECEIVE_APP,
  ASF_RECEIVE_PROCESS_MI,
  ASF_REVIEW_ENTER_DATA,
  ASF_WAIT_STATE_APPROVAL,
  ASPB_CANCEL_APP,
  ASPB_CLOSE_APP,
  ASPB_COMPLETE_APP,
  ASPB_NOTIFY_CLIENT_PENDED_APP,
  ASPB_PERFORM_QC,
  ASPB_PERFORM_RESEARCH,
  ASPB_PROCESS_APP_INFO,
  ASPB_RVW_ENTER_DATA,
  ASPB_WAIT_STATE_APPROVAL,
  ASSD_NOTIFY_CLIENT_PENDED_APP,
  ASSD_PERFORM_QC,
  ASSD_PERFORM_RESEARCH,
  ASSD_PROCESS_APP_INFO,
  ASSD_RVW_ENTER_DATA,
  ASSD_WAIT_STATE_APPROVAL,
  AUTO_REPROCESS_FLAG,
  CANCEL_DATE,
  CHANNEL,
  CIN,
  CIN_DT,
  CLOCKDOWN_INDICATOR,
  COMPLETE_DT,
  COUNTY,
  CREATE_DT,
  CURRENT_TASK_ID,
  DE_TASK_ID,
  ELIGIBILITY_ACTION,
  FPBP_TYPE,
  GWF_MISSING_INFO,
  GWF_NEW_MI,
  GWF_OUTCM_NOTIFY_RQRD,
  GWF_PEND_NOTIFY_RQRD,
  GWF_QC_OUTCOME,
  GWF_QC_RQRD,
  GWF_RESEARCH,
  HEART_APP_STATUS,
  HEART_CASE_STATUS,
  HEART_INCMPLT_APP_IND,
  HEART_REPROCESS_STATUS,
  HEART_REPROCESS_STATUS_DT,
  HEART_SYNCH_FLAG,
  INVOICE_READY_DT,
  LAST_MAIL_DT,
  MI_RECEIVED_TASK_COUNT,
  NOTIFY_CLIENT_PENDED_APP_DT,
  PERFORM_QC_DT,
  PERFORM_RESEARCH_DT,
  PROCESS_APP_INFO_DT,
  PROVIDER_NAME,
  QC_TASK_ID,
  RECEIPT_DT,
  REFER_LDSS_FLAG,
  RESEARCH_REASON,
  RESEARCH_TASK_ID,
  REV_CLEAR_IND,
  REV_CLEAR_IND_DT,
  REV_CLEAR_OUTCOME,
  RVW_ENTER_DATA_DT,
  SLA_DAYS,
  SLA_DAYS_TYPE,
  SLA_JEOPARDY_DAYS,
  SLA_JEOPARDY_DT,
  SLA_TARGET_DAYS,
  STATE_CASE_IDEN,
  STATE_REVIEW_TASK_COUNT,
  STATE_REVIEW_TASK_ID,
  UPSTATE_INDICATOR,
  WAIT_STATE_APPROVAL_DT,
  WMS_REASON,
  STOP_APP_REASON,
  REACTIVATION_REASON,
  REACTIVATION_IND,
  REACTIVATION_NBR,
  WORKFLOW_REACT_IND,
  CURR_MODE_CD,
  CURR_MODE_LABEL,
  OUTCOME_LTR_TYPE,
  OUTCOME_LTR_STATUS,
  OUTCOME_LTR_ID,
  OUTCOME_LTR_CREATE_DT,
  OUTCOME_LTR_SENT_DT,
  REACTIVATED_BY,
  REACTIVATION_DT,
  OUTCOME_NOTIFY_RQRD_FLAG,
  QC_IND,
  REV_CLEAR_REASON,
  MA_REASON,
  OFFICE_ID,
  APPLICANT_ID,
  REG_TASK_ID,
  QC_REG_TASK_ID,
  PERFORM_QC_REG_DT,
  ASSD_REG_ENTER_DATA,
  ASSD_PERFORM_QC_REG,
  ASPB_REG_ENTER_DATA,
  ASPB_PERFORM_QC_REG,
  NUMBER_OF_APPLICANTS,
  REG_ENTER_DATA_DT
on NYEC_ETL_PROCESS_APP
for each row

declare
  
  v_bsl_id number := 2; -- 'NYEC_ETL_PROCESS_APP'  
  v_bil_id number := 2; -- 'Application ID' 
  -- v_data_version number := 2; -- Added r4 - HEART_CASE_STATUS and STATE_CASE_IDEN.
  -- v_data_version number := 3; -- Removed calculation columns.
  v_data_version number := 4; -- Added reactivation columns.
  
  v_event_date date := null;
  v_identifier varchar2(100) := null;
    
  v_xml_string_old clob := null;
  v_xml_string_new clob := null;
  
  v_sql_code number := null;
  v_log_message clob := null;
   
begin

  v_event_date := :new.STG_LAST_UPDATE_DATE;
  v_identifier := :new.APP_ID || '_' || to_char(:new.REACTIVATION_NBR);

  /* 
  Include: 
    STG_LAST_UPDATE_DATE
  Exclude:
    AGE_IN_BUSINESS_DAYS
    AGE_IN_CALENDAR_DAYS
    APP_CYCLE_BUS_DAYS
    APP_CYCLE_CAL_DAYS
    DAYS_UNTIL_TIMEOUT
    JEOPARDY_FLAG
    TIMELINESS_STATUS
  */  
  v_xml_string_old := 
    '<?xml version="1.0"?>
    <ROWSET>  
      <ROW>
        <APPLICANT_ID>' || :old.APPLICANT_ID || '</APPLICANT_ID>
        <APP_COMPLETE_RESULT><![CDATA[' || :old.APP_COMPLETE_RESULT || ']]></APP_COMPLETE_RESULT>
        <APP_CYCLE_END_DT>' || to_char(:old.APP_CYCLE_END_DT,BPM_COMMON.GET_DATE_FMT) || '</APP_CYCLE_END_DT>
        <APP_CYCLE_START_DT>' || to_char(:old.APP_CYCLE_START_DT,BPM_COMMON.GET_DATE_FMT) || '</APP_CYCLE_START_DT>
        <APP_ID>' || :old.APP_ID || '</APP_ID>
        <APP_STATUS><![CDATA[' || :old.APP_STATUS || ']]></APP_STATUS>
        <APP_STATUS_GROUP><![CDATA[' || :old.APP_STATUS_GROUP || ']]></APP_STATUS_GROUP>
        <APP_TYPE><![CDATA[' || :old.APP_TYPE || ']]></APP_TYPE>
        <ASF_CANCEL_APP><![CDATA[' || :old.ASF_CANCEL_APP || ']]></ASF_CANCEL_APP>
        <ASF_CLOSE_APP><![CDATA[' || :old.ASF_CLOSE_APP || ']]></ASF_CLOSE_APP>
        <ASF_COMPLETE_APP><![CDATA[' || :old.ASF_COMPLETE_APP || ']]></ASF_COMPLETE_APP>
        <ASF_NOTIFY_CLIENT_PENDED_APP><![CDATA[' || :old.ASF_NOTIFY_CLIENT_PENDED_APP || ']]></ASF_NOTIFY_CLIENT_PENDED_APP>
        <ASF_PERFORM_QC><![CDATA[' || :old.ASF_PERFORM_QC || ']]></ASF_PERFORM_QC>
        <ASF_PERFORM_RESEARCH><![CDATA[' || :old.ASF_PERFORM_RESEARCH || ']]></ASF_PERFORM_RESEARCH>
        <ASF_PROCESS_APP_INFO><![CDATA[' || :old.ASF_PROCESS_APP_INFO || ']]></ASF_PROCESS_APP_INFO>
        <ASF_RECEIVE_APP><![CDATA[' || :old.ASF_RECEIVE_APP || ']]></ASF_RECEIVE_APP>
        <ASF_RECEIVE_PROCESS_MI><![CDATA[' || :old.ASF_RECEIVE_PROCESS_MI || ']]></ASF_RECEIVE_PROCESS_MI>
        <ASF_REVIEW_ENTER_DATA><![CDATA[' || :old.ASF_REVIEW_ENTER_DATA || ']]></ASF_REVIEW_ENTER_DATA>
        <ASF_WAIT_STATE_APPROVAL><![CDATA[' || :old.ASF_WAIT_STATE_APPROVAL || ']]></ASF_WAIT_STATE_APPROVAL>
        <ASPB_CANCEL_APP><![CDATA[' || :old.ASPB_CANCEL_APP || ']]></ASPB_CANCEL_APP>
        <ASPB_CLOSE_APP><![CDATA[' || :old.ASPB_CLOSE_APP || ']]></ASPB_CLOSE_APP>
        <ASPB_COMPLETE_APP><![CDATA[' || :old.ASPB_COMPLETE_APP || ']]></ASPB_COMPLETE_APP>
        <ASPB_NOTIFY_CLIENT_PENDED_APP><![CDATA[' || :old.ASPB_NOTIFY_CLIENT_PENDED_APP || ']]></ASPB_NOTIFY_CLIENT_PENDED_APP>
        <ASPB_PERFORM_QC><![CDATA[' || :old.ASPB_PERFORM_QC || ']]></ASPB_PERFORM_QC>
        <ASPB_PERFORM_QC_REG><![CDATA[' || :old.ASPB_PERFORM_QC_REG || ']]></ASPB_PERFORM_QC_REG>
        <ASPB_PERFORM_RESEARCH><![CDATA[' || :old.ASPB_PERFORM_RESEARCH || ']]></ASPB_PERFORM_RESEARCH>
        <ASPB_PROCESS_APP_INFO><![CDATA[' || :old.ASPB_PROCESS_APP_INFO || ']]></ASPB_PROCESS_APP_INFO>
        <ASPB_REG_ENTER_DATA><![CDATA[' || :old.ASPB_REG_ENTER_DATA || ']]></ASPB_REG_ENTER_DATA>
        <ASPB_RVW_ENTER_DATA><![CDATA[' || :old.ASPB_RVW_ENTER_DATA || ']]></ASPB_RVW_ENTER_DATA>
        <ASPB_WAIT_STATE_APPROVAL><![CDATA[' || :old.ASPB_WAIT_STATE_APPROVAL || ']]></ASPB_WAIT_STATE_APPROVAL>
        <ASSD_NOTIFY_CLIENT_PENDED_APP>' || to_char(:old.ASSD_NOTIFY_CLIENT_PENDED_APP,BPM_COMMON.GET_DATE_FMT) || '</ASSD_NOTIFY_CLIENT_PENDED_APP>
        <ASSD_PERFORM_QC>' || to_char(:old.ASSD_PERFORM_QC,BPM_COMMON.GET_DATE_FMT) || '</ASSD_PERFORM_QC>
        <ASSD_PERFORM_QC_REG>' || to_char(:old.ASSD_PERFORM_QC_REG,BPM_COMMON.GET_DATE_FMT) || '</ASSD_PERFORM_QC_REG>
        <ASSD_PERFORM_RESEARCH>' || to_char(:old.ASSD_PERFORM_RESEARCH,BPM_COMMON.GET_DATE_FMT) || '</ASSD_PERFORM_RESEARCH>
        <ASSD_PROCESS_APP_INFO>' || to_char(:old.ASSD_PROCESS_APP_INFO,BPM_COMMON.GET_DATE_FMT) || '</ASSD_PROCESS_APP_INFO>
        <ASSD_REG_ENTER_DATA>' || to_char(:old.ASSD_REG_ENTER_DATA,BPM_COMMON.GET_DATE_FMT) || '</ASSD_REG_ENTER_DATA>
        <ASSD_RVW_ENTER_DATA>' || to_char(:old.ASSD_RVW_ENTER_DATA,BPM_COMMON.GET_DATE_FMT) || '</ASSD_RVW_ENTER_DATA>
        <ASSD_WAIT_STATE_APPROVAL>' || to_char(:old.ASSD_WAIT_STATE_APPROVAL,BPM_COMMON.GET_DATE_FMT) || '</ASSD_WAIT_STATE_APPROVAL>
        <AUTO_REPROCESS_FLAG><![CDATA[' || :old.AUTO_REPROCESS_FLAG || ']]></AUTO_REPROCESS_FLAG>
        <CANCEL_DATE>' || to_char(:old.CANCEL_DATE,BPM_COMMON.GET_DATE_FMT) || '</CANCEL_DATE>
        <CHANNEL><![CDATA[' || :old.CHANNEL || ']]></CHANNEL>
        <CIN><![CDATA[' || :old.CIN || ']]></CIN>
        <CIN_DT>' || to_char(:old.CIN_DT,BPM_COMMON.GET_DATE_FMT) || '</CIN_DT>
        <CLOCKDOWN_INDICATOR><![CDATA[' || :old.CLOCKDOWN_INDICATOR || ']]></CLOCKDOWN_INDICATOR>
        <COMPLETE_DT>' || to_char(:old.COMPLETE_DT,BPM_COMMON.GET_DATE_FMT) || '</COMPLETE_DT>
        <COUNTY><![CDATA[' || :old.COUNTY || ']]></COUNTY>
        <CREATE_DT>' || to_char(:old.CREATE_DT,BPM_COMMON.GET_DATE_FMT) || '</CREATE_DT>
        <CURRENT_TASK_ID>' || :old.CURRENT_TASK_ID || '</CURRENT_TASK_ID>
        <CURR_MODE_CD><![CDATA[' || :old.CURR_MODE_CD || ']]></CURR_MODE_CD>
        <CURR_MODE_LABEL><![CDATA[' || :old.CURR_MODE_LABEL || ']]></CURR_MODE_LABEL>
        <DE_TASK_ID>' || :old.DE_TASK_ID || '</DE_TASK_ID>
        <ELIGIBILITY_ACTION><![CDATA[' || :old.ELIGIBILITY_ACTION || ']]></ELIGIBILITY_ACTION>
        <FPBP_TYPE><![CDATA[' || :old.FPBP_TYPE || ']]></FPBP_TYPE>
        <GWF_MISSING_INFO><![CDATA[' || :old.GWF_MISSING_INFO || ']]></GWF_MISSING_INFO>
        <GWF_NEW_MI><![CDATA[' || :old.GWF_NEW_MI || ']]></GWF_NEW_MI>
        <GWF_OUTCM_NOTIFY_RQRD><![CDATA[' || :old.GWF_OUTCM_NOTIFY_RQRD || ']]></GWF_OUTCM_NOTIFY_RQRD>
        <GWF_PEND_NOTIFY_RQRD><![CDATA[' || :old.GWF_PEND_NOTIFY_RQRD || ']]></GWF_PEND_NOTIFY_RQRD>
        <GWF_QC_OUTCOME><![CDATA[' || :old.GWF_QC_OUTCOME || ']]></GWF_QC_OUTCOME>
        <GWF_QC_RQRD><![CDATA[' || :old.GWF_QC_RQRD || ']]></GWF_QC_RQRD>
        <GWF_RESEARCH><![CDATA[' || :old.GWF_RESEARCH || ']]></GWF_RESEARCH>
        <HEART_APP_STATUS><![CDATA[' || :old.HEART_APP_STATUS || ']]></HEART_APP_STATUS>
        <HEART_CASE_STATUS><![CDATA[' || :old.HEART_CASE_STATUS || ']]></HEART_CASE_STATUS>
        <HEART_INCMPLT_APP_IND><![CDATA[' || :old.HEART_INCMPLT_APP_IND || ']]></HEART_INCMPLT_APP_IND>
        <HEART_REPROCESS_STATUS><![CDATA[' || :old.HEART_REPROCESS_STATUS || ']]></HEART_REPROCESS_STATUS>
        <HEART_REPROCESS_STATUS_DT>' || to_char(:old.HEART_REPROCESS_STATUS_DT,BPM_COMMON.GET_DATE_FMT) || '</HEART_REPROCESS_STATUS_DT>
        <HEART_SYNCH_FLAG><![CDATA[' || :old.HEART_SYNCH_FLAG || ']]></HEART_SYNCH_FLAG>
        <INVOICE_READY_DT>' || to_char(:old.INVOICE_READY_DT,BPM_COMMON.GET_DATE_FMT) || '</INVOICE_READY_DT>
        <LAST_MAIL_DT>' || to_char(:old.LAST_MAIL_DT,BPM_COMMON.GET_DATE_FMT) || '</LAST_MAIL_DT>
        <MA_REASON><![CDATA[' || :old.MA_REASON || ']]></MA_REASON>
        <MI_RECEIVED_TASK_COUNT>' || :old.MI_RECEIVED_TASK_COUNT || '</MI_RECEIVED_TASK_COUNT>
        <NOTIFY_CLIENT_PENDED_APP_DT>' || to_char(:old.NOTIFY_CLIENT_PENDED_APP_DT,BPM_COMMON.GET_DATE_FMT) || '</NOTIFY_CLIENT_PENDED_APP_DT>
        <NUMBER_OF_APPLICANTS>' || :old.NUMBER_OF_APPLICANTS || '</NUMBER_OF_APPLICANTS>
        <OFFICE_ID>' || :old.OFFICE_ID || '</OFFICE_ID>
        <OUTCOME_LTR_CREATE_DT>' || to_char(:old.OUTCOME_LTR_CREATE_DT,BPM_COMMON.GET_DATE_FMT) || '</OUTCOME_LTR_CREATE_DT>
        <OUTCOME_LTR_ID>' || :old.OUTCOME_LTR_ID || '</OUTCOME_LTR_ID>
        <OUTCOME_LTR_SENT_DT>' || to_char(:old.OUTCOME_LTR_SENT_DT,BPM_COMMON.GET_DATE_FMT) || '</OUTCOME_LTR_SENT_DT>
        <OUTCOME_LTR_STATUS><![CDATA[' || :old.OUTCOME_LTR_STATUS || ']]></OUTCOME_LTR_STATUS>
        <OUTCOME_LTR_TYPE><![CDATA[' || :old.OUTCOME_LTR_TYPE || ']]></OUTCOME_LTR_TYPE>
        <OUTCOME_NOTIFY_RQRD_FLAG><![CDATA[' || :old.OUTCOME_NOTIFY_RQRD_FLAG || ']]></OUTCOME_NOTIFY_RQRD_FLAG>
        <PERFORM_QC_DT>' || to_char(:old.PERFORM_QC_DT,BPM_COMMON.GET_DATE_FMT) || '</PERFORM_QC_DT>
        <PERFORM_QC_REG_DT>' || to_char(:old.PERFORM_QC_REG_DT,BPM_COMMON.GET_DATE_FMT) || '</PERFORM_QC_REG_DT>
        <PERFORM_RESEARCH_DT>' || to_char(:old.PERFORM_RESEARCH_DT,BPM_COMMON.GET_DATE_FMT) || '</PERFORM_RESEARCH_DT>
        <PROCESS_APP_INFO_DT>' || to_char(:old.PROCESS_APP_INFO_DT,BPM_COMMON.GET_DATE_FMT) || '</PROCESS_APP_INFO_DT>
        <PROVIDER_NAME><![CDATA[' || :old.PROVIDER_NAME || ']]></PROVIDER_NAME>
        <QC_IND><![CDATA[' || :old.QC_IND || ']]></QC_IND>
        <QC_REG_TASK_ID>' || :old.QC_REG_TASK_ID || '</QC_REG_TASK_ID>
        <QC_TASK_ID>' || :old.QC_TASK_ID || '</QC_TASK_ID>
        <REACTIVATED_BY><![CDATA[' || :old.REACTIVATED_BY || ']]></REACTIVATED_BY>
        <REACTIVATION_DT>' || to_char(:old.REACTIVATION_DT,BPM_COMMON.GET_DATE_FMT) || '</REACTIVATION_DT>
        <REACTIVATION_IND>' || :old.REACTIVATION_IND || '</REACTIVATION_IND>
        <REACTIVATION_NBR>' || :old.REACTIVATION_NBR || '</REACTIVATION_NBR>
        <REACTIVATION_REASON><![CDATA[' || :old.REACTIVATION_REASON || ']]></REACTIVATION_REASON>
        <RECEIPT_DT>' || to_char(:old.RECEIPT_DT,BPM_COMMON.GET_DATE_FMT) || '</RECEIPT_DT>
        <REFER_LDSS_FLAG><![CDATA[' || :old.REFER_LDSS_FLAG || ']]></REFER_LDSS_FLAG>
        <REG_ENTER_DATA_DT>' || to_char(:old.REG_ENTER_DATA_DT,BPM_COMMON.GET_DATE_FMT) || '</REG_ENTER_DATA_DT>
        <REG_TASK_ID>' || :old.REG_TASK_ID || '</REG_TASK_ID>
        <RESEARCH_REASON><![CDATA[' || :old.RESEARCH_REASON || ']]></RESEARCH_REASON>
        <RESEARCH_TASK_ID>' || :old.RESEARCH_TASK_ID || '</RESEARCH_TASK_ID>
        <REV_CLEAR_IND><![CDATA[' || :old.REV_CLEAR_IND || ']]></REV_CLEAR_IND>
        <REV_CLEAR_IND_DT>' || to_char(:old.REV_CLEAR_IND_DT,BPM_COMMON.GET_DATE_FMT) || '</REV_CLEAR_IND_DT>
        <REV_CLEAR_OUTCOME><![CDATA[' || :old.REV_CLEAR_OUTCOME || ']]></REV_CLEAR_OUTCOME>
        <REV_CLEAR_REASON><![CDATA[' || :old.REV_CLEAR_REASON || ']]></REV_CLEAR_REASON>
        <RVW_ENTER_DATA_DT>' || to_char(:old.RVW_ENTER_DATA_DT,BPM_COMMON.GET_DATE_FMT) || '</RVW_ENTER_DATA_DT>
        <SLA_DAYS>' || :old.SLA_DAYS || '</SLA_DAYS>
        <SLA_DAYS_TYPE><![CDATA[' || :old.SLA_DAYS_TYPE || ']]></SLA_DAYS_TYPE>
        <SLA_JEOPARDY_DAYS>' || :old.SLA_JEOPARDY_DAYS || '</SLA_JEOPARDY_DAYS>
        <SLA_JEOPARDY_DT>' || to_char(:old.SLA_JEOPARDY_DT,BPM_COMMON.GET_DATE_FMT) || '</SLA_JEOPARDY_DT>
        <SLA_TARGET_DAYS>' || :old.SLA_TARGET_DAYS || '</SLA_TARGET_DAYS>
        <STATE_CASE_IDEN><![CDATA[' || :old.STATE_CASE_IDEN || ']]></STATE_CASE_IDEN>
        <STATE_REVIEW_TASK_COUNT>' || :old.STATE_REVIEW_TASK_COUNT || '</STATE_REVIEW_TASK_COUNT>
        <STATE_REVIEW_TASK_ID>' || :old.STATE_REVIEW_TASK_ID || '</STATE_REVIEW_TASK_ID>
        <STG_LAST_UPDATE_DATE>' || to_char(:old.STG_LAST_UPDATE_DATE,BPM_COMMON.GET_DATE_FMT) || '</STG_LAST_UPDATE_DATE>
        <STOP_APP_REASON><![CDATA[' || :old.STOP_APP_REASON || ']]></STOP_APP_REASON>
        <UPSTATE_INDICATOR><![CDATA[' || :old.UPSTATE_INDICATOR || ']]></UPSTATE_INDICATOR>
        <WAIT_STATE_APPROVAL_DT>' || to_char(:old.WAIT_STATE_APPROVAL_DT,BPM_COMMON.GET_DATE_FMT) || '</WAIT_STATE_APPROVAL_DT>
        <WMS_REASON><![CDATA[' || :old.WMS_REASON || ']]></WMS_REASON>
        <WORKFLOW_REACT_IND><![CDATA[' || :old.WORKFLOW_REACT_IND || ']]></WORKFLOW_REACT_IND>
      </ROW>
    </ROWSET>
    ';

  /* 
  Include: 
    STG_LAST_UPDATE_DATE
  Exclude:
    AGE_IN_BUSINESS_DAYS
    AGE_IN_CALENDAR_DAYS
    APP_CYCLE_BUS_DAYS
    APP_CYCLE_CAL_DAYS
    DAYS_UNTIL_TIMEOUT
    JEOPARDY_FLAG
    TIMELINESS_STATUS
  */     
  v_xml_string_new := 
    '<?xml version="1.0"?>
    <ROWSET>  
      <ROW>
        <APPLICANT_ID>' || :new.APPLICANT_ID || '</APPLICANT_ID>
        <APP_COMPLETE_RESULT><![CDATA[' || :new.APP_COMPLETE_RESULT || ']]></APP_COMPLETE_RESULT>
        <APP_CYCLE_END_DT>' || to_char(:new.APP_CYCLE_END_DT,BPM_COMMON.GET_DATE_FMT) || '</APP_CYCLE_END_DT>
        <APP_CYCLE_START_DT>' || to_char(:new.APP_CYCLE_START_DT,BPM_COMMON.GET_DATE_FMT) || '</APP_CYCLE_START_DT>
        <APP_ID>' || :new.APP_ID || '</APP_ID>
        <APP_STATUS><![CDATA[' || :new.APP_STATUS || ']]></APP_STATUS>
        <APP_STATUS_GROUP><![CDATA[' || :new.APP_STATUS_GROUP || ']]></APP_STATUS_GROUP>
        <APP_TYPE><![CDATA[' || :new.APP_TYPE || ']]></APP_TYPE>
        <ASF_CANCEL_APP><![CDATA[' || :new.ASF_CANCEL_APP || ']]></ASF_CANCEL_APP>
        <ASF_CLOSE_APP><![CDATA[' || :new.ASF_CLOSE_APP || ']]></ASF_CLOSE_APP>
        <ASF_COMPLETE_APP><![CDATA[' || :new.ASF_COMPLETE_APP || ']]></ASF_COMPLETE_APP>
        <ASF_NOTIFY_CLIENT_PENDED_APP><![CDATA[' || :new.ASF_NOTIFY_CLIENT_PENDED_APP || ']]></ASF_NOTIFY_CLIENT_PENDED_APP>
        <ASF_PERFORM_QC><![CDATA[' || :new.ASF_PERFORM_QC || ']]></ASF_PERFORM_QC>
        <ASF_PERFORM_RESEARCH><![CDATA[' || :new.ASF_PERFORM_RESEARCH || ']]></ASF_PERFORM_RESEARCH>
        <ASF_PROCESS_APP_INFO><![CDATA[' || :new.ASF_PROCESS_APP_INFO || ']]></ASF_PROCESS_APP_INFO>
        <ASF_RECEIVE_APP><![CDATA[' || :new.ASF_RECEIVE_APP || ']]></ASF_RECEIVE_APP>
        <ASF_RECEIVE_PROCESS_MI><![CDATA[' || :new.ASF_RECEIVE_PROCESS_MI || ']]></ASF_RECEIVE_PROCESS_MI>
        <ASF_REVIEW_ENTER_DATA><![CDATA[' || :new.ASF_REVIEW_ENTER_DATA || ']]></ASF_REVIEW_ENTER_DATA>
        <ASF_WAIT_STATE_APPROVAL><![CDATA[' || :new.ASF_WAIT_STATE_APPROVAL || ']]></ASF_WAIT_STATE_APPROVAL>
        <ASPB_CANCEL_APP><![CDATA[' || :new.ASPB_CANCEL_APP || ']]></ASPB_CANCEL_APP>
        <ASPB_CLOSE_APP><![CDATA[' || :new.ASPB_CLOSE_APP || ']]></ASPB_CLOSE_APP>
        <ASPB_COMPLETE_APP><![CDATA[' || :new.ASPB_COMPLETE_APP || ']]></ASPB_COMPLETE_APP>
        <ASPB_NOTIFY_CLIENT_PENDED_APP><![CDATA[' || :new.ASPB_NOTIFY_CLIENT_PENDED_APP || ']]></ASPB_NOTIFY_CLIENT_PENDED_APP>
        <ASPB_PERFORM_QC><![CDATA[' || :new.ASPB_PERFORM_QC || ']]></ASPB_PERFORM_QC>
        <ASPB_PERFORM_QC_REG><![CDATA[' || :new.ASPB_PERFORM_QC_REG || ']]></ASPB_PERFORM_QC_REG>
        <ASPB_PERFORM_RESEARCH><![CDATA[' || :new.ASPB_PERFORM_RESEARCH || ']]></ASPB_PERFORM_RESEARCH>
        <ASPB_PROCESS_APP_INFO><![CDATA[' || :new.ASPB_PROCESS_APP_INFO || ']]></ASPB_PROCESS_APP_INFO>
        <ASPB_REG_ENTER_DATA><![CDATA[' || :new.ASPB_REG_ENTER_DATA || ']]></ASPB_REG_ENTER_DATA>
        <ASPB_RVW_ENTER_DATA><![CDATA[' || :new.ASPB_RVW_ENTER_DATA || ']]></ASPB_RVW_ENTER_DATA>
        <ASPB_WAIT_STATE_APPROVAL><![CDATA[' || :new.ASPB_WAIT_STATE_APPROVAL || ']]></ASPB_WAIT_STATE_APPROVAL>
        <ASSD_NOTIFY_CLIENT_PENDED_APP>' || to_char(:new.ASSD_NOTIFY_CLIENT_PENDED_APP,BPM_COMMON.GET_DATE_FMT) || '</ASSD_NOTIFY_CLIENT_PENDED_APP>
        <ASSD_PERFORM_QC>' || to_char(:new.ASSD_PERFORM_QC,BPM_COMMON.GET_DATE_FMT) || '</ASSD_PERFORM_QC>
        <ASSD_PERFORM_QC_REG>' || to_char(:new.ASSD_PERFORM_QC_REG,BPM_COMMON.GET_DATE_FMT) || '</ASSD_PERFORM_QC_REG>
        <ASSD_PERFORM_RESEARCH>' || to_char(:new.ASSD_PERFORM_RESEARCH,BPM_COMMON.GET_DATE_FMT) || '</ASSD_PERFORM_RESEARCH>
        <ASSD_PROCESS_APP_INFO>' || to_char(:new.ASSD_PROCESS_APP_INFO,BPM_COMMON.GET_DATE_FMT) || '</ASSD_PROCESS_APP_INFO>
        <ASSD_REG_ENTER_DATA>' || to_char(:new.ASSD_REG_ENTER_DATA,BPM_COMMON.GET_DATE_FMT) || '</ASSD_REG_ENTER_DATA>
        <ASSD_RVW_ENTER_DATA>' || to_char(:new.ASSD_RVW_ENTER_DATA,BPM_COMMON.GET_DATE_FMT) || '</ASSD_RVW_ENTER_DATA>
        <ASSD_WAIT_STATE_APPROVAL>' || to_char(:new.ASSD_WAIT_STATE_APPROVAL,BPM_COMMON.GET_DATE_FMT) || '</ASSD_WAIT_STATE_APPROVAL>
        <AUTO_REPROCESS_FLAG><![CDATA[' || :new.AUTO_REPROCESS_FLAG || ']]></AUTO_REPROCESS_FLAG>
        <CANCEL_DATE>' || to_char(:new.CANCEL_DATE,BPM_COMMON.GET_DATE_FMT) || '</CANCEL_DATE>
        <CHANNEL><![CDATA[' || :new.CHANNEL || ']]></CHANNEL>
        <CIN><![CDATA[' || :new.CIN || ']]></CIN>
        <CIN_DT>' || to_char(:new.CIN_DT,BPM_COMMON.GET_DATE_FMT) || '</CIN_DT>
        <CLOCKDOWN_INDICATOR><![CDATA[' || :new.CLOCKDOWN_INDICATOR || ']]></CLOCKDOWN_INDICATOR>
        <COMPLETE_DT>' || to_char(:new.COMPLETE_DT,BPM_COMMON.GET_DATE_FMT) || '</COMPLETE_DT>
        <COUNTY><![CDATA[' || :new.COUNTY || ']]></COUNTY>
        <CREATE_DT>' || to_char(:new.CREATE_DT,BPM_COMMON.GET_DATE_FMT) || '</CREATE_DT>
        <CURRENT_TASK_ID>' || :new.CURRENT_TASK_ID || '</CURRENT_TASK_ID>
        <CURR_MODE_CD><![CDATA[' || :new.CURR_MODE_CD || ']]></CURR_MODE_CD>
        <CURR_MODE_LABEL><![CDATA[' || :new.CURR_MODE_LABEL || ']]></CURR_MODE_LABEL>
        <DE_TASK_ID>' || :new.DE_TASK_ID || '</DE_TASK_ID>
        <ELIGIBILITY_ACTION><![CDATA[' || :new.ELIGIBILITY_ACTION || ']]></ELIGIBILITY_ACTION>
        <FPBP_TYPE><![CDATA[' || :new.FPBP_TYPE || ']]></FPBP_TYPE>
        <GWF_MISSING_INFO><![CDATA[' || :new.GWF_MISSING_INFO || ']]></GWF_MISSING_INFO>
        <GWF_NEW_MI><![CDATA[' || :new.GWF_NEW_MI || ']]></GWF_NEW_MI>
        <GWF_OUTCM_NOTIFY_RQRD><![CDATA[' || :new.GWF_OUTCM_NOTIFY_RQRD || ']]></GWF_OUTCM_NOTIFY_RQRD>
        <GWF_PEND_NOTIFY_RQRD><![CDATA[' || :new.GWF_PEND_NOTIFY_RQRD || ']]></GWF_PEND_NOTIFY_RQRD>
        <GWF_QC_OUTCOME><![CDATA[' || :new.GWF_QC_OUTCOME || ']]></GWF_QC_OUTCOME>
        <GWF_QC_RQRD><![CDATA[' || :new.GWF_QC_RQRD || ']]></GWF_QC_RQRD>
        <GWF_RESEARCH><![CDATA[' || :new.GWF_RESEARCH || ']]></GWF_RESEARCH>
        <HEART_APP_STATUS><![CDATA[' || :new.HEART_APP_STATUS || ']]></HEART_APP_STATUS>
        <HEART_CASE_STATUS><![CDATA[' || :new.HEART_CASE_STATUS || ']]></HEART_CASE_STATUS>
        <HEART_INCMPLT_APP_IND><![CDATA[' || :new.HEART_INCMPLT_APP_IND || ']]></HEART_INCMPLT_APP_IND>
        <HEART_REPROCESS_STATUS><![CDATA[' || :new.HEART_REPROCESS_STATUS || ']]></HEART_REPROCESS_STATUS>
        <HEART_REPROCESS_STATUS_DT>' || to_char(:new.HEART_REPROCESS_STATUS_DT,BPM_COMMON.GET_DATE_FMT) || '</HEART_REPROCESS_STATUS_DT>
        <HEART_SYNCH_FLAG><![CDATA[' || :new.HEART_SYNCH_FLAG || ']]></HEART_SYNCH_FLAG>
        <INVOICE_READY_DT>' || to_char(:new.INVOICE_READY_DT,BPM_COMMON.GET_DATE_FMT) || '</INVOICE_READY_DT>
        <LAST_MAIL_DT>' || to_char(:new.LAST_MAIL_DT,BPM_COMMON.GET_DATE_FMT) || '</LAST_MAIL_DT>
        <MA_REASON><![CDATA[' || :new.MA_REASON || ']]></MA_REASON>
        <MI_RECEIVED_TASK_COUNT>' || :new.MI_RECEIVED_TASK_COUNT || '</MI_RECEIVED_TASK_COUNT>
        <NOTIFY_CLIENT_PENDED_APP_DT>' || to_char(:new.NOTIFY_CLIENT_PENDED_APP_DT,BPM_COMMON.GET_DATE_FMT) || '</NOTIFY_CLIENT_PENDED_APP_DT>
        <NUMBER_OF_APPLICANTS>' || :new.NUMBER_OF_APPLICANTS || '</NUMBER_OF_APPLICANTS>
        <OFFICE_ID>' || :new.OFFICE_ID || '</OFFICE_ID>
        <OUTCOME_LTR_CREATE_DT>' || to_char(:new.OUTCOME_LTR_CREATE_DT,BPM_COMMON.GET_DATE_FMT) || '</OUTCOME_LTR_CREATE_DT>
        <OUTCOME_LTR_ID>' || :new.OUTCOME_LTR_ID || '</OUTCOME_LTR_ID>
        <OUTCOME_LTR_SENT_DT>' || to_char(:new.OUTCOME_LTR_SENT_DT,BPM_COMMON.GET_DATE_FMT) || '</OUTCOME_LTR_SENT_DT>
        <OUTCOME_LTR_STATUS><![CDATA[' || :new.OUTCOME_LTR_STATUS || ']]></OUTCOME_LTR_STATUS>
        <OUTCOME_LTR_TYPE><![CDATA[' || :new.OUTCOME_LTR_TYPE || ']]></OUTCOME_LTR_TYPE>
        <OUTCOME_NOTIFY_RQRD_FLAG><![CDATA[' || :new.OUTCOME_NOTIFY_RQRD_FLAG || ']]></OUTCOME_NOTIFY_RQRD_FLAG>
        <PERFORM_QC_DT>' || to_char(:new.PERFORM_QC_DT,BPM_COMMON.GET_DATE_FMT) || '</PERFORM_QC_DT>
        <PERFORM_QC_REG_DT>' || to_char(:new.PERFORM_QC_REG_DT,BPM_COMMON.GET_DATE_FMT) || '</PERFORM_QC_REG_DT>
        <PERFORM_RESEARCH_DT>' || to_char(:new.PERFORM_RESEARCH_DT,BPM_COMMON.GET_DATE_FMT) || '</PERFORM_RESEARCH_DT>
        <PROCESS_APP_INFO_DT>' || to_char(:new.PROCESS_APP_INFO_DT,BPM_COMMON.GET_DATE_FMT) || '</PROCESS_APP_INFO_DT>
        <PROVIDER_NAME><![CDATA[' || :new.PROVIDER_NAME || ']]></PROVIDER_NAME>
        <QC_IND><![CDATA[' || :new.QC_IND || ']]></QC_IND>
        <QC_REG_TASK_ID>' || :new.QC_REG_TASK_ID || '</QC_REG_TASK_ID>
        <QC_TASK_ID>' || :new.QC_TASK_ID || '</QC_TASK_ID>
        <REACTIVATED_BY><![CDATA[' || :new.REACTIVATED_BY || ']]></REACTIVATED_BY>
        <REACTIVATION_DT>' || to_char(:new.REACTIVATION_DT,BPM_COMMON.GET_DATE_FMT) || '</REACTIVATION_DT>
        <REACTIVATION_IND>' || :new.REACTIVATION_IND || '</REACTIVATION_IND>
        <REACTIVATION_NBR>' || :new.REACTIVATION_NBR || '</REACTIVATION_NBR>
        <REACTIVATION_REASON><![CDATA[' || :new.REACTIVATION_REASON || ']]></REACTIVATION_REASON>
        <RECEIPT_DT>' || to_char(:new.RECEIPT_DT,BPM_COMMON.GET_DATE_FMT) || '</RECEIPT_DT>
        <REFER_LDSS_FLAG><![CDATA[' || :new.REFER_LDSS_FLAG || ']]></REFER_LDSS_FLAG>
        <REG_ENTER_DATA_DT>' || to_char(:new.REG_ENTER_DATA_DT,BPM_COMMON.GET_DATE_FMT) || '</REG_ENTER_DATA_DT>
        <REG_TASK_ID>' || :new.REG_TASK_ID || '</REG_TASK_ID>
        <RESEARCH_REASON><![CDATA[' || :new.RESEARCH_REASON || ']]></RESEARCH_REASON>
        <RESEARCH_TASK_ID>' || :new.RESEARCH_TASK_ID || '</RESEARCH_TASK_ID>
        <REV_CLEAR_IND><![CDATA[' || :new.REV_CLEAR_IND || ']]></REV_CLEAR_IND>
        <REV_CLEAR_IND_DT>' || to_char(:new.REV_CLEAR_IND_DT,BPM_COMMON.GET_DATE_FMT) || '</REV_CLEAR_IND_DT>
        <REV_CLEAR_OUTCOME><![CDATA[' || :new.REV_CLEAR_OUTCOME || ']]></REV_CLEAR_OUTCOME>
        <REV_CLEAR_REASON><![CDATA[' || :new.REV_CLEAR_REASON || ']]></REV_CLEAR_REASON>
        <RVW_ENTER_DATA_DT>' || to_char(:new.RVW_ENTER_DATA_DT,BPM_COMMON.GET_DATE_FMT) || '</RVW_ENTER_DATA_DT>
        <SLA_DAYS>' || :new.SLA_DAYS || '</SLA_DAYS>
        <SLA_DAYS_TYPE><![CDATA[' || :new.SLA_DAYS_TYPE || ']]></SLA_DAYS_TYPE>
        <SLA_JEOPARDY_DAYS>' || :new.SLA_JEOPARDY_DAYS || '</SLA_JEOPARDY_DAYS>
        <SLA_JEOPARDY_DT>' || to_char(:new.SLA_JEOPARDY_DT,BPM_COMMON.GET_DATE_FMT) || '</SLA_JEOPARDY_DT>
        <SLA_TARGET_DAYS>' || :new.SLA_TARGET_DAYS || '</SLA_TARGET_DAYS>
        <STATE_CASE_IDEN><![CDATA[' || :new.STATE_CASE_IDEN || ']]></STATE_CASE_IDEN>
        <STATE_REVIEW_TASK_COUNT>' || :new.STATE_REVIEW_TASK_COUNT || '</STATE_REVIEW_TASK_COUNT>
        <STATE_REVIEW_TASK_ID>' || :new.STATE_REVIEW_TASK_ID || '</STATE_REVIEW_TASK_ID>
        <STG_LAST_UPDATE_DATE>' || to_char(:new.STG_LAST_UPDATE_DATE,BPM_COMMON.GET_DATE_FMT) || '</STG_LAST_UPDATE_DATE>
        <STOP_APP_REASON><![CDATA[' || :new.STOP_APP_REASON || ']]></STOP_APP_REASON>
        <UPSTATE_INDICATOR><![CDATA[' || :new.UPSTATE_INDICATOR || ']]></UPSTATE_INDICATOR>
        <WAIT_STATE_APPROVAL_DT>' || to_char(:new.WAIT_STATE_APPROVAL_DT,BPM_COMMON.GET_DATE_FMT) || '</WAIT_STATE_APPROVAL_DT>
        <WMS_REASON><![CDATA[' || :new.WMS_REASON || ']]></WMS_REASON>
        <WORKFLOW_REACT_IND><![CDATA[' || :new.WORKFLOW_REACT_IND || ']]></WORKFLOW_REACT_IND>
     </ROW>
    </ROWSET>
    ';

  insert into BPM_UPDATE_EVENT_QUEUE
      (BUEQ_ID,BSL_ID,BIL_ID,IDENTIFIER,EVENT_DATE,QUEUE_DATE,DATA_VERSION,OLD_DATA,NEW_DATA)
      values (SEQ_BUEQ_ID.nextval,v_bsl_id,v_bil_id,v_identifier,v_event_date,sysdate,v_data_version,xmltype(v_xml_string_old),xmltype(v_xml_string_new));
  
exception
     
  when OTHERS then
    v_sql_code := SQLCODE;
    v_log_message := SQLERRM || ' 
      XML (old): 
      ' || v_xml_string_old || ' 
      XML (new): 
      ' || v_xml_string_new;
    BPM_COMMON.LOGGER(BPM_COMMON.LOG_LEVEL_SEVERE,null,$$PLSQL_UNIT,v_bsl_id,v_bil_id,v_identifier,null,v_log_message,v_sql_code);  
    raise;

end;
/

alter session set plsql_code_type = interpreted;