--------------------------------------------------------
--  File created - Thursday-June-26-2014   
--------------------------------------------------------
REM INSERTING into  CORP_ETL_CONTROL
SET DEFINE OFF;
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_BATCH_CLASS_LIST2','V','FL Regular Mail','These are the FL PROD Batch Classes',to_date('25-JUN-14','DD-MON-RR'),to_date('25-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_BATCH_CLASS_LIST3','V','FL E-Mails','These are the FL PROD Batch Classes',to_date('25-JUN-14','DD-MON-RR'),to_date('25-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_BATCH_CLASS_LIST4','V','FL Return Mail - Without Address','These are the FL PROD Batch Classes',to_date('25-JUN-14','DD-MON-RR'),to_date('25-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_BATCH_CLASS_LIST5','V','FL Return Mail- With Address','These are the FL PROD Batch Classes',to_date('25-JUN-14','DD-MON-RR'),to_date('25-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_BATCH_CLASS_LIST6','V','FL Applications with FI','These are the FL PROD Batch Classes',to_date('25-JUN-14','DD-MON-RR'),to_date('25-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_ARS_LAST_UPDATE_DATE','D','24-JUN-14','This is the date of the last ProcessMailFaxBatch Reporting database run.',to_date('24-JUN-14','DD-MON-RR'),to_date('25-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_ARS_LOOKBACK_DAYS','N','3','This is the number of days to look back for Batch Created in ProcessMailFaxBatch Remote database run.',to_date('24-JUN-14','DD-MON-RR'),to_date('24-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_BATCH_CLASS_LIST1','V','FL Faxes','These are the FL PROD Batch Classes',to_date('24-JUN-14','DD-MON-RR'),to_date('24-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_CENTRAL_LAST_UPDATE_DATE','D','24-JUN-14','This is the date of the last ProcessMailFaxBatch Central database run.',to_date('24-JUN-14','DD-MON-RR'),to_date('25-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_CENTRAL_LOOKBACK_DAYS','N','3','This is the number of days to look back for Batch Created in ProcessMailFaxBatch Remote database run.',to_date('24-JUN-14','DD-MON-RR'),to_date('24-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_CLASSIFICATION_MODULE_NAME','V','KCN Server','This is the Kofax Classification Module Name',to_date('24-JUN-14','DD-MON-RR'),to_date('24-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_EXPORT_MODULE_NAME','V','Export','This is the Kofax Export Module Name',to_date('24-JUN-14','DD-MON-RR'),to_date('24-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_PDF_MODULE_NAME','V','PDF Generator','This is the Kofax PDF Module Name',to_date('24-JUN-14','DD-MON-RR'),to_date('24-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_QC_MODULE_NAME','V','Quality Control','This is the Kofax QC Module Name',to_date('24-JUN-14','DD-MON-RR'),to_date('24-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_RECOGNITION_MODULE_NAME','V','KTM Server','This is the Kofax Recognition Module Name',to_date('24-JUN-14','DD-MON-RR'),to_date('24-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_REMOTE_LAST_UPDATE_DATE','D','24-JUN-14','This is the date of the last ProcessMailFaxBatch Remote database run.',to_date('24-JUN-14','DD-MON-RR'),to_date('25-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_REMOTE_LOOKBACK_DAYS','N','3','This is the number of days to look back for Batch Created in ProcessMailFaxBatch Remote database run.',to_date('24-JUN-14','DD-MON-RR'),to_date('24-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_REPORT_MODULE_NAME','V','Advanced Reports - Data Exporter','This is the Kofax Report Module Name',to_date('24-JUN-14','DD-MON-RR'),to_date('24-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_SCAN_MODULE_NAME','V','Scan','This is the Kofax Scan Module Name',to_date('24-JUN-14','DD-MON-RR'),to_date('24-JUN-14','DD-MON-RR'));
Insert into  CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) values ('MFB_VALIDATION_MODULE_NAME','V','KTM Validation','This is the Kofax Validation Module Name',to_date('24-JUN-14','DD-MON-RR'),to_date('24-JUN-14','DD-MON-RR'));
commit;
