create or replace view MARS_DP4BI_PROD.PUBLIC.MIO_D_CPU_AND_CVIU_QA_SCORES_SV(
SCORECARD_TYPE
,EW_CASE_UNIT
,CASE_TYPE
,CARDTYPE
,DECISION_DATE
, MONTH_NAME
,QA_PERCENTAGE
,CASE_IDENTIFIER
,ALTERNATIVE_CASE_NUMBER
,ANSWER
,QA_STATUS
,QA_COMPLETE
,QUESTION_IDENTIFIER
,QUESTION
,RESPONSIBLE_INDIVIDUAL_SUPERVISOR
,RESPONSIBLE_INDIVIDUAL_NAME
,POSSIBLE_POINTS
,MISSED_POINTS
, EARNED_POINTS
,PROMPT_TYPE 
,REPORT_TYPE
,CPU_NEW_APPLICATIONS_TOTAL_AUDITS
,CPU_RENEWALS_TOTAL_AUDITS
,TIMES_ANSWERED
,TIMES_MISSED
,NESTING_TOTAL_AUDITS
, NESTING_MISSED_AUDITS) COPY GRANTS
as
SELECT INF.SCORECARD_TYPE AS SCORECARD_TYPE
,INF.EW_CASE_UNIT AS EW_CASE_UNIT
,CASE_TYPE AS CASE_TYPE
,CARDTYPE AS CARDTYPE
,INF.DECISION_DATE AS DECISION_DATE
,CONCAT(MONTHNAME(DECISION_DATE),'-',YEAR(DECISION_DATE)) AS MONTH_NAME
,INF.QA_PERCENTAGE AS QA_PERCENTAGE
,INF.CASE_IDENTIFIER AS CASE_IDENTIFIER
,ALTERNATIVE_CASE_NUMBER AS ALTERNATIVE_CASE_NUMBER
,SC.ANSWER AS ANSWER
,INF.QA_STATUS AS QA_STATUS
,QA_COMPLETE AS QA_COMPLETE
,QUESTION_IDENTIFIER AS QUESTION_IDENTIFIER
,QUESTION AS QUESTION
,RESPONSIBLE_INDIVIDUAL_SUPERVISOR AS RESPONSIBLE_INDIVIDUAL_SUPERVISOR
,RESPONSIBLE_INDIVIDUAL_NAME AS RESPONSIBLE_INDIVIDUAL_NAME
,POSSIBLE_POINTS
,MISSED_POINTS
,POSSIBLE_POINTS-MISSED_POINTS AS EARNED_POINTS
,CASE WHEN SCORECARD_TYPE IN ('CPU','CPU Renewal') THEN 'CPU'
WHEN SCORECARD_TYPE IN ('CVIU Eligibility','CVIU Renewal') THEN 'CVIU' END AS PROMPT_TYPE 
,CASE 
 WHEN INF.SCORECARD_TYPE='CPU' AND CASE_TYPE='A' AND  CardType IN ('Production', 'Nesting 1', 'Nesting 2') THEN 'CPU New Applications'
 WHEN INF.SCORECARD_TYPE='CPU' AND CASE_TYPE='A' AND  CardType IN ('Nesting 1', 'Nesting 2') THEN 'CPU New Applications Nesting'
 WHEN INF.SCORECARD_TYPE='CPU Renewal' AND CASE_TYPE IN ('R', 'E' , 'N')  AND  CardType IN ('Production', 'Nesting 1', 'Nesting 2') THEN 'CPU Renewals'
 WHEN INF.SCORECARD_TYPE='CPU Renewal' AND CASE_TYPE IN ('R', 'E' , 'N') AND  CardType IN ('Nesting 1', 'Nesting 2') THEN 'CPU Renewals Nesting'
 WHEN INF.SCORECARD_TYPE='CVIU Eligibility' AND CASE_TYPE='A' AND  CardType IN ('Production', 'Nesting 1', 'Nesting 2') THEN 'CVIU E New Applications'
 WHEN INF.SCORECARD_TYPE='CVIU Eligibility' AND CASE_TYPE='A' AND  CardType IN ('Nesting 1', 'Nesting 2') THEN 'CVIU E New Applications Nesting'
 WHEN INF.SCORECARD_TYPE='CVIU Renewal' AND CASE_TYPE IN ('R', 'E' , 'N')  AND  CardType IN ('Production', 'Nesting 1', 'Nesting 2') THEN 'CVIU E Renewals'
 WHEN INF.SCORECARD_TYPE='CVIU Renewal' AND CASE_TYPE IN ('R', 'E' , 'N') AND  CardType IN ('Nesting 1', 'Nesting 2') THEN 'CVIU E Renewals Nesting' END AS REPORT_TYPE
--Total Audits
,CASE WHEN  CASE_TYPE='A' THEN 1 ELSE 0 END AS CPU_NEW_APPLICATIONS_TOTAL_AUDITS
,CASE WHEN CASE_TYPE IN ('R', 'E' , 'N') THEN 1 ELSE 0 END AS CPU_RENEWALS_TOTAL_AUDITS
,CASE WHEN SC.ANSWER IN ('Y','N','NA') AND CardType IN ('Production', 'Nesting 1', 'Nesting 2') THEN 1 ELSE 0 END AS TIMES_ANSWERED
,CASE WHEN SC.ANSWER IN ('N') AND CardType IN ('Production') THEN 1 ELSE 0 END AS TIMES_MISSED
,CASE WHEN SC.ANSWER IN ('Y','N','NA') AND CardType IN ('Nesting 1', 'Nesting 2') THEN 1 ELSE 0 END AS NESTING_TOTAL_AUDITS
,CASE WHEN SC.ANSWER IN ('N') AND CardType IN ('Nesting 1', 'Nesting 2') THEN 1 ELSE 0 END AS NESTING_MISSED_AUDITS
FROM COVERVA_MIO.QA_INFO INF
JOIN COVERVA_MIO.QA_SCORES SC
ON INF.ID=SC.QA_INFO_ID
where INF.dmas_ic_submission='N'
AND CASE_TYPE IN ('A','R','E','N')
AND SCORECARD_TYPE IN ('CPU','CPU Renewal','CVIU Eligibility','CVIU Renewal')
AND QA_STATUS in ('Initial Review Complete', 'Worker Review', 'Updated', 'Post DMAS Audit','Dispute')
AND CardType IN ('Production', 'Nesting 1', 'Nesting 2')
AND INF.DECISION_DATE BETWEEN DATE_TRUNC(month, DATEADD(year, -2, sysdate())) AND sysdate();

GRANT SELECT ON VIEW MARS_DP4BI_PROD.PUBLIC.MIO_D_CPU_AND_CVIU_QA_SCORES_SV TO DATA_SUPPORT_ROLE;