DROP INDEX STG_IDX2_PHONENUM;

CREATE UNIQUE INDEX EMRS_S_PHONE_STG_PK ON EMRS_S_PHONE_STG (PHON_ID) TABLESPACE MAXDAT_LAEB_DATA;
ALTER TABLE EMRS_S_PHONE_STG ADD CONSTRAINT EMRS_S_PHONE_STG_PK PRIMARY KEY (PHON_ID) USING INDEX EMRS_S_PHONE_STG_PK ENABLE;


