CREATE SEQUENCE  "EMRS_SEQ_CASESTATUS_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1061 CACHE 20 NOORDER  NOCYCLE ;

GRANT SELECT ON "EMRS_SEQ_CASESTATUS_ID" TO &role_name;

CREATE TABLE EMRS_D_CASE_STATUS
   (CASE_STATUS_ID NUMBER NOT NULL, 
    CASE_STATUS_CODE VARCHAR2(32),
    CASE_STATUS VARCHAR2(240)  
	  ) TABLESPACE &tablespace_name ;

 ALTER TABLE "EMRS_D_CASE_STATUS" ADD CONSTRAINT "CASESTATUS_COMB_UK" UNIQUE ("CASE_STATUS_CODE") USING INDEX  TABLESPACE &tablespace_name  ENABLE;
 ALTER TABLE "EMRS_D_CASE_STATUS" ADD CONSTRAINT "CASESTATUSPK" PRIMARY KEY ("CASE_STATUS_ID") USING INDEX TABLESPACE &tablespace_name  ENABLE;
  
GRANT SELECT ON "EMRS_D_CASE_STATUS" TO &role_name;

CREATE OR REPLACE TRIGGER "BIR_CASE_STATUS" 
 BEFORE INSERT
 ON emrs_d_case_status
 FOR EACH ROW
DECLARE
    v_seq_id     EMRS_D_CASE_STATUS.case_status_id%TYPE;
BEGIN
  IF :NEW.case_status_id IS NULL THEN
    SElECT EMRS_SEQ_CASESTATUS_ID.NEXTVAL
    INTO v_seq_id
    FROM dual;

    :NEW.case_status_id       := v_seq_id;
  END IF;
END BIR_CASE_STATUS;
/
ALTER TRIGGER "BIR_CASE_STATUS" ENABLE;
/

CREATE OR REPLACE VIEW EMRS_D_CASE_STATUS_SV
AS
SELECT case_status_code case_status_cd
       ,case_status
FROM emrs_d_case_status;

GRANT SELECT ON "EMRS_D_CASE_STATUS_SV" TO &role_name;
