CREATE SEQUENCE  "EMRS_SEQ_ZIPLOC_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1061 CACHE 20 NOORDER  NOCYCLE ;

GRANT SELECT ON "EMRS_SEQ_ZIPLOC_ID" TO &role_name;

CREATE TABLE EMRS_D_ZIP_LOCATIONS
   (ZIP_LOCATION_ID NUMBER NOT NULL, 
    ZIP_CODE NUMBER(7,0), 
    PLACE_NAME VARCHAR2(18), 
    STATE VARCHAR2(9), 
    STATE_ABBREVIATION VARCHAR2(2), 
    COUNTY VARCHAR2(20), 
    LATITUDE NUMBER(6,4), 
    LONGITUDE NUMBER(6,4)  
	  ) TABLESPACE  &tablespace_name ;

 ALTER TABLE "EMRS_D_ZIP_LOCATIONS" ADD CONSTRAINT "ZIPLOC_COMB_UK" UNIQUE ("ZIP_CODE") USING INDEX  TABLESPACE &tablespace_name  ENABLE;
 ALTER TABLE "EMRS_D_ZIP_LOCATIONS" ADD CONSTRAINT "ZIPLOCPK" PRIMARY KEY ("ZIP_LOCATION_ID") USING INDEX TABLESPACE &tablespace_name  ENABLE;
  
GRANT SELECT ON "EMRS_D_ZIP_LOCATIONS" TO &role_name;

CREATE OR REPLACE TRIGGER "BIR_ZIPLOC"
 BEFORE INSERT
 ON emrs_d_zip_locations
 FOR EACH ROW
DECLARE
    v_seq_id     EMRS_D_ZIP_LOCATIONS.zip_location_id%TYPE;
BEGIN
  IF :NEW.zip_location_id IS NULL THEN
    SElECT EMRS_SEQ_ZIPLOC_ID.NEXTVAL
    INTO v_seq_id
    FROM dual;

    :NEW.zip_location_id       := v_seq_id;
  END IF;
END BIR_ZIPLOC;
/
ALTER TRIGGER "BIR_ZIPLOC" ENABLE;
/

CREATE OR REPLACE VIEW EMRS_D_ZIP_LOCATIONS_SV
AS
SELECT zip_code
       ,place_name
       ,state
       ,state_abbreviation
       ,county
       ,latitude
       ,longitude
FROM emrs_d_zip_locations;

GRANT SELECT ON "EMRS_D_ZIP_LOCATIONS_SV" TO &role_name;
