
DROP TABLE MAXDAT_LAEB.EMRS_S_NETWORK_LANGUAGE_STG CASCADE CONSTRAINTS;

CREATE TABLE MAXDAT_LAEB.EMRS_S_NETWORK_LANGUAGE_STG
	(
	  NETWORK_ID          NUMBER (18)
	, LANGUAGE_TYPE_CD    VARCHAR2 (32)
	, PROVIDER_SPEAKS_IND NUMBER (1)
	, CREATE_TS           DATE
	, CREATED_BY          VARCHAR2 (80)
	, UPDATE_TS           DATE
	, UPDATED_BY          VARCHAR2 (80)
	, LANGUAGE_EXT_CD     VARCHAR2 (2)
	)
	TABLESPACE MAXDAT_LAEB_DATA
	STORAGE (BUFFER_POOL DEFAULT);

CREATE INDEX XPKSNETWORK_LANGUAGE
	ON MAXDAT_LAEB.EMRS_S_NETWORK_LANGUAGE_STG (NETWORK_ID, LANGUAGE_TYPE_CD)
	TABLESPACE MAXDAT_LAEB_DATA;

GRANT SELECT ON MAXDAT_LAEB.EMRS_S_NETWORK_LANGUAGE_STG TO MAXDAT_LAEB_READ_ONLY;

DROP TABLE MAXDAT_LAEB.EMRS_S_NETWORK_OFFICE_HOURS_STG CASCADE CONSTRAINTS;

CREATE TABLE MAXDAT_LAEB.EMRS_S_NETWORK_OFFICE_HOURS_STG
	(
	  NETWORK_OFFICE_HOURS_ID NUMBER (18) NOT NULL
	, DAY_OF_WEEK             VARCHAR2 (20)
	, OPEN_FROM               VARCHAR2 (8)
	, CLOSE_AT                VARCHAR2 (8)
	, CREATED_BY              VARCHAR2 (30)
	, CREATE_TS               DATE
	, UPDATED_BY              VARCHAR2 (30)
	, UPDATE_TS               DATE
	, NETWORK_ID              NUMBER (18),
	CONSTRAINT SNOHR_PK PRIMARY KEY (NETWORK_OFFICE_HOURS_ID)
	)
	TABLESPACE MAXDAT_LAEB_DATA
	STORAGE (BUFFER_POOL DEFAULT);

GRANT SELECT ON MAXDAT_LAEB.EMRS_S_NETWORK_OFFICE_HOURS_STG TO MAXDAT_LAEB_READ_ONLY;

DROP TABLE MAXDAT_LAEB.EMRS_S_NETWORK_SPECIALTY_STG CASCADE CONSTRAINTS;

CREATE TABLE MAXDAT_LAEB.EMRS_S_NETWORK_SPECIALTY_STG
	(
	  NETWORK_ID        NUMBER (18) NOT NULL
	, SPECIALTY_TYPE_CD VARCHAR2 (32) NOT NULL
	, CREATE_TS         DATE
	, CREATED_BY        VARCHAR2 (80)
	, UPDATE_TS         DATE
	, UPDATED_BY        VARCHAR2 (80)
	, SPECIALTY_EXT_CD  VARCHAR2 (2),
	CONSTRAINT XPKSNETWORK_SPECIALTY PRIMARY KEY (NETWORK_ID, SPECIALTY_TYPE_CD)
	)
	TABLESPACE MAXDAT_LAEB_DATA
	STORAGE (BUFFER_POOL DEFAULT);

GRANT SELECT ON MAXDAT_LAEB.EMRS_S_NETWORK_SPECIALTY_STG TO MAXDAT_LAEB_READ_ONLY;

DROP TABLE MAXDAT_LAEB.EMRS_S_NETWORK_STG CASCADE CONSTRAINTS;

CREATE TABLE MAXDAT_LAEB.EMRS_S_NETWORK_STG
	(
	  NETWORK_ID                    NUMBER (18) NOT NULL
	, PROVIDER_ID                   NUMBER (18)
	, PLAN_ID                       NUMBER (18)
	, FIRST_NAME                    VARCHAR2 (64)
	, FIRST_NAME_CANNON             VARCHAR2 (64)
	, FIRST_NAME_SOUNDLIKE          VARCHAR2 (64)
	, LAST_NAME                     VARCHAR2 (64)
	, LAST_NAME_SOUNDLIKE           VARCHAR2 (64)
	, LAST_NAME_CANNON              VARCHAR2 (64)
	, MIDDLE_NAME                   VARCHAR2 (32)
	, OFFICE_ADDR_1                 VARCHAR2 (128)
	, OFFICE_ADDR_2                 VARCHAR2 (50)
	, OFFICE_CITY                   VARCHAR2 (64)
	, OFFICE_STATE                  VARCHAR2 (2)
	, OFFICE_ZIP                    VARCHAR2 (32)
	, OFFICE_COUNTY                 VARCHAR2 (64)
	, OFFICE_PHONE                  VARCHAR2 (15)
	, OFFICE_FAX                    VARCHAR2 (15)
	, OFFICE_EMAIL                  VARCHAR2 (256)
	, AGE_LOW_LIMIT                 NUMBER (3)
	, AGE_HIGH_LIMIT                NUMBER (3)
	, MEDICAID_ID_EXT               VARCHAR2 (32)
	, WHEEL_CHAIR_ACCESSIBLE_IND    NUMBER (1)
	, PCP_IND                       NUMBER (1)
	, ACCEPTING_NEW_CLIENTS_MCO_IND NUMBER (1)
	, ACCEPTING_NEW_CLIENTS_PCP_IND NUMBER (1)
	, SEX_LIMITS_CD                 VARCHAR2 (32)
	, PROVIDER_GENDER_CD            VARCHAR2 (32)
	, CREATE_TS                     DATE
	, CREATED_BY                    VARCHAR2 (80)
	, UPDATE_TS                     DATE
	, UPDATED_BY                    VARCHAR2 (80)
	, LICENSE_NUMBER                VARCHAR2 (30)
	, START_DATE                    DATE
	, MULTIPLE_LOCATIONS_IND        NUMBER (1)
	, SITENAME                      VARCHAR2 (128)
	, SITENAME_SOUNDLIKE            VARCHAR2 (64)
	, SITENAME_CANNON               VARCHAR2 (64)
	, FQHC_STATUS_IND               NUMBER (1)
	, NETWORK_ID_EXT                VARCHAR2 (128)
	, PLAN_ID_EXT                   VARCHAR2 (128)
	, PROVIDER_ID_EXT               VARCHAR2 (128)
	, FILE_ID_EXT                   NUMBER (1)
	, STATUS_CD                     VARCHAR2 (2)
	, ACCEPTS_OBSTETRICS_IND        NUMBER (1)
	, WOMEN_ONLY_IND                NUMBER (1)
	, ADMIT_PRIVILEGES_IND          NUMBER (1)
	, DELIVERY_PRIVILEGES_IND       NUMBER (1)
	, EFFECTIVE_DT                  DATE
	, END_DT                        DATE
	, LOCATION_CD                   VARCHAR2 (1)
	, EXTERNAL_GROUP_ID             VARCHAR2 (256)
	, PROGRAM_TYPE_CD               VARCHAR2 (32)
	
	, ACCEPTING_NEW_CLIENTS_PCP_CD  VARCHAR2 (32)
	, ACCEPTING_NEW_CLIENTS_MCO_CD  VARCHAR2 (32)
	, NETWORK_GENERIC_FIELD1_DATE   DATE
	, NETWORK_GENERIC_FIELD2_DATE   DATE
	, NETWORK_GENERIC_FIELD3_NUM    NUMBER (18)
	, NETWORK_GENERIC_FIELD4_NUM    NUMBER (18)
	, NETWORK_GENERIC_FIELD5_TXT    VARCHAR2 (256)
	, NETWORK_GENERIC_FIELD6_TXT    VARCHAR2 (256)
	, NETWORK_GENERIC_FIELD7_TXT    VARCHAR2 (256)
	, NETWORK_GENERIC_FIELD8_TXT    VARCHAR2 (256)
	, NETWORK_GENERIC_FIELD9_TXT    VARCHAR2 (256)
	, NETWORK_GENERIC_FIELD10_TXT   VARCHAR2 (256)
	, NETWORK_GENERIC_REF11_ID      NUMBER (18)
	, NETWORK_GENERIC_REF12_ID      NUMBER (18)
	, RAW_ADDRESS_ID                NUMBER (18)
	, NORM_ADDRESS_ID               NUMBER (18)
	, ADDR_UPDATED_BY               VARCHAR2 (80)
	, ADDR_UPDATE_TS                DATE
	, HASH_NUM                      NUMBER (20),
	CONSTRAINT XPKSNETWORK PRIMARY KEY (NETWORK_ID)
	)
	TABLESPACE MAXDAT_LAEB_DATA
	STORAGE (BUFFER_POOL DEFAULT);

GRANT SELECT ON MAXDAT_LAEB.EMRS_S_NETWORK_STG TO MAXDAT_LAEB_READ_ONLY;

DROP TABLE MAXDAT_LAEB.EMRS_S_PANEL_LIMIT_STG CASCADE CONSTRAINTS;

CREATE TABLE MAXDAT_LAEB.EMRS_S_PANEL_LIMIT_STG
	(
	  PANEL_LIMIT_ID NUMBER (18) NOT NULL
	, NETWORK_ID     NUMBER (18)
	, PROVIDER_ID    NUMBER (18)
	, PANEL_SIZE     INTEGER
	, ENROLLED_COUNT INTEGER
	, HOLD_CD        VARCHAR2 (32)
	, CREATE_TS      DATE
	, CREATED_BY     VARCHAR2 (80)
	, UPDATE_TS      DATE
	, UPDATED_BY     VARCHAR2 (80)
	, TYPE_CD        VARCHAR2 (32)
	, PLAN_ID        NUMBER (18),
	CONSTRAINT XPKSPANEL_LIMIT PRIMARY KEY (PANEL_LIMIT_ID)
	)
	TABLESPACE MAXDAT_LAEB_DATA
	STORAGE (BUFFER_POOL DEFAULT);

GRANT SELECT ON MAXDAT_LAEB.EMRS_S_PANEL_LIMIT_STG TO MAXDAT_LAEB_READ_ONLY;

DROP TABLE MAXDAT_LAEB.EMRS_S_PROVIDER_STG CASCADE CONSTRAINTS;

CREATE TABLE MAXDAT_LAEB.EMRS_S_PROVIDER_STG
	(
	  PROVIDER_ID                  NUMBER (18) NOT NULL
	, PROVIDER_ID_EXT              VARCHAR2 (128)
	, DEA_ID_EXT                   VARCHAR2 (32)
	, NPI_ID_EXT                   VARCHAR2 (32)
	, STATUS_CD                    VARCHAR2 (32)
	, DBA_NAME                     VARCHAR2 (64)
	, TAX_NAME                     VARCHAR2 (64)
	, FIRST_NAME_CANNON            VARCHAR2 (64)
	, FIRST_NAME_SOUNDLIKE         VARCHAR2 (64)
	, TITLE                        VARCHAR2 (32)
	, FIRST_NAME                   VARCHAR2 (64)
	, LAST_NAME                    VARCHAR2 (64)
	, MIDDLE_NAME                  VARCHAR2 (64)
	, NAME_SUFFIX                  VARCHAR2 (32)
	, SSN                          VARCHAR2 (30)
	, PCP_IND                      NUMBER (1)
	, PROV_ENRL_CNT_STATE          NUMBER (9)
	, CREATE_TS                    DATE
	, CREATED_BY                   VARCHAR2 (80)
	, UPDATE_TS                    DATE
	, UPDATED_BY                   VARCHAR2 (80)
	, PHONE                        VARCHAR2 (15)
	, FAX                          VARCHAR2 (15)
	, EMAIL                        VARCHAR2 (64)
	, NPI_TYPE_CD                  VARCHAR2 (32)
	, LAST_NAME_CANNON             VARCHAR2 (64)
	, LAST_NAME_SOUNDLIKE          VARCHAR2 (32)
	, LICENSE_NUMBER               VARCHAR2 (30)
	, PROVIDER_GENDER_CD           VARCHAR2 (32)
	, OUT_OF_STATE_IND             NUMBER (1)
	, MEDICAID_IND                 NUMBER (1)
	, TYPE_CD                      VARCHAR2 (32)
	, CLASSIFICATION_CD            VARCHAR2 (32)
	, PROVIDER_GENERIC_FIELD1_DATE DATE
	, PROVIDER_GENERIC_FIELD2_DATE DATE
	, PROVIDER_GENERIC_FIELD3_NUM  NUMBER (18)
	, PROVIDER_GENERIC_FIELD4_NUM  NUMBER (18)
	, PROVIDER_GENERIC_FIELD5_TXT  VARCHAR2 (256)
	, PROVIDER_GENERIC_FIELD6_TXT  VARCHAR2 (256)
	, PROVIDER_GENERIC_FIELD7_TXT  VARCHAR2 (256)
	, PROVIDER_GENERIC_FIELD8_TXT  VARCHAR2 (256)
	, PROVIDER_GENERIC_FIELD9_TXT  VARCHAR2 (256)
	, PROVIDER_GENERIC_FIELD10_TXT VARCHAR2 (256)
	, PROVIDER_GENERIC_REF11_ID    NUMBER (18)
	, PROVIDER_GENERIC_REF12_ID    NUMBER (18),
	CONSTRAINT XPKSPROVIDER PRIMARY KEY (PROVIDER_ID)
	)
	TABLESPACE MAXDAT_LAEB_DATA
	STORAGE (BUFFER_POOL DEFAULT);

GRANT SELECT ON MAXDAT_LAEB.EMRS_S_PROVIDER_STG TO MAXDAT_LAEB_READ_ONLY;

DROP TABLE MAXDAT_LAEB.EMRS_S_SELECTION_SEGMENT_STG CASCADE CONSTRAINTS;

CREATE TABLE MAXDAT_LAEB.EMRS_S_SELECTION_SEGMENT_STG
	(
	  SELECTION_SEGMENT_ID   NUMBER (18) NOT NULL
	, CLIENT_ID              NUMBER (18)
	, PROGRAM_TYPE_CD        VARCHAR2 (32)
	, PLAN_TYPE_CD           VARCHAR2 (32)
	, START_DATE             DATE
	, END_DATE               DATE
	, STATUS_CD              VARCHAR2 (32)
	, STATUS_DATE            DATE
	, PLAN_ID                NUMBER (18)
	, PLAN_ID_EXT            VARCHAR2 (30)
	, NETWORK_ID             NUMBER (18)
	, PROVIDER_ID_EXT        VARCHAR2 (32)
	, PROVIDER_FIRST_NAME    VARCHAR2 (64)
	, PROVIDER_MIDDLE_NAME   VARCHAR2 (25)
	, PROVIDER_LAST_NAME     VARCHAR2 (64)
	, CHOICE_REASON_CD       VARCHAR2 (32)
	, DISENROLL_REASON_CD_1  VARCHAR2 (32)
	, DISENROLL_REASON_CD_2  VARCHAR2 (32)
	, CLIENT_AID_CATEGORY_CD VARCHAR2 (32)
	, COUNTY_CD              VARCHAR2 (32)
	, ZIPCODE                VARCHAR2 (32)
	, CREATED_BY             VARCHAR2 (80)
	, CREATE_TS              DATE
	, UPDATED_BY             VARCHAR2 (80)
	, UPDATE_TS              DATE
	, CONTRACT_ID            NUMBER (18)
	, START_ND               NUMBER (8)
	, END_ND                 NUMBER (8)
	, SS_GENERIC_FIELD1_DATE DATE
	, SS_GENERIC_FIELD2_DATE DATE
	, SS_GENERIC_FIELD3_NUM  NUMBER (18)
	, SS_GENERIC_FIELD4_NUM  NUMBER (22,18)
	, SS_GENERIC_FIELD5_TXT  VARCHAR2 (256)
	, SS_GENERIC_FIELD6_TXT  VARCHAR2 (256)
	, SS_GENERIC_FIELD7_TXT  VARCHAR2 (256)
	, SS_GENERIC_FIELD8_TXT  VARCHAR2 (256)
	, SS_GENERIC_FIELD9_TXT  VARCHAR2 (256)
	, SS_GENERIC_FIELD10_TXT VARCHAR2 (256),
	CONSTRAINT PK_SSELECTION_SEGMENT PRIMARY KEY (SELECTION_SEGMENT_ID)
	)
	TABLESPACE MAXDAT_LAEB_DATA
	STORAGE (BUFFER_POOL DEFAULT);

GRANT SELECT ON MAXDAT_LAEB.EMRS_S_SELECTION_SEGMENT_STG TO MAXDAT_LAEB_READ_ONLY;

DROP TABLE MAXDAT_LAEB.EMRS_S_SELECTION_TXN_STG CASCADE CONSTRAINTS;

CREATE TABLE MAXDAT_LAEB.EMRS_S_SELECTION_TXN_STG
	(
	  SELECTION_TXN_ID              NUMBER (18) NOT NULL
	, SELECTION_TXN_GROUP_ID        NUMBER (18)
	, PROGRAM_TYPE_CD               VARCHAR2 (32)
	, TRANSACTION_TYPE_CD           VARCHAR2 (32)
	, SELECTION_SOURCE_CD           VARCHAR2 (32)
	, REF_SOURCE_ID                 NUMBER (18)
	, REF_SOURCE_TYPE               VARCHAR2 (32)
	, REF_EXT_TXN_ID                VARCHAR2 (80)
	, PLAN_TYPE_CD                  VARCHAR2 (32)
	, PLAN_ID                       NUMBER (18)
	, PLAN_ID_EXT                   VARCHAR2 (30)
	, CONTRACT_ID                   NUMBER (18)
	, NETWORK_ID                    NUMBER (18)
	, PROVIDER_ID                   NUMBER (18)
	, PROVIDER_ID_EXT               VARCHAR2 (32)
	, PROVIDER_FIRST_NAME           VARCHAR2 (64)
	, PROVIDER_MIDDLE_NAME          VARCHAR2 (25)
	, PROVIDER_LAST_NAME            VARCHAR2 (64)
	, START_DATE                    DATE
	, END_DATE                      DATE
	, CHOICE_REASON_CD              VARCHAR2 (32)
	, DISENROLL_REASON_CD_1         VARCHAR2 (32)
	, DISENROLL_REASON_CD_2         VARCHAR2 (32)
	, OVERRIDE_REASON_CD            VARCHAR2 (32)
	, FOLLOWUP_REASON_CD            VARCHAR2 (32)
	, FOLLOWUP_CALL_DATE            DATE
	, FOLLOWUP_FORM_RCV_DATE        DATE
	, FOLLOWUP_BY                   VARCHAR2 (80)
	, MISSING_INFO_ID               NUMBER (18)
	, MISSING_SIGNATURE_IND         NUMBER (1)
	, OUTREACH_SESSION_ID           NUMBER (18)
	, BENEFITS_PACKAGE_CD           VARCHAR2 (32)
	, SELECTION_SEGMENT_ID          NUMBER (18)
	, CLIENT_ID                     NUMBER (18)
	, STATUS_CD                     VARCHAR2 (32)
	, STATUS_DATE                   DATE
	, CLIENT_AID_CATEGORY_CD        VARCHAR2 (32)
	, COUNTY                        VARCHAR2 (32)
	, ZIPCODE                       VARCHAR2 (32)
	, CLIENT_RESIDENCE_ADDRESS_ID   NUMBER (18)
	, PRIOR_SELECTION_SEGMENT_ID    NUMBER (18)
	, PRIOR_SELECTION_START_DATE    DATE
	, PRIOR_SELECTION_END_DATE      DATE
	, PRIOR_PLAN_ID                 NUMBER (18)
	, PRIOR_PLAN_ID_EXT             VARCHAR2 (32)
	, PRIOR_PROVIDER_ID             NUMBER (18)
	, PRIOR_PROVIDER_ID_EXT         VARCHAR2 (32)
	, PRIOR_PROVIDER_FIRST_NAME     VARCHAR2 (25)
	, PRIOR_PROVIDER_MIDDLE_NAME    VARCHAR2 (25)
	, PRIOR_PROVIDER_LAST_NAME      VARCHAR2 (35)
	, REF_SELECTION_TXN_ID          NUMBER (18)
	, SURPLUS_INFO                  NUMBER (10,2)
	, CREATED_BY                    VARCHAR2 (80)
	, CREATE_TS                     DATE
	, UPDATED_BY                    VARCHAR2 (80)
	, UPDATE_TS                     DATE
	, PRIOR_CONTRACT_ID             NUMBER (18)
	, PRIOR_NETWORK_ID              NUMBER (18)
	, START_ND                      NUMBER (8)
	, END_ND                        NUMBER (8)
	, PRIOR_CHOICE_REASON_CD        VARCHAR2 (32)
	, PRIOR_DISENROLL_REASON_CD_1   VARCHAR2 (32)
	, PRIOR_DISENROLL_REASON_CD_2   VARCHAR2 (32)
	, PRIOR_CLIENT_AID_CATEGORY_CD  VARCHAR2 (32)
	, PRIOR_COUNTY_CD               VARCHAR2 (32)
	, PRIOR_ZIPCODE                 VARCHAR2 (32)
	, ORIGINAL_START_DATE           DATE
	, ORIGINAL_END_DATE             DATE
	, SELECTION_GENERIC_FIELD1_DATE DATE
	, SELECTION_GENERIC_FIELD2_DATE DATE
	, SELECTION_GENERIC_FIELD3_NUM  NUMBER (18)
	, SELECTION_GENERIC_FIELD4_NUM  NUMBER (18)
	, SELECTION_GENERIC_FIELD5_TXT  VARCHAR2 (256)
	, SELECTION_GENERIC_FIELD6_TXT  VARCHAR2 (256)
	, SELECTION_GENERIC_FIELD7_TXT  VARCHAR2 (256)
	, SELECTION_GENERIC_FIELD8_TXT  VARCHAR2 (256)
	, SELECTION_GENERIC_FIELD9_TXT  VARCHAR2 (256)
	, SELECTION_GENERIC_FIELD10_TXT VARCHAR2 (256),
	CONSTRAINT PK_SSELECTION_TXN PRIMARY KEY (SELECTION_TXN_ID)
	)
	TABLESPACE MAXDAT_LAEB_DATA
	STORAGE (BUFFER_POOL DEFAULT);

GRANT SELECT ON MAXDAT_LAEB.EMRS_S_SELECTION_TXN_STG TO MAXDAT_LAEB_READ_ONLY;

DROP TABLE MAXDAT_LAEB.EMRS_S_SELECTN_MISSING_INFO_STG CASCADE CONSTRAINTS;

CREATE TABLE MAXDAT_LAEB.EMRS_S_SELECTN_MISSING_INFO_STG
	(
	  MISSING_INFO_ID      NUMBER (18) NOT NULL
	, COMMENTS             VARCHAR2 (4000)
	, COMMENTS_FOR_CLIENT  VARCHAR2 (4000)
	, CREATE_TS            DATE
	, CREATED_BY           VARCHAR2 (80)
	, UPDATE_TS            DATE
	, UPDATED_BY           VARCHAR2 (80)
	, MISSING_INFO_TYPE_CD VARCHAR2 (32),
	CONSTRAINT XPKSSELECTION_MISSING_INFO PRIMARY KEY (MISSING_INFO_ID)
	)
	TABLESPACE MAXDAT_LAEB_DATA
	STORAGE (BUFFER_POOL DEFAULT);

GRANT SELECT ON MAXDAT_LAEB.EMRS_S_SELECTN_MISSING_INFO_STG TO MAXDAT_LAEB_READ_ONLY;

DROP TABLE MAXDAT_LAEB.EMRS_S_SELTN_MISNG_INFO_DETL_STG CASCADE CONSTRAINTS;

CREATE TABLE MAXDAT_LAEB.EMRS_S_SELTN_MISNG_INFO_DETL_STG
	(
	  MISSING_INFO_DETAILS_ID NUMBER (18) NOT NULL
	, MISSING_INFO_ID         NUMBER (18)
	, ERROR_CODE              VARCHAR2 (32)
	, CLIENT_ID               NUMBER (18)
	, SEND_IN_LETTER_IND      NUMBER (1)
	
	, ADDITIONAL_MESSAGE_IND  NUMBER (1)
	
	, CREATE_TS               DATE
	, CREATED_BY              VARCHAR2 (80)
	, UPDATE_TS               DATE
	, UPDATED_BY              VARCHAR2 (80)
	, COMMENTS                VARCHAR2 (4000)
	, DENIAL_ERROR_CD         VARCHAR2 (32)
	, SUPPLEMENTAL_INFO       VARCHAR2 (256),
	CONSTRAINT XPKSSEL_MISSING_INFO_DETAILS PRIMARY KEY (MISSING_INFO_DETAILS_ID)
	)
	TABLESPACE MAXDAT_LAEB_DATA
	STORAGE (BUFFER_POOL DEFAULT);

GRANT SELECT ON MAXDAT_LAEB.EMRS_S_SELTN_MISNG_INFO_DETL_STG TO MAXDAT_LAEB_READ_ONLY;

DROP TABLE MAXDAT_LAEB.EMRS_S_SELECTN_TXN_STAT_HIST_STG CASCADE CONSTRAINTS;

CREATE TABLE MAXDAT_LAEB.EMRS_S_SELECTN_TXN_STAT_HIST_STG
	(
	  SELECTION_TXN_STATUS_HIST_ID NUMBER (18) NOT NULL
	, SELECTION_TXN_ID             NUMBER (18)
	, STATUS_CD                    VARCHAR2 (32)
	, CREATED_BY                   VARCHAR2 (80)
	, CREATE_TS                    DATE,
	CONSTRAINT PK_SSELECTION_TXN_STATUS_HISTOR PRIMARY KEY (SELECTION_TXN_STATUS_HIST_ID)
	)
	TABLESPACE MAXDAT_LAEB_DATA
	STORAGE (BUFFER_POOL DEFAULT);
  
GRANT SELECT ON MAXDAT_LAEB.EMRS_S_SELECTN_TXN_STAT_HIST_STG TO MAXDAT_LAEB_READ_ONLY;