CREATE SEQUENCE  "EMRS_SEQ_PHONE_TYPE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1061 CACHE 20 NOORDER  NOCYCLE ;

GRANT SELECT ON "EMRS_SEQ_PHONE_TYPE_ID" TO &role_name;

CREATE TABLE EMRS_D_PHONE_TYPE
   (PHONE_TYPE_ID NUMBER NOT NULL, 
    PHONE_TYPE_CODE VARCHAR2(32),
    PHONE_TYPE VARCHAR2(240)    
	  ) TABLESPACE &tablespace_name ;

 ALTER TABLE "EMRS_D_PHONE_TYPE" ADD CONSTRAINT "PHONETYPE_COMB_UK" UNIQUE ("PHONE_TYPE_CODE") USING INDEX  TABLESPACE &tablespace_name  ENABLE;
 ALTER TABLE "EMRS_D_PHONE_TYPE" ADD CONSTRAINT "PHONETYPEPK" PRIMARY KEY ("PHONE_TYPE_ID") USING INDEX TABLESPACE &tablespace_name  ENABLE;
  
GRANT SELECT ON "EMRS_D_PHONE_TYPE" TO &role_name;

CREATE OR REPLACE TRIGGER "BIR_PHONE_TYPE" 
 BEFORE INSERT
 ON emrs_d_phone_type
 FOR EACH ROW
DECLARE
    v_seq_id     EMRS_D_PHONE_TYPE.phone_type_id%TYPE;
BEGIN
  IF :NEW.phone_type_id IS NULL THEN
    SElECT EMRS_SEQ_PHONE_TYPE_ID.NEXTVAL
    INTO v_seq_id
    FROM dual;

    :NEW.phone_type_id       := v_seq_id;
  END IF;
END BIR_PHONE_TYPE;
/
ALTER TRIGGER "BIR_PHONE_TYPE" ENABLE;
/

CREATE OR REPLACE VIEW EMRS_D_PHONE_TYPE_SV
AS
SELECT phone_type_code phon_type_cd
       ,phone_type
FROM emrs_d_phone_type;

GRANT SELECT ON "EMRS_D_PHONE_TYPE_SV" TO &role_name;
