CREATE SEQUENCE  "EMRS_SEQ_OVERRIDE_RSN_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1061 CACHE 20 NOORDER  NOCYCLE ;

GRANT SELECT ON "EMRS_SEQ_OVERRIDE_RSN_ID" TO &role_name;

CREATE TABLE EMRS_D_OVERRIDE_REASONS
   (OVERRIDE_REASON_ID NUMBER NOT NULL, 
    OVERRIDE_REASON_CODE VARCHAR2(32),
    OVERRIDE_REASON VARCHAR2(240)    
	  ) TABLESPACE &tablespace_name ;

 ALTER TABLE "EMRS_D_OVERRIDE_REASONS" ADD CONSTRAINT "OVERRIDERSN_COMB_UK" UNIQUE ("OVERRIDE_REASON_CODE") USING INDEX  TABLESPACE &tablespace_name  ENABLE;
 ALTER TABLE "EMRS_D_OVERRIDE_REASONS" ADD CONSTRAINT "OVERRIDERSNPK" PRIMARY KEY ("OVERRIDE_REASON_ID") USING INDEX TABLESPACE &tablespace_name  ENABLE;
  
GRANT SELECT ON "EMRS_D_OVERRIDE_REASONS" TO &role_name;

CREATE OR REPLACE TRIGGER "BIR_OVERRIDE_RSN" 
 BEFORE INSERT
 ON emrs_d_override_reasons
 FOR EACH ROW
DECLARE
    v_seq_id     EMRS_D_OVERRIDE_REASONS.override_reason_id%TYPE;
BEGIN
  IF :NEW.override_reason_id IS NULL THEN
    SElECT EMRS_SEQ_OVERRIDE_RSN_ID.NEXTVAL
    INTO v_seq_id
    FROM dual;

    :NEW.override_reason_id       := v_seq_id;
  END IF;
END BIR_OVERRIDE_RSN;
/
ALTER TRIGGER "BIR_OVERRIDE_RSN" ENABLE;
/

CREATE OR REPLACE VIEW EMRS_D_OVERRIDE_REASONS_SV
AS
SELECT override_reason_code override_reason_cd
       ,override_reason
FROM emrs_d_override_reasons;

GRANT SELECT ON "EMRS_D_OVERRIDE_REASONS_SV" TO &role_name;
