CREATE SEQUENCE  "EMRS_SEQ_CLIENT_TYPE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1061 CACHE 20 NOORDER  NOCYCLE ;

GRANT SELECT ON "EMRS_SEQ_CLIENT_TYPE_ID" TO &role_name;

CREATE TABLE EMRS_D_CLIENT_TYPE
   (CLIENT_TYPE_ID NUMBER NOT NULL, 
    CLIENT_TYPE_CODE VARCHAR2(32),
    CLIENT_TYPE VARCHAR2(240)  
	  ) TABLESPACE &tablespace_name ;

 ALTER TABLE "EMRS_D_CLIENT_TYPE" ADD CONSTRAINT "CLIENTTYPE_COMB_UK" UNIQUE ("CLIENT_TYPE_CODE") USING INDEX  TABLESPACE &tablespace_name  ENABLE;
 ALTER TABLE "EMRS_D_CLIENT_TYPE" ADD CONSTRAINT "CLIENTTYPEPK" PRIMARY KEY ("CLIENT_TYPE_ID") USING INDEX TABLESPACE &tablespace_name  ENABLE;
  
GRANT SELECT ON "EMRS_D_CLIENT_TYPE" TO &role_name;

CREATE OR REPLACE TRIGGER "BIR_CLIENT_TYPE" 
 BEFORE INSERT
 ON emrs_d_client_type
 FOR EACH ROW
DECLARE
    v_seq_id     EMRS_D_CLIENT_TYPE.client_type_id%TYPE;
BEGIN
  IF :NEW.client_type_id IS NULL THEN
    SElECT EMRS_SEQ_CLIENT_TYPE_ID.NEXTVAL
    INTO v_seq_id
    FROM dual;

    :NEW.client_type_id       := v_seq_id;
  END IF;
END BIR_CLIENT_TYPE;
/
ALTER TRIGGER "BIR_CLIENT_TYPE" ENABLE;
/

CREATE OR REPLACE VIEW EMRS_D_CLIENT_TYPE_SV
AS
SELECT client_type_code client_type_cd
       ,client_type
FROM emrs_d_client_type;

GRANT SELECT ON "EMRS_D_CLIENT_TYPE_SV" TO &role_name;
