-- Unknown Values

INSERT INTO EMRS_D_ADDRESS_TYPE (ADDRESS_TYPE_ID,ADDRESS_TYPE_CODE,ADDRESS_TYPE )
SELECT 
    0 
    ,'UD'
    , 'Undefined'  
FROM EMRS_D_ADDRESS_TYPE
WHERE ADDRESS_TYPE_CODE = 'UD'
HAVING count(*) = 0;


INSERT INTO EMRS_D_BENEFITS_PACKAGE (BENEFITS_PACKAGE_ID,BENEFITS_PACKAGE_CODE,BENEFITS_PACKAGE )
SELECT 0
     ,'0'
    , 'Not Defined'  
FROM EMRS_D_BENEFITS_PACKAGE
WHERE BENEFITS_PACKAGE_CODE = '0'
HAVING count(*) = 0;


INSERT INTO EMRS_D_CARE_SERV_DELIV_AREA (CSDA_ID,CSDA_CODE,CSDA_NAME,REGION_ID,STATUS,EFFECTIVE_START_DATE,EFFECTIVE_END_DATE )
SELECT 0 CSDA_ID,
    '-1' AS CSDA_CODE ,
    'Not Defined' AS CSDA_NAME ,
    -1 AS REGION_ID,
    'A' AS STATUS ,
    to_date('01/01/1900', 'mm/dd/yyyy')AS EFFECTIVE_START_DATE,
    NULL AS EFFECTIVE_END_DATE
    FROM EMRS_D_CARE_SERV_DELIV_AREA
WHERE CSDA_CODE = '-1'
HAVING count(*) = 0;

INSERT INTO EMRS_D_CASE_STATUS(CASE_STATUS_ID, CASE_STATUS_CODE,CASE_STATUS )
SELECT 0,
     '0'
    , 'Not Defined'  
FROM EMRS_D_CASE_STATUS
WHERE CASE_STATUS_CODE = '0'
HAVING count(*) = 0;

INSERT INTO EMRS_D_CHANGE_REASON(CHANGE_REASON_ID,CHANGE_REASON_CODE,CHANGE_REASON,CHANGE_REASON_CODE_PLAN)    
SELECT 0,
    '0' CHANGE_REASON_CODE ,
    'Not Defined' CHANGE_REASON ,
    NULL CHANGE_REASON_CODE_PLAN
FROM EMRS_D_CHANGE_REASON
WHERE CHANGE_REASON_CODE = '0'
HAVING count(*) = 0;


INSERT INTO EMRS_D_CHANNEL(CHANNEL_CODE,CHANNEL)
VALUES('Phone','Phone');

INSERT INTO EMRS_D_CHANNEL(CHANNEL_CODE,CHANNEL)
VALUES('IVR','IVR');   

INSERT INTO EMRS_D_CHANNEL(CHANNEL_CODE,CHANNEL)
VALUES('Web','Web');

INSERT INTO EMRS_D_CHANNEL(CHANNEL_CODE,CHANNEL)
VALUES('Mobile','Mobile');

INSERT INTO EMRS_D_CHANNEL(CHANNEL_CODE,CHANNEL)
VALUES('MailFax','Mail/Fax');

INSERT INTO EMRS_D_CHANNEL(CHANNEL_CODE,CHANNEL)
VALUES('Reinstatement','Reinstatement');

INSERT INTO EMRS_D_CHANNEL(CHANNEL_CODE,CHANNEL)
VALUES('Newborn','Newborn');

INSERT INTO EMRS_D_CHANNEL(CHANNEL_CODE,CHANNEL)
VALUES('DEFile','DE File');

INSERT INTO EMRS_D_CHANNEL(CHANNEL_CODE,CHANNEL)
VALUES('AutoEnrollments','Auto Enrollments');


INSERT INTO EMRS_D_CITIZENSHIP_STATUS(CITIZENSHIP_STATUS_ID, CITIZENSHIP_STATUS_CODE,CITIZENSHIP_STATUS)
SELECT 0
     ,'0'
    , 'Not Defined'  
FROM EMRS_D_CITIZENSHIP_STATUS
WHERE CITIZENSHIP_STATUS_CODE = '0'
HAVING count(*) = 0;

INSERT INTO EMRS_D_CATEGORY_OF_ASSISTANCE(COA_ID, COA_CODE,COA_DESCRIPTION)
SELECT 0,
    '0' ,
    'Not Defined' 
  FROM EMRS_D_CATEGORY_OF_ASSISTANCE
  WHERE COA_CODE = '0'
HAVING count(*) = 0;

INSERT INTO EMRS_D_COUNTY(COUNTY_ID,COUNTY_CODE,COUNTY_NAME,COUNTY_FIPS_CODE,DISTRICT_ID,STATE,STATUS,MODIFIED_DATE,MODIFIED_TIME,MODIFIED_NAME)
SELECT 0,
    '0' AS COUNTY_CODE ,
    'UNKNOWN' AS COUNTY_NAME ,
    NULL AS COUNTY_FIPS_CODE ,
    '-1' AS DISTRICT_ID ,
    'NA' AS STATE ,
    NULL AS STATUS ,
    NULL AS MODIFIED_DATE ,
    NULL AS MODIFIED_TIME ,
    NULL AS MODIFIED_NAME 
FROM EMRS_D_COUNTY
  WHERE COUNTY_CODE = '0'
HAVING count(*) = 0;

INSERT INTO EMRS_D_ELIGIBILITY_STATUS(ELIGIBILITY_STATUS_ID,ELIGIBILITY_STATUS_CODE,ELIGIBILITY_STATUS )
SELECT 0,
    '0' ,
    'Not Defined' 
  FROM EMRS_D_ELIGIBILITY_STATUS
  WHERE ELIGIBILITY_STATUS_CODE = '0'
HAVING count(*) = 0;


INSERT INTO EMRS_D_ENROLL_TRANS_TYPE(ENROLLMENT_TRANS_TYPE_CODE, ENROLLMENT_TRANS_TYPE )
SELECT 
    'AutoTransfer' AS ENROLLMENT_TRANS_TYPE_CODE
    ,'Auto Transfer' AS ENROLLMENT_TRANS_TYPE
FROM EMRS_D_ENROLL_TRANS_TYPE
WHERE ENROLLMENT_TRANS_TYPE_CODE = 'AutoTransfer'
HAVING count(*) = 0;

INSERT INTO EMRS_D_ENROLL_TRANS_TYPE(ENROLLMENT_TRANS_TYPE_ID,ENROLLMENT_TRANS_TYPE_CODE, ENROLLMENT_TRANS_TYPE )
SELECT 0,
    'NotDefined' AS ENROLLMENT_TRANS_TYPE_CODE
    ,'Not Defined' AS ENROLLMENT_TRANS_TYPE
FROM EMRS_D_ENROLL_TRANS_TYPE
WHERE ENROLLMENT_TRANS_TYPE_CODE = 'NotDefined'
HAVING count(*) = 0;

INSERT INTO EMRS_D_ENROLLMENT_TYPE(ENROLLMENT_TYPE_ID,ENROLLMENT_TYPE_CODE, ENROLLMENT_TYPE,ORDER_BY_DEFAULT)
SELECT 0,
'NotDefined' AS ENROLLMENT_TYPE_CODE
    ,'Not Defined' AS ENROLLMENT_TYPE
    , 50 ORDER_BY_DEFAULT
FROM EMRS_D_ENROLLMENT_TYPE
WHERE ENROLLMENT_TYPE_CODE = 'NotDefined'
HAVING count(*) = 0;

INSERT INTO EMRS_D_ENROLLMENT_ERROR_CODE(ENROLLMENT_ERROR_ID,ENROLLMENT_ERROR_CODE,ENROLLMENT_ERROR)
SELECT 0,
'0' AS ENROLLMENT_ERROR_CODE
    ,'Not Defined' AS ENROLLMENT_ERROR    
FROM EMRS_D_ENROLLMENT_ERROR_CODE
WHERE ENROLLMENT_ERROR_CODE = '0'
HAVING count(*) = 0;

INSERT INTO EMRS_D_MI_TYPE(MI_TYPE_ID, MI_TYPE_CODE,MI_TYPE)
 SELECT 0,
    '0',
    'Not Defined' 
FROM EMRS_D_MI_TYPE
WHERE MI_TYPE_CODE = '0'
HAVING count(*) = 0;

INSERT INTO EMRS_D_OVERRIDE_REASONS(OVERRIDE_REASON_ID,OVERRIDE_REASON_CODE,OVERRIDE_REASON)
 SELECT 0,
    '0',
    'Not Defined' 
FROM EMRS_D_OVERRIDE_REASONS
WHERE OVERRIDE_REASON_CODE = '0'
HAVING count(*) = 0;

INSERT INTO EMRS_D_PHONE_TYPE (PHONE_TYPE_ID,PHONE_TYPE_CODE,PHONE_TYPE )
SELECT 0,
     'UD'
    , 'Undefined'  
FROM EMRS_D_PHONE_TYPE
WHERE PHONE_TYPE_CODE = 'UD'
HAVING count(*) = 0;

INSERT INTO EMRS_D_PLAN_SERVICE_TYPE (PLAN_SERVICE_TYPE_ID,PLAN_SERVICE_TYPE_CODE,PLAN_SERVICE_TYPE  )
SELECT 0,
     'UD'
    , 'Undefined'  
FROM EMRS_D_PLAN_SERVICE_TYPE
WHERE PLAN_SERVICE_TYPE_CODE = 'UD'
HAVING count(*) = 0;

INSERT INTO EMRS_D_PLAN
   (DP_PLAN_ID,
    PLAN_ID,
    PLAN_CODE,
    PLAN_ID_EXT,
    PLAN_NAME,
    PLAN_ABBREVIATION,
    MANAGED_CARE_PROGRAM,
    PLAN_SERVICE_TYPE_CD,
    PLAN_EFFECTIVE_DATE,
    CONTACT_FIRST_NAME,
    CONTACT_MIDDLE_NAME,
    CONTACT_LAST_NAME,
    CONTACT_FULL_NAME,
    ADDRESS1,
    ADDRESS2,
    CITY,
    STATE,
    ZIP,
    CONTACT_PHONE,
    ACTIVE,
    ENROLLOK,
    PLAN_ASSIGN,
    PLAN_TYPE,
    RECORD_DATE,
    RECORD_TIME,
    RECORD_NAME  ) 
  SELECT 0,
     0 AS PLAN_ID,
    '0' AS PLAN_CODE,
    '0' AS PLAN_ID_EXT,
    'No Plan' AS PLAN_NAME,
    'No Plan' AS PLAN_ABBREVIATION,
    'MEDICAID' AS MANAGED_CARE_PROGRAM,
    'UD' AS PLAN_SERVICE_TYPE_CD,
    TO_DATE('01/01/1900','MM/DD/YYYY') AS PLAN_EFFECTIVE_DATE,
    NULL AS CONTACT_FIRST_NAME,
    NULL AS CONTACT_MIDDLE_NAME,
    NULL AS CONTACT_LAST_NAME,
    NULL AS CONTACT_FULL_NAME,
    NULL AS ADDRESS1,
    NULL AS ADDRESS2,
    NULL AS CITY,
    NULL AS STATE,
    NULL AS ZIP,
    NULL AS CONTACT_PHONE, 
     'N' AS ACTIVE,
    'N' AS ENROLLOK,
    'N' AS PLAN_ASSIGN,
    '0' AS PLAN_TYPE,
    NULL AS RECORD_DATE,
    NULL AS RECORD_TIME,
    NULL AS RECORD_NAME
FROM EMRS_D_PLAN
WHERE PLAN_CODE = '0'
HAVING COUNT(*) = 0;

INSERT INTO EMRS_D_PLAN_TYPE (PLAN_TYPE_ID, PLAN_TYPE,PLAN_TYPE_DESC  )
SELECT 0,
     '0'
    , 'Not Defined'  
FROM EMRS_D_PLAN_TYPE
WHERE PLAN_TYPE = '0'
HAVING count(*) = 0;

INSERT INTO EMRS_D_PROGRAM (PROGRAM_ID,
   PROGRAM_CODE, 
   PROGRAM_NAME, 
   PROGRAM_DESCRIPTION,
   PROGRAM_CATEGORY, 	  
   ACTIVE_INACTIVE ,
   START_DATE, 
   END_DATE    )
 SELECT 0,
    '0' AS program_code ,
    'Not Defined' AS program_name ,
    'Not Defined' AS program_description,
    'Not Defined' AS program_category,
    'A' AS active_inactive , 
    TO_DATE('01/01/1900','MM/DD/YYYY') AS start_date,
    NULL AS end_date 
FROM EMRS_D_PROGRAM
WHERE PROGRAM_CODE = '0'
HAVING count(*) = 0;

INSERT INTO EMRS_D_PROVIDER_SPECIALTY_CODE(PROVIDER_SPECIALTY_ID,PROVIDER_SPECIALTY_CODE, PROVIDER_SPECIALTY,EFFECTIVE_START_DATE, EFFECTIVE_END_DATE)
SELECT 0,
      'UD' PROVIDER_SPECIALTY_CODE ,
      'Undefined' PROVIDER_SPECIALTY ,
      TO_DATE('01/01/1900', 'mm\dd\yyyy') AS EFFECTIVE_START_DATE,
      NULL AS EFFECTIVE_END_DATE
FROM  EMRS_D_PROVIDER_SPECIALTY_CODE
WHERE PROVIDER_SPECIALTY_CODE = 'UD'
HAVING count(*) = 0;

INSERT INTO EMRS_D_PROVIDER_TYPE(PROVIDER_TYPE_ID,PROVIDER_TYPE_CODE,PROVIDER_TYPE_NAME,EFFECTIVE_START_DATE,EFFECTIVE_END_DATE)	 
 SELECT 0,
     '0' AS PROVIDER_TYPE_CODE,
    'Not Defined' AS PROVIDER_TYPE_NAME,
    TO_DATE('01/01/1900','mm/dd/yyyy') AS EFFECTIVE_START_DATE,
    NULL AS EFFECTIVE_END_DATE     
FROM EMRS_D_PROVIDER_TYPE
WHERE PROVIDER_TYPE_CODE = '0'
HAVING COUNT(*) = 0;

INSERT INTO EMRS_D_REGION(REGION_CODE,REGION_NAME)
VALUES('1','Capital');

INSERT INTO EMRS_D_REGION(REGION_CODE,REGION_NAME)
VALUES('2','Gulf');

INSERT INTO EMRS_D_REGION(REGION_CODE,REGION_NAME)
VALUES('3','North');

INSERT INTO EMRS_D_REGION(REGION_CODE,REGION_NAME)
VALUES('4','South Central');

INSERT INTO EMRS_D_REGION(REGION_ID,REGION_CODE,REGION_NAME)
VALUES(0,'-1','Unknown');

INSERT INTO EMRS_D_RELATIONSHIP (RELATIONSHIP_ID,RELATIONSHIP_CODE,RELATIONSHIP )
SELECT 0
    , '0'
    , 'Not Defined'  
FROM EMRS_D_RELATIONSHIP
WHERE RELATIONSHIP_CODE = '0'
HAVING count(*) = 0;

INSERT INTO EMRS_D_SELECTION_REASON  (SELECTION_REASON_ID,SELECTION_REASON_CODE, SELECTION_REASON  )
SELECT
    0,
   '0' AS SELECTION_REASON_CODE ,
    'Not Defined' AS SELECTION_REASON 
FROM EMRS_D_SELECTION_REASON
WHERE SELECTION_REASON_CODE = '0'
HAVING count(*) = 0;

INSERT INTO EMRS_D_SELECTION_SOURCE
    (
    SELECTION_SOURCE_ID
    , SELECTION_SOURCE_CODE
    , SELECTION_SOURCE
    , IS_CHOICE_IND
    )
SELECT
    0,
   '0' AS SELECTION_SOURCE_CODE ,
    'State Assigned' AS SELECTION_SOURCE,
    'N' AS IS_CHOICE_IND   
FROM EMRS_D_SELECTION_SOURCE
WHERE SELECTION_SOURCE_CODE = '0'
HAVING count(*) = 0;

INSERT INTO EMRS_D_SELECTION_STATUS
    ( SELECTION_STATUS_ID, 
   SELECTION_STATUS_CODE, 
   SELECTION_STATUS_DESCRIPTION, 	
   OVERWRITE_IND,
   OVERWRITE_TO_VALUE,
   VALID_SELECTION_IND,
   ALLOW_NEW_SELECTION_IND  )
SELECT
    0 SELECTION_STATUS_ID,
  '0' AS SELECTION_STATUS_CODE,
    'Not Defined' AS SELECTION_STATUS_DESCRIPTION,
    0 AS OVERWRITE_IND,
    NULL AS OVERWRITE_TO_VALUE,    
    0 AS VALID_SELECTION_IND,
    0 AS ALLOW_NEW_SELECTION_IND 
FROM EMRS_D_SELECTION_STATUS
WHERE SELECTION_STATUS_CODE = '0'
HAVING count(*) = 0;

INSERT INTO EMRS_D_SUB_PROGRAM
    (SUB_PROGRAM_ID, 
   SUB_PROGRAM_CODE, 	
   SUB_PROGRAM_NAME, 	 
   PARENT_PROGRAM_NAME, 
   START_DATE,
   END_DATE,
   PLAN_SERVICE_TYPE )
SELECT
    0,
   'UD' AS SUBPROGRAM_CODE,
    'Not Defined' AS SUBPROGRAM_NAME,
    'MEDICAID' AS PARENT_PROGRAM_NAME,
    TO_DATE('01/01/1900','MM/DD/YYYY') AS START_DATE,
    NULL AS END_DATE,    
    NULL AS PLAN_SERVICE_TYPE
FROM EMRS_D_SUB_PROGRAM
WHERE SUB_PROGRAM_CODE = 'UD'
HAVING count(*) = 0;

INSERT INTO EMRS_D_SUBPROGRAM_CATEGORY(SUBPROGRAM_CATEGORY_CODE,SUBPROGRAM_CATEGORY)
VALUES('GROUP_1','Acute and Behavioral Health');

INSERT INTO EMRS_D_SUBPROGRAM_CATEGORY(SUBPROGRAM_CATEGORY_CODE,SUBPROGRAM_CATEGORY)
VALUES('GROUP_2','Behavioral Health Only');

INSERT INTO EMRS_D_SUBPROGRAM_CATEGORY(SUBPROGRAM_CATEGORY_CODE,SUBPROGRAM_CATEGORY)
VALUES('GROUP_3','HCBS and Chisholm – Acute and Behavioral Health');

INSERT INTO EMRS_D_SUBPROGRAM_CATEGORY(SUBPROGRAM_CATEGORY_CODE,SUBPROGRAM_CATEGORY)
VALUES('GROUP_4','HCBS and Chisholm – Behavioral Health Only');

INSERT INTO EMRS_D_SUBPROGRAM_CATEGORY(SUBPROGRAM_CATEGORY_ID,SUBPROGRAM_CATEGORY_CODE,SUBPROGRAM_CATEGORY)
VALUES(0,'UD','Not Defined');

INSERT INTO EMRS_D_TERMINATION_REASON  (TERM_REASON_CODE_ID,REASON_CODE, REASON  )
SELECT
    0,
   '0' AS REASON_CODE ,
    'Not Defined' AS REASON 
FROM EMRS_D_TERMINATION_REASON
WHERE REASON_CODE = '0'
HAVING count(*) = 0;

INSERT INTO EMRS_D_ZIPCODE(ZIPCODE_ID, 
   ZIP_CODE, 
   ZIP_CITY, 	
   ZIP_COUNTY,
   ZIP_STATE,
   COVERS_MULTIPLE_COUNTY)
SELECT 0 AS ZIPCODE_ID,
    '0' AS ZIP_CODE,
    'Unknown' AS ZIP_CITY,
    '0' AS ZIP_COUNTY,
    'NA' AS ZIP_STATE,
    'N' AS COVERS_MULTIPLE_COUNTY
FROM EMRS_D_ZIPCODE
WHERE ZIP_CODE = '0'
HAVING COUNT(*) = 0;

COMMIT;   
   