*** NYEC***
*** Drop backup table***;


alter session set current_schema = MAXDAT;

Drop table MAXDAT.BPM_CIN_SNAPSHOT_BKUP;
Drop table MAXDAT.BPM_CIN_SNAPSHOT_20140623;

TRUNCATE table MAXDAT.BPM_UPDATE_EVENT_BACKUP;
TRUNCATE table MAXDAT.BPM_UPDATE_EVENT_RETIRE;
TRUNCATE table MAXDAT.BPM_INSTANCE_ATTRIBUTE_RETIRE ;

***CORP_ETL_ERROR_LOG     -delete everything over 6 months -quaterly schedule.

  CREATE TABLE MAXDAT.CORP_ETL_ERROR_LOG_TEMP AS 
SELECT * FROM MAXDAT.CORP_ETL_ERROR_LOG WHERE CREATE_TS  > TRUNC(SYSDATE-180);
TRUNCATE TABLE MAXDAT.CORP_ETL_ERROR_LOG ;

Commit;

INSERT INTO MAXDAT.CORP_ETL_ERROR_LOG
SELECT * FROM MAXDAT.CORP_ETL_ERROR_LOG_TEMP ;
DROP TABLE MAXDAT.CORP_ETL_ERROR_LOG_TEMP ;

Commit;


CREATE TABLE MAXDAT.BPM_UPDATE_EVENT_QUEUE_ARCHIVE_TEMP AS
SELECT * FROM MAXDAT.BPM_UPDATE_EVENT_QUEUE_ARCHIVE WHERE EVENT_DATE  > TRUNC(SYSDATE-180);
TRUNCATE TABLE MAXDAT.BPM_UPDATE_EVENT_QUEUE_ARCHIVE ;

INSERT INTO MAXDAT.BPM_UPDATE_EVENT_QUEUE_ARCHIVE
SELECT * FROM MAXDAT.BPM_UPDATE_EVENT_QUEUE_ARCHIVE_TEMP;

DROP TABLE MAXDAT.BPM_UPDATE_EVENT_QUEUE_ARCHIVE_TEMP;

Commit;

