CREATE OR REPLACE VIEW EMRS_D_PHONE_SV
AS
SELECT PHON_ID PHONE_ID
,PHON_BEGIN_DATE SOURCE_PHONE_BEGIN_DATE
,PHON_TYPE_CD
,PT.REPORT_LABEL PHONE_TYPE
,PHON_END_DATE SOURCE_PHONE_END_DATE
,CLNT_CLIENT_ID CLIENT_NUMBER
,PHON_AREA_CODE
,PHON_PHONE_NUMBER
,PHON_EXT
,PHON_PROV_ID
,PHON_CNTT_ID
,PHON_DOLK_ID
,PN.CREATED_BY RECORD_NAME
,TRUNC(PN.CREATION_DATE) RECORD_DATE
,PN.LAST_UPDATED_BY MODIFIED_NAME
,TRUNC(PN.LAST_UPDATE_DATE) MODIFIED_DATE
,PHON_CASE_ID CASE_NUMBER
,START_NDT
,END_NDT
,PHON_CARRIER_INFO
,PN.SMS_ENABLED_IND
,PHON_BAD_DATE
,PHON_BAD_DATE_SATISFIED
FROM phone_number pn
 JOIN enum_phone_type pt ON (pn.phon_type_cd = pt.value);

GRANT SELECT ON MAXDAT_SUPPORT.EMRS_D_PHONE_SV TO MAXDAT_REPORTS;