drop view D_PI_INCIDENT_STATUS_SV;
CREATE OR REPLACE VIEW D_PI_INCIDENT_STATUS_SV
AS
  SELECT value DPIISS_ID ,
    report_label INCIDENT_STATUS
  FROM eb.enum_incident_header_status
  WHERE scope = 'INCIDENT' 
  AND effective_end_date IS NULL;
  
  GRANT SELECT ON MAXDAT_SUPPORT.D_PI_INCIDENT_STATUS_SV TO MAXDAT_REPORTS ; 
  GRANT SELECT ON MAXDAT_SUPPORT.D_PI_INCIDENT_STATUS_SV TO MAXDATSUPPORT_READ_ONLY;