drop view D_PI_INCIDENT_REASON_SV;
CREATE OR REPLACE VIEW D_PI_INCIDENT_REASON_SV
AS
  SELECT value DPIIR_ID ,
    report_label INCIDENT_REASON
  FROM eb.enum_affected_party_subtype
  WHERE scope = 'INCIDENT' 
  AND effective_end_date IS NULL;
  
  GRANT SELECT ON MAXDAT_SUPPORT.D_PI_INCIDENT_REASON_SV TO MAXDAT_REPORTS ; 
  GRANT SELECT ON MAXDAT_SUPPORT.D_PI_INCIDENT_REASON_SV TO MAXDATSUPPORT_READ_ONLY;