--DELETE RECORDS
TRUNCATE TABLE CC_S_ACD_INTERVAL_PERIOD;

--ADD NEW COLUMNS
ALTER TABLE CC_S_ACD_INTERVAL_PERIOD
  ADD BUCKETINTERVALID INT not null;
  
ALTER TABLE CC_S_ACD_INTERVAL_PERIOD
  ADD ENTERPRISENAME VARCHAR2(32 BYTE) not null;

--UPDATE UNIQUE KEY CONSTRAINT  
ALTER TABLE CC_S_ACD_INTERVAL_PERIOD
 DROP CONSTRAINT CC_S_INTERVAL_PERIOD__UN;
DROP INDEX CC_S_INTERVAL_PERIOD__UN;
 
 
ALTER TABLE CC_S_ACD_INTERVAL_PERIOD ADD CONSTRAINTS CC_S_INTERVAL_PERIOD_UN UNIQUE
(
  BUCKETINTERVALID
  ,PERIOD_TYPE
);

ALTER TABLE CC_S_ACD_INTERVAL_PERIOD 
MODIFY (
PERIOD_1_UPPER_BOUND    NULL ,     
PERIOD_2_UPPER_BOUND    NULL ,    
PERIOD_3_UPPER_BOUND    NULL ,   
PERIOD_4_UPPER_BOUND    NULL ,    
PERIOD_5_UPPER_BOUND    NULL ,    
PERIOD_6_UPPER_BOUND    NULL ,    
PERIOD_7_UPPER_BOUND    NULL ,    
PERIOD_8_UPPER_BOUND    NULL ,    
PERIOD_9_UPPER_BOUND    NULL ,    
PERIOD_10_UPPER_BOUND   NULL  
);