execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');

execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');

execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');

execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');

execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');

execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');
execute PROCESS_BPM_QUEUE.CREATE_JOB('PROCESS_ALL_ROWS_ALL_BSL','100,''BPM_SEMANTIC''');


