UPDATE MAXDAT.PROCESS_BPM_QUEUE_JOB_CTRL_CFG
SET MAX_TOTAL_NUM_JOBS = 64
	, NUM_JOBS_TO_DEL_DURING_ADJUST = 1
	, NUM_JOBS_TO_ADD_DURING_ADJUST = 4
	, NUM_GROUP_CYCLES_BEFORE_ADD = 2
	, CONTROL_JOB_SLEEP_SECONDS = 30
	, LOCK_TIMEOUT_SECONDS = 300
	, PROCESS_SLEEP_SECONDS = 120
	, PROCESS_BATCH_SECONDS = 10
	, START_DELAY_SECONDS = 10
	, STOP_DELAY_SECONDS = 15
	, PROCESSING_ENABLED = 'Y';

-- Fix incorrect meta-data.
update PROCESS_BPM_QUEUE_JOB
set 
  BSL_ID = 1,
  BDM_ID = 1,
  BATCH_SIZE = 1
where
  BSL_ID  is null
  and BDM_ID is null;
  
commit;


-- Stop incorrect meta-data jobs.

execute PROCESS_BPM_QUEUE_JOB_CONTROL.STOP_JOB_BY_ID(11101);
execute PROCESS_BPM_QUEUE_JOB_CONTROL.STOP_JOB_BY_ID(11294);

