insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values('U','Unknown',1,'Login','Login',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(-1,'Unknown',-1,'Ready','Ready',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(-1,'Reinitialized',2,'Logout','Reinitialized',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(-2,'PG Reset',2,'Logout','PG Reset',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(-3,'Extension Modified',2,'Logout','Extension Modified',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(0,'Unknown',2,'Logout','Unknown',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(0,'Unknown',3,'NotReady','Unknown',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(1,'Break',2,'Logout','Break',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(1,'Break',3,'NotReady','Break',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(2,'Lunch',2,'Logout','Lunch',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(2,'Lunch',3,'NotReady','Lunch',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(3,'Meeting',2,'Logout','Meeting',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(3,'Meeting',3,'NotReady','Meeting',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(4,'Training',3,'NotReady','Training',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(5,'System Issues',2,'Logout','System Issues',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(5,'System Issues',3,'NotReady','System Issues',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(6,'End of Shift',2,'Logout','End of Shift',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(6,'End of Shift',3,'NotReady','End of Shift',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(7,'Special Projects',3,'NotReady','Special Projects',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(8,'Personal',3,'NotReady','Personal',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(9,'Break',3,'NotReady','Break',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(10,'Bathroom',3,'NotReady','Bathroom',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(11,'Follow Up',3,'NotReady','Follow Up',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(12,'Resource Center',3,'NotReady','Resource Center',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(13,'Coaching',3,'NotReady','Coaching',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(14,'Emergency',2,'Logout','Emergency',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(14,'Emergency',3,'NotReady','Emergency',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(15,'Dropped Call-Call Back',3,'NotReady','Dropped Call-Call Back',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(16,'ACW',3,'NotReady','ACW',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(17,'VM',3,'NotReady','VM',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(18,'SME',3,'NotReady','SME',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(19,'Offline Work',3,'NotReady','Offline Work',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(20,'Morning Prep',3,'NotReady','Morning Prep',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(21,'CPS',3,'NotReady','CPS',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(22,'Case Note',3,'NotReady','Case Note',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(23,'Supervisor',3,'NotReady','Supervisor',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(24,'Outbound',3,'NotReady','Outbound',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(25,'Unscheduled',3,'NotReady','Unscheduled',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(26,'Outbound - M3',3,'NotReady','Outbound - M3',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(27,'Outbound - CCC',3,'NotReady','Outbound - CCC',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(28,'AM Break',3,'NotReady','AM Break',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(29,'PM Break',3,'NotReady','PM Break',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(30,'Team Meeting',3,'NotReady','Team Meeting',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(31,'Predictive-Dialer',3,'NotReady','Predictive-Dialer',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(32,'Data Entry',3,'NotReady','Data Entry',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(33,'MAXIMUS Training',3,'NotReady','MAXIMUS Training',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(34,'Client Requested Training',3,'NotReady','Client Requested Training',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(36,'Unknown',3,'NotReady','Unknown',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(999,'Forced by Supervisor',2,'Logout','Forced by Supervisor',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(999,'Supervisor Forced',3,'NotReady','Supervisor Forced',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(32767,'RONA',3,'NotReady','RONA',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(20001,'Logout',3,'NotReady','Logout',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(20002,'Logout',3,'NotReady','Logout',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(20003,'Logout',3,'NotReady','Logout',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(20003,'Forced Logout',2,'Logout','Forced Logout',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(50002,'CTI Client Failure',2,'Logout','CTI Client Failure',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(50002,'Unknown',3,'NotReady','Unknown',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(50003,'Out of Service',2,'Logout','Out of Service',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(50003,'Unknown',3,'NotReady','Unknown',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(50004,'Inactivity',2,'Logout','Inactivity',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(50005,'Non-ACD Call',3,'NotReady','Non-ACD Call',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(50010,'Missed Calls',3,'NotReady','Missed Calls',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(50020,'Reskilled',2,'Logout','Reskilled',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(50030,'Error',2,'Logout','Error',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(50040,'Error',2,'Logout','Error',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(50041,'Line Busy',3,'NotReady','Line Busy',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));

insert into CC_C_ACD_ACTIVITY_EVENT_TYPE (REASONCODE,REASONTEXT,EVENTCODE,EVENTDESC,ACTIVITY,RECORD_EFF_DT,RECORD_END_DT)
values(50042,'Phone Line Disconnected',2,'Logout','Phone Line Disconnected',to_date('01-JAN-00','DD-MON-YY'),to_date('31-DEC-99','DD-MON-YY'));



commit;

