REMARK This will run the scripts in MIEB\EMRS dir
REMARK set EMRS script dir below

define dir = C:\Soundra\MaxDatsvn\BPM\MIEB\createdb\EMRS
@&dir\D_WEEKS_BY_MONTH.sql
@&dir\EMRS_D_AA_CLIENT_SV.sql
@&dir\EMRS_D_AA_TRANS_SV.sql
@&dir\EMRS_D_ADDRESS_SV.sql
@&dir\EMRS_D_ALERT_SV.sql
@&dir\EMRS_D_CARE_SERV_DELIV_AREA_SV.sql
@&dir\EMRS_D_CASE_CLIENT.sql
@&dir\EMRS_D_CASE_REF_SV.sql
@&dir\EMRS_D_CASE_SCI_SV.sql
@&dir\EMRS_D_CASE_SV.sql
@&dir\EMRS_D_CELL_PHONE_SV.sql
@&dir\EMRS_D_CLIENT_ENRL_STATUS_SV.sql
@&dir\EMRS_D_CLIENT_PLAN_ELIG_SV.sql
@&dir\EMRS_D_CLIENT_REF_SV.sql
@&dir\EMRS_D_CLIENT_SV.sql
@&dir\EMRS_D_CLNT_ENROLLED_SV.sql
@&dir\EMRS_D_CLNT_UNENROLLED_SV.sql
@&dir\EMRS_D_ENROLLMENT_ERROR_CD_SV.sql
@&dir\EMRS_D_ENROLLMENT_NOTIF_SV.sql
@&dir\EMRS_D_ENROLLMENT_REJECTION_SV.sql
@&dir\EMRS_D_HOME_PHONE_SV.sql
@&dir\EMRS_D_MAXSTAR_ADDRESS_SV.sql
@&dir\EMRS_D_NOTIFICATION_SV.sql
@&dir\EMRS_D_OE_TRANSFER_SV.sql
@&dir\EMRS_D_OE_TRANSFER_SV_old.sql
@&dir\EMRS_D_PHONE_SV.sql
--@&dir\EMRS_D_PLAN_PERCENTAGE_SV.sql
@&dir\EMRS_D_PRIOR_PROGRAM_SV.sql
@&dir\EMRS_D_PROVIDER_REF_SV.sql
@&dir\EMRS_D_PROVIDER_SPECIALTY_SV.sql
@&dir\EMRS_D_PROVIDER_SV.sql
@&dir\EMRS_D_PROVIDER_TYPE_SV.sql
@&dir\EMRS_D_SELECTION_MI_SV.sql
@&dir\EMRS_D_SELECTION_SEGMENT_SV.sql
@&dir\EMRS_D_SELECTION_TRANS_HIST_SV.sql
@&dir\EMRS_D_SELECTION_TRANS_SV.sql
@&dir\EMRS_D_STATE_ADDRESS_SV.sql
@&dir\EMRS_F_AUTOASSIGN_SV.sql
@&dir\EMRS_F_ENRL_START_CNT_SV.sql
@&dir\EMRS_F_ENROLLMENT_SV.sql
@&dir\EMRS_F_OE_CASE_SV.sql
@&dir\EMRS_F_OE_TRANSFER_CNT_SV.sql
@&dir\EMRS_F_SELECTION_SEGMENT_SV.sql
@&dir\EMRS_F_SLCT_TRANS_CNT_SV.sql

define dir = C:\Soundra\MaxDatsvn\BPM\MIEB\createdb
@&dir\D_LETTER_DEFINITION_SV.sql
@&dir\D_PL_COUNTY_SV.sql
@&dir\D_SURVEY_SV.sql
@&dir\F_DAILY_LETTERS_COUNT_SV.sql
@&dir\F_MATERIALS_COUNT_SV.sql
@&dir\F_PL_LTR_CNT_SV.sql
@&dir\F_PL_LTR_CNT_SV_old.sql
@&dir\F_SURVEYS_COUNT_SV.sql
exit
