DROP VIEW MAXDAT_SUPPORT.EMRS_D_TERMINATION_REASON_SV;

CREATE OR REPLACE VIEW MAXDAT_SUPPORT.EMRS_D_TERMINATION_REASON_SV
AS
SELECT edr.value AS REASON_CODE,
    edr.description AS REASON 
  FROM eb.enum_disenrollment_reason edr
  UNION
   SELECT '0' AS REASON_CODE ,
    'Not Defined' AS REASON 
  FROM DUAL;

GRANT SELECT ON MAXDAT_SUPPORT.EMRS_D_TERMINATION_REASON_SV TO DP4BI_READ_ONLY;
GRANT SELECT ON MAXDAT_SUPPORT.EMRS_D_TERMINATION_REASON_SV TO MAXDATSUPPORT_READ_ONLY;
GRANT SELECT ON MAXDAT_SUPPORT.EMRS_D_TERMINATION_REASON_SV TO MAXDAT_SUPPORT_READ_ONLY;
