DROP VIEW MAXDAT_SUPPORT.EMRS_D_CLIENT_TYPE_SV;

CREATE OR REPLACE VIEW MAXDAT_SUPPORT.EMRS_D_CLIENT_TYPE_SV
AS
SELECT 
    c.VALUE AS CLIENT_TYPE_CD
    ,c.REPORT_LABEL AS CLIENT_TYPE
  FROM EB.ENUM_CLIENT_TYPE c;

GRANT SELECT ON MAXDAT_SUPPORT.EMRS_D_CLIENT_TYPE_SV TO DP4BI_READ_ONLY;
GRANT SELECT ON MAXDAT_SUPPORT.EMRS_D_CLIENT_TYPE_SV TO MAXDATSUPPORT_READ_ONLY;
GRANT SELECT ON MAXDAT_SUPPORT.EMRS_D_CLIENT_TYPE_SV TO MAXDAT_SUPPORT_READ_ONLY;
