DROP VIEW MAXDAT_SUPPORT.EMRS_D_CHANNEL_SV;

CREATE OR REPLACE VIEW MAXDAT_SUPPORT.EMRS_D_CHANNEL_SV
AS
SELECT 'Phone' AS CHANNEL_CODE ,
    'Phone' AS CHANNEL
  FROM DUAL
  UNION ALL
  SELECT 'IVR' AS CHANNEL_CODE ,
    'IVR' AS CHANNEL
  FROM DUAL
  UNION ALL
  SELECT 'Web' AS CHANNEL_CODE ,
    'Web' AS CHANNEL
  FROM DUAL
  UNION ALL
  SELECT 'Mobile' AS CHANNEL_CODE ,
    'Mobile' AS CHANNEL
  FROM DUAL
  UNION ALL
  SELECT 'MailFax' AS CHANNEL_CODE ,
    'Mail/Fax' AS CHANNEL
  FROM DUAL
  UNION ALL
  SELECT 'Reinstatement' AS CHANNEL_CODE ,
    'Reinstatement' AS CHANNEL
  FROM DUAL
  UNION ALL
  SELECT 'Newborn' AS CHANNEL_CODE ,
    'Newborn' AS CHANNEL
  FROM DUAL
  UNION ALL
  SELECT 'DEFile' AS CHANNEL_CODE ,
    'DE File' AS CHANNEL
  FROM DUAL
  UNION ALL
  SELECT 'AutoEnrollments' AS CHANNEL_CODE ,
    'Auto Enrollments' AS CHANNEL
  FROM DUAL;

GRANT SELECT ON MAXDAT_SUPPORT.EMRS_D_CHANNEL_SV TO DP4BI_READ_ONLY;
GRANT SELECT ON MAXDAT_SUPPORT.EMRS_D_CHANNEL_SV TO MAXDATSUPPORT_READ_ONLY;
GRANT SELECT ON MAXDAT_SUPPORT.EMRS_D_CHANNEL_SV TO MAXDAT_SUPPORT_READ_ONLY;
