DROP VIEW MAXDAT_SUPPORT.EMRS_D_OVERRIDE_REASONS_SV;

CREATE OR REPLACE VIEW MAXDAT_SUPPORT.EMRS_D_OVERRIDE_REASONS_SV
AS
SELECT 
    o.value AS OVERRIDE_REASON_CD
    ,o.description AS OVERRIDE_REASON
  FROM EB.ENUM_OVERRIDE_REASONS o
  UNION ALL
  SELECT 
    '0' AS OVERRIDE_REASON_CD
    ,'Not Defined' AS OVERRIDE_REASON
  FROM DUAL;

GRANT SELECT ON MAXDAT_SUPPORT.EMRS_D_OVERRIDE_REASONS_SV TO DP4BI_READ_ONLY;
GRANT SELECT ON MAXDAT_SUPPORT.EMRS_D_OVERRIDE_REASONS_SV TO MAXDATSUPPORT_READ_ONLY;
GRANT SELECT ON MAXDAT_SUPPORT.EMRS_D_OVERRIDE_REASONS_SV TO MAXDAT_SUPPORT_READ_ONLY;

