CREATE OR REPLACE TRIGGER BIU_CC_A_SCHEDULED_JOB 
    BEFORE INSERT OR UPDATE ON CC_A_SCHEDULED_JOB 
    FOR EACH ROW 
BEGIN 
IF INSERTING AND :NEW.SCHEDULED_JOB_ID IS NULL THEN 
          SELECT SEQ_CC_A_SCHEDULED_JOB.NEXTVAL INTO :NEW.SCHEDULED_JOB_ID FROM DUAL;
END IF;
IF INSERTING THEN
  	:NEW.JOB_START_DATE := SYSDATE;
END IF;
END; 
 
/