Insert into CORP_ETL_CONTROL (NAME,VALUE_TYPE,VALUE,DESCRIPTION,CREATED_TS,UPDATED_TS) 
values ('EMRS_ADHOC_RUN_DATE','D','02/11/2014','Get records starting this date for EMRS tables',SYSDATE,SYSDATE);

COMMIT;