ALTER TABLE emrs_f_enrollment
ADD plan_type_id NUMBER(22,0);

ALTER TABLE "EMRS_F_ENROLLMENT" ADD CONSTRAINT "ENROLL_PLANTYPE_FK" FOREIGN KEY ("PLAN_TYPE_ID")
 REFERENCES "EMRS_D_PLAN_TYPE" ("PLAN_TYPE_ID") ENABLE;