CREATE OR REPLACE VIEW "CISCO_ENTERPRISE_CC"."HCO_F_VM_BY_HR_TYPE_BY_DAY_SV" AS
with BUSINESS_HOURS_RANK as
(
select business_hour_type, start_hour, end_hour, start_date, end_date, rank() over ( partition by business_hour_type order by start_hour ) "Rank"
from HCO_BUSINESS_HOURS_TYPE_LKUP
where business_hour_type = 'Business Hours'
)
,
VOICEMAILS_REFERRED AS
(
SELECT
D.D_DATE AS D_DATE
, V.D_DATE_ID
, V.F_V2_CALL_ID
, TO_CHAR(V.DATETIME,'HH24.MISS') as HOUR_VOICEMAIL_REFERRED
, IVR_TIME_SECONDS
, Q.QUEUE_TYPE
,(SELECT L.BUSINESS_HOUR_TYPE 
  from HCO_BUSINESS_HOURS_TYPE_LKUP l where  (TO_CHAR(V.DATETIME,'HH24.MISS') >= L.START_HOUR AND TO_CHAR(V.DATETIME,'HH24.MISS') < L.END_HOUR) and (v.datetime between L.START_DATE AND L.END_DATE) ) AS BUSINESS_HOUR_TYPE
, CASE WHEN V.D_CONTACT_QUEUE_ID IS NOT NULL THEN Q.D_PROJECT_ID
   ELSE NULL
   END D_PROJECT_ID
, CASE
   WHEN V.D_CONTACT_QUEUE_ID IS NOT NULL THEN Q.D_PROGRAM_ID
   ELSE NULL
   END D_PROGRAM_ID  
from 
CC_F_V2_CALL V
INNER JOIN CC_D_DATES D ON (V.D_DATE_ID=D.D_DATE_ID)
INNER JOIN CC_D_CONTACT_QUEUE Q ON (V.D_CONTACT_QUEUE_ID=Q.D_CONTACT_QUEUE_ID AND Q.QUEUE_TYPE  in  (SELECT distinct rtrim(ltrim(regexp_substr(OUT_VAR, '[^,]+', 1, level),''''),'''') 
  FROM (SELECT OUT_VAR  FROM CC_A_LIST_LKUP WHERE NAME = 'VM_call_types') 
CONNECT BY instr(OUT_VAR, ',', 1, level - 1) > 0)  )
INNER JOIN CC_D_PROJECT P ON Q.D_PROJECT_ID = P.PROJECT_ID
WHERE V.IVR_TIME_SECONDS > (select out_var from cc_a_list_lkup where name = 'CAHCO_REFERRED_VM_THRESHOLD')
AND P.PROJECT_NAME = 'CA HCO'
),
VOICEMAILS_RANKED AS
(
select
*
 from
VOICEMAILS_REFERRED V, BUSINESS_HOURS_RANK R
WHERE V.HOUR_VOICEMAIL_REFERRED BETWEEN R.START_HOUR AND R.END_HOUR
AND R.business_hour_type = 'Business Hours'
)
select
D_DATE
, 1 as HOUR_TYPE_ID
, D_DATE_ID
, D_PROJECT_ID
, D_PROGRAM_ID
, sum(case when "Rank" =1 then 1 else 0 end) as  VOICEMAILS_REFERRED
from VOICEMAILS_RANKED
GROUP BY D_DATE, D_DATE_ID, D_PROJECT_ID, D_PROGRAM_ID
UNION ALL
select
D_DATE
, 2 as HOUR_TYPE_ID
, D_DATE_ID
, D_PROJECT_ID
, D_PROGRAM_ID
, sum(case when "Rank" =2 then 1 else 0 end) as  VOICEMAILS_REFERRED
from VOICEMAILS_RANKED
GROUP BY D_DATE, D_DATE_ID, D_PROJECT_ID, D_PROGRAM_ID;


GRANT SELECT ON HCO_F_VM_BY_HR_TYPE_BY_DAY_SV TO MAXDAT_READ_ONLY; 