
--ACD_APPLICATION_ID_INC -- ADD TO UAT:	
INSERT INTO CC_C_FILTER (FILTER_TYPE, VALUE) VALUES ('ACD_APPLICATION_ID_INC','10012');
INSERT INTO CC_C_FILTER (FILTER_TYPE, VALUE) VALUES ('ACD_APPLICATION_ID_INC','10013');
INSERT INTO CC_C_FILTER (FILTER_TYPE, VALUE) VALUES ('ACD_APPLICATION_ID_INC','10014');
INSERT INTO CC_C_FILTER (FILTER_TYPE, VALUE) VALUES ('ACD_APPLICATION_ID_INC','10015');
INSERT INTO CC_C_FILTER (FILTER_TYPE, VALUE) VALUES ('ACD_APPLICATION_ID_INC','10020');
INSERT INTO CC_C_FILTER (FILTER_TYPE, VALUE) VALUES ('ACD_APPLICATION_ID_INC','10021');

INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME)
VALUES ('0.3.1','200','200_ADD_MISSING_ACD_APPLICATION_IDS_TO_C_FILTER');

COMMIT;