DROP TABLE ETL_INIT_MIHC_CON;

CREATE TABLE ETL_INIT_MIHC_CON 
(
  JOB_ID NUMBER(18, 0) NOT NULL 
, ROW_NUM NUMBER(18, 0) NOT NULL 
, ERROR_COUNT NUMBER(18, 0) 
, ERROR_TEXT VARCHAR2(512 BYTE) 
, ERROR_FIELDS VARCHAR2(512 BYTE) 
, RECORD_CONTENT VARCHAR2(1024 BYTE) 
, LETTER_REQ_ID NUMBER(18, 0) 
, CLNT_FNAME VARCHAR2(80 BYTE) 
, CLNT_LNAME VARCHAR2(80 BYTE) 
, CLNT_MNAME VARCHAR2(80 BYTE) 
, ATTENTION_LINE VARCHAR2(80 BYTE) 
, HOUSE_NO VARCHAR2(80 BYTE) 
, STREET1 VARCHAR2(80 BYTE) 
, STREET2 VARCHAR2(80 BYTE) 
, CITY VARCHAR2(80 BYTE) 
, STATE VARCHAR2(80 BYTE) 
, ZIP VARCHAR2(32 BYTE) 
, ZIP_FOUR VARCHAR2(32 BYTE) 
, STATUS_CODE VARCHAR2(80 BYTE) 
, UPDATE_CODE VARCHAR2(80 BYTE) 
, CASE_CIN VARCHAR2(32 BYTE) 
, MAIL_TS DATE 
, CONTROL_NUM VARCHAR2(80 BYTE) 
, RECIPIENT_ID VARCHAR2(80 BYTE) 
, MICRD_ID VARCHAR2(80 BYTE) 
, PROCESS_IND NUMBER(1, 0) 
, PROCESS_TS DATE 
, JOB_CTRL_ID NUMBER(38) NOT NULL
) 
TABLESPACE MAXDAT_MIEB_DATA;

CREATE UNIQUE INDEX ETL_INIT_MIHC_CON_PK ON ETL_INIT_MIHC_CON (ROW_NUM ASC, JOB_ID ASC) TABLESPACE MAXDAT_MIEB_DATA;
ALTER TABLE ETL_INIT_MIHC_CON ADD CONSTRAINT ETL_INIT_MIHC_CON_PK PRIMARY KEY ( ROW_NUM, JOB_ID ) USING INDEX ETL_INIT_MIHC_CON_PK;

CREATE INDEX IDX01_ETL_INIT_MIHC_CON ON ETL_INIT_MIHC_CON (LETTER_REQ_ID ASC, JOB_ID ASC) TABLESPACE MAXDAT_MIEB_DATA;
CREATE INDEX IDX02_ETL_INIT_MIHC_CON ON ETL_INIT_MIHC_CON (RECIPIENT_ID ASC, JOB_ID ASC) TABLESPACE MAXDAT_MIEB_DATA;

