CREATE OR REPLACE VIEW D_PI_INCIDENT_ABOUT_SV
AS
  SELECT value DPIIA_ID ,
    report_label INCIDENT_ABOUT
  FROM eb.enum_affected_party_type
  WHERE scope = 'INCIDENT' ;
  
  GRANT SELECT ON MAXDAT_SUPPORT.D_PI_INCIDENT_ABOUT_SV TO MAXDAT_REPORTS ; 