CREATE OR REPLACE FORCE VIEW CC_D_TARGET_SV AS
SELECT * from CC_D_TARGET;

CREATE PUBLIC SYNONYM CC_D_TARGET_SV FOR CC_D_TARGET_SV ;

GRANT SELECT ON  CC_D_TARGET_SV TO MAXDAT_READ_ONLY;


CREATE OR REPLACE FORCE VIEW CC_D_PROD_PLANNING_TARGET_SV AS
SELECT * FROM CC_D_PROD_PLANNING_TARGET;

CREATE PUBLIC SYNONYM CC_D_PROD_PLANNING_TARGET_SV FOR CC_D_PROD_PLANNING_TARGET_SV ;

GRANT SELECT ON  CC_D_PROD_PLANNING_TARGET_SV TO MAXDAT_READ_ONLY;

INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME) VALUES ('0.1.4','004','004_CREATE_TARGET_VIEWS');

COMMIT;

