CREATE TABLE TXEB_ETL_CHIP_ELIG_EVENTS (
TECEE_ID 	 NUMBER  NOT NULL ENABLE,
EVENT_ID	 NUMBER(38,0) NOT NULL ENABLE,
EVENT_CD	 VARCHAR2(100 BYTE),
SYS_TRA_ID	 NUMBER(38,0),
TRAN_TYPE	 VARCHAR2(30 BYTE),
JOB_ID		 NUMBER(38,0),
CASE_ID		 NUMBER(38,0),
CASE_CIN	 VARCHAR2(30 BYTE),
CLIENT_ID	 NUMBER(38,0),
CLIENT_MED_ID	 VARCHAR2(30 BYTE),
SEGMENT_START_DT DATE,
SEGMENT_END_DT	 DATE,
SEGMENT_ID	 NUMBER(38,0),
ERR_INDICATOR	 VARCHAR2(1 BYTE),
CREATE_DT	 DATE NOT NULL ENABLE,
CREATE_BY_NAME	 VARCHAR2(100 BYTE),
UPDATE_DT	 DATE,
UPDATE_BY_NAME	 VARCHAR2(100 BYTE),
TIERS_SEND_DT	 DATE,
PROCESS_DT	 DATE,
LETTER_TYPE	 VARCHAR2(10),
LETTER_REQ_ID	 NUMBER(18,0),
PROGRAM		 VARCHAR2(30 BYTE),
PERI_DEN_SEGMENT NUMBER(18,0),
ENROLL_STAT_DENTAL VARCHAR2(64 BYTE),
ENROLL_STAT_MED	 VARCHAR2(64 BYTE),
CASE_STATUS	 VARCHAR2(2 BYTE),
ENROLL_TRAN_TYPE VARCHAR2(30 BYTE),
ENR_SYS_TRA_ID	 NUMBER(38,0),
EDG_SYS_TRA_ID	 NUMBER(38,0),
INSTANCE_STATUS	 VARCHAR2(32 BYTE) DEFAULT 'Active' NOT NULL ENABLE, 
CANCEL_DT	 DATE,
CANCEL_BY	 VARCHAR2(80 BYTE),
CANCEL_REASON	 VARCHAR2(40 BYTE),
CANCEL_METHOD	 VARCHAR2(40 BYTE),
COMPLETE_DT	 DATE,
ASSD_PROCESS_ELIG_EVENT	DATE,
ASED_PROCESS_ELIG_EVENT	DATE,
ASF_PROCESS_ELIG_EVENT	VARCHAR2(1 BYTE),	
ASPB_PROCESS_ELIG_EVENT	VARCHAR2(100),
STG_EXTRACT_DATE DATE NOT NULL ENABLE, 
STG_LAST_UPDATE_DATE DATE NOT NULL ENABLE, 
STAGE_DONE_DATE DATE, 
INSTANCE_START_DATE DATE,
INSTANCE_END_DATE DATE,
LAST_EVENT_DATE   DATE,
CHANGE_FLAG varchar2(1),
PRIOR_ENR_TRANS_SENT varchar2(1),
SYS_TRAN_STAGE_ID NUMBER(38,0),
SYS_TRAN_STAGE_NAME VARCHAR2(50),
FEE_STATUS	    VARCHAR2(10)

)TABLESPACE MAXDAT_DATA ;

--CREATE PRIMARY KEY
alter table  TXEB_ETL_CHIP_ELIG_EVENTS add primary key (TECEE_ID) using index tablespace MAXDAT_INDX; 

create unique index txeb_chip_elig_events_ix1 on TXEB_ETL_CHIP_ELIG_EVENTS(EVENT_ID) tablespace MAXDAT_INDX;
create index txeb_chip_elig_events_ix2 on TXEB_ETL_CHIP_ELIG_EVENTS (SyS_TRA_ID) TABLESPACE MAXDAT_INDX;
create index txeb_chip_elig_events_ix3 on TXEB_ETL_CHIP_ELIG_EVENTS (INSTANCE_STATUS) TABLESPACE MAXDAT_INDX;
create index txeb_chip_elig_events_ix4 on TXEB_ETL_CHIP_ELIG_EVENTS (CREATE_DT) TABLESPACE MAXDAT_INDX;
create index txeb_chip_elig_events_ix5 on TXEB_ETL_CHIP_ELIG_EVENTS (COMPLETE_DT) TABLESPACE MAXDAT_INDX;
CREATE INDEX TXEB_CHIP_ELIG_EVENTS_IX6 ON TXEB_ETL_CHIP_ELIG_EVENTS(event_cd) TABLESPACE MAXDAT_INDX;
create index TXEB_CHIP_ELIG_EVENTS_IX7 on TXEB_ETL_CHIP_ELIG_EVENTS(CHANGE_FLAG) TABLESPACE MAXDAT_INDX;


grant select on TXEB_ETL_CHIP_ELIG_EVENTS to MAXDAT_READ_ONLY;


CREATE TABLE TXEB_ETL_CHIP_ELIG_EVENT_OLTP (
TECEE_ID 	 NUMBER  NOT NULL ENABLE,
EVENT_ID	 NUMBER(38,0) NOT NULL ENABLE,
EVENT_CD	 VARCHAR2(100 BYTE),
SYS_TRA_ID	 NUMBER(38,0),
TRAN_TYPE	 VARCHAR2(30 BYTE),
JOB_ID		 NUMBER(38,0),
CASE_ID		 NUMBER(38,0),
CASE_CIN	 VARCHAR2(30 BYTE),
CLIENT_ID	 NUMBER(38,0),
CLIENT_MED_ID	 VARCHAR2(30 BYTE),
SEGMENT_START_DT DATE,
SEGMENT_END_DT	 DATE,
SEGMENT_ID	 NUMBER(38,0),
ERR_INDICATOR	 VARCHAR2(1 BYTE),
CREATE_DT	 DATE NOT NULL ENABLE,
CREATE_BY_NAME	 VARCHAR2(100 BYTE),
UPDATE_DT	 DATE,
UPDATE_BY_NAME	 VARCHAR2(100 BYTE),
TIERS_SEND_DT	 DATE,
PROCESS_DT	 DATE,
LETTER_TYPE	 VARCHAR2(10),
LETTER_REQ_ID	 NUMBER(18,0),
PROGRAM		 VARCHAR2(30 BYTE),
PERI_DEN_SEGMENT NUMBER(18,0),
ENROLL_STAT_DENTAL VARCHAR2(64 BYTE),
ENROLL_STAT_MED	 VARCHAR2(64 BYTE),
CASE_STATUS	 VARCHAR2(2 BYTE),
ENROLL_TRAN_TYPE VARCHAR2(30 BYTE),
ENR_SYS_TRA_ID	 NUMBER(38,0),
EDG_SYS_TRA_ID	 NUMBER(38,0),
INSTANCE_STATUS	 VARCHAR2(32 BYTE), 
CANCEL_DT	 DATE,
CANCEL_BY	 VARCHAR2(80 BYTE),
CANCEL_REASON	 VARCHAR2(40 BYTE),
CANCEL_METHOD	 VARCHAR2(40 BYTE),
COMPLETE_DT	 DATE,
ASSD_PROCESS_ELIG_EVENT	DATE,
ASED_PROCESS_ELIG_EVENT	DATE,
ASF_PROCESS_ELIG_EVENT	VARCHAR2(1 BYTE),	
ASPB_PROCESS_ELIG_EVENT	VARCHAR2(100),
STG_EXTRACT_DATE DATE,
STG_LAST_UPDATE_DATE DATE, 
STAGE_DONE_DATE DATE, 
INSTANCE_START_DATE DATE,
INSTANCE_END_DATE DATE,
LAST_EVENT_DATE   DATE,
CHANGE_FLAG varchar2(1),
LETTER_CREATE_DT DATE,
ENR_TRAN_UPDATE_DT DATE,
ENROLL_STATUS_UPDATE_DT DATE,     
ENROLL_STATUS_MED_CD VARCHAR2(64),
ENROLL_STATUS_DEN_CD VARCHAR2(64),
ENR_TRAN_TYPE_CD VARCHAR2(64),
PRIOR_ENR_TRANS_SENT varchar2(1),
SYS_TRAN_STAGE_ID NUMBER(38,0),
SYS_TRAN_STAGE_NAME VARCHAR2(50),
FEE_STATUS	    VARCHAR2(10)
)TABLESPACE MAXDAT_DATA ;

create unique index txeb_chip_elig_events_oltp_ix1 on TXEB_ETL_CHIP_ELIG_EVENT_OLTP(EVENT_ID) tablespace MAXDAT_INDX;
create index txeb_chip_elig_events_oltp_ix2 on TXEB_ETL_CHIP_ELIG_EVENT_OLTP (COMPLETE_DT) TABLESPACE MAXDAT_INDX;
CREATE INDEX TXEB_CHIP_ELIG_EVENTS_OLTP_IX3 ON TXEB_ETL_CHIP_ELIG_EVENT_OLTP(event_cd) TABLESPACE MAXDAT_INDX;
create index TXEB_CHIP_ELIG_EVENTS_OLTP_IX4 on TXEB_ETL_CHIP_ELIG_EVENT_OLTP(CHANGE_FLAG) TABLESPACE MAXDAT_INDX;
create index TXEB_CHIP_ELIG_EVENTS_OLTP_IX5 on TXEB_ETL_CHIP_ELIG_EVENT_OLTP(SYS_TRAN_STAGE_NAME) TABLESPACE MAXDAT_INDX;



grant select on TXEB_ETL_CHIP_ELIG_EVENT_OLTP to MAXDAT_READ_ONLY;


CREATE TABLE TXEB_CHIP_ELIG_EVENTS_WIP_BPM(
TECEE_ID 	 NUMBER  NOT NULL ENABLE,
EVENT_ID	 NUMBER(38,0) NOT NULL ENABLE,
EVENT_CD	 VARCHAR2(100 BYTE),
SYS_TRA_ID	 NUMBER(38,0),
TRAN_TYPE	 VARCHAR2(30 BYTE),
JOB_ID		 NUMBER(38,0),
CASE_ID		 NUMBER(38,0),
CASE_CIN	 VARCHAR2(30 BYTE),
CLIENT_ID	 NUMBER(38,0),
CLIENT_MED_ID	 VARCHAR2(30 BYTE),
SEGMENT_START_DT DATE,
SEGMENT_END_DT	 DATE,
SEGMENT_ID	 NUMBER(38,0),
ERR_INDICATOR	 VARCHAR2(1 BYTE),
CREATE_DT	 DATE NOT NULL ENABLE,
CREATE_BY_NAME	 VARCHAR2(100 BYTE),
UPDATE_DT	 DATE,
UPDATE_BY_NAME	 VARCHAR2(100 BYTE),
TIERS_SEND_DT	 DATE,
PROCESS_DT	 DATE,
LETTER_TYPE	 VARCHAR2(10),
LETTER_REQ_ID	 NUMBER(18,0),
PROGRAM		 VARCHAR2(30 BYTE),
PERI_DEN_SEGMENT NUMBER(18,0),
ENROLL_STAT_DENTAL VARCHAR2(64 BYTE),
ENROLL_STAT_MED	 VARCHAR2(64 BYTE),
CASE_STATUS	 VARCHAR2(2 BYTE),
ENROLL_TRAN_TYPE VARCHAR2(30 BYTE),
ENR_SYS_TRA_ID	 NUMBER(38,0),
EDG_SYS_TRA_ID	 NUMBER(38,0),
INSTANCE_STATUS	 VARCHAR2(32 BYTE), 
CANCEL_DT	 DATE,
CANCEL_BY	 VARCHAR2(80 BYTE),
CANCEL_REASON	 VARCHAR2(40 BYTE),
CANCEL_METHOD	 VARCHAR2(40 BYTE),
COMPLETE_DT	 DATE,
ASSD_PROCESS_ELIG_EVENT	DATE,
ASED_PROCESS_ELIG_EVENT	DATE,
ASF_PROCESS_ELIG_EVENT	VARCHAR2(1 BYTE),
ASPB_PROCESS_ELIG_EVENT	VARCHAR2(100),	
STG_EXTRACT_DATE DATE, 
STG_LAST_UPDATE_DATE DATE, 
STAGE_DONE_DATE DATE, 
INSTANCE_START_DATE DATE,
INSTANCE_END_DATE DATE,
LAST_EVENT_DATE   DATE,
CHANGE_FLAG varchar2(1),
PRIOR_ENR_TRANS_SENT varchar2(1),
SYS_TRAN_STAGE_ID NUMBER(38,0),
SYS_TRAN_STAGE_NAME VARCHAR2(50),
FEE_STATUS	    VARCHAR2(10)
)TABLESPACE MAXDAT_DATA ;

create unique index txeb_chip_elig_events_wip_ix1 on TXEB_CHIP_ELIG_EVENTS_WIP_BPM(EVENT_ID) tablespace MAXDAT_INDX;
create index txeb_chip_elig_events_wip_ix2 on TXEB_CHIP_ELIG_EVENTS_WIP_BPM (COMPLETE_DT) TABLESPACE MAXDAT_INDX;
create index txeb_chip_elig_events_wip_ix3 on TXEB_CHIP_ELIG_EVENTS_WIP_BPM (CHANGE_FLAG) TABLESPACE MAXDAT_INDX;



grant select on TXEB_CHIP_ELIG_EVENTS_WIP_BPM to MAXDAT_READ_ONLY;


create table TXEB_CHIP_ELIG_EVENTS_LKUP
(
EVENT_TYPE varchar2(50)
,LETTER_TYPE varchar2(50)
,ENROLL_STATUS_LIST varchar2(256)
)
tablespace MAXDAT_DATA;

CREATE INDEX CHIP_EE_LKUP_IDX1 ON TXEB_CHIP_ELIG_EVENTS_LKUP(event_type) TABLESPACE MAXDAT_INDX;


grant select on TXEB_CHIP_ELIG_EVENTS_LKUP to MAXDAT_READ_ONLY;



