
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','A','A-No Action Yet, Welcome Packet Due',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','B','B-Welcome Packet Sent',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','D','E-Add Enroll Pending',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','E','D-Add Enroll Not Sent',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','K','K-Excluded',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','L','L-Voluntary',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','AAF','AutoAssignment Process Complete',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','AAR','Awaiting AutoAssignment Job',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','P','P-Pending',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','A*','A*-Mandatory, NO Welcome Packet Required',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','G','G-Effective Enrollment',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','AAPOR','Awaiting AutoAssignment PlanOnly Job',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','C','C-Reminder Letter Sent',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','L*','L*-Voluntary, Welcome Packet Sent',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','O*','O*-Out Of Service Area ,HPC Letter Request created',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','H','H-Out Of Service Area,HPC Letter Request sent',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','S','S - MMP Enrollment Accepted',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','D+','D+ - MMP Accepted by CMS',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','PE','PE - MMP Pending Enrollment',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','X','Enrollment Status Error',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','D*','D*-CHIP Client has active Medicaid Eligibility',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','G+','G+ -New Enrollment, Plan Change allowed',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','G*','G*-Service Area Change, Plan Change allowed',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);
Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) values (Seq_cell_Id.Nextval,'CLIENT_ENROLL_STATUS','ENROLL_STATUS','G^','G^-Renewal Enrollment, Plan Change allowed',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List lookup for client enrollment status.  VALUE maps to the ENROLL_STATUS_CD in Client_Enroll_Status_Stg table.',SYSDATE,SYSDATE);

insert into corp_etl_control(name,value_type,value,description,created_ts,updated_ts)
values('CEE_LAST_CHIP_ELIG_EVENT_ID','N','0','Used to fetch CHIP eligibility events for Monitor CHIP Eligibility Events process',sysdate,sysdate);

insert into corp_etl_control(name,value_type,value,description,created_ts,updated_ts)
values('RUN_CHIP_ELIG_EVENT_START','V','000000','Used to fetch CHIP eligibility events for Monitor CHIP Eligibility Events process',sysdate,sysdate);

insert into corp_etl_control(name,value_type,value,description,created_ts,updated_ts)
values('RUN_CHIP_ELIG_EVENT_END','V','235959','Used to fetch CHIP eligibility events for Monitor CHIP Eligibility Events process',sysdate,sysdate);


insert into TXEB_CHIP_ELIG_EVENTS_LKUP(event_type, letter_type,enroll_status_list)
values ('ADDR_UPDATED','HPC','''O*''');

insert into TXEB_CHIP_ELIG_EVENTS_LKUP(event_type, letter_type,enroll_status_list)
values ('NEW','EPM','''A''');

insert into TXEB_CHIP_ELIG_EVENTS_LKUP(event_type, letter_type,enroll_status_list)
values ('RENEWAL','EPM','''G''');

insert into TXEB_CHIP_ELIG_EVENTS_LKUP(event_type, letter_type,enroll_status_list)
values ('ADD','EPM','''A'',''AAPOR''');

insert into TXEB_CHIP_ELIG_EVENTS_LKUP(event_type, letter_type,enroll_status_list)
values ('REACTIVATION','ECN','''G'',''AAPOR''');


Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) 
values (Seq_cell_Id.Nextval,'EVENTS_POST_PROCESS_PASS','CHIP_ELIG_EVENTS','CHIP_ELIG_EVENTS','''HOH'',''REN_REACT'',''CEFLAG_CHANGE'',''COSTSHARE_CHANGE'',''CLIENT_DATES_CHANGE'',''DNL_VOID'',''RENR'',''DNL'',''TRM''',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List of events that are set to completion if they have a stage status of POST_PROCESS_PASS.',SYSDATE,SYSDATE);

Insert into CORP_ETL_LIST_LKUP (CELL_ID,NAME,LIST_TYPE,VALUE,OUT_VAR,REF_TYPE,REF_ID,START_DATE,END_DATE,COMMENTS,CREATED_TS,UPDATED_TS) 
values (Seq_cell_Id.Nextval,'EVENTS_STAGE_STATUS','CHIP_ELIG_EVENTS','ELIG_EVENTS_STATUS','''POST_PROCESS_PASS'',''REPROCESSED_FINAL_PASS'',''VALIDATION_FAIL'',''REPROCESSED_VALIDATION_FAIL'',''EB_NO_ACTION_NEEDED''',null,null,SYSDATE,to_date('07-JUL-77','DD-MON-RR'),'List of terminal status that for Financial events for CHIP Elig Events.',SYSDATE,SYSDATE);


insert into corp_etl_control(name,value_type,value,description,created_ts,updated_ts)
values('ENROLL_STATUS_TIME_VALUE','N','5','Time in minutes to add to the event creation date when looking for the enrollment status',sysdate,sysdate);


commit;  