
ALTER TABLE CC_F_AGENT_BY_DATE MODIFY (FIRST_LOGIN NULL);
ALTER TABLE CC_F_AGENT_BY_DATE MODIFY (LAST_LOGOUT NULL);
ALTER TABLE CC_F_AGENT_BY_DATE MODIFY (SCHEDULED_SHIFT_MINUTES NULL);
ALTER TABLE CC_F_AGENT_BY_DATE MODIFY (ACTUAL_SHIFT_MINUTES NULL);
ALTER TABLE CC_F_AGENT_BY_DATE MODIFY (ACTUAL_OVERTIME_MINUTES NULL);

INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME)
VALUES ('0.1.2','100','100_ALTER_CC_F_AGENT_BY_DATE_MODIFY_WFM_FIELDS');

COMMIT;