CREATE OR REPLACE VIEW EMRS_D_ADDR_TYPE_SV
AS
SELECT value AS ADDR_TYPE_CD
      ,report_label AS ADDR_TYPE
FROM &schema_name..enum_address_type
WHERE effective_end_date IS NULL
UNION ALL
SELECT 'UD' AS ADDR_TYPE_CD
      , 'Undefined' AS ADDR_TYPE
FROM DUAL;

GRANT SELECT ON EMRS_D_ADDR_TYPE_SV TO MAXDAT_REPORTS;
