CREATE OR REPLACE VIEW MAXDAT_SUPPORT.EMRS_D_COEB_PROV_ORG_SV AS
SELECT DISTINCT PX.RAE_ID PLAN_ID_ext
, P.PLAN_ID
, 'MEDICAID' MANAGED_CARE_PROGRAM
, CASE WHEN PROVIDER_ID_EXT IN ('07020368','23876239') THEN 'MCO' ELSE 'PCMP' END PROVIDER_ORG_TYPE
, CASE WHEN PROVIDER_ID_EXT IN ('07020368','23876239') THEN PROVIDER_ID_EXT ELSE 'PCMP' END PROVIDER_ORG_CD
, CASE WHEN PROVIDER_ID_EXT = '07020368' THEN 'Rocky Mountain Health Plan'
       WHEN PROVIDER_ID_EXT = '23876239' THEN 'Denver Health Medicaid Choice'
       ELSE 'Individual PCMP' END PROVIDER_ORG_LABEL
FROM 
&schema_name..PROVIDER_ID_XWALK PX
join &schema_name..PLANS p on p.plan_id_ext = PX.RAE_ID
WHERE (PX.DTE_END IS NULL OR PX.DTE_EFFECTIVE < PX.DTE_END)
;
            
  GRANT SELECT ON MAXDAT_SUPPORT.EMRS_D_COEB_PROV_ORG_SV TO MAXDAT_REPORTS; 



