DROP VIEW MAXDAT_SUPPORT.D_CLIENT_SUPPLEMENTARY_INFO_SV;

CREATE OR REPLACE VIEW MAXDAT_SUPPORT.D_CLIENT_SUPPLEMENTARY_INFO_SV
AS
SELECT "CLIENT_ID","CASE_CLIENT_ID","CASE_ID","CASE_CIN","HOH_ID","CASE_STATUS","CASE_CLIENT_STATUS","LAST_NAME","LAST_NAME_CANON","LAST_NAME_SOUNDLIKE","FIRST_NAME","FIRST_NAME_CANON","FIRST_NAME_SOUNDLIKE","MIDDLE_INITIAL","CLIENT_CIN","SSN","GENDER_CD","DOB","DOB_NUM","CLIENT_TYPE_CD","ADDR_ID","ADDR_TYPE_CD","ADDR_COUNTY","ADDR_ZIP","ADDR_ZIP_FOUR","ADDR_ATTN","ADDR_STREET_1","ADDR_STREET_2","ADDR_CITY","ADDR_BAD_DATE","ADDR_BAD_DATE_SATISFIED","CREATED_BY","CREATE_TS","UPDATED_BY","UPDATE_TS","CASE_CREATED_BY","CASE_CREATE_TS","CASE_UPDATED_BY","CASE_UPDATE_TS","PROGRAM_CD","ADDR_STATE_CD","ADDR_COUNTRY","CLNT_GENERIC_FIELD1_DATE","CLNT_GENERIC_FIELD2_DATE","CLNT_GENERIC_FIELD3_NUM","CLNT_GENERIC_FIELD4_NUM","CLNT_GENERIC_FIELD5_TXT","CLNT_GENERIC_FIELD6_TXT","CLNT_GENERIC_FIELD7_TXT","CLNT_GENERIC_FIELD8_TXT","CLNT_GENERIC_FIELD9_TXT","CLNT_GENERIC_FIELD10_TXT" FROM eb.client_supplementary_info;

GRANT SELECT ON MAXDAT_SUPPORT.D_CLIENT_SUPPLEMENTARY_INFO_SV TO EB_READ_ONLY;
GRANT SELECT ON MAXDAT_SUPPORT.D_CLIENT_SUPPLEMENTARY_INFO_SV TO MAXDATSUPPORT_READ_ONLY;
GRANT SELECT ON MAXDAT_SUPPORT.D_CLIENT_SUPPLEMENTARY_INFO_SV TO MAXDAT_SUPPORT_READ_ONLY;
