use role SYSADMIN;
use warehouse PUREINSIGHTS_DEV_LOAD_DAILY_WH;
use database PUREINSIGHTS_DEV;
use schema PUBLIC;

CREATE OR REPLACE FORCE VIEW PI_FILES_TO_INGEST_VW AS
	SELECT * FROM raw.pi_files_to_ingest;

GRANT SELECT ON PI_FILES_TO_INGEST_VW TO PI_DATA_INGEST_DEV_ALERT_USER;