--DROP VIEW MAXDAT.F_MFB_V2_BY_HOUR_SV;

/* Formatted on 7/12/2022 10:57:44 AM (QP5 v5.374) */
CREATE OR REPLACE FORCE VIEW MAXDAT.F_MFB_V2_BY_HOUR_SV
(
    FMFBBH_ID,
    D_DATE_HOUR,
    MFB_BI_ID,
    CREATION_COUNT,
    INVENTORY_COUNT,
    COMPLETION_COUNT
)
BEQUEATH DEFINER
AS
    SELECT MFB_V2_BI_ID             AS FMFBBH_ID,
	       -- D_DATE is a DAY (no time )
	       -- Add 1 second to the D_DATE so MS will work with no changes
		   -- because MS uses > not >= for the date test
           D_DATE+(1/(24*60*60))    AS D_DATE_HOUR,
           MFB_V2_BI_ID             AS MFB_BI_ID,
           CREATION_COUNT           AS CREATION_COUNT,
           CASE WHEN 
                NVL(COMPLETION_COUNT,0) > 0 
                THEN 0 
				ELSE 1 END          AS INVENTORY_COUNT,
           COMPLETION_COUNT
      FROM MAXDAT.F_MFB_V2_BY_DAY
WITH READ ONLY;


GRANT INSERT, SELECT, UPDATE ON MAXDAT.F_MFB_V2_BY_HOUR_SV TO MAXDAT_OLTP_SIU;

GRANT DELETE, INSERT, SELECT, UPDATE ON MAXDAT.F_MFB_V2_BY_HOUR_SV TO MAXDAT_OLTP_SIUD;

GRANT SELECT ON MAXDAT.F_MFB_V2_BY_HOUR_SV TO MAXDAT_READ_ONLY;
