--------------------------------------------------------------------------
-- Run this script in MAXDAT@NHX1DORUHXDP.CLDMGFTTY3FU.US-EAST-1.RDS.AMAZONAWS.COM:1557/NYHXDPMU to make it look like MAXDAT@NHX1DORD1HXDP.CLDMGFTTY3FU.US-EAST-1.RDS.AMAZONAWS.COM:1557/NYHXDPMD.
--
-- Please review the script before using it to make sure it won't cause any unacceptable data loss.
--
-- MAXDAT@NHX1DORUHXDP.CLDMGFTTY3FU.US-EAST-1.RDS.AMAZONAWS.COM:1557/NYHXDPMU schema extracted by user WL134672
-- MAXDAT@NHX1DORD1HXDP.CLDMGFTTY3FU.US-EAST-1.RDS.AMAZONAWS.COM:1557/NYHXDPMD schema extracted by user MAXDAT
--------------------------------------------------------------------------
-- "Set define off" turns off substitution variables.
Set define off;

CREATE SEQUENCE MAXDAT.SEQ_NYHIX_MFB_V2_REPROCESSED_ID
  START WITH 20040
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 10
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;

CREATE TABLE MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH
(
  NYHIX_MFB_V2_REPROCESSED_ID  NUMBER,
  MFB_V2_CREATE_DATE           DATE,
  MFB_V2_UPDATE_DATE           DATE,
  BATCH_NAME                   VARCHAR2(255 BYTE),
  CREATION_USER_ID             VARCHAR2(128 BYTE),
  REPROCESSED_FLAG             VARCHAR2(1 BYTE),
  REPROCESSED_DATE             DATE,
  JIRA_NUMBER                  VARCHAR2(128 BYTE),
  REPROCESSING_COMPLETED_DATE  DATE,
  F_BY_DAY_ROW_CNT_BEFORE      NUMBER(12),
  F_BY_DAY_ROW_CNT_AFTER       NUMBER(12),
  F_BY_HOUR_ROW_CNT_BEFORE     NUMBER(12),
  F_BY_HOUR_ROW_CNT_AFTER      NUMBER(12)
);

CREATE OR REPLACE procedure MAXDAT.NYHIX_MFB_V2_INSERT_REPROCESS_STAGE(
    P_BATCH_NAME           VARCHAR2,      
    P_REPROCESSED_DATE     VARCHAR2, 
    P_JIRA_NUMBER          VARCHAR2,
    P_CREATION_USER_ID     VARCHAR2
)
AS
    LV_MFB_V2_BI_ID             NUMBER          := 0;
    LV_F_BY_DAY_ROW_CNT_BEFORE  NUMBER(12,0)    := 0;
    LV_F_BY_DAY_ROW_CNT_AFTER   NUMBER(12,0)    := 0;
    LV_F_BY_HOUR_ROW_CNT_BEFORE NUMBER(12,0)    := 0;
    LV_F_BY_HOUR_ROW_CNT_AFTER  NUMBER(12,0)    := 0;
BEGIN
    LV_MFB_V2_BI_ID            := 0;
    LV_F_BY_DAY_ROW_CNT_BEFORE := 0;
    LV_F_BY_DAY_ROW_CNT_AFTER  := NULL;
    LV_F_BY_HOUR_ROW_CNT_BEFORE := 0;
    LV_F_BY_HOUR_ROW_CNT_AFTER := NULL;

    DBMS_OUTPUT.PUT_LINE('P_BATCH_NAME '||P_BATCH_NAME );    
    DBMS_OUTPUT.PUT_LINE('P_REPROCESSED_DATE '||P_REPROCESSED_DATE); 
    DBMS_OUTPUT.PUT_LINE('P_JIRA_NUMBER '||P_JIRA_NUMBER);
    DBMS_OUTPUT.PUT_LINE('P_CREATION_USER_ID '||P_CREATION_USER_ID);
   
    SELECT MFB_V2_BI_ID INTO LV_MFB_V2_BI_ID
    FROM NYHIX_MFB_V2_BATCH_SUMMARY
    WHERE BATCH_NAME = P_BATCH_NAME;      

    SELECT SUM(1) INTO LV_F_BY_DAY_ROW_CNT_BEFORE 
    FROM F_MFB_V2_BY_DAY
    WHERE MFB_V2_BI_ID = LV_MFB_V2_BI_ID;

    SELECT SUM(1) INTO LV_F_BY_HOUR_ROW_CNT_BEFORE 
    FROM F_MFB_V2_BY_DAY
    WHERE MFB_V2_BI_ID = LV_MFB_V2_BI_ID;

    INSERT INTO MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH
        (
        BATCH_NAME,
        REPROCESSED_DATE, 
        JIRA_NUMBER,
        CREATION_USER_ID,
        F_BY_DAY_ROW_CNT_BEFORE,
        F_BY_HOUR_ROW_CNT_BEFORE,   
        F_BY_DAY_ROW_CNT_AFTER,
        F_BY_HOUR_ROW_CNT_AFTER   
        )
    VALUES
    (
        P_BATCH_NAME,      
        TO_DATE(P_REPROCESSED_DATE,'DD-MM-YYYY'), 
        P_JIRA_NUMBER,
        P_CREATION_USER_ID,
        LV_F_BY_DAY_ROW_CNT_BEFORE,
        LV_F_BY_HOUR_ROW_CNT_BEFORE,   
        LV_F_BY_DAY_ROW_CNT_AFTER,
        LV_F_BY_HOUR_ROW_CNT_AFTER   
    );    

COMMIT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('P_BATCH_NAME '||P_BATCH_NAME );    
        DBMS_OUTPUT.PUT_LINE('P_REPROCESSED_DATE '||P_REPROCESSED_DATE); 
        DBMS_OUTPUT.PUT_LINE('P_JIRA_NUMBER '||P_JIRA_NUMBER);
        DBMS_OUTPUT.PUT_LINE('P_CREATION_USER_ID '||P_CREATION_USER_ID);
        RAISE;
END;
/

SHOW ERRORS;

CREATE OR REPLACE procedure MAXDAT.NYHIX_MFB_V2_REPROCESS_BATCH
    (
    P_REPROCESSED_ID    NUMBER, 
    P_REPROCESSED_FLAG  VARCHAR,
    P_CREATION_USER_ID  VARCHAR
    ) 
AS
-----------------------------------------------------------
    LV_BATCH_NAME           VARCHAR2(255)       := NULL;
    LV_CREATION_USER_ID     VARCHAR2 (128 Byte) := NULL;
    LV_REPROCESSED_FLAG     VARCHAR2 (1 Byte)   := NULL;
    LV_REPROCESSED_DATE     DATE                := SYSDATE;
    LV_JIRA_NUMBER          VARCHAR2 (128 Byte) := NULL;

    LV_CREATE_DT            date                := null;
    LV_MFB_V2_BI_ID         NUMBER              := NULL;

    LV_F_BY_DAY_ROW_CNT_BEFORE  NUMBER(12,0)    := 0;
    LV_F_BY_DAY_ROW_CNT_AFTER   NUMBER(12,0)    := 0;
    LV_F_BY_HOUR_ROW_CNT_BEFORE NUMBER(12,0)    := 0;
    LV_F_BY_HOUR_ROW_CNT_AFTER  NUMBER(12,0)    := 0;

-----------------------------------------------------------
BEGIN

    LV_BATCH_NAME           := NULL;
    LV_CREATION_USER_ID     := NULL;
    LV_REPROCESSED_FLAG     := NULL;
    LV_REPROCESSED_DATE     := SYSDATE;
    LV_JIRA_NUMBER          := NULL;

    LV_CREATE_DT            := null;
    LV_MFB_V2_BI_ID         := NULL;

    LV_MFB_V2_BI_ID             := 0;
    LV_F_BY_DAY_ROW_CNT_BEFORE  := 0;
    LV_F_BY_DAY_ROW_CNT_AFTER   := NULL;
    LV_F_BY_HOUR_ROW_CNT_BEFORE := 0;
    LV_F_BY_HOUR_ROW_CNT_AFTER  := NULL;
   
    SELECT 
        BATCH_NAME,
        CREATION_USER_ID,   
        REPROCESSED_FLAG, 
        nvl(REPROCESSED_DATE,to_date('1900/01/01','yyyy/mm/dd')), 
        JIRA_NUMBER
        INTO 
        LV_BATCH_NAME,
        LV_CREATION_USER_ID,   
        LV_REPROCESSED_FLAG, 
        LV_REPROCESSED_DATE, 
        LV_JIRA_NUMBER
    FROM MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH
    WHERE NYHIX_MFB_V2_REPROCESSED_ID = P_REPROCESSED_ID;
    
    SELECT CREATE_DT, MFB_V2_BI_ID 
    INTO LV_CREATE_DT, LV_MFB_V2_BI_ID
    FROM NYHIX_MFB_V2_BATCH_SUMMARY
    WHERE BATCH_NAME = LV_BATCH_NAME;

    IF NVL(P_REPROCESSED_FLAG,'N') NOT IN ('Y','N')
    THEN
        RETURN;
    END IF;    

    IF NVL(P_REPROCESSED_FLAG,'N') = 'N'
    THEN 
        LV_REPROCESSED_DATE := NULL;
    ELSIF 
        NVL(P_REPROCESSED_FLAG,'N') = 'Y'
    THEN 
        IF LV_REPROCESSED_DATE < LV_CREATE_DT
        THEN 
            LV_REPROCESSED_DATE := LV_CREATE_DT + (1/24);
        END IF;
    END IF;

    SELECT SUM(1) INTO LV_F_BY_DAY_ROW_CNT_BEFORE 
    FROM F_MFB_V2_BY_DAY
    WHERE MFB_V2_BI_ID = LV_MFB_V2_BI_ID;

    SELECT SUM(1) INTO LV_F_BY_HOUR_ROW_CNT_BEFORE 
    FROM F_MFB_V2_BY_hour
    WHERE MFB_V2_BI_ID = LV_MFB_V2_BI_ID;



    UPDATE NYHIX_MFB_V2_STATS_BATCH
    SET 
        REPROCESSED_FLAG = P_REPROCESSED_FLAG, 
        REPROCESSED_DATE = LV_REPROCESSED_DATE
    WHERE BATCH_NAME = LV_BATCH_NAME;         

    COMMIT;

    --------------------------------------------------------------------
    -- call the package for the specific batch_name
    IF NVL(P_REPROCESSED_FLAG,'N') IN ('Y','N')
    THEN
        NYHIX_MFB_V2_BATCH_SUMMARY_PKG.Load_BATCH_SUMMARY(LV_BATCH_NAME);
    END IF;    
    --------------------------------------------------------------------

    SELECT SUM(1) INTO LV_F_BY_DAY_ROW_CNT_AFTER 
    FROM F_MFB_V2_BY_DAY
    WHERE MFB_V2_BI_ID = LV_MFB_V2_BI_ID;

    SELECT SUM(1) INTO LV_F_BY_HOUR_ROW_CNT_AFTER 
    FROM F_MFB_V2_BY_hour
    WHERE MFB_V2_BI_ID = LV_MFB_V2_BI_ID;


    UPDATE MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH
    SET 
        REPROCESSING_COMPLETED_DATE = SYSDATE,
        CREATION_USER_ID            = P_CREATION_USER_ID, 
        F_BY_DAY_ROW_CNT_BEFORE     = LV_F_BY_DAY_ROW_CNT_BEFORE,
        F_BY_DAY_ROW_CNT_AFTER      = LV_F_BY_DAY_ROW_CNT_AFTER,
        F_BY_HOUR_ROW_CNT_BEFORE    = LV_F_BY_HOUR_ROW_CNT_BEFORE,
        F_BY_HOUR_ROW_CNT_AFTER     = LV_F_BY_HOUR_ROW_CNT_AFTER        
    WHERE  NYHIX_MFB_V2_REPROCESSED_ID = P_REPROCESSED_ID;

COMMIT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
    WHEN OTHERS THEN RAISE;
END;
/

SHOW ERRORS;

CREATE OR REPLACE FORCE VIEW MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH_SV
(NYHIX_MFB_V2_REPROCESSED_ID, MFB_V2_CREATE_DATE, MFB_V2_UPDATE_DATE, BATCH_NAME, CREATION_USER_ID, 
 REPROCESSING_COMPLETED_DATE, REPROCESSED_FLAG_STG, REPROCESSED_DATE_STG, F_BY_DAY_ROW_CNT_BEFORE, F_BY_DAY_ROW_CNT_AFTER, 
 F_BY_HOUR_ROW_CNT_BEFORE, F_BY_HOUR_ROW_CNT_AFTER, JIRA_NUMBER, BATCH_GUID, EXTERNAL_BATCH_ID, 
 BATCH_DESCRIPTION, BATCH_CLASS, BATCH_TYPE, INSTANCE_STATUS, REPROCESSED_FLAG, 
 REPROCESSED_DATE, CREATE_DT, BATCH_COMPLETE_DT, CANCEL_DT, CANCEL_BY, 
 CANCEL_REASON, CANCEL_METHOD, COMPLETE_DT)
BEQUEATH DEFINER
AS 
SELECT RP.NYHIX_MFB_V2_REPROCESSED_ID,
           RP.MFB_V2_CREATE_DATE,
           RP.MFB_V2_UPDATE_DATE,
           RP.BATCH_NAME,
           RP.CREATION_USER_ID,
           RP.REPROCESSING_COMPLETED_DATE,
           CASE WHEN RP.REPROCESSING_COMPLETED_DATE IS NULL 
            THEN '?' ELSE B.REPROCESSED_FLAG END     AS REPROCESSED_FLAG_STG,
           B.REPROCESSED_DATE     AS REPROCESSED_DATE_STG,
           RP.F_BY_DAY_ROW_CNT_BEFORE,
           RP.F_BY_DAY_ROW_CNT_AFTER,
           RP.F_BY_HOUR_ROW_CNT_BEFORE,
           RP.F_BY_HOUR_ROW_CNT_AFTER,
           RP.JIRA_NUMBER,
           B.BATCH_GUID,
           B.EXTERNAL_BATCH_ID,
           B.BATCH_DESCRIPTION,
           B.BATCH_CLASS,
           B.BATCH_TYPE,
           B.INSTANCE_STATUS,
           B.REPROCESSED_FLAG,
           B.REPROCESSED_DATE,
           B.CREATE_DT,
           B.BATCH_COMPLETE_DT,
           B.CANCEL_DT,
           B.CANCEL_BY,
           B.CANCEL_REASON,
           B.CANCEL_METHOD,
           B.COMPLETE_DT
      FROM MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH  RP
           LEFT JOIN MAXDAT.NYHIX_MFB_V2_BATCH_SUMMARY B
               ON B.BATCH_NAME = RP.BATCH_NAME
               ORDER BY NYHIX_MFB_V2_REPROCESSED_ID desc;

CREATE OR REPLACE FORCE VIEW MAXDAT.NYHIX_MFB_V2_REPROCESS_STG
(NYHIX_MFB_V2_REPROCESSED_ID, MFB_V2_CREATE_DATE, MFB_V2_UPDATE_DATE, BATCH_NAME, CREATION_USER_ID, 
 REPROCESSED_FLAG, REPROCESSED_DATE, JIRA_NUMBER, REPROCESSING_COMPLETED_DATE)
BEQUEATH DEFINER
AS 
select "NYHIX_MFB_V2_REPROCESSED_ID","MFB_V2_CREATE_DATE","MFB_V2_UPDATE_DATE","BATCH_NAME","CREATION_USER_ID","REPROCESSED_FLAG","REPROCESSED_DATE","JIRA_NUMBER","REPROCESSING_COMPLETED_DATE" from MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH;

CREATE OR REPLACE TRIGGER MAXDAT.TRG_BIU_NYHIX_MFB_V2_REPROCESSED_BATCH
before insert or update ON MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH
for each row
begin
  if inserting then
    :new.MFB_V2_CREATE_DATE := sysdate;
    :new.NYHIX_MFB_V2_REPROCESSED_ID := SEQ_NYHIX_MFB_V2_REPROCESSED_ID.nextval;
  end if;
  
  :new.MFB_V2_UPDATE_DATE := sysdate;
  
  if updating then
    :new.MFB_V2_UPDATE_DATE := sysdate;
    :new.MFB_V2_create_DATE := :old.MFB_V2_create_DATE;
  end if;
end;
/
SHOW ERRORS;

GRANT EXECUTE ON MAXDAT.NYHIX_MFB_V2_INSERT_REPROCESS_STAGE TO MAXDAT_MSTR_TRX_RPT;

GRANT DELETE, INSERT, SELECT, UPDATE ON MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH TO MAXDAT_MSTR_TRX_RPT;

GRANT INSERT, SELECT, UPDATE ON MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH_SV TO MAXDAT_MSTR_TRX_RPT;

GRANT EXECUTE ON MAXDAT.NYHIX_MFB_V2_REPROCESS_BATCH TO MAXDAT_MSTR_TRX_RPT;

GRANT INSERT, SELECT, UPDATE ON MAXDAT.NYHIX_MFB_V2_REPROCESS_STG TO MAXDAT_MSTR_TRX_RPT;

GRANT INSERT, SELECT, UPDATE ON MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH TO MAXDAT_OLTP_SIU;

GRANT INSERT, SELECT, UPDATE ON MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH_SV TO MAXDAT_OLTP_SIU;

GRANT INSERT, SELECT, UPDATE ON MAXDAT.NYHIX_MFB_V2_REPROCESS_STG TO MAXDAT_OLTP_SIU;

GRANT SELECT ON MAXDAT.SEQ_NYHIX_MFB_V2_REPROCESSED_ID TO MAXDAT_OLTP_SIU;

GRANT DELETE, INSERT, SELECT, UPDATE ON MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH TO MAXDAT_OLTP_SIUD;

GRANT DELETE, INSERT, SELECT, UPDATE ON MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH_SV TO MAXDAT_OLTP_SIUD;

GRANT DELETE, INSERT, SELECT, UPDATE ON MAXDAT.NYHIX_MFB_V2_REPROCESS_STG TO MAXDAT_OLTP_SIUD;

GRANT SELECT ON MAXDAT.SEQ_NYHIX_MFB_V2_REPROCESSED_ID TO MAXDAT_OLTP_SIUD;

GRANT EXECUTE ON MAXDAT.NYHIX_MFB_V2_BATCH_REPROCESS TO MAXDAT_PFP_E;

GRANT EXECUTE ON MAXDAT.NYHIX_MFB_V2_BATCH_REPROCESS_PKG TO MAXDAT_PFP_E;

GRANT EXECUTE ON MAXDAT.NYHIX_MFB_V2_F_BY_DAY_PKG TO MAXDAT_PFP_E;

GRANT EXECUTE ON MAXDAT.NYHIX_MFB_V2_INSERT_REPROCESS_STAGE TO MAXDAT_PFP_E;

GRANT EXECUTE ON MAXDAT.NYHIX_MFB_V2_REPROCESS_BATCH TO MAXDAT_PFP_E;

GRANT EXECUTE ON MAXDAT.NYHIX_MFB_V2_RUN_PACKAGES TO MAXDAT_PFP_E;

GRANT DEBUG ON MAXDAT.NYHIX_MFB_V2_BATCH_REPROCESS TO MAXDAT_PFP_READ_ONLY;

GRANT DEBUG ON MAXDAT.NYHIX_MFB_V2_BATCH_REPROCESS_PKG TO MAXDAT_PFP_READ_ONLY;

GRANT DEBUG ON MAXDAT.NYHIX_MFB_V2_F_BY_DAY_PKG TO MAXDAT_PFP_READ_ONLY;

GRANT DEBUG ON MAXDAT.NYHIX_MFB_V2_INSERT_REPROCESS_STAGE TO MAXDAT_PFP_READ_ONLY;

GRANT DEBUG ON MAXDAT.NYHIX_MFB_V2_REPROCESS_BATCH TO MAXDAT_PFP_READ_ONLY;

GRANT DEBUG ON MAXDAT.NYHIX_MFB_V2_RUN_PACKAGES TO MAXDAT_PFP_READ_ONLY;

GRANT SELECT ON MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH TO MAXDAT_READ_ONLY;

GRANT SELECT ON MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH_SV TO MAXDAT_READ_ONLY;

GRANT SELECT ON MAXDAT.NYHIX_MFB_V2_REPROCESS_STG TO MAXDAT_READ_ONLY;

GRANT EXECUTE ON MAXDAT.NYHIX_MFB_V2_INSERT_REPROCESS_STAGE TO MAXDAT_REPORTS;

GRANT INSERT, SELECT, UPDATE ON MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH_SV TO MAXDAT_REPORTS;

GRANT EXECUTE ON MAXDAT.NYHIX_MFB_V2_REPROCESS_BATCH TO MAXDAT_REPORTS;

GRANT INSERT, SELECT, UPDATE ON MAXDAT.NYHIX_MFB_V2_REPROCESS_STG TO MAXDAT_REPORTS;

GRANT SELECT ON MAXDAT.NYHIX_MFB_V2_BATCH_SUMMARY TO RO38606;

GRANT EXECUTE ON MAXDAT.NYHIX_MFB_V2_INSERT_REPROCESS_STAGE TO RO38606;

GRANT DELETE, INSERT, SELECT, UPDATE ON MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH TO RO38606;

GRANT INSERT, SELECT, UPDATE ON MAXDAT.NYHIX_MFB_V2_REPROCESSED_BATCH_SV TO RO38606;

GRANT EXECUTE ON MAXDAT.NYHIX_MFB_V2_REPROCESS_BATCH TO RO38606;

GRANT INSERT, SELECT, UPDATE ON MAXDAT.NYHIX_MFB_V2_REPROCESS_STG TO RO38606;

GRANT SELECT ON MAXDAT.NYHIX_MFB_V2_STATS_BATCH TO RO38606;