truncate table BPM_D_OPS_GROUP_TASK;
truncate table CORP_ETL_LIST_LKUP;


INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Call Center', 'Complaint Follow-up Required Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Call Center', 'Complaint Sent in Error Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Call Center', 'Complaints Follow Up');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Call Center', 'NYHBE Complaints');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Call Center', 'Nyhbe Referral Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Call Center', 'Referral Follow-up Required Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Call Center', 'Referral Sent in Error Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Call Center', 'Supervisor Complaint Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Call Center', 'Supervisor Complaints VHT');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Call Center', 'Supervisor Referral Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Appeal Validity Check');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'DOH Good Cause Review');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Decision Overturned');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Hearing Set - Disposition Review Needed');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Hearing Set - No Disposition Review');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Personal Injury Form Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Refer to State-Appeals');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Refer to State-Application Support');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Refer to State-CHP');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Refer to State-Financial Management');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Refer to State-MA/FHP');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Refer to State-Managed Care');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Refer to State-Research');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Refer to State-SHOP');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Refer to State-TPHI');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Refer to State-Transition');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Remand');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Request to Vacate Dismissal');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'Retro Coverage Documentation');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'SHOP Desk Review');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'State Complaints');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'State Supervisory Review-Appeals');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'State Supervisory Review-Application Support');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'State Supervisory Review-CHP');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'State Supervisory Review-Financial Management');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'State Supervisory Review-MA/FHP');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'State Supervisory Review-Managed Care');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'State Supervisory Review-SHOP');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'State Supervisory Review-TPHI');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('DOH', 'TPHI Manual Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Data Entry', 'DPR - SHOP Employee Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Data Entry', 'DPR - SHOP Employer Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Data Entry', 'Data Entry Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Data Entry', 'Data Entry-SHOP Employee Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Data Entry', 'Data Entry-SHOP Employer Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility A', 'HSDE-QC VHT');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility A', 'Link Document Set');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility B', 'DOH Absent Parent');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility B', 'DOH Good Cause');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility B', 'Data Entry-Verification Document Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility B', 'Newborn Request');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'APPEAL');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Awaiting Documentation');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Awaiting Validity Amendment - Individual');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Awaiting Validity Amendment - SHOP');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Awaiting Written Withdrawal');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Cancel Hearing');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'DERT-Existing Appeal');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Dismissal - Failed to Attend Hearing');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Document-Account Review');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Evidence Packet Correction Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Expired Clock Document');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Incident Open');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Refer to ES-C');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Refer to ES-C Supervisor');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Refer to NY Appeals');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Refer to NY Appeals Unit Supervisor');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Reschedule Hearing - Appellant Request');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Reschedule Hearing - DOH Request');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Eligibility C', 'Schedule Hearing');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Exception', 'CSC Payload Review');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Exception', 'Manual Human Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Exception', 'Manual Linking');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Exception', 'Manual Task - General');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('QC', 'Link Doc Set QC Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('QC', 'NYHBE MAXIMUS QC Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DERT-Authorized Representative');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DERT-Other');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DPR - Account Correction');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DPR - Appeals');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DPR - Application in Process');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DPR - Application-Missing Data');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DPR - Authorized Representative');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DPR - Complaint');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DPR - Doc/Form Type Mismatch Task ');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DPR - Existing Appeal');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DPR - FM Returned Mail');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DPR - Financial Management');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DPR - Free Form Follow-Up');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DPR - Multiple Applications');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DPR - Orphan Document');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DPR - Other');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DPR - Returned Mail Application');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'DPR - Wrong Program');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'Data Entry Research-Account Correction');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'Document Problem Resolution');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'Incarceration Proof');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'Large Font Notice Request');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'Letter Resend Request');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'NYHBE Verification Doc DERT-Account Correction');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'NYHBE Verification Doc DERT-Other');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'NYHBE Verification Doc Research Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'Re-verification Manual Task');
INSERT INTO BPM_D_OPS_GROUP_TASK (OPS_GROUP, TASK_TYPE) VALUES ('Research', 'Relink Request');



INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DOH Good Cause'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 20137018
    , to_date ('2015-09-08', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2015-09-09 12:32:46', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2015-09-09 12:32:46', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DOH Absent Parent'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 20137023
    , to_date ('2015-09-08', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2015-09-09 12:32:46', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2015-09-09 12:32:46', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Newborn Request'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 20137030
    , to_date ('2015-09-08', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2015-09-09 12:32:46', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2015-09-09 12:32:46', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DERT-Existing Appeal'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013051
    , to_date ('2014-09-04', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-09-05 11:39:25', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-09-05 11:39:25', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DPR - Authorized Representative'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013053
    , to_date ('2014-09-04', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-09-05 11:39:26', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-09-05 11:39:26', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DERT-Authorized Representative'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013054
    , to_date ('2014-09-04', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-09-05 11:39:26', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-09-05 11:39:26', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Incarceration Proof'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2016254
    , to_date ('2014-09-04', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-09-05 11:39:27', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-11-19 12:03:41', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Large Font Notice Request'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2016236
    , to_date ('2014-06-26', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-06-27 11:40:05', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-06-27 11:40:05', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Expired Clock Document'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 20137008
    , to_date ('2014-12-15', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-12-16 11:56:02', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-12-16 11:56:02', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
      CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Document Problem Resolution'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 3003
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:20', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Link Document Set'
    , '0'
    , 'STEP_DEFINITION_ID'
    , 3005
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:21', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'NYHBE Complaints'
    , '10'
    , 'STEP_DEFINITION_ID'
    , 30049
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Complaints Follow Up'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 30050
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Supervisor Complaints VHT'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 30053
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Supervisor Referral Task'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 31053
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Supervisor Complaint Task'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 31054
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'HSDE-QC VHT'
    , '0'
    , 'STEP_DEFINITION_ID'
    , 32282
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:21', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DPR - Complaint'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013010
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:22', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DPR - Account Correction'
    , '1'
    , 'STEP_DEFINITION_ID'
    , 2013011
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:23', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DPR - Wrong Program'
    , '1'
    , 'STEP_DEFINITION_ID'
    , 2013012
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DPR - Orphan Document'
    , '15'
    , 'STEP_DEFINITION_ID'
    , 2013013
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:24', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DPR - Free Form Follow-Up'
    , '1'
    , 'STEP_DEFINITION_ID'
    , 2013014
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:25', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Link Doc Set QC Task'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013015
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Data Entry Task'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2013018
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Data Entry-Verification Document Task'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2013019
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Data Entry-SHOP Employer Task'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2013020
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Data Entry-SHOP Employee Task'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2013021
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'NYHBE MAXIMUS QC Task'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013022
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DPR - SHOP Employer Task'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013023
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DPR - SHOP Employee Task'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013024
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'NYHBE Verification Doc Research Task'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2013025
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DPR - Multiple Applications'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013026
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DPR - Other'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013027
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DPR - Doc/Form Type Mismatch Task '
    , '1'
    , 'STEP_DEFINITION_ID'
    , 2013028
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:26', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DPR - Appeals'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013029
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Refer to State-Appeals'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2013030
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Refer to State-Application Support'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2013031
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Refer to State-CHP'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2013032
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Refer to State-Financial Management'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2013033
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Refer to State-Managed Care'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2013034
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Refer to State-MA/FHP'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2013035
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Refer to State-SHOP'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2013036
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Refer to State-TPHI'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2013037
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'State Supervisory Review-Appeals'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013038
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'State Supervisory Review-Application Support'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013039
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'State Supervisory Review-CHP'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013040
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'State Supervisory Review-Financial Management'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013041
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'State Supervisory Review-Managed Care'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013042
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'State Supervisory Review-MA/FHP'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013043
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'State Supervisory Review-SHOP'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013044
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'State Supervisory Review-TPHI'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013045
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'APPEAL'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2015000
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Incident Open'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2015001
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Incident Open2'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2015002
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Refer to ES-C'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2015003
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Refer to ES-C2'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2015004
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Refer to ES-C Supervisor'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2015005
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Refer to ES-C Supervisor2'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2015006
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Hearing Set - Disposition Review Needed'
    , '10'
    , 'STEP_DEFINITION_ID'
    , 2015008
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Refer to NY Appeals Unit Supervisor'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2015009
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Schedule Hearing'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2015010
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Reschedule Hearing - DOH Request'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2015011
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Reschedule Hearing - Appellant Request'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2015012
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Cancel Hearing'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2015013
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Appeal Validity Check'
    , '10'
    , 'STEP_DEFINITION_ID'
    , 2015014
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Dismissal - Failed to Attend Hearing'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2015015
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Request to Vacate Dismissal'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2015018
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Remand'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2015019
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Decision Overturned'
    , '10'
    , 'STEP_DEFINITION_ID'
    , 2015020
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'SHOP Desk Review'
    , '10'
    , 'STEP_DEFINITION_ID'
    , 2015023
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Re-verification Manual Task'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2013450
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:18', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:18', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Relink Request'
    , '0'
    , 'STEP_DEFINITION_ID'
    , 2016156
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:18', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:18', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'Personal Injury Form Task'
    , NULL
    , 'STEP_DEFINITION_ID'
    , 2016214
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:20', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-11-19 12:03:40', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'NYHBE Verification Doc DERT-Other'
    , '5'
    , 'STEP_DEFINITION_ID'
    , 2013052
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:28', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:28', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DPR - Financial Management'
    , '15'
    , 'STEP_DEFINITION_ID'
    , 2013400
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:29', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:29', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DPR - Returned Mail Application'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013420
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:31', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:31', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days'
    , 'TASK_TYPE'
    , 'DPR - Application-Missing Data'
    , '25'
    , 'STEP_DEFINITION_ID'
    , 2013058
    , to_date ('2014-09-17', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-09-18 16:33:58', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-09-18 16:33:58', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DOH Good Cause'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 20137018
    , to_date ('2015-09-08', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2015-09-09 12:32:40', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2015-09-09 12:32:40', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DOH Absent Parent'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 20137023
    , to_date ('2015-09-08', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2015-09-09 12:32:40', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2015-09-09 12:32:40', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Newborn Request'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 20137030
    , to_date ('2015-09-08', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2015-09-09 12:32:40', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2015-09-09 12:32:40', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DERT-Existing Appeal'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013051
    , to_date ('2014-09-04', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-09-05 11:39:25', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-09-05 11:39:25', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DPR - Authorized Representative'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013053
    , to_date ('2014-09-04', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-09-05 11:39:26', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-09-05 11:39:26', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DERT-Authorized Representative'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013054
    , to_date ('2014-09-04', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-09-05 11:39:26', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-09-05 11:39:26', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Incarceration Proof'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2016254
    , to_date ('2014-09-04', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-09-05 11:39:27', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-11-19 12:03:41', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Large Font Notice Request'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2016236
    , to_date ('2014-06-26', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-06-27 11:40:04', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-06-27 11:40:04', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Expired Clock Document'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 20137008
    , to_date ('2014-12-15', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-12-16 11:56:02', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-12-16 11:56:02', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Document Problem Resolution'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 3003
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Link Document Set'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 3005
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'NYHBE Complaints'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 30049
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Complaints Follow Up'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 30050
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Supervisor Complaints VHT'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 30053
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Supervisor Referral Task'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 31053
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Supervisor Complaint Task'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 31054
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'HSDE-QC VHT'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 32282
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DPR - Complaint'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013010
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DPR - Account Correction'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013011
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DPR - Wrong Program'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013012
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DPR - Orphan Document'
    , 'C'
    , 'STEP_DEFINITION_ID'
    , 2013013
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:24', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DPR - Free Form Follow-Up'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013014
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Link Doc Set QC Task'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013015
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Data Entry Task'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013018
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Data Entry-Verification Document Task'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013019
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Data Entry-SHOP Employer Task'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013020
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Data Entry-SHOP Employee Task'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013021
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'NYHBE MAXIMUS QC Task'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013022
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DPR - SHOP Employer Task'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013023
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DPR - SHOP Employee Task'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013024
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'NYHBE Verification Doc Research Task'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013025
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DPR - Multiple Applications'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013026
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DPR - Other'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013027
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DPR - Doc/Form Type Mismatch Task '
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013028
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DPR - Appeals'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013029
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Refer to State-Appeals'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013030
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Refer to State-Application Support'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013031
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Refer to State-CHP'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013032
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Refer to State-Financial Management'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013033
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Refer to State-Managed Care'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013034
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Refer to State-MA/FHP'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013035
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Refer to State-SHOP'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013036
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Refer to State-TPHI'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013037
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'State Supervisory Review-Appeals'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013038
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'State Supervisory Review-Application Support'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013039
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'State Supervisory Review-CHP'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013040
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'State Supervisory Review-Financial Management'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013041
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'State Supervisory Review-Managed Care'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013042
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'State Supervisory Review-MA/FHP'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013043
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'State Supervisory Review-SHOP'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013044
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'State Supervisory Review-TPHI'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013045
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'APPEAL'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015000
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Incident Open'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015001
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Incident Open2'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015002
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Refer to ES-C'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015003
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Refer to ES-C2'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015004
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Refer to ES-C Supervisor'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015005
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Refer to ES-C Supervisor2'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015006
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Hearing Set - Disposition Review Needed'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015008
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Refer to NY Appeals Unit Supervisor'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015009
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Schedule Hearing'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015010
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Reschedule Hearing - DOH Request'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015011
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Reschedule Hearing - Appellant Request'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015012
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Cancel Hearing'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015013
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Appeal Validity Check'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015014
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Dismissal - Failed to Attend Hearing'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015015
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Request to Vacate Dismissal'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015018
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Remand'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015019
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Decision Overturned'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015020
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'SHOP Desk Review'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2015023
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Re-verification Manual Task'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013450
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:17', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:17', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Relink Request'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2016156
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:18', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:18', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'Personal Injury Form Task'
    , NULL
    , 'STEP_DEFINITION_ID'
    , 2016214
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:19', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-11-19 12:03:40', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'NYHBE Verification Doc DERT-Other'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013052
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:27', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:27', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DPR - Financial Management'
    , 'C'
    , 'STEP_DEFINITION_ID'
    , 2013400
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:29', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:29', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DPR - Returned Mail Application'
    , 'B'
    , 'STEP_DEFINITION_ID'
    , 2013420
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:30', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:30', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Days_Type'
    , 'TASK_TYPE'
    , 'DPR - Application-Missing Data'
    , 'C'
    , 'STEP_DEFINITION_ID'
    , 2013058
    , to_date ('2014-09-17', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-09-18 16:33:58', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-09-18 16:33:58', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DOH Good Cause'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 20137018
    , to_date ('2015-09-08', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2015-09-09 12:33:15', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2015-09-09 12:33:15', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DOH Absent Parent'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 20137023
    , to_date ('2015-09-08', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2015-09-09 12:33:15', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2015-09-09 12:33:15', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Newborn Request'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 20137030
    , to_date ('2015-09-08', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2015-09-09 12:33:15', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2015-09-09 12:33:15', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DERT-Existing Appeal'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013051
    , to_date ('2014-09-04', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-09-05 11:39:26', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-09-05 11:39:26', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DPR - Authorized Representative'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013053
    , to_date ('2014-09-04', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-09-05 11:39:26', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-09-05 11:39:26', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DERT-Authorized Representative'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013054
    , to_date ('2014-09-04', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-09-05 11:39:26', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-09-05 11:39:26', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Incarceration Proof'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2016254
    , to_date ('2014-09-04', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-09-05 11:39:27', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-11-19 12:03:41', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Large Font Notice Request'
    , '1'
    , 'STEP_DEFINITION_ID'
    , 2016236
    , to_date ('2014-06-26', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-06-27 11:40:05', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-06-27 11:40:05', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Expired Clock Document'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 20137008
    , to_date ('2014-12-15', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-12-16 11:56:02', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-12-16 11:56:02', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Document Problem Resolution'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 3003
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:21', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Link Document Set'
    , '1'
    , 'STEP_DEFINITION_ID'
    , 3005
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'NYHBE Complaints'
    , '7'
    , 'STEP_DEFINITION_ID'
    , 30049
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Complaints Follow Up'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 30050
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Supervisor Complaints VHT'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 30053
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Supervisor Referral Task'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 31053
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Supervisor Complaint Task'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 31054
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'HSDE-QC VHT'
    , '1'
    , 'STEP_DEFINITION_ID'
    , 32282
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DPR - Complaint'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013010
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:22', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DPR - Account Correction'
    , '1'
    , 'STEP_DEFINITION_ID'
    , 2013011
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DPR - Wrong Program'
    , '1'
    , 'STEP_DEFINITION_ID'
    , 2013012
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DPR - Orphan Document'
    , '12'
    , 'STEP_DEFINITION_ID'
    , 2013013
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:25', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DPR - Free Form Follow-Up'
    , '1'
    , 'STEP_DEFINITION_ID'
    , 2013014
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Link Doc Set QC Task'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013015
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Data Entry Task'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013018
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Data Entry-Verification Document Task'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013019
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Data Entry-SHOP Employer Task'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013020
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Data Entry-SHOP Employee Task'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013021
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'NYHBE MAXIMUS QC Task'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013022
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DPR - SHOP Employer Task'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013023
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DPR - SHOP Employee Task'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013024
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'NYHBE Verification Doc Research Task'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013025
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DPR - Multiple Applications'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013026
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DPR - Other'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013027
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DPR - Doc/Form Type Mismatch Task '
    , '1'
    , 'STEP_DEFINITION_ID'
    , 2013028
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:26', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DPR - Appeals'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013029
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Refer to State-Appeals'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013030
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Refer to State-Application Support'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013031
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Refer to State-CHP'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013032
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Refer to State-Financial Management'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013033
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Refer to State-Managed Care'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013034
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Refer to State-MA/FHP'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013035
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Refer to State-SHOP'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013036
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Refer to State-TPHI'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013037
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'State Supervisory Review-Appeals'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013038
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'State Supervisory Review-Application Support'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013039
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'State Supervisory Review-CHP'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013040
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'State Supervisory Review-Financial Management'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013041
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'State Supervisory Review-Managed Care'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013042
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'State Supervisory Review-MA/FHP'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013043
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'State Supervisory Review-SHOP'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013044
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'State Supervisory Review-TPHI'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2013045
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'APPEAL'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2015000
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Incident Open'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2015001
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Incident Open2'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2015002
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Refer to ES-C'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2015003
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Refer to ES-C2'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2015004
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Refer to ES-C Supervisor'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2015005
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Refer to ES-C Supervisor2'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2015006
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Hearing Set - Disposition Review Needed'
    , '7'
    , 'STEP_DEFINITION_ID'
    , 2015008
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Refer to NY Appeals Unit Supervisor'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2015009
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Schedule Hearing'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2015010
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Reschedule Hearing - DOH Request'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2015011
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Reschedule Hearing - Appellant Request'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2015012
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Cancel Hearing'
    , '2'
    , 'STEP_DEFINITION_ID'
    , 2015013
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Appeal Validity Check'
    , '7'
    , 'STEP_DEFINITION_ID'
    , 2015014
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Dismissal - Failed to Attend Hearing'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2015015
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Request to Vacate Dismissal'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2015018
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Remand'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2015019
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Decision Overturned'
    , '7'
    , 'STEP_DEFINITION_ID'
    , 2015020
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'SHOP Desk Review'
    , '7'
    , 'STEP_DEFINITION_ID'
    , 2015023
    , to_date ('2013-11-14', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2013-11-15 12:43:59', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Re-verification Manual Task'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013450
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:18', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:18', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'Relink Request'
    , '1'
    , 'STEP_DEFINITION_ID'
    , 2016156
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:19', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:19', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'NYHBE Verification Doc DERT-Other'
    , '3'
    , 'STEP_DEFINITION_ID'
    , 2013052
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:28', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:28', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DPR - Financial Management'
    , '12'
    , 'STEP_DEFINITION_ID'
    , 2013400
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:30', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:30', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DPR - Returned Mail Application'
    , '1'
    , 'STEP_DEFINITION_ID'
    , 2013420
    , to_date ('2014-08-13', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-08-14 11:30:31', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-08-14 11:30:32', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Jeopardy_Days'
    , 'TASK_TYPE'
    , 'DPR - Application-Missing Data'
    , '21'
    , 'STEP_DEFINITION_ID'
    , 2013058
    , to_date ('2014-09-17', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2014-09-18 16:33:58', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-09-18 16:33:58', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Target_Days'
    , 'TASK_TYPE'
    , 'DOH Good Cause'
    , NULL
    , 'STEP_DEFINITION_ID'
    , 20137018
    , to_date ('2015-09-08', 'YYYY-MM-DD')
    , to_date ('0777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2015-09-09 12:33:18', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2015-09-09 12:33:18', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Target_Days'
    , 'TASK_TYPE'
    , 'DOH Absent Parent'
    , NULL
    , 'STEP_DEFINITION_ID'
    , 20137023
    , to_date ('2015-09-08', 'YYYY-MM-DD')
    , to_date ('0777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2015-09-09 12:33:18', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2015-09-09 12:33:18', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'ManageWork_SLA_Target_Days'
    , 'TASK_TYPE'
    , 'Newborn Request'
    , NULL
    , 'STEP_DEFINITION_ID'
    , 20137030
    , to_date ('2015-09-08', 'YYYY-MM-DD')
    , to_date ('0777-07-07', 'YYYY-MM-DD')
    , 'Initial Load'
    , to_date ('2015-09-09 12:33:18', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2015-09-09 12:33:18', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'MW_V2_ADD_TO_WHERE_CLAUSE'
    , 'MW_V2_LIST'
    , 'AND clause for the INSERT statement'
    , NULL
    , NULL
    , NULL
    , to_date ('2014-11-12', 'YYYY-MM-DD')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , NULL
    , to_date ('2014-11-12 19:24:13', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-11-21 20:06:11', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'MW_TASK_STATUS_ORDER'
    , 'ORDER'
    , 'UNCLAIMED'
    , '10'
    , NULL
    , NULL
    , to_date ('2014-01-23 14:53:33', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'OLTP creates instance history out of order, this cardinality sets records correctly in MAXDAT. Highest value is end of instance cycle.'
    , to_date ('2014-01-23 14:53:33', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-01-23 14:53:33', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'MW_TASK_STATUS_ORDER'
    , 'ORDER'
    , 'CLAIMED'
    , '20'
    , NULL
    , NULL
    , to_date ('2014-01-23 14:53:33', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'OLTP creates instance history out of order, this cardinality sets records correctly in MAXDAT. Highest value is end of instance cycle.'
    , to_date ('2014-01-23 14:53:34', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-01-23 14:53:34', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'MW_TASK_STATUS_ORDER'
    , 'ORDER'
    , 'INPROCESS'
    , '30'
    , NULL
    , NULL
    , to_date ('2014-01-23 14:53:33', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'OLTP creates instance history out of order, this cardinality sets records correctly in MAXDAT. Highest value is end of instance cycle.'
    , to_date ('2014-01-23 14:53:34', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-01-23 14:53:34', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'MW_TASK_STATUS_ORDER'
    , 'ORDER'
    , 'SUSPENDED'
    , '40'
    , NULL
    , NULL
    , to_date ('2014-01-23 14:53:33', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'OLTP creates instance history out of order, this cardinality sets records correctly in MAXDAT. Highest value is end of instance cycle.'
    , to_date ('2014-01-23 14:53:34', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-01-23 14:53:34', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'MW_TASK_STATUS_ORDER'
    , 'ORDER'
    , 'TERMINATED'
    , '50'
    , NULL
    , NULL
    , to_date ('2014-01-23 14:53:33', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'OLTP creates instance history out of order, this cardinality sets records correctly in MAXDAT. Highest value is end of instance cycle.'
    , to_date ('2014-01-23 14:53:34', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-01-23 14:53:34', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'MW_TASK_STATUS_ORDER'
    , 'ORDER'
    , 'VOIDED'
    , '80'
    , NULL
    , NULL
    , to_date ('2014-01-23 14:53:33', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'OLTP creates instance history out of order, this cardinality sets records correctly in MAXDAT. Highest value is end of instance cycle.'
    , to_date ('2014-01-23 14:53:34', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-01-23 14:53:34', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'MW_TASK_STATUS_ORDER'
    , 'ORDER'
    , 'TIMEOUT'
    , '60'
    , NULL
    , NULL
    , to_date ('2014-01-23 14:53:33', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'OLTP creates instance history out of order, this cardinality sets records correctly in MAXDAT. Highest value is end of instance cycle.'
    , to_date ('2014-01-23 14:53:34', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-01-23 14:53:34', 'YYYY-MM-DD HH24:MI:SS')
    );

INSERT INTO CORP_ETL_LIST_LKUP
    (
    CELL_ID
    , NAME
    , LIST_TYPE
    , VALUE
    , OUT_VAR
    , REF_TYPE
    , REF_ID
    , START_DATE
    , END_DATE
    , COMMENTS
    , CREATED_TS
    , UPDATED_TS
    )
VALUES
    (
    SEQ_CELL_ID.NEXTVAL
    , 'MW_TASK_STATUS_ORDER'
    , 'ORDER'
    , 'COMPLETED'
    , '100'
    , NULL
    , NULL
    , to_date ('2014-01-23 14:53:33', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('7777-07-07', 'YYYY-MM-DD')
    , 'OLTP creates instance history out of order, this cardinality sets records correctly in MAXDAT. Highest value is end of instance cycle.'
    , to_date ('2014-01-23 14:53:34', 'YYYY-MM-DD HH24:MI:SS')
    , to_date ('2014-01-23 14:53:34', 'YYYY-MM-DD HH24:MI:SS')
    );

COMMIT;