CREATE INDEX DOC_LINK_STG_IDX03 ON DOC_LINK_STG (LINK_TYPE_CD,LINK_REF_ID)  TABLESPACE MAXDAT_INDX;

CREATE INDEX LETTER_REQ_LINK_IDX02 ON LETTER_REQUEST_LINK_STG (REFERENCE_ID,REFERENCE_TYPE) TABLESPACE MAXDAT_INDX;