CREATE TABLE AID_CATEGORY_LKUP
(VALUE	VARCHAR2(32 BYTE)
,DESCRIPTION	VARCHAR2(256 BYTE)
,REPORT_LABEL	VARCHAR2(64 BYTE)
,SCOPE	VARCHAR2(128 BYTE)
,CREATED_BY	VARCHAR2(80 BYTE)
,CREATE_TS	DATE
,UPDATED_BY	VARCHAR2(80 BYTE)
,UPDATE_TS	DATE
,ORDER_BY_DEFAULT	NUMBER(10,0)
,EFFECTIVE_START_DATE	DATE
,EFFECTIVE_END_DATE	DATE
,ADLK_GROUP_CD	VARCHAR2(2 BYTE)
,ADLK_FUND_TYPE_RANGE	VARCHAR2(5 BYTE)
,ADLK_STATUS_CD	VARCHAR2(1 BYTE)
,ADLK_CHEC_HCFA_416_REP_GRP_CD	VARCHAR2(5 BYTE)
,ADLK_PREGNANCY_CD	VARCHAR2(1 BYTE)
,DATABASE_OBJECT_NAME	VARCHAR2(40 BYTE)
,ADLK_PRIORITY	NUMBER(3,0)
,MAID_ID	NUMBER(38,0)
,ACPMGP_ID	NUMBER(38,0)
,ADLK_PTLK_ID	VARCHAR2(32 BYTE)
,SUBPROGRAM_CODES	VARCHAR2(20 BYTE)) TABLESPACE MAXDAT_DATA;

CREATE UNIQUE INDEX XPK_AID_CATEGORY_LKUP ON AID_CATEGORY_LKUP(VALUE) TABLESPACE MAXDAT_INDX;
CREATE INDEX AID_CATEGORY_LKUP_IDX1 ON AID_CATEGORY_LKUP(SUBPROGRAM_CODES) TABLESPACE MAXDAT_INDX;

GRANT SELECT ON AID_CATEGORY_LKUP to MAXDAT_READ_ONLY;

ALTER TABLE app_individual_stg
ADD (CLIENT_SELECTION_DATE DATE);

insert into CORP_ETL_CONTROL(name,VALUE_TYPE,value,DESCRIPTION,CREATED_TS,UPDATED_TS) 
values ('CASEADDR_LAST_CREATE_DATE','D',to_char(TRUNC(SYSDATE-360),'yyyy/mm/dd hh24:mi:ss'),'This is the timestamp of the address.creation_date from the previous run. creation_date of the most recent address record from the previous run.',sysdate,sysdate);

insert into CORP_ETL_CONTROL(name,VALUE_TYPE,value,DESCRIPTION,CREATED_TS,UPDATED_TS) 
values ('CASEADDR_LAST_UPDATE_DATE','D',to_char(TRUNC(SYSDATE-360),'yyyy/mm/dd hh24:mi:ss'),'This is the timestamp of the address.last_update_date from the previous run. last_update_date of the most recent address record from the previous run.',sysdate,sysdate);

commit;