ALTER TABLE app_individual_stg
ADD (supplemental_nbr VARCHAR2(32));

CREATE TABLE ETL_E_DAILY_ACCENT_STAGING_STG
(ETL_E_DAILY_ACCENT_STAGING_ID	NUMBER(18,0),
APPLICATION_ID	NUMBER(18,0),
CREATE_TS	DATE,
PROCESS_TS	DATE,
PROCESS_IND	NUMBER(1,0),
TRANSACTION_CD	VARCHAR2(1 BYTE)
CLIENT_CIN	VARCHAR2(32 BYTE),
CASE_CIN	VARCHAR2(32 BYTE),
APPLICATION_DT	DATE,
VENDOR_CASE_NO	VARCHAR2(32 BYTE),
STATUS_CD	VARCHAR2(32 BYTE),
LMREQ_ID	NUMBER(18,0)) TABLESPACE MAXDAT_DATA;

GRANT SELECT ON ETL_E_DAILY_ACCENT_STAGING_STG to MAXDAT_READ_ONLY;

CREATE INDEX ETL_E_ACCENT_APP_ID	ON ETL_E_DAILY_ACCENT_STAGING_STG(APPLICATION_ID) TABLESPACE MAXDAT_INDX;
CREATE INDEX ACCENT_STAGING_LMREQ_IDX	ON ETL_E_DAILY_ACCENT_STAGING_STG(LMREQ_ID) TABLESPACE MAXDAT_INDX;
CREATE UNIQUE INDEX ETL_E_DAILY_ACCENT_STAGING_PK	ON ETL_E_DAILY_ACCENT_STAGING_STG(ETL_E_DAILY_ACCENT_STAGING_ID) TABLESPACE MAXDAT_INDX;


insert into CORP_ETL_CONTROL(name,VALUE_TYPE,value,DESCRIPTION,CREATED_TS,UPDATED_TS) 
values ('DAILYACCENT_STG_CREATE_DATE','D',to_char(TRUNC(SYSDATE-360),'yyyy/mm/dd hh24:mi:ss'),'This is the timestamp of the etl_e_daily_accent_staging.create_ts from the previous run. create_ts of the most recent app_status_staging record from the previous run.',sysdate,sysdate);

insert into CORP_ETL_CONTROL(name,VALUE_TYPE,value,DESCRIPTION,CREATED_TS,UPDATED_TS) 
values ('DAILYACCENT_STG_PROCESS_DATE','D',to_char(TRUNC(SYSDATE-360),'yyyy/mm/dd hh24:mi:ss'),'This is the timestamp of the etl_e_daily_accent_staging.process_ts from the previous run. process_ts of the most recent app_status_staging record from the previous run.',sysdate,sysdate);

commit;