CREATE TABLE CLIENT_STG
(CLIENT_ID	NUMBER(18)
,CASE_ID NUMBER(18)
,CASE_CIN VARCHAR2(30)
,CLNT_FNAME	VARCHAR2(30)
,CLNT_LNAME	VARCHAR2(40)
,CLNT_MI	VARCHAR2(25)
,SUFFIX VARCHAR2(32)
,CLNT_GENDER_CD	VARCHAR2(32)
,CLNT_CITIZEN	VARCHAR2(32)
,CLNT_DOB	DATE
,CLNT_SSN	VARCHAR2(30)
,CLNT_CIN	VARCHAR2(30)
,CREATED_BY	VARCHAR2(80)
,CREATION_DATE	DATE
,LAST_UPDATED_BY	VARCHAR2(80)
,LAST_UPDATE_DATE	DATE
,CLNT_DISPLAY_NAME	VARCHAR2(80)
,CLIENT_TYPE_CD	VARCHAR2(10)
,SUPPLEMENTAL_NBR	VARCHAR2(32)
,CLIENT_LANGUAGE	VARCHAR2(32)
,CLNT_GENERIC_FIELD1_DATE	DATE
,CLNT_GENERIC_FIELD2_DATE	DATE
,CLNT_GENERIC_FIELD3_NUM	NUMBER(18)
,CLNT_GENERIC_FIELD4_NUM	NUMBER(18)
,CLNT_GENERIC_FIELD5_TXT	VARCHAR2(256)
,CLNT_GENERIC_FIELD6_TXT	VARCHAR2(256)
,CLNT_GENERIC_FIELD7_TXT	VARCHAR2(256)
,CLNT_GENERIC_FIELD8_TXT	VARCHAR2(256)
,CLNT_GENERIC_FIELD9_TXT	VARCHAR2(256)
,CLNT_GENERIC_FIELD10_TXT	VARCHAR2(256)
,CLNT_GENERIC_REF11_ID	NUMBER(18)
,CLNT_GENERIC_REF12_ID	NUMBER(18)) TABLESPACE MAXDAT_DATA;

CREATE INDEX IDX1_CLIENT_STG_UK ON CLIENT_STG(CLIENT_ID) TABLESPACE MAXDAT_INDX;
CREATE INDEX IDX2_CLIENT_STG ON CLIENT_STG(SUPPLEMENTAL_NBR) TABLESPACE MAXDAT_INDX;

GRANT SELECT ON CLIENT_STG to MAXDAT_READ_ONLY;

CREATE TABLE AUTHORIZED_CONTACT_STG
(AUTHORIZED_CONTACT_ID	NUMBER(18)
,AC_TYPE_CODE	VARCHAR2(32)
,AC_CASE_ID	NUMBER(18)
,AC_MAIL_PROCESS_CODE	VARCHAR2(32)
,AC_FIRST_NAME	VARCHAR2(25)
,AC_LAST_NAME	VARCHAR2(40)
,AC_ADDRESS_STREET_1	VARCHAR2(55)
,AC_ADDRESS_STREET_2	VARCHAR2(55)
,AC_ADDRESS_ATTN	VARCHAR2(55)
,AC_ADDRESS_CITY	VARCHAR2(30)
,AC_ADDRESS_STATE_CODE	VARCHAR2(20)
,AC_ADDRESS_ZIP	VARCHAR2(32)
,AC_ADDRESS_ZIP4	VARCHAR2(4)
,AC_ADDRESS_COUNTRY	VARCHAR2(20)
,AC_PHONE_AREA_CODE	VARCHAR2(3)
,AC_PHONE_NUMBER	VARCHAR2(7)
,AC_STATUS_CODE	VARCHAR2(32)
,AC_STATUS_DATE	DATE
,AC_GENERIC_FIELD1_DATE	DATE
,AC_GENERIC_FIELD2_DATE	DATE
,AC_GENERIC_FIELD3_NUM	NUMBER(18)
,AC_GENERIC_FIELD4_NUM	NUMBER(18)
,AC_GENERIC_FIELD5_TXT	VARCHAR2(256)
,AC_GENERIC_FIELD6_TXT	VARCHAR2(256)
,AC_GENERIC_FIELD7_TXT	VARCHAR2(256)
,AC_GENERIC_FIELD8_TXT	VARCHAR2(256)
,AC_GENERIC_FIELD9_TXT	VARCHAR2(256)
,AC_GENERIC_FIELD10_TXT	VARCHAR2(256)
,AC_START_DATE	DATE
,AC_END_DATE	DATE
,AC_CREATE_TS	DATE
,AC_CREATED_BY	VARCHAR2(80)
,AC_UPDATE_TS	DATE
,AC_UPDATED_BY	VARCHAR2(80)) TABLESPACE MAXDAT_DATA;

CREATE INDEX IDX1_AUTHCONTACT_STG_UK ON AUTHORIZED_CONTACT_STG(AUTHORIZED_CONTACT_ID) TABLESPACE MAXDAT_INDX;

GRANT SELECT ON AUTHORIZED_CONTACT_STG to MAXDAT_READ_ONLY;
       
insert into CORP_ETL_CONTROL(name,VALUE_TYPE,value,DESCRIPTION,CREATED_TS,UPDATED_TS) 
values ('CLIENT_LAST_CREATE_DATE','D',to_char(TRUNC(SYSDATE-360),'yyyy/mm/dd hh24:mi:ss'),'This is the timestamp of the client.creation_date from the previous run. create_ts of the most recent app header record from the previous run.',sysdate,sysdate);

insert into CORP_ETL_CONTROL(name,VALUE_TYPE,value,DESCRIPTION,CREATED_TS,UPDATED_TS) 
values ('CLIENT_LAST_UPDATE_DATE','D',to_char(TRUNC(SYSDATE-360),'yyyy/mm/dd hh24:mi:ss'),'This is the timestamp of the client.last_update_date from the previous run. update_ts of the most recent app header record from the previous run.',sysdate,sysdate);

insert into CORP_ETL_CONTROL(name,VALUE_TYPE,value,DESCRIPTION,CREATED_TS,UPDATED_TS) 
values ('AUTHCONTACT_CREATE_DATE','D',to_char(TRUNC(SYSDATE-360),'yyyy/mm/dd hh24:mi:ss'),'This is the timestamp of the authorized_contact.ac_create_ts from the previous run. update_ts of the most recent app header record from the previous run.',sysdate,sysdate);

insert into CORP_ETL_CONTROL(name,VALUE_TYPE,value,DESCRIPTION,CREATED_TS,UPDATED_TS) 
values ('AUTHCONTACT_UPDATE_DATE','D',to_char(TRUNC(SYSDATE-360),'yyyy/mm/dd hh24:mi:ss'),'This is the timestamp of the authorized_contact.ac_update_ts from the previous run. update_ts of the most recent app header record from the previous run.',sysdate,sysdate);

commit;       

