ALTER TABLE D_STAFF ADD
(
    SOURCE_REFERENCE_TYPE                   VARCHAR2(30),
    SOURCE_REFERENCE_ID                     NUMBER
);

 CREATE OR REPLACE FORCE EDITIONABLE VIEW D_STAFF_SV AS
  select STAFF_ID,
  EXT_STAFF_NUMBER,
  FIRST_NAME,
  MIDDLE_NAME,
  LAST_NAME,
  START_DATE,
  END_DATE,
  CREATE_TS,
  UPDATE_TS,
  SOURCE_REFERENCE_TYPE,
  SOURCE_REFERENCE_ID
from D_STAFF;
