CREATE OR REPLACE VIEW D_SCID_CURRENT_SV
AS
  SELECT crl.CALL_RECORD_ID AS CONTACT_RECORD_ID,
  crl.CALL_RECORD_LINK_ID AS CONTACT_RECORD_LINK_ID,
  crl.CLIENT_ID AS CLIENT_ID,
  crl.CASE_ID AS CASE_ID,
  'PROGRAM_TYPE' AS program,
  'PROGRAM_SUBTYPE' AS subprogram,
   CASE WHEN FLOOR(MONTHS_BETWEEN(sysdate, cl.CLNT_DOB)/12) < 21 THEN 'Y' 
        WHEN FLOOR(MONTHS_BETWEEN(sysdate, cl.CLNT_DOB)/12) >= 21 THEN 'N' 
        ELSE NULL END AS CLIENT_UNDER_TWENTYONE
FROM EB.CALL_RECORD_LINK crl
LEFT JOIN EB.CLIENT cl ON (crl.CLIENT_ID = cl.CLNT_CLNT_CLIENT_ID)
; 
  
  GRANT SELECT ON maxdat_support.D_SCID_CURRENT_SV TO EB_MAXDAT_REPORTS;  