
UPDATE CC_C_CONTACT_QUEUE 
SET UNIT_OF_WORK_NAME = 'EB Outbound'
WHERE QUEUE_TYPE = 'Outbound';

UPDATE CC_S_CONTACT_QUEUE
SET UNIT_OF_WORK_ID = 
	(SELECT UNIT_OF_WORK_ID
		FROM CC_C_UNIT_OF_WORK
		WHERE UNIT_OF_WORK_NAME = 'EB Outbound'
	)
WHERE QUEUE_TYPE = 'Outbound';

INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME)
VALUES ('1.5.0','101','101_UPDATE_CONTACT_QUEUE_RECORDS');

COMMIT;