INSERT INTO D_CRS_STATUS (STATUS_ID) VALUES (0);
INSERT INTO D_CRS_DATA_PROVIDED (DATA_PROVIDED_ID) VALUES (0);
INSERT INTO D_CRS_EXPERTS (EXPERT_ID) VALUES (0);
INSERT INTO D_CRS_EXPERT_LICENSES (EXPERT_LICENSE_ID) VALUES (0);
INSERT INTO D_CRS_EXPERT_TYPES (EXPERT_TYPE_ID) VALUES (0);
INSERT INTO D_CRS_EXPERT_SPECIALTIES (EXPERT_SPECIALTY_ID) VALUES (0);
INSERT INTO D_CRS_ISSUE_TYPES (ISSUE_TYPE_ID) VALUES (0);
INSERT INTO D_CRS_DECISION_TYPES (DECISION_TYPE_ID) VALUES (0);
INSERT INTO D_CRS_INELIGIBLE_REASONS (INELIGIBLE_REASON_ID) VALUES (0);

COMMIT;