INSERT INTO D_CRS_CLAIM_PRIORITIES (CLAIM_PRIORITY_ID) VALUES (0);
INSERT INTO D_CRS_CLOSED_REASONS (CLOSED_REASON_ID) VALUES (0);
INSERT INTO D_CRS_EDI_CONTRIBUTORS (EDI_CONTRIBUTOR_ID) VALUES (0);
INSERT INTO D_CRS_STATES (STATE_ID) VALUES (0);
INSERT INTO D_CRS_TERMINATION_REASONS (TERMINATION_REASON_ID) VALUES (0);

COMMIT;