ALTER TABLE D_DELTEK_HOURS ADD SUP_UPDATED VARCHAR(2) DEFAULT 'N';

CREATE OR REPLACE VIEW MAXDAT_CADR.D_DELTEK_HOURS_SV AS
SELECT
DDH_ID,
EMPLOYEE_ID,
LABOR_GRP_TYPE,
LAST_NAME,
FIRST_NAME,
TITLE,
EMPL_ORG_ID,
EMPL_ORG_NAME,
APPROVAL_NAME,
PROJECT_ID,
PROJECT_NAME,
ORG_ID,
ORG_NAME,
PAY_TYPE,
PLC_ID,
HOURS_DATE,
ENTERED_HOURS,
PRODUCTIVE_HOURS,
COMMENTS,
NOTES,
SUP_UPDATED,
MAXDAT_AUDIT_CREATE_DT,
MAXDAT_AUDIT_UPDATE_DT
FROM D_DELTEK_HOURS;

/