-- Update all the changes to Production as of 8/1
--  dwd 8/1/2014
TRUNCATE TABLE gather_stats_table_config;

--UPDATE CORP_ETL_CONTROL set VALUE = '400000'
--WHERE NAME = 'MW_LAST_STEP_INST_HIST_ID';
--COMMIT;

DROP TABLE corp_etl_manage_work_tmp;

CREATE TABLE CORP_ETL_MANAGE_WORK_TMP (
  CEMW_ID                NUMBER
, ASF_CANCEL_WORK        VARCHAR2(1)
, ASF_COMPLETE_WORK      VARCHAR2(1)
, AGE_IN_BUSINESS_DAYS   NUMBER
, AGE_IN_CALENDAR_DAYS   NUMBER
, CANCEL_WORK_DATE       DATE
, CANCEL_WORK_FLAG       VARCHAR2(1)
, COMPLETE_DATE          DATE
, COMPLETE_FLAG          VARCHAR2(1)
, CREATE_DATE            DATE
, CREATED_BY_NAME        VARCHAR2(100)
, ESCALATED_FLAG         VARCHAR2(1)
, ESCALATED_TO_NAME      VARCHAR2(100)
, FORWARDED_BY_NAME      VARCHAR2(100)
, FORWARDED_FLAG         VARCHAR2(1)
, GROUP_NAME             VARCHAR2(100)
, GROUP_PARENT_NAME      VARCHAR2(100)
, GROUP_SUPERVISOR_NAME  VARCHAR2(100)
, JEOPARDY_FLAG          VARCHAR2(1)
, LAST_UPDATE_BY_NAME    VARCHAR2(100)
, LAST_UPDATE_DATE       DATE
, OWNER_NAME             VARCHAR2(100)
, SLA_DAYS               NUMBER
, SLA_DAYS_TYPE          VARCHAR2(1)
, SLA_JEOPARDY_DAYS      NUMBER
, SLA_TARGET_DAYS        NUMBER
, SOURCE_REFERENCE_ID    NUMBER
, SOURCE_REFERENCE_TYPE  VARCHAR2(30)
, STATUS_AGE_IN_BUS_DAYS NUMBER
, STATUS_AGE_IN_CAL_DAYS NUMBER
, STATUS_DATE            DATE
, TASK_ID                NUMBER
, TASK_STATUS            VARCHAR2(50)
, TASK_TYPE              VARCHAR2(100)
, TEAM_NAME              VARCHAR2(100)
, TEAM_PARENT_NAME       VARCHAR2(100)
, TEAM_SUPERVISOR_NAME   VARCHAR2(100)
, TIMELINESS_STATUS      VARCHAR2(20)
, UNIT_OF_WORK           VARCHAR2(30)
, STG_EXTRACT_DATE       DATE
, STG_LAST_UPDATE_DATE   DATE
, STAGE_DONE_DATE        DATE
, DATE_TODAY             DATE
, CASE_ID                NUMBER
, CLIENT_ID              NUMBER
, CANCEL_METHOD          VARCHAR2(50)
, CANCEL_REASON          VARCHAR2(256)
, CANCEL_BY              VARCHAR2(50)
, TASK_PRIORITY          VARCHAR2(50)
, PARENT_TASK_ID         NUMBER
, CHANNEL                VARCHAR2(20)
, INSTANCE_STATUS        VARCHAR2(20)
, INSTANCE_START_DATE    DATE
, INSTANCE_END_DATE      DATE
, RECEIVED_DATE          DATE
, ASSIGNED_DATE          DATE
, ORIGINAL_CREATION_DATE DATE
, CASE_NUMBER            VARCHAR2(100)
, UPDATED                VARCHAR2(1)
)
TABLESPACE MAXDAT_DATA ;

CREATE UNIQUE INDEX CORP_ETL_MANAGE_WORK_TMP_IX1 ON CORP_ETL_MANAGE_WORK_TMP (TASK_ID) 
  TABLESPACE MAXDAT_INDX ;

CREATE UNIQUE INDEX CORP_ETL_MANAGE_WORK_TMP_IX2 ON CORP_ETL_MANAGE_WORK_TMP (CEMW_ID) 
  TABLESPACE MAXDAT_INDX ;

CREATE INDEX IDX_MANAGE_WORK_TMP_CASE_ID ON CORP_ETL_MANAGE_WORK_TMP (CASE_ID) 
  TABLESPACE MAXDAT_INDX ;

CREATE INDEX IDX_MANAGE_WORK_TMP_CLIENT_ID ON CORP_ETL_MANAGE_WORK_TMP (CLIENT_ID) 
  TABLESPACE MAXDAT_INDX ;

CREATE INDEX IDX_MANAGE_WORK_TMP_PTASK_ID ON CORP_ETL_MANAGE_WORK_TMP (PARENT_TASK_ID) 
  TABLESPACE MAXDAT_INDX ;

GRANT SELECT ON CORP_ETL_MANAGE_WORK_TMP TO MAXDAT_READ_ONLY;

-------------------
DROP TABLE cadir_maxdat_stg;

CREATE TABLE CADIR_MAXDAT_STG (
	ID                    NUMBER NOT NULL ENABLE, 
	C_ASSIGNMENT_FROM     NUMBER, 
	C_ASSIGNMENT_TO       NUMBER, 
	C_CREATED_BY          NUMBER, 
	C_CREATED_ON          DATE, 
	ASSIGNMENT_ID         NUMBER, 
	DATA_OBJECT_KEY       VARCHAR2(10), 
	TRACKING_ID           NUMBER, 
	SUBJECT_TYPE          NUMBER, 
	SUBJECT_ID            NUMBER, 
	ROLE_ID               NUMBER, 
	IS_CURRENT            NUMBER, 
	IS_DELEGATE           NUMBER, 
	IS_CREATOR            NUMBER, 
	ASSIGNMENT_DATE       DATE, 
	DESCRIPTION           VARCHAR2(200), 
	STG_EXTRACT_DATE      DATE DEFAULT SYSDATE, 
	STG_LAST_UPDATE_DATE  DATE DEFAULT SYSDATE, 
	PREVIOUS_ASSIGNMENT_ID NUMBER, 
	C_ASSIGNED_DATE       DATE, 
	C_RECEIVED_DATE       DATE, 
	C_CASE_NUMBER         VARCHAR2(100), 
	C_CLAIM_TYPE0         NUMBER
)
TABLESPACE MAXDAT_DATA;

CREATE INDEX CADIR_MAXDAT_STG_INXID ON CADIR_MAXDAT_STG (ID)
  TABLESPACE MAXDAT_INDX;

CREATE INDEX CADIR_MAXDAT_STG_INDXFR ON CADIR_MAXDAT_STG (C_ASSIGNMENT_FROM)
  TABLESPACE MAXDAT_INDX;

CREATE INDEX CADIR_MAXDAT_STG_INDXTO ON CADIR_MAXDAT_STG (C_ASSIGNMENT_TO)
  TABLESPACE MAXDAT_INDX;

CREATE INDEX CADIR_MAXDAT_STG_INDXAS ON CADIR_MAXDAT_STG (ASSIGNMENT_ID)
  TABLESPACE MAXDAT_INDX;

CREATE INDEX CADIR_MAXDAT_STG_INDXTR ON CADIR_MAXDAT_STG (TRACKING_ID)
  TABLESPACE MAXDAT_INDX;

GRANT SELECT ON CADIR_MAXDAT_STG TO MAXDAT_READ_ONLY;

-------------------
CREATE TABLE CADIR_MANAGEWORK_LOGGING (
  START_DATE DATE
, END_DATE   DATE
, MODULE     VARCHAR2(20)
)
TABLESPACE MAXDAT_DATA ;

GRANT SELECT ON CADIR_MANAGEWORK_LOGGING TO MAXDAT_READ_ONLY;

-------------
CREATE INDEX CADIR_USER_STG_INDXUS ON CADIR_USER_STG (USER_ID)
  TABLESPACE MAXDAT_INDX;

CREATE INDEX CADIR_USER_STG_INDXPS ON CADIR_USER_STG (PERSON_ID)
  TABLESPACE MAXDAT_INDX;

CREATE INDEX CADIR_PERSON_STG_INDXPS ON CADIR_PERSON_STG (PERSON_ID)
  TABLESPACE MAXDAT_INDX;

CREATE INDEX IDX_MANAGE_WORK_PTASK_ID ON CORP_ETL_MANAGE_WORK (PARENT_TASK_ID) 
  TABLESPACE MAXDAT_INDX ;

