ALTER SESSION SET CURRENT_SCHEMA = CISCO_ENTERPRISE_CC;

ALTER TABLE CC_S_IVR_MENU_GROUP_DATE
ADD(IVR_ELEMENT_RESULT VARCHAR2(100)
    ,IVR_ELEMENT_CAUSE VARCHAR2(100)
    ,IVR_EXIT_STATE VARCHAR2(100)
    ,IVR_ELEMENT_TYPE VARCHAR2(100)
    ,AVERAGE_ELAPSED VARCHAR2(25)
    ,SOURCE_APPLICATION_NAME  VARCHAR2(100)
    ,RESULT_ID NUMBER
    ,CAUSE_ID NUMBER
    ,ELEMENT_TYPE_ID NUMBER);
    
ALTER TABLE CC_F_IVR_MENU_GROUP_DATE
ADD(IVR_ELEMENT_RESULT VARCHAR2(100)
    ,IVR_ELEMENT_CAUSE VARCHAR2(100)
    ,IVR_EXIT_STATE VARCHAR2(100)
    ,IVR_ELEMENT_TYPE VARCHAR2(100)
    ,AVERAGE_ELAPSED VARCHAR2(25)
    ,SOURCE_APPLICATION_NAME  VARCHAR2(100)
    ,RESULT_ID NUMBER
    ,CAUSE_ID NUMBER
    ,ELEMENT_TYPE_ID NUMBER);

ALTER TABLE CC_S_IVR_MENU_GROUP_DATE DROP CONSTRAINT CC_S_IVR_MENU_GROUP_DATE__UN;
ALTER TABLE CC_F_IVR_MENU_GROUP_DATE DROP CONSTRAINT CC_F_IVR_MENU_GROUP_DATE__UN;
    
CREATE  INDEX CC_S_IVR_MENU_GROUP_DATE_IDX1 ON CC_S_IVR_MENU_GROUP_DATE(IVR_ELEMENT_CAUSE) TABLESPACE MAXDAT_DATA;
CREATE  INDEX CC_F_IVR_MENU_GROUP_DATE_IDX1 ON CC_F_IVR_MENU_GROUP_DATE(IVR_ELEMENT_CAUSE) TABLESPACE MAXDAT_DATA;


CREATE  INDEX CC_S_IVR_MENU_GROUP_DATE_IDX2 ON CC_S_IVR_MENU_GROUP_DATE(CALL_DATE,
IVR_MENU_NAME,
IVR_SUB_MENU_NAME,
IVR_EXIT_STATE,
RESULT_ID,
ELEMENT_TYPE_ID,
CAUSE_ID,
SOURCE_APPLICATION_NAME,
AVERAGE_ELAPSED) TABLESPACE MAXDAT_DATA;

CREATE  INDEX CC_F_IVR_MENU_GROUP_DATE_IDX3 ON CC_F_IVR_MENU_GROUP_DATE(D_DATE_ID,
IVR_MENU_NAME,
IVR_SUB_MENU_NAME,
IVR_EXIT_STATE,
RESULT_ID,
ELEMENT_TYPE_ID,
CAUSE_ID,
SOURCE_APPLICATION_NAME,
AVERAGE_ELAPSED) TABLESPACE MAXDAT_DATA;

 --view script  
 CREATE OR REPLACE VIEW CC_F_IVR_MENU_GROUP_ELEMENT_BY_DATE_SV 
 AS
 SELECT ivr.D_DATE_ID
       ,cp.PROJECT_ID AS D_PROJECT_ID
       ,cm.PROGRAM_ID AS D_PROGRAM_ID
       ,cp.PROJECT_NAME
       ,cm.PROGRAM_NAME
       ,mn.IVR_MENU_GROUP_NAME
       ,ivr.IVR_ELEMENT_RESULT
       ,ivr.IVR_ELEMENT_CAUSE
       ,ivr.IVR_ELEMENT_TYPE
       ,CASE WHEN ivr.IVR_EXIT_STATE = 'Unknown' THEN NULL ELSE ivr.IVR_EXIT_STATE END IVR_EXIT_STATE
       ,CASE WHEN ivr.AVERAGE_ELAPSED = '00' THEN NULL ELSE ivr.AVERAGE_ELAPSED END AVERAGE_ELAPSED
       ,CASE WHEN ivr.SOURCE_APPLICATION_NAME = 'Unknown' THEN NULL ELSE ivr.SOURCE_APPLICATION_NAME END SOURCE_APPLICATION_NAME
       ,CASE WHEN ivr.RESULT_ID = 999 THEN NULL ELSE ivr.RESULT_ID END RESULT_ID
       ,CASE WHEN ivr.CAUSE_ID = 999 THEN NULL ELSE ivr.CAUSE_ID END CAUSE_ID
       ,CASE WHEN ivr.ELEMENT_TYPE_ID = 999 THEN NULL ELSE ELEMENT_TYPE_ID END ELEMENT_TYPE_ID
       ,ivr.IVR_MENU_NAME
       ,IVR_CALL_COUNT IVR_CALL_COUNT
       ,ivr.IVR_SUB_MENU_NAME 
    FROM CC_F_IVR_MENU_GROUP_DATE ivr
    INNER JOIN CC_C_IVR_MENU_GROUP mn
      ON ivr.IVR_SUB_MENU_NAME = mn.IVR_SUB_MENU_NAME 
      AND ivr.IVR_MENU_NAME = mn.IVR_MENU_NAME
    INNER JOIN CC_D_DATES dd ON ivr.D_DATE_ID = dd.D_DATE_ID
    INNER JOIN CC_D_PROJECT cp ON mn.PROJECT_NAME = cp.PROJECT_NAME
    INNER JOIN CC_D_PROGRAM cm ON mn.PROGRAM_NAME = cm.PROGRAM_NAME
    WHERE dd.d_date >= TO_DATE('02/01/2020','mm/dd/yyyy')
  ;
  
  GRANT SELECT ON CC_F_IVR_MENU_GROUP_ELEMENT_BY_DATE_SV TO MAXDAT_READ_ONLY;
    
  