-- Drop CC_IVR_PKG objects
DROP PACKAGE IVR_CALC_PKG;

-- Drop CC_IVR_UTIL_PKG objects
DROP PACKAGE IVR_UTIL_PKG;

-- Drop  CC_F_IVR_PERFORMANCE_INSTANCE objects
DROP VIEW CC_F_IVR_PERFORMANCE_INSTANCE_SV;
DROP SEQUENCE SEQ_CLASS_RUN_ID;
DROP TABLE CC_S_TMP_CLASS_RUN;
DROP SEQUENCE SEQ_IVR_PERFORMANCE_INSTANCE_EXT_ID;
DROP TABLE CC_S_IVR_PERFORMANCE_INSTANCE_EXT;
DROP SEQUENCE SEQ_IVR_PERFORMANCE_INSTANCE_ID;
DROP TABLE CC_F_IVR_PERFORMANCE_INSTANCE;

-- Drop CC_F_IVR_PERFORMANCE_INTERVAL objects

DROP VIEW CC_F_IVR_PERFORMANCE_INTERVAL_SV;
DROP SEQUENCE SEQ_IVR_PERFORMANCE_INTERVAL_ID;
DROP TABLE CC_F_IVR_PERFORMANCE_INTERVAL;

-- Drop CC_S_IVR_CISCOCVP objects
DROP VIEW CC_S_IVR_CISCOCVP_SV;
DROP SEQUENCE SEQ_IVR_CISCOCVP_ID;
DROP TABLE  CC_S_IVR_CISCOCVP;

-- Drop CC_S_IVR_CTRL objects
DROP VIEW CC_C_IVR_CTRLS_SV;
DROP SEQUENCE SEQ_IVR_CTRL_ID;
DROP TABLE CC_C_IVR_CTRLS;

--Drop CC_C_IVR_LANGUAGE objects

DROP VIEW CC_C_IVR_LANGUAGE_SV;
DROP SEQUENCE SEQ_IVR_LANG_ID;
DROP TABLE CC_C_IVR_LANGUAGE;

-- Drop CC_C_IVR_HOLIDAY objects

DROP VIEW CC_C_IVR_HOLIDAYS_SV;
DROP SEQUENCE SEQ_IVR_HOLIDAYS_ID;
DROP TABLE CC_C_IVR_HOLIDAYS;

-- Drop CC_C_IVR_JOB objects

DROP VIEW CC_A_IVR_JOB_CTRL_SV;
DROP SEQUENCE SEQ_IVR_JOB_CTRL_ID;
DROP TABLE CC_A_IVR_JOB_CTRL;

DROP VIEW CC_A_IVR_JOB_SV;
DROP SEQUENCE SEQ_IVR_JOB_ID;
DROP TABLE CC_A_IVR_JOB;


-- Drop CC_F_IVR_PERFORMANCE_INTERVAL_VIEW objects
DROP VIEW CC_F_IVR_PERFORMANCE_INTERVAL_SV;





