DROP TABLE CC_A_IVR_JOB;
CREATE TABLE CC_A_IVR_JOB (
IVR_JOB_ID NUMBER(38) NOT NULL
, JOB_NAME VARCHAR2(15) NOT NULL
, JOB_DESCRIPTION VARCHAR2(500)
, DAILY_RUN_ENABLED     VARCHAR2(1)
, DAILY_RUN_SCRIPT VARCHAR2(1000)
, ENABLED VARCHAR2(1)
, CREATE_DT DATE NOT NULL
, CREATED_BY VARCHAR2(50) NOT NULL
, UPDATE_DT DATE NOT NULL
, UPDATED_BY VARCHAR2(50) NOT NULL
)
       TABLESPACE MAXDAT_DATA 
        LOGGING 
;        

ALTER TABLE CC_A_IVR_JOB 
    ADD CONSTRAINT CC_A_IVR_JOB_PK PRIMARY KEY ( IVR_JOB_ID ) ;

ALTER TABLE CC_A_IVR_JOB 
    ADD CONSTRAINT CC_A_IVR_JOB_UN UNIQUE ( JOB_NAME ) ;

DROP SEQUENCE SEQ_IVR_JOB_ID;
CREATE SEQUENCE SEQ_IVR_JOB_ID;  

CREATE OR REPLACE TRIGGER BIU_CC_A_IVR_JOB
    BEFORE INSERT OR UPDATE ON CC_A_IVR_JOB 
    FOR EACH ROW 
BEGIN
IF INSERTING AND :NEW.IVR_JOB_ID IS NULL THEN 
          SELECT SEQ_IVR_JOB_ID.NEXTVAL INTO :NEW.IVR_JOB_ID FROM DUAL;
END IF;
    IF :NEW.CREATE_DT IS NULL THEN
      :NEW.CREATE_DT := SYSDATE;
    END IF;
    
    IF :NEW.CREATED_BY IS NULL THEN
       :NEW.CREATED_BY := USER;
    END IF;
    
  IF :NEW.ENABLED IS NULL THEN
    :NEW.ENABLED := 'N';
  END IF;
  :NEW.ENABLED := UPPER(:NEW.ENABLED);
  IF :NEW.DAILY_RUN_ENABLED IS NULL THEN
    :NEW.DAILY_RUN_ENABLED := 'N';
  END IF;
  :NEW.DAILY_RUN_ENABLED := UPPER(:NEW.DAILY_RUN_ENABLED);
  :NEW.UPDATED_BY := USER;
  :NEW.UPDATE_DT := SYSDATE;
END;
/

CREATE OR REPLACE VIEW CC_A_IVR_JOB_SV AS 
SELECT * FROM CC_A_IVR_JOB;

-- select * from CC_A_IVR_JOB
-- TRUNCATE TABLE CC_A_IVR_JOB

GRANT SELECT ON CC_A_IVR_JOB TO CISCO_READ_ONLY;
GRANT SELECT ON CC_A_IVR_JOB_SV TO CISCO_READ_ONLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON CC_A_IVR_JOB TO SD25802, SR18956, LG74078;
GRANT SELECT ON CC_A_IVR_JOB TO MAXDAT_READ_ONLY;
GRANT SELECT ON CC_A_IVR_JOB_SV TO MAXDAT_READ_ONLY;

