alter table cc_s_ivr_ciscocvp drop constraint cc_s_ivr_ciscocvp_un;

alter table cc_s_ivr_ciscocvp add
(
    callstartdate_db_local          date
);

COMMENT ON COLUMN "CISCO_ENTERPRISE_CC"."CC_S_IVR_CISCOCVP"."CALLSTARTDATE_DB_LOCAL" IS 'VXMLSESSION.CALLSTARTDATE; The local callstartdate';
COMMENT ON COLUMN "CISCO_ENTERPRISE_CC"."CC_S_IVR_CISCOCVP"."CALLSTARTDATE" IS 'The callstartdate in US/Eastern';

alter table cc_s_ivr_ciscocvp add
(
    CONSTRAINT "CC_S_IVR_CISCOCVP_UN" UNIQUE ("CALLGUID", "CALLSTARTDATE_DB_LOCAL")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "MAXDAT_DATA"  ENABLE
);