CREATE TABLE CC_EVENT_STG (
MCES_ID   NUMBER PRIMARY KEY,
CREATE_TS DATE,
UPDATE_TS DATE,
EVENT_ID  NUMBER NOT NULL,
EVENT_CREATE_TS DATE NOT NULL,
REF_ID    NUMBER NOT NULL,
CASE_ID   NUMBER,
CALL_CAMPAIGN_TYPE VARCHAR2(32)
--UNIQUE(EVENT_ID)
)

CREATE SEQUENCE seq_mces START WITH 1 CACHE 1000;

CREATE OR REPLACE TRIGGER MAXDAT."TRG_CC_EVENT_stg" BEFORE
       INSERT OR
       UPDATE ON CC_EVENT_STG FOR EACH ROW
BEGIN
  IF Inserting THEN
      SELECT mces_seq.Nextval INTO :NEW.MCES_ID FROM Dual;
      :NEW.CREATE_TS := to_date(SYSDATE);
  END IF;
  
  :NEW.UPDATE_TS := SYSDATE;
END;
