CREATE VIEW MAXDAT.D_INCIDENT_STATUS_HISTORY_SV
AS select
INCIDENT_HEADER_ID AS INCIDENT_ID,
STATUS_CD,
INCIDENT_STATUS,
CREATE_TS INCIDENT_STATUS_DT,
CREATED_BY,
CREATED_BY_STAFF_ID
from
INCIDENT_HEADER_STAT_HIST_STG WITH READ ONLY
