UPDATE corp_clnt_outreach_proc_lkup
SET step1 = 'Phone Call3'
   ,step3 = 'Letter2'
   ,step5 = 'Home Visit2'
WHERE process = 'OUTREACH_REQUEST_6';

UPDATE corp_clnt_outreach_proc_lkup
SET step4 = 'Home Visit3'
WHERE process = 'OUTREACH_REQUEST_13';

UPDATE CORP_ETL_CLNT_OR_ACTIVITY_LKUP 
SET outreach_step_type = 'Home Visit2'
WHERE outreach_step_type = 'Home Visit'
and event_type_cd in('BASIC_SCRIPT_DELIVERED',
'HCO_SCRIPT_DELIVERED',
'CM_SCRIPT_DELIVERED');
  
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Letter2','Basic Script Delivered',null,'BASIC_SCRIPT_DELIVERED',null);
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Letter2','HCO Script Delivered',null,'HCO_SCRIPT_DELIVERED',null);
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Letter2','Case Management Script Delivered', null,'CM_SCRIPT_DELIVERED',null);
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Letter2','Outreach Request - Letter Request has been created.',null,'OUTREACH_REQUEST_LETTER_CREATED',null);
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Letter2','Outreach Request - Letter Request not created.',null,null,null);
 
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Home Visit2','Outreach Request Home Visit Success',null,'OR_HOME_VISIT_SUCCESS',null);
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Home Visit2','Outreach Request Home Visit Failure',null,'OR_HOME_VISIT_FAILURE',null);


Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Home Visit3','Basic Script Delivered',null,'BASIC_SCRIPT_DELIVERED','NEW_SSI');
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Home Visit3','HCO Script Delivered',null,'HCO_SCRIPT_DELIVERED','NEW_SSI');
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Home Visit3','Case Management Script Delivered',null,'CM_SCRIPT_DELIVERED','NEW_SSI');
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Home Visit3','No One Home, Left Letter',null,'NOT_HOME_LEFT_LTR',null);
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Home Visit3','Outreach Request Home Visit Failure',null,'OR_HOME_VISIT_FAILURE',null);
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Home Visit3','Safety Issue - Do Not Return',null,'SAFETY_ISSUE',null);
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Home Visit3','Wrong House - Home Visit Attempt',null,'WRONG_HOUSE',null);




commit;  
