update CORP_CLNT_OUTREACH_PROC_LKUP
set step3 = 'Phone Call4'
where process = 'OUTREACH_REQUEST_1';

Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Phone Call4','Outreach Dialer Unsuccessful',null,'OR_TESTING_DIALER_NO_REACH',null);
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Phone Call4','Basic Script Delivered',null,'BASIC_SCRIPT_DELIVERED',null);
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Phone Call4','HCO Script Delivered',null,'HCO_SCRIPT_DELIVERED',null);
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Phone Call4','Outbound Call Successful',null,'OUTBOUND_CALL_SUCCESS',null);
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Phone Call4','Outbound Call Unsuccessful',null,'OUTBOUND_CALL_UNSUCCESS',null);
Insert into CORP_ETL_CLNT_OR_ACTIVITY_LKUP (OUTREACH_STEP_TYPE,EVENT_TYPE,OUTREACH_TYPE,EVENT_TYPE_CD,OUTREACH_TYPE_CD) values ('Phone Call4','Outreach Request - Client has no phone',null,'OUTREACH_REQUEST_NO_PHONE',null);

commit;
