create index DCORCUR_IX3 ON D_COR_CURRENT(CREATE_DATE) TABLESPACE MAXDAT_INDX;
create index DCORCUR_IX4 ON D_COR_CURRENT(COMPLETE_DATE) TABLESPACE MAXDAT_INDX;
create index DCORCUR_IX5 ON D_COR_CURRENT(CPW_REFERRAL_SOURCE_TYPE) TABLESPACE MAXDAT_INDX;
create index DCORCUR_IX6 ON D_COR_CURRENT(CPW_REFERRAL_SOURCE_NAME) TABLESPACE MAXDAT_INDX;
create index DCORCUR_IX7 ON D_COR_CURRENT(OUTREACH_REQUEST_TYPE) TABLESPACE MAXDAT_INDX;

create index FCORBD_IXL5 on F_COR_BY_DATE (INVENTORY_COUNT) local online tablespace MAXDAT_INDX parallel compute statistics;