CREATE SEQUENCE  "HCO_SEQ_ORDER_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 582 CACHE 5 NOORDER  NOCYCLE ;

GRANT SELECT ON "HCO_SEQ_ORDER_ID" TO "MAXDAT_READ_ONLY";

CREATE TABLE HCO_D_ORDER (
DP_ORDER_ID NUMBER(10),
ORDER_ID NUMBER(10),
ORDER_DETAIL_ID NUMBER(10),
VENDOR_RECEIVED_DATE DATE,
COUNTY_NAME VARCHAR2(255),
DATE_REQUESTED DATE,
SHIP_DATE DATE,
MATERIAL_NAME VARCHAR2(255),
MATERIAL_TYPE VARCHAR2(255),
MATERIAL_LANGUAGE VARCHAR2(255),
MATERIAL_CODE VARCHAR2(255),
MATERIAL_DESCRIPTION VARCHAR2(255),
MATERIAL_ID NUMBER(10),
ORDER_QUANTITY NUMBER(10),
ORDER_STATUS_ID NUMBER(10),
ORDER_STATUS VARCHAR2(32),
RECORD_DATE DATE,
MODIFIED_DATE DATE,
DATE_CREATED DATE,
DATE_UPDATED DATE,
CREATED_BY VARCHAR2(50),
UPDATED_BY VARCHAR2(50)) TABLESPACE MAXDAT_DATA;


ALTER TABLE "HCO_D_ORDER" ADD CONSTRAINT "MR_ORDER_PK" PRIMARY KEY ("DP_ORDER_ID") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE;
CREATE INDEX HCODORDER_IDX01 ON HCO_D_ORDER(ORDER_ID) TABLESPACE "MAXDAT_INDX";
CREATE INDEX HCODORDER_IDX02 ON HCO_D_ORDER(ORDER_DETAIL_ID) TABLESPACE "MAXDAT_INDX";

GRANT SELECT ON "HCO_D_ORDER" TO "MAXDAT_READ_ONLY";

CREATE OR REPLACE TRIGGER "BUIR_ORDER" 
 BEFORE INSERT OR UPDATE
 ON hco_d_order
 FOR EACH ROW
DECLARE
    v_seq_id     HCO_D_ORDER.dp_order_id%TYPE;
BEGIN
  IF INSERTING THEN
    IF :NEW.dp_order_id IS NULL THEN
      SElECT HCO_SEQ_ORDER_ID.NEXTVAL
      INTO v_seq_id
      FROM dual;

      :NEW.dp_order_id       := v_seq_id;
    END IF;
    :NEW.date_created := sysdate;
    :NEW.created_by := user;
  END IF;
  
  :NEW.date_updated := sysdate;
  :NEW.updated_by := user;
END BUIR_ORDER;
/
ALTER TRIGGER "BUIR_ORDER" ENABLE;
/




