CREATE SEQUENCE  "HCO_SEQ_PACKET_MAIL_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 582 CACHE 5 NOORDER  NOCYCLE ;

GRANT SELECT ON "HCO_SEQ_PACKET_MAIL_ID" TO "MAXDAT_READ_ONLY";

CREATE TABLE HCO_S_PACKET_MAILING_STG(
DIM_PACKET_MAILING_ID NUMBER(10),
VENDOR_RECEIVED_DATE DATE,
COUNTY_CODE VARCHAR2(10),
JOB_ID VARCHAR2(50),
DCIN VARCHAR2(40),
DATE_REQUESTED DATE,
DATE_MAILED DATE,
SHIP_BY_DATE DATE,
LANGUAGE_ID VARCHAR2(1),
PACKET_TYPE VARCHAR2(2),
PACKET_SUBTYPE VARCHAR2(50),
BOOKLET_TYPE1 VARCHAR2(50),
BOOKLET_TYPE2 VARCHAR2(50),
PPD VARCHAR2(1),
PACKETS_REQUESTED NUMBER(10),
CASE_ID VARCHAR2(10),
VALID_FLAG VARCHAR2(1),
MAIL_STATUS VARCHAR2(50),
BAD_ADDRESS_TRANSACTION_TYPE VARCHAR2(10),
BAD_ADDRESS_RECORD_DATE DATE,
BAD_ADDRESS_FLAG VARCHAR2(1),
CUSTOM_MAILING_INDICATOR VARCHAR2(10),
MODIFIED_DATE DATE,
MODIFIED_BY VARCHAR2(50)) TABLESPACE MAXDAT_DATA;

GRANT SELECT ON "HCO_S_PACKET_MAILING_STG" TO "MAXDAT_READ_ONLY";

CREATE INDEX HCOSPKTMAILSTG_IDX01 ON HCO_S_PACKET_MAILING_STG (DIM_PACKET_MAILING_ID) TABLESPACE MAXDAT_INDX;

CREATE TABLE HCO_D_PACKET_MAILING(
DP_PACKET_MAIL_ID NUMBER(10),
DIM_PACKET_MAILING_ID NUMBER(10),
CUSTOM_MAILING_INDICATOR VARCHAR2(10),
VENDOR_RECEIVED_DATE DATE,
COUNTY_CODE VARCHAR2(10),
JOB_ID VARCHAR2(50),
DCIN VARCHAR2(40),
DATE_REQUESTED DATE,
DATE_MAILED DATE,
SHIP_BY_DATE DATE,
LANGUAGE_ID VARCHAR2(1),
PACKET_TYPE VARCHAR2(2),
PACKET_SUBTYPE VARCHAR2(50),
BOOKLET_TYPE1 VARCHAR2(50),
BOOKLET_TYPE2 VARCHAR2(50),
PPD VARCHAR2(1),
PACKETS_REQUESTED NUMBER(10),
CASE_ID VARCHAR2(10),
VALID_FLAG VARCHAR2(1),
MAIL_STATUS VARCHAR2(50),
BAD_ADDRESS_TRANSACTION_TYPE VARCHAR2(10),
BAD_ADDRESS_RECORD_DATE DATE,
BAD_ADDRESS_FLAG VARCHAR2(1),
MODIFIED_DATE DATE,
MODIFIED_NAME VARCHAR2(50),
RECORD_DATE DATE,
RECORD_NAME VARCHAR2(50),
DATE_CREATED DATE,
DATE_UPDATED DATE,
CREATED_BY VARCHAR2(50),
UPDATED_BY VARCHAR2(50)) TABLESPACE MAXDAT_DATA;


ALTER TABLE "HCO_D_PACKET_MAILING" ADD CONSTRAINT "PM_PACKETMAILING_PK" PRIMARY KEY ("DP_PACKET_MAIL_ID") USING INDEX TABLESPACE "MAXDAT_INDX"  ENABLE;

GRANT SELECT ON "HCO_D_PACKET_MAILING" TO "MAXDAT_READ_ONLY";
GRANT select, insert, update on HCO_D_PACKET_MAILING to MAXDAT_OLTP_SIU;
GRANT select, insert, update, delete on HCO_D_PACKET_MAILING to MAXDAT_OLTP_SIUD;

BEGIN
DBMS_ERRLOG.CREATE_ERROR_LOG ('HCO_D_PACKET_MAILING','ERRLOG_PACKET_MAILING');
END;
/


CREATE OR REPLACE TRIGGER "BUIR_PACKET_MAILING" 
 BEFORE INSERT OR UPDATE
 ON hco_d_packet_mailing
 FOR EACH ROW
DECLARE
    v_seq_id     HCO_D_PACKET_MAILING.dp_packet_mail_id%TYPE;
BEGIN
  IF INSERTING THEN
    IF :NEW.dp_packet_mail_id IS NULL THEN
      SElECT HCO_SEQ_PACKET_MAIL_ID.NEXTVAL
      INTO v_seq_id
      FROM dual;

      :NEW.dp_packet_mail_id       := v_seq_id;
    END IF;
    :NEW.date_created := sysdate;
    :NEW.created_by := user;
  END IF;
  
  :NEW.date_updated := sysdate;
  :NEW.updated_by := user;
END BUIR_PACKET_MAILING;
/
ALTER TRIGGER "BUIR_PACKET_MAILING" ENABLE;
/

CREATE OR REPLACE VIEW HCO_D_PACKET_MAILING_SV
AS 
SELECT dim_packet_mailing_id packet_mailing_id,
vendor_received_date,
county_code,
custom_mailing_indicator,
job_id,
dcin,
date_requested,
date_mailed,
ship_by_date,
ml.language material_language,
packet_type,
packet_subtype,
booklet_type1,
booklet_type2,
ppd,
CASE WHEN ppd = 'F' AND packet_type != 'PV' THEN 'C'
     WHEN ppd = 'S' THEN 'C'
     WHEN ppd = 'F' AND packet_type = 'PV' THEN 'PV2'
  ELSE ppd END ppd2,
packets_requested,
mail_status order_status_id,
valid_flag,
bad_address_transaction_type,
bad_address_record_date bad_address_date,
bad_address_flag
FROM hco_d_packet_mailing pm
 LEFT JOIN emrs_d_language ml ON pm.language_id = ml.language_code  ;

GRANT SELECT ON "HCO_D_PACKET_MAILING_SV" TO "MAXDAT_READ_ONLY";


