DECLARE
 v_rec        corp_etl_control%ROWTYPE;
 --
     PROCEDURE ins_upd_rec IS
        v_cnt INTEGER := 0;
     BEGIN
           SELECT  COUNT(*) INTO v_cnt
             FROM corp_etl_control  a
            WHERE a.NAME = v_rec.NAME;
           IF v_cnt = 0 THEN
              INSERT INTO corp_etl_control VALUES v_rec;
           END IF;
     END;
BEGIN
   v_rec.CREATED_TS := SYSDATE;
   v_rec.UPDATED_TS := SYSDATE;

   --*****************************************
   v_rec.NAME := 'AP_HRT_CASE_STATUS_LAST_SYNC_DT';
   v_rec.VALUE_TYPE := 'D';
   v_rec.VALUE := to_char(sysdate-1,'YYYY/MM/DD');
   v_rec.DESCRIPTION := 'This is the last sync date of processapp heart case status process run.';
   ins_upd_rec;
   --*****************************************

END;
/
COMMIT;


-- New columns for Reactivation to NYEC_ETL_PROCESS_APP
 
Alter Table NYEC_ETL_PROCESS_APP ADD REACTIVATION_IND     NUMBER(1) default 0; 
Alter Table NYEC_ETL_PROCESS_APP ADD REACTIVATION_DT          DATE;
Alter Table NYEC_ETL_PROCESS_APP ADD REACTIVATION_REASON   VARCHAR2(32);
Alter Table NYEC_ETL_PROCESS_APP ADD REACTIVATED_BY           VARCHAR2(100);
Alter Table NYEC_ETL_PROCESS_APP ADD REACTIVATION_NBR     NUMBER(3); 

Alter Table NYEC_ETL_PROCESS_APP ADD CURR_MODE_CD   VARCHAR2(2);
Alter Table NYEC_ETL_PROCESS_APP ADD CURR_MODE_LABEL  VARCHAR2(50);

Alter Table NYEC_ETL_PROCESS_APP ADD OUTCOME_NOTIFY_RQRD_FLAG   VARCHAR2(1);
Alter Table NYEC_ETL_PROCESS_APP ADD OUTCOME_LTR_ID  NUMBER(20);
Alter Table NYEC_ETL_PROCESS_APP ADD OUTCOME_LTR_TYPE   VARCHAR2(100);
Alter Table NYEC_ETL_PROCESS_APP ADD OUTCOME_LTR_STATUS VARCHAR2(32);
Alter Table NYEC_ETL_PROCESS_APP ADD OUTCOME_LTR_SENT_DT          DATE;
Alter Table NYEC_ETL_PROCESS_APP ADD OUTCOME_LTR_CREATE_DT        DATE;

Alter Table NYEC_ETL_PROCESS_APP ADD STOP_APP_REASON  VARCHAR2(50);
Alter Table NYEC_ETL_PROCESS_APP ADD WORKFLOW_REACT_IND   VARCHAR2(1);
Alter Table NYEC_ETL_PROCESS_APP ADD QC_IND   VARCHAR2(1);

-- New columns added for Reactivation to PROCESS_APP_STG table

Alter Table PROCESS_APP_STG ADD REACTIVATION_IND     NUMBER(1) default 0; 
Alter Table PROCESS_APP_STG ADD REACTIVATION_DT          DATE;
Alter Table PROCESS_APP_STG ADD REACTIVATION_REASON   VARCHAR2(32);
Alter Table PROCESS_APP_STG ADD REACTIVATED_BY           VARCHAR2(100);
Alter Table PROCESS_APP_STG ADD REACTIVATION_NBR     NUMBER(3); 

Alter Table PROCESS_APP_STG ADD CURR_MODE_CD   VARCHAR2(2);
Alter Table PROCESS_APP_STG ADD CURR_MODE_LABEL  VARCHAR2(50);

Alter Table PROCESS_APP_STG ADD OUTCOME_NOTIFY_RQRD_FLAG   VARCHAR2(1);
Alter Table PROCESS_APP_STG ADD OUTCOME_LTR_ID  NUMBER(20);
Alter Table PROCESS_APP_STG ADD OUTCOME_LTR_TYPE   VARCHAR2(100);
Alter Table PROCESS_APP_STG ADD OUTCOME_LTR_STATUS VARCHAR2(32);
Alter Table PROCESS_APP_STG ADD OUTCOME_LTR_SENT_DT          DATE;
Alter Table PROCESS_APP_STG ADD OUTCOME_LTR_CREATE_DT        DATE;

Alter Table PROCESS_APP_STG ADD STOP_APP_REASON  VARCHAR2(50);
Alter Table PROCESS_APP_STG ADD WORKFLOW_REACT_IND   VARCHAR2(1);
Alter Table PROCESS_APP_STG ADD QC_IND   VARCHAR2(1);