CREATE TABLE process_app_mi_stg
( MISSING_INFO_ID             NUMBER(18)   NOT NULL
, APP_ID                      NUMBER(18)   NOT NULL
, MI_ITEM_LEVEL               VARCHAR2(20) NOT NULL
, MI_ITEM_TYPE                VARCHAR2(20) NOT NULL
, MI_ITEM_CREATE_DT           DATE         NOT NULL
, MI_ITEM_REQUESTED_BY        VARCHAR2(50) NOT NULL
, MI_LETTER_REQUIRED_STATUS   VARCHAR2(20)
, MI_LETTER_ID                NUMBER(18)
, RFE_STATUS                  VARCHAR2(20)
, RFE_STATUS_DT               DATE
, MI_ITEM_STATUS              VARCHAR2(20)
, MI_ITEM_STATUS_DT           DATE
, MI_ITEM_STATUS_PERFORMER    VARCHAR2(50)
, SDE_TASK_COMPLETE_DT        DATE
, REPROCESS_TASK_CREATE_DT    DATE
, MI_ITEM_SATISFIED_CHANNEL   VARCHAR2(20)
, MI_LETTER_CYCLE_START_DT    DATE
, MI_LETTER_CYCLE_END_DT      DATE
, MI_ITEM_CREATE_TASK_TYPE    VARCHAR2(30)
, UNDELIVERABLE_IND           VARCHAR2(1)  NOT NULL 
, UNDELIVERABLE_IND_DT        DATE
, MI_VALIDATED_DT             DATE
, OUTBOUND_CALL_ID            NUMBER(10)
, IN_PROCESS_IND              VARCHAR2(1)  DEFAULT 'Y' NOT NULL
, MI_EXTRACT_COMPLETE_DT      DATE )
TABLESPACE MAXDAT_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

/* Primary Key */
CREATE UNIQUE INDEX process_app_mi_stg_pk_idx ON PROCESS_APP_MI_STG
(MISSING_INFO_ID)
LOGGING
TABLESPACE MAXDAT_INDX
NOPARALLEL;

ALTER TABLE PROCESS_APP_MI_STG
  ADD CONSTRAINT process_app_mi_stg_pk
  PRIMARY KEY (MISSING_INFO_ID);
  
/* Index for Foreign Key */
CREATE INDEX process_app_mi_stg_app_id_idx ON PROCESS_APP_MI_STG
(APP_ID)
LOGGING
TABLESPACE MAXDAT_INDX
NOPARALLEL;

/* Foreign Key to Process App Stg */
ALTER TABLE MAXDAT.PROCESS_APP_MI_STG ADD 
CONSTRAINT process_app_mi_stg_fk1
 FOREIGN KEY (APP_ID)
 REFERENCES MAXDAT.PROCESS_APP_STG (APP_ID)
 ENABLE
 VALIDATE
 
ALTER TABLE process_app_mi_stg
MODIFY(undeliverable_ind  DEFAULT 'N');

CREATE PUBLIC SYNONYM PROCESS_APP_MI_STG FOR MAXDAT.PROCESS_APP_MI_STG;

GRANT SELECT ON process_mi_stg to MAXDAT_READ_ONLY
