/*Staging tables*/
TRUNCATE TABLE CORP_ETL_PROCESS_ONLINE_INFO;
TRUNCATE TABLE CORP_ETL_PROC_ONLINE_INFO_OLTP;
TRUNCATE TABLE CORP_ETL_PROC_ONLINE_INFO_WIP;

/*Semantic tables*/
ALTER TABLE F_ONL_BY_DATE DISABLE CONSTRAINT FONLBD_DONLCUR_FK;
TRUNCATE TABLE F_ONL_BY_DATE;
TRUNCATE TABLE D_ONL_CURRENT;
ALTER TABLE F_ONL_BY_DATE ENABLE CONSTRAINT FONLBD_DONLCUR_FK;
DELETE FROM D_ONL_INSTANCE_STATUS;

/*Update global controls*/
update corp_etl_control
set value = '6579053'
WHERE Name = 'LAST_TRANSACTION_ID';

commit;