
--Set TERMINATION_DATE for Sandra Garcia
UPDATE CC_S_AGENT
SET TERMINATION_DATE = to_date('2014-05-30 00:00:00','yyyy-mm-dd HH24:mi:ss')
WHERE LOGIN_ID = '73141';

INSERT INTO CC_L_PATCH_LOG (PATCH_VERSION, SCRIPT_SEQUENCE, SCRIPT_NAME)
VALUES ('1.1.0',101,'101_UPDATE_S_AGENT_TERMINATION_DATE');

COMMIT;