-- Jan'16

INSERT INTO CC_A_ADHOC_JOB (ADHOC_JOB_TYPE, START_DATETIME_PARAM, END_DATETIME_PARAM, REPORTING_PERIOD_TYPE_PARAM, IS_PENDING) 
VALUES ('export_amp_metrics', '2016/05/01', '2016/05/31', 'MONTHLY', '1');

INSERT INTO CC_A_ADHOC_JOB (ADHOC_JOB_TYPE, START_DATETIME_PARAM, END_DATETIME_PARAM, REPORTING_PERIOD_TYPE_PARAM, IS_PENDING) 
VALUES ('export_amp_metrics', '2016/05/08', '2016/05/14', 'WEEKLY', '1');

INSERT INTO CC_A_ADHOC_JOB (ADHOC_JOB_TYPE, START_DATETIME_PARAM, END_DATETIME_PARAM, REPORTING_PERIOD_TYPE_PARAM, IS_PENDING) 
VALUES ('export_amp_metrics', '2016/05/15', '2016/05/21', 'WEEKLY', '1');

INSERT INTO CC_A_ADHOC_JOB (ADHOC_JOB_TYPE, START_DATETIME_PARAM, END_DATETIME_PARAM, REPORTING_PERIOD_TYPE_PARAM, IS_PENDING) 
VALUES ('export_amp_metrics', '2016/05/22', '2016/05/28', 'WEEKLY', '1');

INSERT INTO CC_A_ADHOC_JOB (ADHOC_JOB_TYPE, START_DATETIME_PARAM, END_DATETIME_PARAM, REPORTING_PERIOD_TYPE_PARAM, IS_PENDING) 
VALUES ('export_amp_metrics', '2016/05/29', '2016/06/04', 'WEEKLY', '1');

INSERT INTO CC_A_ADHOC_JOB (ADHOC_JOB_TYPE, START_DATETIME_PARAM, END_DATETIME_PARAM, REPORTING_PERIOD_TYPE_PARAM, IS_PENDING) 
VALUES ('export_amp_metrics', '2016/06/05', '2016/06/11', 'WEEKLY', '1');

INSERT INTO CC_A_ADHOC_JOB (ADHOC_JOB_TYPE, START_DATETIME_PARAM, END_DATETIME_PARAM, REPORTING_PERIOD_TYPE_PARAM, IS_PENDING) 
VALUES ('export_amp_metrics', '2016/06/12', '2016/06/18', 'WEEKLY', '1');


