--Form Table Create and xfer

CREATE TABLE CORP_ETL_MFB_FORM_STG_NEW 
tablespace MAXDAT_DATA parallel
as
select * 
from CORP_ETL_MFB_FORM_STG
where (DOC_COUNT > 0
    OR REJECTED_DOCS > 0
	OR PAGES > 0
	OR REJECTED_PAGES > 0
	OR COMPLETED_DOCS > 0
	OR COMPLETED_PAGES > 0
	);

alter table CORP_ETL_MFB_FORM_STG drop primary key;
drop index IDX_CEMFB_FORM_STG_COVERED;

Alter table CORP_ETL_MFB_FORM_STG RENAME TO CORP_ETL_MFB_FORM_STG_OLD;
Alter table CORP_ETL_MFB_FORM_STG_NEW RENAME TO CORP_ETL_MFB_FORM_STG;

alter table CORP_ETL_MFB_FORM_STG add constraint CEMFBFS_ID_PK primary key (CEMFBF_ID) using index tablespace MAXDAT_INDX; 

create index IDX_CEMFB_FORM_STG_COVERED on CORP_ETL_MFB_FORM_STG (FORM_TYPE_ENTRY_ID, TYPE_NAME, DOC_CLASS_NAME, DOC_COUNT, REJECTED_DOCS, PAGES, REJECTED_PAGES, COMPLETED_DOCS, COMPLETED_PAGES) online tablespace MAXDAT_INDX parallel compute statistics;

grant select on CORP_ETL_MFB_FORM_STG to MAXDAT_READ_ONLY; 

execute MAXDAT_ADMIN.GATHER_TABLE_STATS('MAXDAT','CORP_ETL_MFB_FORM_STG',4);
