ALTER SESSION SET CURRENT_SCHEMA = CISCO_ENTERPRISE_CC;

CREATE TABLE CC_HCO_F_V2_CALL
  (
    F_V2_CALL_ID  		NUMBER (19) ,
    DATETIME                    DATE ,
    D_DATE_ID                   NUMBER (19)  ,
    CALLTYPE_REPORTING_DATETIME      DATE,
    D_CONTACT_QUEUE_ID          NUMBER (19),
    QUEUE_NUMBER                NUMBER (19),
    D_AGENT_ID			NUMBER(19) , 
    D_PROGRAM_ID		NUMBER,
    D_PROJECT_ID		NUMBER,
    AGENT_LOGIN_ID		VARCHAR2(50),
    ROUTER_CALL_KEY_DAY         NUMBER(19),
    ROUTER_CALL_KEY             NUMBER(19),
    PERIPHERAL_CALL_KEY         NUMBER(19),
    PERIPHERAL_CALL_TYPE        NUMBER(19),
    PERIPHERAL_ID               NUMBER(19) ,
    SKILL_GROUP_ID              NUMBER(19),
    PRECISION_QUEUE_ID          NUMBER(19),
    SOURCE_D_AGENT_ID           NUMBER(19),
    SOURCE_AGENT_LOGIN_ID       VARCHAR2(50),
    CALL_REFERENCE_ID		VARCHAR2(50),
    CALLGUID                    VARCHAR2(50),
    CALL_SEGMENT_ID		VARCHAR2(50), 
    SOURCE_CALL_ID		VARCHAR2(40), 
    ACTIVITY_ID			VARCHAR2(50), 
    DIGITS_DIALED               VARCHAR2(50),
    ANI_PHONE_NUMBER            VARCHAR2(50), 
    CALL_DISPOSITION            NUMBER(19) ,
    CALL_DISPOSITION_DESC	VARCHAR2(200),
    CALL_DISPOSITION_FLAG       NUMBER(19),
    CALL_DISPOSITION_FLG_DESC	VARCHAR2(50),
    DNIS			VARCHAR2(30),
    LANGUAGE			VARCHAR2(50),
    QUEUE_TIME_SECONDS          NUMBER(11,2), --  NETWORK_SKILL_GROUP_Q_TIME
    RING_TIME_SECONDS  		NUMBER(11,2),
    HOLD_TIME_SECONDS           NUMBER(11,2),
    WORK_TIME_SECONDS	        NUMBER(11,2),
    TALK_TIME_SECONDS           NUMBER(11,2),
    IVR_TIME_SECONDS  		NUMBER(11,2), -- NET_Q_TIME
    NETWORK_TIME_SECONDS        NUMBER(11,2),
    LOCAL_Q_TIME_SECONDS        NUMBER(11,2), -- LOCAL_Q_TIME
    DELAY_TIME_SECONDS          NUMBER(11,2), -- DELAY_TIME
    TIME_TO_ABAND_SECONDS       NUMBER(11,2), -- TIME_TO_ABAND
    CALL_DURATION		NUMBER,
    TRANSFER_TO			VARCHAR2(200),
    XFERRED_OUT_FLAG		VARCHAR2(1),
    VOICEMAIL_FLAG		VARCHAR2(1),
    CALL_ABANDONED_FLAG         NUMBER(1),
    CALL_OFFERED_FLAG		NUMBER,
    CALL_ANSWERED_FLAG		NUMBER,
    CALL_BUSY_FLAG              NUMBER,
    CALL_DROPPED_FLAG           NUMBER,
    CALL_HANDLE_METHOD          VARCHAR2(50),
    CALL_DIAL_METHOD            VARCHAR2(50),
    CALL_SEGMENT_END_DT		DATE, 
    CUSTOMER_ACCOUNT_NUMBER	VARCHAR2(128),
    CREATE_DATE                 DATE ,
    LAST_UPDATE_DATE            DATE  ,
    LAST_UPDATED_BY 		VARCHAR2(30) 
  ) ;
  

  CREATE INDEX CC_HCO_F_V2_CALL_IDX0 ON CC_HCO_F_V2_CALL
          (
            D_DATE_ID ASC
      ) ;
    
/*    ALTER TABLE CC_HCO_F_V2_CALL ADD CONSTRAINT CC_HCO_F_V2_CALL_ID_PK PRIMARY KEY
    (
      F_V2_CALL_ID
    )
    ;
    
    */
    
    grant select, on commit refresh
    on CC_HCO_F_V2_CALL 
    to MAXDAT_READ_ONLY ;
    
    CREATE MATERIALIZED VIEW LOG ON CC_HCO_F_V2_CALL WITH ROWID;