RENAME  NYHX_ETL_COMPL_INCIDENTS_OLTP TO CORP_ETL_COMPL_INCIDENTS_OLTP;

alter table CORP_ETL_COMPL_INCIDENTS_OLTP RENAME COLUMN NECI_ID TO CECI_ID;

RENAME  NYHX_ETL_COMPL_INCIDN_WIP_BPM TO CORP_ETL_COMPL_INCIDN_WIP_BPM;

alter table CORP_ETL_COMPL_INCIDN_WIP_BPM RENAME COLUMN NECI_ID TO CECI_ID;