CREATE TABLE CC_C_CAMPAIGN
  (
    CAMPAIGN_ID NUMBER(19) NOT NULL,
    CAMPAIGN_NAME VARCHAR2(50) NOT NULL,
    CAMPAIGN_DESC VARCHAR2(255),
    PROJECT_NAME VARCHAR2(50) NOT NULL,  
    PROGRAM_NAME VARCHAR2(50) NOT NULL,  
    REGION_NAME VARCHAR2(50) NOT NULL,   
    STATE_NAME VARCHAR2(50) NOT NULL,    
    PROVINCE_NAME VARCHAR2(50) NOT NULL,   
    DISTRICT_NAME VARCHAR2(50) NOT NULL,    
    COUNTRY_NAME VARCHAR2(50) NOT NULL, 
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL ,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL ,
    LAST_UPDATED_BY VARCHAR2(30)
  ) ;

CREATE INDEX CC_C_CAMPAIGN_IDX1 ON CC_C_CAMPAIGN
(
  PROJECT_NAME
) 
;
      
CREATE INDEX CC_C_CAMPAIGN_IDX2 ON CC_C_CAMPAIGN
(
  PROGRAM_NAME
) 
;
  
ALTER TABLE CC_C_CAMPAIGN ADD CONSTRAINT CC_C_CAMPAIGN_PK PRIMARY KEY
(
  CAMPAIGN_ID
)
;


CREATE OR REPLACE TRIGGER BIU_CC_C_CAMPAIGN
      BEFORE INSERT OR UPDATE ON CC_C_CAMPAIGN
      FOR EACH ROW 
  BEGIN 
  IF INSERTING THEN 
            :NEW.CREATE_DATE := SYSDATE;
  END IF;
  :NEW.LAST_UPDATE_DATE := SYSDATE;
  :NEW.LAST_UPDATED_BY := USER;
  END; 
  / 


CREATE TABLE CC_C_CALL_RESULT_LKUP  
  (
  CALL_RESULT_CODE NUMBER(19) NOT NULL,
  CALL_RESULT_DESC VARCHAR2(200) NOT NULL,
  CREATE_DATE      DATE DEFAULT SYSDATE NOT NULL ,
  LAST_UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL ,
  LAST_UPDATED_BY  VARCHAR2(30)
  ) ;
  
ALTER TABLE  CC_C_CALL_RESULT_LKUP ADD CONSTRAINT CC_C_CALL_RESULT_LKUP_PK PRIMARY KEY
(
  CALL_RESULT_CODE
)
;

CREATE OR REPLACE TRIGGER BIU_CC_C_CALL_RESULT_LKUP
      BEFORE INSERT OR UPDATE ON CC_C_CALL_RESULT_LKUP
      FOR EACH ROW 
  BEGIN 
  IF INSERTING THEN 
            :NEW.CREATE_DATE := SYSDATE;
  END IF;
  :NEW.LAST_UPDATE_DATE := SYSDATE;
  :NEW.LAST_UPDATED_BY := USER;
  END; 
  /     
  
CREATE TABLE CC_C_DIALING_MODE_LKUP
  (
  DIAL_MODE_CODE NUMBER(19) NOT NULL,
  DIAL_MODE_DESC VARCHAR2(50) NOT NULL,
  CREATE_DATE      DATE DEFAULT SYSDATE NOT NULL ,
  LAST_UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL ,
  LAST_UPDATED_BY  VARCHAR2(30)
  ) ;
  
ALTER TABLE CC_C_DIALING_MODE_LKUP ADD CONSTRAINT CC_C_DIALING_MODE_LKUP_PK PRIMARY KEY
(
  DIAL_MODE_CODE
)
;

CREATE OR REPLACE TRIGGER BIU_CC_C_DIALING_MODE_LKUP
      BEFORE INSERT OR UPDATE ON CC_C_DIALING_MODE_LKUP
      FOR EACH ROW 
  BEGIN 
  IF INSERTING THEN 
            :NEW.CREATE_DATE := SYSDATE;
  END IF;
  :NEW.LAST_UPDATE_DATE := SYSDATE;
  :NEW.LAST_UPDATED_BY := USER;
  END; 
  / 

 CREATE OR REPLACE VIEW CC_C_CAMPAIGN_SV
 AS
 SELECT
CAMPAIGN_ID
,CAMPAIGN_NAME
,CAMPAIGN_DESC
,PROGRAM_NAME
,PROJECT_NAME
,PROVINCE_NAME
,DISTRICT_NAME
,REGION_NAME
,STATE_NAME
,COUNTRY_NAME
FROM CC_C_CAMPAIGN;

GRANT SELECT ON CC_C_CAMPAIGN_SV TO MAXDAT_READ_ONLY;   