DELETE FROM CC_F_ACTUALS_QUEUE_INTERVAL WHERE D_CONTACT_QUEUE_ID =299 and F_CALL_CENTER_ACTLS_INTRVL_ID in (58975,58976);

INSERT INTO CC_L_PATCH_LOG ( PATCH_VERSION , SCRIPT_SEQUENCE , SCRIPT_NAME)
VALUES ('0.5.2','101','101_MAXDAT_DELETE_FACTS_QUEUE');

COMMIT;