--rename existing fact table

ALTER TABLE CC_F_V2_CALL
  RENAME TO CC_F_V2_CALL_ORIG;
  
--create new Fact table with partition
 
CREATE TABLE CC_F_V2_CALL
  (
    F_V2_CALL_ID  		NUMBER (19) NOT NULL ,
    DATETIME                    DATE NOT NULL ,
    D_DATE_ID                   NUMBER (19) NOT NULL ,
    CALLTYPE_REPORTING_DATETIME                   DATE,
    D_CONTACT_QUEUE_ID          NUMBER (19),
    QUEUE_NUMBER                NUMBER (19),
    D_AGENT_ID			NUMBER(19) , 
    AGENT_LOGIN_ID		VARCHAR2(50),
    ROUTER_CALL_KEY_DAY         NUMBER(19),
    ROUTER_CALL_KEY             NUMBER(19),
    PERIPHERAL_CALL_KEY         NUMBER(19),
    PERIPHERAL_CALL_TYPE        NUMBER(19),
    PERIPHERAL_ID               NUMBER(19) NOT NULL,
    SKILL_GROUP_ID              NUMBER(19),
    PRECISION_QUEUE_ID          NUMBER(19),
    SOURCE_D_AGENT_ID           NUMBER(19),
    SOURCE_AGENT_LOGIN_ID       VARCHAR2(50),
    CALL_REFERENCE_ID		VARCHAR2(50),
    CALLGUID                    VARCHAR2(50),
    CALL_SEGMENT_ID		VARCHAR2(50), -- no mapping
    SOURCE_CALL_ID		VARCHAR2(40), -- no mapping
    ACTIVITY_ID			VARCHAR2(50), -- no mapping
    DIGITS_DIALED               VARCHAR2(50),
    ANI_PHONE_NUMBER            VARCHAR2(50), 
    CALL_DISPOSITION            NUMBER(19) NOT NULL,
    CALL_DISPOSITION_FLAG       NUMBER(19),
    DNIS			VARCHAR2(30),
    LANGUAGE			VARCHAR2(50),
    QUEUE_TIME_SECONDS          NUMBER(11,2), --  NETWORK_SKILL_GROUP_Q_TIME
    RING_TIME_SECONDS  		NUMBER(11,2),
    HOLD_TIME_SECONDS           NUMBER(11,2),
    WORK_TIME_SECONDS	        NUMBER(11,2),
    TALK_TIME_SECONDS           NUMBER(11,2),
    IVR_TIME_SECONDS  		NUMBER(11,2), -- NET_Q_TIME
    NETWORK_TIME_SECONDS        NUMBER(11,2),
    LOCAL_Q_TIME_SECONDS        NUMBER(11,2), -- LOCAL_Q_TIME
    DELAY_TIME_SECONDS          NUMBER(11,2), -- DELAY_TIME
    TIME_TO_ABAND_SECONDS       NUMBER(11,2), -- TIME_TO_ABAND
    CALL_DURATION		NUMBER,
    TRANSFER_TO			VARCHAR2(200),
    XFERRED_OUT_FLAG		VARCHAR2(1),
    VOICEMAIL_FLAG		VARCHAR2(1),
    CALL_ABANDONED_FLAG         NUMBER(1),
    CALL_OFFERED_FLAG		NUMBER,
    CALL_ANSWERED_FLAG		NUMBER,
    CALL_BUSY_FLAG              NUMBER,
    CALL_DROPPED_FLAG           NUMBER,
    CALL_HANDLE_METHOD          VARCHAR2(50),
    CALL_DIAL_METHOD            VARCHAR2(50),
    CALL_SEGMENT_END_DT		DATE, -- no mapping
    CREATE_DATE                 DATE DEFAULT SYSDATE NOT NULL,
    LAST_UPDATE_DATE            DATE DEFAULT SYSDATE NOT NULL ,
    LAST_UPDATED_BY 		VARCHAR2(30) NOT NULL
  )
  PARTITION BY LIST (D_DATE_ID) AUTOMATIC 
  (partition cfv2c_partition_init values (1));
  
-- insert data from renamed fact table to new fact table

ALTER TABLE CC_F_V2_CALL NOLOGGING;

INSERT /*+ PARALLEL(4) */ INTO CC_F_V2_CALL (
F_V2_CALL_ID
,DATETIME
,D_DATE_ID
,D_CONTACT_QUEUE_ID
,QUEUE_NUMBER
,D_AGENT_ID
,AGENT_LOGIN_ID
,ROUTER_CALL_KEY_DAY
,ROUTER_CALL_KEY
,PERIPHERAL_CALL_KEY
,PERIPHERAL_CALL_TYPE
,PERIPHERAL_ID
,SKILL_GROUP_ID
,PRECISION_QUEUE_ID
,SOURCE_D_AGENT_ID
,SOURCE_AGENT_LOGIN_ID
,CALL_REFERENCE_ID
,CALLGUID
,CALL_SEGMENT_ID
,SOURCE_CALL_ID
,ACTIVITY_ID
,DIGITS_DIALED
,ANI_PHONE_NUMBER
,CALL_DISPOSITION
,CALL_DISPOSITION_FLAG
,DNIS
,LANGUAGE
,QUEUE_TIME_SECONDS
,RING_TIME_SECONDS
,HOLD_TIME_SECONDS
,WORK_TIME_SECONDS
,TALK_TIME_SECONDS
,IVR_TIME_SECONDS
,NETWORK_TIME_SECONDS
,LOCAL_Q_TIME_SECONDS
,DELAY_TIME_SECONDS
,TIME_TO_ABAND_SECONDS
,CALL_DURATION
,TRANSFER_TO
,XFERRED_OUT_FLAG
,VOICEMAIL_FLAG
,CALL_ABANDONED_FLAG
,CALL_OFFERED_FLAG
,CALL_ANSWERED_FLAG
,CALL_BUSY_FLAG
,CALL_DROPPED_FLAG
,CALL_HANDLE_METHOD
,CALL_DIAL_METHOD
,CALL_SEGMENT_END_DT
,CREATE_DATE
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,CALLTYPE_REPORTING_DATETIME
)
SELECT /*+ PARALLEL(4) */ 
F_V2_CALL_ID
,DATETIME
,D_DATE_ID
,D_CONTACT_QUEUE_ID
,QUEUE_NUMBER
,D_AGENT_ID
,AGENT_LOGIN_ID
,ROUTER_CALL_KEY_DAY
,ROUTER_CALL_KEY
,PERIPHERAL_CALL_KEY
,PERIPHERAL_CALL_TYPE
,PERIPHERAL_ID
,SKILL_GROUP_ID
,PRECISION_QUEUE_ID
,SOURCE_D_AGENT_ID
,SOURCE_AGENT_LOGIN_ID
,CALL_REFERENCE_ID
,CALLGUID
,CALL_SEGMENT_ID
,SOURCE_CALL_ID
,ACTIVITY_ID
,DIGITS_DIALED
,ANI_PHONE_NUMBER
,CALL_DISPOSITION
,CALL_DISPOSITION_FLAG
,DNIS
,LANGUAGE
,QUEUE_TIME_SECONDS
,RING_TIME_SECONDS
,HOLD_TIME_SECONDS
,WORK_TIME_SECONDS
,TALK_TIME_SECONDS
,IVR_TIME_SECONDS
,NETWORK_TIME_SECONDS
,LOCAL_Q_TIME_SECONDS
,DELAY_TIME_SECONDS
,TIME_TO_ABAND_SECONDS
,CALL_DURATION
,TRANSFER_TO
,XFERRED_OUT_FLAG
,VOICEMAIL_FLAG
,CALL_ABANDONED_FLAG
,CALL_OFFERED_FLAG
,CALL_ANSWERED_FLAG
,CALL_BUSY_FLAG
,CALL_DROPPED_FLAG
,CALL_HANDLE_METHOD
,CALL_DIAL_METHOD
,CALL_SEGMENT_END_DT
,CREATE_DATE
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,CALLTYPE_REPORTING_DATETIME
FROM CC_F_V2_CALL_ORIG;

commit;

ALTER TABLE CC_F_V2_CALL LOGGING;

--remove indexes, constraints & triggers on renamed table

  DROP INDEX CC_F_V2_CALL_IDX1;
      
  DROP INDEX CC_F_V2_CALL_IDX2;
    
  DROP INDEX CC_F_V2_CALL_IDX3;
      
  DROP INDEX CC_F_V2_CALL_IDX4;
      
  DROP INDEX CC_F_V2_CALL_IDX5;
      
  DROP INDEX CC_F_V2_CALL_IDX6;
  
  DROP INDEX CC_F_V2_CALL_IDX7;

  DROP INDEX CC_F_V2_CALL_IDX8;
  
  DROP INDEX CC_F_V2_CALL_IDX9;

  ALTER TABLE CC_F_V2_CALL_ORIG DROP CONSTRAINT CC_F_V2_CALL_PK;

  ALTER TABLE CC_F_V2_CALL_ORIG DROP CONSTRAINT F_V2_CALL_D_CNTCT_Q_FK;
    
  ALTER TABLE CC_F_V2_CALL_ORIG DROP CONSTRAINT F_V2_CALL_D_AGENT_FK;
       
  ALTER TABLE CC_F_V2_CALL_ORIG DROP CONSTRAINT CC_F_V2_CALL__UN; 
  
  DROP TRIGGER BIU_CC_F_V2_CALL;
    
-- add indexes, constraints & triggers to new table
  
  CREATE INDEX CC_F_V2_CALL_IDX1 ON CC_F_V2_CALL
      (
        D_CONTACT_QUEUE_ID ASC
      ) ;
      
  CREATE INDEX CC_F_V2_CALL_IDX2 ON CC_F_V2_CALL
            (
              D_AGENT_ID ASC
      ) ;
    
  CREATE INDEX CC_F_V2_CALL_IDX3 ON CC_F_V2_CALL
          (
            QUEUE_NUMBER ASC
      ) ;
      
  CREATE INDEX CC_F_V2_CALL_IDX4 ON CC_F_V2_CALL
          (
            AGENT_LOGIN_ID ASC
      ) ;  
      
  CREATE INDEX CC_F_V2_CALL_IDX5 ON CC_F_V2_CALL
          (
            ROUTER_CALL_KEY_DAY ASC
      ) ;   
      
  CREATE INDEX CC_F_V2_CALL_IDX6 ON CC_F_V2_CALL
          (
            ROUTER_CALL_KEY ASC
      ) ;    
  
  CREATE INDEX CC_F_V2_CALL_IDX7 ON CC_F_V2_CALL
            (
              CALL_DISPOSITION ASC
      ) ; 
  CREATE INDEX CC_F_V2_CALL_IDX8 ON CC_F_V2_CALL
            (
              CALL_DISPOSITION_FLAG ASC
      ) ;   
  
  CREATE INDEX CC_F_V2_CALL_IDX9 ON CC_F_V2_CALL
          (
            D_DATE_ID ASC
      ) ;
    
    ALTER TABLE CC_F_V2_CALL ADD CONSTRAINT CC_F_V2_CALL_PK PRIMARY KEY
    (
      F_V2_CALL_ID
    )
    ;
    
    ALTER TABLE CC_F_V2_CALL ADD CONSTRAINT F_V2_CALL_D_CNTCT_Q_FK FOREIGN KEY ( D_CONTACT_QUEUE_ID ) REFERENCES CC_D_CONTACT_QUEUE ( D_CONTACT_QUEUE_ID ) NOT DEFERRABLE ;
    
    ALTER TABLE CC_F_V2_CALL ADD CONSTRAINT F_V2_CALL_D_AGENT_FK FOREIGN KEY ( D_AGENT_ID ) REFERENCES CC_D_AGENT ( D_AGENT_ID ) NOT DEFERRABLE ;
       
    ALTER TABLE CC_F_V2_CALL ADD CONSTRAINT CC_F_V2_CALL__UN UNIQUE
    (
      DATETIME 
      , CALLTYPE_REPORTING_DATETIME
      , ROUTER_CALL_KEY_DAY
      , ROUTER_CALL_KEY
      , PERIPHERAL_CALL_KEY         
      , PERIPHERAL_CALL_TYPE        
      , PERIPHERAL_ID  
      , QUEUE_NUMBER
      , AGENT_LOGIN_ID
      , SOURCE_AGENT_LOGIN_ID
      , SKILL_GROUP_ID
      , PRECISION_QUEUE_ID
      , DIGITS_DIALED
      , ANI_PHONE_NUMBER
      , DNIS
      , CALL_DISPOSITION
      , CALL_DISPOSITION_FLAG
      , CALL_REFERENCE_ID
      , CALLGUID
    )
    ;  
    
  CREATE OR REPLACE TRIGGER BIU_CC_F_V2_CALL
      BEFORE INSERT OR UPDATE ON CC_F_V2_CALL
      FOR EACH ROW 
  BEGIN 
  IF INSERTING AND :NEW.F_V2_CALL_ID IS NULL THEN 
            SELECT SEQ_CC_F_V2_CALL.NEXTVAL INTO :NEW.F_V2_CALL_ID FROM DUAL;
  END IF;
  IF INSERTING THEN 
            :NEW.CREATE_DATE := SYSDATE;
  END IF;
  :NEW.LAST_UPDATE_DATE := SYSDATE;
  :NEW.LAST_UPDATED_BY := USER;
  END; 
   
/     
